### ISSUE TITLE
Files transferred with content-encoding: gzip should be decompressed

### ISSUE THREAD

**Issue by larkin** [bower/bower#1004]
When you install a file from an url endpoint and that file is served gzipped, bower downloads the file but does not remove the content-encoding.  The resulting file has to be manually decompressed before it can be used in build scripts / etc.

Ideally, this would be handled by @mikeal/request, but it looks like that is delayed by compatibility issues.  Related issue & proposed snippet for handling content-encoding can be found here:  https://github.com/mikeal/request/issues/539#issuecomment-17351112

I think the best place to implement this would be in urlResolver.js, or is there a better place for this to go?

**Comment by mpolichette** [comment]
Are there any updates on this issue? Was this fixed in 1.4?

**Comment by razorman8669** [comment]
:+1: having an issue with gzipped js files stored in S3 and would love to have the ability to reference them from bower.

**Comment by sheerun** [comment]
Bower is deprecated and in maintenance mode, so we won't implement new features like this one. We recommend switching to yarn and migrating legacy projects to it with [bower-away](https://github.com/sheerun/bower-away)
