### ISSUE TITLE
Optionally automate resolution of suitable package version during install

### ISSUE THREAD

**Issue by caitp** [bower/bower#1007]
I'm interested in writing a [karma](https://github.com/karma-runner/karma) plugin which will install bower dependencies for a test suite before running it, so that external components need not be checked into the tree, and can be tested against multiple versions to ensure that breaking changes between versions of components don't wreck the app.

This generally works great, with one issue:

If a package has already been installed in a given directory in one version, trying to install it with a different version introduces a conflict, and the package will not be installed.

So, for robotic programs which need to do this sort of work, it would be nice to have an automatic "best guess" suitable version resolver.

My thinking is:

If the target version is a clean semver, simply look for an exact match,
otherwise if it's a range, look for the highest semver matching the range,
otherwise complain/throw.

I think this seems reasonable, and I've been poking around seeing how a patch would look to make this work.

Are there any problems with it?

---

Also, it seems weird that installing a different version of a module constitutes a conflict, when there are no other modules or dependencies being looked at (my test case is only installing different versions of AngularJS).

How exactly does that constitute a conflict when there are no incompatible dependencies?

**Comment by sheerun** [comment]
Would be solved by #578 if implemented
