### ISSUE TITLE
Non-interactive installation prompts for git password

### ISSUE THREAD

**Issue by pornel** [bower/bower#1009]
```
$ node
> require('bower').commands.install(['https://github.com/examplebrokenurl/doesnotexist.git'], {}, {interactive:false});
{ _interceptors: [], _piped: [] }
> Username for 'https://github.com':
```

The `git` child process can show its own interactive prompt at any time (e.g. git interprets 404 on github as authentication error and wants to retry with a password).

To prevent this you can run `git` with:

     git -c core.askpass=true …

`true` here is not a boolean value, but a command `/bin/true` that will make git think it asked for a password.

**Comment by sheerun** [comment]
I think `true` won't work on Windows..

**Comment by shurcooL** [comment]
@sheerun, according to commit message of https://github.com/svn2github/chromium-depot-tools/commit/cc130b9f4df1fd7fd10599d2880f60d82267557f:

> 'true' is available in the msys distribution.

**Comment by sheerun** [comment]
Bower also supports non-msys installation

**Comment by shurcooL** [comment]
Well, another way, if git version 2.3 or later is used, is to use `GIT_TERMINAL_PROMPT` environment variable.

**Comment by sheerun** [comment]
Maybe we can do both, with platform detection :)
