### ISSUE TITLE
`bower validate`

### ISSUE THREAD

**Issue by sindresorhus** [bower/bower#1014]
We already do some validation check on `bower register`, but it's going to be more checks and would be nice for people to be able to run it while developing and not only on registering.

**Comment by zzarcon** [comment]
Which is the status of this?

**Comment by ruyadorno** [comment]
`abandoned` :disappointed:

**Comment by zzarcon** [comment]
@ruyadorno I'd like to work into this with someone. 
@sheerun which is the priority of this?

**Comment by ruyadorno** [comment]
@zzarcon please go ahead :smile: 

take a look at #1145 and the discussion that ensued there, you'll see that the proper way to implement this feature is to add a `validate()` method on [bower-json](https://github.com/bower/json) first and once that's available, just create a command on `bower` that consumes it to parse/output validation info to the user.

wish you the best of luck with that :+1: great to see people taking over the awesome work from bower :tada:

**Comment by sheerun** [comment]
@zzarcon bower-json uses excptions in `validate` method. First we need to make `validateWarnings` method that returns all the warnings, so we can return them in `bower validate` command. You can certainly work on it :)

**Comment by sheerun** [comment]
Here's link to validate method: https://github.com/bower/json/blob/master/lib/json.js#L87

**Comment by sheerun** [comment]
Bower is deprecated and doesn't allow registering new packages anymore, so I'm closing this
