### ISSUE TITLE
New URL Scheme

### ISSUE THREAD

**Issue by rwjblue** [bower/bower#1015]
## The `git` Problem

Currently, for a project to use (what I consider) the best features of Bower (dependency management, and versioning support) you are basically limited to using `git` as a transport. `git` is a wonderful version control system, but I feel that it is not a great mechanism for distributing "compiled" assets. One of the main issues is that with a project of any significant size it will likely be stored in a number of smaller files within the repo, and require a build stage to compile those files into the final product.  Using `git` to store those assets either requires updating the final build file on each change or maintaining a separate repo to be used as a "shim" repo (holding only the final assets).  Both of these options are tedious at best, and bad practice at worst.
## The Other Options
- Single file (by specifying the file needed to download directly in the `bower.json` via its URL) doesn't offer the 
  ability to handle dependency management (since no `bower.json` can be specified). This means that the consuming
  project must manually add the dependencies into its own `bower.json`.
- Tarballs can be used to provide all files needed by the project (including `bower.json` for dependency management),
  but it doesn't allow for automatic project versioning (since it requires specifying the exact URL for the
  `tar.gz`/`zip` file). This means that the consuming project must update the URL specified whenever it wants a new
  version, and any dependencies must manually specify the `tar.gz` URL that it depends on which could cause a conflict
  that isn't as simple to identify as a version number conflict would be.
## Proposal

I propose that we decide on a URL scheme that can be used in the registry that will allow consumers to simply specify the package version required (exactly as you can with `git` registered packages).  A rough idea of this follows.
1. The following would be setup in the main bower registry for a new package:
   `https://some.base.domain.com/random/base/url/`
2. The bower command line client would look in the following URL for a listing of package versions (a simple JSON array of version strings):
   `https://some.base.domain.com/random/base/url/<package-name>-versions.json`
3. The command line client can then use its current internal logic to determine which version (from the list of available versions) should be used.
4. The bower client would download the tarball using the following URL scheme:
   `https://some.base.domain.com/random/base/url/<package-name>-<package-version>.tar.gz`

So assuming that I wanted to download version 1.2.0 of the package registered as `ember` and a base URL of `http://builds.emberjs.com/bower/` the following URLs would be used:

`http://builds.emberjs.com/bower/ember-versions.json`
`http://builds.emberjs.com/bower/ember-1.2.0.tar.gz`
## Summary
- This schema would allow project maintainers to simply automate the generation of the tarballs, and publish them to any webserver (probably the most significant would be S3).  
- Final build assets would not be required to be stored in the main repo.
- Project maintainers would not need to keep a separate "shim" repo up to date.
- Consumers can simply specify project name and require version, just like any project currently registered with `git`.

I would be happy to work on implementing this feature if it is accepted.

**EDIT 2013/12/16**

We could also auto-detect a base url of `http://github.com/` and use their releases API (instead of using the tags) which provides the ability to upload comiled assets via tar.gz.  This would allow folks to actually host the build assets on Github (and not need a custom web-server/S3 setup).

**Comment by sheerun** [comment]
Bower is deprecated and doesn't allow registering new packages anymore, so I'm closing this
