### ISSUE TITLE
bowerrc not respected

### ISSUE THREAD

**Issue by kirkstrobeck** [bower/bower#102]
I have a `.bowerrc` file in my mac home folder ( `cd ~`) with the contents

    {
      "directory" : "assets/components"
    }

but it still uses the directory `./components`

**Comment by vdeep** [comment]
Having the same issue. Bower - 1.4.1, node - 0.12.0.

**Comment by bevinhex** [comment]
Same issue here, using linux mint, bower 1.7.1
Not using ~/.bowerrc, if I create it in project folder it works,  but never uses home folder

**Comment by sheerun** [comment]
Works for me on 1.7.1.. Can you post your full environment? (bower version, node version, os version)

**Comment by bevinhex** [comment]
-> nodejs -v
v4.2.3
uname -a
Linux bevin-silent 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Lin
bower -v
1.7.1

**Comment by sheerun** [comment]
@bevinhex Could you post the directory of the project, contents of .bowerrc? Do you use sudo for bower?

**Comment by bevinhex** [comment]
```
-> cat .bowerrc 
{
	"directory":"lib"
}
```
I don't use sudo for bower, bower installed using
```npm -g install bower```

**Comment by sheerun** [comment]
@bower/contributors We need to investigate this. Can anyone confirm it?

**Comment by bevinhex** [comment]
I'll try it in another computer when I go to office, then paste the result

**Comment by pertrai1** [comment]
@bower/contributors 

I have taken the steps to try to reproduce the issue and here are my findings:

```
~ node -v
v4.1.2
~ uname -a
Darwin robpro-3.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; 
root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64
~ bower -v
1.6.5
```

Created a `.bowerrc` file in home directory

```
{
    "directory":  "assets/components"
}
```

Then ran:

```
bower install jquery
bower cached        git://github.com/jquery/jquery.git#2.1.4
bower validate      2.1.4 against git://github.com/jquery/jquery.git#*
bower install       jquery#2.1.4
```

Ran `ls -la` and there is no `assets/components` directory.

I then created a `testing` directory in home folder. Changed `.bowerrc` to the following:

```
{
   "directory": "testing/components"
}
```

Ran `bower install jquery` again from home directory:

```
bower install jquery
bower cached        git://github.com/jquery/jquery.git#2.1.4
bower validate      2.1.4 against git://github.com/jquery/jquery.git#*
bower install       jquery#2.1.4

jquery#2.1.4 testing/components/jquery
```

The outcome of my testing is that the `.bowerrc` with the directory `assets` was not created, but the one with the name `testing` was created as you can see above.

**Comment by paulohp** [comment]
Since I'm working on #1986, I can take a look on this one.

**Comment by sheerun** [comment]
So it's also an issue on Darwin... @paulohp We need to create failing test for it.

**Comment by samy100** [comment]
Exact same issue here on MAC OSX 10.9:
```
node -v
v4.2.3

npm -v
2.14.7

bower -v
1.7.1

cat .bowerrc
{
  "directory": "app/static/assets/libs",
  "interactive": true,
  "analytics": false
}

**Comment by sheerun** [comment]
1.7.3 should work. If not, please open create a failing test and send PR with it
