### ISSUE TITLE
(git) fatal: working tree xxx already exists

### ISSUE THREAD

**Issue by binarykitchen** [bower/bower#1033]
When installing https://github.com/gamtiq/extend with `bower install` on the server through a bare repo, I am getting this error:

```
bower extend#*                               checkout master
bower extend#*                                ECMDERR Failed to execute "git clone git://github.com/gamtiq/extend.git -b master --progress . --depth 1", exit code of #128

Additional error details:
fatal: working tree '/var/www/signdna/staging' already exists.
```

the whole script is run by a git hook where these commands are run before the above:

```
export GIT_WORK_TREE="/var/www/signdna/staging"

cd /home/signdna/signdna.git
git fetch
git checkout -f staging
```

No idea what's wrong here. Any clues?

**Comment by dlee** [comment]
I am also running into this issue when running `bower install` in a git alias.

I think there might be a solution in `git` itself for this: http://article.gmane.org/gmane.comp.version-control.git/281960
