### ISSUE TITLE
Version dependency resolution is broken

### ISSUE THREAD

**Issue by chrisirhc** [bower/bower#1037]
## Case 1:

To reproduce, create a new directory and run in the terminal:

```
$ bower install angular-mocks#~1.0.8
$ bower install angular-mocks#~1.2.7
```
### Result

bower fails to find a suitable version of angular on the second command.

![screen shot 2014-01-08 at 2 30 24 am](https://f.cloud.github.com/assets/132584/1867475/2fd41aa2-7850-11e3-98fa-25f5ded739a5.png)
### Expected behavior

bower should proceed with the 1.2.8 prerelease version (I'm aware that this resolution to a pre-release version is another bug that has been filed as an issue). My bower.json has no dependencies at all, so the `and has UI Bootstrap as dependants` is not possible.

---
## Case 2:
1. Run:

```
    $ bower install angular-mocks#~1.0.8
```
1. Add a bower.json with:

```
{
  "name": "App",
  "devDependencies": {
    "angular-mocks": "~1.2.7"
  }
}
```
1. Run:

```
    $ bower install
```
### Result

Unable to find suitable version of angular.
![screen shot 2014-01-08 at 2 51 23 am](https://f.cloud.github.com/assets/132584/1867598/d9c29b22-7852-11e3-8683-61d4664ede18.png)
### Expected behavior

bower should ignore angular-mock#1.0.8's dependencies because it's about to be upgraded anyway. angular-mock#1.0.8's dependencies should not affect the decision in picking a version.

**Comment by benjiwheeler** [comment]
Is there any chance that bower dependency resolution might be nondeterministic even when starting wth a clean cache and empty bower_components? I seem to be experiencing that!

(Asking here because it seems most relevant place)

**Comment by samccone** [comment]
@benjiwheeler mind opening a new issue with a test case?

**Comment by benjiwheeler** [comment]
Yes! Trying to get problem to recur reliably! ...

**Comment by sheerun** [comment]
@benjiwheeler Maybe at the same time you could send PR for https://github.com/bower/bower/issues/780 ?
