### ISSUE TITLE
`--save` by default

### ISSUE THREAD

**Issue by sindresorhus** [bower/bower#1040]
Since most people would want to save a dependency to bower.json when doing `bower install <package>` I suggest we make `--save` the default and introduce a `--no-save` flag. The default will only have an effect if there is a bower.json.

**Comment by tannerhodges** [comment]
:+1:

**Comment by legshooter** [comment]
:+1:

**Comment by automatix** [comment]
+1 for `save-by-default`/`save-dev-by-default` (`true`|`false`, default = `false`) and `--no-save`/`--no-save-dev`.

**Comment by vedmant** [comment]
:+1:  I'm for this feature! Often forget to add --save, mostly I install package and want to save it to bower.json.

**Comment by fewspider** [comment]
👍

**Comment by svengt** [comment]
I would suggest to make this configurable like npm does.
```
$ npm config set save=true
$ npm config set save-exact=true
```
http://blog.heroku.com/archives/2015/11/10/node-habits-2016#2-use-a-smart-npmrc

**Comment by sheerun** [comment]
Good idea. I'll accept a PR enabling it for .bowerrc

**Comment by BenMann** [comment]
I feel like https://github.com/bower/bower/pull/2161 is not just a neat solution but also enough to close this issue.
cc: @sheerun agree?

**Comment by sheerun** [comment]
yup :)
