### ISSUE TITLE
'bower link' with command line configuration options causes bower to hang

### ISSUE THREAD

**Issue by iwebdev1** [bower/bower#1043]
Our build environment is disconnected from the Internet, so we cache bower related packages in a central location so that they are available to our various build jobs. To utilize that cache, we pass the following options into our bower command line:

--config.storage.links D:\build\bower\data\links
--config.storage.packages D:\build\bower\cache\packages
--config.storage.registry D:\build\bower\cache\registry
--config.storage.completion D:\build\bower\data\completion
--config.storage.empty D:\build\bower\data\empty

This works well for "install", but causes "link" to hang. If we do not pass the config.* options in on the command line, "link" works as expected but reads from APPDATA instead of our cache. Setting these options via the .bowerrc file works fine as well. It's only when passed in via the command line that we run into issues. 

Here's command line we are using:
node D:\build\npm\node_modules\bower\bin\bower link --config.storage.links D:\build\bower\data\links --config.storage.packages D:\build\bower\cache\packages --config.storage.registry D:\build\bower\cache\registry --config.storage.completion D:\build\bower\data\completion --config.storage.empty D:\build\bower\data\empty

When stepping through a debugger, here's what the config object looks like:
![image](https://f.cloud.github.com/assets/6379330/1895441/ed05d3be-7b2e-11e3-8a7d-36575ee3d317.png)

The issue seems to be in link.js. config.argv.remain contains the config data passed in via the command line and link is looking at that array for localName and name vars. Here's the code segment in link.js
![image](https://f.cloud.github.com/assets/6379330/1895448/5141e4a8-7b2f-11e3-8237-f5015a6804ad.png)

The work around is to call bower like this:
node debug D:\build\npm\node_modules\bower\bin\bower link . FPFramework --config.storage.links D:\build\bower\data\links --config.storage.packages D:\build\bower\cache\packages --config.storage.registry D:\build\bower\cache\registry --config.storage.completion D:\build\bower\data\completion --config.storage.empty D:\build\bower\data\empty

**Comment by sheerun** [comment]
@iwebdev1 I've added Windows CI support to Bower. I encourage you all to create failing test.

**Comment by sheerun** [comment]
Closing because of no feedback
