### ISSUE TITLE
bower search leads to ECONNREFUSED

### ISSUE THREAD

**Issue by dmitriz** [bower/bower#1049]
Running `bower search` 

leads to error:

`bower ECONNREFUSED  Request to https://bower.herokuapp.com/packages failed: connect ECONNREFUSED`

Any ideas?

I am behind proxy - can that be the reason?

**Comment by thangaapp** [comment]
leads to error:

bower ECONNREFUSED Request to https://bower.herokuapp.com/packages failed: connect ECONNREFUSED 

Getting the error when i'm install web3js command is "bower install web3"
And also I add the proxy in .bowerrc file
But Still getting the same. 
Any one idea about this one

**Comment by abhaydhar** [comment]
Getting the same error while doing npm run prep  on deeplearnjs cloned from below
git clone https://github.com/PAIR-code/deeplearnjs.git

following this -https://deeplearnjs.org/
