### ISSUE TITLE
Update command: not working at all

### ISSUE THREAD

**Issue by bdkjones** [bower/bower#1054]
## Environment:

Mac OS 10.9.1, Bower 1.2.8, Node 0.10.20
## Steps to reproduce:

1) Create a new folder on the desktop.
2) Open terminal and `cd` to your new folder.
3) Run this command: `bower install jquery#2.0.1`
4) Run `bower list` and verify that jQuery 2.0.1 is installed.
5) Run `bower update`
6) Run `bower list` and find that jQuery 2.0.1 is still installed and that Bower reports 2.0.3 as the latest available version.
## Expected Results:

After running `bower update`, jQuery 2.0.1 should be replaced with jQuery 2.0.3.
## Actual Results:

jQuery is not updated to the latest version available. 
## Extra information:
1. Adding `--force` and/or `--force-latest` has no effect. 
2. The presence of a bower.json file in the project's root folder has no effect.
3. Note that I'm using jQuery as an example --- the same issue manifests for all packages I attempt to update. 
4. I have some old projects lying around that have older versions of various libraries (jQuery, Foundation, etc) that were installed using Bower, but were installed without a specific target hashtag. That is, I did: `bower install jQuery` to get the latest version available at that time. These projects also fail to update if I run `bower update` on them.
## Other

I'm not an expert with bower, but according to every tutorial I can find online, the above process should automatically update my installed components to the latest available versions. Apologies in advance if the reason for the failure is a misunderstanding on my part.

**Comment by weisk** [comment]
+1

**Comment by franciscop** [comment]
Could @bdkjones please add the solution at the top? I had to read through all of the messages to find the fix (just running a `bower install XXX` to update the package to the last version).
