### ISSUE TITLE
Allow relative linking - i.e. `bower link ../some-module`

### ISSUE THREAD

**Issue by vjpr** [bower/bower#1058]
Just like `npm link`.

Currently it resolves the relative link in the global link dir which would never make sense:

```
bower link ../xxx
bower ENOENT        Failed to create link to xxx
.local/share/bower/links/xxx doest not exists or points to a non-existent file
```

**Comment by ciekawy** [comment]
+1

**Comment by ciekawy** [comment]
Actually I'v just found that everything works fine. Just the documentation is probably unclear since few people have same problem. 

So to create global link use just `bower link` then to use it in dependant project `bower link <global name>`

**Comment by sheerun** [comment]
Bower is deprecated and in maintenance mode, so we won't implement new features like this one. We recommend switching to yarn and migrating legacy projects to it with [bower-away](https://github.com/sheerun/bower-away)
