### ISSUE TITLE
Provide an option to not remove unecessary resolutions from bower.json

### ISSUE THREAD

**Issue by edeustace** [bower/bower#1061]
I have a bower.json like this: 

```
{
  "name": "bower-resolutions",
  "version": "0.0.1",
  "dependencies": {
    "angular": "~1.2.8"
  },
  "resolutions" : {
    "angular" : "~1.2.8"
  }
}
```

When I run `bower install` - it deletes the resolutions. However, in my build script I run `bower install` for some dynamic dependencies and I want to make use of the resolutions property to guide their installation also. So I don't want the key removed.

I'd like to be able to run: 

```
bower install --remove-unnecessary-resolutions=false 
```

So I can then run: 

```
bower install some-project  #the resolutions are intact so will help this separate install 
```

**Comment by sathran** [comment]
+1 still happening in 1.3.3

**Comment by sheerun** [comment]
1.3.3 is not latest version

**Comment by sathran** [comment]
Fair enough. When I read your "1.3.X" I assumed any 1.3.X version would have the fix.
We'll update our CI dependencies :)
Thanks.
