### ISSUE TITLE
bower ENORESTARGET  No tag found that was able to satisfy

### ISSUE THREAD

**Issue by Maddy1984** [bower/bower#1063]
Hello there,

 After googling for a couple of hours I couldn't find a solution for this.

 I'm just trying to do "bower install", but keep getting

bower not-cached    git://github.com/jrburke/requirejs.git#~2.1.8
bower resolve       git://github.com/jrburke/requirejs.git#~2.1.8
bower not-cached    git://github.com/lodash/lodash.git#~2.0.0
bower resolve       git://github.com/lodash/lodash.git#~2.0.0
bower not-cached    git://github.com/marionettejs/backbone.marionette.git#~1.1.0
bower resolve       git://github.com/marionettejs/backbone.marionette.git#~1.1.0
bower not-cached    git://github.com/marionettejs/backbone.wreqr.git#~0.2.0
bower resolve       git://github.com/marionettejs/backbone.wreqr.git#~0.2.0
bower not-cached    git://github.com/components/jquery.git#~2.0.3
bower resolve       git://github.com/components/jquery.git#~2.0.3
bower not-cached    git://github.com/marionettejs/backbone.babysitter.git#~0.0.6
bower resolve       git://github.com/marionettejs/backbone.babysitter.git#~0.0.6
bower not-cached    git://github.com/requirejs/text.git#~2.0.10
bower resolve       git://github.com/requirejs/text.git#~2.0.10
bower not-cached    git://github.com/EightMedia/hammer.js.git#1.0.5
bower resolve       git://github.com/EightMedia/hammer.js.git#1.0.5
bower not-cached    git://github.com/ftlabs/fastclick.git#~0.6.10
bower resolve       git://github.com/ftlabs/fastclick.git#~0.6.10
bower ENORESTARGET  No tag found that was able to satisfy ~0.6.10

Additional error details:
No versions found in git://github.com/ftlabs/fastclick.git

Any idea why this is happening?

Thanks in advance,
M

**Comment by haaaiiimmm** [comment]
any other solution?  we met this issue either ..   @sindresorhus 
`bower cache clean`  not work ...

sorry for my English...

**Comment by abetsagaral** [comment]
you need to update your dependencies.

**Comment by dalper01** [comment]
@Maddy1984 , did you ever find solution.

@abetsagaral , I'm getting this problem, while one of my contributors (co workers doesn't), so it doesn't seem like a dependancy problem. It seems more like another problem, something saved gobally. For example, he's using bower 1.8, I'm using 2.0.

My problem is specifically for angular-underscore. My co-worker had no issues, while for me bower gives this senseless error and suggests I use version .5. Right now it looks like Bower v 2.0 is the likely culprit. I suspect it's trying to be too clever and getting in my way.
