### ISSUE TITLE
Rewrite: `bower completion`

### ISSUE THREAD

**Issue by sindresorhus** [bower/bower#1066]
Looks like `bower completion` didn't make the rewrite: https://github.com/bower/bower/blob/3d64222655bfe04047b348c8d80e990a27c4f90a/lib/commands/completion.js#L28

PR welcome :)

**Comment by sheerun** [comment]
This is implemented externally with https://github.com/zsh-users/zsh-completions or https://github.com/miklos-martin/oh-my-zsh-plugins/blob/master/bower/bower.plugin.zsh

No need to include it in bower itself :)
