### ISSUE TITLE
Support standard npm git tag conventions

### ISSUE THREAD

**Issue by ljharb** [bower/bower#1069]
If I do `bower install foo#1.2.3`, it will check foo's git repo for the `1.2.3` tag. However, npm modules, via convention and the `npm version` command, would have a tag `v1.2.3`.

It would be ideal if bower worked automatically with that tag naming convention, so that I can stick with the "v" prefix - that should reduce friction with npm modules that want to add a `bower.json`. Otherwise, I have to create two parallel tags with each new version, which is just messy.

See https://github.com/es-shims/es5-shim/pull/171 for some context.

**Comment by joallard** [comment]
In the latest version I get this:
```
bower not-cached    git://github.com/joallard/fb-login.git#0.1.0.alpha
bower resolve       git://github.com/joallard/fb-login.git#0.1.0.alpha
bower ENORESTARGET  Tag/branch 0.1.0.alpha does not exist

Additional error details:
Available tags: v0.1.0.alpha, v0.1.0a
Available branches: master
```
