### ISSUE TITLE
How do you add bower components as requireJS modules for an r.js optimization?

### ISSUE THREAD

**Issue by PsySecCorp** [bower/bower#1093]
```
{
    options: {
        baseUrl: dir,
        mainConfigFile: dir + '/application.js',
        dir: container.getOptions().release.directories.target + '/requirejs',
        modules: [
            {
                name: 'application',
                include: modules
            }
        ]
    }
}
```

The options.modules.include contains a list of module names to build, but many bower components do not have reuiqreJS module definitions.  So while I can access the bower components this way in a pre-build environment...

```
require.config({
    paths: {
        "requirejs.text": "../bower_components/requirejs-text/text",
        "requireLib": "core/require",
        "jquery": "../bower_components/jquery/jquery",
        "jquery.easing": "../bower_components/jquery.easing/js/jquery.easing",
        "momentjs": "../bower_components/momentjs/moment",
        "requirejs.domReady": "../bower_components/requirejs-domready/domReady",
        "sammy": "../bower_components/sammy/lib/sammy",
        "touchpunch": "../bower_components/jqueryui-touch-punch-improved/jquery.ui.touch-punch-improved"
    }
});
```

... it doesn't work after you build a compressed file.  The browser tries to find these components via a path name, and not a module name in the compressed file.  I'm not sure if this is a bower, requireJS, or grunt issue.

**Comment by briantopping** [comment]
@sindresorhus: I'd disagree with this somewhat. To me, Bower is a Git URL aggregator that can find projects referenced for import. Unless projects are going to maintain two repositories (one for original sources and one for distribution), there ought to be a well-known pattern by which generated artifacts are not needing to be generated into locations that obscure their source. 

I totally appreciate that Bower does not want to document and solve for it's use in every permutation of build and I don't think anyone is asking for that. But when compared to Maven, APT or RPM (two enterprise grade package managers I am familiar with), the deployment artifacts are built and managed separately from the source tree, not generated into the source tree.

My fear is that not solving for a few of the popular environments like RequireJS will mean that someone with less vision and a lot of time will fragment the Bower space by "fixing" this issue with a new repository manager (like what happened with Apache Ivy). Trust me, everyone loses at that point...
