### ISSUE TITLE
Install components for production version

### ISSUE THREAD

**Issue by ua9msn** [bower/bower#1105]
Bower is a cool thing actually. But there is the thing annoying me - bower downloads whole github content of packages include docs, tests, dev version of component.
That files is not needed in most cases. In my case it's even obstruct the usage. For me it's Meteor.js conception. Also this behavior makes adding bower components into the own repos very uncomfortable. So bower becomes inapplicable for big enterprise projects where components must have been fixed regardless of github updates. 
That would be great to add '-production' option to avoid unpacking nonminified files into destination directory. May be there is another way to make it, for example add some options in bower.json

**Comment by argb** [comment]
+1 Agree completely.
