### ISSUE TITLE
`bower install` should override linked dependencies (?)

### ISSUE THREAD

**Issue by OliverJAsh** [bower/bower#1111]
`bower install` should override linked dependencies, or at least provide an option to override linked dependencies. Currently it silently fails. The former is the behaviour of npm (just as a reference).

**Comment by jca258** [comment]
I would like to have a `bower list --linked` command or something like that to get a fast review of what dependencies are linked, but I don't think that bower install would have to replace the linked deps.
Most of the times I'm working with linked dependencies I want to update/install other deps without replacing the once I'm linking from my local repos.
Also a good approach would be to add a `--clean-linked` or `--override-linked` to the update/install commands if someone needs that behaviour.

**Comment by sheerun** [comment]
Bower is now deprecated and in maintenance mode which means we won't be making breaking changes or breaking features
