### ISSUE TITLE
Transitive dependency upgrade causes conflict

### ISSUE THREAD

**Issue by TwoSlick** [bower/bower#1147]
I'm working through an issue where a module (modA) upgrades one of its dependencies (modB) to a breaking change version (from 1.0.0 to 2.0.0).  modA updates its version to 1.1.0 and releases.  An app that has dependencies to modA#^1 and modB#^1  used to work, and should stick with version 1.0.0 of both modules.  However, Bower always picks modA#1.1.0, and causes a conflict.  Releasing modA as 2.0.0 fixes the problem, but its API never changed, and I am using the Semver 2.0 scheme.

I would expect Bower to initially try modA#1.1.0, notice the conflict, and then work its way back to modA#1.0.0, and see that the conflict is resolved.  modA#1.0.0 and modB#1.0.0 would be the final chosen versions.

**Comment by kaelig** [comment]
@benschwarz I'd appreciate an update on this issue.

PS: I work with @triblondon at FT Labs, if we can help, let us know!

**Comment by sheerun** [comment]
Bower is now deprecated and in maintenance mode which means we won't be fixing such edge cases. We encourage to switch to yarn with bower-away and use resolutions
