### ISSUE TITLE
bower install --clean, or something like it?

### ISSUE THREAD

**Issue by shaqq** [bower/bower#1184]
It'd be nice to have a command that does:

```
rm -rf bower_components
bower cache clean
bower install
```

Or, we could have a `bower uninstall --all`. I just don't like having to hard-code my bower_components folder into a command.

I could send a PR if people think this is a worthy feature.

**Comment by mclarke47** [comment]
+1

**Comment by che-effe** [comment]
+1

**Comment by sheerun** [comment]
I'm locking, because we're clear I'd accept such PR (`--clear flag that removes extraneous dependencies`)

**Comment by sheerun** [comment]
Bower is deprecated and in maintenance mode, so we won't implement new features like this one. We recommend switching to yarn and migrating legacy projects to it with [bower-away](https://github.com/sheerun/bower-away)
