### ISSUE TITLE
Bower install is not working with svn

### ISSUE THREAD

**Issue by akshaykumar6** [bower/bower#1196]
I installed bower on my Windows 8 machine globally. Now I tried installing package from svn repository 

`bower install svn+svn://svn.somename.com/project/Branches/MyBranch#32`

I got:

`bower ENOTFOUND Package svn+svn://svn.somename.com/project/Branches/MyBranch not found`

Its a private package protected by login password. What is wrong with it ? Does bower support password protected svn packages?

**Comment by jamshid** [comment]
Just verifying that svn+https *does* get your svn credentials from your environment (just like svn itself), so you won't be prompted for a username/password.
$ bower install 'svn+https://private.example.com/src/repo/bower_test/'
As pointed out earlier, bower does expect your svn path to have the folders trunk, tags, branches.
