### ISSUE TITLE
Unregister package requests

### ISSUE THREAD

**Issue by satazor** [bower/bower#120]
_**Edit** (April 2014): Updated by @paulirish & @sheerun_

Package unregistering will be available via `bower unregister <package>` soon, but for now, you can unregister packages yourself using `curl`, if the package is hosted on GitHub and you're an owner or collaborator.

```sh
curl -X DELETE "https://bower.herokuapp.com/packages/PACKAGE?access_token=TOKEN"
```

* Where `PACKAGE` is the package name you want to delete and `TOKEN` is GitHub's Personal Access Token that you can fetch from here: https://github.com/settings/applications
* A default GitHub Personal Access Token will work -- no permissions necessary
* You need to be an owner or [collaborator](https://developer.github.com/v3/repos/collaborators/) of the repo and URL needs to be OK. 
* You'll likely want to `bower cache clean` after your change.
* Please remember it is generally considered bad behavior to remove versions of a library that others are depending on. Think twice :)

If the above doesn't work for you, we can handle your case manually (and please post below). And again, soon we'll be addressing the remaining issues so this is much easier for everyone. :) Cheers.

**Comment by Luegg** [comment]
Please unregister angularjs-scroll-glue and angularjs-scroll-glue-Luegg. The former is a no longer maintained fork and the later a ill-named registration someone else created. The correct package is _angular-scroll-glue_.

**Comment by outsideris** [comment]
Could you please re-register `git://github.com/outsideris/angular-summernote.git` to `git://github.com/summernote/angular-summernote.git`
I got GitHub.com error from `curl -X DELETE ...`
Thank you.

**Comment by stephenwinsor** [comment]
Please unregister `primer` because the repo `git://github.com/code-curve/primer.git` is no longer available. Thanks!

**Comment by mike-schultz** [comment]
Please re-register ```zingchart``` to ```git@github.com:zingchart/ZingChart.git``` . Thanks!

**Comment by epistemex** [comment]
Please unregister ports (git@github.com:epistemex/ports.git). Thanks (and same as others: curl with option -X fails in windows).

**Comment by kossebau** [comment]
Hi. Please re-register "viewerjs" from "github.com/aurigadl/Viewer.js" to "github.com/kogmbh/ViewerJS_release".
The former is an unmaintained 3rd-party package (whose author @aurigadl did not react to emails to the github registered email address in the last 2 months), while the latter is the maintained package from the original project developers.

**Comment by kossebau** [comment]
Please unregister `webodf_build`.
It is an unmaintained 3rd-party package (whose author @aurigadl did not react to emails to the github registered email address in the last 2 months). A maintained package for the library webodf.js  from the original project developers is already registered as `webodf.js`.

**Comment by desandro** [comment]
+ @parris unregistered `react-android-timepicker` :white_check_mark:
+ @prettynatty @Luegg re-registered `angularjs-scroll-glue` to `git://github.com/prettynatty/angularjs-scroll-glue.git` :white_check_mark:. This package had lots of hits, so it's important to keep the registration.
+ @Luegg unregistered `angularjs-scroll-glue-Luegg` :white_check_mark:
+ @outsideris re-registered `angular-summernote` to `git://github.com/summernote/angular-summernote.git` :white_check_mark:
+ @stephenwinsor unregistered `primer` :white_check_mark:
+ @mike-schultz re-registered `zingchart` to `git://github.com/zingchart/ZingChart.git` :white_check_mark:
+ @epistemex unregistered `ports` :white_check_mark:
+ @kossebau
  - for `viewerjs` I've opened kogmbh/ViewerJS_release#1 to discuss resolving this
  - for `webodf_build`, There's no conflict here. Both `webodf.js` and `webodf_build` can co-exist.

No need to say thanks. Thank _you_ for using Bower :bird:

**Comment by lqez** [comment]
Hi bower team!
Summernote had moved from hackerwins/summernote to [summernote/summernote](https://github.com/summernote/summernote).
Please re-register it. Thanks.

**Comment by felixexter** [comment]
Please re-register `tmpl.js` to `git://github.com/felixexter/tmpl.js.git`.

**Comment by kossebau** [comment]
>   *  for viewerjs I've opened kogmbh/ViewerJS_release#1 to discuss resolving this

Hopefully solved now as far as also supporting the older version not covered before. So looking forward to next manual registration maintenance round :)

>  *   for webodf_build, There's no conflict here. Both webodf.js and webodf_build can co-exist.

Given that webodf_build package is outdated/unmaintained I would have proposed to clean things up, as it does not add anything to what the maintained version offers, and people might only get frustrated to learn there is another version with bugs fixed and new stuff added.  But your call.

**Comment by StephanBijzitter** [comment]
`bower unregister famous-material` didn't work as unregister isn't a command (at least on my system) and the CURL option wasn't doing anything (visible) at all =-/

Could you please unregister and reregister `famous-material` from `https://github.com/StephanBijzitter/Famous-Material` to `https://github.com/Skelware/Famous-Material`?

**Comment by AlexanderFedorenko** [comment]
Hi!
Having **Application Error** during curl request, so
please, remove this [jquery.rateit](https://github.com/AlexanderFedorenko/jquery.rateit) from Bower repo

**Comment by simeg** [comment]
Please uninstall `ngjs-color-picker`. 

Thanks.

**Comment by mholt** [comment]
I was getting a "GitHub.com error" when trying to unregister Papa Parse. Somehow it got registered 3 times, and I'd like to unregister all of them and start fresh:

`papaparse`
`papaparse.js`
`papa-parse`

I'm not sure how they appeared on Bower, as I've never used Bower before. Could you please unregister those? I'll re-register it in a little bit once I'm ready.

**Comment by jrcamp** [comment]
I'm getting "GitHub.com error" when trying to unregister as well.

Can knockout-jqueryui be transferred to @gvas? Thanks!

**Comment by csshugs** [comment]
Could you please unregister these packages:
- `genesis-helper`
- `genesis-wordpress`
- `henryCSS`

Thanks!

**Comment by desandro** [comment]
+ @lqez re-registered `summernote` to `git://github.com/summernote/summernote.git` :white_check_mark:
+ @felixexter re-registered `tmpl.js` to `github.com/felixexter/tmpl.js.git` :white_check_mark:
+ @StephanBijzitter re-registered `famous-material` to `git://github.com/Skelware/Famous-Material.git` :white_check_mark:
+ @mholt unregisterd `papaparse`, `papaparse.js`, and `papa-parse` :white_check_mark:. These packages had 1000's of hits, so they're fairly popular. We'd appreciate if you could re-register at least one
+ @jrcamp re-registered `knockout-jqueryui` to `git://github.com/gvas/knockout-jqueryui.git` :white_check_mark:
+ @csshugs unregistered `genesis-helper` and `henryCSS` :white_check_mark:

No need to say thank you. Thank _you_ for using Bower.

**Comment by mholt** [comment]
Thanks @desandro - I didn't know that. I re-registered Papa Parse under the name `papaparse`. But I found one more stray entry that should be removed; I'm not sure who put it there, and the repo doesn't exist anymore:

- `papa.parse` (git://github.com/mholt/jquery.parse.git)

**Comment by StephanBijzitter** [comment]
^- probably a good idea to create a system to automatically delete packages that haven't been valid for 30 days? 1 cron job a day on a server and 30 continuous fails = bye bye

**Comment by jasonrichardsmith** [comment]
I just need to transfer my package 
mongular-js
from
git://github.com/jasonrichardsmith/mongular-js.git
to
https://github.com/mongular/mongular-js

**Comment by Gillardo** [comment]
can someone please change my 2 bower projects, i ended up putting ui-bootstrap instead of bootstrap-ui

They are

ui-bootstrap-datetime-picker
to
bootstrap-ui-datetime-picker

and

ui-bootstrap-treeview
to
bootstrap-ui-treeview

Can you let me know when this is done and i will update it on github. Thanks

**Comment by rpocklin** [comment]
* [ ] angular-timeline git://github.com/destegabry/angular-timeline.git

Owner does not support bower and issue has been open for > 12 months (see https://github.com/destegabry/angular-timeline/issues/2) without response.

**Comment by leoz** [comment]
Hello,

Could you please un-register the following packages?

- nglivejournal
- xmlrpc

The git repos were moved to the new location.
I will register them again once they are removed.

Thanks,
Leonid.

**Comment by ManRueda** [comment]
Hi, i need to erase the lokijs-datagrid package.

Thanks!

**Comment by tivie** [comment]
Can you please change the url of showdown package to https://github.com/showdownjs/showdown and the owner to myself?

The url is outdated (before changing to a organization repository).

**Comment by eordano** [comment]
Please move `bitcore-channel` from git://github.com/eordano/bitcore-channel.git to git://github.com/bitpay/bitcore-channel.git.

**Comment by bigtimebuddy** [comment]
Please move `bellhop` from **git://github.com/CloudKidStudio/Bellhop.git** to **git://github.com/SpringRoll/Bellhop.git**. Thank you!

**Comment by desandro** [comment]
+ @jasonrichardsmith re-registered `mongular-js` to `git://github.com/mongular/mongular-js.git` :arrow_right:
+ @rpocklin unregisterd `angular-timeline` :negative_squared_cross_mark:
+ @leoz
  - re-registered `nglivejournal` to `git://github.com/leoz/ngLiveJournal.git` :arrow_right:
  - re-registered `xmlrpc` to `git://github.com/leoz/xmlrpc.js.git` :arrow_right:
+ @ManRueda unregistered `lokijs-datagrid` :negative_squared_cross_mark:
+ @tivie re-registered `showdown` to `git://github.com/showdownjs/showdown.git` :arrow_right:
+ @eordano re-registered `bitcore-channel` to `git://github.com/bitpay/bitcore-channel` :arrow_right:
+ @bigtimebuddy re-registered `bellhop` to `git://github.com/SpringRoll/Bellhop.git` :arrow_right:

No need to say thanks. Thank _you_ for using Bower :bird

---

@Gillardo Both `bootstrap-ui-datetime-picker` and `bootstrap-ui-treeview` are open to be registered. There is no need to unregister `ui-bootstrap-datetime-picker` or `ui-bootstrap-treeview`

**Comment by desicochrane** [comment]
please move `picky-sass` from git://github.com/ginacontrino/picky-sass.git to git://github.com/pickygoat/picky-sass.git

Admire the work :)

**Comment by PLEEROCK** [comment]
please move *angular-tags-input* from ```git://github.com/anim/angular-tags-input.git``` to ```git://github.com/PLEEROCK/angular-tags-input.git```

**Comment by Ppjet6** [comment]
I'm sorry I failed during the registration. Please move *flex-min* to *flex-grid* (https://github.com/Ppjet6/flex-grid)

**Comment by gontard** [comment]
Please, move *scribe-global * from `https://github.com/guardian/scribe` to https://github.com/intactile/scribe-global

**Comment by erquhart** [comment]
Please change the repo for `pretty-embed`:

current: `git://github.com/erquhart/bower-pretty-embed`
new: `git://github.com/mike-zarandona/prettyembed.js`

**Comment by desandro** [comment]
+ @desicochrane re-registered `picky-sass` to `git://github.com/pickygoat/picky-sass.git` :arrow_right:
+ @PLEEROCK re-registered `angular-tags-input` to `git://github.com/PLEEROCK/angular-tags-input.git` :arrow_right:
+ @gontard re-registered `scribe-global` to `git://github.com/intactile/scribe-global.git` :arrow_right:
+ @erquhart re-registered `pretty-embed` to `git://github.com/mike-zarandona/PrettyEmbed.js.git` :arrow_right:

---

@Ppjet6 You do not need to unregister a package to register it with a different name. `flex-grid` is already registered, but you are free to register your package with a different name.

**Comment by erquhart** [comment]
@desandro thank you. Please check out my updated comment.

**Comment by Ppjet6** [comment]
@desandro, thank you for the information. Could you remove `flex-min` still, this one was a mistake.

**Comment by rnicholus** [comment]
Please unregister "file-input".  I'm the owner of the parent repo.  [This user forked and registered the package](https://github.com/Bor1s/file-input) just moments after I unregistered it during an attempt to relocate the repo to another organization.  

The original location is git@github.com:garstasio/file-input.git, but I am going to move this to git@github.com:rnicholus/file-input.git shortly.

**Comment by dvberkel** [comment]
I tried to do this with curl but it did not recognize me as the owner of the repository.

I would like to register a new owner and url for "cois-sprite-importer". Currently it is https://github.com/dvberkel/sprite-importer.git but ownership it transferred to https://github.com/Chair-of-Indefinite-Studies/sprite-importer.git

**Comment by andresusanopinto** [comment]
Please update adapter.js from git@github.com:GoogleChrome/webrtc.git to git@github.com:webrtc/adapter.git
The delete method fails probably because we moved and split the repository between the organization.

**Comment by c808xx** [comment]
Hi, I have issue registering my package *angular-route-ext*. Please unregister *angular-route-ext* and *angular-route-ext-test*. So I can re-register. I tried to unregister them but could not re-register.

**Comment by rwjblue** [comment]
Please change `ember-qunit` to point to `git://github.com/rwjblue/ember-qunit-builds`.

Back story: 

* It was originally located at `git://github.com/rpflorence/ember-qunit`
* Ownership was transferred to @rwjblue and the main project lives at `git://github.com/rwjblue/ember-qunit.git`
* Builds have been removed from that repo, and moved to the rwjblue/ember-qunit-builds repo which is where we need `ember-qunit` to point...

**Comment by desandro** [comment]
+ @Ppjet6 unregistered `flex-min` :negative_squared_cross_mark:
+ @rnicholus re-registered `file-input` to `git://github.com/rnicholus/file-input.git` :arrow_right:
+ @dvberkel re-registered `cois-sprite-importer` to `git://github.com/Chair-of-Indefinite-Studies/sprite-importer.git` :arrow_right:
+ @andresusanopinto re-registered `adapter.js` to `git://github.com/webrtc/samples.git` :arrow_right:
+ @c808xx both `angular-route-ext` and `angular-route-ext-test` are not registered :white_check_mark:
+ @rwjblue re-registered `ember-qunit` to `git://github.com/rwjblue/ember-qunit-builds.git` :arrow_right:

**Comment by rnicholus** [comment]
Thanks much Mr. @desandro!

**Comment by liccy-fuentes** [comment]
Please rename git-pu-video to pu-video. Thank you!

**Comment by Four51SteveDavis** [comment]
Please remove ordercloudsdk at https://github.com/Four51/OrderCloudAngularSDK.git

**Comment by panterz** [comment]
I am trying to unregister a bower package and I am getting the error that I am not collaborator, but I am.
curl -X DELETE https://bower.herokuapp.com/packages/fieldtrip-extend-record?access_token=3b504a68349fc46f647a8832228c997009eafdd5

Am I missing something? Can you unregister it for me?

**Comment by panterz** [comment]
I am trying to unregister a bower package called fieldtrip-extend-record. I am a collaborator but when I run the one below
curl -X DELETE https://bower.herokuapp.com/packages/fieldtrip-extend-record?access_token=TOKEN

I am getting the error that I am not a collaborator.

Is it possible to manually unregister it for me?

**Comment by warpech** [comment]
Please re-register: `fast-json-patch` `git://github.com/Starcounter-Jack/Fast-JSON-Patch.git`
to: `git://github.com/Starcounter-Jack/JSON-Patch.git`

**Comment by sorich87** [comment]
Please re-register inject git@github.com:linkedin/inject-bower.git to git@github.com:linkedin/inject.git.

It was asked for in a previous comment https://github.com/bower/bower/issues/120#issuecomment-31971112, but it hasn't been done. :)

**Comment by desandro** [comment]
+ @liccy-fuentes registered `pu-video` to `git://github.com/PracticeUpdate/pu-video.git` :white_check_mark:
+ @panterz unregistered `fieldtrip-extend-record` :negative_squared_cross_mark:
+ @warpech re-registered `fast-json-patch` to `git://github.com/Starcounter-Jack/JSON-Patch.git`  :arrow_right:
+ @sorich87   re-registered `inject` to `git://github.com/linkedin/inject.git` :arrow_right:

Thank you for using Bower!

**Comment by tocker** [comment]
Can you please process @seba-1511's [request](https://github.com/bower/bower/issues/120#issuecomment-38376450) so that the package `cloudinary` is released and can be registered to @cloudinary's master repository (https://github.com/cloudinary/cloudinary_js)?

- [ ] release package `cloudinary` from git://github.com/seba-1511/cloudinary_js.git
- [ ] register package `cloudinary` to git://github.com/cloudinary/cloudinary_js.git

Thanks!

**Comment by derickbailey** [comment]
Hello - I need to get a bower package unregistered from my name / github account, as the repository was moved. 

The original repository was derickbailey/backbone.syphon - the package was backbone.syphon

if you could get that package unregistered so that the new team maintaining it can register the new version, that would be awesome.

thanks!

**Comment by ssc-hrep3** [comment]
Can you remove the package jquery-loadtemplate? I removed the github repository and need the package to be deleted. Thank you!

**Comment by sbstjn** [comment]
`timesheet.js git://github.com/CatTail/timesheet.js.git` is not available anymore
`timesheet git://github.com/semu/timesheet.js.git` is not available anymore

**Comment by dasnervtdoch** [comment]
Hello, could you please remove model-validator package (https://github.com/dasnervtdoch/model-validator). I will rename my account. Thanks!

**Comment by desandro** [comment]
+ @tocker @seba-1511 re-registered `cloudinary` to git://github.com/cloudinary/cloudinary_js.git :arrow_right:
+ @derickbailey unregistered `backbone.syphon` :negative_squared_cross_mark:
+ @ssc-hrep3 unregistered `jquery-loadtemplate` :negative_squared_cross_mark:
+ @sbstjn unregistered `timesheet.js` :negative_squared_cross_mark: . `timesheet` is still registered as it's properly pointing to `git://github.com/semu/timesheet.js.git`
+ @abedurftig re-registered `model-validator` to `git://github.com/abedurftig/model-validator.git` :arrow_right:

---

No need to say thanks. Thank _you_ for using Bower :bird:

**Comment by bladev2** [comment]
Hi - can you please unregister jwt-decode-test ? Thanks!

**Comment by bbooth** [comment]
Need to remove ember-cli-skycons-shim.  Ended up not needing it.  The curl for me keeps returning a 404 :(

**Comment by evanvosberg** [comment]
Hello, could you please move the `crypto-js` package?

From: git:////github.com/Jeff-Mott-OR/CryptoJS.git
To: git://github.com/evanvosberg/crypto-js.git

Since the original repo doesn't exists anymore and my one is already well known on `npm` people asked for adding `bower` support. I just did so and added bower support and released a new version.

**Comment by andreyviktorov** [comment]
Hello, could you move `notiny` package (someone forked it and registered at bower registry)

From: git://github.com/mamboer/notiny
To: git://github.com/andreyviktorov/notiny

**Comment by kirill-konshin** [comment]
As a follow up for comment https://github.com/bower/bower/issues/120#issuecomment-84255071 -- the package is currently registered as `crypto-js-evanvosberg`. The original `crypto-js` package cannot be downloaded anymore due to 404 (repo has been deleted).

**Comment by RenatoUtsch** [comment]
Hello,

Could you please unregister the `polynvd3` package? I recreated it under the `poly-nvd3` name.

**Comment by cubedro** [comment]
Hello,
Could you please move `ethereum.js`
FROM: ```git://github.com/cubedro/ethereum.js.git```
TO: ```git://github.com/ethereum/ethereum.js.git```

Thank you!

**Comment by sheerun** [comment]
Hey everyone. Bower 1.4.0 now includes `unregister` feature.

If you're still unable to unregister your component, please open an issue on [bower/registry](https://github.com/bower/registry).
