### ISSUE TITLE
bower install should not use timestamps from the archive

### ISSUE THREAD

**Issue by mgedmin** [bower/bower#1207]
1. `bower install bootstrap`
2. Create a Makefile that runs lessc to compile bootstrap.css from bower_components/less/bootstrap.less
3. Run `make`
4. Install a different bootstrap version with `bower install bootstrap\#3.0.0`
5. Run `make` again

What should happen: make notices that bootstrap.less has a new mtime and rebuilds bootstrap.css

What actually happens: nothing.

Why?  Because the timestamps of the files in bower_components/bootstrap/less/*.less are from last December, because unpacking the .tar.gz restored the mtimes.  It shouldn't do that, for the same reason 'git checkout' doesn't restore the mtime of checked out files.

**Comment by sheerun** [comment]
Bower is now deprecated we encourage to use Yarn instead. You can migrate with bower-away
