### ISSUE TITLE
Perform benchmarks and speedup slowest commands

### ISSUE THREAD

**Issue by sheerun** [bower/bower#1233]
Thanks to #1232 commands are now executing independent from one another (i.e. loading time of one command doesn't affect the other one). As for now, it would be good to prepare set of benchmarks for all (or at least the slowest) commands, profile them, and make them faster, one by one.

That said, I'm not an expert in neither benchmarking nor profiling of Node applications.

**Comment by wookoouk** [comment]
happy to write bench marks, lemme know.
