### ISSUE TITLE
allow for pointing to a specific file / directory in a repository as a dependency

### ISSUE THREAD

**Issue by ahmadnassri** [bower/bower#1235]
a simple example would be `bower install --path=/less bootstrap#*` where I want to just get the `less` directory and not the whole output of `bootstrap`

the potential value here is the ability to setup micro-dependencies on parts of big libraries/modules... obviously only useful for BIG libraries with some useful smaller parts. 

*(not that I'm a fan of libraries that are structured this way, I believe they need to be broken down)*

a good syntax could be:
`bower install --path=<path-to-lib-dir> <package>#<version>`
`bower install --file=<path-to-file> <package>#<version>`

figured I'd start this conversation, worth discussing?

*also see #1139*

**Comment by sheerun** [comment]
This would be solved by #1930 if implemented
