### ISSUE TITLE
The package you are trying to register is marked as private

### ISSUE THREAD

**Issue by choiks141** [bower/bower#1246]
i tried to register component
but i met the issue.

bower EPRIV         The package you are trying to register is marked as private

**Comment by krysalead** [comment]
Hi,

ran in the same issue, but reading the code my issue was to have the 

{
...
"private": "false",
...
}

Which is true.

thanks and regards

**Comment by TonyLiuDalian** [comment]
delete "private":true   and  change tag to higher, that's whath i did ,it worked.
