### ISSUE TITLE
Dependencies from package.json are not installed

### ISSUE THREAD

**Issue by unscriptable** [bower/bower#1252]
It seems that if I `bower install --save X` and X has only a package.json file, rather than  a bower.json file, then X's dependencies are not installed.

I see from a comment in #599 that this may be intentional, but it doesn't make any sense to me.  How is it useful to `bower install` a package if that package's dependencies aren't installed?

As a package author, if I want to register my package on bower, I would naturally want it to be installable -- including dependencies -- via bower.  Right?.  Therefore, I would ensure that all of the dependencies in package.json are also available on bower.  If they're not, then I would ask their maintainers to add them to bower.

**Comment by sheerun** [comment]
As far as I remember bower now supports intalling packages without bower.json (but still it won't install deps from package.json, use yarn or npm for this)
