### ISSUE TITLE
builds failing do to EPERM error about unlinking files

### ISSUE THREAD

**Issue by j-kim** [bower/bower#1271]
I've gone through quite of few of your tickets which seem to address the same error code, but all seem to have occurred due to different reasons (anti-virus, administrative rights, folder permissions, proxy, etc).  The last and most recent comments on https://github.com/bower/bower/issues/991 address what is currently being seen with an EPERM dealing with problems with unlinking a file during a build.  All the previous "solutions" have been implemented and the error still occurs.  The thing that makes this difficult is that it is intermittent.  It literally happened all day on one day... then only once on another.  I have not been able to pin point what caused this error.  Any insight into this would be much appreciated.  Thanks.

Windows 7 x64
Bower 1.3.3
Node v0.10.26
NPM 1.4.3

**Comment by csuwildcat** [comment]
I am getting this after changing the `main` property. I tried to remove it and change the files it points to, and that seemed to kick off this cycle where any bower update containing updates of that package now throws and unlink error. To fix it, I am forced to delete the folder and re-run update to pull in a fresh copy.
