### ISSUE TITLE
resolutions is not being used to resolve dependencies when called with a specific dependency

### ISSUE THREAD

**Issue by edeustace** [bower/bower#1272]
see: https://github.com/edeustace/bower-deps-test

steps: 

```
git clone https://github.com/edeustace/bower-deps-test
cd bower-deps-test 
./run
```

In the test case, we:
- copy with-resolutions.json -> bower.json
- run `bower install`
- copy the with-resolutions.json -> bower.json (so that the `resolutions` are restored [see: #1061])
- then we run `bootstrap install angular-dragdrop`

Expected: jquery 1.11.0 is used as the resolution
Actual: a prompt appears asking for a resolution

Note: adding both dependencies in the one bower.json works.

**Comment by sheerun** [comment]
Bower is deprecated and in maintenance mode, so we won't implement new features like this one. We recommend switching to yarn and migrating legacy projects to it with [bower-away](https://github.com/sheerun/bower-away). Yarn supports resolutions as well: https://classic.yarnpkg.com/en/docs/selective-version-resolutions/
