### ISSUE TITLE
Error should be indicated when unable to write to HOME

### ISSUE THREAD

**Issue by shepmaster** [bower/bower#1273]
Running in a Docker build environment, `HOME` is not defined. This causes bower to silently fail:

```bash
$ CI=true bower install
$ echo $?
0
$ HOME=/tmp CI=true bower install
# ... snipped installation output ...
```

It would be better if

1. Some error text was given to the user
2. An error exit code was returned to cause build scripts to fail.

Even better, it would be great if `HOME` wasn't required in this type of environment.

```
$ bower --version
1.3.3
```

**Comment by ceoaliongroo** [comment]
Despite the warm, runs normally.
