### ISSUE TITLE
Support local filesystem installs

### ISSUE THREAD

**Issue by panuhorsmalahti** [bower/bower#1275]
Currently bower supports installing from a "folder that's a Git repository". Bower should additionally (or instead) support installing directly from a folder, just like NPM. The benefits are clear: when doing local development, the developer can install a updated version of the bower package by simply "bower install ../my_package/" instead of doing commits.

In addition, Bower often doesn't really get the latest version from a local Git folder, I've noticed that I need to clean the cache and what-not to make sure I'll get the latest version.

**Comment by sheerun** [comment]
TIL about git subtrees.

Yes, bower should use last tag / commit if target is a git repository.

- `./components/component` - use latest tag
- `./components/component#~1.3.4` - use latest matching tag
- `./components/component#master` - use latest commit

As far as I know there's no way to use working directory of taget's git repo (except `bower link`).

Bower link creates symlink in filesystem between your source and target repository. This change is local-only and meant to use for development. You need to manually `bower link` on each machine if you want `bower_componens/component` to symlink to `./components/component`.

I hope I'm clear enough :)

**Comment by plestik** [comment]
Thank you! This is a problem for me as it stands, because sometimes I'll commit changes in the parent repository but not in the subtree directory, meaning it will get out of sync. Can we then turn this into a feature request? Basically: I want to be able to define the install protocol (i.e. use the current source, or resolve the latest commit/tag).

I'll have to wait with publishing my components, then, for the mean time.

**Comment by sheerun** [comment]
As I mentioned before `file://` prefix could mean to use working dir instead latest commit / tag.

There's nobody to implement this feature, though.

**Comment by plestik** [comment]
Putting it on my list then! Thanks!

**Comment by kosz** [comment]
+1 :+1:

**Comment by kosz** [comment]
@plestik have you started on this ? my team will need something similar as well in about a month, wanted to see if I can help in any way. if you haven't started on it, then I can also start investigating and see if i can build it myself, even though there will be some overhead there since i've never contributed to this project.

**Comment by plestik** [comment]
@kosz I'm probably going to move away from Bower so I've kind of lost my interest. Sorry about that.

**Comment by kosz** [comment]
@plestik no worries, thanks for the update

**Comment by tomasAlabes** [comment]
@sheerun the `file://` thing you talked about is this [issue](https://stackoverflow.com/questions/28418806/npm-install-fails-with-multi-layered-local-dependencies/28466731#28466731)? This happened in npm and was fixed. And is happening in bower.

**Comment by dawniegrl** [comment]
What's evw

**Comment by jpsfs** [comment]
Hi!

Are there any updates regarding this?

**Comment by ChicagoDave** [comment]
The use case that requires local installs is in the enterprise. I'm in a corporate environment with a Gitorious implementation and we have our own private packaging of code. So we have cases of using bower via GitHub, but we'd like to use bower via onprem .git sources. As it is, we're using "git clone", but that's overkill. The point of bower is to only grab the dist file(s), not the entire repo.

So being able to:

bower git@gotorious.mycompany.com:my-repo/my-repo.git

..would be extremely beneficial. A switch (-local) would be fine. It would be even better if we could config bower itself to look for an on-prem location before going to github. So then I could just do:

bower my-repo

and it would look first in git@gotorious.mycompany.com:my-repo/{name}.git

Seems like a reasonable request.

**Comment by tomalec** [comment]
Are there any news about support for non-git local folders?

**Comment by viniciuspires** [comment]
@tomalec It's already available in the latest version of bower. Check out the docs about the `bower install` command: http://bower.io/docs/api/#install

**Comment by tomalec** [comment]
I have tried many variants :
`bower install --save path/to/folder/`
`bower install --save file://path/to/folder/`
`bower install --save "path\\to\\folder\\"`

All gave same error:
`bower ENOTFOUND     Package path/to/folder/ not found`

**Comment by tomalec** [comment]
Now i got it `bower install --save  ./path/to/folder/`. I think it's worth mentioning in docs

**Comment by davidemoro** [comment]
Unfortunately the official bower doc (http://bower.io/docs/api/#install) says that package can be also a local folder but it doesn't work :/

**Comment by davidemoro** [comment]
Just tried providing an absolute path for package, it hangs

**Comment by davidemoro** [comment]
Update::

    $ bower install ABSOLUTEPATH"

worked but the ``bower_components`` folder was created from the calling path, not in ABSOLUTEPATH

**Comment by davidemoro** [comment]
Alternatively it can be done putting a ``.bowerrc`` file with the following:
`` 
   {
      "directory": "bower_components",
      "cwd": "./PATH"
    }
``

See http://bower.io/docs/config/#cwd

**Comment by sheerun** [comment]
Now you can implement it as a [Pluggable Resolver](http://bower.io/docs/pluggable-resolvers/) that overrides native one.

We're going to deprecate native resolvers in favour of pluggable resolvers, and we don't want to make backward-incompatible changes in Bower. I hope some of you will have time to implement custom resolver that implements this enhancement, as Bower's core team is short on resources.

**Comment by cloudtronics** [comment]
with v1.7.2  :  i can do : 
 bower install ../mycompo --save
but if I change the files in mycompo folder and running either install or update even w/o --force flag the updated files are not pulled to the working app.. Pls help . Thanks

**Comment by stefk** [comment]
> I hope some of you will have time to implement custom resolver that implements this enhancement, as Bower's core team is short on resources.

This one made the trick for me: https://github.com/Backbase/filesystem-bower-resolver.

**Comment by alirezamirian** [comment]
@sheerun the **bower link** that you've suggested has a downside that bower ignored files will not get ignored.

**Comment by polu3g** [comment]
hi,

i can pull the updates if i change the maxcore codebase. maxcore is a local component,  where bower link will help you to establish the live linkage with maxcore & current component..

` "dependencies": {
   "maxcore" : "latest"
  }`

for me a build anyway fetches always the latest.. so the changes made by the core-team in maxcore component is always visible to subscribed components..

njoy
