### ISSUE TITLE
Bower service down

### ISSUE THREAD

**Issue by aaziz** [bower/bower#1280]
Hello, 

Our team uses bower for our application, and is noticing that requests to Bower are timing out. Is this a known issue? What it the ETA for the fix? 

Thank you! 
amal

**Comment by ryanbagwell** [comment]
I'm getting an ssl certificate error now. Is this related?

````
$bower install granite
bower                            error Request to https://bower.herokuapp.com/packages/granite failed: Hostname/IP doesn't match certificate's altnames
````

**Comment by ryanbagwell** [comment]
looks like a strange dns issue with my isp
