### ISSUE TITLE
Bower 1.3.3 on Windows Doesn't Unzip Files

### ISSUE THREAD

**Issue by mikeborozdin** [bower/bower#1286]
Hi,

I'm using Bower 1.3.3, which includes decompress-zip 0.0.6, on Windows 7 x64.

Everytime I try to install a dependency that is contained in a ZIP file, Bower downloads a ZIP file but never unpacks it. There are no errors in the console. Bower just saves a file as 'index.zip'.

**Comment by sheerun** [comment]
@mikeborozdin I've added Windows CI support for bower. I encourage you to create failing test.

**Comment by petermetz** [comment]
Same happens on OS X with Bower 1.4.1

**Comment by sheerun** [comment]
This probably should be fixed in bower 1.6.2 thanks to https://github.com/bower/bower/commit/0bb1536c9972e13f3be06bea9a8619632966c664
