### ISSUE TITLE
apply ignore parameter only for production installation

### ISSUE THREAD

**Issue by sbrunot** [bower/bower#1293]
The documentation for the `ignore` parameter is as following: `An array of paths not needed in production that you want Bower to ignore when installing your package.`

Because these are path that are not needed in production, my feeling is that the dependencies content should only be filtered when doing a production installation (`bower install -production`).

We have a project which bower ignore properties remove the tests directory of its dependencies, but we actually needs theses tests directories in development. It is currently impossible to keep the tests directories when doing a non production install, and remove them when doing a production install.

**Comment by softvar** [comment]
+1
@ApoorvSaxena

**Comment by ApoorvSaxena** [comment]
Another use case for this feature will be to create custom builds requiring the entire source along with build files, which are usually ignored in bower.json as not used by many in production. Currently the only solution is to fork the repo and change bower.json to not ignore the files required as per use. Ideal solution should be to add a setting inside bower.json that allows overriding `ignore` value for a repo.

**Comment by ca0v** [comment]
How about "ignore" and "devIgnore".  When "devIgnore" is found "ignore" is interpreted as the files to ignore (in addition to "devIgnore") when --production.

**Comment by sheerun** [comment]
Bower is deprecated and in maintenance mode and this would be breaking change
