### ISSUE TITLE
Bower 1.3.3 doesn't respect registry.register in .bowerrc

### ISSUE THREAD

**Issue by mikeborozdin** [bower/bower#1294]
Hi,

Bower seems to be suffixing the registry.register value in .bowerrc with '/packages'.

For example, if I have the following .bowerrc:

```
{
    "directory": "bower_components",
    "registry":  {
        "search": "http://localhost:5678/packages",
        "register": "http://localhost:5678/registerPackage"
    }
}
```

bower.registry will result in sending a request to

```
http://localhost:5678/registerPackage/packages
```

This makes it difficult to use or write bower registry servers, such as https://github.com/Hacklone/private-bower

**Comment by sheerun** [comment]
Bower is deprecated and doesn't allow registering new packages anymore, so I'm closing this
