### ISSUE TITLE
Feature: More useful bower search

### ISSUE THREAD

**Issue by torifat** [bower/bower#1302]
I think if we can see repo's watch, start & fork count beside the name in the search list then it would be very useful to search random libraries. Also, http github link will be more useful than git link.

**Comment by adityadineshsaxena** [comment]
@sheerun can you help me understand why the change needs to be made in registry ?

1. Does the registry poll the GitHub repos regularly? If not, then how'd the Stars/Forks/Watching count be constantly updated?
2. If #1 does not hold, then sending requests to every github repo whenever `bower search` is called for wouldn't be feasible. It'd also be very slow for cases like `bower search angular`

Please advise.

**Comment by sheerun** [comment]
@adityadineshsaxena Yup, it needs to poll. That's what search server does.

**Comment by adityadineshsaxena** [comment]
@sheerun thanks for your reply. Let me take a look again and try to be of some use in this issue :-)
