### ISSUE TITLE
Allow Registering Private Packages with Private Registry

### ISSUE THREAD

**Issue by IronGeek** [bower/bower#1314]
I'm aware that the whole reason behind the `private: true` flag is to mark a package from being accidentally registered in bower registry. As is, the restriction applies to both public and private registry. I'm hoping there's an easy way to override this restriction if I were to register a private package _WITH_ private registry.

Why? I've setup a private bower registry to host our internal packages (marked as private of course). Currently the only way to register these packages is by manually adding the necessary information directly into our registry. It would be nice if I could do this with bower client without throwing the error:

```
EPRIV The package you are trying to register is marked as private.
```

Maybe by executing a command, say, something like this:

```
bower register my-private-pkg the-private-pkg-url --private
```

I'm willing to create a PR for this, but I'm not sure if this kind of feature fits with the scope and philosophy of bower, or if there's already a better way to do it. What do you guys think? comment?

— _Instead of all this, I know I could just remove the `private: true` flag on the private packages and be on my way, but that would defeat its original purpose._

**Comment by iuprade** [comment]
not sure if this is the right place to ask question. So if i have my private component and i do not want to register it with bower what are the alternatives to install it withing various teams ?

**Comment by sheerun** [comment]
Bower is deprecated and doesn't allow registering new packages anymore, so I'm closing this
