### ISSUE TITLE
version command doesn't respect existing bower.json indentation (4 spaces)

### ISSUE THREAD

**Issue by patkujawa-wf** [bower/bower#1338]
See https://github.com/bower/bower/issues/1337 for more details. Basically, `bower version major|minor|patch` reformats bower.json to 2-space instead of respecting previous formatting.

**Comment by xiphiaz** [comment]
Bump, still nothing?

**Comment by brunowego** [comment]
If `bower.json` has 4 spaces and install a new library, bower reformat for 2 spaces. This is a small detail, but it creates a certain discomfort.

**Comment by iKlsR** [comment]
Is this still on anyones todo?

**Comment by sheerun** [comment]
No

**Comment by sheerun** [comment]
Bower is deprecated and in maintenance mode, so we won't implement new features like this one. We recommend switching to yarn and migrating legacy projects to it with [bower-away](https://github.com/sheerun/bower-away)
