### ISSUE TITLE
Pull bare git repository on network share rather then copying the folder

### ISSUE THREAD

**Issue by daanvanhulst** [bower/bower#1346]
I have a project which has a dependency on a bower module. Both the project and the bower module are a bare repository located on a network share, accessible by multiple computers.

\SHARED_FOLDER\git\project \SHARED_FOLDER\git\my_bowermodule

Next to that, I have setup a private bower repository where I have registered the bower module where the link to the git repository is the link: '\SHARED_FOLDER\git\my_bowermodule'.

From here I am able to install the module in the project doing a 'bower install my_module'. The problem is that it copies the bare repository folder located at the '\SHARED_FOLDER\git\my_bowermodule', rather than treating it as an actual git repository. 

For me, it would be great if there is an option so that this folder would get treated like a repository, instead of just "local" folder which gets copied.

**Comment by samy100** [comment]
I think I'm having the same issue but with gforge.
For some reason I can't bower install gforge git bare projects.
See: http://blog.gforgegroup.com/2010/04/15/git-support-in-gforge/
Using git clone works great but I wish I could use bower install on gforge...
The command is usually "git clone ssh://<username>@<gforge_server>/gitroot/gitprojectxyz"
This issue might be related to this, if not, can someone guide me in the correct approach?

"bower install ssh://<username>@<gforge_server>/gitroot/gitprojectxyz" doesn't work.

**Comment by sheerun** [comment]
Bower is deprecated and doesn't accept new feature like this one, so I'm closing this
