### ISSUE TITLE
Consider running git command in temporary directory

### ISSUE THREAD

**Issue by thanpolas** [bower/bower#1351]
I was trying to run `bower install` on a freshly generated project which was not a git repo and bower failed with the following error message:

```
[10:21:46] $ bower install
bower modernizr#~2.8.2      not-cached git://github.com/Modernizr/Modernizr.git#~2.8.2
bower modernizr#~2.8.2         resolve git://github.com/Modernizr/Modernizr.git#~2.8.2
bower jquery#~1.11.1        not-cached git://github.com/jquery/jquery.git#~1.11.1
bower jquery#~1.11.1           resolve git://github.com/jquery/jquery.git#~1.11.1
bower closure-helpers#~0.0.3    cached git://github.com/closureplease/closure-helpers.git#0.0.3
bower closure-helpers#~0.0.3  validate 0.0.3 against git://github.com/closureplease/closure-helpers.git#~0.0.3
bower closure-helpers#~0.0.3   ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/closureplease/closure-helpers.git", exit code of #128

Additional error details:
fatal: Not a git repository: ../.git/modules/dotfiles
```

Once i run `git init` it worked as expected

**Comment by sheerun** [comment]
It won't be changed in Bower's native resolver for backward compatibility reasons, but you can implement it as [Pluggable Resolver](http://bower.io/docs/pluggable-resolvers/) that overwrites native one.

**Comment by joslinm** [comment]
I am running `docker-compose up` where my `docker-compose.yml` file is referencing sub-modules. It seems to be working fine until it blows up `fatal: Not a git repository: ../.git/modules/...`

Is there anything I can do or am I stuck high & dry for backward compatibility reasons?

**Comment by joslinm** [comment]
Confused? You can see my SO post here: http://stackoverflow.com/questions/34538270/bower-git-submodules-docker-compose

**Comment by sheerun** [comment]
I know what you mean. There's even PR for it: #1106

We just need to put it behind some kind of flag to maintain backward compatibility for bower 1.x

I thought about `--beta` flag but I need to spec it first...

**Comment by joslinm** [comment]
Oh ok I'll follow the PR #1106 thank you. I'll try to catch up on what needs to get done and if I can contribute, I'll try my best. Thanks for the reply.

**Comment by syradium** [comment]
Until PR is merged you can run bower command specifying `GIT_DIR` env variable. Like:
```
GIT_DIR=/tmp bower install
```
