### ISSUE TITLE
Cache not updating for local zip packages

### ISSUE THREAD

**Issue by zgmnkv** [bower/bower#1356]
I need to install package from local file system from .zip file and this package changes from time to time.
Bower caches this package, but does not update cache when .zip file is updated.
Steps to reproduce:
1. create `test.zip` archive with some content
2. run `bower install ./test.zip`

```
bower test#*                not-cached /tmp/test.zip#*
bower test#*                   resolve /tmp/test.zip#*
bower test#*                      copy /tmp/test.zip
bower test#*                   extract test.zip
bower test#*                  resolved /tmp/test.zip
```

`bower_components` dir is created, `test` subdir is created with archive content
3. change `test.zip` content, remove `bower_components` dir (a new installation)
4. run `bower install ./test.zip`

```
bower test#*                    cached /tmp/test.zip
bower test#*                  validate /tmp/test.zip#*
bower test#*                       new version for /tmp/test.zip#*
bower test#*                   resolve /tmp/test.zip#*
bower test#*                      copy /tmp/test.zip
bower test#*                   extract test.zip
bower test#*                  resolved /tmp/test.zip
bower test#*                   install test
```

`bower_components` dir is created again, but `test` subdir content is from old archive.

Problem exists with bower 1.3.2+, 1.3.1 works fine.

**Comment by tsdaemon** [comment]
I've faced this issue on Windows with a local version of forked package. Bower do not copy new files from local folder and I need to do manual cache clean every time

**Comment by sheerun** [comment]
Please provide exact steps to reproduce & platform details in new issue.
