### ISSUE TITLE
offline option not working in bower.commands.install

### ISSUE THREAD

**Issue by harrison-t-lm** [bower/bower#1358]
I'm trying to write a grunt task to first try to install my bower packages from the cache, and then if that doesn't work, do it online, without the offline option, but it doesn't recognize the offline option in the first try

i.e. 
bower.commands
                .install([], { offline: true })
                .on('end', function(data) {
                    grunt.log.writeln(data);
                    done();
                })

gives: 
Fatal error: Failed to execute "git ls-remote --tags --heads https://github.com/components/jquery.git", exit code of #128

**Comment by sheerun** [comment]
Bower is deprecated so I'm going to close this
