### ISSUE TITLE
https://bower.herokuapp.com/ is down!

### ISSUE THREAD

**Issue by tony99nyr** [bower/bower#1385]
Every bower package cannot be fetched as of yesterday.  I assume the heroku application needs to be restarted.

Request to https://bower.herokuapp.com/packages/angular failed
Request to https://bower.herokuapp.com/packages/json3 failed
Request to https://bower.herokuapp.com/packages/jquery failed
....

To replicate locally for any application using bower:
1. Clear out bower_components folder
2. bower cache clean
3. bower install

**Comment by tmli3b3rm4n** [comment]
It's down right now too.

**Comment by awsp** [comment]
Seems down to me too. 
Using Google Public DNS 8.8.8.8 and 8.8.4.4

**Comment by cassianoalves** [comment]
It's down again...
Check it out: http://www.websitedown.info/bower.herokuapp.com
https://bower.herokuapp.com/

**Comment by wherewelive** [comment]
+1

**Comment by ricorodriguez** [comment]
+1

**Comment by theyaserfox** [comment]
back to work

**Comment by wherewelive** [comment]
Down again :(

**Comment by sheerun** [comment]
Restarted. This is getting annoying.

**Comment by caio1982** [comment]
Is it back up? Still not getting through from here: http://www.downforeveryoneorjustme.com/http://bower.herokuapp.com/

**Comment by sheerun** [comment]
It crashed again. I have than to switch to 2 dynos 2x. Previously there were some db connection issues with 2 dynos... Maybe there's some connection leak issue in code. I restarted app and hope it won't happen again. I'm waiting for @wibblymat to transfer ownership of bower account, so I can upgrade postgres. Btw. for downtime handling please join: https://gitter.im/bower/bower

**Comment by juanpasolano** [comment]
Apparently is down again right now. :cry:

**Comment by lowe0292** [comment]
Down for me too. :[

**Comment by danielagreen** [comment]
Indeed down again

**Comment by lowe0292** [comment]
Down for me too @juanpasolano. I'm getting **Application Error** when going straight to the failed dependencies in the browser ([example](https://bower.herokuapp.com/packages/angular-animate)).

@sheerun any idea what's going on?

**Comment by deeg** [comment]
Me too, hope this gets fixed soon!

**Comment by cafesanu** [comment]
same here!

**Comment by verokim** [comment]
It's down for me too...

**Comment by jptannus** [comment]
+1
http://www.websitedown.info/bower.herokuapp.com
tested and it is still down

**Comment by deeg** [comment]
It is back up. @sheerun, was very responsive in chat. Thanks!

**Comment by juanpasolano** [comment]
Thanks. Yey! back up again :smile: :heart:

**Comment by jptannus** [comment]
Nice! Thanks!! :D

**Comment by cabloo** [comment]
Thanks for the fast response, bower team!

**Comment by admosity** [comment]
![image](https://cloud.githubusercontent.com/assets/4655972/9527361/af3b8126-4cbc-11e5-9285-eb6b17ebecbb.png)
Appears to be down again :(

**Comment by karlingen** [comment]
Seems to be down again

**Comment by simonealessandrelli** [comment]
Down again yes!

**Comment by pjcliche** [comment]
Confirmed, down.

**Comment by priyank2005** [comment]
## Following to know when it is up!!

**Comment by alshakero** [comment]
Anybody facing this today?

**Comment by alshakero** [comment]
Fixed by updating bower to 1.8.2 (`npm i -g bower`).

**Comment by ErikSvedin** [comment]
@alshakero 
check this: https://twitter.com/bower/status/918073147789889536

**Comment by grptx** [comment]
updating bower not solve to me

**Comment by sheerun** [comment]
@grptx It might be cause you have custom `.bowerrc` with `bower.herokuapp.com` url.

**Comment by Jazzepi** [comment]
I was able to fix this for us by adding the new registry into the .bowerrc file. This helped get our team up and running since we can't easily update all the bower dependencies.

```
{
  "registry": {
    "search": [
      "https://registry.bower.io"
    ]
  }
}
```

**Comment by sheerun** [comment]
Proper entry is:

```
{
  "registry": "https://registry.bower.io"
}
```

**Comment by grptx** [comment]
@sheerun you right
now it's all ok thanks
