### ISSUE TITLE
Option for limiting simultaneous checkouts

### ISSUE THREAD

**Issue by anton-rudeshko** [bower/bower#1414]
We have a lot of git dependencies (currently 79) checked out by bower and this can easily lay down our git server because of huge load on cpu (especially without local cache).

Can we define an option for bower to limit simultaneous checkouts? Like so:

``` bash
$ bower install --parallel=3
```

Thanks

**Comment by hekinadedul** [comment]
👍

**Comment by sheerun** [comment]
Bower is deprecated now, and in maintenance mode. Because of this we won't implement new features like this one. We recommend switching to Yarn or npm, and migrating with [bower-away](https://github.com/sheerun/bower-away)
