### ISSUE TITLE
Bower always install components in a "app" folder

### ISSUE THREAD

**Issue by jgoux** [bower/bower#1432]
Hello,
I never had problem with bower until today. I don't know how but each time I do "bower install", the bower_components folder is wrapped inside a "app" folder.
So I end up with "app/bower_components/angular".
To be sure, I put this bower.json _alone_ in a directory : 

``` json
{
    "name": "bower-test",
    "dependencies": {
        "angular": "~1.2.20"
    }
}
```

Then I simply type : "bower install"
And the installation is : app/bower_components/angular instead of bower_components/angular

Any idea ? ^^

EDIT : I put a .bowerrc inside my folder with bower_components as default and it works (ok so far it's normal). 
Is the default folder "app/bower_components" ?

**Comment by leoman730** [comment]
@sheerun This works for me. Thanks.

**Comment by brendan** [comment]
doh!  happened to me today.  parent folder had a .bowerrc in it due to an earlier accidental yeoman invocation.
