### ISSUE TITLE
bower init: Apply defaults from .bowerrc

### ISSUE THREAD

**Issue by mcandre** [bower/bower#1438]
When I run `bower init`, I don't want to be prompted for _license_ and other values each time; I want any values defined in a .bowerrc file to be applied, and the prompt for them skipped.

**Comment by sheerun** [comment]
Bower is deprecated now, and in maintenance mode. Because of this we won't implement new features like this one. We recommend switching to Yarn or npm, and migrating with [bower-away](https://github.com/sheerun/bower-away)
