### ISSUE TITLE
Bower proxy issue: Failed to execute "git ls-remote..."

### ISSUE THREAD

**Issue by BOFH2k** [bower/bower#1443]
In a proxied Environment on Win7 Pro with the following settings in .bowerrc:
{
"proxy":"http://XYZ:password@proxy:8080",
"https-proxy":"http://XYZ:password@proxy:8080"
}
we get:
C:\Users\XYZ\Eigene Apps\raw>bower install
bower not-cached    https://github.com/eligrey/canvas-toBlob.js.git#*
bower resolve       https://github.com/eligrey/canvas-toBlob.js.git#*
bower not-cached    https://github.com/angular/bower-angular.git#1.2.14
bower resolve       https://github.com/angular/bower-angular.git#1.2.14
bower not-cached    https://github.com/mbostock/d3.git#~3.4.3
bower resolve       https://github.com/mbostock/d3.git#~3.4.3
...
bower not-cached    https://github.com/marijnh/CodeMirror.git#4.0.1
bower resolve       https://github.com/marijnh/CodeMirror.git#4.0.1
bower ECMDERR       Failed to execute "git ls-remote --tags --heads https://gith
ub.com/twbs/bootstrap.git", exit code of #128

Additional error details:
fatal: unable to access 'https://github.com/twbs/bootstrap.git/': Failed connect
 to github.com:443; No error

Bower job definition can be found here:
https://github.com/densitydesign/raw/blob/master/bower.json 

Manuall call of the offending command works just fine (with git configured for proxy use as well):
C:\Users\XYZ\Eigene Apps\raw>git ls-remote --tags --heads https://github.com/twbs/bootstrap.git

**Comment by venkataraghu** [comment]
I got the same issue but on port 80. However git clone is working good. And, my system is not under a proxy.

λ git ls-remote --tags --heads git://github.com/bestiejs/json3.git
fatal: unable to connect to github.com:
github.com[0: 192.30.252.130]: errno=No error

**Comment by antigremlin** [comment]
@venkataraghu, see my comment on #1574 and this post on stackoverflow:
<http://stackoverflow.com/questions/1722807/git-convert-git-urls-to-http-urls>

**Comment by LoganVS** [comment]
@antigremlin Fixed my issue- thank you!

**Comment by punnashivakrishna** [comment]
bower angular#~1.6.0           ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/angular/bower-angular.git", exit code of #128 fatal: unable to access 'https://github.com/angular/bower-angular.git/': error se
tting certificate verify locations:   CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt   CApath: none

Additional error details:
fatal: unable to access 'https://github.com/angular/bower-angular.git/': error setting certificate verify locations:
  CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none

**Comment by punnashivakrishna** [comment]
>npm install -g bower.

i'm getting error:


'CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command,
operable program or batch file.
C:\Users\shivakrishna.punna\AppData\Roaming\npm\bower -> C:\Users\shivakrishna.punna\AppData\Roaming\npm\node_modules\bower\bin\bower
C:\Users\shivakrishna.punna\AppData\Roaming\npm
`-- bower@1.8.0

**Comment by thebiltheory** [comment]
I had the same-ish issue. 

`Fatal error: Failed to execute "git ls-remote --tags --heads git@github.com:grantila/awesome-phonenumber.git", exit code of #128`

Fixed it by adding an SSH Key to my account.

**Comment by avinashgharepayu** [comment]
Fatal error: Failed to execute "git ls-remote --tags --heads git@github.com:grantila/awesome-phonenumber.git", exit code of #128   I have same issue while running command "sudo bower install --allow-root"  

Content In bower json

{
  "name": "myProject",
  "description": "an Application",
  "main": "app.js",
  "authors": [
    "avinash"
  ],
  "license": "MIT",
  "homepage": "",
  "private": true,
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "angular": "~1.6.6",
    "angular-sanitize": "~1.6.6",
    "angular-animate": "~1.6.6",
    "ace-builds": "https://github.com/ajaxorg/ace-builds.git#~1.2.2",
    "angular-aria": "~1.4.8",
    "angular-backtop": "*",
    "angular-bootstrap": "^2.1.3",
    "angular-hotkeys": "chieffancypants/angular-hotkeys#^1.7.0",
    "angular-flexslider": "~1.3.2",
    "angular-masonry": "^0.16.0",
    "angular-material": "^1.0.9",
    "angular-bootstrap-toggle-switch": "^0.5.6",
    "angular-material-icons": "https://github.com/klarsys/angular-material-icons.git#~0.6.0",
    "angular-recaptcha": "~2.2.4",
    "angular-clipboard": "~1.2.1",
    "angular-translate": "^2.12.1",
    "angular-toastr": "^2.0.0",
    "angular-ui-sortable": "~0.13.4",
    "angular-ui-select": "^0.18.1",
    "angular-ui-tinymce": "https://github.com/angular-ui/ui-tinymce.git#^0.0.16",
    "angular-ui-router": "^0.3.2",
    "angularjs-imageupload-directive": "https://github.com/Mischi/angularjs-imageupload-directive.git",
    "angular-ui": "~0.4.0",
    "AngularJS-Toaster": "angularjs-toaster#^2.0.0",
    "angulartics-google-analytics": "^0.2.1",
    "animate.css": "^3.5.2",
    "bootstrap-sass": "^3.3.7",
    "bourbon": "^4.2.7",
    "fancybox": "^3.1.20",
    "international-phone-number": "^0.0.16",
    "jquery-slimscroll": "^1.3.8",
    "font-awesome": "^4.6.3",
    "jStorage": "https://github.com/andris9/jStorage.git#^0.4.12",
    "js-beautify": "https://github.com/beautify-web/js-beautify.git#~1.5.10",
    "moment": "^2.17.1",
    "ngInfiniteScroll": "^1.3.0",
    "ngmap": "^1.17.3",
    "ngDraggable": "^0.1.10",
    "ngMeta": "^0.3.9",
    "peity": "https://github.com/benpickles/peity.git#^3.2.0",
    "smart-app-banner": "^1.3.0",
    "svg-morpheus": "https://github.com/alexk111/SVG-Morpheus.git#~0.1.8",
    "lodash": "^4.16.0",
    "ui-router": "latest",
    "tinymce": "4.3.12",
    "angular-ui-swiper": "^2.3.6",
    "textAngular": "^1.5.16",
    "cleave.js": "^0.7.10",
    "angular-promise-buttons": "^0.1.21",
    "angular-scroll": "^1.0.2",
    "swiper": "^4.0.5",
    "bower": "*",
    "install": "^1.0.4",
    "ngclipboard": "^1.1.3"
  },
  "resolutions": {
    "angular": "1.6.6"
  }
}

**Comment by whitelowrie** [comment]
> I had the same-ish issue.
> 
> `Fatal error: Failed to execute "git ls-remote --tags --heads git@github.com:grantila/awesome-phonenumber.git", exit code of #128`
> 
> Fixed it by adding an SSH Key to my account.

Can you tell me how to add an SSH Key to account

**Comment by whitelowrie** [comment]
> Yes, #1426. You can probably set HTTP_PROXY and HTTPS_PROXY env variables as a workaround.

I set the http_proxy and https_proxy, but is useless, I use windows

```json
{
    "directory": "bower_components",
    "registry": "http://bower.herokuapp.com",
    "proxy":"http://xxx-proxy.xxx.com:8080",
    "https-proxy":"https://xxx-proxy.xxx.com:8080",
    "strict-ssl": false
}
```
```java
bower angular-resource#1.7.7                                ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/angular/bower-angular-resource.git", exit code of #128 fatal: unable to acces
s 'https://github.com/angular/bower-angular-resource.git/': error setting certificate verify locations:   CAfile: /mingw64/ssl/certs/ca-bundle.crt   CApath: none

Additional error details:
fatal: unable to access 'https://github.com/angular/bower-angular-resource.git/': error setting certificate verify locations:
  CAfile: /mingw64/ssl/certs/ca-bundle.crt
  CApath: none
```
above, I think the CAfille path is wrong, but I don't known how to fix it, please help me~

**Comment by whitelowrie** [comment]
> bower angular#~1.6.0 ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/angular/bower-angular.git", exit code of #128 fatal: unable to access 'https://github.com/angular/bower-angular.git/': error se
> tting certificate verify locations: CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt CApath: none
> 
> Additional error details:
> fatal: unable to access 'https://github.com/angular/bower-angular.git/': error setting certificate verify locations:
> CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
> CApath: none

Do you fix the issue? I have the same problem.
