### ISSUE TITLE
Use .netrc when logging into private repositories

### ISSUE THREAD

**Issue by gianebao** [bower/bower#1456]
I there a way to pull private repositories? I have a .netrc which works fine for other applications like composerphp and and git but does not seem to work for bower.

**Comment by jclem** [comment]
@benschwarz Handling private git repositories with git+ssh isn't possible in all circumstances. I have a build process where I generate an on-the-fly .netrc file during a Heroku build process. This is really one of the only secure ways to use a private GitHub repo in a deploy process like this. It allows me to clone private NPM packages from GitHub. I'd like to be able to do this for bower, as well.

**Comment by froucher** [comment]
Hello, I do not agree with this issue, I have just been able to use my own .netrc with a private repository (in stash). Steps:

1. Save git pass, (please add the vars $GIT... to your environment)
cat << EOF >> .netrc
machine $GITMACHINE
        login $GITUSER
        password $GITPASS
EOF

2.- Update PATH
export PATH=`pwd`:$PATH

3.- npm install bower
npm install bower

4.- execute bower with $HOME substitution
HOME=$(pwd) ./node_modules/bower/bin/bower install

I hope this will help you.

**Comment by sheerun** [comment]
You can now implement it using a [Pluggable Resolver](http://bower.io/docs/pluggable-resolvers/) feature of Bower :)

**Comment by wenqingyu** [comment]
Is there a similar way to get authentication with public key instead of name / password method?
