### ISSUE TITLE
bower search should not list everything

### ISSUE THREAD

**Issue by rayshan** [bower/bower#1462]
Slow & not super helpful, should show a help message, e.g.:

"Please provide something for Bower to search with. E.g. `bower search angular`"

**Comment by mbbaig** [comment]
Hi I'd like to start working on this bug. Could I get some pointers in the right direction?

**Comment by mbbaig** [comment]
@rayshan @sheerun anyone wanna chime in on whether I should submit a PR for this?

**Comment by sheerun** [comment]
@mbbaig Yes, but output for `--json` mode should stay the same :)

**Comment by BenMann** [comment]
No idea which PR fixed it, but this no longer seems to be an issue.
Currently running `bower search` without providing a `<package name>` results in this:
```
Usage:

    bower search <name> [<options>]

Options:

    -h, --help              Show this help message
    Additionally all global options listed in 'bower help' are available

Description:

    Finds all packages or a specific package.
```
Which seems fine!
That being said, I'll close this issue. Yell at me if I'm wrong or missed something! :v:
