### ISSUE TITLE
Clean install after changing branches

### ISSUE THREAD

**Issue by dgieselaar** [bower/bower#1466]
Hi all,

We're currently running into an issue where we are frequently switching between branches with different versions of packages in bower.json. Specifically, angular and various modules (such as angular-animate, angular-route, etc).

Unfortunately, when running `bower install` after switching between versions, bower (incorrectly) detects a dependency conflict. Let's say it changes from:

``` json{
    "dependencies": {
        "angular": "1.2.20",
        "angular-cookies": "1.2.20",
        "angular-route": "1.2.20"
    }
```

to:

``` json{
    "dependencies": {
        "angular": "1.2.21",
        "angular-cookies": "1.2.21",
        "angular-route": "1.2.21"
    }
```

This causes bower to (wrongly) detect a dependency conflict:

> Unable to find a suitable version for angular, please choose one:
>     1) angular#1.2.20 which resolved to 1.2.20 and is required by angular-cookie
> s#1.2.20, angular-route#1.2.20
>     2) angular#1.2.21 which resolved to 1.2.21 and is required by angular-cookies#1.2.21, angular-route#1.2.21

Now, we're using deploy scripts which are unable to deal with the prompt. Adding a resolution to bower.json is not an option either, as this is overwritten by bower itself as soon as the install doesn't need one (which is a baffling choice to me, but as I understand is being fixed). `bower install --force` doesn't help either, as it always installs the latest version of the conflicting packages (as far as I can see). `bower cache clean` and `bower prune` do little to alleviate this problem as well. Bower has no 'uninstall all' command either, so the only option left would be to get the components dir from .bowerrc and `rm -rf` it, but I'd rather not.

What is the recommended approach for this issue?

**Comment by reda-alaoui** [comment]
Hello,

We also encoutered this issue with bower 1.7.9.
Any update?

**Comment by sheerun** [comment]
Bower is now deprecated so this won't be implemented
