### ISSUE TITLE
--force does not force an exact version of a component

### ISSUE THREAD

**Issue by constfun** [bower/bower#1472]
As it stands now, there is no way to install an exact version of a component in a non-interactive script.

The actual bug for me is that --force angular#1.2.18 is not forceful at all and will install angular 1.2.22 (latest.)

**Comment by sheerun** [comment]
Bower is deprecated now, and in maintenance mode. Because of this we won't implement new features like this one. We recommend switching to Yarn or npm, and migrating with [bower-away](https://github.com/sheerun/bower-away)
