### ISSUE TITLE
`bower install` installs relative to cwd, not .bowerrc or bower.json

### ISSUE THREAD

**Issue by Rich-Harris** [bower/bower#1477]
If I'm in a subfolder of my project, and I run `bower install x`, the package will be installed to `subfolder/bower_components/x` instead of `bower_components/x`, even if there's a `bower.json` or `.bowerrc` in the project root.

If I have a `.bowerrc` with a custom `directory` setting (e.g. `"vendor"`), it will be installed to `subfolder/vendor/x`!

That seems like a bug to me, what does everyone else think? I can't imagine any situation where I'd set a custom `directory` in my project root but want it to be relative to an arbitrary subfolder.

**Comment by drGrove** [comment]
This should at least be considered as a feature for future development.

**Comment by mjschlot** [comment]
For anybody who stumbles upon this thread, take a look at:
https://github.com/bower/bower/issues/1763

**Comment by pravinbashyal** [comment]
i am annoyed by this feature as well...
