### ISSUE TITLE
Ignore metadata part of semver on ranges

### ISSUE THREAD

**Issue by elidupuis** [bower/bower#1486]
I just installed bootstrap-sass [v3.2.0+1](https://github.com/twbs/bootstrap-sass/releases/tag/v3.2.0%2B1). Apparently that `+1` is actually legit in terms of [SemVer](http://semver.org/) (see line item 10 under the Spec section).

Anyway, running `bower install --save bootstrap-sass-official` installed properly and wrote `"bootstrap-sass-official": "~3.2.0+1"` to `bower.json` as expected. **However, if I run `bower install` with that value in `bower.json` it fails**:

``` bash
bower bootstrap-sass-official#~3.2.0+1     ENORESTARGET Tag/branch ~3.2.0+1 does not exist
```

I'm not sure if this is even a Bower issue specifically, but it seems like the `--save` flag should ignore any version metadata that is after the `+`.

Thoughts?

**Comment by lazyhammer** [comment]
That's because Bower depends on node-semver@^2.3.0 and there is a bug, that was fixed in [4.0](https://github.com/npm/node-semver/commit/6d7dadf30e822dd9d5aced4cc3a837c3a07c971f).

**Comment by jasny** [comment]
@sheerun In practice the metadata is also being used to version forks, see https://github.com/mojombo/semver/issues/17

**Comment by sheerun** [comment]
Bower is deprecated now, and in maintenance mode. Because of this we won't implement new features like this one. We recommend switching to Yarn or npm, and migrating with [bower-away](https://github.com/sheerun/bower-away)
