### ISSUE TITLE
bower.herokuapps.com - static ip needed behind corporate firewall

### ISSUE THREAD

**Issue by jsdevel** [bower/bower#1489]
I'm using Jenkins to build my app behind a corporate firewall.  The server Jenkins is running on is extremely locked down by firewall restrictions.  Fortunately I'm able to give my network admins static ips and ports for urls on an as needed basis.  I've done this for github.com, but it looks like bower calls `bower.herokuapps.com` for the github url to fetch from.

Is bower.herokuapps.com guaranteed to have a static ip?

**Comment by samdunne** [comment]
Any progress on this?

**Comment by sheerun** [comment]
I'm afraid that with our traffic and sponsored budget of $250/month for heroku services, we can't afford static IP for heroku hosting. We already use $240/month for three 2x dynos, and "Standard 0" postgresql database.

**Comment by sheerun** [comment]
There are about 36 000 requests per hour.

**Comment by samdunne** [comment]
For the sort of money would something like digital ocean/aws not be more cost effective? Just curious.

**Comment by jsdevel** [comment]
Incidentally, we've found `npm` to be a suitable alternative to `bower` for the following reasons:

1. `npm` has a static ip.
2. Client side packages are moving to `npm` in droves.
3. `npm` + `browserify` works out very nicely.

**Comment by Vaccano** [comment]
@jsdevel Where did you find (or what is) the static ip for `npm`?  (I am having the same problem.)

**Comment by samccone** [comment]
@sheerun any way we can reach out to heroku and see if they would be willing to sponsor us for a static IP?

**Comment by jsdevel** [comment]
@Vaccano Using `ping npmjs.org` -> `PING npmjs.org (54.187.170.181) 56(84) bytes of data.`

**Comment by Vaccano** [comment]
@jsdevel Thank you!

**Comment by sheerun** [comment]
First we'd need to estimate traffic, but most likely it would be more than 5M requests per month and we'd need to get Enterprise Proximo which costs 1250$/mo. Currently we have budget of $250/mo.

Sincerely, I really doubt heroku agrees to that.

**Comment by samccone** [comment]
Heh, fair fair, just asking :wink: I guess that means that we can just close this right?

**Comment by sheerun** [comment]
Otherwise we'd need to migrate entirely out of Heroku, and find new sponsor.

Another possibility is to ask someone to host 3rd party static IP proxy. Like https://www.quotaguard.com
