### ISSUE TITLE
CLI Bug: --quiet implemented incorrectly

### ISSUE THREAD

**Issue by bdkjones** [bower/bower#1493]
Run this command to list the locally installed components:

```
bower list -q
```

Bower runs successfully, exits with a `0` code and prints absolutely nothing. Now run this command:

```
bower list
```

This time, Bower will correctly print the desired output. 

The point of `--quiet` is to tell Bower that we don't want _extraneous_ printing. It means, "Print only the critical stuff; leave off all the baggage". 

`--quiet` should NOT mean, "Print nothing, ever."

When we run a command that explicitly asks for some output, that output should be printed. The quiet flag should suppress any _extra_ information (such as stack traces, progress updates, log messages, etc) but it should NOT suppress the printing of information we asked for (in this case, the result from the `list` command).

This is happening in Bower 1.3.9.

**Comment by sheerun** [comment]
Bower is deprecated and in maintenance mode, we only fix critical/security issues, no changes
