### ISSUE TITLE
merge bower into npm, why aren't we using npm?

### ISSUE THREAD

**Issue by jokeyrhyme** [bower/bower#1520]
After reading through https://github.com/bower/bower/issues/1102#issuecomment-55679643 , it occurred to me that Bower and npm have distinctly different designs, strengths and weaknesses.

[NPM stands for "no problem, meatbag"](https://twitter.com/npmjs/status/347062349540237312) so there's nothing Node.JS or even JavaScript specific about it. There's some recent-ish precedent for using it for front-end packages:
- http://blog.kewah.com/2014/npm-as-a-front-end-package-manager/
- http://dontkry.com/posts/code/using-npm-on-the-client-side.html

I listened to http://nodeup.com/seventy , and the npm maintainers seemed open to pull requests that address reasons why people use bower over npm, in order to unify the community.

If possible, I think it would be terrific to have a serious discussion about:
- why do people choose Bower?
- why do people choose npm?
- is much interest on this side regarding a unified community?
- what would need to be implemented in npm in order to meet the needs of the Bower community?

**Comment by jokeyrhyme** [comment]
http://blog.npmjs.org/post/110924823920/npm-weekly-5:
> With npm@3, your node_modules directory will be a lot flatter. All of your dependencies and most of your subdependencies (and (sub)+dependencies) will be sitting next to each other at the top level. Only when there are conflicts will modules be installed at deeper levels.
Nice!

**Comment by jokeyrhyme** [comment]
Possible related discussion: https://github.com/bower/bower/issues/1600

**Comment by patrickkettner** [comment]
how is that related?

**Comment by jokeyrhyme** [comment]
@patrickkettner well, shrinkwrap is something npm does, and it's functionality that is wanted in bower. I figured it was worth linking to as far as the npm/bower discussion goes...

**Comment by patrickkettner** [comment]
I believe that is about using npm's shrinkwrapping feature for the bower binary, not including a feature in the library itself.

**Comment by jokeyrhyme** [comment]
NPM 3 is in beta, and will be released soon:
http://blog.npmjs.org/post/122450408965/npm-weekly-20-npm-3-is-here-ish

NPM 3 installs dependencies as flat as possible, unless there are conflicts:
https://github.com/npm/npm/blob/multi-stage/CHANGELOG.md#flat-flat-flat

Once NPM 3 drops the "beta" flag, there'll likely be little reason to favour Bower.

**Comment by nicklasb** [comment]
I would recommend you people to take a look at JSPM/SystemJS, it really makes up for all the differences.

**Comment by donaldpipowitch** [comment]
Right, but jspm is focused on JS, right ? I always liked Bower for being language agnostic, so it can be used with Less easily. But I really hope these non-js cases are solved with npm in the next years.

**Comment by nicklasb** [comment]
Not sure what you mean by language-agnostic. There is no client side code on the web that isn't Javascript. Even less less.js. (pun intended) 

While jspm *can* serve any file, it has plug-ins for most things. Even [less](https://github.com/Aaike/jspm-less-plugin). Puns galore. :-)

**Comment by patrickkettner** [comment]
Language agnostic means css, html, plaintext, C, java. It just serves an
endpoint.

**Comment by nicklasb** [comment]
Oh, I know what the expression means, I was not understanding in what way jspm wasn't.
Sorry, could perhaps been clearer.

**Comment by donaldpipowitch** [comment]
If I'm not wrong jspm has one main file while Bower always supported an array of main files. Very handy, because my Web Components, directives, whatever often come with a JS _and_ Less file (sometimes even more). That's one thing why I initially liked Bower...

**Comment by nicklasb** [comment]
Well, a jspm-package has one main file, an entry point. But that doesn't mean it can load multiple files. 
For example an ES 6 `import "packagename/css/cssfile.css!"` imports a css file(if you have the css plugin). 

And you can obviously always manually load it directly from the jspm_packages/ folder in a `<link href="/jspm-packages/packagename/css/cssfile.css" rel="stylesheet" type="text/css" media="print">`.

A package in jspm/npm/github can contain any kind of file just like bower can. Or am I not understanding what you mean?

**Comment by donaldpipowitch** [comment]
I think you understand what I mean, but your examples show the problem: if I start to manually import certain files I loose a lot of the benefits of a package manager. If this would be enough we could have used npm all the time.

**Comment by jokeyrhyme** [comment]
@donaldpipowitch (and @nicklasb @patrickkettner): is there an issue filed against NPM for your use case and what is missing? I'm sure there are people in the NPM community who sympathise with you but won't find these comments here in the Bower project (do link back here if you file anything).

**Comment by nicklasb** [comment]
But I don't want to automatically load *all* files, as that would be detrimental to performance and increase server load. I want to load them when I need them. 

That is why I have the import-statements in the code, and that is one of the main benefits of SystemJS and modules. 
Also, with good integration, the import statements tell my IDE what to show to me. ES 6 modules and import statements are a huge feature, something I have waited years for to get on the front end.

Using jspm you can then not only install (`jspm install jquery`) the module, a config file is automatically generated that is used in deployment to satisfy run time dependencies. That is another thing I like about it, the clear distinction between run time and design time dependencies.

**Comment by nicklasb** [comment]
@jokeyrhyme : I am only trying to get sympathy, but clearing up what I feel is something of a misunderstanding, except from having multiple main entry points, which I do not really see the point with, especially with ES 6 and all.

**Comment by Enelar** [comment]
Sorry for being impolite, but could you clarify strong and weak points of both for end-user?
I read whole thread. But im not sure, is flat-tree good or bad, and when, and so on.
I think wiki page will be great.

**Comment by PowerKiKi** [comment]
@Enelar if you don't have a strong opinion on the matter go with npm 3 (`npm install -g npm@3.0-latest`) and forget about bower. Multiplying package manager in your project is not a good idea for your workflow and chances are very high that you will require npm for something anyway (build tools such as grunt/gulp or other things).

**Comment by Enelar** [comment]
@PowerKiKi well, thanks for quick respond. That was ultimatum. Like "this repository IS DEPRECATED".
Rather than being rude, and taking your advice, i will humble wait for comparison, or trying to dig it by my own.

**Comment by jokeyrhyme** [comment]
@Enelar: start with NPM, as @PowerKiKi says pretty much every JavaScript-related project is going to need something from there anyway
_Only_ use bower as well if you have a problem that can't be solved with NPM alone.

Bower had a flat-tree from the beginning, and NPM only just got it with v3.x. Flat tree is more convenient for front-end development (if you have to put URLs in HTML link and script tags, etc). So bower and NPM are now even on this score.

I can't remember, but I think Bower handles unpublished projects via direct git URLs a little bit better than NPM. The NPM folks want to improve this, I'm not sure if they are working on it actively or not. If you only use published versions of packages then this doesn't apply to you.

People here aren't being rude or wishing that bower developers would give up or anything horrible like that. The objective consensus is that NPM is rapidly catching up to bower in terms of front-end friendliness, and likely has _already_ caught up for the majority of projects. NPM wouldn't be as awesome as it is today without the competition from Bower.

**Comment by donaldpipowitch** [comment]
Well said!

**Comment by shehi** [comment]
:+1:

**Comment by calidion** [comment]
I don't think the mixing of frontend and backend into one package management will make life any easier.
bower still has its value to go.
I think time will prove.
if i want to use bootstrap in my frontend project, and i don't need bootstrap been installed when i run `npm install` to start my node project. 

they are totally different things.

**Comment by benallfree** [comment]
I think @calidion is correct, it's been two years since NPM started talking about ecosystems and it must be a taller order than the community anticipated. Bower is ready now, available now, and perfect for representing the frontend ecosystem :) The [pain points](http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging) highlighted earlier are very accurate.

**Comment by almereyda** [comment]
Given the explanations in https://bower.io/blog/2017/how-to-migrate-away-from-bower/ this issue could be renamed to *Migrate bower (projects) to yarn.*.

**Comment by sheerun** [comment]
Yeah, Yarn is now possible way to go
