### ISSUE TITLE
Make prune command more verbose

### ISSUE THREAD

**Issue by FarSeeing** [bower/bower#1521]
Up to now `prune` command does not output anything when there are no packages to remove. It would be nice to output the status like:
1. if any packages were removed — list them or just output`x packages removed`,
2. if no packages were removed — output something like `nothing to remove`.

**Comment by sheerun** [comment]
Bower is deprecated now, and in maintenance mode. Because of this we won't implement new features like this one. We recommend switching to Yarn or npm, and migrating with [bower-away](https://github.com/sheerun/bower-away)
