### ISSUE TITLE
Add support for bower.cson

### ISSUE THREAD

**Issue by lipis** [bower/bower#1541]
Atom is using `.cson` format for their configuration files and Grunt supports `Gruntfile.coffee` along with the `Gruntfile.js`.

The main advantage is that you don't need to have commas so it is very easy to rearrange stuff without always removing the last comma or adding it. Plus you don't have the whole noise of the `}}}` in the end.

Here is a simple example on how more readable it could be:

``` json
{
  "name": "hello",
  "dependencies": {
    "bootstrap": "~3",
    "jquery": "~2",
    "moment": "~2"
  },
  "exportsOverride": {
    "bootstrap": {
      "js": "js/*.js",
      "less": "less/*.less",
      "font": "fonts/*"
    },
    "jquery": {
      "js": "dist/jquery.js"
    },
    "moment": {
      "js": "*.js"
    }
  }
}
```

``` coffeescript
name: "hello"
dependencies:
  bootstrap: "~3"
  jquery: "~2"
  moment: "~2"

exportsOverride:
  bootstrap:
    js: "js/*.js"
    less: "less/*.less"
    font: "fonts/*"

  jquery:
    js: "dist/jquery.js"

  moment:
    js: "*.js"
```

**Comment by ccorcos** [comment]
+1 for CSON. Why not?

**Comment by benschwarz** [comment]
@ccorcos, @paulirish already covered it. The biggest reason is that allowing CSON in bower.json will break tools that use bower packages. It isn't worth the fallout that it'd cause.
