### ISSUE TITLE
bower link does not work with dependencies of dependencies

### ISSUE THREAD

**Issue by raDiesle** [bower/bower#1545]
In my use-case I would like to use bower link for more than one dependency,
so for nested dependencies:

My structure:

moduleB
moduleA
->  bower.json defines dependency: moduleB
bower link moduleB
moduleC
-> bower link moduleA
-> bower link moduleB

bower link moduleA will throw an error message, because it cannot find moduleB,
but will create the link ( what is expected).

**Comment by r0zar** [comment]
You can work around this by linking to both modules from the top level one.
- moduleA --bower-link--> moduleB
- moduleA --bower-link--> moduleC

Not the best solution, but if you don't have the option of working with B and C linked until C is published, it may be the only one.

**Comment by sheerun** [comment]
Bower is in maintenance mode and we suggest switching to Yarn which supports such advanced features
