### ISSUE TITLE
Bower-installed projects become undeletable on Windows because dependencies-of-dependencies create excessively long path names

### ISSUE THREAD

**Issue by BillyWM** [bower/bower#1556]
I just had this problem installing angular-seed. When I changed my mind about using angular-seed for my project and tried to delete it, I found that I couldn't remove 11,000+ files because so many dependencies had other dependencies with "bower_components" and "node_modules" directories of their own. This created paths so long that windows couldn't delete them (This solution - creating a virtual drive - worked, for anyone wondering http://superuser.com/questions/755298/how-to-delete-a-file-with-a-path-too-long-to-be-deleted)

How to fix this? A project with enough nested dependencies will eventually cause this problem, but I'd suggest choosing a shorter directory name than bower_components as a start.

**Comment by dougal83** [comment]
Thanks Guys.  Just had same problem.
