### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by fcamblor** [bower/bower#156]
I will present bower in a conference soon (mid december), where I won't have any internet access.

Although I fully understand why bower should require internet access most of the time, I don't know why it fails when it tries to install some cached lib without any internet connexion

```
bower error getaddrinfo ENOENT
```

It would be nice if we could provide some --offline argument to bower CLI, allowing to : 
- skip repository indexes update (during bower search) 
- consider using cached components (when available) when installing them on current project

WDYT ?

**Comment by zdary** [comment]
+1 for this feature

**Comment by vprasanth** [comment]
Since it isn't explicitly stated here, and this is a pretty top hit on Google, going to go ahead and say, as of 1.8.x, `--offline` is available to you.
