### ISSUE TITLE
Add warning about ~/.bowerrc

### ISSUE THREAD

**Issue by silvenon** [bower/bower#1560]
I don't think there's any documentation about this, but creating a `~/.bowerrc` changes Bower's defaults and it can be pretty frustrating for many people not knowing what is going on. In our Yeoman generators we had to add local `.bowerrc`s to override any potential global to the initial value.

**Comment by sheerun** [comment]
Bower is deprecated now, and in maintenance mode. Because of this we won't implement new features like this one. We recommend switching to Yarn or npm, and migrating with [bower-away](https://github.com/sheerun/bower-away)
