### ISSUE TITLE
NPM install fail

### ISSUE THREAD

**Issue by fulup-bzh** [bower/bower#1563]
I tried to install on two machines Bower with NPM and in both case it fails on dependencies.
See here after message. If then try to install the first dependency manually with
npm  install strip-ansi it works, but I get version 2.0, when bower package.json point on version 1.1 !!!

If you check Package.json, all dependencies have fixed version number. I'm surprise npm auto install can work anywhere, does it ?

Now if I download the last version from git, extract from Package.JSON dependencies. Remove version with text editor and install all of them ignoring version. Then "bower install" fail with "ENOENT No bower.json present", when I have a module ./node_modules/bower-json on disk.

Would be nice, is on a clean machine, the installation was working out of the box, looks like you've broken the standard NPM install process. Note I tried on CentOS6 and OpenSuse13.1, on both case it fail. One has npm-2.0.0 the other one a V1.3.6.

Here after log message, did I mess up strongly ?

Fulup

(107/107) Installation: npm - 2.0.0-1.1 ..............................................................................................[fait]
fulup@fulup-desktop:~/workspace/PHP> sudo npm install -g bower
/usr/bin/bower -> /usr/lib/node_modules/bower/bin/bower
npm WARN unmet dependency /usr/lib/node_modules/columnify requires strip-ansi@'^1.0.0' but will load
npm WARN unmet dependency /usr/lib/node_modules/strip-ansi,
npm WARN unmet dependency which is version 2.0.0
npm WARN unmet dependency /usr/lib/node_modules/http-signature requires assert-plus@'0.1.2' but will load
npm WARN unmet dependency /usr/lib/node_modules/assert-plus,
npm WARN unmet dependency which is version 0.1.5
npm WARN unmet dependency /usr/lib/node_modules/http-signature requires asn1@'0.1.11' but will load
npm WARN unmet dependency /usr/lib/node_modules/asn1,
npm WARN unmet dependency which is version 0.2.2
npm WARN unmet dependency /usr/lib/node_modules/http-signature requires ctype@'0.5.2' but will load
npm WARN unmet dependency /usr/lib/node_modules/ctype,
npm WARN unmet dependency which is version 0.5.3
npm WARN unmet dependency /usr/lib/node_modules/npm requires archy@'0' but will load
npm WARN unmet dependency /usr/lib/node_modules/archy,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency /usr/lib/node_modules/npm requires ini@'~1.2.0' but will load
npm WARN unmet dependency /usr/lib/node_modules/ini,
npm WARN unmet dependency which is version 1.3.0
npm WARN unmet dependency /usr/lib/node_modules/npm requires init-package-json@'~1.0.0' but will load
npm WARN unmet dependency /usr/lib/node_modules/init-package-json,
npm WARN unmet dependency which is version 1.1.0
npm WARN unmet dependency /usr/lib/node_modules/npm requires npmconf@'~2.0.8' but will load
npm WARN unmet dependency /usr/lib/node_modules/npmconf,
npm WARN unmet dependency which is version 2.1.0
npm WARN unmet dependency /usr/lib/node_modules/npm requires opener@'~1.3.0' but will load
npm WARN unmet dependency /usr/lib/node_modules/opener,
npm WARN unmet dependency which is version 1.4.0
npm WARN unmet dependency /usr/lib/node_modules/npm requires request@'~2.42.0' but will load
npm WARN unmet dependency /usr/lib/node_modules/request,
npm WARN unmet dependency which is version 2.44.0
npm WARN unmet dependency /usr/lib/node_modules/npm requires semver@'~4.0.0' but will load
npm WARN unmet dependency /usr/lib/node_modules/semver,
npm WARN unmet dependency which is version 3.0.1
npm WARN unmet dependency /usr/lib/node_modules/npm requires sha@'~1.2.1' but will load
npm WARN unmet dependency /usr/lib/node_modules/sha,
npm WARN unmet dependency which is version 1.3.0
npm WARN unmet dependency /usr/lib/node_modules/npm-registry-client requires retry@'0.6.0' but will load
npm WARN unmet dependency /usr/lib/node_modules/retry,
npm WARN unmet dependency which is version 0.6.1
npm WARN unmet dependency /usr/lib/node_modules/request requires qs@'~1.2.0' but will load
npm WARN unmet dependency /usr/lib/node_modules/qs,
npm WARN unmet dependency which is version 2.2.4
npm WARN unmet dependency /usr/lib/node_modules/request requires mime-types@'~1.0.1' but will load
npm WARN unmet dependency /usr/lib/node_modules/mime-types,
npm WARN unmet dependency which is version 2.0.1
bower@1.3.12 /usr/lib/node_modules/bower

**Comment by sindresorhus** [comment]
Upgrade node and npm. Use StackOverflow for support questions.
