### ISSUE TITLE
Error installing package with “+” in version

### ISSUE THREAD

**Issue by julien-f** [bower/bower#1567]
```
> bower i -S bootstrap-sass-official@~3.2.0+2
bower bootstrap-sass-official#~3.2.0+2     ENORESTARGET Tag/branch ~3.2.0+2 does not exist
```

The problem is that automatically Bower will select this tag if it is the last one in the git repository and put it in `bower.json` which will  no longer works.

**Comment by jamesxv7** [comment]
In the following [issue](https://github.com/twbs/bootstrap-sass/issues/749) conversation @glebm indicates that they are not following the `+N` convention for for newer versions. With that information we can considered this issue closed.  

For the part related to the semantic versioning please refer to this [comment](https://github.com/bower/bower/issues/1486#issuecomment-54069741) by @sheerun.
