### ISSUE TITLE
Misleading error on 'bower register' with uppercase letter

### ISSUE THREAD

**Issue by fhemberger** [bower/bower#1573]
I just tried to register a new package with an uppercase letter in its name, the registration fails with `EINVFORMAT Invalid URL format`. When I tried to send the POST request manually to https://bower.herokuapp.com/packages, I got the correct error message: 

> Invalid Package Name. Package names must only contain lower case a through z, 0 through 9, dots, dashes, and underscores.

Please let the bower command return the error message from the server instead of `EINVFORMAT`.

**Comment by sheerun** [comment]
Bower is deprecated and doesn't allow registering new packages anymore, so I'm closing this
