### ISSUE TITLE
Feature Request: directory in bower.json (too)

### ISSUE THREAD

**Issue by jillesme** [bower/bower#1583]
Hello,

I would very much like it if we could just add a directory property to our bower.json instead of creating a .bowerrc just for that one directory property. What do you guys think?

Cheers

**Comment by sheerun** [comment]
Bower is deprecated now, and in maintenance mode. Because of this we won't implement new features like this one. We recommend switching to Yarn or npm, and migrating with [bower-away](https://github.com/sheerun/bower-away)
