### ISSUE TITLE
register and install behave differently with same URI

### ISSUE THREAD

**Issue by robkinyon** [bower/bower#1585]
I'm working within a corporate network setting up an internal bower instance. We're also using Atlassian Stash, which doesn't support Git's "dumb http protocol". When doing testing, I found that `bower install https://our.stash.net/scm/foo/bar.git#0.0.1` worked just fine, but `bower register bar https://our.stash.net/scm/foo/bar.git#0.0.1` failed with a 501. I tracked it down to the HEAD request made in `_checkNew` in the UrlResolver and Stash's refusal to support the dumb http protocol.

The interesting thing is this - why did `register` attempt to do a HEAD request when `install` did not? What's really interesting is that when I put the exact URL that worked with `install` directly into private-bower's configuration, install attempted to do the HEAD request as well. I would think that they should do the exact same thing because `register` is just creating an indirection pointer. So, it seems that the URI is handled differently depending on how the URI is encountered.

The answer to making `bower register` work with Stash is to use `git+https` as the protocol.

**Comment by sheerun** [comment]
Bower is deprecated and doesn't allow registering new packages anymore, so I'm closing this
