### ISSUE TITLE
Git URLs are not using the global credential helper

### ISSUE THREAD

**Issue by andrewmcwatters** [bower/bower#1589]
This is a continuation of #1413. #1413 was originally named "Git URLs are not using the global credential helper", but was later named "Update of tmp dependency in v1.3.8 breaks on Windows installations." and while #1434 fixed the tmp dependency issue, it did not address the global credential helper issue.

In any project containing dependencies using http:// or https:// instead of git@... bower will not utilize any existing credential helper, causing the issues originally mentioned in #1413:

> When performing a `bower install` which will clone the same repo, the dialog is not displayed and the username and password is requested from the console window instead. This is normally the case when no credential helper in git is configured at all.

> The asynchronous nature of Bower means these are usually lost in the console and multiple usernames and password are requested at the same time which is the main reason for using a cache-based helper.

**Comment by igorlino** [comment]
I had the same problem.  The git store and cache helpers would not work under bower install.

The solution I found was to use the winstore credential helper.
http://gitcredentialstore.codeplex.com/

which as a great side-effect, stores securely the credentials under windows.
