### ISSUE TITLE
Idea: allow to use a different bower.json on `bower install`

### ISSUE THREAD

**Issue by rstacruz** [bower/bower#1590]
It'd be nice to be able to use a custom bower.json:

``` sh
$ bower install --file=bower.dev.json
$ env BOWER_FILE=bower.dev.json bower install
```

Motivation:
- It'd be possible to make an external tool to create a "bower shrinkwrap file" by making a custom bower.json with versions/sha1 tags (eg, "jquery#0d34d12c" instead of "jquery#master").
- It may be useful to make alternate bower files for testing purposes, eg, to test with different versions of dependencies.

**Comment by sheerun** [comment]
Other people want to keep bower data in package.json: #1626

**Comment by benmb1984** [comment]
+1 I really need that function!

**Comment by miriti** [comment]
+1
Was surprised that there is no such feature...

**Comment by sheerun** [comment]
Bower is in maintenance mode and no new features will be implemented
