### ISSUE TITLE
ECMDERR - postuninstall hook throwing an error

### ISSUE THREAD

**Issue by shuhrat** [bower/bower#1594]
I have a postinstall hook in my `.bowerrc`

``` javascript
"scripts": {
    "postinstall": "test -f postinstall.js && node postinstall.js"
}
```

getting an error after installing

```
ECMDERR Failed to execute "test -f postinstall.js [object Object] node postinstall.js", exit code of #2
```

**Comment by sheerun** [comment]
I can confirm and reproduce. Please help to fix this by sending PR.

**Comment by zzarcon** [comment]
@sheerun @albertinadx I gonna take a look into this as well

**Comment by albertinadx** [comment]
Hi @zzarcon I had a fix for this, following how npm implements hooks. Would you like to review it as soon as I create the pull request?

**Comment by zzarcon** [comment]
@albertinadx that's great, for sure! just let me know :)

**Comment by zzarcon** [comment]
@albertinadx it's because of the script contains `&&`?

**Comment by albertinadx** [comment]
It is because we are not allowing shell operators (for example &&) in the way we are executing the hooks scripts. I will finish this today. Thanks!

**Comment by sheerun** [comment]
@albertinad Please send a test if possible :)

**Comment by zzarcon** [comment]
@albertinadx good point, good job!

**Comment by sheerun** [comment]
@albertinadx Any progress? :)

**Comment by albertinadx** [comment]
@sheerun I'm back :), I will finish this in the following couple of days. I want to develop a couple of tests before making a PR.

**Comment by sheerun** [comment]
@albertinadx Did you manage to finish the tests?

**Comment by BenMann** [comment]
And with [that](https://github.com/bower/bower/pull/2197#issuecomment-192773428) we should be good to close! :tada:

**Comment by sheerun** [comment]
I had to revert @albertinadx PR because /bin/sh is not available on Windows

**Comment by albertinadx** [comment]
Thanks @sheerun, I will fix it tomorroe

**Comment by sheerun** [comment]
Actually no need to fix it until we agree on appropriate solution.. Probably it would be better to wait for npm to implement similar feature.

**Comment by albertinad** [comment]
Npm already has it, at least similar, and thus fix is based on that.

**Comment by albertinadx** [comment]
Npm already has it, and this fix is based on that.

**Comment by sheerun** [comment]
Really? I'll test your solution on Windows and merge if it works. Sorry, but I coudn't risk it for this patch release.
