### ISSUE TITLE
bower reset

### ISSUE THREAD

**Issue by ain** [bower/bower#1596]
In many scenarios it is desired to wipe clean the `bower_components` and install again, e.g. equivalent to:
```sh
rm -rf path/to/bower_components
bower cache clean
bower install
```
IMO, this could be a very nice addition to the Bower CLI commands.

**Comment by craigmingtaozhang** [comment]
From the maven world we could say 'mvn clean install' to achieve 'mvn clean' + 'mvn install', while separately 'maven clean' could remove things in 'target'(~bower_components), 'maven install' could do things based on the pom file. Is it possible to chain command in bower? Will it be better or worse?

**Comment by ain** [comment]
Further discussion in #1617 that has proven to work and is the way to go. Closing.
