### ISSUE TITLE
`bower.commands.info` not working with `{offline: true}`

### ISSUE THREAD

**Issue by anodynos** [bower/bower#1601]
If I use `bower.commands.info` with the `{offline: true}` option, I get the following with `1.3.12`:

```coffeescript
bcl = bower.commands.info 'lodash', {offline: true}
bcl.on 'end', (result)-> l.log result
bcl.on 'error', (err)-> l.log err
# produces [TypeError: Object #<Object> has no method 'split'] 
```
It works ok without the option.

Also `$ bower info lodash --json` doesnt produce a consumable `json`, but an array of objects followed but an object like this 

```
[{
  "level": "info",
   ...
}, {
 {
  "level": "action",
    ...
}
], {
  "name": "lodash",
  "versions": [..]
  ...
}
```

**Comment by sheerun** [comment]
You can pass offline as third parameter:

bower.commands.info('lodash', undefined, { offline: true })
