### ISSUE TITLE
shorthand_resolver/shorthand-resolver does not work

### ISSUE THREAD

**Issue by evil-shrike** [bower/bower#1609]
By default bower uses git protocol. But it can be closed:
```
c:\>bower install underscore --save
bower underscore#*          not-cached git://github.com/jashkenas/underscore.git#*
bower underscore#*             resolve git://github.com/jashkenas/underscore.git#*
bower underscore#*             ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/jashkenas/underscore.git", exit code of #128

c:\>bower --ver
1.3.12
```
It's noted on [bower.io](http://bower.io/docs/config/#shorthand-resolver) that there could be an option 'shorthand-resolver' in bowerrc for overriding url.
I added in my .bowerrc:
`    "shorthand-resolver": "https://github.com/.git",`
Nothing happens. Bower still uses git protocol.

Also in https://github.com/bower/bower.json-spec it's stated:
>Value can be an owner/package shorthand, i.e. owner/package. By default, the shorthand resolves to GitHub -> https://github.com/owner/package. This may be changed in .bowerrc shorthand_resolver.

So now it's `shorthand_resolver` (instead of  shorthand-resolver). I tried this one. No luck.

So, is there such an option at all? Should it work? How?

**Comment by sheerun** [comment]
Documentation for shorthand-resolver is here: http://bower.io/docs/config/#shorthand-resolver

It works only for `owner/package` syntax. `underscore` has no `/` in it.
