### ISSUE TITLE
Main file path in dependencies

### ISSUE THREAD

**Issue by raphaelluchini** [bower/bower#1610]
We always use a task runner to concat, minify, compress, etc right? The problem is we always have to set every new dist file in a array. I was thinking why not include a main path in dependencies? Would be easy to develop a task to read and concat those files automatically and easily. Searching a way to do this, I've found [this great lib](https://www.npmjs.org/package/main-bower-files) but they go along all folders and read all bower.json from all projects. Would be faster and again, easier.

I thought in a way, for example:

```
{
"dependencies": {
  "jquery":{
    "main":'jquery/dist/jquery.min.js',
    "version":"~1.2.0"
    }
  }
}
```

What do you guys think about it?
Thanks

**Comment by sheerun** [comment]
Backward compatibility is an issue with this approach.
