### ISSUE TITLE
bower.herokuapp.com: Cannot GET /

### ISSUE THREAD

**Issue by bjornstar** [bower/bower#1612]
I was warned that my package would be installable via the registry:
`Registering a package will make it installable via the registry (https://bower.herokuapp.com), continue?`

But there's nothing at the registry except this:
`Cannot GET /`

Is https://bower.herokuapp.com supposed to redirect to http://bower.io?

**Comment by sheerun** [comment]
I added issue on registry repository: https://github.com/bower/registry/issues/106
