### ISSUE TITLE
GitHub URLs always need to be looked up

### ISSUE THREAD

**Issue by jacksonrayhamilton** [bower/bower#1625]
Say that I have dependencies like the following:

```json
"dependencies": {
  "angular-scroll": "jacksonrayhamilton/angular-scroll"
}
```

If I specify a GitHub URL, then when I do `bower install`, that package always needs to be looked up, because its version could have changed. Pretty sure NPM does this. Worse yet, the GitHub packages are cached, so deleting the package from `bower_components` doesn't result in a maybe-update.

Thus the only way (that I know) to update a GitHub package is to `rm -rf bower_components/package && bower cache clean && bower install`. This is bad and should be fixed.

**Comment by sheerun** [comment]
It should be the case for newest bower if you use `bower update` instead `bower install`.

**Comment by bre55tok2882** [comment]
id would like to unscribe from you sending emails please.

thank you
brittany klepfer

**Comment by sheerun** [comment]
@bre55tok2882 You can manage your notifications in https://github.com/watching

**Comment by jacksonrayhamilton** [comment]
Yep, `bower update` seems to do what I want. Thanks!
