### ISSUE TITLE
Updating dependency on remote git repository is slow

### ISSUE THREAD

**Issue by JostBaron** [bower/bower#1630]
I have a dependency on a remote git repository. It seems that whenever I run `bower update`, the whole repository is redownloaded - even if the two runs of that command are done directly after another.

Since the repository is about 60MB big, and my internet connection only has 2MBit/s, and the repository hoster seems to throttle too, this takes a quite a bit of time (between 5 and 20 Minutes) for each update. A raw `git pull` on the repository takes only a few seconds most of the time.

**Comment by sheerun** [comment]
Currently bower caches only working directories. Each update clones repository (unless you use semver and github, it downloads archives then). Moreover only tags can be cached (not branches).

**Comment by j0nimost** [comment]
This issue still persists up to date. The Dev team at bower should do something. No wonder the _bower update_ felt super slow

**Comment by sheerun** [comment]
v

**Comment by sheerun** [comment]
Bower is deprecated now, and in maintenance mode. Because of this we won't implement new features like this one. We recommend switching to Yarn or npm, and migrating with [bower-away](https://github.com/sheerun/bower-away)
