### ISSUE TITLE
Multilanguage Support

### ISSUE THREAD

**Issue by marceloboeira** [bower/bower#1637]
I guess it would be awesome to implement this, if the maintainers agree I would try to write some code and translate it to Brazilian Portuguese ...

**Comment by sindresorhus** [comment]
Yes, should happen eventually, but it's way too early to start complicating the code-base with localization code. Lots of other pressing issues that needs attentions.

**Comment by marceloboeira** [comment]
@sindresorhus you could at least put this on the roadmap, as not a priority.
