### ISSUE TITLE
Why I need add all file?

### ISSUE THREAD

**Issue by joowh85** [bower/bower#1638]
Every file I should need add it?

Every packages there is no configurations about final release path.

So, I need add whole files on my configurations like karma.conf.js. see below.

---------------------------------------------------------------------------------------------------------
files: [
      'bower_components/angular/angular.js',
      'bower_components/angular-mocks/angular-mocks.js',
      'bower_components/angular-animate/angular-animate.js',
      'bower_components/angular-aria/angular-aria.js',
      'bower_components/angular-cookies/angular-cookies.js',
      'bower_components/angular-messages/angular-messages.js',
      'bower_components/angular-resource/angular-resource.js',
      'bower_components/angular-route/angular-route.js',
      'bower_components/angular-sanitize/angular-sanitize.js',
      'bower_components/angular-touch/angular-touch.js',
      'bower_components/ngstorage/ngStorage.js',
      'bower_components/angular-ui-utils/ui-utils.js',
      'bower_components/angular-ui-router/release/angular-ui-router.js',
      'app/scripts/**/*.js',
      'test/mock/**/*.js',
      'test/spec/**/*.js'
    ],
---------------------------------------------------------------------------------------------------------

It is very uncomfortable.

We need to think something new feature or standard for solve this.

for example:

On bower.json, every vendors, packages..

....
"name": "admin",
  "version": "0.0.0",
  "properties": { 
    "angular.version":"~1.3.8" 
  },
 "dist": {
   "development" : "bower_components/angular-ui-router/release/angular-ui-router.js"
   "production" : "bower_components/angular-ui-router/release/angular-ui-router.min.js"
  }
....

**Comment by sindresorhus** [comment]
Closing as this has been discussed multiple times before and this is providing nothing new.
