### ISSUE TITLE
"Prefix the choice with ! to persist it to bower.json" needs a line break

### ISSUE THREAD

**Issue by pkollitsch** [bower/bower#1639]
Just a small flaw: If a bower.json configuration exists and I run 

```bower install --save-dev PACKAGENAME```

where the PACKAGENAME is already noted in the bower.json it asks me to choose a version. The last line says "Prefix the choice with ! to persist it to bower.json". There should most probably be a linebreak (or two) before that sentence, see screenshot.

![2015-01-01-20 11 35](https://cloud.githubusercontent.com/assets/83281/5592225/bf80660c-91f3-11e4-9d28-35d684c9a0c9.png)

**Comment by sheerun** [comment]
Mind to send a PR?

**Comment by pkollitsch** [comment]
I have a commit here aad253bfadab769005c594a8ce33aa54cbf48c5d but I am not sure how to test if this works. Is there a guide somewhere how to compile my local bower from this repo?

**Comment by sheerun** [comment]
Test is not necessary if you're sure it fixes the problem. Just send a PR :)

**Comment by sheerun** [comment]
Fixed via #1644
