### ISSUE TITLE
jsdom and ace fails to be injected on using bower install

### ISSUE THREAD

**Issue by manishdipankar1711** [bower/bower#1642]
I am using angular generator from yeoman.

I did : 
bower install ace --save 
bower install jsdom --save

 File "bower.json" changed.
Running "wiredep:app" (wiredep) task

jsdom was not injected in your file.
Please go take a look in "<project-dir>/bower_components/jsdom" for the file you need, then manually include it in your file.

ace was not injected in your file.
Please go take a look in "<project-dir>/bower_components/ace" for the file you need, then manually include it in your file.

Done, without errors.

So, "ace was not injected in your file" and "jsdom was not injected in your file" is causing the trouble.

I tried to manually include it in my html file but after doing "grunt build" the manual change is gone.
I am stuck. Please help.

**Comment by sheerun** [comment]
You're looking for https://github.com/taptapship/wiredep
