### ISSUE TITLE
Change `bower list` executing commands over https not ssh.

### ISSUE THREAD

**Issue by tdeekens** [bower/bower#1645]
Hi folks,

whenever I install packages from my `bower.json` bower resolves and clones packages over https which is perfect. Anyhow as soon as I perform `bower list` it performs an e.g. `git ls-remote --tags --heads git://github.com/angular/bower-angular-mocks.git`. This command fails in my environment (which is why I would never call this behaviour a bug) as it will use the ssh port for performing the request (as far as my knowledge goes). 

As a result I get:
```
fatal: unable to connect to github.com:
github.com[0: 192.30.252.128]: errno=Connection refused
```
Can bower somehow just use https in accordance with the clone url or have an config option for this?

Thanks!

**Comment by venkataraghu** [comment]
I got the same issue. However git clone is working good. 
λ git ls-remote --tags --heads git://github.com/bestiejs/json3.git
fatal: unable to connect to github.com:
github.com[0: 192.30.252.130]: errno=No error

**Comment by tdeekens** [comment]
...it's definitely a proxy (does not allow ssh ports) or firewall issue. I just wonder why bower performs this request over ssh and not https or better just the protocol the repo was cloned with.

**Comment by venkataraghu** [comment]
@tdeekens glad you responded on this. Meanwhile, I have tried finding out the filtering happening at firewall.  Based on the results, I could make out that only http requests are working good. 

> nmap github.com -p 80,9418,2

Starting Nmap 6.47 ( http://nmap.org ) at 2015-01-23 14:44 India Standard Time
Stats: 0:00:39 elapsed; 0 hosts completed (0 up), 1 undergoing Ping Scan
Parallel DNS resolution of 1 host. Timing: About 0.00% done
Stats: 0:00:40 elapsed; 0 hosts completed (1 up), 1 undergoing SYN Stealth Scan
SYN Stealth Scan Timing: About 50.00% done; ETC: 14:45 (0:00:00 remaining)

Nmap scan report for github.com (192.30.252.128)
Host is up (0.058s latency).
PORT     STATE    SERVICE
22/tcp   filtered ssh
80/tcp   open     http
9418/tcp filtered git

Nmap done: 1 IP address (1 host up) scanned in 41.63 seconds

**Comment by tdeekens** [comment]
@venkataraghu thanks for the investigations. I assume it's the same issue for us.

I was digging into bower's code and assume that it should be caused [here](https://github.com/bower/bower/blob/master/lib/commands/list.js#L89) which leads us to the [core/Project](https://github.com/bower/bower/blob/master/lib/core/Project.js) which in turn seems to utilise the [endpointParser](https://github.com/bower/endpoint-parser).

Questions for me remains: how and why is a project is specify cloned over https and then after is does the `bower list` command go over ssh.

Should we isolate this issue more and maybe move towards a pull request?

**Comment by amalahussein** [comment]
FYI this fixed the issue for me: 
git config --global url."https://".insteadOf git://

**Comment by runspired** [comment]
I experience this on a cisco linksys router routinely, haven't been able to pin down what's up.  Assumed it was a closed/blocked port but that turned out to not be the case.

**Comment by doub1ejack** [comment]
Thanks @amalahussein - that worked nicely.

**Comment by BeierZhu** [comment]
@amalahussein thanks, it works

**Comment by sheerun** [comment]
We changed git:// urls to https:// in registry, #2235
