### ISSUE TITLE
Flag --ignoreDependencies

### ISSUE THREAD

**Issue by joaom182** [bower/bower#1647]
It would be very interesting if it were possible to install or uninstall packages ignoring its dependencies. For example, if I install the 'B' package, it will install the 'J' package as a dependency. When I uninstall the package 'B' it will also uninstall the package 'J', but this is not always desired.

**Comment by joaom182** [comment]
When a package is installed, and one of its dependencies is already installed with a lower version, this dependency will be updated as well?

**Comment by patrickkettner** [comment]
you are asked to resolve a conflict when that happens

On Tue, Jan 6, 2015 at 6:50 PM, João Marcos Mainka <notifications@github.com
> wrote:

> When a package is installed, and one of its dependencies is already
> installed with a lower version, this dependency will be updated as well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bower/bower/issues/1647#issuecomment-68956265>.
>



-- 
patrick

**Comment by joaom182** [comment]
You could escape these conflicts if you use this flag, it is not atypical you install a package knowing that the dependencies are already installed.

**Comment by patrickkettner** [comment]
I am not sure how adding a flag you would have to invoke manually is better than selecting an option that already exists.

Not against the idea, I just have yet to see the benefit

**Comment by joaom182** [comment]
In [Nuget](http://nuget.org) this flag is very useful, but I agree with you, would have to see the real benefit of this, I do not have many arguments.

**Comment by sindresorhus** [comment]
You should explicitly define dependencies you depend on, even though sub-dependencies might have the same dependencies.
