### ISSUE TITLE
When using svn with bower and temp dir has @ the repo is not fetched correctly

### ISSUE THREAD

**Issue by arturokunder** [bower/bower#1650]
When I fetch a bower package, it is stored at a temp dir.
In some cases, the computer's username may have an @. 
In this case, the generated temp dir will contain this @, making svn act weird.

For example, in Windows, if I have "example@example.com" as username, generated temp dir will be:
```` C:\Users\EXAMPLE~1.COM\AppData\Local\Temp\PC-EX-example@example.com\bower\PACKAGE-NAME-XXXX ````

SVN interprets the @ on this uri as something else and it crops it to:
```` C:\Users\EXAMPLE~1.COM\AppData\Local\Temp\PC-EX-example ````

Storing the data somewhere else. Then, when bower tries to read and copy the files, it throws an error

I'm making a PR for fix this issue

**Comment by sindresorhus** [comment]
Open a ticket on SVN, it should be fixed there too.
