### ISSUE TITLE
Use bundleDependencies in package.json to speed up installation

### ISSUE THREAD

**Issue by jzaefferer** [bower/bower#1656]
Installing bower takes a while (20 seconds on a Travis build just now). This could be sped up using the `bundleDependencies` setting in `package.json`. That's what npm itself uses: https://github.com/npm/npm/blob/6f2b726c03bab3eb45c1f277fd929cdacd9d6323/package.json#L99 (should be the same line in master).

**Comment by sindresorhus** [comment]
npm uses that because they have too.

You're better off caching all your dependencies: http://docs.travis-ci.com/user/caching/
