### ISSUE TITLE
Specify location for dependencies within bower_components

### ISSUE THREAD

**Issue by websirnik** [bower/bower#1659]
My workflow include installing dependencies with bower and concatinating them with Gulp's [main-bower-files](https://github.com/ck86/main-bower-files) into one large `vendor.js`. My `vendor.js` file has become very large, so I need to modularise it into `vendor.core.js`, `vendor.moduleX.js` & `vendor.moduleY.js` and lazy-load modules in my app.

I can solve it by telling [main-bower-files](https://github.com/ck86/main-bower-files) which dependency goes to which module. But that would require referencing all dependency js files inside `gulpfile.js` and maintaining those references with every new dependency update. Feels inefficient to me.

The best scenario as I see it is to have an ability to specify install location for the dependency within `bower_components` folder in `bower.json`.

I'm looking for the following output. Then I can tell [main-bower-files](https://github.com/ck86/main-bower-files) that all dependencies from `bower_components/core` folder goes into `vendor.core.js` and dependencies from `bower_components/moduleX` to `vendor.moduleX.js`.

![screen shot 2015-01-14 at 18 46 29](https://cloud.githubusercontent.com/assets/282871/5745041/c5089dfe-9c1d-11e4-85a8-cb50429463e8.png)

**Comment by sindresorhus** [comment]
Out of scope of what Bower should do. If you need multiple folders, just use multiple bower.json files in subdirectories.
