### ISSUE TITLE
bower.herokuapp.com is down

### ISSUE THREAD

**Issue by cassianoalves** [bower/bower#1660]
It's down again... (#1385)
Check it out: http://www.websitedown.info/bower.herokuapp.com
https://bower.herokuapp.com/

**Comment by cassianoalves** [comment]
Now working! Thanks!

**Comment by diefans** [comment]
```bower jquery-placeholder#~2.0.7        EINVRES Request to https://bower.herokuapp.com/packages/jquery-placeholder failed with 500```
