### ISSUE TITLE
503 accessing registry

### ISSUE THREAD

**Issue by btilford** [bower/bower#1661]
Looks like https://bower.herokuapp.com/ is down.

**Comment by arturgspb** [comment]
+1

**Comment by CFXd** [comment]
+1

I freaked out because it happened right after I updated bower!

**Comment by alexey-shaposhnikov** [comment]
may be it is a sign to start using  npm?

**Comment by sheerun** [comment]
https://gitter.im/bower/bower

**Comment by arturgspb** [comment]
@CFXd, oh. All my CI build has filed now =(

**Comment by suitupalex** [comment]
I had issues, but bower seems to working fine now.

**Comment by CFXd** [comment]
Yes, seems to be back up and running fine now. Thanks for confirming this wasn't a local issue guys!

**Comment by vladikoff** [comment]
Request to https://bower.herokuapp.com/packages/chai failed with 503

**Comment by sheerun** [comment]
The cause of crash was high CPU load.

Heroku agreed to sponsor Bower's hosting with $150/month. I've added another small dyno.

We also have Heroku metrics now, so we can monitor Bower's registry performance.

Cheers and thanks for Heroku!

**Comment by vladikoff** [comment]
Thanks Heroku!

**Comment by qubyte** [comment]
I'm seeing this today. Getting:

`bower jquery#~2.1.0                                                 EINVRES Request to https://bower.herokuapp.com/packages/jquery failed with 503`
