### ISSUE TITLE
Bower ignore glob may match incorrectly. 

### ISSUE THREAD

**Issue by Dervisevic** [bower/bower#1663]
So i'm not 100% sure this is a bug as i'm not a superstar at globbing but i'll explain my case and you can determine if it is. A more comprehensive issue can be found at Textalk/angular-schema-form#211. 

The faulting ignore line we had in our bower.json was: `*.js`. It did not specify any dir, it was supposed to ignore javascript files at root level. However the file `dist/schema-form.js`was ignored, and as a side note `dist/schema-form.min.js` was not ignored. Removing the faulting line fixed the issue.

**Comment by yonatanhakatan** [comment]
Hi,
Did this ever get resolved? Im experiencing the same issue.
Thanks

**Comment by sheerun** [comment]
This issue got stale. If this is still relevant, please create another one
