### ISSUE TITLE
bower conflict issues:

### ISSUE THREAD

**Issue by deanclkclk** [bower/bower#1664]
Tried running bower install on my CI and getting the following issues (note the:  `bower                                                ECONFLICT Unable to find suitable version for angular`):

  					   {
					  "name": "angular-seed",
					  "description": "A starter project for AngularJS",
					  "version": "0.0.0",
					  "homepage": "https://github.com/angular/angular-seed",
					  "license": "MIT",
					  "private": true,
					  "dependencies": {
						"angular": "~1.2.x",
						"angular-loader": "1.2.x",
						"angular-mocks": "~1.2.x",
						"angular-ga": "~0.1.3",
						"expect": "~0.3.1",
						"bootstrap": "~3.1.1",
						"angular-route": "~1.2.x",
						"angular-ui-router": "0.2.11",
						"jquery-ui": "1.10.3",
						"jquery.easing": "1.3.1",
						"jquery-migrate": "1.2.1",
						"jquery": "1.10.2",
						"superfish": "1.7.4",
						"html5shiv": "3.7.2",
						"bootstrap3-wysihtml5-bower": "0.3.2",
						"fullcalendar": "1.6.4",
						"iCheck": "1.0.1",
						"ion.rangeSlider": "1.8.2",
						"jquery-knob": "1.2.11",
						"bower-jvectormap": "1.2.2",
						"morris.js": "0.5.1",
						"slimScroll": "1.3.0",
						"bootstrap-timepicker": "0.2.3",
						"raphael": "~2.1.2",
						"angular-translate": "2.5.2",
						"angular-translate-loader-partial": "~2.5.2",
						"angular-sanitize": "~1.3.8"
					  },
					  "resolutions": {
						"jquery": "1.10.2",
						"bootstrap": "~3.1.1",
						"raphael": "2.1.1"
					  },
					  "devDependencies": {
						"sinonjs": "~1.10.2"
						   }
						} 

This is my build output:

					bower wysihtml5x#0.4.9                                resolved git://github.com/Edicy/wysihtml5.git#0.4.9
					bower bootstrap#3.1.0                                 resolved git://github.com/twbs/bootstrap.git#3.1.0
					bower jquery-ui#1.10.3                            invalid-meta jquery-ui is missing "ignore" entry in bower.json
					bower jquery-ui#1.10.3                                resolved git://github.com/components/jqueryui.git#1.10.3
					bower                                                ECONFLICT Unable to find suitable version for angular
					[INFO] ------------------------------------------------------------------------
					[INFO] BUILD FAILURE
					[INFO] ------------------------------------------------------------------------
					[INFO] Total time: 1:06.064s
					[INFO] Finished at: Thu Jan 15 18:54:40 UTC 2015
					[INFO] Final Memory: 21M/1121M
					[INFO] ------------------------------------------------------------------------
					[ERROR] Failed to execute goal pl.allegro:grunt-maven-plugin:1.4.1:bower (default) on project cointraders-frontend: Unable to execute mojo: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
					org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal pl.allegro:grunt-maven-plugin:1.4.1:bower (default) on project cointraders-frontend: Unable to execute mojo

**Comment by huyhong** [comment]
Try adding inside `"resolutions": { ... }` an `"angular": "1.2.28"` (or whatever version of angular 1.2 you're on).

**Comment by sheerun** [comment]
Also: #1362

For now resolutions are only used when there's actually a conflict. This might be slightly confusing.
