### ISSUE TITLE
SVN - install individual folder

### ISSUE THREAD

**Issue by josephfinlayson** [bower/bower#1665]
I have a library of utilities that I want to use across projects, but don't want to set up individual git repos for. Is it possible to install an individual SVN folder?

`svn checkout https://github.com/driftyco/ionic/trunk/js/angular` works but `
bower install svn+https://github.com/driftyco/ionic/trunk/js/angular` doesn't

**Comment by TheOnlyLupo** [comment]
Don't think anyone gives a fuck about your issue.

**Comment by sheerun** [comment]
Bower is deprecated now, and in maintenance mode. Because of this we won't implement new features like this one. We recommend switching to Yarn or npm, and migrating with [bower-away](https://github.com/sheerun/bower-away)
