### ISSUE TITLE
Ubuntu Wrong Node Install 

### ISSUE THREAD

**Issue by kelleyDanger** [bower/bower#1666]
# Install - Wrong Node 

OS - Ubuntu 13.10
npm - 1.2.18

After installing bower and trying to run any command using it, I received the error that it could not find node.  This is because bower must look for the package node, but on Ubuntu that package is a f***ing (hamradio): Amateur Packet Radio Node program......  Instead, had to just create a sym link to nodejs, which is what Ubuntu calls it.

**Comment by sheerun** [comment]
That's known issue and that's npm's issue. You need to symlink `node` to `nodejs`.
