### ISSUE TITLE
Option for appending currently installed packages to bower.json

### ISSUE THREAD

**Issue by kontur** [bower/bower#1668]
Hey,

first of all forgive me if this feature either has been discussed before or exists; in that case just close the issue.

I was hoping for a command what would update my `bower.json` with all installed (as in: `$ bower list`) packages as dev dependencies. Imagine something like `$ bower install -S` or `$ bower list --install--dev-dependencies`.

For example *pip* for python allows you to dump the currently installed dependencies into a file like `$ pip freeze > myfile.txt` and I find this super convenient, but, alas, missing from bower. For example [this highly upvoted solution given on stackoverflow](http://stackoverflow.com/questions/20279792/how-to-update-bower-json-with-installed-packages) seems rather laborious.

Any thoughts on this suggestion or instructions on possible ways to do this already?

**Comment by sindresorhus** [comment]
Nah, just always use `bower install -S`. In your .bashrc/.zshrc: `alias bi='bower install -S'` ;)

Saving to bower.json will be default in Bower 2.0: https://github.com/bower/bower/issues/1040
