### ISSUE TITLE
Idea: Allow reference mutiple local specific files

### ISSUE THREAD

**Issue by maxiruani** [bower/bower#1670]
It would be nice to be capable of make custom builds of git packages with local files too.
For example, there are projects like [angular-io](https://github.com/angular-ui/bootstrap) that you can't make a custom build unless you make fork of the project and create your own bower.json.

```javascript
{
  "name": "quivs",
  "version": "0.0.1",
  "license": "MIT",
  "dependencies": {
    "some-package": "*",
    "custom-package-1": [
        "./bower_components/some-package/folder-1/file-1.js",
        "./bower_components/some-package/folder-2/file-2.js",
      ],
    "custom-package-2": [
        "./src/file-3.js",
        "./src/components",
      ]
  }
}
```

Thanks in advance

**Comment by sindresorhus** [comment]
This has already been discussed multiple times in the past. Looks through the issue tracker.
