### ISSUE TITLE
Rename .bowerrc to .bowerrc.json

### ISSUE THREAD

**Issue by EvanCarroll** [bower/bower#1671]
It'd be nice if we had this as .bowerrc.json or something of that sort. The `require()` call works with json. It'd be nice to do something in gulpfile.js, like

> var BOWER_PATH = require('.bowerrc.json').directory

We can easily parse the file as json, but if the extension was just right (and more-nodeish), we wouldn't have to write the parse manually. Or, use jsonutil, or readFile.

**Comment by sheerun** [comment]
1. `.bowerrc` can be defined in different directories (HOME, project, etc). It's unsafe to read it directly.
2. We already decided on `.bowerrc` name, we can't change it due to backward compatibility
3. It's quite similar to other rc files, for example you don't write `.bashrc.sh`

**Comment by EvanCarroll** [comment]
1. Why would it be unsafe to read it directly? I would think as a JSON file, it should always be safe to run it through `require()` if that worked? Are we speaking about some hypothetical security vulnerability in the core JSON parse routines?
3. Right, but `.bashrc` is a script `.bowerrc` is configuration, and that configuration is likely going to be needed for the buildsystem.

On backwards compatibility: I see you've decided on that. What about permitting a `.bowerrc.json`? The whole idea of this being an `rc` file seems like a cutesy and stupid. An rc file is initialization not configuration. I'd suggest changing it because it's confusing and silly regardless.

**Comment by sheerun** [comment]
Because we decided developers should read bower configuration using: https://github.com/bower/config

Among others that's how we provide backward compatibility.

**Comment by sheerun** [comment]
We can't provide there will be always `.bowerrc`, but we promise there will be always bower/config

**Comment by EvanCarroll** [comment]
Well, I'm good with that. There is logic in using a configuration parser. That said, I'm all for dropping the rc stuff and moving to the node convention of `.json` (which helps MSWIN users too).
