### ISSUE TITLE
Standard error json output on successful run

### ISSUE THREAD

**Issue by Chewbone** [bower/bower#1676]
While using json output during package installation, I have noticed that standard error is being used to output an array of json objects even when there are no problems.  They have this format:
```
{
  "level": "info",
  "id": "cached",
  "message": "git://myhost/myrepo.git#1.0.0",
  "data": {
    "endpoint": {
  ...
```
In a typical successful install, there is no standard error output.  I would expect them same when specifying json output.

**Comment by sheerun** [comment]
You can use `--quiet` option to avoid outputting non-error logs to stderr.

**Comment by Chewbone** [comment]
Your solution has the bonus side effect of silencing standard out as well.  This completely negates the use of json output, so is no real solution at all.  It just moves the real problem.  Non-error content shouldn't be output in standard error.  This causes problems for scripts that rely on collapsing standard out with standard error.  They receive two json objects in the same stream when only one is expected. Please reopen this issue.

**Comment by samccone** [comment]
> Non-error content shouldn't be output in standard error

I agree with this, it is important to follow unix semantics otherwise we are causing people pain :art:  

thoughts on reopening @sheerun ?

**Comment by sheerun** [comment]
@samccone Actually it's common UNIX semantic to output extra logs on stderr :) Command is considered failed because of error exit code, not presence of stderr.

I think making this non-backwards compatible change is not worth it.

**Comment by samccone** [comment]
ah ah so my point was more, if we are writing info to stderr and exiting with 0 does that not seem weird?
Would this log be better as a warning logged to stdout?

just questions :) and something to think about? Seems just slightly odd to me logging to err and still exiting with 0, that is all

**Comment by sheerun** [comment]
Well, this is behavior only of `--json` API, so both logs and error errors can be consumed with the same channel. If command succeeds, consumer can read output from stdout.

So behavior for `--json` is now:

1. STDOUT: Actual JSON output in case of 0 exit code.
2. STDERR: Progress logs & warning logs & error logs, uniform format

After this change it would be:

1. STDOUT: Actual JSON output in case of 0 exit code, mixed with progress logs & warn logs.
2. STDERR: Error logs only in case of non-0 exit code.

As you can see it makes consumer's logic more complicated. And we would break a contract.

**Comment by samccone** [comment]
yep :+1: fair point, just raising the point for conversation, I understand what your point is, and I think it is fair
