### ISSUE TITLE
Error installing any package.

### ISSUE THREAD

**Issue by denzelwamburu** [bower/bower#1678]
My bower was running previously well till recently i really don't know what happened when i tried to install a new package or even trying to search any package.
It returns the following error,
bower retry         Request to https://bower.herokuapp.com/packages/angular failed with ECONNRESET, retrying in 1.0s
bower retry         Request to https://bower.herokuapp.com/packages/angular failed with ECONNRESET, retrying in 2.8s
bower retry         Request to https://bower.herokuapp.com/packages/angular failed with ECONNRESET, retrying in 5.8s
bower retry         Request to https://bower.herokuapp.com/packages/angular failed with ECONNRESET, retrying in 11.0s

OR for angular-material 
bower retry         Request to https://bower.herokuapp.com/packages/angular-material failed with ECONNRESET, retrying in 1.1s
bower retry         Request to https://bower.herokuapp.com/packages/angular-material failed with ECONNRESET, retrying in 2.8s
bower retry         Request to https://bower.herokuapp.com/packages/angular-material failed with ECONNRESET, retrying in 5.9s
bower retry         Request to https://bower.herokuapp.com/packages/angular-material failed with ECONNRESET, retrying in 15.6s
bower retry         Request to https://bower.herokuapp.com/packages/angular-material failed with ECONNRESET, retrying in 29.1s
bower ECONNRESET    Request to https://bower.herokuapp.com/packages/angular-material failed: tunneling socket could not be established, cause=139983883896640:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:795:

I can't seem to find the issue

**Comment by vladikoff** [comment]
Should be fixed now https://github.com/bower/bower/issues/1661

**Comment by denzelwamburu** [comment]
@vladikoff Thanks guess the server was down,at the moment the server currently down i guess,i have reproduce the same error again.
