### ISSUE TITLE
Updating dependency versions in bower.json and doesn't pickup the change

### ISSUE THREAD

**Issue by genu** [bower/bower#1679]
I'm a little new to bower, but from my understanding if a project updates its depdendncies, doing `bower info <package>` should show the new updated dependency versions.

For example: 

package-a has:

```json
"dependencies": {
     "package-c": "~1.0.0"
}
```
if I do `bower info package-a` it would show that it depends on `package-c` version `~1.0.0`

Now, say the `package-a` developer updates the `package-c` dependency so that now it looks like:

```json
"dependencies": {
     "package-c": ">=1.0.0"
}
```

Does that developer need to create a new tag again? or is the correct behavior that doing `bower info package-a` would automatically show that `package-c` is now changed to `>= 1.0.0`

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow.
