### ISSUE TITLE
bower - fatal: unable to connect to github.com

### ISSUE THREAD

**Issue by svox1** [bower/bower#1687]
After upgrading ember-cli on my mac (Yosemite 10.10.2)
npm uninstall -g ember-cli
npm cache clean
bower cache clean
npm install -g ember-cli@0.1.12
....

my bower doesnt work anymore.

If I try:
bower list

I get an error:
bower check-new     Checking for new versions of the project dependencies..
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/rwjblue/ember-cli-test-loader.git", exit code of #128

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.128]: errno=Operation timed out

But if I execute:
git ls-remote --tags --heads git://github.com/rwjblue/ember-cli-test-loader.git
it works:
git ls-remote --tags --heads git://github.com/rwjblue/ember-cli-test-loader.git
c6006a11515c756d115bb5209103a22c2e9554a0	refs/heads/master
929777f8b5c60db3120712c7328f5debdf74a0cd	refs/tags/0.0.1
055d50f770ad333e7ead10ecb04605f951e2435b	refs/tags/0.0.2
9defa2c59df38dcc334d6c1cc266075c04c2a4f6	refs/tags/0.0.3
a925b8fc428829ea3599e66eb0e6353726426356	refs/tags/0.0.4
c6006a11515c756d115bb5209103a22c2e9554a0	refs/tags/v0.1.0

Also every git clone git:// or http:// works and I can access 192.30.252.128 over http.

Only in combination with bower it doesnt work.
With npm I have also no problems.

What Im trying was to uninstall and reinstall bower. But this doesnt solve the problem.

Im also exit my firewalls with no result.

I have no proxy configurred. 

Any idea?

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/bower
Paste in the link to the question here so others can follow ;)

**Comment by svox1** [comment]
Ok. Here is the question:
http://stackoverflow.com/questions/28361937/bower-fatal-unable-to-connect-to-github-com
