### ISSUE TITLE
I'd like to run bower under www-data user

### ISSUE THREAD

**Issue by sandrodz** [bower/bower#1688]
Hey guys,

I'm in love with bower ^_^

But, on my ubuntu server, I'd like to automate deploy mechanism. Since I run svn + post-commit hooks, I'd like to update dev server on each commit - this means running rm -r packages/* and bower install on every commit.

Svn post-commit hook runs under apache user www-data. Bower is installed for my user.

Is there a way to let www-data use bower goodies?

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/bower
Paste in the link to the question here so others can follow ;)

**Comment by sandrodz** [comment]
Ok, got it!

http://stackoverflow.com/questions/28361866/bower-automation-with-svn-hooks-www-data-bower

Thx.
