### ISSUE TITLE
Merge .bowerrc with global bower

### ISSUE THREAD

**Issue by sebakerckhof** [bower/bower#1689]
Hello,

I'm working with a team on a couple of repositories.
Some of these repositories have their bower components installed in a directory named, others in the default bower_components. This is specified in the bowerrc file in each repository

The problem is that some of our team are working behind a proxy and others are not working behind a proxy. This also needs to be defined in the .bowerrc file. Therefore the .bowerrc file is different between team members.

Now, I could not add the bowerrc file to git, but then every member needs to know the correct setting for the "directory" setting (and some others, like "scripts", which is also custom for each repository).

Ideally I would only specify "directory" and "scripts" in the repositories .bowerrc file and bower would merge this with my global .bowerrc file, where I specify my proxy settings.

**Comment by sheerun** [comment]
You can place `.bowerrc` in project's directory. Does it solve this problem?

**Comment by sebakerckhof** [comment]
Well, I have a directory structure like so:
<pre>
├──  repository/
│   └──  .bowerrc
└──  .bowerrc
</pre>

The bowerrc file in the repository directory contains:
```js
{
  "directory":"app/lib"
}
```

And the .bowerrc file in the root directory contains:
```js
{
  "proxy":"http://192.168.12.102:3128",
  "https-proxy":"http://192.168.12.102:3128"
}
```

According to the [bower docs](http://bower.io/docs/config/), these two should be merged by bower, therefore the total configuration used by bower should be:
```js
{
  "directory":"app/lib",
  "proxy":"http://192.168.12.102:3128",
  "https-proxy":"http://192.168.12.102:3128"
}
```

Yet, bower doesn't seem to do this. It doesn't use the proxy settings defined in the .bowerrc in the root directory. Only when I update the .bowerrc in the repository directory manually to include the proxy settings, it does work...

I use windows 7 pro x64, bower 1.3.12 and nodejs 0.10.35

**Comment by sheerun** [comment]
I can confirm. Only first `.bowerrc` is used. A fixing PR with tests for https://github.com/bower/config/blob/master/lib/util/rc.js#L31 would be appreciated.

**Comment by samccone** [comment]
Leaning on the giants here, `.gitignore` works in a similar fashion as to what was proposed here. so :+1:

**Comment by kodypeterson** [comment]
@sheerun I can take a look at this!

**Comment by sheerun** [comment]
OK :)

**Comment by kodypeterson** [comment]
@sheerun the fix PR is here https://github.com/bower/config/pull/24

Also, this repo never had tests :open_mouth: Now it does :)

Still needs more tests, but this is a good start!
