### ISSUE TITLE
`bower install` does nothing when existing package has version conflicts

### ISSUE THREAD

**Issue by eheikes** [bower/bower#1690]
If I change the version of a package in the manifest and then run `bower install`, nothing happens.

Example: Start with a `bower.json` like this:

```json
{
  // ...
  "dependencies": {
    "angular-ui-router": "0.2.11",
    "package-that-requires-0.2.11": "0.1.0"
  }
}
```

and all the packages have been installed.

Now change the manifest:

```json
{
  // ...
  "dependencies": {
    "angular-ui-router": "0.2.13",
    "package-that-requires-0.2.11": "0.1.0"
  },
  "resolutions": {
    "angular-ui-router": "0.2.13"
  }
}
```

If I run `bower install`, I get no output and the angular-ui-router package remains at 0.2.11. (The same happens without the `resolutions` property.) If I run `bower install angular-ui-router`, then I get the "Unable to find a suitable version for angular-ui-router, please choose one" conflict message. Using `--force` or `--force-latest` resolves to 0.2.13.

Am I wrong in expecting bower to resolve to the `resolutions` version, or at least to warn me about the version conflict? I couldn't find this behavior described anywhere in the docs.

(I'm using bower 1.3.12)

**Comment by sheerun** [comment]
Yes, it's confusing, and there's ticket for it: #1362
