### ISSUE TITLE
Install package from HTTP without renaming the actual file

### ISSUE THREAD

**Issue by Landish** [bower/bower#1693]
Hello!

Let's say I have a "package" ( i'm using curly braces, because that file/package is not registered on bower's registry ) name defined in `dependencies` object, which points to some file, which is accessible by  `http` request:
```json
"dependencies" : {
   "some-example-js" : "http://example.com/example.js"
}
```
When I type `bower update some-example-js` command in terminal, it downloads that file and saves into `bower_components/some-example-js/index.js` file. 

Everything works like a charm, but my question is, is it possible to save that `example.js` file, as `example.js` and not as `index.js` ? 

Also note that, I'm using `update` command ( `bower update some-example-js` ), because when using `install`  ( `bower install some-example-js` )  it searches through bower registry and that package does not exists, so it does not download it.

Is it possible to force the bower for searching/downloading that "package" from the given URL? Do I have to pass the flag or extra argument for that? 

I've found nothing about that on docs page, otherwise I wouldn't waste your time by opening this issue ;)

Thanks!

**Comment by sindresorhus** [comment]
> Everything works like a charm, but my question is, is it possible to save that example.js file, as example.js and not as index.js ?

No, that's how Bower works. `index.js` because it's the entry-point to the package.

**Comment by lucasconstantino** [comment]
Seriously, this is really an annoying and misleading behavior. This is simply wrong O.o
