### ISSUE TITLE
Forcing authors to commit compiled / built files

### ISSUE THREAD

**Issue by jondavidjohn** [bower/bower#1694]
One thing that has bothered me about publishing a component with bower is the requirement that the distribution be contained entirely within the repository.

This model forces authors to commit compiled / built / minified files in order to distribute via bower.

Is there a way currently to avoid this?

Would utilizing the file uploads in the github releases feature be a feasible way to allow an alternative way to publish a component with bower?

**Comment by sheerun** [comment]
No way to avoid that, but there's discussion here: #1606
