### ISSUE TITLE
Bower does not find home (~) directory

### ISSUE THREAD

**Issue by vohtaski** [bower/bower#1697]
When I run `bower install` on MacOS, instead of creating `.bower` folder in my home directory it creates a folder `~` in my project directory and puts `cache`, `registery` files there.
The expected behavior would be to create these files in my home directory.

bower version - 1.3.12

I have the following `.bowerrc`:
```js
{
  "directory": "public/lib",
  "json": "bower.json",
  "interactive": false,
  "storage": {
    "packages": "~/.bower/cache",
    "registry": "~/.bower/registry"
  },
  "tmp": "~/.bower/tmp"
}
```

**Comment by moeHaydar** [comment]
+1

**Comment by sheerun** [comment]
PR with tests welcome for https://github.com/bower/config :)

**Comment by giacgbj** [comment]
+1

**Comment by changsijay** [comment]
+1

**Comment by sheerun** [comment]
It works now with the newest bower
