### ISSUE TITLE
Bower does not git clone dotfiles

### ISSUE THREAD

**Issue by orlade** [bower/bower#1698]
When a Git repository is listed as a Bower dependency, the repo is cloned but any dotfiles committed to the repo are not. This is messing with the build process for one of our apps, because the developer has the dependency symlinked for testing (with dotfiles) but when other users run bower install, those same dotfiles are missing.

The dotfile in question is a simple `.bowerrc` file in the dependency project that tells bower to install _its_ dependencies into `/bower_components` rather than `/lib`, then Grunt expects to copy certain files out. It's certainly not an ideal build configuration (we should publish the Bower packages, etc.), but that's the way it is at the moment.

Is this expected behaviour? If so, why? [This SO post](http://stackoverflow.com/a/22598185/363039) may be relevant, but he thinks not. I can't really find any other information about it.

**Comment by stevevanhooser** [comment]
Check out: https://github.com/bower/bower/issues/183

Apparently it is a requested feature that has never happened.
