### ISSUE TITLE
Bower install does nothing

### ISSUE THREAD

**Issue by diffoperator** [bower/bower#1699]
nikhil@diffoperator-machine-0:~/work/india/mui$ nodejs -v
v0.10.25
nikhil@diffoperator-machine-0:~/work/india/mui$ node -v
v0.10.25
nikhil@diffoperator-machine-0:~/work/india/mui$ npm -v
2.5.1
nikhil@diffoperator-machine-0:~/work/india/mui$ bower install
nikhil@diffoperator-machine-0:~/work/india/mui$ 

I can bower install individual packages but the above command does nothing, it does not give a useful error message, it just sits there.

I am running Ubuntu 14.10

**Comment by SimonMckeon** [comment]
Do you have a bower.json file? Bower install it's meant to install dependencies already listed in bower.json.

**Comment by sheerun** [comment]
Exacely as @SimonMckeon said. You need `bower.json`.

Also if you execute `bower install` after package were installed, it'll do nothing. It's expected.

**Comment by samccone** [comment]
`npm i` follows this same pattern :+1:
