### ISSUE TITLE
bower project changing license

### ISSUE THREAD

**Issue by Niggler** [bower/bower#1701]
Ran into an issue recently with a project jqgrid, which recently changed from a free license to a proprietary one (dual licensed with a non-commercial CC license).

What is the best way to handle this situation?  Should I just skip bower altogether and use the latest liberally licensed version?  Should I create a separate fork pinned to the last free version?

**Comment by benschwarz** [comment]
I'd just choose the package using a git sha or tag that presents the licence that you want.

**Comment by benschwarz** [comment]
eg: 

```
"c3": "c76c89273b11665d9ddaf73dd6231c5839122328"
```
