### ISSUE TITLE
Multiple errors on npm install -g bower

### ISSUE THREAD

**Issue by DaveLindberg** [bower/bower#1702]
A number of node_modules failed during install. Almost all are Error code ENOENT, errno 34. 
Here's a partial list:
npm ERR! Error: ENOENT, lstat '/Users/xxx/local/lib/node_modules/bower/node_modules/mout/lang.js'
.../tmp/test/name-test.js'
.../fstream/lib/file-writer.js'
.../cardinal/lib/highlightFile.js'
.../fstream-ignore/test/.ignore'
.../bower-json/test/pkg-bower-json-malformed/bower.json'
 and so on, for maybe 10 +/- similar messages. 

running Mac OSX Yosemite 10.10.2

**Comment by sindresorhus** [comment]
npm install errors => https://github.com/npm/npm/issues
