### ISSUE TITLE
Unhelpful warning from bower makes it hard to locate syntax error

### ISSUE THREAD

**Issue by caspii** [bower/bower#1703]
If `bower.json` contains an error as follows, then bower does not give a useful warning:

```
{
  "name": "test3",
  "private": true,
  "dependencies": {
    "modernizr": "~2.8.2",
    "bootswatch-dist": "3.3.0-lumen",
    "RRSSB": "~1.6.5",
    "jQueryKeyframes": "~0.0.8",  /* ERROR: there should be no comma here */
  }
}
```
The warning is:
```
Running "wiredep:app" (wiredep) task
Warning: Unexpected token } Used --force, continuing.
```
It's easy to run into this problen if you cut and paste a dependency. I've had this problem twice now and spent too long figuring what had gone wrong. The first time I reverted to a working commit. The second time I finally figured it out.

Bower should at least tell me which file causes the warning.

**Comment by sheerun** [comment]
It's because you use bower through wiredep. If you use bower directly you get nice message:

```
bower                       EMALFORMED Failed to read /Users/sheerun/Source/Bower/bower.json

Additional error details:
Unexpected token /
```

This is wiredep's or grunt's plugin issue for not forwarding bower error logs.

**Comment by caspii** [comment]
Ok thanks

**Comment by devonc0** [comment]
Glad I stumbled upon this, for some reason, this just did NOT stand out to me!!

"grunt unexpected token }"
