### ISSUE TITLE
Question: is bower auto-updating itself from github?

### ISSUE THREAD

**Issue by inf3rno** [bower/bower#1708]
From the documentation it is not clear to me how to update the packages when I increase the version number. By npm you have to run `npm publish`. Does bower auto-updates the stored packages from github after I registered the package, or how does this work?

Should I add only the browser specific builds to the bower.json and let nodejs ppl install my lib from npm? (currently only nodejs is supported by my lib, but I intend to support browsers with browserify later.)

**Comment by sheerun** [comment]
Please ask support questions on StackOverflow

**Comment by inf3rno** [comment]
Ok. I asked the question here: http://stackoverflow.com/questions/28782108/is-bower-auto-updating-itself-from-github I hope I don't get too many minus points...

**Comment by inf3rno** [comment]
@sheerun Actually this issue was about low quality documentation...

**Comment by sheerun** [comment]
Bower uses GitHub tags as version numbers.

The documentation PR and issues can be filled against https://github.com/bower/bower.github.io/issues

**Comment by inf3rno** [comment]
Okay.
