### ISSUE TITLE
Package listing is slow. Should default behavior be changed?

### ISSUE THREAD

**Issue by AlicanC** [bower/bower#1712]
I am using `bower.commands.list()` (programmatic API) to fetch the list of installed packages. It runs terribly slow and it looks like `PackageRepository.prototype.versions()` is causing it.

Calling of this function is understandable since the documentation defines the functionality as "List local packages **and possible updates**." which makes online lookups a must, but the command is "list" and not "check for updates". Shouldn't the default behavior exclude that check?

(Note for people who want to disable it: In CLI, `--offline` argument disables those checks. In the programmatic API, `bower.commands.list(null, {offline: true})` can be used.)

**Comment by sheerun** [comment]
Bower could change this behavior, but it would need to be behind a flag until major release.

**Comment by akullpp** [comment]
I stumbled upon this today and must say that this contradicts the principle of "do one thing and do it right". Why does `list` do two things at once? Not everybody wants the extra latency or has a connection at the point of executing the command. This is an premature assumption on the client's side which has to be reassessed.

**Comment by sheerun** [comment]
Bower is in maintenance mode now, no changes
