### ISSUE TITLE
Bower complains about missing entries in bower.json but they are not required in the spec

### ISSUE THREAD

**Issue by dolmen** [bower/bower#1713]
Bower 1.3.12 complains about missing entries `main` and `ignore` in [`Polymer/core-ajax/bower.json`](/Polymer/core-ajax/blob/08989202a860074221662c285764f65caadcbb72/bower.json), but those are only marked as _recommended_ in the [spec](/bower/bower.json-spec#main).

This is a false positive that just annoys the end user.

With bower 1.3.12 (just installed on a fresh new node 0.12.0):

```
$ bower install Polymer/core-ajax
bower not-cached    git://github.com/Polymer/core-ajax.git#*
bower resolve       git://github.com/Polymer/core-ajax.git#*
bower download      https://github.com/Polymer/core-ajax/archive/0.5.5.tar.gz
bower extract       core-ajax#* archive.tar.gz
bower invalid-meta  core-ajax is missing "main" entry in bower.json
bower invalid-meta  core-ajax is missing "ignore" entry in bower.json
bower resolved      git://github.com/Polymer/core-ajax.git#0.5.5
bower install       core-ajax#0.5.5

core-ajax#0.5.5 bower_components/core-ajax
└── polymer#0.5.5
```

**Comment by sheerun** [comment]
That's why you get a warning instead of an error :)
