### ISSUE TITLE
The "please choose one" dialogue should accept typing the version name as a way of indicating your choice

### ISSUE THREAD

**Issue by ExplodingCabbage** [bower/bower#1714]
This is amusingly petty, but...

Just now I ran a bower install and got this dialogue:

```
Unable to find a suitable version for firebase, please choose one:
    1) firebase#2.1.x which resolved to 2.1.2 and is required by angularfire#0.9.2 
    2) firebase#~2.2.1 which resolved to 2.2.1Prefix the choice with ! to persist it to bower.json

? Answer::
```

with the number at the beginning of each line (`1)` or `2)`) highlighted in pink, the version spec (`firebase#2.1.x` or `firebase#~2.2.1`) highlighted in blue, and the concrete version (`2.1.2` or `2.2.1`) highlighted in green.

Because I am an idiot, I did not notice that the lines were numbered and tried typing the full version number or version spec as my answer instead, repeatedly getting told "Invalid choice!" as bower rejected my attempts to answer. I suspect, though I have no evidence, that others must have been caught out by this dialogue and made the same mistake. It took me a few minutes to figure out how to proceed.

Accepting the user typing in a full version spec, or, where unambiguous, a full version, seems like it would help silly people like me who don't think of typing the line number as their response.

**Comment by jazzfog** [comment]
Agree, got stuck with the same :)

**Comment by sheerun** [comment]
Please send a PR :)

**Comment by graciano** [comment]
I just did the exact same thing and got stuck a few minutes searching for a possible bug or thinking the problem could be in the package.

**Comment by faceleg** [comment]
Added labels to indicate this is suitable for a beginner and is of low priority.

**Comment by theaverageguy** [comment]
Where will you make changes for this? A little help please.

**Comment by ptitgraig** [comment]
Instead of letting the user type version, shall we simply clarify the statement.
I suggest : _Unable to find a suitable version for <package-name>, please choose one by typing one of the number below:_

**Comment by BenMann** [comment]
@ptitgraig I'd honestly prefer that, especially because I think it is far more convenient to press one key instead of typing entire version numbers — I guess if we added the option and people knew about both possibilities, most would still just hit the number. Maybe even more important: it might prevent miss-typing the version more often.

**Comment by graciano** [comment]
I agree with @BenMann, if you show where to change the message in the source code, I can try here (I really want to contribute, even in such a small feature, to learn from it).

**Comment by echavezNS** [comment]
How can I trigger this conflict message? I would like to do a PR of what @ptitgraig suggested.

**Comment by BenMann** [comment]
So if you're both interested we could actually do both — your choice :)
The "easier" solution, which I also favor is located in `lib/templates/std/conflict.std`.
If you want to go and implement the possibility to type the entire version you should have a look at `lib/core/Manager.js`. To be more specific, conflicts start around [here](https://github.com/bower/bower/blob/master/lib/core/Manager.js#L712) and the actual choice is somewhere around [this line](https://github.com/bower/bower/blob/master/lib/core/Manager.js#L849) or slightly above.

To trigger this message you'd actually have to install a package that requires different versions of a certain package, or has dependencies that require different versions of a package. If the conflict cannot be resolved automatically (by choosing the higher version for example), the user is asked for input.

**Comment by thinkxl** [comment]
I was about to send a PR but I will leave it to @echavezNS or @theaverageguy

**Comment by echavezNS** [comment]
Thanks @thinkxl I just sent it.

**Comment by BenMann** [comment]
So part of this is implemented in https://github.com/bower/bower/pull/2212, but we can still implement the original idea behind the issue as well. If one of you is interested @thinkxl, @graciano or @theaverageguy just go for it.

**Comment by oskarcieslik** [comment]
Hi @BenMann, I came across this issue and decide to submit PR, I hope nobody was already assigned? :)

**Comment by graciano** [comment]
@oskarcieslik I was thinking about doing it, but didn't have the time, so it's ok ;)

**Comment by BenMann** [comment]
Nice, thank you everybody!
Closed by https://github.com/bower/bower/pull/2243 🎉

**Comment by seyisulu** [comment]
Hello everyone, I noticed this was closed but while using PowerShell on Windows 10 64 bit I did not even get to see the line numbers and a Google search brought me here.

I'm not sure if this should be a separate issue.

**Comment by graciano** [comment]
@seyisulu Look, I'll especulate a little here and I could be wrong, but here it goes:
I think most of the developers here doesn't even have windows in their computers and will not be available to help you. So I would try to download the source and try to debug it myself if I were you. If it's really necessary for you to keep trying to use it on windows.
