### ISSUE TITLE
Proposal: Bower should use a temporary directory if it can't access $HOME

### ISSUE THREAD

**Issue by chrisfosterelli** [bower/bower#1715]
Hey guys,

As per #1631 it appears that bower attempts to use the `HOME` environment variable. If it can't use it, then it crashes with an `EACCES` error. Normally that's fine, but there are some situations where that causes issues.

A good example would be a web application package in NPM that uses bower. Users install and download that package with `sudo npm install -g <packagename>`, but the package has a `postinstall` script that calls `bower install`. The problem is that NPM, when you are root, will run `postinstall` scripts as the user `nobody` but the `HOME` environment variable is still propagated. 

Therefore, this leads to `bower` trying to access a `HOME` directory it doesn't have access to because it's running as `nobody` and these types of packages can no longer be installed. My recommendation is that `bower` behaves like `node-gyp` where it tries to access the particular `HOME` directory, but if it can't then it creates it's own temporary directory to use for bower things.

Would this be an acceptable solution? My one concern is that I understand there are a number of areas where people will have genuine permission problems in their cache because they ran bower as sudo or something, and I'm worried doing this would mask that problem and cause them to basically get a fresh cache each time without realizing it. Some `WARN` messages could maybe help with that.

Thoughts on this?

**Comment by RQuadling** [comment]
Could bower set the environment for the post-install process?

**Comment by chrisfosterelli** [comment]
@RQuadling I'm not sure I understand what you mean. Bower _is_ the post-install process in this case, the problem is that it is taking the `HOME` variable of the user running `npm install` but the script is running as `nobody` due to how NPM works.

**Comment by RQuadling** [comment]
@chrisfosterelli So this is really an NPM issue? Can you tell it the user to run child processes with?

**Comment by sheerun** [comment]
Bower is deprecated now, and in maintenance mode. Because of this we won't implement new features like this one. We recommend switching to Yarn or npm, and migrating with [bower-away](https://github.com/sheerun/bower-away)
