### ISSUE TITLE
Npm install does nothing only on bower install 

### ISSUE THREAD

**Issue by zooter** [bower/bower#1717]
I tried installing bower using npm install bower -g. 
This lead to nothing expect the bar spinning for a long time. After the wait was over, I got the following error.

npm ERR! npm  v2.5.1
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request

I have a good internet connection and I am not behind any proxy. Soon after this I also tried installing other node modules globally and did not face any issues. 

My node version is 0.12.0
npm version 2.5.1
Mac OSX Yosemite
zsh

**Comment by sindresorhus** [comment]
> npm ERR!

https://github.com/npm/npm/issues
