### ISSUE TITLE
bower install command not found

### ISSUE THREAD

**Issue by Shyrine** [bower/bower#1720]
Hi :)

I'm struggling trying to install Bower. 
I alredy installed Bower with this command : [$ sudo npm install -g bower]
But when I try to check with: "bower --help" it says that the command is not found.
I tried to add "/usr/local/bin/npm" to my PATH doing: [$ export PATH="/usr/local/bin/npm:$PATH"]
but it is still not working.

Any idea ?

Thankkkssss

**Comment by sheerun** [comment]
Hey. Please ask support questions on StackOverflow. This is development issue tracker.

**Comment by Shyrine** [comment]
Thank you
