### ISSUE TITLE
windows slash appended to svn info by bower

### ISSUE THREAD

**Issue by fenchu** [bower/bower#1721]
Hi
I'm moving a project from a win2008 to a win2012 server.
The only difference is svn version 1.7.10(2012) and 1.7.5(2008)

bower update
:
bower buypass-grunt#0.1.8                                   ECMDERR Failed to execute "svn list https://svnserver.intra.buypass.no/svn/bpw/bower/buypass-grunt\tags --verbose", exit code of #1 svn: warning: W160013: Unable to connect to a repository at URL 'https://svnserver.intra.buypass.no/svn/bpw/bower/buypass-grunt%5Ctags' svn: E200009: Could not list all targets because some targets don't exist

This should be 
"svn list https://svnserver.intra.buypass.no/svn/bpw/bower/buypass-grunt/tags --verbose"

```javascript
$ cat bower.json
{
  "name": "minsideclient",
  "version": "1.4.2",
  "date": "2015-03-04 07:44:32 +00:00",
  "description": "Buypass min side client",
  "authors": [
    "Buypass AS"
  ],
  "homepage": "http://buypass.no",
  "private": true,
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests",
    "war",
    "dist",
    "coverage"
  ],
  "license": "Private",
  "dependencies": {
    "angular": "1.2.16",
    "angular-i18n": "1.2.5",
    "angular-sanitize": "1.2.16",
    "angular-route": "1.2.16",
    "angular-resource": "1.2.16",
    "angular-animate": "1.2.16",
    "jquery": "1.11.0",
    "angular-bootstrap": "0.10.0",
    "angular-ui-select2": "0.0.5",
    "jquery-ui": "1.10.3",
    "select2": "3.4.6",
    "fancybox": "2.1.5",
    "bootstrap": "3.1.1",
    "es5-shim": "2.3.0",
    "respond": "1.4.2",
    "html5shiv": "3.7.0",
    "buypass-bootstrap": "svn+https://svnserver.intra.buypass.no/svn/bpw/bower/buypass-bootstrap#~0.4.0",
    "buypass-grunt": "svn+https://svnserver.intra.buypass.no/svn/bpw/bower/buypass-grunt#0.1.8",
    "buypass-angular-utils": "svn+https://svnserver.intra.buypass.no/svn/bpw/bower/buypass-angular-utils#*",
    "angular-translate": "2.4.2",
    "angular-translate-loader-static-files": "~2.4.2"
  },
  "devDependencies": {
    "angular-mocks": "1.2.16"
  }
}
```

$ bower --version
1.3.12

$ node --version
v0.10.25

$ svn --version
svn, version 1.7.10 (r1485443)
   compiled Jun  1 2013, 09:36:13

I see the same if I run in cygwin, dos cli or jenkins. Any idea what it is.
All other projects on the server seem to work fine.

Thanks
Morten Bjoernsvik, Buypass, Oslo, Norway

**Comment by sheerun** [comment]
Any change you use bower version from `master` branch instead actual 1.3.12?

**Comment by fenchu** [comment]
Hi thanks for the reply. There was no changed with the latest from git master. But I found the error:
```javascript
Administrator@vmbld05it /cygdrive/c/jenkins/jobs/Min Side Client
$ npm install
/cygdrive/c/nodejs/nodejsv0.10.25/npm: line 2: $'\r': command not found
/cygdrive/c/nodejs/nodejsv0.10.25/npm: line 4: $'\r': command not found
/cygdrive/c/nodejs/nodejsv0.10.25/npm: line 5: syntax error near unexpected token `$'in\r''
'cygdrive/c/nodejs/nodejsv0.10.25/npm: line 5: `case `uname` in

Administrator@vmbld05it /cygdrive/c/jenkins/jobs/Min Side Client
$ dos2unix /cygdrive/c/nodejs/nodejsv0.10.25/npm
dos2unix: converting file /cygdrive/c/nodejs/nodejsv0.10.25/npm to Unix format...
```
when that file is in proper format it continues, probably if this file is in windows crlf mode it will give out '/'

Thanks again

**Comment by sheerun** [comment]
I don't understand. Is your issue resolved? The second error you posted seems like a different issue.
