### ISSUE TITLE
No configurations for ~/.config and ~/.local

### ISSUE THREAD

**Issue by dantran** [bower/bower#1725]
Hi,

Currently Bower writes to  ~/.config and ~/.local during build, to use a different set of locations, one can configure them using the 2 env.XDG_DATA_HOME and env.XDG_CONFIG_HOME variables respectively. However,  I'd like to set those 2 using  the command line instead similar to --config.storage.package --config.storage.registry and --config.tmp

what are the equivalent of those 2 env vars for bower configuration??

Much appreciated

**Comment by mreiche** [comment]
+1

**Comment by mreiche** [comment]
I dont know how to vote, so i just make +1

**Comment by sheerun** [comment]
There are none unfortunately and they won't be added as Bower is deprecated
