### ISSUE TITLE
Environment Variable alternative for --production

### ISSUE THREAD

**Issue by toastercup** [bower/bower#1729]
## Proposal

Right now, a `--production` flag can be applied to `install` and `prune`, but there is no way to skip `devDependencies` installation with an environment variable. I'm interested in a feature similar to Bundler's `BUNDLE_WITHOUT` environment variable, which acts as an alternative to the CLI flag `--without`. You can see this documented in their [man page](https://github.com/bundler/bundler/blob/a2343c9eabf5403d8ffcbca4dea33d18a60fc157/man/bundle-config.ronn#L88).
## Use Case

This would primarily be useful for server environments, where, ideally, the provisioning routine is controlled by environment variables rather than modifying a script per-environment, or the script detecting production vs. development and executing different commands for each.
## Implementation

I'm interested in creating the pull request for this feature. The implementation would be fairly straightforward: the only considerations in my mind are:
- The name of the env variable. `BOWER_PRODUCTION`, perhaps? Does Bower have any other examples of env variables in use right now?
- Which flag takes priority - I would almost certainly assume the CLI flag would override anything in the environment, but I will leave that up to the maintainer.

**Comment by sheerun** [comment]
Hey. I think ideally `--production` would be configuration flag (shortcut for --config.production=true).

In that case you would just use `BOWER_PRODUCTION=1`

For now CLI options are parsed separately from config options.

**Comment by sheerun** [comment]
Maybe you'd like to prepare PR for it + tests?

**Comment by Clement-TS** [comment]
Hi,
what is the current status of this enhancement?

**Comment by sheerun** [comment]
no progress has been done

**Comment by sheerun** [comment]
Bower is deprecated now, and in maintenance mode. Because of this we won't implement new features like this one. We recommend switching to Yarn or npm, and migrating with [bower-away](https://github.com/sheerun/bower-away)
