### ISSUE TITLE
fatal: unable to access 'https://github.com/angular/bower-angular.git/': Could not resolve host: github.com

### ISSUE THREAD

**Issue by siegfried01** [bower/bower#1730]
I'm having symptoms similar to those described here:
https://github.com/bower/bower/issues/689 

I tried the proposed solution:
git config --global url."https://".insteadOf git://

I'm still getting this error with a version of git and bower I installed today:

>bower install angular
bower not-cached    https://github.com/angular/bower-angular.git#*
bower resolve       https://github.com/angular/bower-angular.git#*
bower ECMDERR       Failed to execute "git ls-remote --tags --heads https://gith
ub.com/angular/bower-angular.git", exit code of #128

Additional error details:
fatal: unable to access 'https://github.com/angular/bower-angular.git/': Could not resolve host: github.com

This worked on my personal notebook computer running windows 8.1. However, when it failed on my work computer (windows 7) I thought that they might be blocking some sites. But clearly they are not blocking github since I can post this from my work computer.

I hope someone can help me resolve this error.
Thanks
Siegfried

**Comment by sheerun** [comment]
Did you try to execute in terminal following?

```
git ls-remote --tags --heads https://github.com/angular/bower-angular.git
```

Clearly they block it in your network. We probably can't do much about it.

**Comment by siegfried01** [comment]
Yes, I guess they are blocking it. They are not blocking my access to this forum, however! How could this be?

fatal: unable to access 'https://github.com/angular/bower-angular.git/': Could n
ot resolve host: github.com

**Comment by samccone** [comment]
yep seems like github is blocked on your network, nothing that we can do on our side. :\

**Comment by siegfried01** [comment]
Are there no work-arounds? Lots of other similar programs (like cygwin, maven, eclipse to name only a few) give you the option of installating on a machine with no network access by supplying a zip file on a memory stick. Is there not a git/bower command I can use to say "look at this memory stick" instead of fetching a zip from github?

**Comment by Praggie** [comment]
Hi,

   I am also getting same error though I am also behind coporate proxy but proxy allows the access. I get valid output (without any error) when I run git ls-remote --tags --heads https://github.com/angular/bower-material.git

But When I run command bower install i get following error.:

C:\RBWS\projects\learning\angular\material-start-master>bower install
bower not-cached    https://github.com/angular/bower-angular-aria.git#^1.3.x
bower resolve       https://github.com/angular/bower-angular-aria.git#^1.3.x
bower not-cached    https://github.com/angular/bower-angular-animate.git#v1.3.x
bower resolve       https://github.com/angular/bower-angular-animate.git#v1.3.x
bower not-cached    https://github.com/angular/bower-angular.git#^1.3.x
bower resolve       https://github.com/angular/bower-angular.git#^1.3.x
bower not-cached    https://github.com/angular/bower-material.git#~0.8.3
bower resolve       https://github.com/angular/bower-material.git#~0.8.3
bower ECMDERR       Failed to execute "git ls-remote --tags --heads https://github.com/angular/bower
-material.git", exit code of #128

Additional error details:
fatal: unable to access 'https://github.com/angular/bower-material.git/': Could not resolve host: gi
thub.com
           
Looks like issue is with bower not with network access.

**Comment by codex49** [comment]
You need to at least set an HTTP_PROXY variable environment.

set HTTPS_PROXY=http://<login_internet>:<password_internet>@aproxy:aport
set HTTP_PROXY=http://<login_internet>:<password_internet>@aproxy:aport

**Comment by joeaniu** [comment]
Hi, 
I have the same issue like what Praggie have said.

**Comment by anyangocynthia** [comment]
I changed to ssh and it worked

**Comment by mwilli23** [comment]
What the hell is a ssh???
