### ISSUE TITLE
Set default values for bower init from package.json

### ISSUE THREAD

**Issue by jisaacks** [bower/bower#1731]
When starting a new project, I always `npm init` and then `bower init` then I get asked mostly the same questions twice. It would be nice if bower read the equivalent values (name, version, description, license, etc.) from package.json if it exists and made those the defaults.

I am sorry if this has been brought up before. I did a quick search and didn't see it.

If this is an acceptable proposal, I could do the work and make a PR.

**Comment by sheerun** [comment]
This is totally acceptable :) PR would need tests, though.

**Comment by samccone** [comment]
:+1:

**Comment by jisaacks** [comment]
Awesome. I will see if I can knock this out this weekend.

**Comment by jisaacks** [comment]
Oops accidentally hit close and comment instead of just comment. My bad.

**Comment by jisaacks** [comment]
@sheerun I made a PR a couple weeks ago, that is about 95% complete. I have a test for the missing piece and it is currently failing until it gets implemented. I had asked for guidance on how to solve that remaining piece. Also I just naively dug in and solved this without being familiar with the code base so if there is a better way to solve it, I would be open to being corrected.
