### ISSUE TITLE
win2012 bower update hangs jenkins if bower v1.3.9 or higher

### ISSUE THREAD

**Issue by fenchu** [bower/bower#1733]
Hi
win2012r2 server with jekins hangs on command 'bower update' if I use version v1.3.9 or higher.
v1.3.8 is fine, but unfortunately some of our packages in many projects fails on older bower.
In different projects it hangs at different places. using the latest from git repository is the same.

![hds_client_hangs](https://cloud.githubusercontent.com/assets/11349883/6594926/a6e2d4ea-c7e5-11e4-9017-bea690c8d7c3.jpg)

Running the same build.bat scrip in cmd.exe/powershell/cygwin as same user work fine.

dumpthread in jenkins shows it is waiting for an interrupt:
"Executor #6 for master : executing Min Side Client #38" Id=8117 Group=main RUNNABLE (in native)
        at java.lang.ProcessImpl.waitForInterruptibly(Native Method)
        at java.lang.ProcessImpl.waitFor(ProcessImpl.java:448)
        at hudson.Proc$LocalProc.join(Proc.java:319)
        at hudson.tasks.CommandInterpreter.join(CommandInterpreter.java:137)
:

I do not get anything else in the jenkins logs.

I'm quite new to node/npm/bower/grunt so I will appreciate if You can guide me to debug this better. especially if it is possible to get better verbose output of bower update. I suspect it is output or return codes bower do not handle or poorly written modules.

We are not able to reproduce this in win2003.

Thanks
Morten Bjoernsvik, Oslo, Norway

**Comment by fenchu** [comment]
Fresh eyes helped fix this. Turned out it was jenkins using local system account, While I was testing with administrator. forcing jenkins to use administrator fixed this. Obviously the local system account has different settings on win2008 and win2012.

**Comment by samccone** [comment]
:+1: closing
