### ISSUE TITLE
"bower list" should return an exit code of 1 if a package is incompatible

### ISSUE THREAD

**Issue by avindra** [bower/bower#1734]
Sample:

```
bower list -o
```

Returns:

```
Project name#2.x /app/myapp
├── animate.css#3.2.0
├─┬ bootstrap#3.3.2
│ └── jquery#2.1.3
├─┬ bootstrap-select#1.6.4
│ └── jquery#2.1.3
├─┬ bootstrap-switch#3.3.2
│ ├── bootstrap#3.3.2
│ └── jquery#2.1.3
├─┬ fullcalendar#2.3.0 incompatible with 2.3.1
│ ├── jquery#2.1.3
│ └── moment#2.9.0
├── html5shiv#3.7.2
├── jquery#2.1.3
├── moment#2.9.0
├── placeholders#4.0.1
└─┬ rangeslider.js#1.0.0
  └── jquery#2.1.3
```
But the exit code:

```
$ echo $?
0
```

is 0. If it were 1, it would be easy to integrate a simple bower list check to verify that dependencies are installed.

**Comment by samccone** [comment]
hmm I am on the fence about this, 0 typically means no error has happened, and list in this case did work... seems like you are looking for something slightly different ... but again could be off base with this.

thanks for critically thinking about this one, something that is vey important for CLI tools.

@sheerun any thoughts?

**Comment by sheerun** [comment]
Non-zero status means bower command failed to do what it is supposed to do.

As @samccone says. It is correct behavior as bower correctly reports incompatible packages.

**Comment by avindra** [comment]
Ok fair enough, but if one wanted to validate the installed packages against the json manifest, they would have to grep for the string "incompatible" which is an ugly solution.

Is there a more automatic / proper way of achieving this?

**Comment by sheerun** [comment]
You can:

1. Pass --json flag to bower CLI and parse JSON output. It should contain
incompatible flags.
2. Use programmatic API of bower
