### ISSUE TITLE
Intermittent transitive dependency installed

### ISSUE THREAD

**Issue by ghost** [bower/bower#1739]
I've encountered a scenario where a transitive dependency is installed when it should not be included.  This issue occurs randomly.  Repeated runs of my scenario will sometimes install it, and sometimes not.  I've made a demonstration available on github.  This can be exercised by repeatedly running this command:
`rm -r bower_components && bower install https://github.com/Chewbone/packageA.git#1.0.x https://github.com/Chewbone/packageB.git#1.0.x`

Sometimes it will install 'packageUnwanted', and sometimes it will not.  It should never be installed.

The basic dependency graph and versions looks like this:
- packageA#1.0.0 dependsOn packageB#1.0-1.1
- packageB#1.0.0 dependsOn nothing
- packageB#1.1.0 dependsOn packageUnwanted#1.0.x

I want to prevent packageUnwanted from installing, so when running bower install, I explicitly choose the older version packageB#1.0.x that does not depend on it.  This triggers the intermittent installation of packageUnwanted.

**Comment by sheerun** [comment]
Bower is deprecated now, and in maintenance mode. Because of this we won't implement new features like this one. We recommend switching to Yarn or npm, and migrating with [bower-away](https://github.com/sheerun/bower-away)
