### ISSUE TITLE
Save without Install

### ISSUE THREAD

**Issue by iamkirkbater** [bower/bower#1743]
Hi,

I've been looking around for a little bit and I can't seem to find anything, but would there be any way to implement a --save --no-install type feature?  Basically just a way to save the package to the bower.json file without actually installing anything.

In my personal example, I have a folder created that stores a scaffolding.  It has a default Gruntfile, bower.json, .bowerrc, package.json, etc, and a bunch of empty folders.  I have a bash script that makes a copy of this folder and it's contents, and then runs npm install and then bower install.  Currently, when I add dependencies that I will re-use, I just copy and paste the line out of the bower.json file of the project that I'm working on and then paste it into the bower.json file in my starter folder.  While this process is okay and it works, having the ability to run a single command to do this for me would be perfect and more preferred.

Something along the lines of `bower install foundation --save --no-install` or something similar.  Looking through the documentation and google have both not turned up anything to what I'm trying to achieve, but I figured I'd ask to see if you guys already have anything like this.

Thanks,
K

**Comment by sheerun** [comment]
Hey. I am not aware of such functionality. You'd need to read, modify, and write bower.json with node.

**Comment by samccone** [comment]
yeah just looked and was unable to find anything similar in npm. :+1: to closing as a wontfix
