### ISSUE TITLE
ECONFLICT Unable to find suitable version for angular

### ISSUE THREAD

**Issue by zumpchke** [bower/bower#1746]
`bower install` with the following:
```
  "dependencies": {
    "json3": "^3.3.0",
    "es5-shim": "^4.0.0",
    "bootstrap": "^3.2.0",
    "angular-bootstrap": "^0.12.1",
    "angular-animate": "~1.3.x",
    "angular-cookies": "~1.3.x",
    "angular-resource": "~1.3.x",
    "angular-route": "~1.3.x",
    "angular-sanitize": "~1.3.x",
    "angular-touch": "~1.3.x",
    "angular-jwt": "~0.0.5",
    "components-font-awesome": "~4.2.0",
    "sparklines": "~1.0.0",
    "jstree": "~3.0.8",
    "bootstrap-switch": "~3.3.0",
    "bootstrap-tabdrop": "~1.0.0",
    "enquire": "~2.1.2",
    "bootbox": "~4.3.0",
    "angular-local-storage": "~0.1.5",
    "angular-ui-router": "~0.2.13",
    "ng-cookies": "~1.0.2",
    "modernizer": "~2.8.2",
    "fastclick": "*",
    "slimScroll": "~1.3.3",
    "jquery.easing": "~1.3.1",
    "jquery-appear": "~0.2.2",
    "jquery-placeholder": "~2.1.1",
    "angular-google-maps": "~2.0.13",
    "ng-timeago": "~0.0.2",
    "angular-loading-bar": "~0.7.1",
    "switchery": "~0.7.0"
  }
```

results in
 `ECONFLICT Unable to find suitable version for angular`

I have no idea how to debug this. I'm new to frontend development. What could be wrong?

**Comment by dancrumb** [comment]
Bower installs all your requested dependencies in the same directory.

It also installs all of *their* dependencies in the same directory.

If two modules each depend on a third module, but require different versions of that module that are incompatible, then bower will throw the ECONFLICT error.

For instance, if A requires C at version >2.0.0 and B requires C at version < 1.5.0, then there's no way for bower to resolve this and it throws that error.

**Comment by sheerun** [comment]
You can put suitable version of package in `resolutions` key of bower.json, as so:

```
"resolutions": {
  "angular": "1.3.0"
}
```

**Comment by TomasMatusek** [comment]
When A requires version of C 2.0 and B requires version of C 1.5, if I install 2.0 wont it break functionality of B that depends on 1.5 ?

**Comment by ionox0** [comment]
Yes I have this same question^

**Comment by Hanamant-Kadlimatti** [comment]
ECONFLICT Unable to find suitable version for angular-animate
iam getting above error. help me
