### ISSUE TITLE
Question: About Installing 1.3.12?

### ISSUE THREAD

**Issue by meuwe** [bower/bower#1749]
Hi,

I have bower 1.3.12, and I know nothing about this, I was assuming this is source that gets compiled and installed, but when I run ```npm install -g bower --prefix "$PKG/usr"``` in my build script all it seems to be doing is just copying the contents of the tar to;

/usr/lib64/node_modules/bower

``ls``

CHANGELOG.md  CONTRIBUTING.md  Gruntfile.js  HOOKS.md  LICENSE  README.md  bin  lib  node_modules  package.json  templates  test

So I'm not sure if this is correct or not? 

This is the build script I am using for slackware;

PRGNAM=bower
VERSION=${VERSION:-1.3.12}
BUILD=${BUILD:-1}
TAG=${TAG:-_foo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/foo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -eu

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

npm install -g bower --prefix "$PKG/usr"

cd $TMP/$PRGNAM-$VERSION
mv CHANGELOG.md CHANGELOG 
mv CONTRIBUTING.md CONTRIBUTING
mv HOOKS.md HOOKS
mv README.md README

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a CHANGELOG CONTRIBUTING HOOKS LICENSE README $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}

thank you

**Comment by meuwe** [comment]
Actually after posting this I just noticed my /install/doinst.sh had created the symlink for bower under /usr/bin, so looking at the below I guess it's all ok?

thanks again...

( cd usr/bin ; rm -rf bower )
( cd usr/bin ; ln -sf ../lib64/node_modules/bower/bin/bower bower )
( cd usr/lib64/node_modules/bower/node_modules/.bin ; rm -rf handlebars )
( cd usr/lib64/node_modules/bower/node_modules/.bin ; ln -sf ../handlebars/bin/handlebars handlebars )
( cd usr/lib64/node_modules/bower/node_modules/.bin ; rm -rf decompress-zip )
( cd usr/lib64/node_modules/bower/node_modules/.bin ; ln -sf ../decompress-zip/bin/decompress-zip decompress-zip )
( cd usr/lib64/node_modules/bower/node_modules/.bin ; rm -rf cdl )
( cd usr/lib64/node_modules/bower/node_modules/.bin ; ln -sf ../cardinal/bin/cdl.js cdl )
( cd usr/lib64/node_modules/bower/node_modules/.bin ; rm -rf mkdirp )
( cd usr/lib64/node_modules/bower/node_modules/.bin ; ln -sf ../mkdirp/bin/cmd.js mkdirp )
( cd usr/lib64/node_modules/bower/node_modules/.bin ; rm -rf semver )
( cd usr/lib64/node_modules/bower/node_modules/.bin ; ln -sf ../semver/bin/semver semver )
( cd usr/lib64/node_modules/bower/node_modules/.bin ; rm -rf nopt )
( cd usr/lib64/node_modules/bower/node_modules/.bin ; ln -sf ../nopt/bin/nopt.js nopt )
( cd usr/lib64/node_modules/bower/node_modules/.bin ; rm -rf rimraf )
( cd usr/lib64/node_modules/bower/node_modules/.bin ; ln -sf ../rimraf/bin.js rimraf )
( cd usr/lib64/node_modules/bower/node_modules/.bin ; rm -rf opn )
( cd usr/lib64/node_modules/bower/node_modules/.bin ; ln -sf ../opn/cli.js opn )
( cd usr/lib64/node_modules/bower/node_modules/.bin ; rm -rf which )
( cd usr/lib64/node_modules/bower/node_modules/.bin ; ln -sf ../which/bin/which which )
( cd usr/lib64/node_modules/bower/node_modules/request/node_modules/.bin ; rm -rf uuid )
( cd usr/lib64/node_modules/bower/node_modules/request/node_modules/.bin ; ln -sf ../node-uuid/bin/uuid uuid )
( cd usr/lib64/node_modules/bower/node_modules/update-notifier/node_modules/.bin ; rm -rf latest-version )
( cd usr/lib64/node_modules/bower/node_modules/update-notifier/node_modules/.bin ; ln -sf ../latest-version/cli.js latest-version )
( cd usr/lib64/node_modules/bower/node_modules/update-notifier/node_modules/configstore/node_modules/.bin ; rm -rf js-yaml )
( cd usr/lib64/node_modules/bower/node_modules/update-notifier/node_modules/configstore/node_modules/.bin ; ln -sf ../js-yaml/bin/js-yaml.js js-yaml )
( cd usr/lib64/node_modules/bower/node_modules/update-notifier/node_modules/configstore/node_modules/.bin ; rm -rf user-home )
( cd usr/lib64/node_modules/bower/node_modules/update-notifier/node_modules/configstore/node_modules/.bin ; ln -sf ../user-home/cli.js user-home )
( cd usr/lib64/node_modules/bower/node_modules/update-notifier/node_modules/configstore/node_modules/js-yaml/node_modules/.bin ; rm -rf esvalidate )
( cd usr/lib64/node_modules/bower/node_modules/update-notifier/node_modules/configstore/node_modules/js-yaml/node_modules/.bin ; ln -sf ../esprima/bin/esvalidate.js esvalidate )
( cd usr/lib64/node_modules/bower/node_modules/update-notifier/node_modules/configstore/node_modules/js-yaml/node_modules/.bin ; rm -rf esparse )
( cd usr/lib64/node_modules/bower/node_modules/update-notifier/node_modules/configstore/node_modules/js-yaml/node_modules/.bin ; ln -sf ../esprima/bin/esparse.js esparse )
( cd usr/lib64/node_modules/bower/node_modules/update-notifier/node_modules/string-length/node_modules/.bin ; rm -rf strip-ansi )
( cd usr/lib64/node_modules/bower/node_modules/update-notifier/node_modules/string-length/node_modules/.bin ; ln -sf ../strip-ansi/cli.js strip-ansi )
( cd usr/lib64/node_modules/bower/node_modules/insight/node_modules/.bin ; rm -rf os-name )
( cd usr/lib64/node_modules/bower/node_modules/insight/node_modules/.bin ; ln -sf ../os-name/cli.js os-name )
( cd usr/lib64/node_modules/bower/node_modules/insight/node_modules/os-name/node_modules/.bin ; rm -rf osx-release )
( cd usr/lib64/node_modules/bower/node_modules/insight/node_modules/os-name/node_modules/.bin ; ln -sf ../osx-release/cli.js osx-release )
( cd usr/lib64/node_modules/bower/node_modules/insight/node_modules/configstore/node_modules/.bin ; rm -rf js-yaml )
( cd usr/lib64/node_modules/bower/node_modules/insight/node_modules/configstore/node_modules/.bin ; ln -sf ../js-yaml/bin/js-yaml.js js-yaml )
( cd usr/lib64/node_modules/bower/node_modules/insight/node_modules/configstore/node_modules/.bin ; rm -rf user-home )
( cd usr/lib64/node_modules/bower/node_modules/insight/node_modules/configstore/node_modules/.bin ; ln -sf ../user-home/cli.js user-home )
( cd usr/lib64/node_modules/bower/node_modules/insight/node_modules/configstore/node_modules/js-yaml/node_modules/.bin ; rm -rf esvalidate )
( cd usr/lib64/node_modules/bower/node_modules/insight/node_modules/configstore/node_modules/js-yaml/node_modules/.bin ; ln -sf ../esprima/bin/esvalidate.js esvalidate )
( cd usr/lib64/node_modules/bower/node_modules/insight/node_modules/configstore/node_modules/js-yaml/node_modules/.bin ; rm -rf esparse )
( cd usr/lib64/node_modules/bower/node_modules/insight/node_modules/configstore/node_modules/js-yaml/node_modules/.bin ; ln -sf ../esprima/bin/esparse.js esparse )
( cd usr/lib64/node_modules/bower/node_modules/insight/node_modules/chalk/node_modules/.bin ; rm -rf strip-ansi )
( cd usr/lib64/node_modules/bower/node_modules/insight/node_modules/chalk/node_modules/.bin ; ln -sf ../strip-ansi/cli.js strip-ansi )
( cd usr/lib64/node_modules/bower/node_modules/insight/node_modules/chalk/node_modules/.bin ; rm -rf has-ansi )
( cd usr/lib64/node_modules/bower/node_modules/insight/node_modules/chalk/node_modules/.bin ; ln -sf ../has-ansi/cli.js has-ansi )
( cd usr/lib64/node_modules/bower/node_modules/insight/node_modules/chalk/node_modules/.bin ; rm -rf supports-color )
( cd usr/lib64/node_modules/bower/node_modules/insight/node_modules/chalk/node_modules/.bin ; ln -sf ../supports-color/cli.js supports-color )
( cd usr/lib64/node_modules/bower/node_modules/insight/node_modules/inquirer/node_modules/readline2/node_modules/.bin ; rm -rf strip-ansi )
( cd usr/lib64/node_modules/bower/node_modules/insight/node_modules/inquirer/node_modules/readline2/node_modules/.bin ; ln -sf ../strip-ansi/cli.js strip-ansi )
( cd usr/lib64/node_modules/bower/node_modules/inquirer/node_modules/readline2/node_modules/.bin ; rm -rf strip-ansi )
( cd usr/lib64/node_modules/bower/node_modules/inquirer/node_modules/readline2/node_modules/.bin ; ln -sf ../strip-ansi/cli.js strip-ansi )
( cd usr/lib64/node_modules/bower/node_modules/handlebars/node_modules/.bin ; rm -rf uglifyjs )
( cd usr/lib64/node_modules/bower/node_modules/handlebars/node_modules/.bin ; ln -sf ../uglify-js/bin/uglifyjs uglifyjs )
( cd usr/lib64/node_modules/bower/node_modules/decompress-zip/node_modules/.bin ; rm -rf nopt )
( cd usr/lib64/node_modules/bower/node_modules/decompress-zip/node_modules/.bin ; ln -sf ../nopt/bin/nopt.js nopt )
( cd usr/lib64/node_modules/bower/node_modules/decompress-zip/node_modules/touch/node_modules/.bin ; rm -rf nopt )
( cd usr/lib64/node_modules/bower/node_modules/decompress-zip/node_modules/touch/node_modules/.bin ; ln -sf ../nopt/bin/nopt.js nopt )
( cd usr/lib64/node_modules/bower/node_modules/chalk/node_modules/.bin ; rm -rf strip-ansi )
( cd usr/lib64/node_modules/bower/node_modules/chalk/node_modules/.bin ; ln -sf ../strip-ansi/cli.js strip-ansi )
( cd usr/lib64/node_modules/bower/node_modules/chalk/node_modules/.bin ; rm -rf has-ansi )
( cd usr/lib64/node_modules/bower/node_modules/chalk/node_modules/.bin ; ln -sf ../has-ansi/cli.js has-ansi )
( cd usr/lib64/node_modules/bower/node_modules/chalk/node_modules/.bin ; rm -rf supports-color )
( cd usr/lib64/node_modules/bower/node_modules/chalk/node_modules/.bin ; ln -sf ../supports-color/cli.js supports-color )
( cd usr/lib64/node_modules/bower/node_modules/cardinal/node_modules/redeyed/node_modules/.bin ; rm -rf esvalidate )
( cd usr/lib64/node_modules/bower/node_modules/cardinal/node_modules/redeyed/node_modules/.bin ; ln -sf ../esprima/bin/esvalidate.js esvalidate )
( cd usr/lib64/node_modules/bower/node_modules/cardinal/node_modules/redeyed/node_modules/.bin ; rm -rf esparse )
( cd usr/lib64/node_modules/bower/node_modules/cardinal/node_modules/redeyed/node_modules/.bin ; ln -sf ../esprima/bin/esparse.js esparse )
( cd usr/lib64/node_modules/bower/node_modules/bower-registry-client/node_modules/request/node_modules/.bin ; rm -rf uuid )
( cd usr/lib64/node_modules/bower/node_modules/bower-registry-client/node_modules/request/node_modules/.bin ; ln -sf ../node-uuid/bin/uuid uuid )

**Comment by sheerun** [comment]
I think it's correct, but you should open issue on NPM's repository, not bower's.

**Comment by meuwe** [comment]
ok thanks
