### ISSUE TITLE
Rename Package to lowercase

### ISSUE THREAD

**Issue by janpaepke** [bower/bower#1751]
Hi!

I'm posting this as an issue here, as suggested in the [bower mailing list](https://groups.google.com/forum/#!topic/twitter-bower/W4Bv8MO_nL0).

Here's the text:

Once upon a time I published my library "[ScrollMagic](https://github.com/janpaepke/ScrollMagic)" for bower.
For lack of knowledge and proper reading (shame on me) I did not adhere to the "lowercase only" naming convention back then.

With version 2.0.0 [i changed that](https://github.com/janpaepke/ScrollMagic/blob/25cbdccd5dd57a14c88f4396aa690d20308123a5/bower.json#L2) and now it's all lowercase.

How do I go about fixing that? Removing "ScrollMagic" is likely to cause problems with people who already set it as a dependency.
But I can't publish as "scrollmagic" because I get the error message that the package already exists.

Thanks for your help!

**Comment by sheerun** [comment]
Hey. You get that message, because package indeed actually exists :) It's the same repo.

Anyway, to allow for re-registration of mixed case character, I allowed temporally to register them again:
https://github.com/bower/registry/commit/7f2abeb52fcb1eab1b13950a64cb91df52241926

We need permanent solution, though.

**Comment by janpaepke** [comment]
Mh. when I initially tested it `bower install scrollmagic` didn't work. Now it does so I guess all is well :)

**Comment by electerious** [comment]
Is this issue still present? What's the best way to rename a package containing uppercase letters, without causing problems for existing users?

**Comment by sheerun** [comment]
You shoudn't. Just keep lowercase for new packages you create
