### ISSUE TITLE
Guidelines for using inside docker?

### ISSUE THREAD

**Issue by eichin** [bower/bower#1752]
`bower install` gives a verbose `ESUDO` when run inside docker (where you default to a (containerized) `root`, no `sudo` involved.)  As far as I know, people don't bother setting up users inside containers; is there a more clever alternative, or if not, could this error point to some useful docs? (Perhaps conditionalized on *not* finding `SUDO_USER` or `SUDO_COMMAND` in the environment, docker itself leaves the environment intentionally very clean.)

**Comment by eichin** [comment]
(also, it seems to force you to need `--config.interactive` which displays a bunch of `^[[1A?` escape sequences for what would otherwise be simple prompts.)

**Comment by samccone** [comment]
@eichin I have been using bower inside of docker for over a year now, with no issues, can I see your docker command and error output?

**Comment by eichin** [comment]
Stripped down, it's as simple as

    $ docker run -i eichin/chrome_apps_nocache bower --help
    bower ESUDO         Cannot be run with sudo

(Image is based on Debian Jessie; docker 1.3.3~dfsg1-2, bower 1.3.12.) The full message does explain `--allow-root` so I'm not blocked, but I'm hoping there's something better than "add an option to every command".

**Comment by jgoelen** [comment]
add the following line to the docker build 
```
RUN echo '{ "allow_root": true }' > /root/.bowerrc
```

**Comment by faddat** [comment]
Thank you!

**Comment by mhumeSF** [comment]
Me as well. Thanks! :+1:

**Comment by michaelperrin** [comment]
@jgoelen Thanks! :+1:

**Comment by wikier** [comment]
thx :+1:

**Comment by faceleg** [comment]
You can also use the --allow-root flag.

**Comment by citypaul** [comment]
@jgoelen this comment is still helping people two years later! Thanks!

**Comment by crizzs** [comment]
Thanks a lot!!!!

**Comment by ORESoftware** [comment]
So this then eh

`bower install --config.interactive=false --allow-root`

**Comment by FlavioAlexander** [comment]
Almost 3 years after and your solution @jgoelen is still relevant 😄

**Comment by crizzs** [comment]
Yes. The solution is still going strong 🥇

**Comment by sachin2919** [comment]
Thanks, it helped me.

**Comment by ZycaR** [comment]
> 
> 
> add the following line to the docker build
> 
> ```
> RUN echo '{ "allow_root": true }' > /root/.bowerrc
> ```

Thanks !

**Comment by DenisVerkhoturov** [comment]
> add the following line to the docker build
> 
> ```
> RUN echo '{ "allow_root": true }' > /root/.bowerrc
> ```
Isn't that crazy that in 2019 this page still saves lives? 😄 
Unfortunately, bower still used in a bunch of legacy projects. 😞
