### ISSUE TITLE
Error installing package

### ISSUE THREAD

**Issue by miguelsneto** [bower/bower#1756]
when I install a package I get the following error:
```bower                        EAI_AGAIN Request to URL failed: getaddrinfo EAI_AGAIN```

In this case URL is https://bower.herokuapp.com/packages/jquery.stellar of package stellar.js

**Comment by sheerun** [comment]
I cannot reproduce.. Any steps or `bower.json`?

**Comment by sheerun** [comment]
Also, what is your environment?

**Comment by miguelsneto** [comment]
I do not know what was happening. but I solved my problem by restarting the virtual machine.
