### ISSUE TITLE
'./manage.py bower_install' must return non zero exit code

### ISSUE THREAD

**Issue by crazyh** [bower/bower#1758]
Try the following:

    # ./manage.py bower_install foo-bar-baz-qwe -- --allow-root ; echo $?
    bower                                          ENOTFOUND Package foo-bar-baz-qwe not found
    0

Perhaps `./manage.py bower_install` must return 1 on errors. For example `./manage.py bower_freeze ; echo $?` (from root) will return 1 on error (because --allow-root is not specified).

I believe that is a fatal issue because you can not use ./manage.py bower_install in automated build scripts (I faced with this issue when building Docker image which runs bower_install).

**Comment by samccone** [comment]
Hi @crazyh 

bower does exit with the correct code:

![screen shot 2015-03-27 at 6 25 51 pm](https://cloud.githubusercontent.com/assets/883126/6878104/bc8eaa32-d4ae-11e4-97fe-53b61132d746.png)

without seeing manage.py it is going to be hard to help you debug, anyhow I do not think this is a bower issue. Let me know if you think it is.

**Comment by crazyh** [comment]
Opps, I have to send this issue into django-bower project instead. Sorry. )
