### ISSUE TITLE
Incorporate bower-installer into bower?

### ISSUE THREAD

**Issue by stefanruijsenaars** [bower/bower#1762]
It seems quite a few people are interested in this, would you consider bundling this with bower and turning it into a command line option?

See also:

https://scotch.io/tutorials/only-grab-the-files-you-need-while-using-bower
https://github.com/bower/bower/issues/1487
https://github.com/bower/bower/issues/1606
https://github.com/bower/bower/issues/1632
https://github.com/bower/bower/issues/1458
https://github.com/bower/bower/issues/1260
https://github.com/bower/bower/issues/837

**Comment by albertinad** [comment]
+1 to this one!

**Comment by joshuasnowball** [comment]
+1 here too. This would streamline my build process even more

**Comment by sheerun** [comment]
Bower is deprecated now, and in maintenance mode. Because of this we won't implement new features like this one. We recommend switching to Yarn or npm, and migrating with [bower-away](https://github.com/sheerun/bower-away)
