### ISSUE TITLE
bower 1.4.0 does not read .bowerrc upwards the directory tree

### ISSUE THREAD

**Issue by mfkddcwy** [bower/bower#1763]
bower version 1.4.0

my project dir structre
```
/
├── .bowerrc
└── test
      ├── lib
      └── bower.json
```

my `.bowerrc` file
```
{
  "directory": "lib"
}
```

when run
```
> cd test && bower install
```

the component was installed into `bower_components`, not the `lib`, when I use `bower#1.3.12`, it worked fine.

**Comment by sheerun** [comment]
This is clearly connected to https://github.com/bower/config/pull/24

We need to double check this behavior.

**Comment by sheerun** [comment]
I released 1.4.1 with appropriate fix. Could you confirm?

**Comment by mfkddcwy** [comment]
Done, without errors.

Good job!

**Comment by mfkddcwy** [comment]
I like the `.1`, happy ending happy day.
