### ISSUE TITLE
Unable to resolve a bower module with requre('bower') in node 0.12.2 and nvm, and bower installed globally

### ISSUE THREAD

**Issue by dmytro-shchurov** [bower/bower#1765]
I'm using `nvm` and the latest `node` which version is 0.12.2. Bower was installed with `package-script` node module at a `postinstall` stage, and can be found on global modules list as `bower@1.4.1` which is the latest at the moment. `$which` also finds bower. `$bower` commands them self work fine.
However, when I try to get a reference to the component with `require('bower')` at `prepublish` stage I get *Error: Cannot find module 'bower'*
UPD: the module can be only resolved when it is installed locally. Is this expected or not?

**Comment by sheerun** [comment]
Yes, it's expected http://stackoverflow.com/questions/15636367/nodejs-require-a-global-module-package
