### ISSUE TITLE
Tags in quotes don't work on Windows.

### ISSUE THREAD

**Issue by rquadling** [bower/bower#1767]
Hi.

There are a couple of tags that are in quotes ...

https://github.com/bower/bower/tree/%221.0.0%22

and

https://github.com/bower/bower/tree/%221.0.1%22

And as we all love windows, more than our own moms, please can these be fixed.

Ta.

Ever so nicely muchly!

**Comment by RQuadling** [comment]
Can we remove these tags as the use of double quotes is a #fail for windows.

**Comment by rquadling** [comment]
BUMP: Please can the duplicate tags in quotes be removed?

**Comment by jamesxv7** [comment]
I believe the following links should work:
- https://github.com/bower/bower/tree/v1.0.0
- https://github.com/bower/bower/tree/v1.0.1

If you understand it is not, feel free to reopen the issue.
