### ISSUE TITLE
bower update unconditionally reinstalls all packages

### ISSUE THREAD

**Issue by nschloe** [bower/bower#1770]
When trying to get [caching on travis](http://docs.travis-ci.com/user/caching/) to work for my front-end packages, I found that `bower update` doesn't do what I expected it to do, namely to

 1. Check which packages and versions are installed under `bower_components` and
 2. Update the ones that don't match the specs in `bower.json`.

Instead, what happens is that _all_ packages are overridden by whatever is specified in `bower.json`, no matter if they are up-to-date or not. This results in our travis tests taking 30% longer than necessary.

Any comments, opinions, hints here?

**Comment by sheerun** [comment]
That's one of the oldest open issues bower has: https://github.com/bower/bower/issues/256

This behavior needs to be tested and fixes, but we don't have resources to do so.

Feel free to help and send PR with fix :) 

A failing test for this behavior can be added to:
https://github.com/bower/bower/blob/master/test/commands/update.js
