### ISSUE TITLE
npm WARN unmet dependency

### ISSUE THREAD

**Issue by brobrts** [bower/bower#1771]
running os x yosemite, 
node: v0.12.2
npm: 2.7.4
 
just followed the tutorial for yeoman w/angularjs and bootstrap
had to run:  $ sudo chown -R usr_name /usr/local
and $ npm cache clean
$ yo doctor shows no problems

finally got a succesful directory generated with the following warnings that read more
like bugs:

npm WARN unmet dependency /Users/williamroberts/Devel/AngularJSProjects/mytodo/node_modules/grunt-google-cdn/node_modules/google-cdn/node_modules/cdnjs-cdn-data requires semver@'~2.2.1' but will load
npm WARN unmet dependency /Users/williamroberts/Devel/AngularJSProjects/mytodo/node_modules/grunt-google-cdn/node_modules/google-cdn/node_modules/semver,
npm WARN unmet dependency which is version 2.3.2
grunt-karma@0.10.1 node_modules/grunt-karma
└── lodash@2.4.1

updated generator via $ yo menu and got more of these: 
npm WARN unmet dependency /Users/williamroberts/Devel/AngularJSProjects/mytodo/node_modules/grunt-google-cdn/node_modules/bower requires chalk@'^1.0.0' but will load
npm WARN unmet dependency /Users/williamroberts/Devel/AngularJSProjects/mytodo/node_modules/grunt-google-cdn/node_modules/chalk,
npm WARN unmet dependency which is version 0.5.1
npm WARN unmet dependency /Users/williamroberts/Devel/AngularJSProjects/mytodo/node_modules/grunt-google-cdn/node_modules/google-cdn/node_modules/bower requires chalk@'0.5.0' but will load
npm WARN unmet dependency /Users/williamroberts/Devel/AngularJSProjects/mytodo/node_modules/grunt-google-cdn/node_modules/chalk,
npm WARN unmet dependency which is version 0.5.1
npm WARN unmet dependency /Users/williamroberts/Devel/AngularJSProjects/mytodo/node_modules/grunt-google-cdn/node_modules/google-cdn/node_modules/cdnjs-cdn-data requires semver@'~2.2.1' but will load
npm WARN unmet dependency /Users/williamroberts/Devel/AngularJSProjects/mytodo/node_modules/grunt-google-cdn/node_modules/google-cdn/node_modules/semver,
npm WARN unmet dependency which is version 2.3.2

Can you tell me what this means?  unmet dependencies sounds like stuff isn't going to work.

Thanks very much!
Billy

**Comment by samccone** [comment]
Hi @brobrts I think you filed this in the wrong repo.

Going to close for now, let me know if you think I am in error. good luck debugging!
