### ISSUE TITLE
version constraints with git tag endpoints

### ISSUE THREAD

**Issue by lfender6445** [bower/bower#1774]
My company has private repo, browser-detect - I'd like to use tilde operator to __auto update minor + patch level changes__

in my bower.json:
```
"dependencies": {
    "almond": "0.2.9",
    "browser-detect": "git@github.com:RentPath/browser-detect.js.git#0.1.0"
}
```
using `~ git@github.com:RentPath/browser-detect.js.git#0.1.0` does not appear to work, as bower will execute ls-remote tags via git to obtain this information.

Is there a work around for this when using git with bower.json?

**Comment by sheerun** [comment]
`git@github.com:RentPath/browser-detect.js.git#~0.1.0` should work

The documentation is pretty clear on it:
http://bower.io/docs/api/#install

**Comment by lfender6445** [comment]
i don't know how I missed that - i'm embarassed. thanks for the link
