### ISSUE TITLE
Local package mistakenly seen as svn ?

### ISSUE THREAD

**Issue by warpdesign** [bower/bower#1776]
I have an svn respository with a project.

With that project, I have defined a "shared" as private local bower component.

Within my main project, I have included the "shared" component as a local bower dependency, like this:
`dependencies: { "onmap-shared": "../shared" }`

If I run `bower install` within my project's directory, it works as expected, the local "shared" package is correctly installed.

However, after adding the local "shared" directory to SVN, a subdirectory ".svn" has been created into the shared's directory (that's how svn works of course, so no problem here). And then, if I try to run bower install from my main's project, apparently bower tries to retrieve the shared component using svn, and I get the error:

`bower onmap-shared#*                                        ENOSVN svn is not installed or not in the PATH`

I don't understand why it tries to fetch it using svn, it shouldn't.

**Comment by warpdesign** [comment]
Having a look at the bower source code, I think I found a problem in resolverFactory, around line 86.

Problem is that the resolver assumes that if you have a .svn at the root of your bower directory, it is an svn repository which may not be the case.

For exemple, you may have a whole project stored in svn which has two apps:

project/app1/bower.json
project/app2/bower.json
project/shared/bower/.json

If all three components are stored in the same svn repository, there will be a .svn directory found into project/shared/.svn as well as in each directory. But the .svn where the repository information is stored will be found in project/.svn

Now, if in project/app1/bower.json you add the shared component as local dependency:

dependencies: {
  'shared': '../shared'
}

If you type `bower install` from within project/app1 directory, bower will assume that app/shared is an svn repository and will call svn, which will fail, instead of simply copying the local project into project/app1/bower_components

**Comment by sheerun** [comment]
How to properly recognize svn repository?

**Comment by warpdesign** [comment]
That's a good question. I think "svn info" command line could be used for that: it returns the svn url of current directory, as well as the root url too. So if (root === current) that's a repository.

**Comment by mathilde-pellerin** [comment]
@warpdesign have you find a workaround for this issue? 
I have quite the same problem.

**Comment by warpdesign** [comment]
@mathilde-pellerin a quick and dirty (really dirty! ;)) would be to comment the lines of code https://github.com/bower/bower/issues/1776#issuecomment-93982858

For that you need to edit the bower's source file and comment out these lines.

- On Windows it would be in something like  `c:\Users/<username>/AppData/Roaming/npm/node_modules/bower/lib/core/resolverFactory.js`

- On MacOSX it would be in something like `/Users/<username>/.npm/bower/<your bower version>/package/lib/core/resolverFactory.js`

A proper fix would be to fix these lines so that promise is only resolved if the .svn directory is the root of the svn repository. The problem is that it's not easy to detect it. I'll ask in official SVN mailing list to see of someone can help.

**Comment by mathilde-pellerin** [comment]
Thanks @warpdesign, but I found a way little less dirty : I don't touch bower sources ;)

Instead, in my shared project, I automatically create dist folder after each build and automatically copy files of interest in their. So when my local project point to that folder in bower.json, there is no .svn folder and so no problem.
