### ISSUE TITLE
Release 1.4.2

### ISSUE THREAD

**Issue by sheerun** [bower/bower#1777]
It will be patch release fixing few old issues and one introduced in 1.4.0:

- [x] Auto-sort dependencies alphabetically (#1381)
- [ ] Fix auto-detecting shallow clone support for GitHub Enterprise (#1764)
- [ ] ???

Please vote for other patches to be applied :)

The best way to have your issue fixed is to prepare failing test + fix, and send it in PR.

**Comment by nwinkler** [comment]
Have we made a decision what to do about #1764? A command line switch, or further, more advanced detection of the kind of host?
