### ISSUE TITLE
Attempting to pull in a single JS file results in odd things.

### ISSUE THREAD

**Issue by RQuadling** [bower/bower#1781]
Hi.

I've got a project that would like to use https://github.com/kvz/phpjs/blob/master/functions/array/array_combine.js.

So I type ```bower install https://github.com/kvz/phpjs/blob/master/functions/array/array_combine.js --save``` and see ...

```
bower array_combine#*           cached https://github.com/kvz/phpjs/blob/master/functions/array/array_combine.js
bower array_combine#*         validate https://github.com/kvz/phpjs/blob/master/functions/array/array_combine.js#*
bower array_combine#*          install array_combine

array_combine bower_components\array_combine
```

This results in my ```bower.json``` file containing ...

```"array_combine": "https://github.com/kvz/phpjs/blob/master/functions/array/array_combine.js"```

At this stage, all looks good.

But the ```bower_components\array_combine``` directory contains 2 files. One called ```.bower.json``` and ```index.js```.

The ```.bower.json``` contains ...

```
{
  "name": "array_combine",
  "_cacheHeaders": {
    "Content-Type": "text/html; charset=utf-8"
  },
  "main": "index.js",
  "_source": "https://github.com/kvz/phpjs/blob/master/functions/array/array_combine.js",
  "_target": "*",
  "_originalSource": "https://github.com/kvz/phpjs/blob/master/functions/array/array_combine.js",
  "_direct": true
}
```

and the ```index.js``` file is actually a HTML file (not included as it is quite big).

Using ```bower-installer``` results in the html file (```index.js```) in ```.\jslib\array_combine\index.js```.

Something isn't right as I was expecting the file https://github.com/kvz/phpjs/blob/master/functions/array/array_combine.js in there somewhere.

Regards,

Richard.

**Comment by sheerun** [comment]
`https://github.com/kvz/phpjs/blob/master/functions/array/array_combine.js` is a HTML file.

You meant `https://raw.githubusercontent.com/kvz/phpjs/master/functions/array/array_combine.js`

**Comment by RQuadling** [comment]
Well. Of course I do. Banging head on desk ... BANG BANG BANG !!!!
