### ISSUE TITLE
I got a problem in windows 8 when installing bootstrap or any bower packages 

### ISSUE THREAD

**Issue by smager** [bower/bower#1782]
I got a problem in windows 8 when installing bootstrap or any bower packages 

when i tried this:
bower install twbs/bootstrap   
or
bower install git://github.com/twbs/bootstrap
then the result below, but not responding: 
bower bootstrap#*           not-cached git://github.com/twbs/bootstrap.git#*
bower bootstrap#*              resolve git://github.com/twbs/bootstrap.git#*
bower bootstrap#~3.2.0      not-cached git://github.com/twbs/bootstrap.git#~3.2.0
bower bootstrap#~3.2.0         resolve git://github.com/twbs/bootstrap.git#~3.2.0

but when I tried this it works, (but why? when you refer the documentation it will not work). 

bower install https://github.com/twbs/bootstrap

I only replace the "git" into "https"

also the problem when i use "bower install" for bower projects it will always fails because of the dependencies trying to download the "git" url package.

**Comment by sheerun** [comment]
probably proxy issues. we changed all git:// urls to https:// in registry so there should be less issues of this kind
