### ISSUE TITLE
Support ~/ paths for user home in .bowerrc

### ISSUE THREAD

**Issue by btilford** [bower/bower#1784]
I work on a team that is sharing .bowerrc files since we are using an internal registry however there is no way to specify storage paths (cache/registry) in a way that works for all users without supporting `~/path`.

Currently anything that begins with a `~` will create a directory called `~` inside the project instead of inside the user's home directory.

**Comment by howardroark** [comment]
Yeah this is very confusing, I assume it is a bug.  The documentation seems to suggest that this is possible... http://bower.io/docs/config/#directory

Also if you specify an absolute system path bower just strips off the first slash and makes all the folders relative to the  `cwd`... `/home/user` becomes `home/user`.

**Comment by sheerun** [comment]
@watilde @btilford @howardroark I'm reverting this because it should be implemented in bower/config repository in "normalize" function.. https://github.com/bower/config/blob/master/lib/Config.js#L84

**Comment by watilde** [comment]
Ahh ok, that seems better to me too! I'll try it again :)

**Comment by sheerun** [comment]
Just please make sure it works and doesn't break backward compatibility before sending a PR :)

**Comment by watilde** [comment]
Resolved by https://github.com/bower/config/pull/42. Looks nice :)

**Comment by sheerun** [comment]
It'll be released really soon
