### ISSUE TITLE
I have added the proxy settings,. but still bower is giving me 407 error

### ISSUE THREAD

**Issue by maheshk172** [bower/bower#1785]
I have added proxy settings in both .bowerrc and also on environment variables. 

.bowerrc
{
  "registry": "http://bower.herokuapp.com",
  "proxy": "http://<userid:pass>@<proxyHost:port>",
  "https-proxy": "http://<userid:pass>@<proxyHost:port>"
}

on Environment variables 
HTTP_PROXY 
HTTPS_PROXY

These both are pointing to same proxy as .bowerrc. 

Below is error I get.

C:\Workspaces\BootstrapWorkspace\BootstrapProject>bower install jquery
bower                          EINVRES Request to http://bower.herokuapp.com/packages/jquery failed with 407

At same time, with same proxy settings my git and npm are working fine.

please advise.

**Comment by samccone** [comment]
Hi @maheshk172 this is going to be pretty hard to debug without more details.  Can you paste your proxy settings?

**Comment by maheshk172** [comment]
I cant mate, those are office proxies.  But I can assure that proxy settings seems correct as I am able to access npm and git with same proxies.  I am able to download npm modules. 

Its problem with Bower only, I might be missing something.  

Can you share me sample .bowerrc file with sample settings, which I can compare.

**Comment by igorlino** [comment]
Hi @maheshk172, from experience, while trying to debug something quite complicated to understand what truly helped me was to add debug traces at the bower source code. 

Thats the beauty of bower and the ability to see and easy modify its code locally.

The files Project.js and GitHubResolver.js are a very good candidates/places to add trace code.
If bower was installed globally, then you may find them in some directory under:
C:\Users\some-user\AppData\Roaming\npm\node_modules\bower\

As example, adding/placing in line 73 of GitHubResolver.js
```javascript
	var opts = {
        proxy: this._config.httpsProxy,
        strictSSL: this._config.strictSsl,
        timeout: this._config.timeout,
        headers: reqHeaders
    };
	
	console.log("\ntarballUrl:"+tarballUrl);
    console.log("\nopts:"+JSON.stringify(opts, null, 4));

	// Download tarball
    return download(tarballUrl, file, opts)
```

would give you some insight what call is being done from bower.

You may even want to print your the config object:

```javascript
console.log("\nconfig:"+JSON.stringify(_config, null, 4));
```

You may discover that maybe the config bowerrc is something else.

**Comment by mcgraphix** [comment]
I'm experiencing the same exact thing. It is driving me nuts. Git and NPM both work fine. I can hit the url in the browser without issue. In my case I have a local CNTLM proxy. My config is:

{
    "proxy": "http://localhost:3128",
    "https-proxy": "http://localhost:3128",
    "strict-ssl": false,
    "directory":"bower_components",
    "registry":"http://bower.herokuapp.com"
}

$ bower install jquery
bower EINVRES       Request to http://bower.herokuapp.com/packages/jquery failed with 407

If I take out the "registry" line I get this:
bower retry         Request to https://bower.herokuapp.com/packages/jquery failed with ECONNRESET, retrying in 1.0s

removing the strict-ssl variable or setting it to true makes no difference.

**Comment by mcgraphix** [comment]
It seems that my CNTLM proxy was the issue. I'm not sure why git and npm worked, but for some reason they did even though CNTLM proxy was messed up where Bower didn't.

**Comment by sheerun** [comment]
It will be fixed in next version of bower via https://github.com/bower/config/commit/5343803017c81034011c7098466187dfab4ec199

**Comment by punitganshani** [comment]
I am still getting this issue in version `1.8.0`
In which version will this be released?

**Comment by sheerun** [comment]
It's already released. And there's no bower 1.8.0 yet.

I've checked it and proxy settings work for 1.7.1. There are also test for them.

407 means there's authentication issue with your proxy. If you're really sure it's bower's error, please re-open another issue with exact steps to reproduce (e.g. shell script with proxy in docker container).
