### ISSUE TITLE
Drop Down List of Most Commonly used License in "bower init"

### ISSUE THREAD

**Issue by anand1ezeeway** [bower/bower#1787]
While creating a boer.json file if we get the List of most commonly uses licenses to choose from than it will be great. Like we have for moduleType. We can have MIT  --> pointing to the website where user can find the more details about that license

**Comment by sheerun** [comment]
For now MIT as a default is OK.. Unless you'd like to prepare a PR that puts link to https://spdx.org/licenses/ somewhere
