### ISSUE TITLE
why bower info takes a long time to finish?

### ISSUE THREAD

**Issue by chapgaga** [bower/bower#1788]
why it need to download a file whose size is 3mb?

bower info bootstrap
bower cached        git://github.com/twbs/bootstrap.git#3.0.3
bower validate      3.0.3 against git://github.com/twbs/bootstrap.git#*
bower new           version for git://github.com/twbs/bootstrap.git#*
bower resolve       git://github.com/twbs/bootstrap.git#*
bower download      https://github.com/twbs/bootstrap/archive/v3.3.4.tar.gz
bower progress      bootstrap#\* received 0.5MB of 3.0MB downloaded, 17%
bower progress      bootstrap#\* received 0.5MB of 3.0MB downloaded, 18%
bower progress      bootstrap#\* received 0.6MB of 3.0MB downloaded, 19%
bower progress      bootstrap#\* received 0.6MB of 3.0MB downloaded, 20%
bower progress      bootstrap#\* received 0.6MB of 3.0MB downloaded, 21%
bower progress      bootstrap#\* received 0.7MB of 3.0MB downloaded, 22%
bower progress      bootstrap#\* received 0.7MB of 3.0MB downloaded, 23%
bower progress      bootstrap#\* received 0.7MB of 3.0MB downloaded, 24%
bower progress      bootstrap#\* received 0.8MB of 3.0MB downloaded, 26%
bower progress      bootstrap#\* received 0.9MB of 3.0MB downloaded, 29%
bower progress      bootstrap#\* received 1.0MB of 3.0MB downloaded, 34%
bower progress      bootstrap#\* received 1.1MB of 3.0MB downloaded, 37%
bower progress      bootstrap#\* received 1.2MB of 3.0MB downloaded, 40%
bower progress      bootstrap#\* received 1.3MB of 3.0MB downloaded, 43%
bower progress      bootstrap#\* received 1.3MB of 3.0MB downloaded, 44%
bower progress      bootstrap#\* received 1.4MB of 3.0MB downloaded, 45%
bower progress      bootstrap#\* received 1.4MB of 3.0MB downloaded, 47%
bower progress      bootstrap#\* received 1.5MB of 3.0MB downloaded, 48%
bower progress      bootstrap#\* received 1.5MB of 3.0MB downloaded, 50%
bower progress      bootstrap#\* received 1.6MB of 3.0MB downloaded, 52%
bower progress      bootstrap#\* received 1.6MB of 3.0MB downloaded, 54%
bower progress      bootstrap#\* received 1.7MB of 3.0MB downloaded, 58%
bower progress      bootstrap#\* received 1.8MB of 3.0MB downloaded, 61%
bower progress      bootstrap#\* received 1.9MB of 3.0MB downloaded, 63%

**Comment by sheerun** [comment]
That's how much bootstrap's tag archive weights. It's expected.
>
>

**Comment by chapgaga** [comment]
@sheerun what happened when using bower info? download latest git repo rather than get the meta data?

**Comment by sheerun** [comment]
@chapgaga Yup. It downloads repo and reads bower.json. We could try to optimize it for some services like GitHub, but it's not possible in general case. Feel free to send a PR.

**Comment by sheerun** [comment]
sheerun@sher.pl sent you an invitation to join MEGA.\n\n";

--- Message from user: ---
Hello, join me on MEGA and get access to encrypted storage and
communication. Get 50 GB free!
---

Please create your free MEGA account by clicking on the following
link:\n\n";
https://mega.nz/#newsignupcmVwbHkrMDAwNDc2MGQxNWJiNTEwOWM1YzMzNWM4NDMyODM2NTA2ODUwZGMxNWMwZGZkMWFiOTJjZjAwMDAwMDAxMTE1NWI1OWQ5MmExNjljZTA0M2VhZjAzQHJlcGx5LmdpdGh1Yi5jb22Z-SVtlA2w2A

Best regards,

Team MEGA
