### ISSUE TITLE
problem with resolutions properties in programmatic api

### ISSUE THREAD

**Issue by tuto** [bower/bower#1789]
Hello

I'm to try install a package from programmatic api 

  bower.commands
                 .install([name], {force:true, allowRoot:true})
                 .on("error", function(error) {
                        console.log("!!!! ERROR" + error);
                 })
                 .on("end", function (result) {
                        console.log("result" + result );
                })

and this package have  2 or more dependencies diferent for the same library. This give me this error

"underscore: Unable to find suitable version for underscore"

This working with "resolutions" properties in bower.json but in the programatic way doesn't works.

**Comment by Xiphe** [comment]
having the same issue. Have you figured out a way, yet?

**Comment by sheerun** [comment]
This issue got stale. If this is still relevant, please create another one
