### ISSUE TITLE
Bower should provide optional target path segment input on dependencies.

### ISSUE THREAD

**Issue by My2Cents** [bower/bower#1790]
When installing packages from different sources, risk is high that packages' file names collide.

I suggest to add an option to Bower to have different packages be installed into their corresponding sub folders, so each package will get installed into its dedicated folder.

For example, `jQuery 2.0` should be installed into `/scripts/jQuery-2.0`, whereas `Bootstrap 2.3.0.0` should be installed into `/styles/Bootstrap-2.3.0.0` and `/scripts/Bootstrap-2.3.0.0`, resp.

<br/>
__So, basically, I suggest to ...__
  1. either take the package name, incl. version number, from the package, or
  1. introduce an option to the `install` command for providing a user defined path segment name.

<br/>
__Examples__

  1. The command line `$ bower install jquery#1.11.1` should install the corresponding jQuery package to `/scripts/jquery-1.11.1/`
  1. Similarly, the command line `$ bower install jquery#~1.11` should install the corresponding jQuery package to `/scripts/jquery-1.11.1/`
  1. The command line `$ bower install jquery#1.11.1 myJQuery` should install the corresponding jQuery package to `/scripts/myJQuery/`

The bower.json configuration file syntax should be amended to accept an optional, additional path segment parameter by use of an anonymous object type:

    "dependencies":
    { "<name>": "<version>"
    , "<name>": "<folder>"
    , "<name>": "<package>"
    , "<name>": { selector: "<version>", pathSegment: "<pathSegment>" }
    , "<name>": { selector: "<folder>", pathSegment: "<pathSegment>" }
    , "<name>": { selector: "<package>", pathSegment: "<pathSegment>" }
    }

If no path segment argument is provided for the `install` command then dependencies should be saved in the basic syntax (= string value) and the path segment should be taken from the package name.

**Comment by sindresorhus** [comment]
You can already give it a custom name: http://bower.io/docs/api/#install

What you suggest is too convoluted.
