### ISSUE TITLE
Unregistering a Package

### ISSUE THREAD

**Issue by barefootcss** [bower/bower#1792]
Hope this is not conflusing...

* I created a git repository and registered it with bower
* I unregistered and deleted the repository thinking I didn't need it.
* Then, I tried repeating the progress and it told me I'm not the collaborator

Here are some of the errors I received.

**When unregistering bare-normalize:**

     EFORBIDDEN    Must be a collaborator on GitHub.com repository

**When registering bare-normalize:**

     EDUPLICATE    Duplicate package

**When getting `bower info` on bare-normalize**

1st Attempt

      Returned the JSON

2nd Attempt

     ECMDERR       Failed to execute "git ls--remote -tags"

I am logged into bower as proper git contributer too who registered the package.

**Comment by barefootcss** [comment]
The name of the package is bare-normalize if you need to know that.

**Comment by sheerun** [comment]
Hey. Please reopen this issue on https://github.com/bower/registry

You could try to temporarily create empty repo in old location, remove it from bower, and then remove it from github once again.
