### ISSUE TITLE
Confusing warning message when bower.json is not found

### ISSUE THREAD

**Issue by rehmsen** [bower/bower#1795]
The warning messages

> bower Example#*           invalid-meta Example is missing "main" entry in bower.json
> bower Example#*           invalid-meta Example is missing "ignore" entry in bower.json

are confusing when no bower.json was found at all. I had a bower.json checked in, but not on the "latest" tag, and did not realize why its not parsing my main and ignore entry. My mistake would have been much more obvious if the warning message had read

> bower Example#*           invalid-meta Example is missing bower.json

**Comment by sheerun** [comment]
We removed these warnings
