### ISSUE TITLE
fail to install a github module using `https`

### ISSUE THREAD

**Issue by stevemao** [bower/bower#1798]
My module https://github.com/stevemao/angular-ical is using https://github.com/mozilla-comm/ical.js as a dep and it's not registered on bower. So i wanted to use `https` to install it but it fails. I tried `ssh` and it works (https://github.com/stevemao/angular-ical/blob/master/bower.json#L6). However if one does not setup a `ssh` key it will fail to install. Travis also complains about it https://github.com/stevemao/angular-ical/issues/1. Is there a way to install by `https` or do you have a better suggestion? Thanks.

**Comment by badger27** [comment]
Steve came you tell me how to unsubscribe from this blog

**Comment by jamesxv7** [comment]
@stevemao Since [jsical](https://github.com/mozilla-comm/ical.js) now [supports](https://github.com/mozilla-comm/ical.js/pull/155) Bower, this item is not longer an issue.
