### ISSUE TITLE
bower should fetch local modules without needing --force

### ISSUE THREAD

**Issue by bblack** [bower/bower#1799]
In my bower config, I have a local dependency, e.g.:

```
{
  "dependencies":
    ...
    "foo": "/home/bblack/foo.js"
}
```

It would be nice to have the changes to that file pulled in by bower on a `bower install`. As it is, I have to either do `bower install --force`, which re-installs _everything_, or `bower install -f foo` every time I know that the file contents have changed in `/home/bblack/foo.js`.

**Comment by rquadling** [comment]
Doesn't ```bower update``` do what you need?

**Comment by bblack** [comment]
No.

**Comment by sheerun** [comment]
Unfortunately bower is deprecated and no new features will be implemented
