### ISSUE TITLE
bower list simple but with versions

### ISSUE THREAD

**Issue by tablatronix** [bower/bower#1800]
`bower list -r` provides version information
`bower list -p` does not

I was hoping for a way to grab components and their current versions in __simple__ JSON or parse-able format.
`-p with versions`

-j is an option, but not simple, tmi.

**Comment by sheerun** [comment]
There's always `--json` switch

**Comment by tablatronix** [comment]
`--json` is not consumable without reparsing, it contains local paths, contains thousands of lines of json, etc. Not something you would distribute.

I was interested in current versioning information for cache control, either combined with -p -r output or a entirely separate simple consumable json list.

```JSON
  "ckeditor": 4.5.9,
  "codemirror": 5.14.2
```

I suppose I can re-parse from --jsont myself into my own file.

`dependencies->_itemid->pkgMeta=>version`  looks promising

**Comment by tablatronix** [comment]
using jq.js (https://github.com/stedolan/jq)
This filter pattern should work for what i need , if it helps anyone.

```
{dependencies}[]|map_values(keys,{pkgMeta}[].version)
```
