### ISSUE TITLE
Intermittent DNS resolution issues

### ISSUE THREAD

**Issue by ryanbagwell** [bower/bower#1801]
I've been encountering intermittent DNS resolution issues with bower.herokuapp.com

Here's a sample of the error I'm encountering:

````
bower fizzy-ui-utils#~1.0.1                                 error Request to https://bower.herokuapp.com/packages/fizzy-ui-utils failed: Hostname/IP doesn't match certificate's altnames
````

When I make a request to http://bower.herokuapp.com/ in the browser, it looks like somebody else's app is returned (some sort of DNA analysis going on):

![screen shot 2015-05-18 at 11 02 45 am](https://cloud.githubusercontent.com/assets/365105/7684667/7c576676-fd4d-11e4-9f97-8df7764786b3.png)

bower.herokuapp.com resolves to a cname with multiple IP addresses. Occasionally it resolves correctly, but most of the time it fails.

**Comment by shimultaleb** [comment]
Same thing happening for me. Any update on this ?

**Comment by sheerun** [comment]
Registry got more stable recently
