### ISSUE TITLE
Cannot use CLI or env vars to set registry.search array

### ISSUE THREAD

**Issue by hitsthings** [bower/bower#1804]
## Background 

registry.search is meant to be an array of URLs to use for searching for bower components. I'd like the equivalent of this .bowerrc:

```
{
  "registry": {
    "search": [
      "https://my-private-bower-registry",
      "https://bower.herokuapp.com"
    ]
  }
}
```

In my particular case, env vars or CLI args are the most convenient way to configure this (the build server I'm running on exposes no concept of the current user or global, so I can't configure my .bowerrc "globally", and it would not be maintainable to put this configuration in each of the N Bower components I'll be calling `bower install` from on the build server).

## Attempts

I've tried different variations on the following types of things:

```
bower install --config.registry.search=["https://my-private-bower-registry", "https://bower.herokuapp.com"]
```

```
set bower_registry__search__0="https://my-private-bower-registry"
set bower_registry__search__1="https://bower.herokuapp.com"
bower install
```

## Actual results

The first one results in config like

```
{
  "registry": {
    "search": "[\"https://my-private-bower-registry\",\"https://bower.herokuapp.com\"]"
  }
}
```

That is, a string in the shape of an array

The second results in config like:

```
{
  "registry": {
    "search": [
        { "0" : "https://my-private-bower-registry", "1" : "https://bower.herokuapp.com" }
    ]
  }
}
```

And Config.js line 65 barfs on this shape.

Is it impossible to do what I'm trying to do?

**Comment by sheerun** [comment]
Bower now accepts arrays in cli & env args
