### ISSUE TITLE
Hook scripts - directory

### ISSUE THREAD

**Issue by oytuntez** [bower/bower#1806]
Hello,

I am trying to use a post-install script (this is my final, working command):

``` bash
ln -s ../../../theme.config components/semantic-ui/src/theme.config
```

The source "theme.config" file is actually in the directory `bower` runs. So this command should actually read like this:

``` bash
ln -s theme.config components/semantic-ui/src/theme.config
```

This command should link `components/semantic-ui/src/theme.config` to `theme.config` in current bower.json directory. However, instead the link look like this: `theme.config -> theme.config`.

Then I thought, perhaps the post-install script is running under the component directory:

``` bash
ln -s ../../theme.config src/theme.config
```

This is throwing file not found error, so the script is not running under the component directory. But if I write the command considering the bower script is running on the same directory with bower.json, then this time the linked file is not pointing to the correct file (it is pointing to the linked file itself, recursively).

Am I doing something weird?

**Comment by sheerun** [comment]
This issue should be posted on stackoverflow first
