### ISSUE TITLE
"directory" setting in bower.json

### ISSUE THREAD

**Issue by robahl** [bower/bower#1807]
Move the `"directory"` config directive into `bower.json`, as you either way change it project wise I see no reason why it must be in a `.bowerrc`.

**Comment by jwvanderbeck** [comment]
Does this even work? I am trying to use this setting and no matter where I put it, bower is just ignoring it and still installing into bower_components.  I am trying to install into public/lib.  I've tried putting it into both the bower.json and the bowerrc.

```
{
    "directory": "public/lib"
}  
```

**Comment by sheerun** [comment]
directory is in .bowerrc because it doesn't apply to dependencies. .bowerrc is owned by app
