### ISSUE TITLE
Option to clone complete git repo like Composer's --prefer-source

### ISSUE THREAD

**Issue by christianmagill** [bower/bower#1809]
I'd love to see an option to clone a package's complete git repository, as Composer does with --prefer-source.

This would make it easier to submit changes to these packages from within the context of overarching projects.

**Comment by stevevanhooser** [comment]
I second this. This seems like a big hole in the present implementation. There's a long discussion in this issue:  https://github.com/bower/bower/issues/183 that was closed but no enhancement was made to the master branch.

**Comment by sheerun** [comment]
Bower is deprecated now, and in maintenance mode. Because of this we won't implement new features like this one. We recommend switching to Yarn or npm, and migrating with [bower-away](https://github.com/sheerun/bower-away)
