### ISSUE TITLE
EINVALID Failed to read [dirpath] The name contains upper case letters

### ISSUE THREAD

**Issue by arbixy** [bower/bower#1810]
Everything worked fine and bower suggested update so I moved to 1.4.1 and
BOOM nothing works now.
Can't install a single module none

`EINVALID Failed to read [dirpath]
Additional error details:
The name contains upper case letters`

Thank you. Appreciate it.

**Comment by Xal3ph** [comment]
I had to downgrade to 1.3.9 to resolve this.

```
npm uninstall bower -g
npm install bower@1.3.9 -g
```

I wonder if they'll resolve this in a future build or if this is just a standard that bower is now enforcing.

**Comment by arbixy** [comment]
@Xal3ph The problem occurs when the folder you download to has downloads from the previous version. Just rename the old one to something else and start from scratch with the new version.
A least that worked for me.

**Comment by sandermarechal** [comment]
It seems that clearing the cache does not work any longer with bower 1.4.1.

**Comment by sheerun** [comment]
This issue got stale, please create another one if it's still an issue
