### ISSUE TITLE
Running bower multiple times yields inconsistent results

### ISSUE THREAD

**Issue by svenstaro** [bower/bower#1811]
I ran bower multiple times in completely different locations on different machines and it results in entirely different results. Sometimes I get 

```
bower angular               resolution Unsuitable resolution declared for angular: ~1.3.15
bower                        ECONFLICT Unable to find suitable version for angular
```

Sometimes it works, sometimes it suggests different resolutions. It's like roulette and my success running bower seems to depend on which bower database server decides to serve my request in that moment.

I'm rather certain this is not an issue on my side.

I consider this a critical problem and I've been having this for days if not weeks.

**Comment by timesqueezer** [comment]
I've got exactly the same issue. I couldn't reproduce it to find a cause that explains why this sometimes happens and sometimes not.

**Comment by DonSailieri** [comment]
Very annoying, makes continuous deployment impossible and kinda defeats the purpose of a version-control system for software. Consistency should be the first consideration.

**Comment by Kaneraz** [comment]
I'm also having problems with angular versioning. If I run bower install and select a version angular resolves to 1.4.0. If I persist that selection as ^1.3.0 it selects version 1.3.15. You can see in the persisted install ^1.3.0 resolves to 1.4.0 and 1.3.15


>>Please note that,
>>    angular-bootstrap-duallistbox#0.0.3 depends on angular#~1.3.3 which resolved to angular#1.3.15
>>    angular-spinner#0.5.1 depends on angular#>=1.0.0 <1.4.0 which resolved to angular#1.3.15
>>    <application>, <internal package>#0.23.0 depends on **angular#^1.3.0 which resolved to angular#1.4.0**
>>    angular-animate#1.4.0, angular-mocks#1.4.0 depends on angular#1.4.0 which resolved to angular#1.4.0
>>    angular-bootstrap#0.11.2 depends on angular#>=1 which resolved to angular#1.4.0
>>    angular-ui-router#0.2.15 depends on angular#>= 1.0.8 which resolved to angular#1.4.0
>>Resort to using **angular#^1.3.0 which resolved to angular#1.3.15**
>>Code incompatibilities may occur.

**Comment by mthierba** [comment]
Hi, just wanted to add how I managed to resolved that same problem, in case it helps some folks.

My original `bower.json`:
```
...
  "dependencies": {
    "angular": "~1.3.15",
...
  },
  "resolutions": {
    "angular": "1.3.15"
  }
```
...failed with:
```
bower angular                         resolution Unsuitable resolution declared for angular: 1.3.15
bower                                  ECONFLICT Unable to find suitable version for angular
```
...and it's now working after I changed it to:
```
...
  "dependencies": {
    "angular": "~1.3.15",
...
  },
  "resolutions": {
    "angular": "~1.3.15"
  }
```
This did install `1.3.16`, by the way.

**Comment by Soranan** [comment]
thx   mthierba 

> ...
  "dependencies": {
    "angular": "~1.3.15",
...
  },
  "resolutions": {
    "angular": "~1.3.15"
  }

>

**Comment by lgaudez** [comment]
Any news about this issue ? It makes continuous deployment impossible... I am considering switching to NPM for client lib dependency management.

Here is my bower.json file 
```
{
  "dependencies": {
    "angular-messages": "~1.5.3",
    "angular-ui-grid": "~3.1.1",
    "codemirror": "4.8.0",
    "angular-ui-codemirror": "0.3.0",
    "ng-ckeditor": "~0.2.1",
    "ngInfiniteScroll": "1.3.0",
    "vis": "~4.9.0",
    "bootstrap": "~3.3.5",
    "fontawesome": "~4.6.0",
    "angular-i18n": "~1.5.3",
    "ng-tags-input": "~3.0.0"
  },
  "devDependencies": {
    "less": "1.7.3"
  },
  "resolutions": {
    "angular": "~1.5.3",
    "codemirror": "4.8.0"
  }
}
```

**Comment by kirillgroshkov** [comment]
+1 (but we indeed switched to npm almost everywhere for similar reasons)
