### ISSUE TITLE
Discussion: Is there a search back for compatible version ?

### ISSUE THREAD

**Issue by surdu** [bower/bower#1812]
Hello,

I have the following scenario:

I have `moduleA` which has `jQuery` version 1 as dependency and I want to install `moduleB` which depends on `jQuery` version 2. 

For now, when I try to install `moduleB` it will tell me that there is a compatibility issue in between `moduleB` and the fact that you have `jQuery` version 1 which is not compatible for the latest version of `moduleB`.

Then, bower gives me an option to basically break the compatibility for `moduleA` by using `jQuery` version 2 or break compatibility for `moduleB` by using `jQuery` version 1.

Why doesn't bower try to look in the history of `moduleB` and offer me a version of `moduleB` which was compatible with `jQuery` version 1 , assuming there was one?

How would bower help me in the this scenario without breaking the compatibility to neither of them? Can it ?

**Comment by sheerun** [comment]
The resolver in bower is not sophisticated enough to handle such case. Bower doesn't have have full-blown constraint solver: https://github.com/bower/bower/issues/578
