### ISSUE TITLE
Bower install tries to update all dependencies, even though they are already there

### ISSUE THREAD

**Issue by tehsenaus** [bower/bower#1816]
I'm trying to set up an automated build, behind a corporate proxy. I don't want this build to be dependent on access to the bower registry or Github (in case it goes down or is blocked by the corp proxy, as has happened in the past...).

I've checked in the external dependencies into source control, but I also have some **internal** bower dependencies too. I don't want these checked in, as I do linking.

So when I do `bower install --production` bower fetches the internal dependencies as it should, but it also tries to access the bower registry and Github, presumably to check for updates to the external packages which are already there. This isn't the behaviour I'd expect from `install`: isn't that what `update` is for?

Perhaps this could be fixed by adding a `--no-update` flag (?).

**Comment by enure** [comment]
One option would be to install https://github.com/Hacklone/private-bower on your corporate network. I think so long as the packages are cached by private bower it shouldn't need to access external resources.

**Comment by sheerun** [comment]
this is correct behavior
