### ISSUE TITLE
`bower info` can take a very long time

### ISSUE THREAD

**Issue by jamesward** [bower/bower#1820]
With a clean cache, some packages take a very long time to get info for.  Example:
```
$ time bower info material-design-icons
...
real    3m30.582s
user    2m4.824s
sys 1m16.864s
```

Just getting package info shouldn't be so slow.

Related to: https://github.com/jamesward/bower-as-a-service/issues/1

**Comment by jamesxv7** [comment]
Hello @jamesward, any updated related to this issue?

**Comment by jamesward** [comment]
I'm not quite sure the best way to handle this... Ideally Bower would resolve this but it seems that Bower is being End-of-Life'd.  Is this package also distributed by NPM?  If so, that seems like a better option.

**Comment by sheerun** [comment]
`bower info` uses `bower.json` from downloaded archive to show info

Their release on this version has 30MB to download. It's not Bower's issue. That's how long it takes to download this archive.

**Comment by jamesward** [comment]
Downloading 30MB doesn't take very long.  There is some other mysterious stuff taking a bunch of time.  The `download` step below actually happens really fast.
```
~ $ rm .cache/bower/
~ $ time bower info material-design-icons
bower not-cached    git://github.com/google/material-design-icons.git#*
bower resolve       git://github.com/google/material-design-icons.git#*
bower download      https://github.com/google/material-design-icons/archive/v2.1.3.tar.gz
bower progress      material-design-icons#* received 30.3MB of 30.4MB downloaded, 100%
bower extract       material-design-icons#* archive.tar.gz
*** long delay ***
bower invalid-meta  material-design-icons is missing "main" entry in bower.json
bower invalid-meta  material-design-icons is missing "ignore" entry in bower.json
*** another really long delay ***
bower resolved      git://github.com/google/material-design-icons.git#2.1.3
*** info omitted ***
real	4m11.750s
user	2m46.434s
sys	1m33.471s
```

But ideally Bower shouldn't have to download any archives to get package info.  This metadata should be in the package metadata repo like it is with NPM.
