### ISSUE TITLE
Request for new option -m --mainonly

### ISSUE THREAD

**Issue by olton** [bower/bower#1821]
Is it possible to implement an additional option which bower install only files specified in main

example: 
bower install package_name -m
bower install package_name --mainonly

**Comment by cvrebert** [comment]
I question the utility of this, considering that `main` doesn't encompass all of a package's useful/necessary files; it specifically excludes fonts, images, and precompiled-for-convenience CSS. See also https://github.com/bower/bower.json-spec/pull/43 .
Let's not encourage the incorrect meme that "only `main` Bower files matter".

**Comment by sheerun** [comment]
Bower is deprecated now, and in maintenance mode. Because of this we won't implement new features like this one. We recommend switching to Yarn or npm, and migrating with [bower-away](https://github.com/sheerun/bower-away)
