### ISSUE TITLE
Specifying branches

### ISSUE THREAD

**Issue by peduxe** [bower/bower#1822]
I would like to know if it is possible to have different branches for the same dependency without overwritting either.

Something like the follow (bower.json):

```json
{
    "polymer": "Polymer/polymer#^1.0.0",
    "polymer-master": "Polymer/polymer#master"
}
```

**Comment by jisaacks** [comment]
I don't think bower will care, but depending on the package, the package itself might override the other.

For example, if you are planning on using globals as a means of importing projects, there can only be one. Using AMD/UMD may work though.
