### ISSUE TITLE
.bowerrc cwd containing `~` creates `~` directory

### ISSUE THREAD

**Issue by ordonezalex** [bower/bower#1825]
According to the [Bower Configuration](http://bower.io/docs/config/#cwd) section for cwd, one should be able to include something like `"cwd": "~/my-project"`.

However, I have put my `.bowerrc` in my project root, then added `"cwd": "~/repos/js/project-name/assets/"`.

I do not think the `directory` configuration is relevant, but in case it is, I have not set it, expecting a default `bower_components/` directory to be placed in `~/repos/js/project-name/assets/`.

Next, I run `bower install --save-dev normalize.css`. My file browser then shows that `~/` has been added to the project root.

Unexpectedly, `~/` contains `repos/js/project-name/assets/bower_components/normalize.css/`.

I assume this is unexpected behavior, because of the example in the documentation mentioned above, but please correct me if I am using the configuration incorrectly.

Although the steps above result in unexpected behavior, using an absolute path for the `cwd` configuration results in expected behavior.

Other facts about my environment:

* I am using Zsh 5.0.2.
* I am using Ubuntu 14.04 LTS
* I am using Bower 1.4.1

**Comment by howardroark** [comment]
This issue is also very closely related to this one... https://github.com/bower/bower/issues/1784

**Comment by sheerun** [comment]
For better or worse bower now supports ~ expansion anywhere in config.
