### ISSUE TITLE
Difficulty installing bower

### ISSUE THREAD

**Issue by kalbers** [bower/bower#1826]
OS: LinuxMint 17

Running npm install -g bower results in the following:

npm http GET http://registry.npmjs.org/bower
npm http 404 http://registry.npmjs.org/bower
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token <
npm ERR! <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
npm ERR! <html><head>
npm ERR! <title>404 Not Found</title>
npm ERR! </head><body>
npm ERR! <h1>Not Found</h1>
npm ERR! <p>The requested URL /bower was not found on this server.</p>
npm ERR! <hr>
npm ERR! <address>Apache/2.4.7 (Ubuntu) Server at registry.npmjs.org Port 80</address>
npm ERR! </body></html>
npm ERR! 
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:238:23)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-35-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "bower"
npm ERR! cwd /var/www/html/mirador
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type unexpected_token
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/html/mirador/npm-debug.log
npm ERR! not ok code 0

**Comment by maxehnert** [comment]
I'm unsure if this will solve the problem, but you could try updating your node and npm packages first as they are out of date. Then try installing bower again.

**Comment by sheerun** [comment]
It's not bower's issue, but npm's.
