### ISSUE TITLE
Existing packages' names (i.e. d3) no longer valid due to stricter validation rules in bower-json 0.5.0

### ISSUE THREAD

**Issue by brian-gates** [bower/bower#1829]
D3 can no longer be installed as of bower-json 0.5.0:

> The name has to end with a lower case character from a to z

Other packages are invalidated by this rule as well:

> The name contains upper case letters

https://github.com/bower/json/blob/3cc1cd61c86d65c11fae42c05e2a4ce61310cbce/lib/json.js#L86-L114

This seems pretty huge.  Installs that worked last month no longer do, with no change on my end.

**Comment by collin** [comment]
Adding that these rules snuck into bower 1.4. We have two systems with the same version of bower. One was installed after bower-json was updated, the other before. The older system has bower-json 0.4 and installations work.

The newer system got bower-json at 0.5 and installations fail.

**Comment by collin** [comment]
To be clear: both systems report the same bower version. Both systems exhibit different behavior. 

There is no such thing as bower@1.4 the version is a lie.

**Comment by collin** [comment]
https://github.com/bower/bower/commit/06f4d0c117835c8af9c05d644598b4528a4e14dc

There's the offending commit. ^ should definitely not be used.

**Comment by eddiemonge** [comment]
`^` means use non-breaking compatible versions. They may include new features but they shouldn't break your existing things.

**Comment by collin** [comment]
In theory yes, but in practice nested dependencies break on minor and patch upgrades, even on libraries maintained by the bower org.

**Comment by brian-gates** [comment]
Yeah, this definitely breaks the rules of semver.

**Comment by sheerun** [comment]
I made the validation less strict, now it should be only a warning.
