### ISSUE TITLE
Ability to download from proprietary git repos with authentication

### ISSUE THREAD

**Issue by rossigee** [bower/bower#1831]
Attempts to install from authenticated git repos return a 401 response, which bower doesn't currently handle.

This is a feature request to add support for authenticated repos. I would like our devs to have a '.bowerrc' something like...

```
{
  "directory": "app/bower_components",
  "registry": "https://www.company.com/bower/"
}
```

Our in-house bower repo then exposes the 'https://www.company.com/git/repo' URLs for our various proprietary JS components to our dev's bower clients.

IMHO, ideally, the bower client needs to do as the git client does and utilise the '.netrc' file to obtain auth creds in the case of a 401. This would save devs from having to duplicate their creds in multiple places.

**Comment by sheerun** [comment]
As bower uses git directly, you can use any available auth mechanism: https://git-scm.com/docs/gitcredentials
