### ISSUE TITLE
Is it possible to pass the --no-color flag when running bower install programmatically?

### ISSUE THREAD

**Issue by DandyDev** [bower/bower#1832]
I'm using [grunt-bower-task](https://github.com/yatskevich/grunt-bower-task) inside an [SBT](http://www.scala-sbt.org/) project, and the output of Bower looks really ugly when it is run as a build on a CI system (Teamcity in my case). I'd like to pass an option to Bower programatically, to not use colors. Is this possible?

**Comment by jisaacks** [comment]
Yep, bower has a `--no-color` flag.

**Comment by jisaacks** [comment]
You can also set this in the `bowerrc` file. See: http://bower.io/docs/config/#color

**Comment by DandyDev** [comment]
> when running bower install programmatically?

I'm not talking about running bower on the command line, but calling `bower.install` from grunt for instance.

**Comment by jisaacks** [comment]
Are you using something like [grunt-bower-task](https://github.com/yatskevich/grunt-bower-task)? If so, have you looked at [options.bowerOptions](https://github.com/yatskevich/grunt-bower-task#optionsboweroptions)

**Comment by DandyDev** [comment]
I'm using exactly that, and I'm asking because it is unclear what the exact name of the option would be, that I would pass.

**Comment by jisaacks** [comment]
Pretty sure the option name would be `color`. Not sure if it would work using the `bower.commands.install` though. It maybe be as simple as adding it [here](https://github.com/bower/bower/blob/master/lib/commands/install.js#L34-L40) but I am not positive.

**Comment by jisaacks** [comment]
@DandyDev after looking into this a bit. It appears that grunt-bower-task, it grabbing the output from bower's log and adding the color: https://github.com/yatskevich/grunt-bower-task/blob/cbd14a0289d73ed029542b4a0b71b359089ec5f4/tasks/bower_task.js#L49

**Comment by DandyDev** [comment]
I see, that is nasty. I'll create a PR for `grunt-bower-task` then, to make it optional.

Thanks for looking into it!
