### ISSUE TITLE
Address npm dependency issues found in master branch [Opened by bitHound]

### ISSUE THREAD

**Issue by gtanner** [bower/bower#1837]
<p>bitHound discovered:</p> <ul> <li>2 packages with at least one security vulnerability, including: <ul> <li><a href="https://nodesecurity.io/advisories/semver_redos">semver Regular Expression Denial of Service</a></li> </ul> </li> <li>19 outdated packages</li> </ul> 
***
We use bower for some of our analysis in bitHound,  I would love it if you updated semver to get rid of the DoS vulnerability warning.

I am also willing to fix this and open a PR if you wish.

**Comment by gtanner** [comment]
See https://www.bithound.io/github/bower/bower/master/dependencies/npm for a reference

**Comment by sheerun** [comment]
I've already accepted a PR that updates semver version. It will be released in bower 1.5.
