### ISSUE TITLE
bower install specific version defined in bower.json

### ISSUE THREAD

**Issue by calidion** [bower/bower#1839]
bower install should install versions defined in bower.json

**Comment by sheerun** [comment]
Not enough details.

**Comment by calidion** [comment]
it seems bower alway fetch the latest version.
but sometimes fetches the new version will break the consistence of a project.
so a specific version is better for  dependency control.
npm is a good example.

**Comment by sheerun** [comment]
You can always put specific version in your dependencies.

**Comment by calidion** [comment]
so be it.

**Comment by iamhabbeboy** [comment]
I already had bower.json in my existing project where i got versions of packages to be installed, but bower  installed the latest version for me.
