### ISSUE TITLE
Bower install stuck on Mac OX 10.10.4

### ISSUE THREAD

**Issue by activatedgeek** [bower/bower#1843]
I am again starting to face the issue that `bower install` gets stuck. Is there a way to debug?

Here are the specs:
* `node` version: `v0.12.4`
* `npm` version: `2.10.1`
* `bower` version: `1.4.1`
* `OS`: `MAC OS X 10.10.4`

Here is the error that comes after a very long time:
```
ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/facebook/react-bower.git", exit code of #128 fatal: read error: Operation timed out
```
It seems to get stuck on the last dependency it is trying to install.

I tried `cache clean` and reinstalling but does not work.

**Comment by sheerun** [comment]
It seems like a temporary github issue. The command `git ls-remote --tags --heads git://github.com/facebook/react-bower.git` works perfectly well on my machine.

**Comment by z0r1k** [comment]
I just had the same issue but with another package.
