### ISSUE TITLE
need to upgrade to newer semver.js dependency (to pick up bug fixes)

### ISSUE THREAD

**Issue by MatthewMaher** [bower/bower#1845]
please see:
http://stackoverflow.com/questions/31144268/bower-no-suitable-angular-version/31274670#31274670

as well as issue #1817, reported a few weeks back, which I believe is the same problem.  

Bottom line is that the version of semver.js that bower uses (per it's package.json) is more than a year old and that semver code has a bug related to the handling of '.x' in the syntax. 

can bower please update to latest semver.js?

Thanks

**Comment by sheerun** [comment]
I've merged PR. It will be released in bower#1.5
