### ISSUE TITLE
No so an issue

### ISSUE THREAD

**Issue by SalathielGenese** [bower/bower#1848]
I'm so new to bower, but familiar with **maven** and **composer** and since these have nothing to do with **bower**, let me expose the facts.

I've been recomended **bower** by my teacher, by looking at his code, so find their [site](bower.io). After 2 week, *bower init* outputed that '/usr/bin/env node' does'nt exists. So run *sudo apt-get install node*, but no result (errors).

I even try *((sudo)? (npm|node|nodejs)? bower init)* ...

After 03 weeks (and learning nodejs and clearing cache and reinstalling all even my OS : Ubuntu 15.04), I discover [here](https://github.com/bower/bower/issues/475#issuecomment-31066364) that the problem is just **sudo ln -s /usr/bin/nodejs /usr/bin/node**

Please, provide a doc for true beginners, or add usefull links and comments.

**Comment by sheerun** [comment]
Thanks. I've include this info in the README. Feel free to also send PR to https://github.com/bower/bower.github.io explaining this.
