### ISSUE TITLE
.bowerrc file Placement & Order wrong in Windows

### ISSUE THREAD

**Issue by doggy8088** [bower/bower#1850]
Refer to http://bower.io/docs/config/ , here is the order of importance of .bowerrc file placement:

* CLI arguments via --config
* Environment variables
* Local .bowerrc located in the current working directory
* All .bowerrc files upwards the directory tree
* .bowerrc file located in user’s home folder (~)
* .bowerrc file located in the global folder (/)

I tried in Windows environment.  There are few things weird and suppose to be a bug.

Here are the steps required to reproduce the bug.

1. Create a **user** config file here: ```%USERPROFILE%\.bowerrc``` and it's content below:

    ```
    {
    	"directory": "user-bm"
    }
    ```

2. Create a **global** config file here: ```%LOCALAPPDATA%\bower\config\bowerrc``` and it's content below:

    ```
    {
    	"directory": "global-bm"
    }
    ```

3. Create a folder outside of user profile folder ( for my sample below is ```G:\Projects\bower-demo``` ) and create a **bower.json** file that it's content below:

    ```
    {
      "name": "bower-demo",
      "version": "0.0.0",
      "dependencies": {
        "fastclick": "~1.0.6"
      }
    }
    ```

4. Then execute ```bower install``` to install the package.  Then you'll see the "global-bm" been created.

    ![image](https://cloud.githubusercontent.com/assets/88981/8637473/10e2ccfc-28c5-11e5-8cc6-ed6735062858.png)

I think the **user** config file should be take the order of importance more than **global** config.  Am I right?

**Comment by sheerun** [comment]
On windows bower uses `%LOCALAPPDATA%\bower\config\bowerrc` as user's home. There's no support for `%USERPROFILE%` on Windows. It's more like documentation issue. Feel free to send a PR to https://github.com/bower/bower.github.io

**Comment by doggy8088** [comment]
@sheerun As I tested, bower do read from ```%USERPROFILE%\.bowerrc``` file.  I tested by [Process Monitor](https://technet.microsoft.com/zh-tw/sysinternals/bb896645).

**Comment by sheerun** [comment]
I think it's part of "All .bowerrc files upwards the directory tree" step.

**Comment by doggy8088** [comment]
@sheerun Not exactly.  Due to my project located under G:\Projects which is not upward related to the user home directory.
