### ISSUE TITLE
Current semver version (<=4.3.2) is too old and contains vulnerabilities

### ISSUE THREAD

**Issue by peterkc** [bower/bower#1851]
Current semver version 2.3.0 is vulnerable to a regular expression denial of service ([CVE-PENDING](https://nodesecurity.io/advisories/semver_redos))

Please upgrade to the latest version of semver > 4.3.2. Upgrading to the latest version of semver will resolve the following (#1817, #1845).

**Comment by trinityXmontoya** [comment]
:+1: +1

**Comment by sheerun** [comment]
I've already merged the PR. It will be released in 1.5

**Comment by chetanddesai** [comment]
@sheerun will the revert of this fix make it back in? specifically the upgrade of semver as outlined in this issue?

**Comment by sheerun** [comment]
I think yes, under a `--beta` flag
