### ISSUE TITLE
Bower repeating error *$$qProvider <- $$q <- $animate <- $compile <- $modalStack*

### ISSUE THREAD

**Issue by waleedarshad** [bower/bower#1853]
Hi @sheerun,
I am having issue regarding bower but not sure it is exactly the problem with bower or not.
I am a bit new to bower and angular. please redirect me to the right forum if it is not.

I am having error "Unknown provider: *$$qProvider <- $$q <- $animate <- $compile <- $modalStack*
i know angular has mention about it in his offical docs. but i am having the code as my colleage and he is running fine. I even go back to couple of comments back(80) but error is same.

Not sure if it is cache problem or something else

# In Browser console

*Uncaught Error: [$injector:unpr] Unknown provider: $$qProvider <- $$q <- $animate <- $compile <- $modalStack*
http://errors.angularjs.org/1.2.28/$injector/unpr?p0=%24%24qProvider%20%3C-%20%24%24q%20%3C-%20%24animate%20%3C-%20%24compile%20%3C-%20%24modalStack
angular.js:10126 Error: undefined role or invalid role validation
    at Object.Permission._findMatchingRole (angular-permission.js:143)
    at Object.Permission.rejectIfMatch (angular-permission.js:185)
    at Object.Permission.authorize (angular-permission.js:204)
    at angular-permission.js:40
    at Scope.$broadcast (angular.js:13093)
    at Object.transitionTo (angular-ui-router.js:3229)
    at Array.<anonymous> (angular-ui-router.js:2346)
    at Object.invoke (angular.js:3965)
    at handleIfMatch (angular-ui-router.js:1836)
    at angular-ui-router.js:1891

# Bower.json
{
  "name": "easyblog-frontend",
  "version": "0.1.0",
  "authors": [
    "Rodion <rodion@brocoders.com>"
  ],
  "description": "EasyBlog frontend",
  "main": "main.js",
  "license": "MIT",
  "private": true,
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "jquery": "~2.1.3",
    "lodash": "~2.4.1",
    "angular": "~1.3.15",
    "angular-ui-utils": "~0.2.2",
    "angular-ui-router": "~0.2.13",
    "restangular": "~1.4.0",
    "angular-bootstrap": "~0.12.1",
    "bootstrap": "~3.3.4",
    "satellizer": "~0.9.4",
    "angular-permission": "~0.2.0",
    "malihu-custom-scrollbar-plugin": "~3.0.8",
    "angular-loading-bar": "~0.7.1",
    "angular-animate": "~1.3.15",
    "angular-file-upload": "~1.1.5",
    "ngImgCrop": "~0.3.2",
    "animate.css": "~3.2.6",
    "ngInfiniteScroll": "~1.2.0",
    "angular-off-click": "~0.0.7",
    "angular-elastic": "~2.4.2",
    "angular-moment": "~0.10.0",
    "angular-pnotify": "~0.0.6",
    "angular-xeditable": "~0.1.9",
    "angular-sanitize": "~1.3.15",
    "angular-google-maps": "~2.1.0",
    "angular-social": "~1.0.0",
    "oauth-js": "~0.4.3",
    "angular-ui-map": "~0.5.0",
    "angular-image-spinner": "*"
  },
  "devDependencies": {
    "bourbon": "~4.2.2"
  },
  "overrides": {
    "ngImgCrop": {
      "main": [
        "compile/unminified/ng-img-crop.js",
        "compile/minified/ng-img-crop.css"
      ]
    },
    "bourbon": {
      "main": ""
    }
  },
  "resolutions": {
    "angular": "^1.2.9"
  }
}
and It always prompt there look at screen shot.
i even try every choice but result is same.
![screenshot from 2015-07-15 15 13 49](https://cloud.githubusercontent.com/assets/5329697/8696247/390d7b64-2b04-11e5-8e5b-5eb9a8aaeb95.png)

**Comment by sheerun** [comment]
I'm sorry, I can't help you. It seems like issue with angular. You probably forgot to include some angular lib in your HTML. Maybe you include wrong version of some package.

**Comment by waleedarshad** [comment]
ok. thanks.
