### ISSUE TITLE
Register with orgname/reponame

### ISSUE THREAD

**Issue by mohsen1** [bower/bower#1857]
It would be nice if Bower would use GitHub orgname/reponame for registering if user provides them as such.

Foe example:

```
bower register yaml-worker mohsen1/yaml-worker
```

**Comment by sheerun** [comment]
Yes it would be nice, could you send PR with tests?

**Comment by oskarcieslik** [comment]
I noticed that there's already PR submitted after I created my, sorry... But I see that it's been stale for 7 months now, so maybe it's not a problem ;p

**Comment by sheerun** [comment]
@oskarcieslik Your is better as it doesn't use exec and has a test

**Comment by sheerun** [comment]
It will be released in bower 1.8
