### ISSUE TITLE
BOM Project

### ISSUE THREAD

**Issue by fernandomoraes** [bower/bower#1862]
Hello, I have a scenario in the distribuition of front-end components, like this:

We produce various components, each with its particular version and dependency between them. For example:

projectA version 1.0.0
projectB version 1.4.0
projectC version 1.8.9
...

And projectA depending on projectB in particular version and projectB depending on another project, and so many projects...

What happened was that I had to get my single project, it was a major project components, and break into several small projects, allowing those who were to use, could choose only the few components you need and not all.

My question is, do not have as well as exist in Maven, I create a project that would be just to list the dependencies and their versions, something like this:

Grouper project
- List all dependencies and versions.

On the client
- I somehow 'would extend' this wrapper project, and I declared only the dependencies that I need, but without putting version, as this would be solved by the grouper. For those who know the Maven out, what I needed was to be alble to do the same thing occurs with BOMs.

Any ideia how to solve this?

Thanks.

**Comment by sheerun** [comment]
Currently it's not possible, unfortunately. But watch for custom resolvers in the next release.
