### ISSUE TITLE
Bower install pull child modules dependencies

### ISSUE THREAD

**Issue by Sandeep546** [bower/bower#1867]
Hi,
    I have  requirement to pull all the dependent modules and the interdependent modules to same level.
This is the project structure.
package
     /bower.json
        dependencies:['module1','module2'];
module1
   /bower.json
       dependencies:['module3']

So the issue is when I try to do bower install on package level I am able to get module1 and module2 but not module3 which is a dependent module for module1.
Does any one have a approach.
Thanks 
- Sunny.

**Comment by sheerun** [comment]
It's not enough information. Please post in new issue github repository that reproduces this.
