### ISSUE TITLE
Bower packages install fails

### ISSUE THREAD

**Issue by peio72** [bower/bower#1868]
Trying to install packages with bower on Windows 7 gives me following error:

 EEXIST, file already exists 'C:\Users\*******\AppData\Local\bower'

Please help.

**Comment by fewspider** [comment]
can you post your node version and npm version and full log?

**Comment by jamesxv7** [comment]
This issue seems to be related to **npm**. Try deleting the node_modules, clear the cache and install again. If this does not work feel free to re-open the issue.
