### ISSUE TITLE
Allow to add a namespace for a dependency

### ISSUE THREAD

**Issue by apretto** [bower/bower#1870]
I would like to be able to add a namespace for dependencies added with bower.
Example:
```json
  "dependencies": {
    "widgets/component-x": "git+ssh://git@bla.com/widgets/component-x.git#0.0.1",
    "widgets/component-y": "git+ssh://git@bla.com/widgets/component-y.git#0.0.1",
    "services/service-a": "git+ssh://git@bla.com/services/service-a.git#0.0.1",
    "utils/service-a": "git+ssh://git@bla.com/utils/service-a.git#0.0.1",
  }
```
Or some other format on how to define a namespace for a Bower dependency.

Which would generate the following file structure:
```
.
└── bower_components
    ├── services
    │   └── service-a
    ├── utils
    │   └── service-a
    └── widgets
        ├── component-x
        └── component-y
```

The reason this option would be beneficial for our team is that we're currently re-factoring our codebase, extracting some components to their own repos to be shared with other teams in the company, and:
- we want to avoid name collision (for example we have `services/service-a` and `utils/service-a` which are 2 different components, one is a service and the other is utilities related to that service);
-  and to maintain the `require` structure, so that a file that requires these extracted components will look like:
```coffeescript
ComponentX = require 'widget/component-x'
ServiceA = require 'services/service-a'
UtilsA = require 'utils/service-a'
```

**Comment by sheerun** [comment]
It's a frequent feature request, but we can't implement it. Flat tree in bower_components is integral to how bower internals work. Maybe you can use bower-installer npm package to do so.
