### ISSUE TITLE
version/resolution ignored

### ISSUE THREAD

**Issue by blowback** [bower/bower#1873]
Using bower 1.4.1, node 0.12.7, npm 2.11.3, I've got this bower.json:

```
{
 ...
  "dependencies": {

    "angular": "1.4.3",
    "angular-animate": "1.4.3",
    ...
  },
  "devDependencies": {
   ...
  },
  "resolutions": {
    "angular": "1.4.3",
    "angular-animate": "1.4.3",
    ...
  }
}
```

on my local machine, I get:

```
├── angular#1.4.3 (latest is 1.4.4-build.4147+sha.bb281f8)
├─┬ angular-animate#1.4.3 (latest is 1.4.4-build.4147+sha.bb281f8)
```

but on my build server I get:

```
├── angular#1.4.3 (latest is 1.4.4-build.4147+sha.bb281f8)                                                                               
├─┬ angular-animate#1.3.17 incompatible with 1.4.3 (1.4.3 available, latest is 1.4.4 build.4147+sha.bb281f8)                            
```

the only difference is that the build server had angular-animate-1.3.7 in it's bower_components, and my dev machine did not.

bower seems to have favoured the incumbent 1.3.7 package, despite me specifying that I wanted 1.4.3, both in the dependency and in the resolution section.

**Comment by sheerun** [comment]
Why on local machine `angular-animate` is sub-dependency, and on server is co-dependency?

**Comment by blowback** [comment]
sorry, cut and paste error from side-by-side tmux. edited.

**Comment by sheerun** [comment]
Did you try to remove bower_component and install again on development?

**Comment by blowback** [comment]
yes, angular-animate-1.4.3 is chosen.

**Comment by sheerun** [comment]
Maybe bower version doesn't match? I don't know what's going on.

**Comment by blowback** [comment]
same bower, same node, same npm. most odd.

**Comment by faceleg** [comment]
@blowback is this still an issue?
