### ISSUE TITLE
Multiple levels of bower.json

### ISSUE THREAD

**Issue by danielbsig** [bower/bower#1875]
Hi,

I've got two web projects which have some shared code, and that code is currently stored in a git submodule. What I would like is to be able to specify a bower.json file in that submodule, and then reference that bower.json file in each bower.json file for the two main projects. Is this possible with the current version of bower?

Regards,
Daníel

**Comment by sheerun** [comment]
No :( You can write Pluggable Resolver for that but it probably won't be easy.
