### ISSUE TITLE
ca configuration being ignored by Bower?

### ISSUE THREAD

**Issue by astrostl** [bower/bower#1877]
Ubuntu 14.04, trying to get `bower` to work with a transparent corporate proxy that replaces SSL keys (read: performs a man-in-the-middle attack for decryption). Using `curl`, for example, I can pass it the `--cacert` directive with a pemfile bundle, which turns failure into success.

http://bower.io/docs/config/#ca reports a `ca` configuration directive, which I was unable to get to work using that same file. `grep`ping the Bower source, I couldn't find a reference to it. `strace`ing `bower` itself when it runs, it looks like it doesn't stat any files referenced by the `ca` directive. Ditto `npm`'s own `cafile` as per https://docs.npmjs.com/misc/config#cafile

Is there some way I can get `bower` to use my SSL bundle? Same situation would be true if I were hitting a self-signed endpoint, shouldn't be specific to a decrypting proxy situation. Thanks!

**Comment by sheerun** [comment]
This should be fixed in next bower version via https://github.com/bower/bower/commit/9cc3dd4c9218656be6585206702f0e94d184c555
