### ISSUE TITLE
bower has incorrect exit code when there's a conflict without a tty

### ISSUE THREAD

**Issue by struys** [bower/bower#1880]
```
$ bower install --config.interactive=true < /dev/null
<snip>
Unable to find a suitable version for X, please choose one:
<snip>
? Answer:

$ echo $?
0
```

**Comment by struys** [comment]
This scenario happens when we run bower during our CI. We'd like to leave interactive mode on; the error message is better, we just want the exit code corrected.

**Comment by sheerun** [comment]
Bower is not deprecated, please use yarn. You can migrate with bower-away
