### ISSUE TITLE
Specify the git branch for bower registry

### ISSUE THREAD

**Issue by AbhiPanda** [bower/bower#1881]
I want to specify a branch name while doing bower register instead of bower defaulting the git branch to master.

bower register mypackage git@gitlab.example.com:mypackage.git#branch
but the above command doesn't work.

Thanks

http://stackoverflow.com/questions/32003508/specify-the-git-branch-for-bower-registry

**Comment by sheerun** [comment]
Bower doesn't allow specifying branches to use. Bower uses git tags for version resolution.

**Comment by AbhiPanda** [comment]
I have one follow up question. How do i create different packages from with a git repo. I was thinking of creating branches in the same repo and use each of them to point to different package. Is it possible ?
