### ISSUE TITLE
npm not ok when trying to install bower

### ISSUE THREAD

**Issue by chfakht** [bower/bower#1882]
Hi, after running "npm install -g bower" 
 i get 

npm http GET https://registry.npmjs.org/bower

npm ERR! Error: failed to fetch from registry: bower
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.g (events.js:156:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1256:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/pi/d3-tip/bower/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.18.14-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "bower"
npm ERR! cwd /home/pi/d3-tip/bower
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: bower
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/d3-tip/bower/npm-debug.log
npm not ok

any hints ?

**Comment by sheerun** [comment]
It looks like npm issue, not bower's

**Comment by chfakht** [comment]
ok is there another command to install bower without using npm ?

**Comment by azat-io** [comment]
@chfakht Try "sudo npm install -g bower" if you are using Linux or OS X.

**Comment by chfakht** [comment]
seems like it works ..... , i'm using raspberry pi with raspbian .......... take some time ==> oh finally that worked perfectly thanks

**Comment by chfakht** [comment]
there is no permission denied ... why does this need root :warning:
