### ISSUE TITLE
Command to install or update 

### ISSUE THREAD

**Issue by arodiss** [bower/bower#1884]
I am sorry as far as this should be already asked 1000 times but I did not manage to find exact same question so asking my own instead

I want the following behavior from bower
- I always specify my dependencies as `major.minor.*` (e.g. `2.0.*`) to automatically get bugfixes but not minor updates which can break BC
- I want bower to always check if it is possible to update to newer version given it matches requirements
- If newer version is available, package should be updated [1]
- If newer version is not available, previous version should be retained [2]
- It should work for first installation as well, i.e. if no installed version available at all [3]

It turns out that if I use `bower install` - it does not update existing dependencies even if updates are available, so requirement [1] is not met
If I use `bower update` - it does nothing on first install at all, so requirement [3] is not met
To get this to work I can do `rm -rf vendors/` and then `bower install`, but this is really non-optimal solution because updates are fetched from internet even if I don't need them (which is 99% cases)
What should I do instead?

PS. I am using bower `1.4.1`

**Comment by sheerun** [comment]
Bower update has been broken and won't be fixed as bower is depreacted
