### ISSUE TITLE
Manipulation of name in bower.json when installing locally without specific package name

### ISSUE THREAD

**Issue by gronke** [bower/bower#1887]
A developer installs a 3rd-party libary from an URL without specifying a package name `custom_name=https://..`

```
bower install https://example.com/trudy/malicious.git
```
### Szenario

Bower takes the name specified in the 3rd-party repository as package name and file system directory. Traversing directories can be used to replace system files
#### trudy/malicious bower.json

``` javascript
{
  "name": "../pwned"
}
```

will put the contents of trudy/malicious to `./pwned` instead of `./bower_components/malicious`

**Comment by sheerun** [comment]
This has been already fixed. Bower validates package name and ends execution with `bower EINVALID      Failed to read` message.
