### ISSUE TITLE
dependency name directory content disclosure (ssl)

### ISSUE THREAD

**Issue by gronke** [bower/bower#1890]
An attacker is in control of the projects or a sub-dependencies `bower.json` and puts a malicious dependency names in the configuration file.

``` javascript
{
  "name": "malicious",
  "dependencies": {
    "ssl": "../../../../../../../../../../etc/ssl"
  }
}
```

so that contents of `/etc/ssl` are copied to `./bower_components/ssl/`

**Comment by sheerun** [comment]
I don't think this is security issue as Bower should not be executed as root user

**Comment by sheerun** [comment]
Because Bower by design allows to install packages from any directory on disk, and we cannot possible blacklist all sensitive directories, it's only reasonable to close this issue and recommend to not run Bower as a root
