### ISSUE TITLE
Programmatic install uses top-level bower.json instead

### ISSUE THREAD

**Issue by simonauner** [bower/bower#1894]
I have a project folder structure like this:

```
root/
    bower.json
    src/
        stuffs that depends on bower.json above
    test-runner/
        index.js
        package.json
```

In my `index.js` I run this:
```
var bower = require('bower');
var packages = ['angular', 'angular-animate']; // etc
bower.commands
            .install(packages, {}, { /* custom config */ })
            .on('end', function() {
                console.log('DONE!');
            });
```
where packages is an array of packages *different*  from those in `root/bower.json` (for the sake of the bug report let's say they're hard-coded).

As I updated bower to `1.5.1` the code in `index.json` has started using `root/bower.json` instead of the packages provided by the `packages` variable. Downgrading to 1.4.1 makes everything work as expected again. 

Expected result: that `bower.commands.install` uses the packages provided in the parameter, and only fallback to `bower.json` if no parameters are provided.

Possibly related to 7acafc26d6207e44794b02402cdf6b9f66c53f01 ?

**Comment by sheerun** [comment]
Yes, thank you. It's a bug. I'll either fix it or rollback very soon.

**Comment by sheerun** [comment]
In 1.5.2 I've reverted auto-running in directory containing bower.json, so it should be fine now..

**Comment by simonauner** [comment]
Thanks for the quick fix!
