### ISSUE TITLE
Dependency order

### ISSUE THREAD

**Issue by bobmulder** [bower/bower#1897]
Hey guys,

I am using Bower (of course...). And use dependencies like jQuery, Bootstrap and AngularJS. However, some plugins of Angular need to be loaded AFTER jQuery.
I've sorted my dependencies in my `bower.json`, and I am using wiredep (gulp) to add them to my `index.html`. However, when I am loading a dependency, or update Bower, the whole order (I created myself) of dependencies is gone, and Bower did it on alphabetical order. In that case I am getting errors on my `index.html` because jQuery is loaded too late...

How am I able to use my own order in my dependencies?

Greetz

Bob

**Comment by arodiss** [comment]
@bobmulder 
`bower` is for installing packages, not for managing load order
If you want to specify your vendors dependencies, I suggest you to take a look on `require.js`: http://requirejs.org/

**Comment by tschilla** [comment]
Seriously!? The decision to order the dependencies in alphabetical order breaks al lot of automated builds. If you want to order the dependencies do it right and take the dependencies own dependencies into account! Dependency management is not just dumping dependency names in alphabetical order. At least you could have given users a choice wether to use your auto-sorting or not.

**Comment by bobmulder** [comment]
:+1: for @tschilla. I think an option to enable auto-sort would be very helpfull.

**Comment by leocaseiro** [comment]
+1

An option to disable auto-sort would be very helpfull.
I also use jQuery and AngularJS and I use gulp task with [bower-main](https://www.npmjs.com/package/bower-main) to add automatically my dependencies, however, jQUery needs to load before AngularJS.

I've been using Bower for a long time. The Issue #1381 should be optional.

Suggestion:
.bowerrc
{ auto-sort: false }

**Comment by michgeek** [comment]
:+1:  for this option.
I've encountered the same problem. https://github.com/bower/bower/pull/1381

:-1:  @arodiss developers have been controlling dependencies order and using wiredep to inject their dependencies in the same order as they are declared since ages. Forcing devs to use new libs or maintain a second array to manage the order is a regression. IMO this alphabetical order trend is a useless candy-eye sparkles.

**Comment by lustdante** [comment]
+1

This alphabetical auto-sorting caused a glitch that could have jeopardized our business if left unaddressed and it took us hours to discover this. There is not even an option to disable this.

I believe it all started with this discussion. #1373

**Comment by jeongsd** [comment]
:+1: for @tschilla
:-1: @arodiss

**Comment by michgeek** [comment]
Fixed https://github.com/bower/bower/commit/9c52ec2751d689a2cddb34adb004df41ce7c8a92

**Comment by sheerun** [comment]
Auto-sorting is reverted in 1.5.3

**Comment by bobmulder** [comment]
:+1:

**Comment by davidrhoderick** [comment]
What is the status of this?  I am trying to use jQuery, which is a dependency for Paper, but it needs to appear before Angular so as not to cause conflicts.  Is there still no way to custom order dependencies?
