### ISSUE TITLE
Global /.bowerrc no longer used as documented, /etc/bowerrc works but not documented

### ISSUE THREAD

**Issue by drcraig** [bower/bower#1898]
The Bower docs at http://bower.io/docs/config/#placement--order say that a global .bowerrc file can be placed in the root of the filesystem at `/.bowerrc`, but as of release 1.5.0, bower appears to no longer use this file.

While investigating this, I also checked if `/etc/bowerrc` would work, and happily it does! Even worked for 1.4.1 as well as 1.5.x. It should be added to the documentation.

If the removal of support for `/.bowerrc` was intentional, I'm actually thrilled. That was non-standard and ugly place to put a config file. But the docs need to be updated and the changelog should be clear that this version breaks support for `/.bowerrc`.

**Comment by sheerun** [comment]
.bowerrc at root should be supported, but bower is now deprecated. Ff someone want this fixed 5 years later, please open another issue
