### ISSUE TITLE
retry Request to https://bower.herokuapp.com/ failed with ETIMEDOUT, retrying in 1.0s

### ISSUE THREAD

**Issue by stephanedemotte** [bower/bower#1900]
Hi, i have this weird status : 
```
retry Request to https://bower.herokuapp.com/packages/modernizr failed with ETIMEDOUT, retrying in 1.0s
```

Any news ?

**Comment by cgomezmendez** [comment]
@stephanedemotte Is only again now.

**Comment by setakhero** [comment]
+1

**Comment by sheerun** [comment]
It seems it failed because of too many requests to /packages endpoint.

I've implemented memcached caching for it, so the service should be more stable now.
