### ISSUE TITLE
Copy repository with hidden (.git) folders

### ISSUE THREAD

**Issue by arshtepe** [bower/bower#1903]
Hello, can you move this ignore list 
https://github.com/bower/bower/blob/v1.5.2/lib/commands/init.js#L280 to single config, which can set dynamically
If need, i can аdd this, if you agree to merge.

**Comment by sheerun** [comment]
You can create Pluggable Resolver that leaves all files intact. Just pass `{ removeIgnores: false }` in the result of `fetch` function.

**Comment by cyberua** [comment]
I cloned this repo https://github.com/sheerun/bower-arti-resolver and changed  { removeIgnores: false }.
Created package.json 
````json
{
  "name": "scripts",
  "version": "1.0.0",
  "description": "",
  "dependencies": {
     "bower": "latest",
     "bower-ignore-resolver": "git://git-..link.com"
   },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  }
}
````
created .bowerrc
````json
{
  "resolvers": [
	"bower-ignore-resolver"	
  ],
  "registry": {
    "register": "http://link.com",
    "publish": "http://link.com",
    "search": [
      "http://link.com",
      "https://bower.herokuapp.com"
    ]
  },
  "timeout": 300000
}
````
and i have error
````
bower MODULE_NOT_FOUND      Cannot find module 'bower-ignore-resolver'
````
but bower-ignore-resolver installes in node_modules/bower-ignore-resolver .

**Comment by cyberua** [comment]
Thanks, It is work with dot folders, but i need .git folder. 
How can i make this?

**Comment by sheerun** [comment]
I think if should work if you create custom git resolver. Artifactory resolver strips .git folder on their server side and downloads .tar.gz of release, instead of cloning git repository. That's why .git folder is not present there.

**Comment by cyberua** [comment]
@sheerun , which resolver need rewrite ?
FsResolver.js 
GitFsResolver.js	
GitRemoteResolver.js
GitResolver.js

**Comment by cyberua** [comment]
@sheerun which for resolver i need change?

**Comment by sheerun** [comment]
There's no resolver to change yet. Bower's internal resolvers have different API than external resolvers. You need to create new one or wait for someone to create one.

**Comment by arshtepe** [comment]
@sheerun, I am replaced from GitResolver.js , _cleanup method and work, but i don`t understand how i can this add how my resolver ? Can i add this resolver only for link http://xxx.com (for example) .

**Comment by sheerun** [comment]
Yes.  All the documentation is in the link I've sent before.

**Comment by arshtepe** [comment]
@sheerun I dont understand how it works.
```javascript
module.exports = function (bower) {
    function getFragments(source) {
        return {
            registryUrl: utils.getRegistryUrl(bower.config),
            repositoryName: utils.getRepositoryName(source)
        }
    };

    return {
        match: function (source) {
            return true;  // ---->>>>>>> If this true using this resolver ?
        },

        releases: function (source) {  // ---->>>>>>> what is function do?
            var fragments = getFragments(source);
            var requestUrl = fragments.registryUrl + '/refs/' + fragments.repositoryName;

            return request(requestUrl, bower.config).then(function (response) {
                return utils.extractReleases(response);
            });
        },

        fetch: function (endpoint, cached) {  // ---->>>>>>> what is it this function need for return ?
            // If cached package is semver, reuse it
            if (cached.version) return;

            var fragments = getFragments(endpoint.source);

            var downloadUrl = fragments.registryUrl + '/binaries/' + fragments.repositoryName + '.git/' + endpoint.target;

            var downloadPath = tmp.dirSync();

            return download(downloadUrl, downloadPath.name, this.config).then(function (archivePatch) {
                var extractPath = tmp.dirSync();

                return extract(archivePatch, extractPath.name).then(function () {
                    downloadPath.removeCallback();

                    return {
                        tempPath: extractPath.name,
                        removeIgnores: true
                    };
                });
            });
        }
    }
}
````

**Comment by sheerun** [comment]
Both of your quesions are answered on
http://bower.io/docs/pluggable-resolvers/

**Comment by arshtepe** [comment]
@sheerun  in documentation (http://bower.io/docs/pluggable-resolvers/#fetchendpoint-object-cached-object-object) it is written that endpoint.source is  the link to resource, but i have in endpoint.source the package name instead - "my-repo" ( not link ). I have  this problem if i use my local bower server and local git server  but if  use bower repo all works.
I have
````js
"search": [
      "http://ddd.com/bower",
      "https://bower.herokuapp.com"
    ]
````
and to fetch method receive first link, even if package does not exist in first repository.

**Comment by sheerun** [comment]
@arshtepe It's because you return true from `match` function when bower passes `my-repo`. You need to return false for `my-repo` and true for git link.

**Comment by arshtepe** [comment]
Hello, thanks for your help, all works fine, but only when I use "latest" version.
When using version 1.0.0 i get error ````bower error    undefined is not a function````.
Error from this https://github.com/bower/bower/blob/master/lib/core/resolvers/pluginResolverFactory.js#L114
result === "module name" and string does not have a filter method 
I use your resolver
````js
var Resolver = require ( "./resolvers/GitRemoteResolver" );
var Logger = require('bower-logger');

module.exports = function (bower) {
    return {

        locate: function (source) {
          return source;
        },
        match: function (source) {
            // return /git\:\/\//g.test( source.trim() );
            return true;
        },

        fetch: function (endpoint, cached) {
            if (cached.version) return;

             var resolver = new Resolver ( endpoint, bower.config, new Logger() );
             return resolver.resolve().then( function () {
               console.log( resolver );

               return {
                 tempPath: resolver.getTempDir(),
                 removeIgnores: false
               };
             } );
        }
    };
};
````
