### ISSUE TITLE
bower sometimes creates a sub-directory in the component directory

### ISSUE THREAD

**Issue by thinking-aloud** [bower/bower#1906]
Hi,
When running "bower install" in a clean environment (no bower cache) on some modules we get unwanted sub-directories, which leads to HTTP 404 (file not found) in the frontend.
instead of: 
`bower_components/angular/angular.js` we get
`bower_components/angular/angular-1.3.18/angular.js`
Deleting the `bower_components/angular/` dir and running bower install, creates the same wrong structure. Running `bower cache clean && bower install` fixes it. After like 20 tries the problem does not come back.
We have bower inside a docker image created by our Bamboo build service. Therefore we always have a clean bower cache and sometimes get this error.
Strangely the last two builds had the same affected packages:
`angular-file-upload-shim.js angular.js ui-bootstrap-tpls.js socket.js hashmap.js angular-file-upload.min.js`

Help on nailing this down would be appreciated.

Greetings Lennart

**Comment by nadja7787** [comment]
The problem is known. See in https://github.com/blittle/bower-installer/issues/75

**Comment by thinking-aloud** [comment]
I don't think that #75 is the same. I don't really care how the structure is, as long as it is always the same. It locks like the issue is non-deterministic, which of cause is pretty bad.

**Comment by Jan0707** [comment]
Facing the same problems here, especially with the following packages:

> bower_components/angular/bower-angular-1.4.3
> bower_components/angular-animate/bower-angular-animate-1.4.3
> bower_components/angular-bootstrap/bootstrap-bower-0.13.0
> bower_components/angular-bootstrap-colorpicker/angular-bootstrap-colorpicker-3.0.18
> bower_components/angular-dragdrop/angular-dragdrop-1.0.11
> bower_components/angular-loading-bar/angular-loading-bar-0.8.0
> bower_components/angular-locker/angular-locker-1.2.1
> bower_components/angular-redactor/angular-redactor-1.1.5
> bower_components/angular-resource/bower-angular-resource-1.4.3
> bower_components/angular-route/bower-angular-route-1.4.3
> bower_components/angular-sanitize/bower-angular-sanitize-1.4.3
> bower_components/angular-ui-ace/ui-ace-0.2.3
> bower_components/angular-ui-bootstrap-datet
> imepicker/angular-js-bootstrap-datetimepicker-0.12.0
> bower_components/angular-ui-calendar/ui-calendar-0.9.0-beta.1
> bower_components/angular-ui-date/ui-date-0.0.8
> bower_components/angular-ui-event/ui-event-1.0.0
> bower_components/angular-ui-indeterminate/ui-indeterminate-1.0.0
> bower_components/angular-ui-mask/ui-mask-1.2.0
> bower_components/angular-ui-scrollpoint/ui-scrollpoint-1.0.1
> bower_components/angular-ui-select/ui-select-0.12.1
> bower_components/angular-ui-sortable/ui-sortable-0.13.4
> bower_components/angular-ui-uploader/ui-uploader-1.0.0
> bower_components/angular-ui-validate/ui-validate-1.1.1
> bower_components/dropzone/dropzone-4.0.1
> bower_components/jquery-migrate/jquery-migrate-1.2.1
> bower_components/restangular/restangular-1.5.1

**Comment by sheerun** [comment]
Can you provide bower.json to reproduce this issue?

**Comment by dgsmith2** [comment]
Since updating to angular-bootstrap-0.14.3, we get the same failure on our Bamboo build.  Since then, `ui-bootstrap-tpls.js` and its siblings end up under `bower_components/angular-bootstrap/bootstrap-bower-0.14.3`.  Running the `bower cache clean` before the `bower install` "fixes" this issue.  We do not encounter this problem at all if we run the build on local developer machines or via a Jenkins build, all the files are where they are expected to be: `bower_components/angular-bootstrap`

**Comment by ristinolla** [comment]
We had the same problem with our build process, even in Jenkins. By manually deleting `bower_components` directory and adding `bower cache clean` before `bower install` to our build process works as a workaround.

**Comment by sheerun** [comment]
@dgsmith2 @ristinolla Are you using bower-installer?

**Comment by ristinolla** [comment]
@dgsmith2 no, just the reqular install. But I think I should use the bower-installer, sounds legit! We are using frontend-maven-plugin since we have a maven project, but I think that shouldn't have anything to do with this bug.

**Comment by sheerun** [comment]
Maybe other users on CI are using bower-install and bower-install overwrites bower's cache?

It seems likely because it happens for both of you only on CI.

**Comment by faceleg** [comment]
You could try specifying bower as an npm dependency and running ./node_modules/.bin/bower to ensure you're using a known bower instance

**Comment by sheerun** [comment]
I think `--force` flag bypasses cache reads.. Maybe that will help.

**Comment by dgsmith2** [comment]
@sheerun, no, we are not using bower-installer.  I'll take a look at --force

@faceleg, we already have bower defined as an npm dependency, which is used for the install task.  From our logs:
`running command line: \n/local/mis/nodejs/bin/node node_modules/bower/bin/bower cache clean\n ... in: /local/mis/bamboo/home/xml-data/build-dir/ORION-NG-JOB1/Web`

**Comment by sheerun** [comment]
This issue got stale. If it still bothers someone, please create another one
