### ISSUE TITLE
Installing Bower pulls in unlicensed code

### ISSUE THREAD

**Issue by mmucklo** [bower/bower#1907]
I have the unfortunate task of confirming licenses on software, so I hate to bring up this rather pedantic issue, however including decompress-zip includes binary which includes buffers which is presently unlicensed in all available versions on npmjs.com.

There is a license file in the repo on github, however there's no published version that has a license file, which results in unlicensed software being pulled in when one installs bower via npm.

I have an open issue with the maintainer of this repo, so hopefully they will just publish a new version, and be done with it - I would appreciate any thumbs-up on the issue so it may come possibly to their attention.  Barring that, if there's anything that can be done on the bower side, perhaps to resolve the dependency chain differently, I would appreciate that as well.

https://github.com/substack/node-buffers/issues/12

Thanks
Matt

**Comment by sheerun** [comment]
We'll wait for substack to release licensed version.
