### ISSUE TITLE
Add support for modular development

### ISSUE THREAD

**Issue by claudio-silva** [bower/bower#1909]
I know this has been asked before, but please reconsider this, as I believe it is something very important and needed.
I'm developing a modular framework and I need a way to merge bower.json files from every module/plugin into a single configuration.
I can't make modules handle their client dependencies on their own, because then each module might try to install a different version of JQuery, for instance.
Whenever a user installs a new module/plugin into a project, a `bower update` must be run to install that module's dependencies. That process must take into account every other module's dependencies.
That can only be done effectively if bower supports some way to load/include multiple bower.json files.
The current "one bower.json only" situation is not suitable at all for modular projects, unless you don't mind updating your bower.json by hand whenever you install a new module, which, IMHO, defeats the purpose of a package manager.

**Comment by sheerun** [comment]
It can be confusing if `bower install` produces different results for the same `bower.json`. I think there's nothing wrong with `bower install --save ./plugins/foobar`, and then being sure that `bower update` or `bower install` actually updates/installs all dependencies and plugins.

**Comment by juniorjpf** [comment]
If i understand, you want to install differentes dependencies for each modules that you have.

should help if we have something like that:

```
"dependencies": {
	"moduleOne": {
		"jquery": "*",
		"bootstrap": "<3.3.4",
		"modernizr": "~2.8.3"
	},
	"moduleTwo": {
		"jquery": "*",
		"angularjs": "1.4.1",
		"bootstrap": "<3.3.3",
		"modernizr": "~2.8.1"
	},
	"angularjs": "1.4.2"
}
```

**Running a global config:**
```
running bower install
```
result sould be: 
> "angularjs": "1.4.2" installed

**Running a moduleOne config:**
```
running bower install 'moduleOne'
```
result sould be: 
> "angularjs": "1.4.2" installed
> "jquery": "*" installed
> "bootstrap": "<3.3.4" installed
> "modernizr": "~2.8.3" installed

**Running a moduleOne config:**
```
running bower install 'moduleTwo'
```
result sould be: 
> "jquery": "*" installed
> "angularjs": "1.4.1" installed (from specific module and not from global config)
> "bootstrap": "<3.3.3" installed
> "modernizr": "~2.8.1" installed

I'm new here and if i say bullshit, please tell me.

**Comment by claudio-silva** [comment]
@juniorjpf Not really, what I want is to be able to easily develop applications comprised of multiple (independently installed) modules/plugins, where each one can bring its own dependencies. When doing a `bower install`, the union of all module's dependencies should be installed, and bower should take care of resolving the intersections (and possible conficts) so that only onle version of each library is installed by bower.

**Comment by claudio-silva** [comment]
@sheerun **Thank you** for the solution you provided! I didn't know we could require modules directly from the local filesystem. **It's not clear from the documentation that this feature is available or how it works.**

I would like to suggest the developers to, please, **highlight and explain this capability on the documentation**, so that more users can realize they can split monolithic applications into discrete modules!
