### ISSUE TITLE
Pluggable Resolver- only respect valid Semantic Versions

### ISSUE THREAD

**Issue by liorhson** [bower/bower#1910]
Some repositories on GitHub doesn't maintain valid Semantic versioning on their tags.  For example: [blockui](https://github.com/malsup/blockui)
When implementing the `releases(source: string): array` from the API, the result would be *empty* because no tags are valid.

Bower without the resolvers implementation knows how to handle this kind of issue.

**Comment by phenomnomnominal** [comment]
I'm seeing something related to this issue as I'm trying to implement a [mercurial resolver](https://github.com/phenomnomnominal/mercurial-bower-resolver/blob/master/lib/HgResolver.js).

As far as I can see, `target` is initalised to `"*"`, and then the versions are returned by the `releases` function on the resolver. This responds with some array, e.g. `[{ version: '*', target: 'whatever' }, { ... }]`. However, any versions that aren't valid semver (e.g. "*") are removed, so the version cannot be resolved... 

Am I missing something obvious here? @sheerun can you shed some light?

**Comment by sheerun** [comment]
The releases method is expected to return list of valid semver versions (not ranges, like `*` or `^1.2.3`), and matching targets. If there are no valid semver versions, return something like `[{ version: '0.0.0', target: 'whatever' }]`.

**Comment by phenomnomnominal** [comment]
Right, that makes sense. How would this work for people wanting to target named branches etc?

**Comment by sheerun** [comment]
Bower executes `releases` method only if user provides a range like `*` (default) or `^1.2.3`. If user provides non-semver target, like `master`, bower skips directly to `fetch` method.

**Comment by phenomnomnominal** [comment]
Of course! Thanks!

**Comment by sheerun** [comment]
I clarified releases method in documentation: https://github.com/bower/bower.github.io/commit/71b8c86eb4a2c506c38211ac0ddfb09a4cfcbe09

**Comment by fjmilens3** [comment]
@sheerun, it appears that the above clarification you made to the documentation is no longer part of the formal pluggable resolver API docs on the Bower site. Is returning a `0.0.0` version or similar still the recommended practice, or has there been a change in guidance?

**Comment by evanjbowling** [comment]
@fjmilens3 I can't account for the change in docs just yet, I'll look into that a bit later. I believe the spirit of the resolver is to support installing packages with semantic versions - the 0.0.0 release only seems to be listed as a default, but it might not be necessary. Are you working on a specific resolver that we can reference?

**Comment by evanjbowling** [comment]
@fjmilens3 I created an [example bower resolver](https://www.npmjs.com/package/example-bower-resolver) ([github link](https://github.com/evanjbowling/example-bower-resolver)). I realize that it's very simple, but the resolver works without implementing the `resolver.releases()`. I noticed that the [bower.io/pluggable-resolvers](http://bower.io/docs/pluggable-resolvers/) lists sample code with that method being optional. Does that answer your question?

**Comment by fjmilens3** [comment]
Thanks for the information! I think it helps, but I'm not sure how applicable the example resolver would be to our particular scenario. The issue we're encountering is that we _do_ want to support semantic versioning when available, but _also_ have a need for a default behavior that would allow us to return the contents of master when a project hasn't any made any formal releases/created any tags in their repo.

So far, it appears that returning an empty array indicating no releases results in Bower failing with an indication that no suitable versions are available. However, making up a version can produce incorrect version numbers being saved in the user's `bower.json` if the user is using the `--save` option (it will record something like `^0.0.0` which is quite different semantically from `*`, which is what we really want). If we could return `*` as a valid version to handle the special case, that might solve the problem, and we could translate that to something meaningful in our resolver's fetch, but `*` isn't a valid semver and won't survive the trip.

This is specifically in the context of our resolver for Nexus 3 at https://github.com/sonatype/bower-nexus3-resolver, but I would imagine this could surface in similar scenarios as well. In our particular case it's a matter of wanting to support semantic versioning as our product is a repository manager, but also wanting to be able to support edge cases for high-profile projects that don't do formal releases with semantically-versioned git tags (and just rely on the git resolver behavior of checking out master).
