### ISSUE TITLE
Bower is case sensitive but you can't have two packages with "same" name on Windows

### ISSUE THREAD

**Issue by fmasa** [bower/bower#1911]
There is issue when you want to use packages with "same" name (i.e. Sortable and sortable) which differs only in case.

Try:

    bower install Sortable
    bower install sortable

Now you have only **s**ortable installed.

Is there any workaround or fix?

**Comment by sheerun** [comment]
Yes:

```
bower install sortable1=Sortable
bower install sortable2=sortable
```
