### ISSUE TITLE
Local modules don't conflict with registered modules, hence ignored 

### ISSUE THREAD

**Issue by GuilhermeMedeiros** [bower/bower#1912]
My project has a `bower.json` which requires a registered collection of modules on our private registry. This collection define some other dependencies which I'm not able to touch.
Let's use `themes` as an example. So I have something like this:

```
{
    "name": "my-project",
    "version": "1.0.0",
    "dependencies": {
        "themes": "2.0.0"
    }
}
```

Themes on this case, is a collection of themes, something like: 
```
{
    "name": "themes",
    "version": "2.0.0",
    "dependencies": {
        "theme-1": "1.0.0",
        "theme-2": "1.0.0"
    }
}
```

But let's say, I want to replace the `theme-1`. That could be easily done by having a git repository because bower would ask for the resolution. However with filesystem that doesn't happen. 
Ideally I want something like this:

```
{
    "name": "my-project",
    "version": "1.0.0",
    "dependencies": {
        "themes": "2.0.0",
        "theme-1": "./path/to/my/local/theme-1"
    },

    "resolutions": {
        "theme-1": "fs"
    }
}
```

Is that possible with the current version?

**Comment by sheerun** [comment]
Hey! Natively it's not possible, but you can create desired functionality with Pluggable Resolver http://bower.io/docs/pluggable-resolvers/
