### ISSUE TITLE
resolver version error

### ISSUE THREAD

**Issue by arshtepe** [bower/bower#1913]
Hello, thanks for your help, all works fine, but only when I use "latest" version.
When using version 1.0.0 i get error ````bower error    undefined is not a function````.
Error from this https://github.com/bower/bower/blob/master/lib/core/resolvers/pluginResolverFactory.js#L114
result === "module name" and string does not have a filter method 
I use your resolver
````js
var Resolver = require ( "./resolvers/GitRemoteResolver" );
var Logger = require('bower-logger');

module.exports = function (bower) {
    return {

        locate: function (source) {
          return source;
        },
        match: function (source) {
            // return /git\:\/\//g.test( source.trim() );
            return true;
        },

        fetch: function (endpoint, cached) {
            if (cached.version) return;

             var resolver = new Resolver ( endpoint, bower.config, new Logger() );
             return resolver.resolve().then( function () {
               console.log( resolver );

               return {
                 tempPath: resolver.getTempDir(),
                 removeIgnores: false
               };
             } );
        }
    };
};
````

**Comment by sheerun** [comment]
Why result is "module name"? Could you share github repository for this respolver so I can debug?

**Comment by arshtepe** [comment]
@sheerun  https://github.com/arshtepe/bower-git-resolver

**Comment by sheerun** [comment]
Your "releases" method returns source instead of array of { version, target } objects.

Please read the documentation.

**Comment by arshtepe** [comment]
@sheerun if i remove this i having error ````bower error         Resolver does not accept version ranges (1.0.0)```

**Comment by sheerun** [comment]
Your resolver needs to implement `releases` function to support version ranges (1.0.0 is version range, that matches only one version). No way around it.

**Comment by arshtepe** [comment]
@sheerun  Thank you very much.
