### ISSUE TITLE
Private bower mirror without reaching out to github.com

### ISSUE THREAD

**Issue by rdeguzman22** [bower/bower#1916]
Is there a way to copy all the bower packages without reaching out to github.com? As it stands right now you need to contact github.com in order to install packages, but if you're on a private network, that is not connected to the internet, this does not work.

Or, is there a way to copy the entire bower mirror? Similar to how NPM does their fullfat registry?

I've read the website: http://toranbillups.com/blog/archive/2013/08/04/How-to-host-a-private-bower-registry/ but even doing this method would require downloading the git repo that you want and copying it locally then over to a private network. But if you don't know which packages you'll need this poses to be a time consuming and problematic issue.

**Comment by sheerun** [comment]
You can use 3rd party service like http://www.jfrog.com/artifactory/
