### ISSUE TITLE
my username keeps turning up in npm-debug.log

### ISSUE THREAD

**Issue by davidmaxwaterman** [bower/bower#1918]
I did a search on my github username and it seems like I contribute to a lot of projects that I have never contributed to, but it's really only because the CONTRIBUTORS.md file contents are added to npm-debug.log files, which people seem to commit for some reason (probably by mistake). For example :

<https://github.com/stephenwww/FoodExApp/blob/master/npm-debug.log>

Is there any way to not have this happen (other than removing me from the CONTRIBUTORS file - I want to stay in the file, obviously)?

**Comment by sheerun** [comment]
Hey,

We've cleaned up README in recent versions, and we show only link to contributors page, so it should not be be a problem or new versions of Bower. For old versions I'm afraid there's no way to prevent people from including result of npm-debug.log in repositories. You'd need to write script to automate it and send PRs with a request of removal of them.

**Comment by davidmaxwaterman** [comment]
ok, thanks.
