### ISSUE TITLE
Custom Resolvers need to be globally installed.

### ISSUE THREAD

**Issue by gaurav21r** [bower/bower#1919]
I was trying to make my own resolver. 

I found that only when I installed my **Custom Resolver globally using `npm -g`** did it work.

I'm on Windows. On trying to use local resolvers, I am getting:

`bower MODULE_NOT_FOUND      Cannot find module 'test-resolver'`

**Comment by sheerun** [comment]
You have few options:

1. Install both resolver and bower locally
2. Install bower locally and resolver globally
3. Install bower and resolver globally

The only option that doesn't work is installing bower globally and resolver locally. Maybe we could fix that. I'm not sure.

Things get more complicated when `npm link` is used :)

**Comment by gaurav21r** [comment]
@sheerun I understand that this investigation can take some time. Can we please include this in the documentation for **Custom Resolvers**

**Comment by sheerun** [comment]
Yes, but I need to confirm those cases before documenting them publicly :)

**Comment by andrey-p** [comment]
Please add documentation, I just got tripped up by this too.

**Comment by ptitgraig** [comment]
This issue can be close since it's documented now.
https://github.com/bower/bower.github.io/blob/master/docs/pluggable-resolvers.md

**Comment by BenMann** [comment]
Agree.. Closing.

**Comment by andrey-p** [comment]
Sorry, I'm not sure if the actual problem @gaurav21r and I had was documented.

[The usage section](https://github.com/bower/bower.github.io/blob/master/docs/pluggable-resolvers.md#using) that @ptitgraig linked to mentions that you can use resolvers globally or locally, but doesn't go into more detail. Specifically it doesn't mention that you have to install the resolver globally if bower is installed globally.

**Comment by BenMann** [comment]
Oh, I get it. I thought the first sentence is enough, stating to install globally, but I see where you're coming from. I'll keep it open, also because  
> Maybe we could fix that.

**Comment by andrey-p** [comment]
Thanks. Appreciate your work on this! :bow:

**Comment by ptitgraig** [comment]
Indeed, my mistake.

**Comment by wrumsby** [comment]
> Maybe we could fix that.

Is fixing that as simple as trying something like trying to require the resolver and if that fails resolve it relative to `cwd`?

(Having said that I can't immediately see the code that's loading these resolvers.)

**Comment by sheerun** [comment]
It's line 60 of resolverFactory.js (simple require call). I think your approach would fix it (require `${cwd}/node_modules/${resolverName}` and then fallback to normal require for global resolvers).
