### ISSUE TITLE
Bower installation error. How to solve it

### ISSUE THREAD

**Issue by Anandapriyan** [bower/bower#1924]
I am running ubuntu 14.04 64 bit operating system. when i try to install bower i get the following error how to solve this

ipriyan@iPriyan:~$ sudo npm install -g bower
npm ERR! Linux 3.19.0-28-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! file /home/ipriyan/.npm/node-uuid/1.4.3/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: /home/ipriyan/.npm/node-uuid/1.4.3/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ipriyan/npm-debug.log

Thanks

**Comment by sheerun** [comment]
It's an errof rom node-uuid installation, not bower.
