### ISSUE TITLE
--save-exact does not store github shorthands

### ISSUE THREAD

**Issue by unilynx** [bower/bower#1925]
`bower install --save --save-exact WebHare/designfiles`

creates this dependency:

```
  "dependencies": {
    "designfiles": "1.2037.0"
  }
```

It should be

```
  "dependencies": {
    "designfiles": "WebHare/designfiles#1.2037.0"
  }
```

Just using `bower install --save WebHare/designfiles` creates the right dependency

**Comment by sheerun** [comment]
Thanks for reporting this
