### ISSUE TITLE
Typing (d.ts) Definition Support Revisited

### ISSUE THREAD

**Issue by gravidThoughts** [bower/bower#1927]
#911

>    So, the problem is that we need a simpler method of installing dependencies on Typescript projects, including both the Javascript code, and the Typescript definition file. The ideal would be if packages could include a definition file, but that's obviously not going to happen.

Could someone please explain why this is "obviously not going to happen"?

Typescript has matured to a point where it can be used in virtually any development environment. Not to mention other transpilers like Babel and Traceur.

What serious node or front end developer would not begin a new project using the benefit of strongly typed javascript development? Angular 2 anyone?  The production of d.ts files will be automated for most new projects moving forward. This is about the future.

I just don't see why this feature should not be incorporated into bower. Perhaps support for the feature by existing packages would be slow in the start. But all of those people contributing to DefinitelyTyped could simply turn their efforts towards contributing directly to the package. 

Most importantly, they would be contributing within the context of the actual package management system itself. Long term, I do not see how it can be any other way. The typing of a package belongs tightly coupled to the package itself.

Bless all of the work done by the contributors to [tsd and DefinitelyTyped](https://github.com/DefinitelyTyped/tsd). At the end of the day, it cannot possibly be a serious long-term solution for managing type definitions.

**Comment by sheerun** [comment]
We could provide more advanced way to postprocess downloaded packages.

I've just created #1930 to track that.
