### ISSUE TITLE
how to change repository url?

### ISSUE THREAD

**Issue by veenedu** [bower/bower#1928]
To learn bower for local packages, i uploaded to package too bower.

Now  I want to change the repository url, how can i do that?

**Comment by sheerun** [comment]
You can put url directly in `bower.json` dependencies, like:

```
{
  "dependencies": {
    "jquery": "veenedu/jquery"
  }
}
```

**Comment by veenedu** [comment]
Hi,


  "repository": {
    "type": "git",
    "url": "git://github.com/praveenprasad0312/veen2.git"
  }  

---
I want to change the url part of "repository"
