### ISSUE TITLE
Is there any way to call bower.commands.install() using the same interface as bower install?

### ISSUE THREAD

**Issue by fernandofleury** [bower/bower#1936]
I've managed to mimic the same behavior of `bower install` using `bower.commands.install()` plus a few event handlers for `prompt` and `log`. But it took me some work to get it done (mostly for the conflicts resolution possibility). I was wondering if there was any way to call `bower.commands.install()` the same way bower install works, so I don't have to re-create what bower already have.

**Comment by sheerun** [comment]
Probably you can use something like `bower.commands.install.line(['angular', 'jquery', '--save'])`.

Feel free to send PR documenting it on bower.io.
