### ISSUE TITLE
bower fails behind company firewalls

### ISSUE THREAD

**Issue by SetTrend** [bower/bower#1940]
This issue may be similar to issue #1741:

I have installed the latest Git for Windows. Still I am not able to connect to GitHub:

```
C:\Users\me>git ls-remote --tags --heads git://github.com/jquery/jquery.git
fatal: unable to connect to github.com:
github.com[0: 192.30.252.128]: errno=No such file or directory
```

No proxy or anything in my way.

**Comment by sheerun** [comment]
That's how firewalls work :) Bower 1.6.2 respects HTTPS_PROXY and HTTP_PROXY for git repositories, so you might try this. You can also use [this trick](http://stackoverflow.com/questions/1722807/git-convert-git-urls-to-http-urls) to make git re-write git:// urls to https:// urls.
