### ISSUE TITLE
Bower init error 

### ISSUE THREAD

**Issue by milkymura** [bower/bower#1942]
![problem](https://cloud.githubusercontent.com/assets/11899020/10414236/2ea11cf2-6ffc-11e5-96f2-e79a9b7a493e.png)

my bower version is: 1.5.3

**Comment by ZaLiTHkA** [comment]
Note: this duplicates #1939.

Also, just a thought @milkymura, it's better to copy/paste the error in code blocks instead of screenshots. This way your error won't show up in any issue searches.

**Comment by milkymura** [comment]
nvm, I already solved it. I just re installed my git bash then I did not use the new feature of git bash. (mintty)

**Comment by sheerun** [comment]
I can confirm. It happens at least in "git bash" terminal on Windows 7.

**Comment by zanjs** [comment]
+1

**Comment by fatphil2001** [comment]
Using the suggested workaround of --config.interactive results in a differnt error:

bower error         Cannot read property 'substring' of undefined

See attachment for full stack trace:
[bower-init-error.txt](https://github.com/bower/bower/files/36896/bower-init-error.txt)

**Comment by ciglesiasweb** [comment]
I have the same problem!!!

**Comment by cockroachzl** [comment]
+1

**Comment by ethanclevenger91** [comment]
Also was able to solve by not using the mintty install of Git Bash (Windows). Not ideal

**Comment by ahmadmilzam** [comment]
+1, use git bash with windows default console to solve this.

**Comment by ragmon** [comment]
+1

**Comment by huangjihua** [comment]
I have the same problem on window8.1

**Comment by huangjihua** [comment]
+1, use git bash with windows default console to solve this.

**Comment by cataquil** [comment]
Got the same issue.  Would be better not to have to switch terminals.  On Windows its crazy to get all this stuff to work you got CMD, MingW64, Powershell and whatever else.

**Comment by cataquil** [comment]
cmd.exe /C "C:\Program Files\Git\bin\bash.exe" --login -i

**Comment by kajnet** [comment]
Had the same problem using Bash.
Tried it with PowerShell and the error was gone.

**Comment by NikhilDoWhile** [comment]
Had the same problem while using GIT, then used cmd !! Problem Solved .

**Comment by iedsilva** [comment]
Only win GIT bash. In windows prompt works.

**Comment by rafagaseo** [comment]
I use the Node Bash and worked.

**Comment by Flame2957** [comment]
+1

**Comment by mazer-rakham** [comment]
Worked in regular CMD for me.

**Comment by richiksc** [comment]
Do you know why this is an issue?

**Comment by Nur-jaman** [comment]
hey guys this happening if you run bower init from **git bash in window**. use nodejs command prompt instead.

**Comment by chiholiu** [comment]
In my case the solution was to run "bower install" in windows command

**Comment by sheerun** [comment]
Bower is deprecated and creating new packages is not recommended anymore
