### ISSUE TITLE
Bower version 1.5.3 still reports update available after updating

### ISSUE THREAD

**Issue by bobintornado** [bower/bower#1943]
As title.

**Comment by sheerun** [comment]
Maybe 1.6.2 works for you? I can't reproduce.

**Comment by eppineda** [comment]
it just happened to me. I did 1.7.0 last night and it's prompting me to "update" to 1.6.5. It's also incorrectly reporting my local version as 1.6.3.

![tt-api_ _bash_ _104x29](https://cloud.githubusercontent.com/assets/6559491/11642979/18c4dcee-9d0f-11e5-9571-cd605c749034.png)

**Comment by sheerun** [comment]
@eppineda Maybe it is this issue: https://github.com/greenkeeperio/greenkeeper/issues/33#issuecomment-144468858

**Comment by eppineda** [comment]
It certainly looks similar.

On Tue, Dec 8, 2015, 04:59 Adam Stankiewicz <notifications@github.com>
wrote:

> @eppineda <https://github.com/eppineda> Maybe it is this issue: greenkeeperio/greenkeeper#33
> (comment)
> <https://github.com/greenkeeperio/greenkeeper/issues/33#issuecomment-144468858>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bower/bower/issues/1943#issuecomment-162836868>.
>
-- 
epp
