### ISSUE TITLE
bower pulling zip file from the cache even though it has found file to be stale

### ISSUE THREAD

**Issue by ajssd** [bower/bower#1945]
My company uses a local bower registry like this in .bowerrc

```
    "registry": "http://artifactory.mycompany.com/artifactory/api/bower/bower-virtual"
```

My bower.json file has a dependency entry like:

```
    "mypackage": "http://mycompany.com:8080/artifactory/bower-local/mypackage-1.7.1.zip",
```

where the zip file is a modified version of a package downloaded from github (for some legal reasons, we had to make a change, and the pull request hasn't yet been accepted).

I do a "bower install mypackage" and everything is great.

Now, I make a change to the zip file.  I can't change the version number or the file name; I am just changing a line of code in a JS file inside the Zip file.  The expectation is that bower can use the e-tag to tell whether the zip file has changed.

I type "bower uninstall mypackage" then "bower install mypackage", expecting to get the new code.  However, this pulls from the (stale) cache rather than grabbing the new code.  ODDLY, however, bower detects the stale zip file (using e-tag) and claims to be updating the cache. However, when I check bower_components, it's the same code as before.

```
$ bower uninstall mypackage
bower uninstall     mypackage

$ bower install mypackage
bower mypackage#*                cached http://mycompany.com:8080/artifactory/bower-local/mypackage-1.7.1.zip#e-tag:2af72bda2b
bower mypackage#*              validate e-tag:2af72bda2b against http://mycompany.com:8080/artifactory/bower-local/mypackage-1.7.1.zip#*
bower mypackage#*                   new version for http://mycompany.com:8080/artifactory/bower-local/mypackage-1.7.1.zip#*
bower mypackage#*               resolve http://mycompany.com:8080/artifactory/bower-local/mypackage-1.7.1.zip#*
bower mypackage#*              download http://mycompany.com:8080/artifactory/bower-local/mypackage-1.7.1.zip
bower mypackage#*               extract mypackage-1.7.1.zip
bower mypackage#*              resolved http://mycompany.com:8080/artifactory/bower-local/mypackage-1.7.1.zip#e-tag:85ddfe2ee0
bower mypackage#*               install mypackage#e-tag:85ddfe2ee0
```

As you can see, there was a cache miss, and although a "new version" was detected, the old version remained in the cache, and my installed package continue to have the old code.

Same thing happens when I do "bower update my package".

The only workaround is to do "bower cache clean mypackage" before every install, just in case the Zip file has been updated.

I realize there are other ways to structure this development environment, without referencing a Zip file over http.  But this is what we have, and bower supports Zip files -- it just doesn't replace them in the cache when it detects that one has changed.

Is this just a bower bug or am I doing something incorrectly?

**Comment by ajssd** [comment]
Here is a simple testcase.  Create a file called **dummy123.zip** file on a webserver somewhere, accessible by http.

This zip file should contain these two files:
 - dummy123/bower.json
 - dummy123/dummy123.js

The **bower.json** file contains
```
{
  "name": "dummy123",
  "private": true,
  "main": "dummy123.js",
  "ignore": [],
  "version": "0.0.1"
}
```
The **dummy123.js** file contains
```
var x = 'version 1';
```

Next, in your dev env, create a bower.json that contains the following:
```
{
  "name": "bowertest",
  "private": "true",
  "devDependencies": {
    "dummy123": "http://127.0.0.1/dummy123.zip"
  }
}
```
and type `bower install` to install the dummy123 package.  So far so good, you should see the file installed in `bower_components/dummy123/dummy123.js`.

NOW, update the dummy123.js file in the Zip file, e.g. change "version 1" to "version 2".

In your dev env, type `bower update dummy123`.  You will see output like this:
```
bower dummy123#*                cached http://127.0.0.1/dummy123.zip#e-tag:35d-5222a
bower dummy123#*              validate e-tag:35d-5222a against http://127.0.0.1/dummy123.zip#*
bower dummy123#*                   new version for http://127.0.0.1/dummy123.zip#*
bower dummy123#*               resolve http://127.0.0.1/dummy123.zip#*
bower dummy123#*              download http://127.0.0.1/dummy123.zip
bower dummy123#*               extract dummy123.zip
bower dummy123#*              resolved http://127.0.0.1/dummy123.zip#e-tag:321-5222a
bower dummy123#*               install dummy123#e-tag:321-5222a
```
which shows the cache miss and the attempted install.  However, if you look at `bower_components/dummy123/dummy123.js`, it's still the old version.  **Nothing was actually installed.**

**Comment by ajssd** [comment]
I tested with 1.5.3 and 1.6.2, both have the same problem.

**Comment by NiteshOswal** [comment]
what if, we had a --force flag?

**Comment by ajssd** [comment]
It may not be necessary to remove the cache completely.  Bower is correctly detecting that the cache is out-of-date, and it correctly downloads a fresh copy and claims to "extract" and "install" it -- just that nothing is actually installed in bower_components, and the cache is not updated with the fresh copy.

**Comment by ptitgraig** [comment]
Which version of artifactory and bower are you using ? I know I'm not answering your question but you could make your life easier with bower 1.5.x> and user the artifactory resolver.

**Comment by ajssd** [comment]
I mentioned above that I reproduced with bower 1.5.3 and 1.6.2.  We are also using
"bower-art-resolver": "2.0.1".  But as shown above, this is reproducible without Artifactory.

**Comment by sheerun** [comment]
Unfortunately Bower won't fix it as it is depreacted and is seems like a bad idea to allow changing contents of packages. If you want contents different you need to change url.
