### ISSUE TITLE
Provide an option for install only main files from library

### ISSUE THREAD

**Issue by Alendorff** [bower/bower#1946]
Hello guys.

  Is it possible to provide some option for installing only main library files from repositories? Often, the entire library repository is not needed. Requires only some js or css files. 
  Peoples from SO suggest to use bower-installer plugin, but I think it's ridiculous. That plugin still downloads all git repo and then does a great job - copypastes specific files into selected folder! 
  I think we need some way to download only main files from libraries repositories.

**Comment by sheerun** [comment]
There's no other way than wrigin custom [Pluggable Resolver](http://bower.io/docs/pluggable-resolvers/) for GitHub repositories. It could download bower.json directly from GitHub repo and then fetch only main files, without checkout. You can create custom prefix, like `main:owner/repo`.

Hope it helps.
