### ISSUE TITLE
module node_uuid is not found

### ISSUE THREAD

**Issue by raqystyle** [bower/bower#1949]
Hello guys! Thanks for great work!

My `npm postinstall` script does the following:

```
rm -rf bower_components; ./node_modules/bower/bin/bower update; ./node_modules/bower/bin/bower install
```

When is comes to it I get this:

```
MODULE_NOT_FOUND Cannot find module 'node-uuid'
MODULE_NOT_FOUND Cannot find module 'node-uuid'
```

I figured out that this happens only with Bower 1.6 but not with 1.5.3

**Comment by sheerun** [comment]
I've rollbacked bower 1.6. Going to publish fixed version..

**Comment by sheerun** [comment]
Done. 1.6.2 should work. Can you confirm?

**Comment by raqystyle** [comment]
Thanks for fixes! I can try on Monday.
