### ISSUE TITLE
bower will not install into symlinked directory

### ISSUE THREAD

**Issue by tannerjfco** [bower/bower#1951]
Our deployments utilize symlinks for ```node_modules``` and ```bower_components``` to reduce disk usage and build times. With the 1.6.2 release, bower identifies that the symlink is not a directory and refuses to install.
> ENOTDIR ENOTDIR, not a directory '/var/www/site/bower_components'

I am unable to bypass this with ```--force``` flag or anything short of using a directory.

Bower should not care whether I install into a directory or a symlink so long as it is able to write to the desired location.

**Comment by uiureo** [comment]
+1 

Related: #1953
