### ISSUE TITLE
Discussion: new property in bower.json to list all files that are used for build steps

### ISSUE THREAD

**Issue by lambertsteven** [bower/bower#1952]
Bower components have no set structure. Some components give you all the source code (jQuery) while others give you everything in the github repo (inject). Some components' main file is the compiled output (jQuery, bootstrap) while others are just a file that depends on other files (polymer).

When trying to create a build step to move bower files to a `dist` folder that will then be deployed, this can cause lots of problems, especially if you want to process files. If we were to just grab everything in components, a build would break when source files are not meant to be processed alone (jQuery source files are not complete files because they are meant to be concatenated, so running uglify on it breaks).

As you are aware, https://github.com/ck86/main-bower-files was created to help solve the issue of knowing which files to work with by looking at the `main` property of the bower.json. However, the problem with the `main` property is that it can only list one file of each type. So in the case of polymer, they can only ever list one html file, even though they need all the html files in their folder to work correctly. 

I would like to propose a new property of the `bower.json` that would allow component developers to list all files that are needed to use that component. This could be an optional property that could be used when multiple files of the same type are needed, as in the case of many of the components being written by the polymer team (iron, gold, etc.).

I'm not sure what to call this property, but I think it would help all consumers of components to be able to work with all the files they need.

**Comment by jshcrowthe** [comment]
:+1:

**Comment by NiteshOswal** [comment]
Sugoi, we can call it, "needs"

**Comment by straker** [comment]
I like the name "needs"

**Comment by NiteshOswal** [comment]
It can be a list of resources needed, or an object nested lists of
resources needed.

**Comment by lambertsteven** [comment]
I like it. How would you use the object nested lists?

**Comment by ZaLiTHkA** [comment]
I think the idea of nested lists is spot on.. By my understanding, the purpose of this object is simply to list "file inclusion rules" for specific projects installed through Bower, to be used for a post-install or specific build step. That about sum it up?

In this case, I see an object that holds named keys (matching Bower components) that each contain an array of globs. Using RegExp to match the files will give the most flexibility, along with a way to explicitly include and exclude specific file name patterns.

For example:

```javascript
{
  ...
  "jquery": ["src/**/*.js"],
  "bootstrap": [
    "less/**/*.less",
    "js/*.js",
    "fonts/*"
  ],
  ...
}
```

Depending on the complexity required from the scripting side, this requirements object could even contain it's own top-level keys for special uses, such as"

```javascript
{
  "concatOnly": {
    "jquery": [...],
    ...
  },
  "default": {
    "bootstrap": [...],
    ...
  }
}
```

Hows that for a starting point?

**Comment by lambertsteven** [comment]
I think that's a great starting point. Let me try to document an extreme example to see if we're on the same page. 

The Polymer component [neon-animation]( https://github.com/PolymerElements/neon-animation) is quite complex and has several different animations that each require their own dependencies. Now, their `main` property is currently invalid according the spec since they list multiple `.html` files, which each have their own dependencies. 

If I understand what you are saying, you would like to use the `needs` property in the component that *consumes* the `neon-animation` component to list the files that I am using from neon-animation. This would require the I as the consumer fully understand the internal dependencies of the neon-animation parts that I am using. Is that correct?

So if I wanted to use the fade in animation, my `bower.json` would list it's needs as:

```js
"needs": {
  "polymer": ["polymer.html"],
  "neon-animation": [
    "neon-*.html",
    "web-animations.html", 
    "animations/fade-in-animation.html"
}
```

I don't know if this is the approach we want to take. This would mostly lead to a trial and error approach where I list everything I could find, and if I miss one, add that to the list. This is exactly what I've been doing up to this point, and it's not very helpful.

I would hope instead that the `needs` property would be used in the component `bower.json` itself that they would tell me, as the consumer, which files their component needs to run. 

In the case of neon-animation, they could choose to take the simple approach and list everything in `animations/*.html`, as well as every `.html` file in the main folder except `index.html`. They could also get really complicated and list what each file needs to work.

So they might list their `needs` as:

```js
"needs": [
  "neon-*.html",
  "web-animations.html", 
  "animations/*"
]
```

or 

```js
"needs": {
  "default": [...],
  "cascaded-animation": [...],
  "fade-in-animation": [...],
  "fade-out-animation": [...],
  ...
}
```

I'm not sure if the second option brings any more order to the chaos, or would help consumers of the component any more than the first option.

Since `bower.json` already lists polymer as a dependency, I can look at polymers `bower.json` to figure out which files it needs, in this case they would list:

```js
"needs": [
  "polymer.html",
  "polymer.mini.html",
  "polymer.micro.html"
]
```

So my nor neon-animations `bower.json` would need to list polymer's files.

A problem I see with this approach is what if you want to use a file not listed in the `needs` property, in which case maybe having the consumers `bower.json` list which files they are using from other dependencies would be helpful.

**Comment by NiteshOswal** [comment]
@ZaLiTHkA I couldn't have explained the nested lists any better

@lambertsteven good point on checking `bower.json` of other components/packages. Didn't anticipate, if needs is a property, people will naturally be using it in their `bower.json` files. So we probably will be better off with simple lists

**Comment by NiteshOswal** [comment]
@lambertsteven about that problem in the end, maybe needs can be defined in the project's `bower.json` as well, and it'll extend the needs list of that package. Oh and that's where the nested lists can help us. We can define more file/pattern dependencies for that package, using that nested lists, with object properties being the package name of course, and they'll extend the predefined needs

**Comment by lambertsteven** [comment]
@NiteshOswal I think that's a great idea

**Comment by ZaLiTHkA** [comment]
> If I understand what you are saying, you would like to use the `needs` property in the component that consumes the `neon-animation` component [...]

@lambertsteven; yup, that is indeed how I understood your initial message. I pictured `project-x` listing all the files it required from `component-a`, `component-b`, etc. with relative paths for *it's own build process*.

You raise a valid point that I hadn't really considered; where the end user probably wouldn't (and shouldn't need to) know the internal mechanics of the components they use. With packages of a "library" level, simply knowing the results of it's public API should be enough to use it. I fear if this property is intended to list files *from the current package* that need to be included in the build of a project that depends on it, then this could get horribly verbose very quickly... Especially for packages that are collections of optional resources, since their `needs` property would then have to cater for *every* variation to be useful.

My work day just started (GMT+2) and I'm not familiar with the `neon-animation` package, so I'll need to do some more digging before I comment further.. I'll see if I can come up with a few other ideas when I get home later this evening.

**Comment by sheerun** [comment]
@lambertsteven PolymerElements/neon-animation can use `neon-animation.html` as their `main` file. It imports all other files so there's no need to list multiple html files in bower.json.

**Comment by lambertsteven** [comment]
@sheerun that is true, but it's not so simple. As [this issue](https://github.com/Polymer/vulcanize/issues/51) explains, when you try to vulcanize the main file, your folder structure may not be what you need it to be. 

This is especially true when you are using a css preprocessor or a js transpiler. You end up having to process those assets down to their css/js native files, typically putting them into `/build`, then moving all needed files also into `/build` to keep the directory structure, so that you can then vulcanize properly. 

This means that my folder structure goes from 

```
- app
  - components
  - assets
```

to

```
- app
  - components
  - assets
  - build
    - assets
    - components 
```

The end result is typically a `/dist` folder that you would deploy to your servers, which requires that you move all needed bower components from their install folder into `/build`, run any processing on them, then move them to `/dist`. Because I only want the files I'm using as part of the deploy and on the server, and I want those files minified and gziped, I can't just move all assets from bower into `/dist`. This is because some projects, like jQuery, provide their entire source code as part of their component, and if I were to try to minimize it, would throw an error.

And since almost all `main` files of any bower file point to the unminified code, I have to run minification on them.

**Comment by sheerun** [comment]
@lambertsteven In case of Polymer you can use hyrolysis to fetch dependencies of given .html file, and process only them, instead of all files in repository:

```
var path = require('path');
var hyd = require('hydrolysis');

hyd.Analyzer.analyze(path.join(__dirname, 'neon-animation.html')).then(function(analyzer) {
  console.log(Object.keys(analyzer.html));
});
```

```
[ '/Users/sheerun/Source/Temporary/neon-animation/neon-animation.html',
  '/Users/sheerun/Source/Temporary/neon-animation/neon-animatable-behavior.html',
  '/Users/sheerun/Source/Temporary/neon-animation/neon-animatable.html',
  '/Users/sheerun/Source/Temporary/neon-animation/neon-animated-pages.html',
  '/Users/sheerun/Source/Temporary/neon-animation/neon-animation-behavior.html',
  '/Users/sheerun/Source/Temporary/neon-animation/neon-animations.html',
  '/Users/sheerun/Source/Temporary/neon-animation/neon-animation-runner-behavior.html',
  '/Users/sheerun/Source/Temporary/neon-animation/neon-shared-element-animatable-behavior.html',
  '/Users/sheerun/Source/Temporary/neon-animation/neon-shared-element-animation-behavior.html',
  '/Users/sheerun/Source/Temporary/polymer/polymer.html',
  '/Users/sheerun/Source/Temporary/iron-resizable-behavior/iron-resizable-behavior.html',
  '/Users/sheerun/Source/Temporary/iron-selector/iron-selectable.html',
  '/Users/sheerun/Source/Temporary/iron-meta/iron-meta.html',
  '/Users/sheerun/Source/Temporary/neon-animation/animations/opaque-animation.html',
  '/Users/sheerun/Source/Temporary/neon-animation/animations/cascaded-animation.html',
  '/Users/sheerun/Source/Temporary/neon-animation/animations/fade-in-animation.html',
  '/Users/sheerun/Source/Temporary/neon-animation/animations/fade-out-animation.html',
  '/Users/sheerun/Source/Temporary/neon-animation/animations/hero-animation.html',
  '/Users/sheerun/Source/Temporary/neon-animation/animations/ripple-animation.html',
  '/Users/sheerun/Source/Temporary/neon-animation/animations/reverse-ripple-animation.html',
  '/Users/sheerun/Source/Temporary/neon-animation/animations/scale-down-animation.html',
  '/Users/sheerun/Source/Temporary/neon-animation/animations/scale-up-animation.html',
  '/Users/sheerun/Source/Temporary/neon-animation/animations/slide-from-left-animation.html',
  '/Users/sheerun/Source/Temporary/neon-animation/animations/slide-from-right-animation.html',
  '/Users/sheerun/Source/Temporary/neon-animation/animations/slide-left-animation.html',
  '/Users/sheerun/Source/Temporary/neon-animation/animations/slide-right-animation.html',
  '/Users/sheerun/Source/Temporary/neon-animation/animations/slide-up-animation.html',
  '/Users/sheerun/Source/Temporary/neon-animation/animations/slide-down-animation.html',
  '/Users/sheerun/Source/Temporary/neon-animation/animations/transform-animation.html',
  '/Users/sheerun/Source/Temporary/neon-animation/web-animations.html' ]
```

You can filter those paths by anything you want.

**Comment by lambertsteven** [comment]
@sheerun hu, I didn't know about that package. I'll have to check it out. Polymer libraries aside, I think a `needs` property would be helpful.

**Comment by lambertsteven** [comment]
Any update on this?

**Comment by sheerun** [comment]
As I said, this property is not needed, because you can always extract all the dependencies from main files. No?

**Comment by lambertsteven** [comment]
Well sure, if you could understand all languages and how they could possibly load their dependencies, then yes.

If I want to use Bootstrap css, it's not listed in any of their main files because they default to their less file. If I use the webcomponentjs pollyfill, it doesn't list it's entire src directory in it's main (because only 1 file type is allowed), but it async loads all the src files in their main script using injected script tags. All of this means that I have to understand these things as I consume the component and have to manually tweak a list of files to bring over from each component every time either they change their files or I bring in a new component.

All I'm really asking is for the bower component to tell me what files I need to bring over in my build process instead of making me do all the work in trying to figure out what they use and depend on.

**Comment by waaronking** [comment]
Yeah I agree with @lambertsteven, at my org we're running into a similar issue. The main files don't provide enough information to know the requisite dependencies.

**Comment by sheerun** [comment]
Personally I think we can't please everyone. If you really need to "list" resources needed for building your project, add a `.json` file to `main` that lists all of them. Or just add `fields` field to bower.json, no problem.

Standardizing such field is out of Bower's scope, simply because Bower doesn't use it in any way..

Would the possibility to add any custom fields, including `files`, to `bower.json` please you?

**Comment by lambertsteven** [comment]
It would only be useful if everyone followed it. Without a standard, it probably wouldn't fix the underlying issue.
