### ISSUE TITLE
Document package.json use

### ISSUE THREAD

**Issue by mathiasrw** [bower/bower#1957]
According to https://github.com/bower/bower/issues/1626 the `package.json` can be used instead of `bower.json`. 

From https://github.com/bower/bower/issues/1626#issuecomment-121179897 its not clear how to use the `"ignore":` option from `bower.json` format.

I recommend that https://github.com/bower/spec includes information about how to use `package.json` for bower.

**Comment by sheerun** [comment]
It can be used only for `.bowerrc` configuration. It's indeed not documented on bower.io

**Comment by mathiasrw** [comment]
Thanks for pointing that out...
