### ISSUE TITLE
bower version not working

### ISSUE THREAD

**Issue by fabdeceglia** [bower/bower#1959]
Hi all,

My bower version is the 1.5.3 on a W7 64bit machine.

I have a folder with a git repo, my bower.json file and my scripts file.

When i update some file and try to run the command: <i>bower version 0.0.5 patch -m "testing bower versionig"</i> <b>no tag and commit are created.</b>

Only the version field is created in the bower.json file (I think this is useless because of this field is deprecated as bower spec).

Is this related to this quote from the official doc ? 

"<i>If run in a git repo, it will also create a version commit and tag, <b>and fail if the repo is not clean.</b></i>" 

Thanks for the help ;)

**Comment by tejgop** [comment]
@fabdeceglia, did you keep your `bower.json` file in your git repo? Then, the repository is **no longer clean!** Try this:
```
git add bower.json
git commit -a -m "Bower JSON"
bower version 1.2.3 patch -m "Testing"
```

**Comment by jamesxv7** [comment]
@fabdeceglia Did you had the opportunity to check the solution provided by @tejgop?
