### ISSUE TITLE
Breaks when asking for user input on Windows

### ISSUE THREAD

**Issue by astromac** [bower/bower#1961]
Whenever bower asks for user input (e.g. ask to send usage stats, choosing a version of a package, etc.) it crashes. It happens on my Windows machine but not my Mac. Both are using Nodejs 4.2.1, npm 3.3.8 and bower 1.6.3. The error displayed is below.

```
Answer events.js:141
    throw er; // Unhanded 'error' event
    ^

Error: read EINVAL
    at exports._errnoException (util.js:874:11)
    at TTY.onread (net.js:544:26)
```

**Comment by esinek** [comment]
I had the same issue. Resolved it by adding the following to .bowerrc
"interactive": false

**Comment by jamesxv7** [comment]
Hello @astromac, could you please confirm is workaround provided by @esinek works?

**Comment by maxlorenz** [comment]
Hi,

same problem here. Windows 10, fresh install, bower 1.8.0. The workaround doesn't solve the problem with choosing a package version as it exits with `ECONFLICT Unable to find suitable version for ...`

**Comment by sheerun** [comment]
This issue got stale, if it's still an issue, please open another one with steps to reproduce
