### ISSUE TITLE
Using bower with monolithic repositories

### ISSUE THREAD

**Issue by gaelduplessix** [bower/bower#1965]
We're using bower to manage both external and internal dependencies on a large web application. However, this forced us to split our application in multiple repositories. This could look like a good idea (separation of concerns, independent/reusable units of code, ...) but it turns out it's creating more problems than it's solving (PR's on multiple repositories, heavy setup for testing...). I'm not going to cover the potential benefits of monolithic repositories here, others [already did this](http://gregoryszorc.com/blog/2014/09/09/on-monolithic-repositories/)

I'm just regretting bower doesn't offer any way to host multiple packages on the same repository. This has already been discussed for a long time #24 and I think the issue is worth re-considering.
Bower is a great tool for package management but this limitation forces large teams to hack their workflow and spend huge amount of time maintaining repositories just to support bower.

Can we have more insights on this subject ?

**Comment by sheerun** [comment]
There's potential to make Pluggable Resolver that can handle it. Or implement "Custom Postprocessors" functionality: https://github.com/bower/bower/issues/1930 Then we could use it something like:

```
"dependencies": {
  "my-monolithic-package": "1.2.3!directory=modules/something"
}
```

Please note that bower requires git tags for versions, so all packages in monolithic repository would need to share their..

**Comment by filib** [comment]
@sheerun @gaelduplessix did either of you get anywhere with this? I'd really like this feature too but not entirely sure where to begin.

**Comment by gaelduplessix** [comment]
We don't use bower anymore (switched to npm for both backend and frontend dependencies). This didn't really solve the "monolithic repo" problem though.

You may be able to put something together using the Custom Postprocessors. Something like checking-out the whole repo and then removing the folders you don't need. Not sure it really solves the problem but that's something to look into

**Comment by sheerun** [comment]
Bower is in maintenance mode and won't support monorepos
