### ISSUE TITLE
--quiet option suppresses all output of info command

### ISSUE THREAD

**Issue by deedubbu** [bower/bower#1966]
Running the `info` command with a specified property displays something like this:
```
$ bower info PolymerElements/paper-button name
bower paper-button#*            cached git://github.com/PolymerElements/paper-button.git#1.0.8
bower paper-button#*          validate 1.0.8 against git://github.com/PolymerElements/paper-button.git#*

'paper-button'
```

I was hoping to suppress the package lookup information and extra white space in order to just retrieve the property value ('paper-button') I was requesting so I tried the `--quiet` option. That however results in no output.

```
$ bower info --quiet PolymerElements/paper-button name
```

The `--quiet` option is documented as `only output important information`. It seems to me in this scenario the property I am requesting is important information.

**Comment by jamesxv7** [comment]
Hello @deedubbu, please verify the following [thread](https://github.com/bower/bower/issues/1493) in order to clarify doubts regarding `--quiet` option. Interesting information is being discussed which I believe it can provide guidance to your situation.
