### ISSUE TITLE
Pluggable Resolver - When using a prefix the resolver is not kicking in

### ISSUE THREAD

**Issue by AlexeiVainshtein** [bower/bower#1975]
When installing a package with prefix for example: `bower install chieffancypants/angular-hotkeys` then the resolver (bower-art-resolver) is not kicking in and it goes straight to Github:

```
bower i chieffancypants/angular-hotkeys
bower angular-hotkeys#*     not-cached git://github.com/chieffancypants/angular-hotkeys.git#*
bower angular-hotkeys#*        resolve git://github.com/chieffancypants/angular-hotkeys.git#*
bower angular-hotkeys#*       download https://github.com/chieffancypants/angular-hotkeys/archive/1.6.0.tar.gz
bower angular-hotkeys#*        extract archive.tar.gz
bower angular-hotkeys#*       resolved git://github.com/chieffancypants/angular-hotkeys.git#1.6.0
bower angular-hotkeys#~1.6.0   install angular-hotkeys#1.6.0
```

It skips the resolver that points to Artifactory and goes straight to GitHub. There is no indication in the logs for this package so it seems that Bower skips the bower-art-resolver in such cases.

**Comment by faceleg** [comment]
Edited for readability.

**Comment by prometheansacrifice** [comment]
@AlexeiVainshtein You are using a shorthand `chieffancypants/angular-hotkeys`. Hence, accordingly, you must also use a `shorthand-resolver` in your `.bowerrc`. The default is `git://github.com/{{owner}}/{{package}}.git`. Hence it tries to resolve the github url

**Comment by BenMann** [comment]
Yep @prometheansacrifice is right. Also here's the according quote from the docs:
```
Bower doesn’t support GitHub-style namespacing (org/repo), 
however you are encouraged to namespace related packages 
with -, for example, angular- and paper-.
```

Also this is a related issue: https://github.com/bower/bower/issues/2179

I guess with all that said, we can close.
Feel free to comment more on the issue if there's more! :cookie:

**Comment by AlexeiVainshtein** [comment]
Thanks! The prefix to use with Artifactory for future reference is: "shorthand-resolver": "art://{{owner}}/{{package}}"
