### ISSUE TITLE
Unregister or Change Repo of BitBucket Package

### ISSUE THREAD

**Issue by buschschwick** [bower/bower#1977]
So I've tried searching how to remove it myself or where to go to ask for it to be removed but I'm coming up blank, or finding old posts I don't want to re-open.

I have a package, sugar-mixins that is public on the Bower Registry and it has a BitBucket repo attached to it. Is there a way to change my endpoint of the public package to a GitHub repo instead or how can I completely remove it. It's my first public package and I might have jumped the gun or configured it wrong.

Or alternatively...

When I install all I have is an index page with BitBucket HTML and not my actual package. Is this a config problem or because it's BitBucket and not GitHub?

Any help would be appreciated or links to some good resources to get me in the right direction. Thanks.

**Comment by pertrai1** [comment]
@bower/contributors - Any ideas to lead @buschschwick in the right direction?

**Comment by buschschwick** [comment]
Thanks @pertrai1 - this is still an issue, but I ended up having to just create a new package and move on. It would be nice to be able to remove my first one.

**Comment by pertrai1** [comment]
@buschschwick - you are welcome. Just to be clear, what do you mean "remove my first one"?

**Comment by buschschwick** [comment]
@pertrai1 I created a package (the first one), with a repo associated with BitBucket, which is no longer maintained as it is now on GitHub. Because I couldn't change the package repo / delete it I created a new package in the registry with a slightly different name.

I'd like to wipe the first one from existence if possible :-)

**Comment by pertrai1** [comment]
@buschschwick If I understand correctly you want to unregister your package? You can do `bower unregister <package>` and that should take care of it for you. I hope I am answering the question right

**Comment by buschschwick** [comment]
@pertrai1 The answer is correct, however since it was created with BitBucket I get this error:

`Can only unregister packages hosted on GitHub.com`

It's marked private so it doesn't show up when searching, but just sort of stinks that I used my good package name :disappointed: 

That's alright. Unless you know of any other solutions, I'm just going to close this issue since it didn't seem to create any traction but there does seem to be lack of resources on how to unregister a package that isn't a GitHub repo, at least that I can find.

Thanks for your help.

**Comment by pertrai1** [comment]
@sheerun - is there any way to handle the issue that @buschschwick has run into with the name of his package being available after moving it from BitBucket?

**Comment by sheerun** [comment]
@buschschwick please send a request to bower/registry repository

**Comment by pertrai1** [comment]
@sheerun - Thanks Adam for quick help

**Comment by buschschwick** [comment]
@pertrai1 @sheerun Yes, thanks everyone!
