### ISSUE TITLE
don't show prereleases as latest in `list` output

### ISSUE THREAD

**Issue by avdd** [bower/bower#1983]
`bower list` shows prereleases as the "latest" version:

```
bower check-new     Checking for new versions of the project dependencies...
bowertest /tmp/bowertest
└── angular#1.4.5 (latest is 1.5.0-build.4368+sha.fe11265)
```

At this time, the latest stable angular is 1.4.7, and `install -F` will install that, and not the prerelease 1.5.  But how do I know that without running `install`?  The prereleases are ignored in the `install` logic, so too should they be ignored by `list`.

**Comment by pertrai1** [comment]
#2081 is a newer thread that goes along with this to a point

**Comment by sheerun** [comment]
@pertrai1 It's little different request

**Comment by pertrai1** [comment]
@sheerun How do I un-reference it?

**Comment by sheerun** [comment]
You can't

**Comment by jamesxv7** [comment]
@avdd I'll close this issue since this item it is discussed in the following [thread](https://github.com/bower/bower/issues/1312).
