### ISSUE TITLE
invalid-meta missing "ignore" entry in bower.json

### ISSUE THREAD

**Issue by robstoll** [bower/bower#1984]
after using bower.init I have the following entry in my bower.json:
```
"ignore": [ "**/.*", "node_modules", "bower_components", "test", "tests" ],
```
When trying to register the corresponding repo I get the above warning. Seems like the check itself ignores the ignore entry ^^

I am using bower 1.6.5

**Comment by sheerun** [comment]
Maybe you forgot to tag last release? Please share the repository.

**Comment by robstoll** [comment]
It was for the following repository:
https://github.com/robstoll/angular-pre-work/blob/0.0.2/bower.json

The message only appears when I try to register the repository:
```
bower register tutteli-angular-pre-work https://github.com/robstoll/angular-pre-work
```
Following the output
```
bower tutteli-angular-pre-work#*          resolve https://github.com/robstoll/angular-pre-work#*
bower tutteli-angular-pre-work#*         download https://github.com/robstoll/angular-pre-work
bower tutteli-angular-pre-work#*     invalid-meta tutteli-angular-pre-work is missing "ignore" entry in bower.json
bower tutteli-angular-pre-work#*         resolved https://github.com/robstoll/angular-pre-work
```
Notice, the ignore flag is only ignored during this check. When I install it afterwards with `bower install`, then I do not get the ignored files, or in other words the ignore entry works as expected. So I guess the bug is somewhere in the logic for registering repositories.

**Comment by OmgImAlexis** [comment]
Getting the same results as @robstoll with [Chart.js](https://github.com/nnnick/Chart.js).

**Comment by zeakd** [comment]
I have same error on my [project](https://github.com/zeakd/rothko.js)

``` bash
bower register rothko https://github.com/zeakd/rothko.js
bower resolve       https://github.com/zeakd/rothko.js#*
bower download      https://github.com/zeakd/rothko.js
bower invalid-meta  rothko is missing "ignore" entry in bower.json
bower resolved      https://github.com/zeakd/rothko.js
```

**Comment by sheerun** [comment]
You can see what bower sees by ussing command `bower info ENDPOINT`, like `bower info zeakd/rothko.js`. Most likely it's missing `ignore` info because you did not released version with added `ignore` field. Bower requires you to add *semver tag* to release package.
