### ISSUE TITLE
Is .bowerrc necessary?

### ISSUE THREAD

**Issue by camohub** [bower/bower#1986]
Hello, can you tell me if there is no way to join .bowerrc file with bower.json? More than often I see projects which have .bowerrc file with only information about directory where to save libraries. But so the root directory has so many files like .gitignore, .htaccess, .bowerrc, ..... that it looks really messy. Of course it is necessary. But only bower needs to have two files for its configuration there. Why?

Thanks.

**Comment by faceleg** [comment]
I believe it is because the `.bowerrc` is also used to reference proxy settings, and is merged backwards through the file directory tree.

See http://bower.io/docs/config/#placement--order for more details

**Comment by faceleg** [comment]
@sheerun pasting from gitter for reference.

A possible modification that might make more sense to the community:

 - Use `.bowerrc` for "system config", i.e. any auth or proxy settings, and expect it to reside at `~/.bowerrc`
 - Expect non "system config" config to reside in a "config" portion of `bower.json`
 - Throw out deprecation warnings when a `.bowerrc` file is found in the project path or non "system config" properties are found in the `~/.bowerrc` file

If this is desirable, we will need:

 - Categorize what config is "system" and what is not
 - Community involvement to write review and submit the change

**Comment by camohub** [comment]
What should I do to achieve that? Nobody before me did not submit similar proposal?

**Comment by faceleg** [comment]
If it has been discussed before, I am not aware of it.

**Comment by camohub** [comment]
May be only "directory": "....", part of .bowerrc could be moved to bower.json. 
I think it is the same kind of info as list of libraries.

**Comment by faceleg** [comment]
Yeah I agree. @sheerun?

**Comment by sheerun** [comment]
We can't move it. We may support it in both. Note that this change is not backward compatible. I.e. if someone will use `directory` in `bower.json`, it will be ignored by old bower versions.. So it forces all members of given team need to update to the newest bower. Is it worth it? I don't know.

**Comment by camohub** [comment]
Of course it has to be supported in both files because of BC. But it would be good. Wouldn't be?

**Comment by faceleg** [comment]
I have many projects that have a `.bowerrc` containing only the directory line, IMHO it's worth it

**Comment by christianpv** [comment]
I'm in favor of adding the directory line to bower.json while maintaining the .bowerrc for BC. When bower 2.0 comes out, remove it from bowerrc. I have 10+ projects with only the directory line in .bowerrc.

**Comment by sheerun** [comment]
Please not that we already indirectly support putting configuration variables in `package.json`, like so:

```
{
  "scripts": {
    "bower": "bower"
  },
  "config": {
    "bower": {
      "directory": "foobar"
    }
  }
}
```

and then running bower with

```
npm run bower
```

I think we should document it better. Maybe create "Bower and npm" page on bower.io?

Also we need to document it here: http://bower.io/docs/config/#bowerrc-specification

@bower/bower-volunteers Mind to create pull requests with docs?

**Comment by camohub** [comment]
But it is not user friendly solution.

**Comment by christianpv** [comment]
@sheerun I think that is not a good way to do it, maybe I'm wrong but shouldn't bower config be in bower.json file? Why should we look for bower config inside package.json? Think about it if you get a project, the first thing you would do if you want to change something bower related is look for bower.json and not package.json. I think this solution is breaking separation of concerns and kiss. We should keep it simple and put it on bower.json.

**Comment by cedced19** [comment]
I think keep `.bowrrc` is a good solution because set it in a `package.json` make us more dependent of npm. And In my opinion It's a bad idea for the community to relocate it in to the `bower.json`.

**Comment by sheerun** [comment]
OK, let's implement it.. The repository to do it is: https://github.com/bower/config

Requirements:

- [ ] Use https://github.com/bower/json to read `bower.json` from passed cwd
- [ ] If no cwd is passed, skip reading from bower.json
- [ ] Merge configuration as so:
  1. CLI arguments via --config
  2. Environment variables
  3. **The "config" field in bower.json located in the current working directory**
  4. Local .bowerrc located in the current working directory
  5. All .bowerrc files upwards the directory tree
  6. .bowerrc file located in user’s home folder (~)
  7. .bowerrc file located in the global folder (/)

And then in bower/bower:

- [ ] Update bower-config dependency 
- [ ] Release a patch for old bower versions that warns about config present in bower.json (it's because old bower versions won't support this feature). I think we need to create `bower-warnings` package and include it in all of previous bower versions. Then we can just update this package to introduce new warnings in all previous versions.

In both cases at least two people from need to review it and at least two people with write access need to say "Ship it!".. Sounds good? Any corrections to this specification?

/ping @bower/bower-volunteers

**Comment by cedced19** [comment]
Ok I'm agree with you.
I'll not write code now, I don't know how bower core works.
Maybe I can help in `bower-json`.
I'll help you to update the docs.
I'm new here.

**Comment by paulohp** [comment]
Can I do this one @sheerun ?

**Comment by sheerun** [comment]
sure :)

**Comment by camohub** [comment]
Thanks a lot!

**Comment by faceleg** [comment]
Awesome go @paulohp :tada: :dancer:

**Comment by christianpv** [comment]
LGTM! Thanks @sheerun for accepting feedback and coming up with a plan. Thanks to @paulohp for help implement it :+1:

**Comment by paulohp** [comment]
:+1: :shipit:

**Comment by indolering** [comment]
> iii. The "config" field in bower.json located in the current working directory
> iv. Local .bowerrc located in the current working directory

That means I won't be able to override a project's directory paths using my own config without having to maintain a split version of the `bower.json` directory.  This is why `.config` files exist: to isolate user-specific settings.  We should at least be able to force an override within a `.bowerrc` file.

**Comment by sheerun** [comment]
I don't understand. Please provide an example. Config in `bower.json` is not inherited, and works only if it is defined in cwd where bower runs. You can as well replace `directory` in bower.json.

**Comment by wookoouk** [comment]
I would love for the  dependency directory to be set in bower.json.

**Comment by elkuku** [comment]
I'd like to vote for this feature too :wink:

**Comment by sheerun** [comment]
Bower is deprecated and in maintenance mode, so we won't implement new features like this one. We recommend switching to yarn and migrating legacy projects to it with [bower-away](https://github.com/sheerun/bower-away)
