### ISSUE TITLE
strict-ssl: false in .bowerrc stopped working after 1.5.3 version of bower

### ISSUE THREAD

**Issue by Joppe-A** [bower/bower#1991]
The 1.60 and higher version of bower don't seem to apply the strict-ssl setting properly. I had to revert to 1.5.3 to get it to work again.

**Comment by faceleg** [comment]
Related? #1972

**Comment by pwielgolaski** [comment]
Yes, it is the same issue

**Comment by vrmerlin** [comment]
whew, i thought i was going crazy! Yes, I am having this problem as well. :-(

**Comment by faceleg** [comment]
Closing, please keep an eye on #1972
