### ISSUE TITLE
bowerrc is not read from set working directory 

### ISSUE THREAD

**Issue by tdesvenain** [bower/bower#1993]
When we set working directory through command line using `--config.cwd=` parameter,
it continues reading the bowerrc configuration from the path we launch the command.

Actually the implementation does'nt care of any cwd override when it builds configuration :

https://github.com/bower/bower/blob/master/lib/config.js#L15

This prevents to run a bower command from outside a directory, and IMHO it is inconsistent with the documentation: https://github.com/bower/spec/blob/master/config.md (`Local .bowerrc located in the current working directory`)

We get the expected behaviour when we replace this by (obviously not the best implementation...) :
```
    current = bowerConfig.create(cwd).load(overwrites);
    if (current.cwd) {
        current = bowerConfig.create(current.cwd).load(overwrites);
    }
```

**Comment by pertrai1** [comment]
@tdesvenain - would you be willing to do a PR on this change with a test?

**Comment by ryantemple** [comment]
I'll take a look at this.

**Comment by ryantemple** [comment]
Have fixed this in the bower-config repo - just needs a second pair of eyes to double check for me
