### ISSUE TITLE
bower.json resolution section issues

### ISSUE THREAD

**Issue by PavelPolyakov** [bower/bower#1995]
Hi,

I have tracked the next bug. In short - if you update the module resolution version several times, it just stop reads from that field (or something.
If you had, for example, version `2.9`, and then updated the `bower.json` to the version `2.10` - it would not install the newest version.

Here is the video:
http://take.ms/xvv9R

As you see, after some time, `bower i` does not do anything, while it should install the version higher then the current one.

Those are the original `bower.json` files:
**A**

```
{
  "name": "test",
  "version": "0.0.1",
  "license": "NL",
  "private": true,
  "dependencies": {
    "moment": "~2.9",
    "material-date-picker": "~1.1.5"
  },
  "resolutions" : {
    "moment": "~2.9"
  }
}

```

**B**

```
{
  "name": "test",
  "version": "0.0.1",
  "license": "NL",
  "private": true,
  "dependencies": {
    "moment": "~2.10",
    "material-date-picker": "~1.1.5"
  },
  "resolutions" : {
    "moment": "~2.10"
  }
}

```

If I remove the `bower_components` directory - bower will install correct versions of libraries.

This bug was tracked, because it affected our deploy (we expected to receive the higher version). So this could be confused.

Any thoughts?

**Comment by pertrai1** [comment]
@PavelPolyakov - if updating to newer versions, would you not want to do `bower update` the packages that you are updating?

**Comment by PavelPolyakov** [comment]
@pertrai1 
nope, I want to do ```bower install``` always, because it's a part of the deploy procedure. It does install when the modules are not installed yet, it does install, when the modules are already installed, but the version number was changed.

So, it's simplier to do ```bower install```, instead of guessing if the modules were already installed.

**Comment by sheerun** [comment]
It's because as soon as there are no conflicts, bower ignores resolutions.

It's strange behavior and I described it in https://github.com/bower/bower/issues/1362

**Comment by PavelPolyakov** [comment]
@sheerun 

Ok, I see that you have started this discussion in 2014. Are there any plans to proceed with this?

Regards,

**Comment by faceleg** [comment]
Plans rely on community support - with pull requests! :D

**Comment by sheerun** [comment]
I'm little biased about this because this change would bread backward compatibility. Even if previous behavior is clearly confusing.. Probably we should introduce `--beta` flag or something and fix it under it.

**Comment by sheerun** [comment]
Bower is deprecated and in maintenance mode, so we won't implement new features like this one. We recommend switching to yarn and migrating legacy projects to it with [bower-away](https://github.com/sheerun/bower-away)
