### ISSUE TITLE
Angular UI and bootsrap case

### ISSUE THREAD

**Issue by diegoaguilar** [bower/bower#1996]
I'm starting user bower with wiredep I tried the following:

`bower install --save angular-ui bootstrap animate.css`

And that's downloading jquery ... so as we know if I'm using bootstrap with angularjs I *don't* want to use jquery at all, also something strange I'm noticying is that none bootstrap css is being added after runnin `wiredep -s index.html`

I'm starting user bower with wiredep I tried the following:

`bower install --save angular-ui bootstrap animate.css`

So we know that when using bootstrap and angular together we *don't*  want to use jquery, which is being downloaded and added ... Also, something strage is that none bootstrap css is being added when running `wiredep -s index.html`

This is what my markup looks like:

```
<!DOCTYPE html>
<html lang="en"></html>
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <!-- bower:css -->
  <link rel="stylesheet" href="bower_components/animate.css/animate.css" />
  <!-- endbower -->	
</head>
<body>
  <!-- bower:js -->
  <script src="bower_components/jquery/dist/jquery.js"></script>
  <script src="bower_components/angular/angular.js"></script>
  <script src="bower_components/angular-bootstrap/ui-bootstrap-tpls.js"></script>
  <script src="bower_components/bootstrap/dist/js/bootstrap.js"></script>
  <!-- endbower -->
</body>
```

**Comment by albertinad** [comment]
@diegoaguilar the problem you're describing seems to be an issue for wiredep instead of bower.
