### ISSUE TITLE
npm ERR! tar.unpack untar error /home/vagrant/.npm/bower/1.6.5/package.tgz

### ISSUE THREAD

**Issue by gregoryderner** [bower/bower#1999]
Anyone know how to resolve this?

**Comment by faceleg** [comment]
Not enough information, please review https://github.com/bower/bower/blob/master/CONTRIBUTING.md#bug-reports and update this issue.

**Comment by gregoryderner** [comment]
This error often occurs
[npm-debug.txt](https://github.com/bower/bower/files/37953/npm-debug.txt)

**Comment by sheerun** [comment]
This is not Bower's error. Please post this issue on npm's issue tracker:

https://github.com/npm/npm

**Comment by imyejin** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

dufma555@naver.com 님께 보내신 메일 <Re: [bower] npm ERR! tar.unpack untar error /home/vagrant/.npm/bower/1.6.5/package.tgz (#1999)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
