### ISSUE TITLE
Repo with space causes ENOTFOUND

### ISSUE THREAD

**Issue by OmgImAlexis** [bower/bower#2003]
I can install [jquery-confirm](https://github.com/myclabs/jquery.confirm) by running `bower install --save jquery-confirm` and it installs fine but as soon as I try to run `bower install` again it gives me an error.

````
bower                        ENOTFOUND Package jQuery Confirm=jquery-confirm not found
````

**Comment by faceleg** [comment]
```
$ bower init
$ bower install jquery-confirm --save
$ bower install
$ rm -rf bower_components
$ bower install
```

That worked as expected for me, anything else going on?

**Comment by OmgImAlexis** [comment]
I had to change the name in the `bower.json` maybe there needs to be a warning that the name on the bower registry and the name in the `bower.json` don't match?

Ref: https://github.com/myclabs/jquery.confirm/pull/53/files

**Comment by sheerun** [comment]
Proper bower name cannot contain spaces: https://github.com/bower/spec/blob/master/json.md#name

**Comment by OmgImAlexis** [comment]
I know but there's no indication to the user that there's an issue.
