### ISSUE TITLE
Add wiki page with instructions for Contributors

### ISSUE THREAD

**Issue by sheerun** [bower/bower#2005]
For example it needs to describe:

1. How to handle open issues
2. How handle requiring feedback from user that added issue
3. How to select issues to review, what too look at, and possible signals in comment (e.g. "looks good to me", or "ship it"
4. ???

@bower/bower-volunteers Could you try to prepare initial version? Any ideas and comments are welcome.

**Comment by faceleg** [comment]
IMHO 4 should be a description of the exact steps required (noting what tests and checks should pass) in order to release a new version based on "ship it" reaching critical threshold.

**Comment by faceleg** [comment]
https://github.com/bower/bower/wiki/Contributor-Guidelines

**Comment by pertrai1** [comment]
@faceleg @sheerun - would it be good to have the steps that a contributor needs to setup development on their local machine to start to contribute?

**Comment by faceleg** [comment]
@pertrai1 sounds good - feel free to add those steps if you get a chance
