### ISSUE TITLE
Update "Bug Reports" section of CONTRUBUTING.md

### ISSUE THREAD

**Issue by sheerun** [bower/bower#2006]
We need to make sure that this section is clear enough for bug reports, because it would be nice to link to it when bug report is not good (for example it is missing a way to reproduce the issue).

@faceleg Could you handle it maybe?

**Comment by pertrai1** [comment]
@sheerun If @faceleg  does not have time I can take this over and lay out proper procedures for reproducing steps for the bug report.

**Comment by faceleg** [comment]
@pertrai1 please be my guest!

**Comment by sheerun** [comment]
@pertrai1 Could you for now create a Wiki page so everyone can contribute?

**Comment by pertrai1** [comment]
@sheerun  I have started the wiki page with the outline of a bug report and will fill in the details of the outline.

**Comment by pertrai1** [comment]
@sheerun - I am going to go ahead and close this issue now that the wiki page has been created. We can continue to evolve the wiki page as I have more content that I need to add to each section of the bug report.
