### ISSUE TITLE
Discuss how we use labels in issue handling

### ISSUE THREAD

**Issue by sheerun** [bower/bower#2007]
- Maybe all labels are not necessary?
- Maybe we need to create extra labels?
- How should we exactly use existing labels?

W need to discuss it and document in somewhere. Wiki?

This issue is related to #2005

**Comment by faceleg** [comment]
This should be added to the wiki IMHO, the Contributing Guidelines document.

Maybe use this issue to discuss what labels, their purpose and how to use them
