### ISSUE TITLE
Plan recruitment path for Bower Contributors

### ISSUE THREAD

**Issue by sheerun** [bower/bower#2008]
We need to discuss the possible roles in Bower organization and clear path for recruiting members of this organization. For now it's more or less as follows:

1. I've created contribution form on http://goo.gl/forms/P1ndzCNoiG
2. The results are gathered in Google Spreadsheet.
3. I invite people from there to "Bower Volunteers" role, that has read access for all of bower repositories and write access for non-critical repositories, like bower.io website.
4. I send following e-mail for all of those people:

> Hey,
> 
> I saw you'd like to contribute to Bower, thank you! For now you are given read access to all of bower repositories and write access to non-essential repositories like bower.io website. If your contributions will show that you clearly know your way around (just enough to avoid breaking things for users), I'd be happy to give you maintainer/owner access.
>
> I hope you understand such security policy. For now, please contribute by commenting on issues, sending PR from your forks, and discussing with other members how to improve development of Bower.
> 
> After you join Bower organisation, I'll invite you to gitter chat where you can meet other contributors and discuss how we can push Bower forward.
> 
> Thank you,
> Adam Stankiewicz 

5. After they join Bower on github I invite them to Gitter Chat where we discuss what's next.

---

Anything to change @bower/bower-volunteers?

We also neext next step and allow Bower member to somehow gain position within Bower organization... Also the docs for Contributors with clear instructions. Please comment on this issue with your ideas. Thank you!

**Comment by pertrai1** [comment]
@sheerun A possible recruiting technique could be to have Labels for the **issues based on a level of knowledge**. Maybe having a label for *beginner*, *intermediate*, *advanced*, etc. could help developers of all experience levels know what they can possibly help with. It could also then make it easier to shoot out links on Twitter for the specific LOE issues.

**Comment by bodieskate** [comment]
@pertrai1 I like this idea. As someone who, just today, applied to be a contributor, I would have absolutely no idea where to start. First, obviously, look through the source. But after that...who knows?

**Comment by pertrai1** [comment]
@sheerun What do you think? Labels based on knowledge so contributors will know where to jump in and start helping out the fastest?

**Comment by sheerun** [comment]
It's a good idea. But who's to judge? :)

**Comment by pertrai1** [comment]
@sheerun It would not be about judging, we would take an issue and give it a label, something like "beginner", "intermediate", "advanced". The label would be based on the level of effort more so than the skills of the person that would be accepting to take it on. 

@bodieskate Do you agree with this?

@bower/bower-volunteers - Does this sound like something that would help people get started tackling issues?

**Comment by riyadhalnur** [comment]
I think it would make more sense to assign an issue to oneself i.e. FIFO

**Comment by sheerun** [comment]
@pertrai1 I'm not agains this feature. In fact I've just created level:beginner level:beginner level:intermediate and level:advanced labels

@bower/bower-volunteers Could you start tagging issues?

**Comment by bodieskate** [comment]
@pertrai1 Yes, completely.

**Comment by pertrai1** [comment]
@sheerun since we now have the tags, can we close this discussion?

**Comment by ceoaliongroo** [comment]
+1

**Comment by sheerun** [comment]
This issue wasn't only about tags

**Comment by pertrai1** [comment]
@sheerun yes that is true but it became all about tags so it should be closed and another discussion topic can be created about new contributors. just my opinion

**Comment by sheerun** [comment]
ok, I'll re-open the same
