### ISSUE TITLE
Bower just won't work in Ubuntu 12.10

### ISSUE THREAD

**Issue by bogdan-kulynych** [bower/bower#201]
Hey, my problem is that running Bower from command line doesn't have any effect whatsoever, neither console output, nor changes to file system, nor error messages, nothing.

I have Ubuntu 12.10 with just-downloaded Node.js v0.8.16 and NPM v1.1.70. Any suggestions?

**Comment by david-alan** [comment]
I had a similar problem.  If you installed node through ```sudo apt-get install node```, you installed a program called node which is used by HAM radio operators. (searching the apt-cache reveals: node - Amateur Packet Radio Node program).  Remove it with ```sudo apt-get remove node``` and then install the correct Node package with ```sudo apt-get install nodejs```.
