### ISSUE TITLE
Add waffle.io PR/Issue activity graphic to readme

### ISSUE THREAD

**Issue by faceleg** [bower/bower#2010]
Maybe it's just me, but I like to see how active collaborators are on a project. 

https://github.com/likeastore/ngDialog#collaboration is an example.

@bower/bower-volunteers thoughts?

**Comment by sheerun** [comment]
Maybe we can setup some statistics :) I don't know the service that provides it, though

**Comment by sheerun** [comment]
Of course we also have closed PR / closed issues stats, but I'm not sure it this stat is that useful.

More likely we'd like to have something like "issue comments count", "labelled issues count", "commit count" or maybe others.

**Comment by riyadhalnur** [comment]
tried out waffle.io. i actually liked the idea behind the product. keeping track of to-dos and etc. on a board makes sense.
