### ISSUE TITLE
Copy-paste pitch email for developers -> managers

### ISSUE THREAD

**Issue by faceleg** [bower/bower#2011]
This would be useful for people who would like to ask their manager to consider supporting Bower in some way.

This would be a generic, formal request letter, with clear MANAGER_NAME, etc tokens to be swapped out by the person wishing to make the request.

**Comment by sheerun** [comment]
Good idea :) I also though about preparing a letter to companies that use Bower in their stack:
http://stackshare.io/search/q=bower

For example to support Bower via bountysource.

**Comment by pertrai1** [comment]
This could also be something that is a callout on the website which would be a landing page of sorts that focus on supporting Bower.

**Comment by thinkxl** [comment]
I was wondering about this a few days ago. I was looking for a good/formal way to ask our company to support the project in any way, because we make money out of it.

Maybe start with a gist or a hackpad to define the content first, then create the landing page/wiki page.

**Comment by pertrai1** [comment]
@faceleg @sheerun Has this stalled or is it still be worked on to come up with the pitch?

**Comment by sheerun** [comment]
I had no time to work on it. I guess @faceleg is stuck with it as well?

**Comment by thinkxl** [comment]
If we create a hackpad document we could progress in small chunks on our spare time.
