### ISSUE TITLE
Support JSON5

### ISSUE THREAD

**Issue by David-Mulder** [bower/bower#2012]
Okay, I have read through the two related issues and I just wanted to propose support for JSON5.

 - It is well defined (as it is directly based upon ES5)
 - Can be placed in a separate file preventing confusion (`bower.json5`)

There has been some debate whether JSON5 should be used for data exchanges between different systems, but considering that `bower.json` files are often edited by hand this is the exact use case where it makes a lot of sense to support JSON5. Another theoretical issue with JSON5 is that it's somewhat slower than low level native parsers, but as `bower` is run separately that shouldn't be an issue either.

**Comment by sheerun** [comment]
Hey. We've already received such requests for like 3+ different file formats. We can't please everyone.

Also tools are depending on bower.json presence. They usually can't read json5 or and ony other format. Bower doesn't use "precompile and publish" model like npm, so you'd get json5 file only. We also need to maintain backward compatibility and this change is not.

**Comment by David-Mulder** [comment]
@sheerun: First of all getting multiple requests for such a feature should maybe be all the more reason to consider that there is something fundamentally wrong with using a file format that doesn't allow comments. Personally I don't care about which format it is, but JSON5 has the advantage of being backwards compatible and well defined. 

Regarding third party tools that read `bower.json`, haven't seen any aside of `bower` itself myself, but no doubt there have to be a couple out there... but it's always been a part of the job with third party tooling to ensure compatibility with the library you provide the tooling for. And considering that most if not all of that tooling will have been written on top of node.js/JS it's a literal 10 minute fix probably.

The hardest part out of all of this would be whether or not to drop comments and the like when using `--save` from the CLI. I would be in favour of just dropping them, but yeah, that would be a harder decision point.

**Comment by sheerun** [comment]
The hardest part is actually authors removing bower.json from repositories and adding bower.json5 instead. It would cause all of old bower versions to stop recognizing such repositories.

**Comment by David-Mulder** [comment]
@sheerun What I have seen in other projects is the introduction of a feature in code sometimes many versions before the feature is publicly and openly announced to mitigate problems like that. Still though, I wouldn't feel bad at all telling my users that they need at least bower version X to install my component if that meant I could deduplicate the optional dependency information<sup>1</sup>. I mean, especially a project like `bower` that notifies of new updates (nice job!) shouldn't have too much of a problem with this.

 <sup>1</sup> Right now I have a somewhat confusing set up where part of the 'information' is in the documentation and part of it is in the config file~

**Comment by sheerun** [comment]
We are on the same page as npm: https://github.com/npm/npm/issues/2412

If you'd like bower to have support for json5 format, please convince npm first.

**Comment by faceleg** [comment]
@David-Mulder this is interesting: https://github.com/npm/npm/issues/2412#issuecomment-5494800

You could write a script that converted your json5 to json :+1: 

I'm going to go ahead and lock this.
