### ISSUE TITLE
Behind a proxy, bower can not download the package.  bower search works fine

### ISSUE THREAD

**Issue by lihongming** [bower/bower#2013]
bower not-cached    https://github.com/angular-ui/ng-grid.git#*
bower resolve       https://github.com/angular-ui/ng-grid.git#*
bower download      https://github.com/angular-ui/ng-grid/archive/v3.0.7.tar.gz
bower retry         Download of https://github.com/angular-ui/ng-grid/archive/v3
.0.7.tar.gz failed with UNABLE_TO_VERIFY_LEAF_SIGNATURE, trying with git..
bower EPERM         EPERM, unlink 'C:\Users\{{MyUsername}}\AppData\Local\Temp\{{MyUsername}}\bower\ng-grid-3280-zXEi7G\archive.tar.gz.a3df070bad968d6619ca79c3224bf409'

Stack trace:
Error: EPERM, unlink 'C:\Users\{{MyUsername}}\AppData\Local\Temp\{{MyUsername}}\bower
\ng-grid-3280-zXEi7G\archive.tar.gz.a3df070bad968d6619ca79c3224bf409'
    at Error (native)

Console trace:
Error
    at StandardRenderer.error (C:\Users\{{MyUsername}}\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:82:37)
    at Logger.<anonymous> (C:\Users\{{MyUsername}}\AppData\Roaming\npm\node_modules\bower\bin\bower:110:22)
    at Logger.emit (events.js:107:17)
    at Logger.emit (C:\Users\{{MyUsername}}\AppData\Roaming\npm\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\{{MyUsername}}\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Users\{{MyUsername}}\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:844:24)
    at C:\Users\{{MyUsername}}\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\{{MyUsername}}\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\{{MyUsername}}\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:788:41)
    at C:\Users\{{MyUsername}}\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:604:44
System info:
Bower version: 1.6.5
Node version: 0.12.2
OS: Windows_NT 6.1.7601 x64

**Comment by lihongming** [comment]
@pertrai1 I have tried all the methods which mentioned at #468, But It did not work for me.

**Comment by lihongming** [comment]
@pertrai1 After I debug bower, I found where is the problem. download.js can not get the "strictSsl" configuration. I think you also had fixed the problem at commit "931b0a89057cf43bdd95ff25d134fd9fb26eb0a1". https://github.com/bower/bower/commit/931b0a89057cf43bdd95ff25d134fd9fb26eb0a1#diff-cc6e4c18bd5d43bea297db7c1cb58af8

But the problem is, When users use npm to install bower, It will download bower 1.6.5 for now which with the bug can not get the "strictSsl" configuration. 

Best Regards,

**Comment by pertrai1** [comment]
@sheerun - can you handle the steps needed to update npm's bower version as stated above - if needed?

**Comment by sheerun** [comment]
@pertrai1 Yes, but we need to fix builds on master before releasing bower.

**Comment by pertrai1** [comment]
@sheerun Ok. Wanted to add you to this as I work on getting up to par and did not want this question lingering out there with no communication.

**Comment by sheerun** [comment]
It should be fine for newest bower
