### ISSUE TITLE
Please update semver

### ISSUE THREAD

**Issue by plynchnlm** [bower/bower#2015]
The current semver in package.json is:
     "semver": "^2.3.0"
which is subject to this [vulnerability](https://nodesecurity.io/advisories/31).

**Comment by sheerun** [comment]
Unfortunately newer semver also breaks compatibility, so we need to put it behind a flag. We already released it once, but had to rollback because of users complains.

**Comment by sheerun** [comment]
So thank you, we know about it, but until we get `--beta` flag implemented, it needs to stay.
