### ISSUE TITLE
Where is bower 1.6.5 tag / release on git?

### ISSUE THREAD

**Issue by gavioto** [bower/bower#2017]
I installed bower 1.6.5 using npm but I didn't found this tag or release on github repository

**Comment by faceleg** [comment]
Hi @gavioto, it's here: https://github.com/bower/bower/tree/v0.6.5

I found it by scrolling down on the "Tags" dropdown on https://github.com/bower/bower

**Comment by sheerun** [comment]
He meant 1.6.5. I forgot to push it after releasing. It's available now.

**Comment by faceleg** [comment]
My bad, thanks @sheerun

**Comment by gavioto** [comment]
Thanks
