### ISSUE TITLE
The version of semver included in package.json is vulnerable to Regular Expression Denial of Service attack

### ISSUE THREAD

**Issue by brian-learningpool** [bower/bower#2018]
I noticed this after running `nsp check` on a project and it flagged that bower was using a vulnerable version of semver.  Here's the link:
https://nodesecurity.io/advisories/31

Perhaps we should move to version 4.3.2 or later?

**Comment by sheerun** [comment]
4.3.2 has breaking changes (it treats prelerelases differently). Someone would need to backport security fixes on semver to old version (pre 4.0.0).

**Comment by toddself** [comment]
Why not treat pre-releases the same as NPM? Consistency is a good thing!

**Comment by sheerun** [comment]
it is, but we're not ready to release next major version of Bower yet.

**Comment by pjmolina** [comment]
Security dependencies [automated analysis] (https://david-dm.org/bower/bower).
- Semver 
- Handlebars

**Comment by sheerun** [comment]
Unfortunately this is low impact security issue and backward compatibility is more important
