### ISSUE TITLE
Add --no-git-tag-version to omit tag+commit when doing version bump

### ISSUE THREAD

**Issue by jfbibeau** [bower/bower#2019]
When running `bower version patch` to increment the version, bower automatically creates a git tag and commit.

npm supports an option, `--no-git-tag-version`, to prevent the git operations (for example, if your CI already takes care of that).

Is it possible to get this option added to `bower version` ? Would you accept a PR?

**Comment by smali-kazmi** [comment]
@jfbibeau you are most welcome to add this feature and generate pull request.

Please follow https://github.com/bower/bower/wiki/Rewrite-architecture

**Comment by jimivdw** [comment]
+1

I was looking for exactly this option just now. Let me know if I can be of any help.

**Comment by sheerun** [comment]
Bower uses only git tags for versions (version field in bower.json is deprecated). 

Because of it, the option you are proposing doesn't make sense for bower.

**Comment by sheerun** [comment]
@smali-kazmi Let's not encourage to make pull requests until we actually agree for a feature. We don't want unnecessary work of community.

**Comment by jfbibeau** [comment]
@sheerun That's a bit short-sighted, no? 

1. Custom resolvers, like the Artifactory resolver (https://github.com/JFrogDev/bower-art-resolver), store and resolve bower artifacts using the bower.json version field.

2. CI tools often handle the version bumping and git tag+committing. In our case, Jenkins handles bumping and committing. It'd be nice to leverage the version manipulation logic you've put in bower without needing to enforce a git commit at the same time - the commit could be done at a later time once tests have passed, etc...

**Comment by sheerun** [comment]
ad 1. I'm pretty sure Artifactory is resolving using git tags. I helped to create this integration.
ad 2. You don't have to create a commit. Creating a tag is enough.

**Comment by jfbibeau** [comment]
I'll buy ya a beer if they're resolving with git tags ;) They're using the version field, for better or for worse...

https://www.jfrog.com/confluence/display/RTF/Bower+Repositories

> A Bower package is a simple tar.gz file which contains your project code as well as a bower.json file describing the package name and version.

**Comment by sheerun** [comment]
When fetching a package, bower overrides `version` field if it doesn't match a tag. Please look at the hidden `.bower.json` file generated by bower in each fetched package. `version` field in `.bower.json` is added even if `version` field in `bower.json` is missing.

**Comment by sheerun** [comment]
@liorhson Is it true? You watch for changes in `version` instead of watching for new git tags?

**Comment by jfbibeau** [comment]
I know that's the case for regular bower resolving, all I'm saying is when we upload a bower .tgz package to artifactory, there is no way for Artifactory to know the version, unless it looks at the bower.json version field. There is no .bower.json uploaded. There is no git repo even storing the code for these artifacts (well, there is, but artifactory is not aware of it, so it can't use tags for resolving).

Cheers.

**Comment by jfbibeau** [comment]
Quote from Artifactory support ticket, from Alex Vainshtein:

> Hi Jean-Francois
> 
> Thank you for contacting us.
> 
> I will try to explain how the Bower integration with Artifactory works. When a tar.gz file is being  deployed to Artifactory’s repository that is marked as Bower repository then Artifactory would try to find the bower.json file in the tar.gz file. Then Artifactory would extract the name and the version of the package from the JSON file and put those values as properties (bower.name and bower.version) on the artifact itself. This would allow the resolution of those packages.

**Comment by jfbibeau** [comment]
@sheerun @liorhson any updates?

**Comment by sheerun** [comment]
@jfbibeau Personally I think the way jFrog interacts with bower doesn't justify adding this command..

This is a use case for very small group of people, and with this flag we're encouraging bad practice of not bumping git tags for broad community of bower users. Can't you handle this case by some custom script or something?

**Comment by brokenalarms** [comment]
I'm coming across the same issue, where I want a single commit incorporating new changes, bower and npm version bumps all in the same commit. I've gotten it down to two commits, but because bower automatically commits and takes away control of those commit options for me, I can't get it into one because I can't specify that the commit should amend...
e.g: 
git stash && bower version patch && git stash pop && npm version patch --no-git-tag-version && git commit -a --amend -m'npm and bower version increment'"

almost does what I want, but then the actual changes are applied after bower has already done the tag. Any other suggestions?
