### ISSUE TITLE
Different permissions for folders downloaded by bower.

### ISSUE THREAD

**Issue by sathishvj** [bower/bower#2023]
```
drwxr-xr-x  10 vj  staff   340B Nov 18 20:07 angular-sanitize/
drwxr-xr-x  11 vj  staff   374B Nov 18 20:07 angular-ui-router/
drwx------  10 vj  staff   340B Nov 18 20:07 animate-css/
drwxr-xr-x  11 vj  staff   374B Nov 18 20:07 d3/
drwx------  11 vj  staff   374B Nov 18 20:07 fontawesome/
drwxr-xr-x  21 vj  staff   714B Nov 18 20:07 html5-boilerplate/
drwx------  12 vj  staff   408B Nov 18 20:07 moment/
drwxr-xr-x  12 vj  staff   408B Nov 18 20:07 moment-timezone/
drwxr-xr-x  18 vj  staff   612B Nov 18 20:07 ng-csv/
drwxr-xr-x  15 vj  staff   510B Nov 18 20:07 ng-file-upload/
drwxr-xr-x  17 vj  staff   578B Nov 18 20:07 ng-table/
drwxr-xr-x   6 vj  staff   204B Nov 18 20:07 nvd3/
drwxr-xr-x   9 vj  staff   306B Nov 18 20:07 underscore/
```
 $ bower -version
1.5.2

Temporary workaround: ```chmod -R 755 folder_name```

**Comment by faceleg** [comment]
I'm not sure what the issue is here?

Note that your bower version is old, current is 1.6.5

**Comment by pritambaral** [comment]
@faceleg I think the issue is the inconsistency in the permissions of the folders downloaded.

**Comment by faceleg** [comment]
Yes but I'm asking if it occurs with the latest version.

**Comment by sathishvj** [comment]
Yes, it is still occurring after a bower update.

⌁ [vj.../app/bower_components] $ ls -l
total 0
drwxr-xr-x  12 vj  staff   408B Nov 22 18:34 angular/
drwxr-xr-x  10 vj  staff   340B Nov 22 18:34 angular-animate/
drwxr-xr-x  10 vj  staff   340B Nov 22 18:34 angular-aria/
drwxr-xr-x  20 vj  staff   680B Nov 22 18:34 angular-material/
drwxr-xr-x  11 vj  staff   374B Nov 22 23:30 angular-ui-router/
drwx------  12 vj  staff   408B Nov 23 01:26 moment/

⌁ [vj.../app/bower_components] $ bower -version
1.6.5

**Comment by faceleg** [comment]
What issues does this cause for you?

**Comment by sathishvj** [comment]
when using nginx and pointing to this directory, it shows an error for lack of permissions on the folder.  Once I do the chmod, it is ok though.  So there is a temporary workaround.

**Comment by faceleg** [comment]
While I understand that this is frustrating, it is generally considered bad practice to server your entire bower_components directory.

Much more secure to manually copy the files you need into `public`, or use a concatenation/minification tool to merge your JS into one file.

**Comment by sathishvj** [comment]
I use the bower components folder only during dev.  I usually refer to cdns on production.  So that's not really a huge concern.  Just that I saw this potential issue and thought I'll report it.

**Comment by faceleg** [comment]
Sure thing, thank you for reporting!

@bower/bower-volunteers if someone would like to claim this and investigate the cause of this inconsistent permission issue?

**Comment by sheerun** [comment]
@bower/bower-volunteers I need someone to confirm we can reproduce it.

**Comment by pertrai1** [comment]
I just tried to reproduce and was **not able** to do so using 1.6.5:

```
drwxr-xr-x 1 pertrai1 pertrai1 340 Nov 22 17:59 angular-sanitize
drwxr-xr-x 1 pertrai1 pertrai1 374 Nov 22 18:02 angular-ui-router
drwxr-xr-x 1 pertrai1 pertrai1 340 Nov 22 18:01 animate.css
drwxr-xr-x 1 pertrai1 pertrai1 374 Nov 22 18:01 d3
drwxr-xr-x 1 pertrai1 pertrai1 374 Nov 22 18:01 font-awesome
drwxr-xr-x 1 pertrai1 pertrai1 612 Nov 22 18:02 html5-boilerplate
drwxr-xr-x 1 pertrai1 pertrai1 408 Nov 22 18:02 moment
drwxr-xr-x 1 pertrai1 pertrai1 408 Nov 22 18:03 moment-timezone
drwxr-xr-x 1 pertrai1 pertrai1 612 Nov 22 18:03 ng-csv
drwxr-xr-x 1 pertrai1 pertrai1 646 Nov 22 18:04 ng-file-upload
drwxr-xr-x 1 pertrai1 pertrai1 748 Nov 22 18:04 ng-table
drwxr-xr-x 1 pertrai1 pertrai1 204 Nov 22 18:04 nvd3
drwxr-xr-x 1 pertrai1 pertrai1 306 Nov 22 18:04 underscore
```
My system info:

```
Operating System: Linux Mint 17.2 Cinnamon 64-bit
Linux Kernel: 3.16.0-38

**Comment by sathishvj** [comment]
My system where I saw the issue.  

[vj:/tmp] $ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F1021

**Comment by ceoaliongroo** [comment]
I'll trying to get deep in the issue... 

@sathishvj , i see you have a group call `staff` could tell us what are the permission of the this group in the project folder?

And just to double check `vj` is actually in the `staff`groups? have root acces?

I like to reproduce your group and user structure

**Comment by sathishvj** [comment]
It seems to be a group on macs.
https://discussions.apple.com/thread/2362727?tstart=0
http://apple.stackexchange.com/questions/130685/understanding-the-staff-user-group

$ dscacheutil -q group -a name staff
name: staff
users: root macports vj _xcsbuildagent _xcscredserver

user 'vj' does not have root access.

**Comment by bodieskate** [comment]
Just out of curiosity, and this may not be relevant at all, but when you initially installed bower did you do so using sudo, i.e. sudo npm install -g bower?

**Comment by ceoaliongroo** [comment]
@sathishvj,  thanks for the links just until now i saw if the os x default group. 

I'm yet looking reproduce the error, without success. Just to discard specific permission issues in your computer, could you verify and repair your computer permissions?  

https://support.apple.com/en-us/HT201560
http://osxdaily.com/2015/01/13/repair-disk-permissions-mac-os-x/

To check the question of @bodieskate: 
```bash
npm list -g bower
```

**Comment by accommodavid** [comment]
I'm on Mac OS X 10.11.2 and also unable to reproduce:

```
drwxr-xr-x  16 accommodavid  staff  544 Nov 25 19:23 ./
drwxr-xr-x   3 accommodavid  staff  102 Nov 25 19:23 ../
drwxr-xr-x  12 accommodavid  staff  408 Nov 25 19:23 angular/
drwxr-xr-x  10 accommodavid  staff  340 Nov 25 19:23 angular-sanitize/
drwxr-xr-x  11 accommodavid  staff  374 Nov 25 19:23 angular-ui-router/
drwxr-xr-x  10 accommodavid  staff  340 Nov 25 19:23 animate.css/
drwxr-xr-x  11 accommodavid  staff  374 Nov 25 19:23 d3/
drwxr-xr-x  11 accommodavid  staff  374 Nov 25 19:23 font-awesome/
drwxr-xr-x  18 accommodavid  staff  612 Nov 25 19:23 html5-boilerplate/
drwxr-xr-x  12 accommodavid  staff  408 Nov 25 19:23 moment/
drwxr-xr-x  12 accommodavid  staff  408 Nov 25 19:23 moment-timezone/
drwxr-xr-x  18 accommodavid  staff  612 Nov 25 19:23 ng-csv/
drwxr-xr-x  19 accommodavid  staff  646 Nov 25 19:23 ng-file-upload/
drwxr-xr-x  22 accommodavid  staff  748 Nov 25 19:23 ng-table/
drwxr-xr-x   6 accommodavid  staff  204 Nov 25 19:23 nvd3/
drwxr-xr-x   9 accommodavid  staff  306 Nov 25 19:23 underscore/
```

**Comment by sathishvj** [comment]
I just deleted my entire bower_components and node_modules and ran it again.  Still the same - those different permission.  
If it's just me, I think we can close it until somebody else reopens it.  I have a workaround anyways.

**Comment by sheerun** [comment]
@sathishvj Thank you for reporting it. We'll reopen as soon as there's someone else with the same issue. For now maybe try `bower cache clean`, `rm -rf bower_components` and reinstall packages.

**Comment by ian-axelrod** [comment]
Hi. I've been having the same issue for a while now. Specifically, some downloaded dependencies have their group mask set to `rw-` while others have it set to `r--`. The latter causes permission denied errors when copying the files to a different directory and then later trying to delete that directory.
