### ISSUE TITLE
[META] Encourage contributions with the `Easy Pick` label

### ISSUE THREAD

**Issue by colinodell** [bower/bower#2029]
Implementing an `Easy Pick` label would help to [increase contributions to Bower](http://bower.io/blog/2015/bower-alive-looking-contributors/).

See http://seld.be/notes/encouraging-contributions-with-the-easy-pick-label

**Comment by waynethompson** [comment]
Good idea. this would be very useful to me right now.

**Comment by cmmata** [comment]
It would be great for people just starting with node like me. That way we can start contributing with less effort.

**Comment by sheerun** [comment]
Hey! For now please register on http://goo.gl/forms/P1ndzCNoiG

We need some time to organize everything :)

**Comment by pertrai1** [comment]
We should keep this open so it stays on the radar that will allow people to see @sheerun answer with the link to register.

@bower/bower-volunteers - please share the register link with others that might be interested in contributing.

**Comment by pertrai1** [comment]
@sheerun @colinodell - I noticed that React has a label for good first bug that they tell those who want to start contributing to pick out. How about a label close to this?

**Comment by colinodell** [comment]
I understand the desire to have potential contributors register, but I worry that it may exclude or alienate people like myself who don't have the time or desire to commit to becoming a regular contributor.

An `Easy Pick` label serves a similar purpose to @pertrai1's suggestion, in that it highlights fairly simple tasks and issues that almost anyone can pick up with minimal experience or guidance.  I believe that adding this label would help encourage contributions from people who:

 - Have never contributed to Bower before
 - Are looking to make a one-time contribution
 - Are looking to make small, infrequent contributions

A similar idea is `up-for-grabs`: http://up-for-grabs.net/  This is also geared to encouraging contributions, but may include tasks which are too difficult for newcomers.

So while I do feel that registration would be great for organizing frequent contributors, I still feel there needs to be something to target newcomers and occasional contributors as well, which is why I feel strongly about the `Easy Pick` concept.

Just my $0.02 :)

**Comment by pertrai1** [comment]
@colinodell Totally agree. For the longest time I was a `roamer` :-) so to speak around GitHub not knowing how to even start contributing. If Bower had a way to get people involved by labelling how to easily get started would be a good first step.

**Comment by faceleg** [comment]
We currently have `level:beginner|intermediate|advanced`

**Comment by pertrai1** [comment]
@faceleg No doubt those will work. Just liked the idea when I saw it about the `First Bug` label that is easy to spot for someone.

**Comment by ceoaliongroo** [comment]
Let's stick it with the `level` tags for the moment

**Comment by pertrai1** [comment]
@ceoaliongroo +1

**Comment by faceleg** [comment]
If there is not already, some mention of the `level` tags might be helpful in the contributing docs

**Comment by pertrai1** [comment]
@faceleg @sheerun I have added the Labels to the Wiki: [https://github.com/bower/bower/wiki/Contributor-Guidelines](https://github.com/bower/bower/wiki/Contributor-Guidelines)

**Comment by sheerun** [comment]
Great :) I can change labels at any time.
