### ISSUE TITLE
Clean up Issues and Pull Requests

### ISSUE THREAD

**Issue by pertrai1** [bower/bower#2032]
@sheerun - Do you think it would be worthwhile to have the older issues and pull requests closed that are more than 2 months ago? The issues that are open at that point don't seem to be active, so they can be closed due to inactivity. Let me know your thoughts.

**Comment by sheerun** [comment]
I think it's not a good idea. We need to review them and close only those that are no longer relevant.

We may set some criteria of closing an issue, though. I open for suggestions :)
