### ISSUE TITLE
Link to Tutorials?

### ISSUE THREAD

**Issue by pertrai1** [bower/bower#2033]
@sheerun would it be good to have a Wiki page that has a posting of tutorials for people to read?

**Comment by faceleg** [comment]
Can't see that it would hurt. Would this not be better if it was included with the site though?

**Comment by sheerun** [comment]
Good idea :) You can create initial article on Wiki and then move it to website maybe.

**Comment by pertrai1** [comment]
@faceleg  @sheerun  Yes I will take lead on this one.
