### ISSUE TITLE
Bower doesn't update bower.json still

### ISSUE THREAD

**Issue by feniixx** [bower/bower#2035]
This might have been asked before, but, why ```bower update --save``` doesn't update bower.json? Or what is the right way to update the dependencies to the latest version?

**Comment by pertrai1** [comment]
@feniixx What I just saw doing a test and reading the API, I needed to update the `bower.json` and then run `bower update`. The steps I took to test:

* I added underscore library from `npm install underscore --save`
* I then changed the version in bower.json to a lesser version
* I then tried to update using `bower update underscore#1.8.3 -F` but did not change `bower.json`
* I went inside of `bower.json` and changed to 1.8.3 and then ran `bower update`
* When I made the change in `bower.json` and then ran `bower update`, the package did change in `bower.jsonz`

I did not see anywhere in the API docs that shows where you can update a package straight from the command line without making a change to the `bower.json` file first.

**Comment by feniixx** [comment]
Isn't it odd @pertrai1 ? Bower should have a command to update all depencies to the latest version:s

**Comment by FrancescoRizzi** [comment]
Hi, I'm fairly new to using bower myself, so I might be wrong, but when you said:
> I then tried to update using bower update underscore#1.8.3 -F

Shouldn't you have included/added the --save flag to expect bower to update the bower.json file? Without it, I think you're saying "force update the underscore library to v.1.8.3 (but don't save this detail to the bower.json file)"

**Comment by pertrai1** [comment]
@FrancescoRizzi Thanks for sharing that. I did not see anything in the docs that said that one needs to use the `--save` flag when doing an update. Is this the case @sheerun ? If it is, this should be added to the docs so one will know that they need to add this when running the `bower update` command.

**Comment by sheerun** [comment]
I really don't know how bower update works now. But I'm pretty sure it doesn't do what it should. It would be nice if someone experimented with it and documented results in Wiki.

**Comment by pertrai1** [comment]
@sheerun I am going to assign this to myself to experiment and document.

**Comment by prometheansacrifice** [comment]
Documenting my observations here. I installed `underscore` using `bower install underscore#1.8.2 --save` and did the following.

* Ran `bower update`. Installs the same version again. No changes with `--save` option.
* Ran `bower install`. Command simply terminates. No re-download or installation from cache

I then manually update the `underscore` version to `1.8.3` in `package,json`.
* Ran `bower update`. Installs the new version of underscore

Installed back `underscore` `1.8.2` version again without touching `bower.json` (So the version is still `1.8.3` in `package.json` but `1.8.2` in `bower_components` folder.)
* Ran `bower install`. Same behavior as bower update - installed the new version.

Given the same state of `bower_components` folder, `install` and `update` commands behave the same.

Ideally, I feel `update` should update the existing components.

**Comment by pertrai1** [comment]
Thank you @prometheansacrifice for the detailed reproduction steps. I am looking into the `update` command and the config options today and tomorrow. Right now it is not setup to update unless there is a change in the .json file that it reads for any changes to the dependencies.

**Comment by pertrai1** [comment]
@sheerun I started working on the `update` command by adding a simple abbreviation `bower u` command. Will continue to look at the command and the options. #2055

**Comment by sheerun** [comment]
@feniixx Does `npm update` update package.json?

**Comment by feniixx** [comment]
Yes, it does @sheerun if there's an `~` before the version of the dependecy, but I'm not sure if `--save` is needed

**Comment by contolini** [comment]
@sheerun @feniixx `npm update` doesn't write anything to package.json unless the [``--save`` flag is passed](https://docs.npmjs.com/cli/update#recording-updates-with-save):

> When you want to update a package and save the new version as the minimum required dependency in package.json, you can use npm update -S or npm update --save

As folks have mentioned here, `bower update` *never* writes to package.json, even if you pass `--save`. This functionality is unexpected and IMO it should mimic npm by updating bower.json if `--save` is specified.

**Comment by contolini** [comment]
@prometheansacrifice Thanks for documenting this. In your scenario, `update` is working as expected.

Similar to npm, bower's `update` respects semver. So if you have underscore pegged at 1.8.2 in bower.json, it won't be updated. However, if you save it as ~1.8.2 (`bower install underscore#~1.8.2 --save`) and then run `bower update`, it will update it to the latest version between 1.8.2 and 1.9.0 (which happens to be 1.8.3).

**Comment by contolini** [comment]
#2062 introduces the `--save` flag to `bower update`.
