### ISSUE TITLE
Failing Test Issue - package-a is not a file or directory

### ISSUE THREAD

**Issue by pertrai1** [bower/bower#2036]
I started to run some tests and ran into this when testing GitHub:

```
26) PackageRepository .fetch should just call the resolver resolve method if 
no appropriate package was found in the resolve cache:
     Uncaught Failed to execute "git ls-remote --tags --heads 
file:///home/pertrai1/Repos/bower/test/assets/package-a", exit code of #128
fatal: '/home/pertrai1/Repos/bower/test/assets/package-a' does not appear to be a git 
repository
fatal: Could not read from remote repository.
```

Is there something that I have not done in the localhost setup?

**Comment by watilde** [comment]
I guess that doesn't seems related setup and it seems that there is an invalid directory/file on test/package-a. Have you tried removing the package-a directory?

```
$ rm -r test/package-a
```

**Comment by paulohp** [comment]
@pertrai1 what's your environment? we have some tests failing on Windows.

Thanks.

**Comment by pertrai1** [comment]
@paulohp my environment that I was testing on is Linux Mint 17.3

**Comment by sheerun** [comment]
@pertrai1 Is it still a thing? What happens when you do fresh clone, npm install, and npm test?

**Comment by pertrai1** [comment]
@sheerun - did a fresh clone, install and test and did work. :+1:
