### ISSUE TITLE
unable to install packages (1.6.5)

### ISSUE THREAD

**Issue by gpolyn** [bower/bower#2039]
(This crosses with [issue 1411](http://github.com/bower/bower/issues/1411) and overlaps with [issue 1171](https://github.com/bower/bower/issues/1171).)

With this context...

Bower version: 1.6.5
Node version: 0.12.2
OS: Darwin 14.3.0 x64

...and executing the following...

`bower install`

...I get the following:

`Error: ENOTDIR, mkdir '/var/folders/h1/bg76tk196rz065b81p1d28ch0000gn/T/gallagherpolyn/bower'`

Yes, I have used `sudo` when installing packages in the past. How do I remediate?

Thanks,

G

**Comment by gpolyn** [comment]
Solved by removing `/var/folders/h1/bg76tk196rz065b81p1d28ch0000gn/T/gallagherpolyn`.

G

**Comment by faceleg** [comment]
Thanks for commenting back here with your resolution :)

**Comment by gpolyn** [comment]
I wish this issue were documented, as it recurs from time to time and only when I use Bower. What is behind the establishment of the troublesome file?
