### ISSUE TITLE
npm shows latest release to be 1.4.2

### ISSUE THREAD

**Issue by scic** [bower/bower#2041]
If i do an npm install bower it installs the old version of 1.4.2. It is also marked as being the latest release on https://www.npmjs.com/package/bower

But the latest release should be 1.6.4 or even 1.6.5?

**Comment by elebumm** [comment]
Try uninstalling bower then reinstalling?

 `npm uninstall -g bower`

 `npm uninstall -g bower`

**Comment by changbenny** [comment]
My bower was version 1.6.5.
However, after uninstalling I try to reinstall, it reinstalls old version 1.4.2.

**Comment by scic** [comment]
@elebumm That didn't help. You should try that then you would get version 1.4.2 aswell ;-) Like @changbenny 

The problem is the following:
![npm_bower](https://cloud.githubusercontent.com/assets/648492/11392477/560653da-935a-11e5-9788-647cfc831ce8.png)

**Comment by paulohp** [comment]
@vladikoff is one of release managers. can you help here @vladikoff ? Thanks

**Comment by vladikoff** [comment]
Ah I see there was an issue with patching old npm releases, working on it ...

**Comment by vladikoff** [comment]
Fixed in 1.6.6

There are several issues with npm here, see https://github.com/npm/npm/issues/6778
The tag APIs is 500ing in several ways as well, so I just published 1.6.6 : 

```
npm info bower
 
{ name: 'bower',
  description: 'The browser package manager',
  'dist-tags': { latest: '1.6.6' },
```

**Comment by sheerun** [comment]
@vladikoff Did you release current master as 1.6.6? It was WIP and there were failing builds..

**Comment by sheerun** [comment]
Ach. I see what you did. Allright :+1:

**Comment by sheerun** [comment]
@vladikoff Actually bower was released in wrong way. You did not follow all the steps from https://github.com/bower/bower/wiki/Releasing-bower (specifically `rm -rf node_modules && npm install --production`)

Because of it Bower has been released without bundledDependencies bundled. Please remember about it next time.

**Comment by vladikoff** [comment]
@sheerun oh didn't know that page existed, sorry! bookmarked it now.

**Comment by vladikoff** [comment]
@sheerun let me know if we should update those

**Comment by sheerun** [comment]
I'll re-release it :)
