### ISSUE TITLE
Create a Bower Style Guide

### ISSUE THREAD

**Issue by AnthonyBobsin** [bower/bower#2043]
With a lot of new volunteers coming on the team, it would be beneficial to have a style guide page that new contributors can reference for specific style conventions used.

**Comment by accommodavid** [comment]
Doesn't Travis already check that using JSHint?

**Comment by pertrai1** [comment]
@AnthonyBobsin I do agree with you on this. Any information that can help get someone up and running is useful. Travis does enforce this, and letting contributors know what it is that is being enforced would be of help. 

+1 from me

**Comment by accommodavid** [comment]
So basically a more human readable version of .jshintrc on the wiki here? I could write up a quick draft for that.

**Comment by AnthonyBobsin** [comment]
Exactly, I'm thinking something similar to the [npm coding style document](https://github.com/npm/npm/blob/master/doc/misc/npm-coding-style.md).

**Comment by AnthonyBobsin** [comment]
Might post this as a different issue after some digging into, but I also noticed that not all jshint preferences are being enforced. For example for `indent: 4`, the file `test/commands/install.js` has indentation set to 2, but no errors are mentioned.

**Comment by pertrai1** [comment]
@AnthonyBobsin - so are you taking the lead on this :-)

**Comment by AnthonyBobsin** [comment]
@pertrai1 sounds good to me :) Will work on implementing node-jscs as well in order to enforce the style guide

**Comment by prometheansacrifice** [comment]
@AnthonyBobsin  @pertrai1 We would use [editorconfig](http://editorconfig.org/) to ensure contributors stick to the style guide. I myself have [set it up](https://github.com/mozilla/pdf.js/pull/6627) for Mozilla's [PDFJS](https://github.com/mozilla/pdf.js)

**Comment by AnthonyBobsin** [comment]
@prometheansacrifice - there is actually already an `.editorconfig` file in the repo. Thanks for pointing that out though, did not notice that before. Will definitely make sure it's up to date with the style guide.

I've implemented [JSCS](http://jscs.info/) which is similar to jshint but strictly related to coding styles. It's great because you can set it so that it automatically corrects code that doesn't adhere to the coding rules we provide. I have a small start to the style guide written up as well, but I would love to get some other people on this with me, as I am fairly new to the project.

**Comment by sheerun** [comment]
@AnthonyBobsin You can create a Wiki page for style guide :) A PR with jscs and style fixes is welcome too.

**Comment by AnthonyBobsin** [comment]
@sheerun - wow, thanks for reminding me, I totally forgot about the Wiki page! Will move the style guide onto a separate Wiki page, then submit the JSCS implementation as a separate PR :+1:

**Comment by prometheansacrifice** [comment]
@AnthonyBobsin I see you've mentioned 4 space indentation. I think 2 would be more suitable against the callback nesting. More opinions on this?

**Comment by AnthonyBobsin** [comment]
@prometheansacrifice - I actually highly prefer 2 as well in most cases. I based a lot of these rules on how the current state of the repo was. As long as everyone is on board though, I would be glad to switch over to 2 space indentation and JSCS will correct the whole repo for us.

**Comment by sheerun** [comment]
I think the current standard for this repo is 4 unfortunately. I like 2 spaces more as well, but we don't want to change every line right now to prevent merge conflicts. So 4 spaces please :)

**Comment by prometheansacrifice** [comment]
There's no maximum allowed line length in the current codebase :(
Could 2 spaces indentation and `max_line_length` be enforced for newer files. With time, existing files could adopt them too.

**Comment by sheerun** [comment]
We can convert everything at once in the future. For now consistent 4 spaces is great.

**Comment by AnthonyBobsin** [comment]
I'll add a `max_line_length` rule as well, couldn't decide yesterday what to set it at. (npm-coding-style)[https://docs.npmjs.com/misc/coding-style] uses 80 characters, but they also use 2 space indentation, so it might be good for us to set it a bit higher. How does 95 sound?

**Comment by sheerun** [comment]
95 sounds good

**Comment by AnthonyBobsin** [comment]
@sheerun - when attempting to set a max line length, there are over 400 errors that can't be automatically fixed. Looking through these, most of them are from `it` strings in specs. Have been trying to implement a way for jscs to ignore these lines but it's more complicated then I thought. Going to submit a PR without the max line length for now then will work on either contributing to jscs to make this process easier, or slowly adjust `it` strings.

**Comment by sheerun** [comment]
Can't we just put `// jscs:disable` at the beginning of each test file?

**Comment by AnthonyBobsin** [comment]
We definitely can. We can even disable just the maxLineLength rule, but I think there might be a more elegant solution.

There are a couple questions at hand here. Should test description strings be that long to begin with? If they should, should we be separating the string onto two lines instead of one long line? Or is it ok as they are, and we should just disable maxLineLength for all test files.

**Comment by sheerun** [comment]
I think they are mostly ok.. descriptive as they need to be.

**Comment by AnthonyBobsin** [comment]
I tried implementing a different jscs config file for all test files so that we don't have to go through and disable the rule manually. This still led to there being over 100 code style errors of lines going over 95 characters. I'm going to leave this how it is for now, and maybe come back to it another time

**Comment by sheerun** [comment]
:+1:

**Comment by AnthonyBobsin** [comment]
Going to close this issue, and will open a new one for implementing a max line length throughout the repo
