### ISSUE TITLE
error after run: npm install -g bower

### ISSUE THREAD

**Issue by douglasdeodato** [bower/bower#2054]
I getting this error after run: npm install -g bower and bower init, actuallly i can't create the bower.json file, but i can install the packages, but why i don't have bower.json file?

$ node -v
v4.1.0

$ grunt --version
grunt-cli v0.1.13
grunt v0.4.5

$ bower -v
1.6.6

$ npm install -g bower
npm WARN installMany abbrev was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany archy was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany bower-config was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany bower-endpoint-parser was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany bower-json was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany bower-logger was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany bower-registry-client was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany cardinal was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany chalk was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany chmodr was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany configstore was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany decompress-zip was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany destroy was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany fs-write-stream-atomic was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany fstream was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany fstream-ignore was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany github was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany glob was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany graceful-fs was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany handlebars was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany inquirer was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany insight was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany is-root was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany junk was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany lockfile was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany lru-cache was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany md5-hex was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany mkdirp was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany mout was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany nopt was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany opn was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany p-throttler was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany promptly was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany q was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany request was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany request-progress was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany retry was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany rimraf was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany semver was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany shell-quote was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany stringify-object was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany tar-fs was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany tmp was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany update-notifier was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany user-home was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
npm WARN installMany which was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
C:\Users\ddeodato\AppData\Roaming\npm\bower -> C:\Users\ddeodato\AppData\Roaming\npm\node_modules\bower\bin\bower
bower@1.6.6 C:\Users\ddeodato\AppData\Roaming\npm\node_modules\bower
├── is-root@1.0.0
├── destroy@1.0.3
├── chmodr@1.0.2
├── junk@1.0.2
├── stringify-object@1.0.1
├── user-home@1.1.1
├── q@1.4.1
├── abbrev@1.0.7
├── bower-endpoint-parser@0.2.2
├── bower-logger@0.2.2
├── opn@1.0.2
├── lockfile@1.0.1
├── archy@1.0.0
├── graceful-fs@3.0.8
├── lru-cache@2.7.3
├── nopt@3.0.6
├── retry@0.6.1
├── tmp@0.0.24
├── semver@2.3.2
├── fs-write-stream-atomic@1.0.4 (graceful-fs@4.1.2)
├── md5-hex@1.1.0 (md5-o-matic@0.1.1)
├── p-throttler@0.1.1 (q@0.9.7)
├── request-progress@0.3.1 (throttleit@0.0.2)
├── shell-quote@1.4.3 (array-filter@0.0.1, array-map@0.0.0, jsonify@0.0.0, array-reduce@0.0.0)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, ansi-styles@2.1.0, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11, graceful-fs@2.0.3)
├── fstream@1.0.8 (inherits@2.0.1, graceful-fs@4.1.2)
├── promptly@0.2.0 (read@1.0.7)
├── which@1.2.0 (is-absolute@0.1.7)
├── bower-registry-client@1.0.0 (async@0.2.10, graceful-fs@4.1.2, request-replay@0.2.0, mkdirp@0.3.5)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── glob@4.5.3 (inherits@2.0.1, once@1.3.3, inflight@1.0.4, minimatch@2.0.10)
├── fstream-ignore@1.0.3 (inherits@2.0.1, minimatch@3.0.0)
├── insight@0.7.0 (object-assign@4.0.1, async@1.5.0, tough-cookie@2.2.1, lodash.debounce@3.1.1, configstore@1.3.0, os-name@1.0.3)
├── rimraf@2.4.4 (glob@5.0.15)
├── bower-config@1.2.2 (graceful-fs@4.1.2, osenv@0.1.3, optimist@0.6.1)
├── github@0.2.4 (mime@1.3.4)
├── tar-fs@1.8.1 (pump@1.0.1, tar-stream@1.3.1)
├── request@2.53.0 (forever-agent@0.5.2, aws-sign2@0.5.0, caseless@0.9.0, tunnel-agent@0.4.1, oauth-sign@0.6.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, tough-cookie@2.2.1, qs@2.3.3, node-uuid@1.4.7, form-data@0.2.0, mime-types@2.0.14, combined-stream@0.0.7, http-signature@0.10.1, bl@0.9.4, hawk@2.3.1)
├── cardinal@0.4.4 (ansicolors@0.2.1, redeyed@0.4.4)
├── decompress-zip@0.1.0 (mkpath@0.1.0, touch@0.0.3, readable-stream@1.1.13, binary@0.3.0)
├── update-notifier@0.3.2 (is-npm@1.0.0, semver-diff@2.1.0, string-length@1.0.1, latest-version@1.0.1)
├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
├── inquirer@0.10.0 (ansi-regex@2.0.0, strip-ansi@3.0.0, figures@1.4.0, ansi-escapes@1.1.0, cli-width@1.1.0, rx-lite@3.1.2, through@2.3.8, cli-cursor@1.0.2, run-async@0.1.0, readline2@1.0.1, lodash@3.10.1)
├── mout@0.11.1
└── configstore@0.3.2 (object-assign@2.1.1, xdg-basedir@1.0.1, uuid@2.0.1, osenv@0.1.3, js-yaml@3.4.5)

other error too:

bower init
bower ENOINT        Register requires an interactive shell

Additional error details:
Note that you can manually force an interactive shell with --config.interactive

**Comment by sheerun** [comment]
I've released new version with fix. Could you check?
