### ISSUE TITLE
Plan recruitment path for Bower Contributors

### ISSUE THREAD

**Issue by sheerun** [bower/bower#2056]
We need to discuss the possible roles in Bower organization and clear path for recruiting members of this organization. For now it's more or less as follows:
1. I've created contribution form on http://goo.gl/forms/P1ndzCNoiG
2. The results are gathered in Google Spreadsheet.
3. I invite people from there to "Bower Volunteers" role, that has read access for all of bower repositories and write access for non-critical repositories, like bower.io website.
4. I send following e-mail for all of those people:

> Hey,
> 
> I saw you'd like to contribute to Bower, thank you! For now you are given read access to all of bower repositories and write access to non-essential repositories like bower.io website. If your contributions will show that you clearly know your way around (just enough to avoid breaking things for users), I'd be happy to give you maintainer/owner access.
> 
> I hope you understand such security policy. For now, please contribute by commenting on issues, sending PR from your forks, and discussing with other members how to improve development of Bower.
> 
> After you join Bower organisation, I'll invite you to gitter chat where you can meet other contributors and discuss how we can push Bower forward.
> 
> Thank you,
> Adam Stankiewicz 
1. After they join Bower on github I invite them to Gitter Chat where we discuss what's next.

---

Anything to change @bower/contributors?

We also neext next step and allow Bower member to somehow gain position within Bower organization... Also the docs for Contributors with clear instructions. Please comment on this issue with your ideas. Thank you!

**Comment by yoannmoinet** [comment]
We could link them to issues tagged for new-comers, like `level:beginner` and such?
And also to the [contributing guide](https://github.com/bower/bower/blob/master/CONTRIBUTING.md).

Maybe make a TL;DR version?

**Comment by aishraj** [comment]
Tagging issues by levels is a great idea as new comers as it would help newcomers looking to get started.

**Comment by jamesxv7** [comment]
@sheerun Apparently there is a large group of contributors and volunteers. I'm a product from you call (invitation). I believe this item may be closed since we can continue any discussion in the Discord Chat Room.
