### ISSUE TITLE
Access denied when installing package

### ISSUE THREAD

**Issue by KeesWoestenenk** [bower/bower#2059]
Bower will be used with Sage for building a Wordpress theme. I installed bower and then in the project theme directory I issued the command bower install. Here I got the folllowing error:
Error: EACCES: permission denied, open '/Users/keeswoestenenk/.config/configstore/bower-github.yml'

You don't have access to this file.

I can't find out how to solve this. I tried logging in as root, but then I get another error: don't give this command as superuser.

**Comment by sheerun** [comment]
There are lot of duplicates for this kind of issue: https://github.com/bower/bower/search?q=EACCES%3A+permission+denied&type=Issues&utf8=%E2%9C%93
