### ISSUE TITLE
Bower 1.6.8 update error

### ISSUE THREAD

**Issue by darkmorpher** [bower/bower#2061]
updating from 1.6.7 gave me this error:
`npm WARN addRemoteGit Error: not found: git`
`npm WARN install Couldn't install optional dependency: not found: git`

**Comment by sheerun** [comment]
What is your platform?

**Comment by darkmorpher** [comment]
Win7 x86

**Comment by sheerun** [comment]
I can't reproduce on Windows 10 x64. @bower/contributors Do you have access to Win7 to reproduce?

**Comment by darkmorpher** [comment]
:octocat: Git broken, reinstalling fixed problem.
