### ISSUE TITLE
Preserve range specifier when using `update --save`?

### ISSUE THREAD

**Issue by contolini** [bower/bower#2065]
The update and install commands don't preserve range specifiers.

Given a bower.json that includes:

``` js
"dependencies": {
  "semantic": "^1.0.0"
}
```

Updating it using `bower update --save semantic` results in:

``` js
"dependencies": {
  "semantic": "~1.12.3"
}
```

Or re-installing it using `bower install --save semantic` results in:

``` js
"dependencies": {
  "semantic": "~2.1.6"
}
```

Notice there are now tildes in bower.json instead of carets. This is because bower defaults to tildes.

This seems to be the correct behavior for `install` because you're effectively saying "trash the component and reinstall it". But should `update` preserve your previous specifier? What should happen if your dep has a complex version range like `>=1.1.0 <2.2.0`?

It's worth noting that npm _doesn't_ preserve range specifiers when using `npm update --save`. It always uses their default, a caret. e.g. `^1.12.3`.

**Comment by olivertappin** [comment]
For those looking for a quick and dirty solution to update all dependencies and save the version numbers to your bower.json file, try the following:

First install the `jq` tool so we can parse jSON via the command line:
```
brew install jq
```

Then the actual one liner:
```
for module in $(jq '.dependencies | keys' bower.json | strings); do; bower install --save $(echo $module | tr -d '",'); done;
```

**Comment by aaroncalderon** [comment]
@olivertappin So, the one liner you provided is a shell command right? Not sure it will work for us windows users. :cry:
