### ISSUE TITLE
Entering `bower search` lists all packages which takes a while

### ISSUE THREAD

**Issue by heinst** [bower/bower#2066]
Entering `bower search` with no entry causes bower to list all packages, this process takes a long time. As an alternative maybe bower should say no search was entered and then ask the user if they would like to list all packages instead of being hung up for about 10 seconds

Resolved by Pull #2074

**Comment by tejgop** [comment]
Good idea, either that or bower should return nothing.

**Comment by eppeters** [comment]
I think it is better to be explicit and let the user know their query failed because it needed more information. Alternatively, we could warn: This will list all (more than X) Bower packages, and will take a while. Continue? y/N

**Comment by tejgop** [comment]
Actually there should be a threshold, like 100 to give that warning.

**Comment by sheerun** [comment]
Any PR that improves this behaviour is welcome

**Comment by heinst** [comment]
Pull request #2074 resolves this issue

**Comment by segrey** [comment]
Hi guys!
Is there now a way to retrieve all bower packages using cli? It's a needed operation for WebStorm Bower integration. Previously, IDE just run `bower search --json` and parsed JSON output.

**Comment by sheerun** [comment]
It turns out the implementation AND tests are wrong... We should display all packages when --json is passed.

**Comment by eppeters** [comment]
I can work on fixing this today if no one else is.

**Comment by segrey** [comment]
Thank you for the fast respond. Yep, `--json` would be a good trigger. Meanwhile, `bower search "" --json` is used as a workaround. FYI, I think I observed several time some text prefix (like some debug output) before JSON body result. Unfortunately, it cannot be reproduced anymore.

**Comment by segrey** [comment]
Thank you for the quick turnaround!
