### ISSUE TITLE
Error installing on windows

### ISSUE THREAD

**Issue by scrapcupcake** [bower/bower#2068]
Get the following errors trying to install on windows w/ Babun shell; I get the same result running from cmd.exe.

npm ERR! git clone <path to git remotes>\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7baaaaefc7e8a6f2fd1f4fdbc8e4b6e7 <path to babun git cache>\git-cache-46304c2d82f00cbe3eac10f17e03bb1a\ac0f001d165564b3763da3252d5bff327c26aea9: Cloning into '<path to babun git cache>\git-cache-46304c2d82f00cbe3eac10f17e03bb1a\ac0f001d165564b3763da3252d5bff327c26aea9'...
npm ERR! git clone <path to git remotes>\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7baaaaefc7e8a6f2fd1f4fdbc8e4b6e7 <path to babun git cache>\git-cache-46304c2d82f00cbe3eac10f17e03bb1a\ac0f001d165564b3763da3252d5bff327c26aea9: fatal: '/cygdrive/c/Users/Scrapcupcake/AppData/Roaming/npm-cache/_git-remotes/git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7baaaaefc7e8a6f2fd1f4fdbc8e4b6e7/<path to git remotes>\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7baaaaefc7e8a6f2fd1f4fdbc8e4b6e7' does not appear to be a git repository
npm ERR! git clone <path to git remotes>\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7baaaaefc7e8a6f2fd1f4fdbc8e4b6e7 <path to babun git cache>\git-cache-46304c2d82f00cbe3eac10f17e03bb1a\ac0f001d165564b3763da3252d5bff327c26aea9: fatal: Could not read from remote repository.
npm ERR! git clone <path to git remotes>\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7baaaaefc7e8a6f2fd1f4fdbc8e4b6e7 <path to babun git cache>\git-cache-46304c2d82f00cbe3eac10f17e03bb1a\ac0f001d165564b3763da3252d5bff327c26aea9:
npm ERR! git clone <path to git remotes>\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7baaaaefc7e8a6f2fd1f4fdbc8e4b6e7 <path to babun git cache>\git-cache-46304c2d82f00cbe3eac10f17e03bb1a\ac0f001d165564b3763da3252d5bff327c26aea9: Please make sure you have the correct access rights
npm ERR! git clone <path to git remotes>\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7baaaaefc7e8a6f2fd1f4fdbc8e4b6e7 <path to babun git cache>\git-cache-46304c2d82f00cbe3eac10f17e03bb1a\ac0f001d165564b3763da3252d5bff327c26aea9: and the repository exists.
npm ERR! git clone <path to git remotes>\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7baaaaefc7e8a6f2fd1f4fdbc8e4b6e7 <path to babun git cache>\git-cache-46304c2d82f00cbe3eac10f17e03bb1a\ac0f001d165564b3763da3252d5bff327c26aea9:
npm ERR! git clone <path to git remotes>\git-https-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-c68fb2e1d07146cb4f3f7be78a227856 <path to babun git cache>\git-cache-cdb5d010d191c3a03685313130ce02ae\ac0f001d165564b3763da3252d5bff327c26aea9: Cloning into '<path to babun git cache>\git-cache-cdb5d010d191c3a03685313130ce02ae\ac0f001d165564b3763da3252d5bff327c26aea9'...
npm ERR! git clone <path to git remotes>\git-https-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-c68fb2e1d07146cb4f3f7be78a227856 <path to babun git cache>\git-cache-cdb5d010d191c3a03685313130ce02ae\ac0f001d165564b3763da3252d5bff327c26aea9: fatal: '/cygdrive/c/Users/Scrapcupcake/AppData/Roaming/npm-cache/_git-remotes/git-https-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-c68fb2e1d07146cb4f3f7be78a227856/<path to git remotes>\git-https-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-c68fb2e1d07146cb4f3f7be78a227856' does not appear to be a git repository
npm ERR! git clone <path to git remotes>\git-https-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-c68fb2e1d07146cb4f3f7be78a227856 <path to babun git cache>\git-cache-cdb5d010d191c3a03685313130ce02ae\ac0f001d165564b3763da3252d5bff327c26aea9: fatal: Could not read from remote repository.
npm ERR! git clone <path to git remotes>\git-https-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-c68fb2e1d07146cb4f3f7be78a227856 <path to babun git cache>\git-cache-cdb5d010d191c3a03685313130ce02ae\ac0f001d165564b3763da3252d5bff327c26aea9:
npm ERR! git clone <path to git remotes>\git-https-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-c68fb2e1d07146cb4f3f7be78a227856 <path to babun git cache>\git-cache-cdb5d010d191c3a03685313130ce02ae\ac0f001d165564b3763da3252d5bff327c26aea9: Please make sure you have the correct access rights
npm ERR! git clone <path to git remotes>\git-https-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-c68fb2e1d07146cb4f3f7be78a227856 <path to babun git cache>\git-cache-cdb5d010d191c3a03685313130ce02ae\ac0f001d165564b3763da3252d5bff327c26aea9: and the repository exists.
npm ERR! git clone <path to git remotes>\git-https-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-c68fb2e1d07146cb4f3f7be78a227856 <path to babun git cache>\git-cache-cdb5d010d191c3a03685313130ce02ae\ac0f001d165564b3763da3252d5bff327c26aea9:
npm ERR! git clone --template=<path to git remotes>\_templates --mirror git@github.com:sheerun/fs-write-stream-atomic.git <path to git remotes>\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7c98389a4aa9e97f1579fc146916c17f: Cloning into bare repository '<path to git remotes>\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7c98389a4aa9e97f1579fc146916c17f'...
npm ERR! git clone --template=<path to git remotes>\_templates --mirror git@github.com:sheerun/fs-write-stream-atomic.git <path to git remotes>\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7c98389a4aa9e97f1579fc146916c17f: Host key verification failed.
npm ERR! git clone --template=<path to git remotes>\_templates --mirror git@github.com:sheerun/fs-write-stream-atomic.git <path to git remotes>\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7c98389a4aa9e97f1579fc146916c17f: fatal: Could not read from remote repository.
npm ERR! git clone --template=<path to git remotes>\_templates --mirror git@github.com:sheerun/fs-write-stream-atomic.git <path to git remotes>\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7c98389a4aa9e97f1579fc146916c17f:
npm ERR! git clone --template=<path to git remotes>\_templates --mirror git@github.com:sheerun/fs-write-stream-atomic.git <path to git remotes>\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7c98389a4aa9e97f1579fc146916c17f: Please make sure you have the correct access rights
npm ERR! git clone --template=<path to git remotes>\_templates --mirror git@github.com:sheerun/fs-write-stream-atomic.git <path to git remotes>\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7c98389a4aa9e97f1579fc146916c17f: and the repository exists.
npm WARN install Couldn't install optional dependency: Command failed: git -c core.longpaths=true clone --template=<path to git remotes>\_templates --mirror git@github.com:sheerun/fs-write-stream-atomic.git <path to git remotes>\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7c98389a4aa9e97f1579fc146916c17f
npm WARN install Cloning into bare repository '<path to git remotes>\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7c98389a4aa9e97f1579fc146916c17f'...
npm WARN install Host key verification failed.
npm WARN install fatal: Could not read from remote repository.
npm WARN install
npm WARN install Please make sure you have the correct access rights
npm WARN install and the repository exists.
npm WARN install

**Comment by tejgop** [comment]
I don't have Windows anymore, but here are some possible problems:
* Git not installed
* Old version of NPM
* Old version of Git
Please provide me some more details, like the versions of your NPM and Git.

**Comment by scrapcupcake** [comment]
git --version 
git version 2.6.2
node -v
v5.1.0
npm -v
3.3.12

npm install uglifyjs succeeds no problem, as does the rest of my individual node packages.

It seems to be failing on building the package for the bower/package.json line, other packages install fine:
 "fs-write-stream-atomic": "sheerun/fs-write-stream-atomic#v1.0.4-fix",

**Comment by scrapcupcake** [comment]
Of note, that repo exists but does not have that tag/branch.

**Comment by scrapcupcake** [comment]
Added in this commit: https://github.com/bower/bower/commit/89286e628b124136d90d69f039ac52beaf7a89eb

**Comment by tejgop** [comment]
Bower installs fine for me, even though I'm using older versions of node and npm. :confused: :question:

**Comment by scrapcupcake** [comment]
Double check that you don't have permissions to that repo that I/the public
don't have?

**Comment by tejgop** [comment]
Testing on another machine, give me some time...

**Comment by tejgop** [comment]
Probably some problem on your side, because I  was able to install it on a fresh VM:

```
$ npm install bower
npm http GET https://registry.npmjs.org/bower
npm http 200 https://registry.npmjs.org/bower
npm http GET https://registry.npmjs.org/bower/-/bower-1.6.8.tgz
npm http 200 https://registry.npmjs.org/bower/-/bower-1.6.8.tgz
bower@1.6.8 node_modules/bower
```

**Comment by tejgop** [comment]
Wait... did you run `npm install bower` or `npm install -g bower`?

**Comment by scrapcupcake** [comment]
I've tried both, same result.

Also:
git clone git@github.com:sheerun/fs-write-stream-atomic.git
~
Cloning into 'fs-write-stream-atomic'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

If I try the HTTPS version, it works, so I think this might be related to
an issue on windows, something not respecting the https+git style of URLs,
going to git/ssh first rather than HTTPS first; I'll investigate further;
It might also just be solved by putting a new (for a new machine I'm on)
ssh key into github, and git will just work for the ssh style url too;
we'll see.

**Comment by tejgop** [comment]
Ok, give that a try and let me know if it works.

**Comment by kosmonaffft** [comment]
I have the same trouble.

PS C:\WINDOWS\system32> npm install -g bower
npm ERR! git clone C:\Users\Anton\AppData\Roaming\npm-cache\_git-remotes\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7baaaaefc7e8a6f2fd1f4fdbc8e4b6e7 C:\Users\Anton\AppData\Local\Temp\npm-8400-795cf4f0\git-cache-4c2b8a05a6085614c5f1dfda639cc782\ac0f001d165564b3763da3252d5bff327c26aea9: Cloning into 'C:\Users\Anton\AppData\Local\Temp\npm-8400-795cf4f0\git-cache-4c2b8a05a6085614c5f1dfda639cc782\ac0f001d165564b3763da3252d5bff327c26aea9'...
npm ERR! git clone C:\Users\Anton\AppData\Roaming\npm-cache\_git-remotes\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7baaaaefc7e8a6f2fd1f4fdbc8e4b6e7 C:\Users\Anton\AppData\Local\Temp\npm-8400-795cf4f0\git-cache-4c2b8a05a6085614c5f1dfda639cc782\ac0f001d165564b3763da3252d5bff327c26aea9: fatal: '/c/Users/Anton/AppData/Roaming/npm-cache/_git-remotes/git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7baaaaefc7e8a6f2fd1f4fdbc8e4b6e7/C:\Users\Anton\AppData\Roaming\npm-cache\_git-remotes\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7baaaaefc7e8a6f2fd1f4fdbc8e4b6e7' does not appear to be a git repository
npm ERR! git clone C:\Users\Anton\AppData\Roaming\npm-cache\_git-remotes\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7baaaaefc7e8a6f2fd1f4fdbc8e4b6e7 C:\Users\Anton\AppData\Local\Temp\npm-8400-795cf4f0\git-cache-4c2b8a05a6085614c5f1dfda639cc782\ac0f001d165564b3763da3252d5bff327c26aea9: fatal: Could not read from remote repository.
npm ERR! git clone C:\Users\Anton\AppData\Roaming\npm-cache\_git-remotes\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7baaaaefc7e8a6f2fd1f4fdbc8e4b6e7 C:\Users\Anton\AppData\Local\Temp\npm-8400-795cf4f0\git-cache-4c2b8a05a6085614c5f1dfda639cc782\ac0f001d165564b3763da3252d5bff327c26aea9:
npm ERR! git clone C:\Users\Anton\AppData\Roaming\npm-cache\_git-remotes\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7baaaaefc7e8a6f2fd1f4fdbc8e4b6e7 C:\Users\Anton\AppData\Local\Temp\npm-8400-795cf4f0\git-cache-4c2b8a05a6085614c5f1dfda639cc782\ac0f001d165564b3763da3252d5bff327c26aea9: Please make sure you have the correct access rights
npm ERR! git clone C:\Users\Anton\AppData\Roaming\npm-cache\_git-remotes\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7baaaaefc7e8a6f2fd1f4fdbc8e4b6e7 C:\Users\Anton\AppData\Local\Temp\npm-8400-795cf4f0\git-cache-4c2b8a05a6085614c5f1dfda639cc782\ac0f001d165564b3763da3252d5bff327c26aea9: and the repository exists.
npm ERR! git clone C:\Users\Anton\AppData\Roaming\npm-cache\_git-remotes\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7baaaaefc7e8a6f2fd1f4fdbc8e4b6e7 C:\Users\Anton\AppData\Local\Temp\npm-8400-795cf4f0\git-cache-4c2b8a05a6085614c5f1dfda639cc782\ac0f001d165564b3763da3252d5bff327c26aea9:
npm ERR! git clone C:\Users\Anton\AppData\Roaming\npm-cache\_git-remotes\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7c98389a4aa9e97f1579fc146916c17f C:\Users\Anton\AppData\Local\Temp\npm-8400-795cf4f0\git-cache-1c6703a83b9c2ad62c764bc49d7975b9\ac0f001d165564b3763da3252d5bff327c26aea9: Cloning into 'C:\Users\Anton\AppData\Local\Temp\npm-8400-795cf4f0\git-cache-1c6703a83b9c2ad62c764bc49d7975b9\ac0f001d165564b3763da3252d5bff327c26aea9'...
npm ERR! git clone C:\Users\Anton\AppData\Roaming\npm-cache\_git-remotes\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7c98389a4aa9e97f1579fc146916c17f C:\Users\Anton\AppData\Local\Temp\npm-8400-795cf4f0\git-cache-1c6703a83b9c2ad62c764bc49d7975b9\ac0f001d165564b3763da3252d5bff327c26aea9: fatal: '/c/Users/Anton/AppData/Roaming/npm-cache/_git-remotes/git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7c98389a4aa9e97f1579fc146916c17f/C:\Users\Anton\AppData\Roaming\npm-cache\_git-remotes\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7c98389a4aa9e97f1579fc146916c17f' does not appear to be a git repository
npm ERR! git clone C:\Users\Anton\AppData\Roaming\npm-cache\_git-remotes\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7c98389a4aa9e97f1579fc146916c17f C:\Users\Anton\AppData\Local\Temp\npm-8400-795cf4f0\git-cache-1c6703a83b9c2ad62c764bc49d7975b9\ac0f001d165564b3763da3252d5bff327c26aea9: fatal: Could not read from remote repository.
npm ERR! git clone C:\Users\Anton\AppData\Roaming\npm-cache\_git-remotes\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7c98389a4aa9e97f1579fc146916c17f C:\Users\Anton\AppData\Local\Temp\npm-8400-795cf4f0\git-cache-1c6703a83b9c2ad62c764bc49d7975b9\ac0f001d165564b3763da3252d5bff327c26aea9:
npm ERR! git clone C:\Users\Anton\AppData\Roaming\npm-cache\_git-remotes\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7c98389a4aa9e97f1579fc146916c17f C:\Users\Anton\AppData\Local\Temp\npm-8400-795cf4f0\git-cache-1c6703a83b9c2ad62c764bc49d7975b9\ac0f001d165564b3763da3252d5bff327c26aea9: Please make sure you have the correct access rights
npm ERR! git clone C:\Users\Anton\AppData\Roaming\npm-cache\_git-remotes\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7c98389a4aa9e97f1579fc146916c17f C:\Users\Anton\AppData\Local\Temp\npm-8400-795cf4f0\git-cache-1c6703a83b9c2ad62c764bc49d7975b9\ac0f001d165564b3763da3252d5bff327c26aea9: and the repository exists.
npm ERR! git clone C:\Users\Anton\AppData\Roaming\npm-cache\_git-remotes\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7c98389a4aa9e97f1579fc146916c17f C:\Users\Anton\AppData\Local\Temp\npm-8400-795cf4f0\git-cache-1c6703a83b9c2ad62c764bc49d7975b9\ac0f001d165564b3763da3252d5bff327c26aea9:
npm WARN install Couldn't install optional dependency: Command failed: git -c core.longpaths=true clone C:\Users\Anton\AppData\Roaming\npm-cache\_git-remotes\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7c98389a4aa9e97f1579fc146916c17f C:\Users\Anton\AppData\Local\Temp\npm-8400-795cf4f0\git-cache-1c6703a83b9c2ad62c764bc49d7975b9\ac0f001d165564b3763da3252d5bff327c26aea9
npm WARN install Cloning into 'C:\Users\Anton\AppData\Local\Temp\npm-8400-795cf4f0\git-cache-1c6703a83b9c2ad62c764bc49d7975b9\ac0f001d165564b3763da3252d5bff327c26aea9'...
npm WARN install fatal: '/c/Users/Anton/AppData/Roaming/npm-cache/_git-remotes/git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7c98389a4aa9e97f1579fc146916c17f/C:\Users\Anton\AppData\Roaming\npm-cache\_git-remotes\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7c98389a4aa9e97f1579fc146916c17f' does not appear to be a git repository
npm WARN install fatal: Could not read from remote repository.
npm WARN install
npm WARN install Please make sure you have the correct access rights
npm WARN install and the repository exists.
npm WARN install
PS C:\WINDOWS\system32>

**Comment by scrapcupcake** [comment]
I solved mine by installing absolute latest git for windows,
3.6.3.windows.1; The version 3.6.2 that's the latest I can get inside of
babun is either out of date or doesn't have the windows patches necessary
to work around this issue; so I have to run my npm commands from inside of
cmd.exe rather than babun for now.

**Comment by shgtkfj** [comment]
Hi,

I have same problem on my windows pc. I'm using git 2.6.3 on msys.
"npm install bower@1.6.7" is OK but "npm install bower@1.6.8" is failed. Is it because of difference of fs-write-stream-atomic entry in the package.json?

* package.json@1.6.8
    "fs-write-stream-atomic": "sheerun/fs-write-stream-atomic#v1.0.4-fix",
* package.json@1.6.7
  "fs-write-stream-atomic": "^1.0.4",

**Comment by kunyan** [comment]
@shgtkfj  I don't have Windows, but can you try to run

```shell
npm install -g shrinkwrap
```

then install 1.6.8 again ?

**Comment by kosmonaffft** [comment]
npm install -g shrinkwrap - installed successfully
npm install -g bower - same error as before

**Comment by kunyan** [comment]
> As of version 1.1.65, you can refer to GitHub urls as just "foo": "user/foo-project".
https://docs.npmjs.com/files/package.json#github-urls

@kosmonaffft could you pls check your npm-config version ?

```shell
➜  ~  npm config -v       
3.3.12

```

**Comment by kosmonaffft** [comment]
PS C:\WINDOWS\system32> npm config -v
3.3.12

**Comment by shgtkfj** [comment]
It seems to depend on git version.
   git 1.9.5 => OK
   git 2.6.3 => NG

**Comment by accommodavid** [comment]
Confirming that with
```cmd
> git --version
git version 2.6.3.windows.1
> npm config -v
3.3.12
```
it does work for me, but I am getting the following:

```cmd
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
```

**Comment by shgtkfj** [comment]
I was using git on msys2. I thought they are same. The following is my result.
   git 2.6.3 on msys2  => NG
   git for windows  2.6.3 => OK

But I also have other error as with accommodavid.

**Comment by tejgop** [comment]
For users who want to resolve this issue **on Mac:**
```
$ brew update
$ brew upgrade node
```

@accommodavid, since you use Windows, I suggest you reinstall git following [these instructions](https://github.com/bower/bower/blob/master/README.md) (scroll down to 'Windows Users').

**Comment by kunyan** [comment]
@accommodavid  I have same version like you, tested on Windows 7. got same error.

you can run below to fix it
```shell
git config --system core.longpaths true
```

It seems cause by Windows path limit, git for windows have some bug
