### ISSUE TITLE
Make quality standards for the website

### ISSUE THREAD

**Issue by tejgop** [bower/bower#2069]
A website for anything is very important. Why? Two reasons.

One:
* A website is what (most) new users visit *before* installing the software.
* They form impressions about the software based on what the website tells them.

And two:
* Users who want to know more about bower visit the website to read the documentation.

(I just expanded on what the [README](https://github.com/bower/bower.github.io/blob/master/README.md) said)

I think we should keep a set of guidelines explaining how you write good documentation.

I have a suggestion for how people should change the website:

Change | What to do
-----------|-----------------
Small changes, such as grammar fixes or adding some documentation | Direct commit
 Bigger changes, such as a website redesign or changing the front page | Pull request, discussion, and then merge

I will add a `CONTRIBUTING.md` file to the `bower/bower.github.io` repo soon that will outline some standards, please give your feedback.

**Comment by pertrai1** [comment]
@tejgop I do agree that there needs to be more concise content that lets a user know exactly what roles there are and how that user can partake in helping out. Your table is a clear way of letting the user know what can be done and how to do it. :+1:

**Comment by sheerun** [comment]
Yes, please :)

**Comment by tejgop** [comment]
Working on it...

**Comment by tejgop** [comment]
Done. [Check it out](https://github.com/bower/bower.github.io/blob/master/CONTRIBUTING.md).

**Comment by sheerun** [comment]
Awesome :)
