### ISSUE TITLE
Pay for developers didn't make sense

### ISSUE THREAD

**Issue by tejgop** [bower/bower#2072]
I got confused because the form for bower contributions asked "how much do you expect per hour?" so I left it blank. Can someone please elaborate on the amount and where the money is coming from and how the developers will get it?

I think pay for developers in an **open source project** doesn't really make sense.

**Comment by sheerun** [comment]
For now there are no sponsors except Artifactory that is willing to sponsor #505

What's wrong with paying for open source work?

**Comment by tejgop** [comment]
If we are sure that the sponsors will stay then there is no problem. The problem arises when everyone expects pay but there are no sponsors/donators. That is how manyopen source projects become paid.

**Comment by tejgop** [comment]
I didn't know there were sponsors, I thought it was 100% random donations, so I guess there is no problem.

**Comment by sheerun** [comment]
Contributing to bower is always voluntary by default. Sponsorship makes sense only for few persons to work on maintaining a project or contributing in continuous way. See Ghost / NPM / neovim / Apache foundations / Mozilla / other open source foundations. I'd like to see it in bower as well.

I think this question can be little misleading, so I removed it from the form. Thank you for feedback.
