### ISSUE TITLE
make global bowerrc path configurable

### ISSUE THREAD

**Issue by ptitgraig** [bower/bower#2073]
Hello.

Unlinke NPM, it would be nice to be able to configure the path to the bowerrc global config file.
For example by using a environment variable:
`export bower_config_globalconfig=<path/to/bowerrc>`.

In addition to this, it would be good also to have a global config file without a "." prefix, since it's by default hidden on LINUX machine - i know you can still type `ls -a` to view all file, however when exploring the file system, it doesn't appear.

What do you think ?

**Comment by sheerun** [comment]
We could support `--config=/path/to/bowerrc` flag that would add additional entry to load.

What should be the merging behavior in such case? Should we use only file passed in `--config` or merge it according to rules defined on http://bower.io/docs/config/ ? Please propose full spec.

I guess that would also solve global config without "." prefix?

**Comment by ptitgraig** [comment]
## use cases for global config file

* company willing to capitalize on a global bower config for all its projects
* developers willing to externalize their bower configuration to avoid having too much config files in their projects directory.

## placement and order

I suggest the addition of a new placement as follow:

The config is obtained by merging multiple configurations by this order of importance:

CLI arguments via --config
Environment variables
Local `.bowerrc` located in the current working directory
All `.bowerrc` files upwards the directory tree
`.bowerrc` file located in user’s home folder (~)
**global config file `bowerrc` file located in &lt;BOWER_INSTALL_DIR/etc/bowerrc&gt; - overridable with the  `bower_config_globalconfig` environment variable**
`.bowerrc` file located in the global folder (/)

**Comment by sheerun** [comment]
Maybe we should put it at the beginning instead of end and use `bower_config` variable or `--config` flag?

**Comment by ptitgraig** [comment]
In my opinion `--config` should remain the top priority because this is a final user harcoded value. The final user should be given the the possibility to override default values defined in files and environmenent variables (i would compare this to the `style=""` in css).

The current `bowerrc` file lookup stratey is great. However it lacks maybe the possibility to define a global config file somewhere on the disk (that the user can define) at a  relatively low level of priority.

I'm not sure making this `bower_config` variable a top priority is the expected behavior for bower users.

**Comment by sheerun** [comment]
According to current "rules" of parsing environment variables and cli arguments, `bower_config` is synonymous  to `--config` cli flag. I don't want to change that :)

**Comment by ptitgraig** [comment]
I'm fine with that. So you suggest to use the global variable `bower_config`, no `bowerrc` global file ?

**Comment by sheerun** [comment]
`bower_config` only points to file to read. like `bower_config=/Users/sheerun/my_awesome_config.json`

**Comment by ptitgraig** [comment]
I set a env variable like: `bower_config=/path/to/my/global/bower/bowerrc` on my linux.
It's not taken into account. Am I using it correctly ?
The content of my bowerrc looks like:
```json
{
  "directory": "bower_components",
  "analytics": false,
  "registry": "http://myregistry/",
  "resolvers": [
    "some-resolver"
  ]
}
```

**Comment by ptitgraig** [comment]
@sheerun I am not sure this feature is implemented. Is it ? If so we shall close this discussion since it answers the need, else is it on the road ?

**Comment by sheerun** [comment]
It is not implemented yet. We're just discussing it.

**Comment by ptitgraig** [comment]
Got it. I'm not aware of how decision is made among bower community but I would be happy to be noticed when the decision is made.

**Comment by sheerun** [comment]
The decision is made :) I'll accept a pull-request implementing it.

**Comment by ptitgraig** [comment]
Great, I'll work on it.

**Comment by ptitgraig** [comment]
Closing this issue. Since it's accepted we'll discuss about it more in Discord.

**Comment by sheerun** [comment]
No need to close such issues. Discord is not a replacement for github issues

**Comment by Nate-Wilkins** [comment]
What is the current state of this?

**Comment by evanjbowling** [comment]
@Nate-Wilkins I'm not sure about the current state, but after reading over the history I have some comments:

Is this truly a replacement for the global config? or would the global folder (/) still be searched? The current docs list configurations being loaded in the following order:

* CLI arguments via --config
* Environment variables
* Local .bowerrc located in the current working directory
* All .bowerrc files upwards the directory tree
* .bowerrc file located in user’s home folder (~)
* .bowerrc file located in the global folder (/)

Once this is done, I can help update the bower docs

**Comment by evanjbowling** [comment]
Actually, I may have a better question. What if we had the new `bower_config` env variable and a specific bower env variable?

export bower_config=/etc/.bowerrc

`/etc/.bowerrc`

    {
      "directory": "bower_components"
    }

export bower_directory='components'

Which value should get priority? I would guess we read the `bower_config` first and then override it with `bower_directory`.

**Comment by sheerun** [comment]
env variables have priority

**Comment by sheerun** [comment]
Unfortunately Bower no longer accepts new features and is in maintenance mode
