### ISSUE TITLE
Improve current style guide

### ISSUE THREAD

**Issue by thinkxl** [bower/bower#2077]
I want to suggest some improvements in the current [Style Guide](https://github.com/bower/bower/wiki/Style-Guide). The goal is to make it more clear, readable, and easy to expand in the future (if needed).

Before to re-write the entire document I wanted to show you my proposal. The biggest change is the one focusing on following a commenting convention, here is the link:

https://gist.github.com/thinkxl/aa1ec1295d72c2ace928

The Comments sections intends to adopt a "standard" for documenting code. New contributors will find easy to understand what functions do.

Most of the edits are borrowed/stolen from [AirBnB](https://github.com/airbnb/javascript/tree/master/es5) and [idiomatic.js](https://github.com/rwaldron/idiomatic.js/) guides.

Feedback appreciated.

**Comment by jahan-addison** [comment]
:+1:

**Comment by contolini** [comment]
Looks great @thinkxl. :+1: 

In your style guide you recommend naming anonymous functions and using JSDoc-style comments. The current codebase does neither of these things but they're both good practice so I support including them.

**Comment by accommodavid** [comment]
:+1: this is some seriously good work

**Comment by thinkxl** [comment]
I will go ahead and modify the wiki page, if we change our minds we can go back in the revisions.

Thanks for your feedback!

**Comment by thinkxl** [comment]
https://github.com/bower/bower/wiki/Style-Guide

Done.
