### ISSUE TITLE
How to get previous version of bower

### ISSUE THREAD

**Issue by akhiruddin** [bower/bower#2079]
Samsung@Dean MINGW64 ~
$ npm install -g bower
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:818:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:11)
npm WARN addRemoteGit     at emitOne (events.js:77:13)
npm WARN addRemoteGit     at Socket.emit (events.js:169:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:469:12)
npm WARN addRemoteGit  sheerun/fs-write-stream-atomic#v1.0.4-fix resetting remote C:\Users\Samsung\AppData\Roaming\npm-cache\_git-remotes\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7baaaaefc7e8a6f2fd1f4fdbc8e4b6e7 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\Samsung\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/sheerun/fs-write-stream-atomic.git C:\Users\Samsung\AppData\Roaming\npm-cache\_git-remotes\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7baaaaefc7e8a6f2fd1f4fdbc8e4b6e7: Cloning into bare repository 'C:\Users\Samsung\AppData\Roaming\npm-cache\_git-remotes\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7baaaaefc7e8a6f2fd1f4fdbc8e4b6e7'...
npm ERR! git clone --template=C:\Users\Samsung\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/sheerun/fs-write-stream-atomic.git C:\Users\Samsung\AppData\Roaming\npm-cache\_git-remotes\git-github-com-sheerun-fs-write-stream-atomic-git-v1-0-4-fix-7baaaaefc7e8a6f2fd1f4fdbc8e4b6e7: fatal: read error: Invalid argument
C:\Users\Samsung\AppData\Roaming\npm\bower -> C:\Users\Samsung\AppData\Roaming\npm\node_modules\bower\bin\bower
C:\Users\Samsung\AppData\Roaming\npm
└─┬ bower@1.6.8
  ├─┬ bower-config@1.2.3
  │ └── graceful-fs@4.1.2
  ├─┬ bower-registry-client@1.0.0
  │ └── graceful-fs@4.1.2
  ├─┬ fs-write-stream-atomic@1.0.4-fix  (git+https://github.com/sheerun/fs-write-stream-atomic.git#ac0f001d165564b3763da3252d5bff327c26aea9)
  │ └── graceful-fs@4.1.2
  ├─┬ fstream@1.0.8
  │ └── graceful-fs@4.1.2
  └─┬ insight@0.7.0
    └─┬ configstore@1.3.0
      └── graceful-fs@4.1.2

npm WARN EBUNDLEOVERRIDE Replacing bundled node_modules\bower\node_modules\fs-write-stream-atomic with new installed version

this is what happen when i tried to install latest bower on my laptop.
i use windows 7, and this is from Git Bash.

**Comment by sheerun** [comment]
I've released bower 1.6.9 that should fix this problem
