### ISSUE TITLE
Gzipped files are producing empty folders or not getting extracted

### ISSUE THREAD

**Issue by accommodavid** [bower/bower#2090]
Tested on OS X 10.11 and Windows 10, using Bower 1.7.0.

When running `bower install --save path/to/agzipped.js.gz`, bower either creates an empty folder with the name of the file (Mac) or creates a folder but does not extract the file, resulting in `bower_components\package\index.gz`. (Windows) The same thing happens when the dependency is manually added to `bower.json` and `bower install` is run.

- The behavior is always the same, including the difference between both platforms
- It happens with local files as well (`bower install --save ../a-nice-file.js.gz`)

The issue where `index.gz` is created was already mentioned in #1004, the issue where the file is extracted, then treated as a folder is not documented anywhere. At any rate, Bower does not seem to handle purely gzipped files –as oppossed to tar.gz– very well.

I am writing tests for tar extraction right now, after that I can look into why gz extraction is failing, or maybe someone else wants to look into it?

**Comment by sheerun** [comment]
We need to check behavior of previous releases. Was it always broken?
