### ISSUE TITLE
Better control over destination of direct assets

### ISSUE THREAD

**Issue by aleemb** [bower/bower#2095]
It would be lovely if Bower could support arrays for dependency values, such as,

```
  "devDependencies": {
    "foo": [
        "https://raw.githubusercontent.com/foo/bar/63eacb484a97a17a9dfde07cc7033119b00bd176/public/assets/css/foo.css",
        "https://raw.githubusercontent.com/foo/bar/63eacb484a97a17a9dfde07cc7033119b00bd176/public/assets/js/foo.js"
       ]
  }
```

This would mean that both assets end up in the same folder. Currently I cannot figure out a way to put both those assets in the same folder. I believe this is a legitimate use-case and would allow for organising assets from unpackaged sources.

Alternatively (or additionally), something along the following lines would also be useful,

```
  "devDependencies": {
    "foo/css": "https://raw.githubusercontent.com/foo/bar/63eacb484a97a17a9dfde07cc7033119b00bd176/public/assets/css/foo.css",
    "foo/js": "https://raw.githubusercontent.com/foo/bar/63eacb484a97a17a9dfde07cc7033119b00bd176/public/assets/js/foo.js"
  }
```

**Comment by sheerun** [comment]
You can change directory destination with 

```
"foo=bar": "https://raw.githubusercontent.com/foo/bar/63eacb484a97a17a9dfde07cc7033119b00bd176/public/assets/css/foo.css"
```

Bower doesn't support sub-directories in bower_components, nor it will be supporting them, sorry.

**Comment by aleemb** [comment]
@sheerun thanks for the tip, I tried that but it doesn't work as proposed. Could you please verify if this is a missing feature or if it is indeed something that I am not doing right:

```
  "devDependencies": {
    "laravel.com-docs-css": "https://raw.githubusercontent.com/laravel/laravel.com/a4a97a17a63eacb49dfde07cc7033119b00bd176/public/assets/css/laravel.css",
    "laravel.com-docs-js=foo": "https://raw.githubusercontent.com/laravel/laravel.com/a4a97a17a63eacb49dfde07cc7033119b00bd176/public/assets/js/laravel.js"
  }
```

Error:
```
bower laravel.com-docs-js#*  ENOTFOUND Package foo=https://raw.githubusercontent.com/laravel/laravel.com/a4a97a17a63eacb49dfde07cc7033119b00bd176/public/assets/js/laravel.js not found
```

Thanks very much!

**Comment by aleemb** [comment]
@sheerun for clarification, I want both the css and js files to end up in the same folder. This will allow me to grab assets much more easily.

I think it's a very useful feature to have.

Not everyone has published a bower package but the simplicity and easy of bower should not be wasted on them. This just allows me to specify that I want to take all these CSS and JS files and put them in my specified folder.

**Comment by sheerun** [comment]
It would be, but reusing the same folder and nested directories are against whole internal architecture of bower. We simply can't implement it in reasonable time.

You can use `postinstall` hook to move assets to appropriate places, though.

**Comment by aleemb** [comment]
Makes sense, fair enough. Good idea on the `postinstall` hook tip, will go that route.
