### ISSUE TITLE
dependencies is ignored in bower list --json meta if processed.

### ISSUE THREAD

**Issue by pwang2** [bower/bower#2098]
This is an inquiry to confirm if this is a bug or in-design behavior. 

``` javascript
Project.prototype._restoreNode = function (node, flattened, jsonKey, processed) {
    var deps;
    node.dependencies = node.dependencies || {};
    node.dependants = node.dependants || {};
    processed = processed || {};

    // Only process deps that are not yet processed
    deps = mout.object.filter(node.pkgMeta[jsonKey], function (value, key) {
        return !processed[node.name + ':' + key];
    });

    mout.object.forOwn(deps,...);
```

If we install jquery-cookie with foundation(foundation has jquery-cookie as dependency), when running bower list --json, in the output(https://gist.github.com/pwang2/79c716ef79d319b31022), jquery-cookie under foundation's dependencies has dependencies: {}; actually it should be 

```
{
    "jquery":{
       "pkgMeta":{},
       "dependencies":{}
    }
}
```

I think it is kinda reasonable to have a full meta file format with all dependencies. If you agree this is a bug, I could send PR to fix that. I was doing some work with bower list meta information(see https://github.com/pwang2/brower), this will also require me to add a processed cache to get a full self-contain meta structure without ignore.  Just want to make it more reasonable for all cases. 

Thanks

**Comment by pwang2** [comment]
@sheerun Can I bother you with this?

**Comment by sheerun** [comment]
I guess it is to prevent duplication or something? I don't think it's by design in this case, it looks wrong. If you could fix it, but also make sure it works with circular dependencies, I think we could merge fix to Bower.

**Comment by sheerun** [comment]
@pwang2 Thank you for reporting it, by the way :)

**Comment by pwang2** [comment]
@sheerun , You are absolutely right.  Circular is the problem here to solve.  

The current implementation may be a shortcut to solve the problem. But It's unexpectedly breaks non circular case like what I mentioned above.  

What we could improve is to create a circular cache to break the ring ONLY when needed.  If a dependency is identified also on existing dependency path(aka a pkg is the descendant of itself), keep the fact in object representation but break the ring when we need to make a JSON serialization.  

I will do some a further review on the user case in current code and plan to make a PR.

**Comment by pwang2** [comment]
@sheerun , could you brief me the de-circular strategy in bower?  

Even in the bundler case like webpack, source code of circulated dependencies need to be arranged to [certain pattern](http://benjamn.github.io/empirenode-2015/#/14)  to work.  in the &lt;script&gt; tag loading case, it is definitely not working at all.  

so my extended question is is it valuable to push this to a package manager like bower here?

**Comment by sheerun** [comment]
I never really went into de-circular strategy in Bower. I'd be glad if someone experimented with it and documented it.
