### ISSUE TITLE
I unregister a package, but it still can be lookup.

### ISSUE THREAD

**Issue by Sspeed5cm** [bower/bower#2104]
I unregister a package first:
```cmd
E:\bk\webpack>bower unregister learn-bower
? You are about to remove component "learn-bower" from the bower registry (https://bower.herokuapp.com). It is generally considered bad behavior to remove versions of a library that others are dependi
ng on. Are you really sure? Yes
bower unregister    learn-bower
bower Package unregistered      learn-bower
```

and, use `bower lookup` to look for it

```cmd
E:\bk\webpack>bower lookup learn-bower
learn-bower git://github.com/Sspeed5cm/learn_bower.git
```

The package is still can be lookup.

but,I clean the cache:

```cmd
E:\bk\webpack>bower cache clean
```

and look for it again:

```cmd
E:\bk\webpack>bower lookup learn-bower
Package not found.
```
use `bower info`
```cmd
E:\bk\webpack>bower info learn-bower
bower                        ENOTFOUND Package learn-bower not found
```

it works.

Why is that? Thanks for helping me!

**Comment by BenMann** [comment]
That's default behavior (correct me if I'm wrong, y'all). As you've already resolved/installed the package once Bower keeps it in the cache, so following installs can be much quicker. That is also why it is generally adviced to clear the cache after unregistering a package. See [bower/registry](https://github.com/bower/registry#unregister-package) for more or if you need further help.

**Comment by contolini** [comment]
:+1: The registry client [checks your local cache](https://github.com/bower/registry-client/blob/master/lib/lookup.js#L28-L50) unless `--force` is passed.

**Comment by Sspeed5cm** [comment]
@BenMann Thanks. Yes, if you install a package, Bower will cache the package. The cache path for example: `C:\Users\dulin\AppData\Local\bower\cache\packages`。But I think register a package or unregister a package should have no relationship with cache.(Forgive me, my English is not well).
In my head, I think `register `,`unregister`,`lookup`,`search`,'info' CLIs are all online operate.

@contolini  Thanks. Read the `bower lookup` CLI's source code. I know what's going on.
