### ISSUE TITLE
cache cannot be used by several user from the same group (unix)

### ISSUE THREAD

**Issue by ptitgraig** [bower/bower#2106]
Hello.

__The context:__
Bower version: 1.5.3
Node version: 0.12.7
OS: Linux 2.6.32-358.23.2.el6.x86_64 x64

Several users uses the machine. All of them use Bower. They share a same cache location define in a global bowerrc with `storage.package: "path/to/packages/"`

__The issue:__
Let's say we have 2 user `userA` and `userB` on a Linux machine belonging to the same group `groupUser`
When `userA` checkouts package from a registry, some cache is created in package directory.
For example: `/path/to/packages/fe4399be35b0d38839088d89f8bb5d11/3.3.5` (this is bootstrap)

When `userB` does the same, it gets the following error:
```sh
Stack trace:
Error: EACCES, rmdir '/path/to/packages/fe4399be35b0d38839088d89f8bb5d11/3.3.5'
    at Error (native)
```

It occurs that the 3.3.5 is only writeable by the owner (.i.e `userA`). Users from same groups are not allowed.
```sh
drwx------ 7 userA userGroup 4096 Dec 15 16:11 3.3.5/
```

My question: how can several users from the same group share the same cache location?

Regards.

**Comment by BenMann** [comment]
Did you `sudo npm install -g bower`? Not sure this helps, but I'd give it a shot, as this is clearly caused by lack of permissions. Maybe installing globally will change group permissions (this is just a guess, as I have no way to replicate righ now). Alternatively.. can you manually set the permissions for the group on the cache folder?

**Comment by Utsav2** [comment]
I think every mkdir call in bower could have a permission of 0765, which can be specified in [mkdir's second parameter](https://github.com/substack/node-mkdirp). The default seems to be 0755, which doesn't give write permission. This should make the bower cache usable by all users in the same group. IIRC, file permissions don't inherit from parent directory or anything, so changing the code of bower seems like the only way that does it automatically. 

You could run a bash script to do a `chmod 765 <dirname>` for every directory in the cache.

**Comment by ptitgraig** [comment]
Thanks for your replies.
@BenMann i did indeed install bower globally. I could of course set the permissions for the group but i'm not sure this is the desired behavior and i'm not willing to run it everytime a new package is installed.
@Utsav2 I could for sure do a batch to `chmod 765 <dirname>` but i'm wondering why I should do this. So basically my question is : is my use case not handle by bower ? Should it be handled ?
Regards.

**Comment by Utsav2** [comment]
Yeah, I don't think it's handled, and there'll have to be a code change to do it as I mentioned before. 

I'm not sure it should be handled by default, there can be security concerns (anyone in the same group could potentially tamper with packages).

**Comment by BenMann** [comment]
Yep, was going to raise an eyebrow on securtiy as well. For now you could probably handle this with a post-install hook.. so it's not impossible. Having said that, I'm not sure we should actually change the default way bower sets permissions. I'd consider this an individual case which isn't needed that often.

**Comment by ptitgraig** [comment]
Ok Thanks. So the `storage.package` option does not make sense for a shared bowerrc. Shall we update the doc ?

**Comment by sheerun** [comment]
@ptitgraig Bower does the same as npm - `0777 & ~process.umask()` that is usually 644 for files and 755 for directories, because `umask` is usually 022.

What is the umask of your user account and root account?

**Comment by ptitgraig** [comment]
both userA and userB account have `0002`.
root account has `0077` (but i'm not supposed to be root on the machine :p)

**Comment by sheerun** [comment]
You have your answer. umask of 0077 means any files created have 700 permission by default.

I'm not sure if we should override this behavior. I wonder what npm does.

**Comment by ptitgraig** [comment]
Oh ok thanks for this piece of knowlegde! So If I understand bower runs as root even when I run it with a user?

**Comment by pertrai1** [comment]
@ptitgraig - Once you feel  you have received the information you need from the thread, please close and comment. If you still have answers you need, feel free to keep open

**Comment by sheerun** [comment]
@ptitgraig Bower doesn't change user for running. Please use StackOverflow for support questions.
