### ISSUE TITLE
1.7.1 fails to extract files

### ISSUE THREAD

**Issue by pyalxx** [bower/bower#2107]
I have a project with such bower file:

```json
{
    "name": "myApp",
    "version": "0.1.0",
    "dependencies": {
        "angular": "~1.4.8",
        "angular-animate": "~1.4.6",
        "angular-google-analytics": "~0.0.15",
        "angular-google-places-autocomplete": "~0.2.7",
        "angular-local-storage": "~0.2.1",
        "angular-moment": "~0.9.0",
        "angular-sanitize": "^1.3.0",
        "angular-touch": "~1.4.2",
        "angular-validation": "~1.2.6",
        "angularjs-geolocation": "~0.1.1",
        "bootstrap": "^3.2.0",
        "fastclick": "~1.0.6",
        "parse-angular-patch": "*",
        "parse-js-sdk": "~1.4.2",
        "ui-router-extras": "~0.0.13",
        "angular-file-model": "~0.3.1",
        "angular-ui-mask": "~1.5.1",
        "ngCordova": "~0.1.22-alpha",
        "angular-scroll": "~0.7.3",
        "angular-google-maps": "~2.2.1",
        "angular-ui-router": "~0.2.15"
    },
    "appPath": "app",
    "license": "MIT",
    "ignore": [
        "**/.*",
        "node_modules",
        "bower_components",
        "test",
        "tests"
    ]
}
```
I've upgraded bower today to 1.7.1. After I run a new clean install using

```bash
bower cache clean
bower install
```

My grunt-bower-concat task broke with main files error. I've noticed that some directories in bower_components folder contained unpacked .tar.gz files.

Downgrading to 1.7.0 solved the problem.

**Comment by kunyan** [comment]
Which version of bower you used before upgraded ?

I try to use 1.7.0 upgrade to 1.7.1, but didn't reproduce

**Comment by pyalxx** [comment]
I used version 1.7.0 which is working fine. I've updated bower today to 1.7.1 and made fresh install - everything worked fine. Maybe it is somehow related to servers, because I had it reproducing on three different systems yesterday.

**Comment by BenMann** [comment]
Sounds like the bug fixed itself..
I'll close this in favor of https://github.com/bower/bower/issues/2101, as it might be related! Please comment if the problem persists or anything and I'll re-open.

**Comment by pyalxx** [comment]
Yes, seems to be related. Thanks for a quick reaction!
