### ISSUE TITLE
Random packages corruption

### ISSUE THREAD

**Issue by vchekan** [bower/bower#2108]
I am experiencing random bower package corruption (not all files are present) . I clean the cache, reinstall, and than another package(s) get corrupt. I can see that corrupt packages are in the cache. I suspect glitches in github, but does bower have any checks that archive stream did not end prematurely? Maybe it makes more sense to download .zip files, at least they have crc32 checks in zip format itself?

**Comment by BenMann** [comment]
There is a check [here](https://github.com/bower/bower/blob/cdf45239f4853ce7d9ccd6b146ea84194bcf52fa/lib/util/download.js) pretty much at the bottom.. it's not very neat though. We're generally experienceing problems with extracting zip files lately, not sure if that's related though!

**Comment by vchekan** [comment]
Than I'm at loss. From "-V" logs I saw tar.gz downloads. I did not capture tcpdump because it is https. 
Closing #2108 as a dup: symptoms sounds exactly like my case. If I find any new info, I'll report to #2101.
