### ISSUE TITLE
Bower install fails to install full packages

### ISSUE THREAD

**Issue by GarrettQ1** [bower/bower#2110]
After upgrading from 1.6.9 to 1.7 I did bower cache clean then bower install. Modules were failing with syntax errors. After looking at the module that was failing I noticed the file just ended at the line of the error. After downgrading to 1.6.9 this quit happening

**Comment by GarrettQ1** [comment]
this is happening out of nowhere. closing for now to determine if its bower or my system.

**Comment by BenMann** [comment]
Are the modules in question retrieved from zip archives? In that case: related — https://github.com/bower/bower/issues/2101 Any new info should go into that issue, thanks. :wink:
