### ISSUE TITLE
Two different projects using same name with different case

### ISSUE THREAD

**Issue by OmgImAlexis** [bower/bower#2111]
https://github.com/centralway/chart.js and https://github.com/nnnick/Chart.js are both on bower, one using a capital `C` and other not.

Is there a reason bower allows/allowed this?

**Comment by sheerun** [comment]
No specific reason. It was mistake to allow it but is too late to remove it to break backward compatibility.

**Comment by OmgImAlexis** [comment]
@sheerun could there not be a warning like what NPM did to ask the user to notify the owner to change their name to lowercase only and disallow any new names to be registered in anything but lowercase? This would basically fix this issue.

**Comment by sheerun** [comment]
We had this enabled for a while, but there was an issue with re-registering packages that were camelCased. Until this issue is resolved, we can only show a warning, but it's not implemented yet #1014 

A PR is always welcome.
