### ISSUE TITLE
`bower install` seems to ignore `--log-level`

### ISSUE THREAD

**Issue by walgitrus** [bower/bower#2112]
`--quiet` or `--silent` greatly reduce the output, but `--log-level=warn` does not

this is with bower 1.7.1

**Comment by ptitgraig** [comment]
I'm not sure what you mean.  `--log-level-warn`  is supposed to display ast least warning messages. What do you actually get ?

**Comment by pertrai1** [comment]
@walgitrus - as @ptitgraig asked, please add the message you received and information about your operating system. Thank you

**Comment by hdgarrood** [comment]
Same here - ubuntu 14.04, bower 1.7.1. I can't find any `--log-level` option that seems to have any effect on bower install. For me, in a directory with a bower.json with dependencies and no `bower_components` existing already, the following all produce the exact same amount of output:

```
$ bower install
$ bower install --log-level=debug
$ bower install --log-level=error
$ bower install --log-level=nonsense
```

In the same vein, it would be nice if the last variant failed (as it seems it should).

Also, kind of related:

```
$ bower install --log-level error
```

will try to install the package `error`. This definitely seems wrong - `--log-level` without an argument seems like it ought to fail.

Also, I think the valid log levels should be documented, or at least printed in the error that you should get when you specify an invalid log level.

**Comment by sheerun** [comment]
It's a documentation issue. log-level is actually loglevel

Thank you for reporting.

**Comment by hdgarrood** [comment]
Ah, I see, thanks. Perhaps it might be worth erroring on unrecognised options, then?

**Comment by sheerun** [comment]
I think it would be acceptable, even it is breaking change
