### ISSUE TITLE
Quicker Defect Resolution?

### ISSUE THREAD

**Issue by pertrai1** [bower/bower#2117]
I want to propose adding this to the wiki or somewhere that this might help people to know of an approach to helping the team to reproduce defects possibly quicker. I have done an example video that shows a setup of bower inside of a project. This obviously is not a defect, but shows what steps I took. This is visually easier to see that looking through a bunch of code I believe. Think about it @bower/contributors 

The below is not a video showing a defect, just an example so forgive the name

[Defect - 2 minute screen cast](http://quick.as/pl0sd1ld)

**Comment by jamesxv7** [comment]
@pertrai1 I'll close this item since is not related to an issue in Bower per se, it seems more to a topic to be discussed on the [Discord Chat group](https://discord.gg/0fFM7QF0KpZRh2cY).
