### ISSUE TITLE
CLI Option To Specify Install Location

### ISSUE THREAD

**Issue by bdkjones** [bower/bower#212]
### Request

I'd like a flag on the command line to specify where Bower should install the contents of a package. Unless I've missed something, the current CLI will always and only install into:

```
./components/
```

I need to be able to specify an arbitrary path. I envision something like this:

```
bower install <package-name> --install-location /some/arbitrary/path/I/want --no-color
```
### Justification

The addition of this feature makes it possible to integrate Bower into other applications and build processes. I write CodeKit (http://incident57.com/codekit) and would like to bring Bower on board. But to do that, I need control over where Bower installs things. (And switching to an "active directory" before running the command is not an option in a Cocoa app.)

**Comment by operatino** [comment]
@atian25, yes, it works now.
