### ISSUE TITLE
Minor version caret indicator for dependencies is not saved in bower.json

### ISSUE THREAD

**Issue by PauliusLabanauskis** [bower/bower#2121]
Installing the dependency with minor version increment indicator (caret ^) does not save the indicator in the bower.json dependencies version value.

To reproduce, execute the following command:
`bower install --save Polymer/polymer#^1.2.0`

I get the following fragment in bower json:
```json
  "dependencies": {
    "polymer": "Polymer/polymer#1.2.0"
  }
```

I would expect to have the full version indicator saved:

```json
  "dependencies": {
    "polymer": "Polymer/polymer#^1.2.0"
  }
```

When the caret is not there, executing ```bower update polymer``` does nothing while I would like to keep the package up to date for its minor version. After manually inserting the caret symbol, it works as expected.

**Comment by azbshiri** [comment]
What version of bower are you using?

**Comment by PauliusLabanauskis** [comment]
1.7.1

**Comment by azbshiri** [comment]
```
bower install --save Polymer/polymer#^1.2.0
bower cached        git://github.com/Polymer/polymer.git#1.2.3
bower validate      1.2.3 against git://github.com/Polymer/polymer.git#^1.2.0
bower cached        git://github.com/Polymer/webcomponentsjs.git#0.7.20
bower validate      0.7.20 against git://github.com/Polymer/webcomponentsjs.git#^0.7.18
bower install       polymer#1.2.3
bower install       webcomponentsjs#0.7.20

polymer#1.2.3 bower_components/polymer
└── webcomponentsjs#0.7.20

webcomponentsjs#0.7.20 bower_components/webcomponentsjs
```

I reproduced the situation but nothing came out and the indicator saved in bower.json

**Comment by PauliusLabanauskis** [comment]
The issue is only reproducible on Windows. I have checked on Ubuntu and it works as expected.

**Comment by hdgarrood** [comment]
On Windows, `^` is a shell escape character. I think you need to either quote it, or double it up: `bower install --save pkg#^^1.2.0`.

Either way, I don't think this is a problem with Bower.

**Comment by PauliusLabanauskis** [comment]
It is true that it has something to do with Windows shell as it works fine with Cygwin, however probably the defaults in Bower might not be as intuitive because when not specifying any version, for instance, the latest version of the package is pulled and the major version update indicator '~' is set. Usually the default behavior in package managers is updating packages by their minor version unless specified othwerwise. However, it is a different topic and solution looks good for now.
