### ISSUE TITLE
install persist-js fails with "Repository not found"

### ISSUE THREAD

**Issue by timvinc** [bower/bower#2124]
It looks like an install of persist-js tries to find the library at https://github.com/gatt-ip/persist-js - which doesn't exist (any longer?).  I believe it should be looking at https://github.com/jeremydurham/persist-js

**Comment by timvinc** [comment]
It looks like maybe the fork located at gatt-ip was deleted, and the original project's owner (jeremydurham) has dropped maintenance responsibilities, so this may be a dead project.

**Comment by samccone** [comment]
seems like we should unpublish it then right?

**Comment by timvinc** [comment]
That seems appropriate to me

**Comment by samccone** [comment]
cc @desandro

**Comment by desandro** [comment]
`persist-js` has been unregistered :heavy_multiplication_x:

**Comment by samccone** [comment]
thanks :sparkles:
