### ISSUE TITLE
Resolver to install from npm registry

### ISSUE THREAD

**Issue by ChadKillingsworth** [bower/bower#2128]
I'm the author of the [bower-sinopia-resolver](https://www.npmjs.com/package/bower-sinopia-resolver)

Are there plans to have a resolver to install from the npm registry? Based on my own tests, all that's required is that the package include the bower.json in the npm published files. I'm even willing to tackle such a task, but it would be best to have an agreed upon syntax for the resolver to match.

**Comment by sheerun** [comment]
We don't plan to automatically install resolver, but you can put it in package.json, right?

**Comment by sheerun** [comment]
@azbshiri awaiting review label is for PRs awaiting review. There's no need to label issues like this.

**Comment by ChadKillingsworth** [comment]
Are revolvers still required to be globally installed?

**Comment by sheerun** [comment]
they can be installed locally if bower is

**Comment by wrumsby** [comment]
> Are revolvers still required to be globally installed?

I'm going to try to fix #1919 so that this is no longer the case.

**Comment by sheerun** [comment]
Fixed with https://github.com/bower/bower/commit/f4cb047e9df55f03e9971ce4f4341c41d99339e3 and will be released in bower 1.7.8
