### ISSUE TITLE
Could we connect sslStrict configuration value with GIT_SSL_NO_VERIFY

### ISSUE THREAD

**Issue by pwielgolaski** [bower/bower#2129]
I think it could solve many issues reported with corporate proxies.
When I set ssl-strict: false, it only works for http calls, but it will fail when I use git command like 
https://github.com/bower/bower/blob/2adb0b0807ccf325f3710d6ebf183e5a9b5f1159/lib/core/resolvers/GitRemoteResolver.js#L210

Not I need to change configuration of my git to also ignore SSL certificate, but it could be more comprehensive if we export GIT_SSL_NO_VERIFY=true when ssl-strict=false.

What do you think, I could start to work on PR, but I wonder if it will be accepted and if it should belong to bower or bower-config project

Some links: 
https://blog.breadncup.com/2011/06/09/skip-git-ssl-verification/
http://stackoverflow.com/questions/9008309/how-do-i-set-git-ssl-no-verify-for-specific-repos-only

**Comment by sheerun** [comment]
It's a good idea :)
