### ISSUE TITLE
libBower, a server-agnostic implementation of Bower

### ISSUE THREAD

**Issue by marianoviola** [bower/bower#2131]
I'm quite lazy so I took this text from Sass/libSass website changing it a bit:

> We want everyone to enjoy ~~Sass~~ Bower, no matter what language they use. ~~Sass~~ Bower was originally written in ~~Ruby~~ JavaScript. ~~libSass~~ libBower is a C/C++ port of the ~~Sass~~ Bower engine. The point is to be simple, faster, and easy to integrate. Find out more about the project over at GitHub.

It could be a good way to relaunch Bower as a server-agnostic package management tool, what do you think about?

**Comment by sheerun** [comment]
Unfortunately we don't have resources nor expertise to create such library
