### ISSUE TITLE
Remove bower proxy settings

### ISSUE THREAD

**Issue by lopezi** [bower/bower#2134]
Bower is using a proxy it is not available anymore giving me "failed with ECONNRESET" errors.
I dont need a proxy anymore. How can I clean all my proxy settings?

**Comment by rajzshkr** [comment]
@lopezi you might configured proxy in your .bowerrc file. So remove those proxy configuration , it should work. your config should look like below one.
{
 "proxy": "http://proxy.local",
  "https-proxy": "https://proxy.local"
}

**Comment by sheerun** [comment]
Actually you just need to *remove* all proxy and https-proxy entries in bowerrc. By default bower doesn't use proxy.

**Comment by lopezi** [comment]
but there are no entries at .bowerrc, I just created the file to test @rajzshkr  solution which by the way is not working unfortunately

**Comment by sheerun** [comment]
Did you check .bowerrc in your home directory? You can also use `no-proxy` entry in .bowerrc to prevent proxying specific domains.

Bower also uses proxy if `HTTP_PROXY` or `HTTPS_PROXY` env variables are present. Please make sure `env | grep PROXY` doesn't return anything.

**Comment by lopezi** [comment]
correct @sheerun, I have an ALL_PROXY variable returned by grep, where can I find it to correct?

**Comment by sheerun** [comment]
Bower doesn't read ALL_PROXY. It seems to be for SOCKS connections for gnome. Maybe git reads it (bower runs git underneath). I hope you manage to fix your settings.

**Comment by reinert** [comment]
I'm running into this issue too. I removed all proxy settings, including envs, but bower keeps using the proxy setting.

**Comment by puneet0191** [comment]
I am facing the same issue, I don't have any entries for Proxy in .bowerrc file, but it still tries to look for proxy.

**Comment by samseralam** [comment]
Try this one: Just you need to clear .bowerrc file. It works for me.
