### ISSUE TITLE
[FEATURE] Add credential support for Git and SVN

### ISSUE THREAD

**Issue by dschwank** [bower/bower#2136]
Hey,

I would love to add credential support for _Git_ and _SVN_ within bower, thus it is possible to use even private repositories with bower. We already implemented a working prototype for SVN, but before we continue working on that prototype / make a pull request, it would be nice if you could say if this solution would fit into the `bower` scope.

### Why?
Normally, in the _free & open_ world the current implementation is enough, because it is possible to checkout / clone any repository you like. Even a private SVN or Git repository, if you store the credentials either in the SVN settings (e.g. using TortoiseSVN) or in the `bower.json` adding the username / password directly in the path (e.g. `https://user:password@myServer/myRepo.git`). But - that is not really the finest way, especially because you don't want to store your credentials within the `bower.json` file and that you sometime don't have the chance store the credentials within the SVN settings.
To point it out a little bit better - our current problem is, that we have a Gulpfile which manages all our stuff including bower, thus the update, ... is automated. Normally the developers have the SVN credentials stored locally on their machines, thus there is no problem on the local machines.
But on our build machine we are forced by the admins to accept the credentials as command line arguments. That means that an automated process calls our Gulpfile with `username` and `password` as commandline arguments. So far so good - no problem, we just read it in and hand it over to bower, thus it is possible to connect to the repositories. _BUT_, wait - that is not possible - bower doesn't allow to pass over the credentials! :-( ...

### Expectations
It would be nice to hand over the custom credentials directly to `bower`, because `bower` also performs the commandline calls within the resolvers (`git ...` & `svn ...`).

### Idea
It should be possible to add credentials in _at least_ two ways:

1. Global credentials
2. Realm / Path / Url specific credentials

This could be done by extending the current configuration by the following properties:
```javascript
bowerConfig = {
  ...
  credentials: {
    // global credentials
    username: 'myUsername',
    password: 'myPassword',

    // match related credentials
    matcher: [
       // custom credentials for a path like: 'svn+https://myCustomServer:8080/myRepo/more/deep/'
       {
         match: '^svn\+https:\/\/myCustomServer.*',
         username: 'otherUsername',
         password: 'otherPassword'
       },
       // custom credentials for any path starting with: 'svn+https'
       {
         match: '^svn\+https.*',
         username: 'otherUsername2',
         password: 'otherPassword2'
       },
       // custom credentials for any path starting with: 'github.com'
       {
         match: '^github\.com.*',
         username: 'otherUsername3',
         password: 'otherPassword3'
       }, ...
    ]
  },
  ...
};
```

Using this configuration, the resolvers - or to be more precise the command line calls - could be extended, thus the credentials are handed over. In the case for _SVN_ it is quite easy, just add the arguments

* `--username`
* `--password` (optional)

and the related credentials.
In the case of `git` it is a little bit more work, but "should" be done by just replacing the `source` urls. For example replace

`https://myserver/myRepo.git`

by

`https://username:password@myserver/myRepo.git`

### Finally
From our point of view this would be a fine way to support credentials, but maybe we miss a point and it is currently already possible using the `bower API`.
So - what do you think about it? Would it be a possible way from your perspective? Any ideas to enhacne / extend it?

If required / requested I can extend the current prototype and add it as pull request.

**Comment by BenMann** [comment]
Just my two cents: I think pluggable resolvers are the way to go. I would not go ahead and include this into Bower by default. In general we might go with more resolvers to fulfill different needs in the future. Writing somthing like this as a pluggable resolver sounds like a great idea, as there are probably more people with that requirement. Keep us updated on this?

**Comment by faceleg** [comment]
Absolute +1 that this is required, and +1 to making it pluggable. 

Assuming there is community agreement, there could be a PR to implement "pluggability" features into bower, with the plugins created as separate repos.

**Comment by dschwank** [comment]
Hey,

sorry for the late response - and thanks for your comments!
The idea with a "pluggable resolver" is great. But that would mean that I would have to "rewrite" / "copy" the general behaviours of the GIT / SVN resolvers. Would be okay for me, because then I could add some other features to the SVN resolver.

So if (at least) you two agree to it, I will create add one / two new resolvers to manage the credentials for SVN & GIT ... okay?

Greetings!

**Comment by sheerun** [comment]
Yes, we're OK with it :) Actually I'm going to ask our contributors to re-write current resolvers in form of pluggable resolvers on https://github.com/bower/bower-next

**Comment by rajzshkr** [comment]
Closing this issue since we are going to take this in pluggable resolvers.
