### ISSUE TITLE
`bower version` still uses bower.json, contradicting the spec

### ISSUE THREAD

**Issue by hdgarrood** [bower/bower#2139]
For example, with Bower 1.7.2:

```
$ bower version major
bower EINVALIDVERSION      Invalid version argument: `major`. Usage: `bower version [<newversion> | major | minor | patch]`
```

The same happens with `minor`, `patch`, and `build`.

**Comment by rajzshkr** [comment]
@hdgarrood I think there is a small typo in your command. It should be **bower --version major**

**Comment by rajzshkr** [comment]
@sheerun I think we have to change the logger message to 
bower EINVALIDVERSION      Invalid version argument: `major`. Usage: `bower --version [<newversion> | major | minor | patch]`.

**Comment by hdgarrood** [comment]
@rajzshkr no, I meant what I wrote. Or perhaps the documentation is wrong: http://bower.io/docs/api/#version

**Comment by hdgarrood** [comment]
`bower version` seems to me like it should definitely be a subcommand, not an option.

**Comment by rajzshkr** [comment]
@hdgarrood oops. I made a wrong assumption.

**Comment by hdgarrood** [comment]
I think this ought to be considered a bug, not an enhancement. It's very clearly not doing what the docs say it should do.

**Comment by hdgarrood** [comment]
Looking at the code, it seems the problem is that Bower is expecting the version to be in `bower.json`, and erroring if it isn't there. So I'm pretty certain that's what's causing the error I'm seeing.

Given that [the spec](https://github.com/bower/spec/blob/master/json.md#version) claims that Bower ignores this field, I think this is a bug. If I sent a PR which made Bower ignore the version in the JSON when running `bower version`, so that it was based only on git tags, would that be accepted?

**Comment by mattcollier** [comment]
@hdgarrood Have you submitted a PR?

**Comment by hdgarrood** [comment]
I did, and it was merged. See #2232 and #2142.
