### ISSUE TITLE
npm install -g bower issue

### ISSUE THREAD

**Issue by AstmDesign** [bower/bower#2141]
Guys I'm trying to install the Bower on my mac but usually I get this issue

$ npm install -g bower

npm ERR! Darwin 13.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6

npm ERR! shasum check failed for /tmp/npm-592-cdaba300/registry.npmjs.org/bower/-/bower-1.7.2.tgz
npm ERR! Expected: b04228f9970f11777017e64ae39d71f9346c9575
npm ERR! Actual:   7ae40dafa2726c4f44b8cd6c5e3963e144b1f940
npm ERR! From:     https://registry.npmjs.org/bower/-/bower-1.7.2.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/astm/sites/notifications/mobile/npm-debug.log

**Comment by BenMann** [comment]
I think this is node related and you can try to swtich to another registry and reset it after successful installation (`npm set registry http://registry.npmjs.org/`). Does that work for you?

**Comment by rajzshkr** [comment]
@AstmDesign Long back one of my colleague faced the same issue. Try to uninstall node and  npm and install again. check this gist https://gist.github.com/DanHerbert/9520689 . let me know if it works !

**Comment by AstmDesign** [comment]
@BenMann I used this command 
```
$ npm set registry http://registry.npmjs.org/
```
then the command 
```
$ npm install -g bower
```
and it's working now   woooooooow  :)

when I running now the command 
```
$ which bower
>  /Users/astm/.node/bin/bower
```

but now i'm trying to installing the **ngCordova** and got the issue
```
 $ bower install ngCordova

/Users/astm/.node/lib/node_modules/bower/node_modules/bower-config/lib/util/rc.js:71
        throw error;
        ^
Error: Unable to parse /Users/astm/.bowerrc: Unexpected token r 
```

**Comment by BenMann** [comment]
What does your `.bowerrc` contain that's located at `/Users/astm/.bowerrc ` ?

**Comment by rajzshkr** [comment]
@AstmDesign you issue got solved?

**Comment by AstmDesign** [comment]
@BenMann @rajzshkr  I'm still get the same issue and I'm also used this commands

 ```
npm install -g archy && npm install -g bower
```

```
npm cache clean -g
```

but nothing happen !!

**Comment by BenMann** [comment]
Please let us know what's inside your `.bowerrc` located at `/Users/astm/.bowerrc`, the error indicates that there is something wrong with it. You could also try removing it.

**Comment by AstmDesign** [comment]
After I opened it on vim Editor 

```
vim .bowerrc
```

I found this only inside it 

```
rectory": "public/lib"
```

**Comment by BenMann** [comment]
If you didn't accidentially cut it, there is a "di" missing >> `directory": "public/lib"`. Can you try removing the file entirely, if that's not the case?

**Comment by AstmDesign** [comment]
@BenMann  After I removed it and the **.bowerrc** become empty 
the bower now worked with me :+1:  :) 
and I installed the **ngCordova**
Thank you

**Comment by BenMann** [comment]
Glad it worked! Closing :end:
