### ISSUE TITLE
Symlink instead of copy when installing local package

### ISSUE THREAD

**Issue by matthieusieben** [bower/bower#2143]
When installing a local package `"private-package": "./private-package"`, the whole folder is copied. It would be nice to have an option in `bower install` that allows to symlink instead of copy? Or maybe by using a special `#link` at the end of the path?

**Comment by pwang2** [comment]
bower link is supposed to do this work. A general user scenario is to test package you are still developing.  

Or if you are good with command line, just use ln -sf (mklink in windows) as you wish.  If private package folder name if the same as your bower.json 's name. it is equivalent. 

local package is not common in my experience.  It fits in the bower's resolver abstraction. You could use for sure.  You could also check if you have "ignore" field in your bower.json, i suppose when using "private-package": "./private-package", the ignore file list will not be copied.

**Comment by i-am-the-slime** [comment]
I would also like this, is there a solution to it by now?

**Comment by sheerun** [comment]
Bower is deprecated and we recommend using Yarn for such things, it can link directories
