### ISSUE TITLE
Always get bower ECMDERR: exit code of #128 Host key verification failed

### ISSUE THREAD

**Issue by tripathysa** [bower/bower#2148]
Get error while I install: bower install
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git@github.i
u.edu:iucomm/bower-framework.git", exit code of #128 Host key verification faile
d. fatal: Could not read from remote repository.  Please make sure you have the
correct access rights and the repository exists.

I have alreadyrun the command git config --global url."https://".insteadOf git:// on windows
as well as used {
    "proxy":"http://<host>:<port>",
    "https-proxy":"http://<host>:<port>"
} in .bowerrc file.

I am able to find the setting [url "https://"]
	insteadOf = git:// in my .gitconfig file.
Moreover my .gitconfig file is in C://users//username
and my project folder is in C://

**Comment by BenMann** [comment]
One thing I noticed is that the url looks strage `... github.iu ...` but that may be a typo?
Can you share your `bower.json`?

**Comment by tripathysa** [comment]
my bower.json looks like
{
  "name": "##",
  "version": "1.0.0",
  "dependencies": {},
  "devDependencies": {
    "##": "git@github.iu.edu:##/bower-framework.git"
  }
}

Github.iu.edu is an enterprise specific github domain for my university and everybody has specific credentials for that.

**Comment by pwang2** [comment]
below **git@domain:user/pkg** is NOT valid protocol.  try add git:// or https:// if you support them.. 

```
"devDependencies": {
"##": "git@github.iu.edu:##/bower-framework.git"
}
```

**Comment by sheerun** [comment]
check your ssh keys. it says 'Host key verification failed'

bower should succeed as long as soon as "git ls-remote --tags --heads git@github.iu.edu:iucomm/bower-framework.git" command works in your shell.
