### ISSUE TITLE
Add an option to fail if a manual resolving action is needed

### ISSUE THREAD

**Issue by maxday** [bower/bower#2149]
Hi,

What do you think about adding an option to mark bower install as a failure if bower is unable to find a suitable version for a component.

This could prevent a job in Jenkins (or other automated script) from being blocked, waiting indefinitley for an answer.

Something live : bower install --failOnResolve ?

I would be happy to contribute with a PR.

**Comment by sheerun** [comment]
--config.interactive=false should work

**Comment by sheerun** [comment]
also you can set `CI` env variable to `1`

**Comment by maxday** [comment]
Thanks !
