### ISSUE TITLE
Error with 1.7.3 - Cannot find module 'optimist' 

### ISSUE THREAD

**Issue by sebastienbonami** [bower/bower#2152]
Only with 1.7.3, I simply execute the "bower" command and I have the following error:

<pre>
module.js:340
    throw err;
          ^
Error: Cannot find module 'optimist'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/test/project/node_modules/bower/node_modules/bower-config/lib/util/rc.js:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
</pre>

**Comment by sheerun** [comment]
What is your node version and npm version?

**Comment by sheerun** [comment]
And operating system

**Comment by natalan** [comment]
Just got the same error on my Jenkins box as @sebastienbonami posted above.
```
npm: 1.3.10
node: v0.10.25
```

Downgraded back to Bower v1.7.1 and it works again.

**Comment by sebastienbonami** [comment]
> npm: 1.3.10
> node: v0.10.25

Same versions on my side and I use Ubuntu Server 14.04.2 LTS.

**Comment by solomongifford** [comment]
Happening here as well.

#node -v
v0.10.36
#npm -v
1.3.6

**Comment by scottlaplante** [comment]
I was having the same issue for about 4 hours today, but just now with the same steps, I did not have the issue. Was this fixed?

**Comment by ianabc** [comment]
@scottlaplante, the developers have withdrawn 1.7.3 for the moment, so unless you are explicitly asking for that version, you will probably be getting 1.7.2 which doesn't trigger the bug.

**Comment by sheerun** [comment]
Thank you for reporting this. I've unpublished bower 1.7.3 until we resolve this issue.

**Comment by BenMann** [comment]
Three things I'd like to try (not really tackling the underlying issue, but might fix):
1) What happens if you cd to the directory where bower sits and just `npm install`?
2) `npm cache clean` + `rm -rf node_modules/` + `npm install`
3) update npm (`npm update npm -g`)

**Comment by sheerun** [comment]
The issue was with published version of bower@1.7.3 that I unpublished, but now that I published exactly the same bower-prerelease@1.7.3, the problem is gone..

**Comment by sheerun** [comment]
I've published bower again, but under beta tag..

Could you all test this version if it works with different npm / node / platforms?

`npm install -g bower@beta`

**Comment by sheerun** [comment]
I've submitted a bug report to npm:
https://github.com/npm/npm/issues/11227

**Comment by newelement** [comment]
It installs in my user dir.

➜  Sites  npm install -g bower@beta
/Users/<user>/npm/bin/bower -> /Users/<user>/npm/lib/node_modules/bower/bin/bower
bower@1.7.2 /Users/<user>/npm/lib/node_modules/bower
└── semver-utils@1.1.1

**Comment by sheerun** [comment]
what if you global install some other library?

**Comment by newelement** [comment]
Odd npm is installing everything in my user dir. 

➜  Sites  which npm
/usr/local/bin/npm
➜  Sites  which node
/usr/local/bin/node
➜  Sites  node -v
v4.2.5
➜  Sites  npm -v
2.14.12
➜  Sites

**Comment by sheerun** [comment]
Then it isn't bower's issue, sorry.

**Comment by BenMann** [comment]
ping @sebastienbonami @natalan @ianabc can you also confirm?
(It's working for us so far)

**Comment by ianabc** [comment]
I'm not sure if I'm testing exactly what you wanted, but I fired up a clean centos/7 install, added EPEL and the version of npm from EPEL (1.3.6). Then I tried bower@1.7.2, bower-prerelease@1.7.3 and bower@beta (1.7.4)  here are the results

1.7.2 works without a problem
```
[vagrant@mleblanc-vm 1]$ npm install bower
npm http GET https://registry.npmjs.org/bower
npm http 200 https://registry.npmjs.org/bower
npm http GET https://registry.npmjs.org/bower/-/bower-1.7.2.tgz
npm http 200 https://registry.npmjs.org/bower/-/bower-1.7.2.tgz
npm http GET https://registry.npmjs.org/semver-utils
npm http 200 https://registry.npmjs.org/semver-utils
npm http GET https://registry.npmjs.org/semver-utils/-/semver-utils-1.1.1.tgz
npm http 200 https://registry.npmjs.org/semver-utils/-/semver-utils-1.1.1.tgz
bower@1.7.2 node_modules/bower
└── semver-utils@1.1.1
[vagrant@mleblanc-vm 1]$ bower-prerelease@1.7.3^C
[vagrant@mleblanc-vm 1]$ ./node_modules/.bin/bower 
? May bower anonymously report usage statistics to improve the tool over time? Yesn) 
```

The prerelease 1.7.3 fails as before. I think this is different from what @sheerun saw in https://github.com/npm/npm/issues/11227
``` 
[vagrant@mleblanc-vm 1]$ cd ../2/
[vagrant@mleblanc-vm 2]$ npm install bower-prerelease@1.7.3
npm http GET https://registry.npmjs.org/bower-prerelease/1.7.3
npm http 200 https://registry.npmjs.org/bower-prerelease/1.7.3
npm http GET https://registry.npmjs.org/bower-prerelease/-/bower-prerelease-1.7.3.tgz
npm http 200 https://registry.npmjs.org/bower-prerelease/-/bower-prerelease-1.7.3.tgz
bower-prerelease@1.7.3 node_modules/bower-prerelease
[vagrant@mleblanc-vm 2]$ ./node_modules/.
./    ../   .bin/ 
[vagrant@mleblanc-vm 2]$ ./node_modules/.bin/bower-prerelease 

module.js:340
    throw err;
          ^
Error: Cannot find module 'optimist'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/vagrant/node2/node_modules/bower-prerelease/node_modules/bower-config/lib/util/rc.js:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```
Then finally bower@beta
```
npm install bower@beta
npm http GET https://registry.npmjs.org/bower
npm http 304 https://registry.npmjs.org/bower
npm http GET https://registry.npmjs.org/bower/-/bower-1.7.4.tgz
npm http 200 https://registry.npmjs.org/bower/-/bower-1.7.4.tgz
bower@1.7.4 node_modules/bower
[vagrant@mleblanc-vm 3]$ ls
node_modules
[vagrant@mleblanc-vm 3]$ ./node_modules/.bin/bower 

module.js:340
    throw err;
          ^
Error: Cannot find module 'optimist'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/vagrant/3/node_modules/bower/node_modules/bower-config/lib/util/rc.js:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by sebastienbonami** [comment]
I have the exact same results as @ianabc on Ubuntu 14.04 with npm 1.3.10 and node v0.10.25.

bower@1.7.2 works well
bower-prerelease@1.7.3 throws the error
bower@beta (1.7.4) also throws the error

@sheerun Running *npm install -g bower@beta* doesn't throw any error. Executing *bower* does.

**Comment by sheerun** [comment]
@sebastienbonami It seems that all npm versions before 1.4.7 exhibit this issue:
https://travis-ci.org/sheerun/bower-test/builds/104495526

**Comment by BenMann** [comment]
I'm still thinking if writing all the `bundledDependencies` as direct dependencies is an option. I know that would make our `package.json` extremely long and it's a workaround at best but the problem seems to occur again in the early 3.x versions (probably for different reasons?). 

@sheerun would you consider that approach? Are you currently looking into other mistakes on our end that might cause it? If no to both I might as well start reading some npm source code :grin:

There are definetely different ways npm handles `bundledDependencies` in different versions, as also described in this [interesting issue](https://github.com/npm/npm/issues/9668#issuecomment-143318074). If people are locked to old versions I don't think there is a reasonably way to use `bundledDependencies` and support all these versions, which is sad.

**Comment by natalan** [comment]
@BenMann it's better late than never:

```
npm: 1.3.10
node: v0.10.25
```

And OS:
```bash
jenkins@jenkins:~/jobs/web-application-master/workspace$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```


#### bower@beta: (still issues)
```bash
jenkins@jenkins:~/jobs/web-application-master/workspace$ sudo npm install -g bower@beta
npm http GET https://registry.npmjs.org/bower
npm http 304 https://registry.npmjs.org/bower
/usr/local/bin/bower -> /usr/local/lib/node_modules/bower/bin/bower
bower@1.7.4 /usr/local/lib/node_modules/bower
jenkins@jenkins:~/jobs/web-application-master/workspace$ bower install

module.js:340
    throw err;
          ^
Error: Cannot find module 'optimist'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/node_modules/bower-config/lib/util/rc.js:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
jenkins@jenkins:~/jobs/web-application-master/workspace$ 
```

#### bower-prerelease@1.7.3 (still issues)
```bash
jenkins@jenkins:~/jobs/web-application-master/workspace$ sudo npm install -g bower-prerelease@1.7.3
npm http GET https://registry.npmjs.org/bower-prerelease/1.7.3
npm http 200 https://registry.npmjs.org/bower-prerelease/1.7.3
npm http GET https://registry.npmjs.org/bower-prerelease/-/bower-prerelease-1.7.3.tgz
npm http 200 https://registry.npmjs.org/bower-prerelease/-/bower-prerelease-1.7.3.tgz
/usr/local/bin/bower-prerelease -> /usr/local/lib/node_modules/bower-prerelease/bin/bower
bower-prerelease@1.7.3 /usr/local/lib/node_modules/bower-prerelease
jenkins@jenkins:~/jobs/web-application-master/workspace$ bower install

module.js:340
    throw err;
          ^
Error: Cannot find module 'optimist'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/node_modules/bower-config/lib/util/rc.js:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```
#### bower@1.7.2 (no issues)
```bash
jenkins@jenkins:~/jobs/web-application-master/workspace$ sudo npm install -g bower@1.7.2 
npm http GET https://registry.npmjs.org/bower/1.7.2
npm http 200 https://registry.npmjs.org/bower/1.7.2
npm http GET https://registry.npmjs.org/bower/-/bower-1.7.2.tgz
npm http 200 https://registry.npmjs.org/bower/-/bower-1.7.2.tgz
npm http GET https://registry.npmjs.org/semver-utils
npm http 304 https://registry.npmjs.org/semver-utils
/usr/local/bin/bower -> /usr/local/lib/node_modules/bower/bin/bower
bower@1.7.2 /usr/local/lib/node_modules/bower
└── semver-utils@1.1.1
jenkins@jenkins:~/jobs/web-application-master/workspace$ bower install
? May bower anonymously report usage statistics to improve the tool over time? No
jenkins@jenkins:~/jobs/web-application-master/workspace$ 
```

**Comment by sheerun** [comment]
@natalan Could you try bower-prerelease@1.7.7 ?

**Comment by sebastienbonami** [comment]
@sheerun I just tried bower-prerelease@1.7.7 (same setup as @natalan) and no issue! :smile:

**Comment by natalan** [comment]
@sheerun, Yes the bower-prerelease works as expected:

```
jenkins@jenkins:~/jobs/web-application-master/workspace$ sudo npm install -g bower-prerelease@1.7.7
npm http GET https://registry.npmjs.org/bower-prerelease/1.7.7
npm http 200 https://registry.npmjs.org/bower-prerelease/1.7.7
npm http GET https://registry.npmjs.org/bower-prerelease/-/bower-prerelease-1.7.7.tgz
npm http 200 https://registry.npmjs.org/bower-prerelease/-/bower-prerelease-1.7.7.tgz
/usr/local/bin/bower-prerelease -> /usr/local/lib/node_modules/bower-prerelease/lib/bin/bower
bower-prerelease@1.7.7 /usr/local/lib/node_modules/bower-prerelease
jenkins@jenkins:~/jobs/web-application-master/workspace$ bower install
bower: command not found
jenkins@jenkins:~/jobs/web-application-master/workspace$ bower-prerelease install
```

and `npm list -g` also reports no issues (ignore my `grunt-cli`):
```
jenkins@jenkins:~/jobs/web-application-master/workspace$ npm list -g
/usr/local/lib
├── bower-prerelease@1.7.7
└─┬ grunt-cli@0.1.13
  ├─┬ findup-sync@0.1.3
  │ ├─┬ glob@3.2.11
  │ │ ├── inherits@2.0.1
  │ │ └─┬ minimatch@0.3.0
  │ │   ├── lru-cache@2.5.0
  │ │   └── sigmund@1.0.0
  │ └── lodash@2.4.1
  ├─┬ nopt@1.0.10
  │ └── abbrev@1.0.5
  └── resolve@0.3.1
```

**Comment by ianabc** [comment]
I can confirm, running with npm 1.3.6 (from CentOS EPEL) and bower-prerelease@1.7.7 everything works again for me.
