### ISSUE TITLE
bower.herokuapp.com down?

### ISSUE THREAD

**Issue by grug** [bower/bower#2154]
Hey there,

It looks like bower.herokuapp.com is down. I can't ping it and running `bower install` on a project from 3 different networks results in `bower ENOTFOUND     Request to https://bower.herokuapp.com/packages/angular failed: getaddrinfo ENOTFOUND bower.herokuapp.com`

Is anyone able to shed some light on this?

Thanks,
Dave

**Comment by sheerun** [comment]
works for me

**Comment by grug** [comment]
Works for you, must work for everyone!
