### ISSUE TITLE
dependency resolution is not working for angular and angularjs

### ISSUE THREAD

**Issue by pencilcheck** [bower/bower#2155]
Even though their info is the same if you do `bower info` they are somehow different when running bower install, and I have two angular folders, one in angular and the other one in angularjs.

Since I use gulp to automate adding the scripts from bower components, this is causing problems where angular will get loads twice in the app.

Is this a well known bug? And how do I fix this besides contacting the author of the offending package to change their dependency to the more common and popular "angular"??

**Comment by faceleg** [comment]
Could you add the bower JSON that causes this?

**Comment by sheerun** [comment]
I'm afraid for now the only way to solve it is indeed to contact author of package.

We're working to solve this issue in bower 2.0, but I'll break compatibility anyway.
