### ISSUE TITLE
npm Package for Bower 1.7.5: Missing node_modules/bower/bin/bower

### ISSUE THREAD

**Issue by bentolor** [bower/bower#2159]
To be able to use individual bower version per project we do not install bower globally, but locally (effectively using `npm install` with bowe in the `package.json` of the project instead of doing a `npm install -g bower`).

Bower 1.7.5 breaks all builds as it no longer ships the binary `node_modules/bower/bin/bower`

**Comment by cyt-rsd** [comment]
Same for me. Its under 'lib' now...

**Comment by vijayk** [comment]
Please see #2157

**Comment by bentolor** [comment]
Money quote: 
> I've switched from using hardcoded bin path to using `node_module/.bin/bower` which fixes the problem for me

So if this is the npm-way to linking to binaries I'm okay with the change in general. 

But having a deprecation warning in a wrapper file for transition and **not changing this in a point release** would be appreciated.

**Comment by bentolor** [comment]
Thanks @vijayk and @cyt-rsd for the fast feedback. This really helped me to sort out the issue far quicker than I could have done.

**Comment by BenMann** [comment]
Closing in favor of https://github.com/bower/bower/issues/2157.
