### ISSUE TITLE
Bower ETIMEDOUT

### ISSUE THREAD

**Issue by Edymov** [bower/bower#2162]
Bower i, bower search e.t.c does not work. Operations fail with ETIMEDOUT error 
![](https://cloud.githubusercontent.com/assets/8273881/12704880/aa916e1c-c875-11e5-9059-20efb4299ac4.png)

bower.herokuapp.com does not ping. 100% packet loss

**Comment by Edymov** [comment]
Searhing on the http://bower.io/search/ does not work too

**Comment by BenMann** [comment]
Can't replicate. Can you share more about your setup? Are you behind a proxy or firewall?

**Comment by Edymov** [comment]
> Can't replicate. Can you share more about your setup? Are you behind a proxy or firewall?

Bower 1.7.7, npm 3.3.6, node.js 5.0, win 8.1. Neither Firewall nor proxy.

**Comment by Edymov** [comment]
It was a net problem. netsh int ip reset fixed the problem.

**Comment by BenMann** [comment]
Glad you figured it out, closing! :end:
