### ISSUE TITLE
Programmatically download bower artifacts without dependencies

### ISSUE THREAD

**Issue by kirschre** [bower/bower#2164]
Hey guys,

I'm working on a project where I need to programmatically download and save bower artifacts from a git repository at a tag.

Given a repository `https://github.com/foo/bar.git` and tag `1.2.3`, I want to kick off `bower install https://github.com/foo/bar.git#1.2.3`, but ignore any dependencies the target package has. Additionally, I would like to provide a folder to install directly to - as opposed to the artifacts ending up in `bower_components/bar`, I'd like to be able to put them in a temp directory of my choice.

I have considered using `git clone` itself for this, but I'd like to avoid it if possible for these reasons:
- Bower already handles equivalent semver tag matching - if I ask for `v1.2.3`, it will install `1.2.3` if available
- Bower allows the library developer to `ignore` some files, which I'd have to prune out manually
- It's important that what I end up with is exactly what bower would have installed to `bower_components/bar` if a user were to execute `bower install` - using bower itself guarantees that I'm not missing any additional handling now or in the future.

Are either of these things possible? If not, can anyone recommend another way to go here? The docs for bower's programmatic API are a little sparse, but I wasn't able to turn up anything useful skimming the code either.

Thanks in advance for any help!

**Comment by sheerun** [comment]
You can use `directory` and `ignoredDependencies` fields in `.bowerrc`.

Currently there's no way to ignore all the dependencies of some package, you need to list explicitly all of them.

**Comment by kirschre** [comment]
Hey @sheerun, thanks for the response. I'm aware of the `ignoredDependencies` flag, but it doesn't quite solve my problem - since I have to support downloading any of a large set of packages (and more can be added at any time, and the dependencies of a package can change from release to release...), it would be a fair amount of work to keep track of the total set of dependencies to ignore.

What I'd really like is to be able to set `ignoredDependencies: *` to ignore all of them. Right now, per bower package I install, I have to pay some amount of overhead downloading (and then deleting!) dependencies I don't need - for a small package with several large dependencies, you can imagine the ratio of useful to wasted time can be quite bad.

Does this sound like a reasonable enhancement to you? If so I'd be willing to work on a PR when my schedule allows.

**Comment by sheerun** [comment]
I think it's fair. I can accept such PR. But please also include integration tests in `test/commands/install.js` and `test/commands/update.js`

**Comment by sheerun** [comment]
Bower is deprecated and in maintenance mode, so we won't implement new features like this one. We recommend switching to yarn and migrating legacy projects to it with [bower-away](https://github.com/sheerun/bower-away)
