### ISSUE TITLE
Display deviation from defaults when using verbose flag

### ISSUE THREAD

**Issue by bheiskell** [bower/bower#2165]
It would be useful when troubleshooting to show the deviations from default configuration made by bowerrc files when running with the verbosity flag on.

**Comment by bbatha** [comment]
:+1:

**Comment by yash14123** [comment]
I would like to take this up.

**Comment by yash14123** [comment]
Can I get some hints on how to proceed?

**Comment by sheerun** [comment]
Please read our "Contribution Guideline" in Wiki section.

**Comment by yash14123** [comment]
Please I need help with this.

**Comment by faceleg** [comment]
@yash14123 this is what he is talking about: https://github.com/bower/bower/wiki/Contributor-Guidelines#writing-code

**Comment by shtr0m** [comment]
Looking into this, it might simpler to just export the defaults from the bower/config project.
Then do a object diff.

I could PR it with tests. @theaverageguy are you working on this?

**Comment by thinkxl** [comment]
@shtr0m I don't think he is working on it. You still want to take over?

**Comment by deepakavs** [comment]
Can I pick this up ?

**Comment by thinkxl** [comment]
@deepakavs sure!

**Comment by sheerun** [comment]
Bower is deprecated and in maintenance mode, so we won't implement new features like this one. We recommend switching to yarn and migrating legacy projects to it with [bower-away](https://github.com/sheerun/bower-away)
