### ISSUE TITLE
Bower link is installing dependencies

### ISSUE THREAD

**Issue by mderoche** [bower/bower#2166]
I am seeing an issue where running `bower link` is seemingly running `bower install` as well.  Wondering if this is intentional.

Scenario:
- Three Bower components: one main application and two sub modules (SM1, SM2)
- Using `bower link` on both sub modules
- Using `bower link SM1` and `bower link SM2` to symlink the submodules into the main application
- The bower.json for the main application includes both SM1 and SM2 as dependencies for wiredep purposes.

When I run `bower link SM1` in the main application directory, it first tries to install all of the other dependencies in the bower.json file for the main application.  Since this bower.json includes both SM1 and SM2, this process fails when it tries to install SM2 since it hasn't been linked yet.

Attached is a zip that sets up the scenario.  To reproduce:
1. `cd /path/to/testBowerLink`
2. `cd sub1`
3. `bower link`
4. `cd ../sub2`
5. `bower link`
6. `cd ../main`
7. `bower link sub1`

The console will show some of the dependencies of main (moment, underscore) being resolved before erroring out on sub2, since it isn't linked yet.

Console output of test:

```
testBowerLink $ cd sub1/
sub1 $ bower link
bower                    link /Users/mike/.local/share/bower/links/sub1 > /Users/mike/dev/testBowerLink/sub1
sub1 $ cd ../sub2
sub2 $ bower link
bower                    link /Users/mike/.local/share/bower/links/sub1 > /Users/mike/dev/testBowerLink/sub2
sub2 $ cd ../main
main $ bower link sub1
bower moment#*                  cached git://github.com/moment/moment.git#2.11.2
bower moment#*                validate 2.11.2 against git://github.com/moment/moment.git#*
bower underscore#*              cached git://github.com/jashkenas/underscore.git#1.8.3
bower underscore#*            validate 1.8.3 against git://github.com/jashkenas/underscore.git#*
bower sub2#*                 ENOTFOUND Package sub2 not found
```

(Running bower 1.7.7)

[testBowerLink.zip](https://github.com/bower/bower/files/118391/testBowerLink.zip)

**Comment by ShyykoSerhiy** [comment]
From what I see, it is intentional 
https://github.com/bower/bower/blob/671c23ad50550bc72fde2329d9e13fae0b71667d/lib/commands/link.js#L61

**Comment by mderoche** [comment]
I interpreted that comment as it was installing the dependencies of the package being linked, not the package itself.

**Comment by gabe-rivera** [comment]
Any update to this? I'm seeing similar issues.

**Comment by sheerun** [comment]
This issue got stale. If it still bothers someone, please create another one
