### ISSUE TITLE
bower home $modulename does not open $modulename homepage

### ISSUE THREAD

**Issue by leegee** [bower/bower#2169]
As in the title.

	$ bower search XMLHttpRequest
	Search results:

	    FakeXMLHttpRequest git://github.com/trek/FakeXMLHttpRequest.git
	    xmlhttprequest git://github.com/ilinsky/xmlhttprequest.git

	$ bower home FakeXMLHttpRequest
	bower FakeXMLHttpRequest#*  not-cached https://github.com/trek/FakeXMLHttpRequest.git#*
	bower FakeXMLHttpRequest#*     resolve https://github.com/trek/FakeXMLHttpRequest.git#*
	bower FakeXMLHttpRequest#*    download https://github.com/trek/FakeXMLHttpRequest/archive/1.3.0.tar.gz
	bower FakeXMLHttpRequest#*     extract archive.tar.gz
	bower FakeXMLHttpRequest#*     invalid-meta fake-xml-http-request is missing "ignore" entry in bower.json
	bower FakeXMLHttpRequest#*         resolved https://github.com/trek/FakeXMLHttpRequest.git#1.3.0

	$ bower help

	Usage:

	    bower <command> [<args>] [<options>]
	Commands:

	    cache                   Manage bower cache
	    help                    Display help information about Bower
	    home                    Opens a package homepage into your favorite browser
	   ...

**Comment by rajzshkr** [comment]
Hi @leegee , I tried the same. **bower home FakeXMLHttpRequest** opens [https://github.com/pretenderjs/FakeXMLHttpRequest](https://github.com/pretenderjs/FakeXMLHttpRequest) in browser. what bower version are you are using?

**Comment by leegee** [comment]
Thanks, @rajzshkr . I'm sorry I can't tell you --- I'm on Windows 10, rather than my usual OSX or Linux. I have no idea how to find out anything on Windows: it's horrible.

My default is set to Chrome (latest), but sometimes Windows seems to prefer to use Edge (no idea why). I also have the latest Firefox.

If I can help, please let me know.

**Comment by BenMann** [comment]
@leegee he meant/said `bower` version, not browser ;)
you can find out with `bower -v` in your terminal.

**Comment by leegee** [comment]
@rajzshkr lol sorry about that -- you can imagine what fun I have debugging with eyesight like this...!

    $ bower -v
    1.7.7

**Comment by sheerun** [comment]
I've updated opn package to 4.0.0. I hope it'll fix issue on Windows (did it ever work)?
