### ISSUE TITLE
${BASEDIR}/lib/node_modules/bower/bin/bower contains an error

### ISSUE THREAD

**Issue by sibaz** [bower/bower#2170]
The file ${BASEDIR}/lib/node_modules/bower/bin/bower specifies that the environment it is to be run in is `node`

Whereas the nodejs rpm creates /usr/bin/node on RPM based systems, the .deb on Ubuntu (14.04) creates /usr/bin/nodejs.  /usr/sbin/node is completely separate application.  nodejs-legacy(.deb) provides a symlink for /usr/bin/node on Ubuntu 14

So the first line of the bower file should replaced according to the following patch, to ensure an error occurs if it's not installed right, rather than it silently trying to use an amateur radio node application, as an js interpreter :-)
<pre>
diff bin.old/bower bin/bower
1c1
< #!/usr/bin/env node
---
> #!/usr/bin/env /usr/bin/node
</pre>

**Comment by sheerun** [comment]
We can't do it because node is not placed in `/usr/bin/node` on all unix platforms (linux distros, osx)

**Comment by sibaz** [comment]
So sheerun, can you clarify the process.  As things stand, it's wrong and broken on Redhat/Centos, if you change it to a fully qualified path, it's broken on OSX.  Are you saying that its ok to be broken on some distros because it's already broken, or is there some preference over OSX vs Redhat?  What is the path to nodejs on OSX?  Is there a better identifier than node?  Perhaps make it nodejs, then it won't clash, and it becomes dependant on those distro's that use 'node' for nodejs, to install an alias for nodejs?

To clarify the issue is that scripting using 'node' as the nominated interpreter is unsafe, as there are multiple packages which make that exe available in the path.

**Comment by sheerun** [comment]
Why exactly `#!/usr/bin/env node` is not working on redhat? `env` won't accept relative paths?

What prevents "ametour radio" or any other tool to install to `/usr/bin/node`?

If you'd like bower to change its behavior, I'd suggest confincing npm first, that bower depends on for its installation: https://github.com/npm/npm/blob/master/bin/npm-cli.js
