### ISSUE TITLE
Application Error unregistering packages.

### ISSUE THREAD

**Issue by mbostock** [bower/bower#2171]
Hi. I’m trying to repoint the `d3` package to a new [d3-bower repository](https://github.com/mbostock-bower/d3-bower). I did this recently for the `topojson` package (now pointed at [topojson-bower](https://github.com/mbostock-bower/topojson-bower), but when I tried to `unregister d3`, I got this error, reformatted for readability:

```
bower EUNKNOWN
<!DOCTYPE html>     
<html>     
<head>       
<meta name="viewport" content="width=device-width, initial-scale=1">       
<style type="text/css">
html, body, iframe { margin: 0; padding: 0; height: 100%; }
iframe { display: block; width: 100%; border: none; }       
</style>     
<title>Application Error</title>     
</head>     
<body>       
<iframe src="//s3.amazonaws.com/heroku_pages/error.html">         
<p>Application Error</p>       
</iframe>     
</body>     
</html>
```

I used `bower login -t …` to authenticate, which appeared successful:

```
bower EAUTH         Logged in as mbostock
```

So, I’m not sure what the problem is here. Please let me know how I can update the registry entry for `d3` (or, if you want to do it for me, that would be great, too!). Thanks.

**Comment by rajzshkr** [comment]
I can also able to replicate this issue.

**Comment by ealves-pt** [comment]
I have the same problem.

**Comment by sheerun** [comment]
I fixed the error on registry, it was my fault.
