### ISSUE TITLE
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/angular/bower-angular-route.git", exit code of #128 fatal: I don't handle protocol '[https'

### ISSUE THREAD

**Issue by marvin-SL** [bower/bower#2172]
Hello, 

I try to install angularJs, but when i come to `bower install` command, i've got error

> bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/angular/bower-angular-route.git", exit code of #128 fatal: I don't handle protocol '[https'

I don't have a proxy at home, i tried with several internet connection, same thing happens.
It's not only this github package which doesn't want to install.

I tried to use `git config --global url."https://".insteadOf git://` or `git config --global url."http://".insteadOf git://` , nothing work.

I'm on ubuntu

Here the stack trace :

> bower not-cached    git://github.com/angular/bower-angular.git#1.4.x
> bower resolve       git://github.com/angular/bower-angular.git#1.4.x
> bower not-cached    git://github.com/angular/bower-angular-mocks.git#1.4.x
> bower resolve       git://github.com/angular/bower-angular-mocks.git#1.4.x
> bower not-cached    git://github.com/jquery/jquery-dist.git#~2.1.1
> bower resolve       git://github.com/jquery/jquery-dist.git#~2.1.1
> bower not-cached    git://github.com/twbs/bootstrap.git#~3.1.1
> bower resolve       git://github.com/twbs/bootstrap.git#~3.1.1
> bower not-cached    git://github.com/angular/bower-angular-route.git#1.4.x
> bower resolve       git://github.com/angular/bower-angular-route.git#1.4.x
> bower not-cached    git://github.com/angular/bower-angular-resource.git#1.4.x
> bower resolve       git://github.com/angular/bower-angular-resource.git#1.4.x
> bower not-cached    git://github.com/angular/bower-angular-animate.git#1.4.x
> bower resolve       git://github.com/angular/bower-angular-animate.git#1.4.x
> bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/jquery/jquery-dist.git", exit code of #128 fatal: I don't handle protocol '[https

> 
> Additional error details:
> fatal: I don't handle protocol '[https'
> npm ERR! weird error 1
> npm WARN This failure might be due to the use of legacy binary "node"
> npm WARN For further explanations, please read
> /usr/share/doc/nodejs/README.Debian

> 
 
npm ERR! not ok code

can you help me ?

thanks

**Comment by sheerun** [comment]
Probably you configured it wrong `[https` instead of `https` in global git config, check what's there. btw. it's not a support channel.

**Comment by LydiaQianyinhua** [comment]
Found your git account's git config file(.gitconfig), and modify the followings:

    [user]
    email = your e-mail account


    name = your git account
    [url "git@github.com:"]


    insteadOf = https://github.com/
