### ISSUE TITLE
Can you unregister package polymer-fontawesome please?

### ISSUE THREAD

**Issue by mdwragg** [bower/bower#2173]
Hi,

The package `polymer-fontawesome` is pointing to a dead repo on github, the user has also disappeared. I tried to follow the steps to unregister the package but cannot (I'm not a contributor to this package). I'd like to reuse the package name.

Thanks in advance for your help.

**Comment by BenMann** [comment]
There is currently an issue with unregistering packaages (see https://github.com/bower/bower/issues/2171).
However @desandro is our chief-unregister-expert I guess.

**Comment by desandro** [comment]
`polymer-fontawesome` has been unregistered. All yours!

**Comment by mdwragg** [comment]
Thanks so much!
