### ISSUE TITLE
scripts/hooks functionality added but there's not documention for it

### ISSUE THREAD

**Issue by azbshiri** [bower/bower#2178]
Hey, [install-hooks](https://github.com/cgross/bower/tree/install-hooks) branch merged successfully but there's no documentation for on master branch. there's only one document file called [HOOKS.md](https://github.com/cgross/bower/blob/install-hooks/HOOKS.md) in [cgross/bower](https://github.com/cgross/bower/) fork which is not included in the merge.

**Comment by BenMann** [comment]
We got rid of the HOOKS.md a while back and added it to https://github.com/bower/bower.github.io/blob/master/docs/config.md
as well as here
https://github.com/bower/spec/blob/master/config.md
