### ISSUE TITLE
bower install jsrsasign broken

### ISSUE THREAD

**Issue by ltrillaud** [bower/bower#2179]
$ bower install jsrsasign 
bower jsrsasign=jsrsasign#~5.0.5       not-cached git://github.com/kjur/jsrsasign=jsrsasign.git#~5.0.5
bower jsrsasign=jsrsasign#~5.0.5          resolve git://github.com/kjur/jsrsasign=jsrsasign.git#~5.0.5
bower jsrsasign#*                          cached git://github.com/kjur/jsrsasign.git#5.0.5
bower jsrsasign#*                        validate 5.0.5 against git://github.com/kjur/jsrsasign.git#*
bower jsrsasign=jsrsasign#~5.0.5          ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/kjur/jsrsasign=jsrsasign.git", exit code of #128 fatal: unable to access 'https://github.com/kjur/jsrsasign=jsrsasign.git/': The requested URL returned error: 400

Additional error details:
fatal: unable to access 'https://github.com/kjur/jsrsasign=jsrsasign.git/': The requested URL returned error: 400

**Comment by BenMann** [comment]
Works for me. I also get why it is not working for you.. The URL part `.../kjur/jsrsasign=jsrsasign.git/'` looks pretty off (is not valid). Would be interesting to know how that happens. Can you tell us a bit more about your setup, especially the Bower version and operating system?

**Comment by ltrillaud** [comment]
Hi Ben

Thank you for your quick answer.

It’s a MacOS 10.9.5
Bower is 1.6.5
npm is 2.14.3
node is 4.2.1

.bowerrc in my project home is :
{“directory”: “app/bower_components"}
I have no .bowerrc in my home directory

I have identified the problem. It's not on the first install, but on the --save. jsrsaasign use his git namespace  to save the module and have a bad saving in the project bower.json

if you try this : 
`$ bower install jsrsasign --save
bower jsrsasign#*               cached git://github.com/kjur/jsrsasign.git#5.0.5
bower jsrsasign#*             validate 5.0.5 against git://github.com/kjur/jsrsasign.git#*
bower kjur/jsrsasign#~5.0.5    install kjur/jsrsasign#5.0.5`

I retrieved the download in app/bower_components/kjur/jsrsasign. All the other components doesn't use their git namespace.
But worse, the bower.json is broken with this line added : 
`"kjur/jsrsasign": "jsrsasign#~5.0.5"`

Should I report this bug in jsrsasign instead of you ?

Laurent

**Comment by BenMann** [comment]
Yeah, I think that's a good idea, as there is nothing we can really do about this.
Actually everything is working as expected as far as Bower is concerned. For a quick fix you can just remove the `"kjur/"` part in the `dependencies` section of your `bower.json`.

Also, from the docs: 

````
Bower doesn’t support GitHub-style namespacing (org/repo), 
however you are encouraged to namespace related packages 
with -, for example, angular- and paper-.
```
Fell free to reference this issue.
I'll close for now but will get any follow-up questions. :cake:

**Comment by ltrillaud** [comment]
For reference. This issue forwarded to : 
[https://github.com/kjur/jsrsasign/issues/156](https://github.com/kjur/jsrsasign/issues/156)
