### ISSUE TITLE
Having a single relative path to all package files

### ISSUE THREAD

**Issue by Gespinha** [bower/bower#2181]
Hi there,

Bower is amazing to have everything managed really easily, but I've found it particularly annoying that every package always has a very specific file organisation inside, which makes me have to go check, every time, where are the files I need located.

Is there any way of having a relative path that just points to the package folder and the specific file, without having to check the folder?

for example, for JQuery and Angualr I would just have the same kind of path, but with only their names changing.

../my-package-folder/jquery/jquery.min.js
../my-package-folder/angular/angular.min.js

Or are the folders that get imported exactly like they are inside the packages' repositories?

Thanks in advance :)

**Comment by sheerun** [comment]
Hey. Currently it's not possible to do, nor planned to implement, but you can use postinstall hooks to to move files to appropriate places.

**Comment by BenMann** [comment]
Looks sufficiently answered!
Closing. If you have further questions (about postinstall hooks) feel free to comment :)
