### ISSUE TITLE
`bower search d3` doesn’t find D3

### ISSUE THREAD

**Issue by mbostock** [bower/bower#2185]
Apologies if I’m being dumb, but I was surprised to discover that neither http://bower.io/search/?q=d3 nor `bower search d3` returns any information about the `d3` package. Instead it returns a lot of D3-related packages:

```
nvd3 git://github.com/novus/nvd3
angularjs-nvd3-directives git://github.com/cmaurer/angularjs-nvd3-directives.git
d3-tip git://github.com/Caged/d3-tip.git
angular-nvd3 git://github.com/krispo/angular-nvd3.git
d3-plugins git://github.com/d3/d3-plugins.git
d3-cloud git://github.com/jasondavies/d3-cloud.git
d3cloud git://github.com/rajenms/d3-cloud.git
r2d3 git://github.com/mhemesath/r2d3.git
d3.chart git://github.com/misoproject/d3.chart.git
d3js git://github.com/henrytao-me/d3js.git
angularD3 git://github.com/WealthBar/angular-d3.git
dagre-d3 git://github.com/cpettitt/dagre-d3.git
d3.chart.base git://github.com/d3-chart-components/d3.chart.base.git
d3.chart.bubble-matrix git://github.com/benbria/d3.chart.bubble-matrix.shim.git
d3-timeline git://github.com/jiahuang/d3-timeline.git
d3pie git://github.com/benkeen/d3pie.git
d3-angular git://github.com/beefsack/angular-d3.git
d3-geo-projection git://github.com/d3/d3-geo-projection.git
amd-d3-cloud git://github.com/Mirajjj/d3-cloud.git
d3-measure-text git://github.com/jprichardson/d3-measure-text.git
d3-amd git://github.com/Moviri/d3
angular-d3 git://github.com/angular-d3/lazy-panda.git
id3 git://github.com/43081j/id3.git
d3-helpers git://github.com/bahmutov/d3-helpers.git
github-d3 git://github.com/github/d3.git
line-chart git://github.com/angular-d3/line-chart.git
d3-treelayout git://github.com/MfgLabs/d3-treelayout.git
ember-nvd3 git://github.com/Glavin001/ember-nvd3.git
webapps-bower-d3 git://github.com/xl8/webapps-bower-d3.git
d3.chart.legend git://github.com/knownasilya/d3.chart.legend.git
```

However, `bower info d3` does return the expected package information.

Perhaps it’s unlikely that someone would search for a package when they already know its name, but it still seems like registry search should index package names, or at the least, check whether the search query is an existing package.

Is this something I need to fix in my bower.json or is this a bug in Bower’s search?

**Comment by ryantemple** [comment]
Doesn't work for me either on the command line or at http://bower.io/search/?q=d3 - I get the same behaviour for the jQuery package, but strangely not for Angular.  Will do a little more digging.

**Comment by BenMann** [comment]
In general `bower info` is working as expected and what you're looking for.
`bower search x` is admittedly not ideal, as it ignores the actual package itself. As mentioned above same happens with `jQuery` and every other package. It is partly designed to discover related packages, such as `d3-timeline`, which works. Not displaying the actual package itself however is pretty questionable. I'd suggest to tackle this in a future version of the registry, as we have already put something tohether using elasticsearch for all the packages, which allows the use of fulltext search and filtering by importance throughout the packages. It can also differ between exact matches and matches containing x + some more.

**Comment by accommodavid** [comment]
Should we close this issue? FWIW http://bower.io/search/?q=d3 does seem to be working now.

**Comment by mbostock** [comment]
Not sure why this was closed. Contrary to @accommodavid’s comment, the `d3` package still doesn’t show up either on the website or using `bower search`.

![screen shot 2016-03-23 at 9 15 29 am](https://cloud.githubusercontent.com/assets/230541/13992099/ef8d37dc-f0d7-11e5-9355-65fdeaef7ee4.png)

![screen shot 2016-03-22 at 7 26 26 pm](https://cloud.githubusercontent.com/assets/230541/13992100/ef93fffe-f0d7-11e5-9579-1e77f11a16d0.png)

**Comment by rajzshkr** [comment]
I didn't see bower.json file in d3js official repo. https://github.com/mbostock/d3

**Comment by mbostock** [comment]
That’s because it’s here: https://github.com/mbostock-bower/d3-bower

```
$ bower info d3
bower d3#*                      cached git://github.com/mbostock-bower/d3-bower.git#3.5.16
bower d3#*                    validate 3.5.16 against git://github.com/mbostock-bower/d3-bower.git#*

{
  name: 'd3',
  description: 'A JavaScript visualization library for HTML and SVG.',
  main: 'd3.js',
  license: 'BSD-3-Clause',
  ignore: [],
  homepage: 'https://github.com/mbostock-bower/d3-bower',
  version: '3.5.16'
}
```

**Comment by BenMann** [comment]
Wow this is super strange! :-/
I actually clicked the link provided by @accommodavid before closing to make sure it appeared, as it seemed weird that this was fixed. d3 was definitely in the results, right on top! However I have no idea why it disappeared again or how this is even possible. When I closed I was under the impression that indexing took literally forever and now it just finished and everything is okay. Apparently that's not the case.

**Comment by echavezNS** [comment]
Hi @mbostock, it looks like the package is registered under the name of **test-d3** and not just **d3.** I'm worndering if you named it like that when you registered the package.

``` 
$ bower info test-d3#3.5.16
bower cached        git://github.com/mbostock-bower/d3-bower.git#3.5.16
bower validate      3.5.16 against git://github.com/mbostock-bower/d3-bower.git#3.5.16

{
  name: 'd3',
  description: 'A JavaScript visualization library for HTML and SVG.',
  main: 'd3.js',
  license: 'BSD-3-Clause',
  ignore: [],
  homepage: 'https://github.com/mbostock-bower/d3-bower',
  version: '3.5.16'
}

```

And it still working for `bower search test-d3`

```
$ bower search test-d3 

Search results:

    test-d3 git://github.com/mbostock-bower/d3-bower.git

```

**Comment by mbostock** [comment]
If the `test-d3` package is a duplicate package definition, why would that effect the behavior of the `d3` package or searching for `d3`?

I don’t recall creating the `test-d3` package. I tried to unregister it, but it looks like that’s temporarily disabled.

```
$ bower unregister test-d3
? You are about to remove component "test-d3" from the bower registry (https://bower.herokuapp.com). It is generally considered bad behavior to remove versions of a library that others are depending on. Are you really sure? Yes
bower unregister    test-d3
bower EFORBIDDEN    Unpublishing bower packages is temporarily disabled
```

**Comment by mbostock** [comment]
(Also, there’s nothing to prevent people besides the author, i.e. the owner of the git URL, from registering multiple aliases pointing to the same URL, right?)

**Comment by echavezNS** [comment]
I tested it, I clone a package and registered pointing to an existing repository and bower let me do that. It looks that just the name has to be unique. So, if you didn't register the name `test-d3` then someone else did it. My question is, did you already registered the package with the name `d3` right?

**Comment by echavezNS** [comment]
The `unregister` option is temporarily disable as in this issue says #2210

**Comment by mbostock** [comment]
@echavezNS Sorry, but I don’t understand how your comments are relevant to this issue. This issue pertains to Bower search, i.e., the `bower search` command and http://bower.io/search/?q=d3. I registered the `d3` package years ago and `bower info d3` and `bower install d3` both work fine.

**Comment by echavezNS** [comment]
What I'm trying to say is that there is a package called **test-d3** and you can't `unregister` it because in fact that feature is disabled. So, if `info` and `install` works then there is something wrong with `search`.

**Comment by piotrjaw** [comment]
The query behind ```bower search {{name}}``` is actually a request to ```http://bower.herokuapp.com/packages/search/{{name}}``` which performs a query to the database with a ```LIKE``` statement in the ```WHERE``` clause and a default limit of 30 resulst, sorted descending by hits. Now you do the same query with a limit of 300 (http://bower.herokuapp.com/packages/search/d3?limit=1000) you'll notice, that there is something like ```{"name":"d3","url":"git://github.com/mbostock-bower/d3-bower.git"}``` fairly close to the end, and it's the one, right? The result's the same when you execute the fetch request (http://bower.herokuapp.com/packages/d3), which performs a query with a exact name check in the ```WHERE``` clause. Might that be the case?

**Comment by sheerun** [comment]
I improved search results so they should be better now.
