### ISSUE TITLE
commandFactory is swallowing exceptions

### ISSUE THREAD

**Issue by katemihalikova** [bower/bower#2187]
[This changed line](https://github.com/bower/bower/commit/b9718bb30982dc32c44836d5a49baa28d823dd16#diff-8414423e549b00cb30763e9749cee3c6L61) in `commandFactory` prevents errors thrown during emitting `'end'` event in `.then` handler to propagate and those errors are swallowed.

**Code used:**
```javascript
bower.commands.list().on('end', function() {throw new Error('test');});
```

**In v1.7.0 and earlier**, error is thrown:
**In v1.7.1 and later**, nothing is thrown and the error is swallowed.
**Expected behaviour**:
Error is rethrown as before _or_ emitted via the logger `logger.emit('error', error);`.

**Comment by faceleg** [comment]
Thanks for reporting this.

When I run your example:

```JS
var bower = require('bower');
bower.commands.list().on('end', function() {throw new Error('test');});
```

With 1.7.1, the code runs then exits. With 1.7.2 it seems to hang forever. Is this similar to what you reported?

**Comment by katemihalikova** [comment]
The change was done between v1.7.0 and v1.7.1, sorry for that. I have updated the issue. Please try the snippet above in those two versions to see the difference.

**Comment by thinkxl** [comment]
I just tried the code above with 1.7.7 and the code runs then exits.

**Comment by katemihalikova** [comment]
For me, the problem is not hanging, but Error swallowing. When an exception occurs in the callback, bower should not ignore it.

```bash
$ npm i bower@1.7.0
...
$ node -e "require('bower').commands.list().on('end', function() {throw new Error('test');});"
C:\test\node_modules\bower\node_modules\q\q.js:155
                throw e;
                ^

Error: test
    at Logger.<anonymous> (C:\test\test.js:5:52)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (C:\test\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\test\node_modules\bower\lib\commands\index.js:65:25
    at _fulfilled (C:\test\node_modules\bower\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\test\node_modules\bower\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\test\node_modules\bower\node_modules\q\q.js:796:13)
    at C:\test\node_modules\bower\node_modules\q\q.js:604:44
    at runSingle (C:\test\node_modules\bower\node_modules\q\q.js:137:13)

$
```

```bash
$ npm i bower@1.7.1
...
$ node -e "require('bower').commands.list().on('end', function() {throw new Error('test');});"

$
```

```bash
$ npm i bower@latest
...
$ node -e "require('bower').commands.list().on('end', function() {throw new Error('test');});"

$
```

**Comment by sheerun** [comment]
Thank you for reporting this. It's not fixes in master branch
