### ISSUE TITLE
Transfer github repo and update bower URL

### ISSUE THREAD

**Issue by leocaseiro** [bower/bower#2188]
Hi, I'm going to transfer a repo from an organization to a member on github and I'm worried how do I keep bower working.

Will work it automatically from redirect 401/redirect github or something like that?
Or should I unregister and then register with same name(is that possible)?

I don't want to change the name on bower, want to keep because the bower is well used.

Thanks

**Comment by rajzshkr** [comment]
You can follow the below command (You have to be the author of the bower package)

bower unregister packagename

bower register packagename url.

**Comment by leocaseiro** [comment]
I'm collaborator of the project. Is that mean I'm also the author of the bower package? Because the person in charge no longer access github...

**Comment by leocaseiro** [comment]
Thanks @rajzshkr it worked like a charm!
