### ISSUE TITLE
bower install don't get files in bower_components

### ISSUE THREAD

**Issue by bgolubovic** [bower/bower#2194]
Hi all,

After installing dependency, bower finish it. But there are not files actually, in folder bower_components.
Is bower sending files elsewhere or how does this works now?

Thank you.

**Comment by dprice809** [comment]
What repository are you trying to download? Are you using the standard install command?
`bower install package_name`

**Comment by bgolubovic** [comment]
@dprice809 
Any repository that I install (download) don't shows files physically in project folder 'bower_components'.
But dependencies are working. So it is getting the files from other place.
I just realize that this folder exist also in a root of local disk [E:] and there are files. I did not change anything. What should I do?
Do I need to change something in bower.json, or init bower again...?
Thank you.

**Comment by dprice809** [comment]
If you are installing a package you should not need to use `init bower`. `Init bower` is reserved for when you are creating your own package. Are you installing a package or creating a package?

`Bower install` by default will install to what ever directory your console is open in. So you may have had the E: drive selected when you installed you packages.

**Comment by bgolubovic** [comment]
@dprice809 Okay, about bower init it is clear. I know that. I am installing package. Console is in project directory, not in E: drive. Thank you.

**Comment by dprice809** [comment]
From my understanding the bower.json files are not specific about where to install a bower package. However, a `.bowercc` file could specify a`directory` to install the package. If `directory` is defined as a FQD it may be able to define a specific drive to install a package. If you do not see any strange `.bowercc` files, you may want to try a fresh install of bower.

**Comment by dprice809** [comment]
Also, see [this](https://github.com/bower/spec/blob/master/config.md) file for `.bowercc` specification

**Comment by bgolubovic** [comment]
@dprice809  I have `.bowercc` file in project. There is in it `"directory" : "/bower_components"`. And I did not change it since project started, and as I said, it moves files itself to `E:/bower_components`. Project is in `E:\SCJohnsonMVC\SCJohnsonMVC.Off.Web\Content\Off`. Thank you.

**Comment by echavezNS** [comment]
Probably you have the `cwd` option configured like that in the  `.bowerrc` file, see [this](https://github.com/bower/spec/blob/master/config.md#cwd). I you have configured that, then you should remove the option.

**Comment by bgolubovic** [comment]
@echavezNS No, I don't have. What I did to fix this issue is to set `directory" : "/bower_components` to `directory" : "E:/***/****/Content/Off/bower_components` in `.bowerrc`.

**Comment by BenMann** [comment]
With that you probably overwrote an existing config. Bower looks in various places as described [here in the docs](http://bower.io/docs/config/#placement--order). The `.bowerrc` in your cwd is always the strongest, so this is an absolutely valid solution.

I think this an individual case and will close for now. If others see this happening, let us know :cake:

**Comment by dm-grinko** [comment]
I have the same issue
