### ISSUE TITLE
Bower doesn't close itself after running `bower install`

### ISSUE THREAD

**Issue by ajoys** [bower/bower#2198]
When I run bower install, everything installs as expected, however bower doesn't close itself and I have to manually exit. Any idea how to fix this?

**Comment by echavezNS** [comment]
@ajoys can you please upload the `bower.json` file that you are trying to read? May be there is something wrong with one  dependency.

**Comment by faceleg** [comment]
@ajoys please upload the bower.json file in question.

**Comment by ajoys** [comment]
Hi sorry about the delay. Here is the bower.json file that I am currently using.

```
{
  "name": "app",
  "version": "0.0.0",
  "dependencies": {
    "angular": "1.5.0",
    "bootstrap": "^3.2.0",
    "angular-animate": "^1.4.9",
    "angular-cookies": "^1.4.0",
    "angular-resource": "^1.4.0",
    "angular-route": "^1.4.0",
    "angular-sanitize": "^1.4.0",
    "angular-touch": "^1.4.0",
    "angular-socket-io": "~0.7.0",
    "angular-ui-router": "~0.2.15",
    "angular-timeago": "~0.2.4",
    "ment.io": "~0.9.24",
    "material-design-icons": "~2.1.3",
    "animate.css": "~3.5.1",
    "angular-moment": "^0.10.3",
    "moment": "^2.11.1",
    "ngMorph": "angular-morph#^0.1.0",
    "angular-emoji": "angular-emoji-filter#^0.0.2",
    "angular-web-notification": "^0.0.60",
    "angular-jwt": "^0.0.9",
    "angular-environment": "~1.0.3"
  },
  "resolutions": {
    "angular": "1.5.0",
    "moment": "2.10.6"
  },
  "devDependencies": {
    "angular-mocks": "^1.4.0"
  },
  "appPath": "app",
  "moduleName": "appApp",
  "overrides": {
    "bootstrap": {
      "main": [
        "less/bootstrap.less",
        "dist/css/bootstrap.css",
        "dist/js/bootstrap.js"
      ]
    }
  }
}
```

**Comment by ajoys** [comment]
@faceleg @echavezNS I have included my bower file above. Thanks!

**Comment by BenMann** [comment]
Works for me. However `material-design-icons` is a **HUGE** package and you may just have to wait for it in the install process. The download alone is ~30MB and installation took forever. Also note that there are version conflicts with angular, which you might want to resolve manually.

**Comment by BenMann** [comment]
@ajoys can you confirm that it's not just hanging because of the rather long installation mentioned above?

**Comment by ajoys** [comment]
That seems to be the issue, removed it and my install time drastically changed. Thanks @BenMann !
