### ISSUE TITLE
bower install bootstrap excluding tests folder

### ISSUE THREAD

**Issue by qcgm1978** [bower/bower#2199]
Hello:
       I want to install bootstrap by bower, but the result is not full. e.g. the js/tests folder not in my bower_component/bootstrap. Why? Event the folder is exist in my downloaded bootstrap folder and I install it by local path, it still doesn't exist.

Best Regards

**Comment by echavezNS** [comment]
I think the directory is ignored because in the bower.json file from the bootstrap repository this directory is ignored as you can see here:

`"ignore": [
    "/.*",
    "_config.yml",
    "CNAME",
    "composer.json",
    "CONTRIBUTING.md",
    "docs",
    "js/tests",
    "test-infra"
  ]`

**Comment by qcgm1978** [comment]
@echavezNS You are right. It works if I fork it first. The bower.json is normal when I fork the repository firstly. So maybe forking the repository is right step if I want the full codebase.
