### ISSUE TITLE
Recieving `ENORESTARGET` for versions with a `+` in them

### ISSUE THREAD

**Issue by copenhas** [bower/bower#2200]
I'm getting the `ENORESTARGET` error for bootswatch right now, but my guess is maybe an issue with versions that include `+<build>`. It worked on the initial `bower install --save bootswatch`. I have several other dependencies in my `bower.json` that are plain `x.y.z` version format that seem unaffected (mostly the default ember 2.3 stuff).

If `bootswatch` is not in my `bower.json` then I receive this output:

```
app>bower install --save bootswatch
bower cached        git://github.com/thomaspark/bootswatch.git#3.3.6+1
bower validate      3.3.6+1 against git://github.com/thomaspark/bootswatch.git#*
bower cached        git://github.com/twbs/bootstrap.git#3.3.6
bower validate      3.3.6 against git://github.com/twbs/bootstrap.git#~3.3.6
bower install       bootswatch#3.3.6+1
bower install       bootstrap#3.3.6

bootswatch#3.3.6+1 bower_components\bootswatch
└── bootstrap#3.3.6

bootstrap#3.3.6 bower_components\bootstrap
└── jquery#2.1.4
```

After that if anyone without `bootswatch` runs a `bower install` they will receive this output:

```
app>bower install
bower not-cached    git://github.com/thomaspark/bootswatch.git#^3.3.6+1
bower resolve       git://github.com/thomaspark/bootswatch.git#^3.3.6+1
bower ENORESTARGET  Tag/branch ^3.3.6+1 does not exist

Additional error details:
Available tags: v2.0.0, v2.0.1, v2.0.2, v2.0.3, v2.0.4, v2.1.0, v2.1.1, v2.1.1+1, v2.2.2, v2.2.2+1, v2.2.2+2, v2.3.0, v2.3.0+1, v2.3.0+2, v2.3.1, v2.3.1+1, v2.3.2, v3.0.0, v3.0.0-rc1, v3.0.0-rc2, v3.0.1, v3.0.2, v3.0.2+1, v3.0.2+2, v3.0.3, v3.0.3+1, v3.1.0, v3.1.0+1, v3.1.1, v3.1.1+1, v3.2.0, v3.2.0+1, v3.2.0+2, v3.2.0+3, v3.2.0+4, v3.3.0, v3.3.1, v3.3.1+1, v3.3.1+2, v3.3.1+3, v3.3.2, v3.3.4, v3.3.4+1, v3.3.5, v3.3.5+1, v3.3.5+2, v3.3.5+3, v3.3.5+4, v3.3.6, v3.3.6+1

Available branches: gh-pages, master
```

I have confirmed this behavior in ConEmu, plain ol' cmd.exe, and Git Bash. I have also tried disabling `Inject ConEmuHk` (per https://github.com/bower/bower/issues/852#issuecomment-145169743) in ConEmu with no effect on behavior:
![capture](https://cloud.githubusercontent.com/assets/357338/13672512/19713416-e6a3-11e5-9b4e-41db1faf84e8.PNG)

What I have found is if I bump the version down to `v3.3.6` instead of `v3.3.6+1` then the `bower install` command succeeds:

```
app>bower install
bower bootswatch#^3.3.6         cached git://github.com/thomaspark/bootswatch.git#3.3.6+1
bower bootswatch#^3.3.6       validate 3.3.6+1 against git://github.com/thomaspark/bootswatch.git#^3.3.6
bower bootstrap#~3.3.6          cached git://github.com/twbs/bootstrap.git#3.3.6
bower bootstrap#~3.3.6        validate 3.3.6 against git://github.com/twbs/bootstrap.git#~3.3.6
bower bootswatch#^3.3.6        install bootswatch#3.3.6+1
bower bootstrap#~3.3.6         install bootstrap#3.3.6

bootswatch#3.3.6+1 bower_components\bootswatch
└── bootstrap#3.3.6

bootstrap#3.3.6 bower_components\bootstrap
└── jquery#2.1.4
```

I'm running:

```
Windows 7 Professional SP 1
git version 1.9.5.msysgit.0
node v4.2.1
bower 1.7.7
```

**Comment by faceleg** [comment]
@bower/windows please can you have a look at this one?

**Comment by rossanthony** [comment]
This isn't a windows specific issue, I'm getting the same error when try to do a bower install on Mac OSX 10.11.3

`bower bootswatch#~3.3.6+1            ENORESTARGET Tag/branch ~3.3.6+1 does not exist`

The bower.json I'm installing from contains the same reference to the [latest version of bootswatch](https://github.com/thomaspark/bootswatch/releases) which happens to contain a "+" in the version number. This does seem a little odd as all other versions I've come across are decimals, just digits and dots.

**Comment by echavezNS** [comment]
I actually tested, I upgrade `semver` to `4.0` and this solve the issue, but I can see that there are some test that fail when I run `npm test`, things related with **GitResolver**, to be honest I'm not an expert in test so I will have to figure it out how to solve the test before I send a PR.

**Comment by sheerun** [comment]
We cannot upgrade to sember to 4.0 because it breaks backward compatiblity (it treats prereleases differently). You can install tag directly though, even with +: `bower install 'https://github.com/thomaspark/bootswatch.git#3.3.6+1'`
