### ISSUE TITLE
bower-installer package maintainer requires support

### ISSUE THREAD

**Issue by rquadling** [bower/bower#2202]
> I am no longer able or interested in maintaining this project. Is anyone in the community interested in doing so?

https://github.com/blittle/bower-installer/issues/149

As a user of bower-installer, I'd really like the functionality to remain available and maintained. Ideally, integrated into bower.

In most cases, when I use bower I just want the code to integrate and ship with my app. No docs, tests, crud, cruft.

**Comment by BenMann** [comment]
As far as I can tell the project wasn't actively maintained for an entire year now and is not in sync with its docs.. which is okay, things happen but I personally wouldn't consider maintaining it.

However(!) I do think one part of the project could be interesting and be added without breaking backwards compatibility and that is **the option to move files into a certain directory and renaming them** after the download. I personally don't see much benefit from fetching only main files, as a standardized way of fetching packages (as we have now) is quite awesome and also works if the main files ever get renamed by the owner or none is defined, which is definitely a problem.

Before going any further I will also say that the above is already possible with postinstall hooks that just move and/or rename files like that `mv bower_components/jquery/index.js wherever/whatever.js`. At the same time you could write a pluggable resolver to achieve the same result.

If this would be something people are interested in I would propose a syntactically simpler version, like this.
```
{
  "dependencies" : {
    "jquery" : "latest",
    "bootstrap": "latest
  },
  "paths": {
    "bower_components/jquery/jquery.js": "./js/jquery.js",
    "bower_components/bootstrap/less/bootstrap.less": "./css/bootstrap.less",
    "bower_components/bootstrap/dist/js/bootstrap.js": "./js/bstrp.js",
  }
}
```
Both sides of the `paths` object would always assume the `cwd` (where the bower.json is located) as the starting point. Left side could even assume starting in `bower_components`.

With all of the above I still think postinstall hooks ([more here](https://github.com/bower/spec/blob/master/config.md#scripts)) are the right way to tackle this problem. However that's just my two cents. I have seen quite a few people in the need to move stuff around, but they never really consider using hooks for it. Anyway I understand the need to move things around.

**Comment by rquadling** [comment]
Considering the fact that there will be a lot of people renaming/moving files, a standardised way to implement that without everyone having to roll their own post-install hook would certainly be useful.

**Comment by BenMann** [comment]
@rajzshkr did you close this by accident? (I guess so?) :lollipop: 
ping @bower/contributors for more voices.

**Comment by dvidsilva** [comment]
I wasn't aware of that project, it looks like there's some cool things we can add. Would it make sense to select some features and come up with a timeline and add them to bower? It might be easier to maintain that way than a different project.

**Comment by rajzshkr** [comment]
@BenMann oops

**Comment by BenMann** [comment]
@dvidsilva sure thing — Want to make a start with that list?
@rquadling if you also have certain features you are especially interested in seeing in Bower, you could add those to the list and we then see where exactly to implement and start working on them together.

**Comment by dvidsilva** [comment]
Sorry, I was AFK for a couple days. Where would be the best place to do that list? 

Tho it looks like fully integrating it might be a good thing, unsure of the effort required but will think more about it. @rquadling do you know which other collaborators will remain and if they would prefer to merge or continue as a separate project?

**Comment by rquadling** [comment]
I've been granted collaborator access to bower-installer. I think I'm the only person willing to do any work with it at the moment. My JS skills aren't as good as they could be so I'm really here to make sure bower-installer doesn't die and, at the bare minimum, remains compatible with bower (in as far as it needs to).

I think having this feature as part of bower would make sense to me, so maybe as a new feature branch that, when ready, can be merged in.

I'm willing to work with someone on this, just not take the lead.

**Comment by thinkxl** [comment]
@rquadling I can help too, if there is any direction that we need to follow, or just check everything and decide for ourselves?

**Comment by BenMann** [comment]
Good to see that it's not just silently dying!
I'd suggest splitting the project into smaller chunks that can be implemented separately into Bower, or keeping it a separate project and work on that (as there is also some traction in the [original issue](https://github.com/blittle/bower-installer/issues/149) now). Either way, making a list of chunks to work on can happen right here, or over at the original repo in a separate issue. I think a simple issue is good enough for that :)
Just need someone to make the first step!

**Comment by sheerun** [comment]
I think what you really want in bower is some kind of pluggable post-processors. I've described it in: #1930

@rquadling Maybe you'd like to prepare daft of such API? Similar to http://bower.io/docs/pluggable-resolvers/

**Comment by nevin** [comment]
i can also help
