### ISSUE TITLE
bower installing packages without .js files in them

### ISSUE THREAD

**Issue by christianscott** [bower/bower#2205]
I've got my bower.json file setup and it installs the packages, but without it's .js files in some of them.

For example "bower install moment", it installs moment without it's folders and .js files. It only downloads the .json and .md files.

Any suggestions would be appreciated.
Thanks

**Comment by paulohp** [comment]
I'd never experienced something like that. Do you have any log to show to us?

**Comment by christianscott** [comment]
I resolved the issue by running "bower cache clean".

Thanks.
