### ISSUE TITLE
bower should avoid name collision in /tmp

### ISSUE THREAD

**Issue by icarito** [bower/bower#2206]
Bower fails when a directory has the name of the project under /tmp - it should instead use a temporary unique name in this case to avoid failing.

**Comment by ptitgraig** [comment]
Hello.
Can you show the error stack you get.

**Comment by rajzshkr** [comment]
I tried the same, but works for me. Can you show the log and give more details like os, bower version.

**Comment by jywarren** [comment]
Here's the error -- I caused it by creating a file at `/tmp/mapknitter` with sudo, so bower presumably didn't have the rights to move/delete/rename it. Removing `/tmp/mapknitter` resolves the error.  

````
mapknitter@tycho2:~/rails3.mapknitter.org$ bower install
bower webgl-distort#*       not-cached git://github.com/jywarren/webgl-distort.git#*
bower webgl-distort#*          resolve git://github.com/jywarren/webgl-distort.git#*
bower webgl-distort#*          ENOTDIR ENOTDIR, mkdir '/tmp/mapknitter/bower'

Stack trace:
Error: ENOTDIR, mkdir '/tmp/mapknitter/bower'

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:45:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:788:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:604:44
System info:
Bower version: 1.4.1
Node version: 0.10.29
OS: Linux 3.2.0-4-amd64 x64
mapknitter@tycho2:~/rails3.mapknitter.org$ 
````

This is Debian (wheezy, right @icarito?) and the file was originally an nginx conf file, but for reproducing it it was just an empty file (`sudo touch /tmp/mapknitter`). Thanks!

**Comment by icarito** [comment]
Yes debian wheezy and bower 1.4.1. :-)

**Comment by BenMann** [comment]
@icarito any chance to upgrade Bower to latest? 1.4.1 is rather old :older_man:

**Comment by ptitgraig** [comment]
try to manually delete `~/.cache/bower`.

**Comment by sheerun** [comment]
Hey. Please try newest bower and submit issue according to guidelines: https://github.com/bower/bower/wiki/Report-a-Bug
