### ISSUE TITLE
Inherit overrides from dependencies

### ISSUE THREAD

**Issue by NielsHolt** [bower/bower#2209]
Hi
I think it would be a nice feature if the overrides made by a dependencies on its own dependencies is automatic inherited 
Example:
RepoA don't have a 'main' in its bower.json
RepoB using RepoA and have a 'overrides' section for RepoA
RepoC using RepoB but will get an error by 'bower install' because RepoA don't have a main-section

Suggestion: Since RepoC is depending of RepoA indirectly by using RepoB it should Inherit the overrides for RepoA from RepoB

Kind Regards

Niels Holt

**Comment by sheerun** [comment]
Bower is deprecated and in maintenance mode, so we won't implement new features like this one. We recommend switching to yarn and migrating legacy projects to it with [bower-away](https://github.com/sheerun/bower-away)
