### ISSUE TITLE
Cant `bower install` 

### ISSUE THREAD

**Issue by SupremeTechnopriest** [bower/bower#2227]
`bower install` throws no errors and installs no packages.  This project has really gone downhill.  Why has a broken version been published for so long?

`node -v v5.7.0`
`bower -v 1.7.7`

**Comment by echavezNS** [comment]
Can you show some kind of log, so we can see what's going on?

**Comment by SupremeTechnopriest** [comment]
Unfortunately there is no log.  It either silently fails or exits without an exception. The best way to reproduce it is:

1. set up a `node v5.7.0` environment
2. `npm i -g bower` 
2. create a `bower.json` file and add some dependencies
3. `bower install` 

I've seen the problem in smartOS, but haven't tested it on other operating systems.

I worked around it by downgrading to `1.6.x`

Hope this helps.

**Comment by echavezNS** [comment]
What if you run `bower install --verbose`?

**Comment by sheerun** [comment]
Works for me on osx

**Comment by rajzshkr** [comment]
it works for me too in OSX

**Comment by nathanchapman** [comment]
@SupremeTechnopriest any update on this?

**Comment by SupremeTechnopriest** [comment]
I would need to spin up a new smartOS zone to test it. Im a bit busy at the moment, and using 1.6 solved my problem, so I guess you can close this for now and I will reopen it the next time I set up a machine.  Ill try to run with verbose flag and post as much output as possible.  Some of my colleagues did verify that they had the same issue on smartOS.

**Comment by protzman** [comment]
A thought - You say colleagues as if you are an employee in an office somewhere. Depending on your company's firewall settings you may not be getting what you need. Myself and a few developers on my team had run into issues of this nature. I'd run bower install too, and it appeared the command had executed, threw no errors, but did not install what I needed. When I tried later at home it worked flawlessly.

**Comment by SupremeTechnopriest** [comment]
Interesting idea @protzman. I work from home 4 out of 5 days and I don't believe it to be a firewall issue, however, I do connect to our cloud through a vpn.  It's odd that its just this version of bower that fails.  The SmartOS version I'm running is `15.4 TLS`

**Comment by protzman** [comment]
Not too sure what SmartOS is, but was just a thought to why the install might fail. I am also in a similar situation where I work from home sometimes, connecting through vpn, and even then though I'm coming from my home network since I am essentially working on the work network it will fail. But on my personal network it would work. Not version specific either. For me it is just what repositories my company allowed us to access. Worth a try but outside of that - sorry I can't provide much more help :relieved:
