### ISSUE TITLE
Problem with bower pulling wrong content from correct commit

### ISSUE THREAD

**Issue by kwypchlo** [bower/bower#2228]
Hi, I have a weird problem on one of my repos at work. It happens only on jenkins so it may be connected to some ancient git version (1.7.1). Take a look:

**This is what bower.json looks like on 0.23.0 when viewed from gitlab**
```
{
  "appPath": "src",
  "dependencies": {
    "angular": "^1.4.0",
    "angular-cookies": "^1.4.0",
    "angular-gettext": "~2.1.0",
    "angular-local-storage": "0.2.3",
    "angular-messages": "^1.4.0",
    "angular-ui-router": "^0.2.15",
    "es5-shim": "~4.1.3",
    "lodash": "~3.9.3",
    "restangular": "~1.5.1",
    "es-common": "https://xxgit1.xxx.com/ngin-boa/es-common.git#0.23.0",
    "es-typecode-ui": "https://xxgit1.xxx.com/ngin-boa/es-typecode-ui.git#0.23.0"
  },
  "devDependencies": {
    "angular-mocks": "^1.4.0",
    "angular-scenario": "^1.4.0"
  },
  "name": "es-auth-ui",
  "version": "0.23.0",
  "main": [
    "README.md"
  ]
}
```

**and this is .bower.json from bower cache when downloaded as a dependency**
```"es-auth-ui": "https://xxgit1.xxx.com/ngin-boa/es-auth-ui.git#0.23.0"```
```
{
  "appPath": "src",
  "dependencies": {
    "angular": "^1.4.0",
    "angular-cookies": "^1.4.0",
    "angular-gettext": "~2.1.0",
    "angular-local-storage": "0.2.3",
    "angular-messages": "^1.4.0",
    "angular-ui-router": "^0.2.15",
    "es5-shim": "~4.1.3",
    "lodash": "~3.9.3",
    "restangular": "~1.5.1",
    "es-common": "https://xxgit1.xxx.com/ngin-boa/es-common.git#develop",
    "es-typecode-ui": "https://xxgit1.xxx.com/ngin-boa/es-typecode-ui.git#develop"
  },
  "devDependencies": {
    "angular-mocks": "^1.4.0",
    "angular-scenario": "^1.4.0"
  },
  "name": "es-auth-ui",
  "version": "0.23.0",
  "main": [
    "README.md"
  ],
  "_release": "0.23.0",
  "_resolution": {
    "type": "version",
    "tag": "v0.23.0",
    "commit": "eb63d298635302d1f73590f19ae601a50b448c57"
  },
  "_source": "https://xxgit1.xxx.com/ngin-boa/es-auth-ui.git",
  "_target": "0.23.0"
}
```

The difference is that the file you see in `.bower.json` is actually from develop branch (check out these 2 dependencies that have #develop appended instead of correct version) while commit `eb63d298635302d1f73590f19ae601a50b448c57` points to 0.23.0 tag

```eb63d298635302d1f73590f19ae601a50b448c57 refs/tags/v0.23.0```

Develop is my default branch so this is what my 6th sense is telling me:
- bower cloned repo (by default develop branch)
- tried to change to tag 0.23.0 but failed silently
- bower assumed that it worked fine, just used develop version and marked is as 0.23.0

:cry:

**Comment by sheerun** [comment]
Could you prepare something to reproduce? For example Dockerfile?

**Comment by kwypchlo** [comment]
Well I cannot reproduce that right now, I already upgraded git everywhere so I guess until someone else finds this issue we can close it :)
