### ISSUE TITLE
Version 1.7.8 introduces breaking behavior on parsing of name field

### ISSUE THREAD

**Issue by BrianAdams** [bower/bower#2233]
I have a bower file that is basically a place holder for dependencies. It has a name field that includes a space.  But with this mornings upgrade to 1.7.8, bower now fails to parse the bower.json file with the following error:

```
bower EINVALID      Failed to read bower.json
Additional error details:

Name must be lowercase string, with dots, dashes, or @
```

The work around was to change the name field so that it passes that validation that has been added.  Assuming that this is an intentional change, it would be nice to have an update in the change log to indicate that additional validation has been added.

Further investigation shows that there are published bower dependencies I am using that also have names that now fail validation.  

To prevent breaking all of these installs, it would be nice if this validation was a warning instead of an error to give everyone time to upgrade their bower files

**Comment by marr75** [comment]
We have the same issue, example depedency:
https://github.com/jpillora/xdomain/blob/gh-pages/bower.json

**Comment by ryaz** [comment]
Same issue...

**Comment by sheerun** [comment]
I've added missing changelog entry. This change has been done to improve the registry and accept only package names that don't cause issues with bower resolution (`/^[a-zA-Z0-9_][a-zA-Z0-9\.\-_]*$/`).

Spaces and slashes and other non-standard characters are known to be causing issues..

I'm on my way to revert this behavior for the sake of backward compatibility. In the meantime i've changed bower latest version to 1.7.7, so for now things should calm down. I'll ask to to test bower 1.7.9 soon.

**Comment by sheerun** [comment]
@BrianAdams @ryaz Could you post package names that caused issues?

**Comment by ryaz** [comment]
@sheerun I'm using bower-rails gem and it creates bower.json with space in name: ` "name": "dsl-generated dependencies",`

**Comment by sheerun** [comment]
@ryaz @BrianAdams @marr75 Please try `npm install -g bower@1.7.9`. It'll be published as latest in few hours..

**Comment by sheerun** [comment]
Fixed in 1.7.9

**Comment by paulmenzel** [comment]
The behavior is still different between 1.7.7 and 1.7.9, when for example using *~* in the name. Is that expected?

**Comment by sheerun** [comment]
@paulmenzel What's the package?..

**Comment by paulmenzel** [comment]
The package name looks like below.

```
{
  "name": "go~mus-shop",
[…]
}
```

**Comment by sheerun** [comment]
I can make another release it it's really this important.

**Comment by paulmenzel** [comment]
@sheerun, we changed the name locally, so no hurry for us. Thank you for looking into it and responding.

**Comment by BrianAdams** [comment]
@sheerun, this is used by the google Polymer project: https://github.com/Kalitte/app-states/ and has the issue with spaces in the name.
