### ISSUE TITLE
Angular on Rails cannot find packages installed by Bower

### ISSUE THREAD

**Issue by RyanKim01** [bower/bower#2234]
Hi.
I'm following Thinkster's tutorial about Angular on Rails(https://thinkster.io/angular-rails#jumping-in-with-angular).
In this tutorial, I install front-end dependencies following way:
`bower install angular angular-ui-router bootstrap --save`

Then I require bootstrap in `application.css` in following way:
```
 *= require bootstrap/dist/css/bootstrap
 *= require_tree .
 *= require_self
```

And here is `application.js` file:
```
//= require angular
//= require angular-rails-templates
//= require angular-ui-router
//= require_tree .
```

When I run the rails server I get following errors,
```
1. couldn't find file 'bootstrap/dist/css/bootstrap' with type 'text/css'
2. couldn't find file 'angular' with type 'application/javascript'
```

Here is an error I'm getting from rails server console:
```
ActionView::Template::Error (couldn't find file 'bootstrap/dist/css/bootstrap' with type 'text/css'):
    2: <html>
    3: <head>
    4:   <title>FlapperNews</title>
    5: 	<%= stylesheet_link_tag    'application', media: 'all' %>
    6:   <%= javascript_include_tag 'application' %>
    7:   <%= csrf_meta_tags %>
    8: </head>
  app/assets/stylesheets/application.css:14
  app/views/layouts/application.html.erb:5:in `_app_views_layouts_application_html_erb___1398966333390810206_70171728569860'
```

I confirm that bootstrap and angular are correctly installed in Rails app. But it seems like it is not finding it in the app. What could be the problem?

**Comment by rajzshkr** [comment]
By default rails asset pipeline will check files in "vendor/assets/bower_components" directory. So make your  .bowerrc file configured to 
```
{
  "directory":"vendor/assets/bower_components"
}
```

**Comment by yelendisuresh** [comment]
still problem is not solved
