### ISSUE TITLE
Change all git://github.com urls in registry to https://github.com

### ISSUE THREAD

**Issue by sheerun** [bower/bower#2235]
According to [this article](https://gist.github.com/grawity/4392747) git:// protocol doesn't support encryption, is often blocked by firewalls and causes issues for users [so they try to bypass it](http://stackoverflow.com/questions/15669091/bower-install-using-only-https). On top of it github deprecated git:// long time ago.

Because of it I suggest to change all "git://github.com" urls in bower registry to "https://github.com".

The only backward-incompatibility I can see is if someone uses custom version-locking solution.

We could do trial run of such change and gather feedback in this issue.

**Comment by sheerun** [comment]
As a first step I've changed normalization in registry to normalize to https:// instead of git:// for new packages: https://github.com/bower/registry/commit/8235550837628b0cc1bfad114ca0bce59cdc23ee

**Comment by riyadhalnur** [comment]
I second it.

**Comment by paulohp** [comment]
We have all reasons to do this. I can help testing and implementing.

**Comment by sheerun** [comment]
Converted first batch of 1000 packages... Waiting for the effect

**Comment by sheerun** [comment]
Converted next batch of 5000 packages

**Comment by allenhartwig** [comment]
Concerned that the conversion is adversely affecting packages. A dependency on `"matchMedia": "~0.2.0"` is causing a build failure of: `git ls-remote --tags --heads git://github.com/paulirish/matchMedia.js/.git`

The `/` before `.git` seems to be the culprit. Could your conversion script be injecting the slash unintentionally?

**Comment by sheerun** [comment]
@allenhartwig This was not intentional. This is one of rare 26 packages that ending with `/` that has been affected. I already fixed all of them in registry. Please let me know if they install correctly again.

**Comment by sheerun** [comment]
Converted next 10000 packages to https://

**Comment by shibbybird** [comment]
@sheerun that fixed it thank you.

**Comment by sheerun** [comment]
half of the registry is now converted

**Comment by riyadhalnur** [comment]
will test it out

**Comment by sheerun** [comment]
OK, whole registry is now converted. Let's wait for feedback.

**Comment by mitrae** [comment]
I'm not sure if it is connect but id:/2247

**Comment by jelmerk** [comment]
This broke our build :( 

Copying my message from the mailing list : 

> Hi 
> 
> I am wondering if the package files hosted on bower.herokuapp.com where recently changed
> 
> For instance 
> 
> https://bower.herokuapp.com/packages/jquery  now returns
> 
> {"name":"jquery","url":"https://github.com/jquery/jquery-dist.git"}
> 
> Where in the past, or at least as early as end of last year (way back machine url : https://web.archive.org/web/20150922021845/https://bower.herokuapp.com/packages/jquery) it seems to have returned
> 
> {"name":"jquery","url":"git://github.com/jquery/jquery.git","hits":14384544}
> 
> 
> This caused issues for us because GitHubResolver treats https repositories as non public repositories
> See the code at https://github.com/bower/bower/blame/master/lib/core/resolvers/GitHubResolver.js#L33
> 
> For public repositories it will first try and download a zip archive and only when that fails will it try to do a checkout
> 
> For non public repositories it will always do a checkout.
> 
> However in some instances the contents of the zips is a lot different from what you get with a checkout. So I suspect this caused our build to fail. Was this recently changed? and if so have you considered that because of the logic in the GithubResolver this can have far reaching consequences?
> 
> --Jelmer

**Comment by sheerun** [comment]
This was done for all github.com urls
