### ISSUE TITLE
Is it possible to use Bower without Git?

### ISSUE THREAD

**Issue by aendrew** [bower/bower#2238]
Hi!
I'm using Bower's programmatic API in an AWS Lambda task, which I accomplished by using a version of Git compiled in Lambda's execution environment. Alas, today it has decided to spontaneously stop working, giving me the following error:

```
[Error: Failed to execute "git ls-remote --tags --heads https://github.com/jsoma/tabletop.git", exit code of #128 fatal: Unable to find remote helper for 'https' ] code: 'ECMDERR', details: 'fatal: Unable to find remote helper for \'https\'\n', exitCode: 128
```

My guess is that Git is needing Curl to consume packages via HTTPS, which now appears to suddenly be unavailable on Lambda.

To that end — is there any way of using Bower without having Git? I've noticed there's a way via SVN but I'm guessing that's even less likely to work on Lambda.

(Also, apologies if this is the wrong place to ask — I've tried on IRC like a week ago and still have not gotten any sort of response.)

**Comment by sheerun** [comment]
Maybe try following: `git config --global url."git://".insteadOf https://`

**Comment by aendrew** [comment]
Thanks @sheerun — that worked for the purpose of getting through my issue. My guess is that Git is kind of central to how Bower works so am closing with the belief there's no way to use Bower without having a Git binary available somewhere. If this is incorrect, please let me know. :smile: Thanks!

**Comment by sheerun** [comment]
This is correct. We mention it in the readme.
