### ISSUE TITLE
npm install bower is not working 

### ISSUE THREAD

**Issue by MahaSannasi** [bower/bower#2239]
Can anybody please help on the below issue :

![error-git](https://cloud.githubusercontent.com/assets/13997388/14354829/6aabdfba-fcfc-11e5-8412-89469a78f7bd.png)
C:\Users\Administrator\git\hygieia\UI>npm install bower
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "bower"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! Unexpected token C
npm ERR! Cannot GET /bower
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\git\hygieia\UI\npm-debug.log

**Comment by sheerun** [comment]
You should post it in npm's tracker, not here
