### ISSUE TITLE
invalid name?

### ISSUE THREAD

**Issue by marshfire** [bower/bower#2240]
Hi, I'm getting warnings that the meta info "name" of my private package is invalid. My bower file looks like this:

```
{
  "name": "orca-json-rpc",
  "dependencies": {
    "angular": "~1.5.*"
  },
  "devDependencies": {
    "angular-mocks": "~1.5.*"
  },
  "main": [
    "orcaJsonRpc.js"
  ],
  "version": "1.0.0"
}
```

I can not see the problem with the name.Is it that I use 2 dashes?

The doc says:

> name

Required

Type: String

The name of the package as stored in the registry.

Must be unique.
Should be slug style for simplicity, consistency and compatibility. Example: unicorn-cake
Lowercase, a-z, can contain digits, 0-9, can contain dash or dot but not start/end with them.
Consecutive dashes or dots not allowed.
50 characters or less.

**Comment by sheerun** [comment]
No error for me. Are you using 1.7.9?

**Comment by marshfire** [comment]
Yes, 1.7.9, The package is on a private bitbucket repository and is referenced as

```
"dependencies": {
   ...
    "orca-json-rpc": "http://<server>:7990/scm/uic/bower-orca-jsonrpc.git#^1.0.0"
}
```

**Comment by sheerun** [comment]
What is the name in the bower.json of latest semver tag in the repository that matches `^1.0.0`?

**Comment by marshfire** [comment]
a colleague of mine did not have this problem also, might have to do with the bower-art-resolver that I experimented with last week. Closing the issue.
