### ISSUE TITLE
Bower on Azure Fails ECMDERR 128

### ISSUE THREAD

**Issue by jrmaingo** [bower/bower#2241]
HI I've been having a tough time trying to deploy to azure using bower so I just wanted to make sure you guys were aware of this issue.

Here is the output when I run bower install from the debugging console on azure

> bower angular#^1.4.0            cached https://github.com/angular/bower-angular.git#1.5.3
> bower angular#^1.4.0          validate 1.5.3 against https://github.com/angular/bower-angular.git#^1.4.0
> bower bootstrap#^3.2.0          cached https://github.com/twbs/bootstrap.git#3.3.6
> bower bootstrap#^3.2.0        validate 3.3.6 against https://github.com/twbs/bootstrap.git#^3.2.0
> bower angular-animate#^1.4.0    cached https://github.com/angular/bower-angular-animate.git#1.5.3
> bower angular-animate#^1.4.0  validate 1.5.3 against https://github.com/angular/bower-angular-animate.git#^1.4.0
> bower angular-cookies#^1.4.0    cached https://github.com/angular/bower-angular-cookies.git#1.5.3
> bower angular-cookies#^1.4.0  validate 1.5.3 against https://github.com/angular/bower-angular-cookies.git#^1.4.0
> bower angular-route#^1.4.0      cached https://github.com/angular/bower-angular-route.git#1.5.3
> bower angular-route#^1.4.0    validate 1.5.3 against https://github.com/angular/bower-angular-route.git#^1.4.0
> bower angular-sanitize#^1.4.0   cached https://github.com/angular/bower-angular-sanitize.git#1.5.3
> bower angular-sanitize#^1.4.0 validate 1.5.3 against https://github.com/angular/bower-angular-sanitize.git#^1.4.0
> bower angular-mocks#^1.4.0      cached https://github.com/angular/bower-angular-mocks.git#1.5.3
> bower angular-mocks#^1.4.0    validate 1.5.3 against https://github.com/angular/bower-angular-mocks.git#^1.4.0
> bower angular-route#^1.4.0     ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/angular/bower-angular-route.git", exit code of #128 fatal: unable to access 'https://github.com/angular/bower-angular-route.git/': Could not resolve host: github.com
> 
> Additional error details:
> fatal: unable to access 'https://github.com/angular/bower-angular-route.git/': Could not resolve host: github.com

I don't have any issues with installing npm packages or running "git ls-remote --tags --heads https://github.com/angular/bower-angular-route.git" from the same console so I can only think that this is some sort of bower issue.
_Note: this error happens using node_modules/.bin/bower and node_modules/.bin/bower.cmd_

Right now I have gotten around the problem by manually adding the packages to the deployment and skipping the install step but that isn't really a solution.

I'll do my best to provide more info if you need anything, **thanks for all the work you guys are doing**

node version: 4.2.3
npm version: 3.5.1
bower version: 1.7.9

**Comment by BenMann** [comment]
Does the problem still exist?
Have you tried any of [those recommendations](http://stackoverflow.com/questions/21544803/git-bower-errors-exit-code-128-failed-connect)? Is a proxy involved?

**Comment by jrmaingo** [comment]
Yes I have tried most of those recommendations but I don't have permission to access the network setting on azure so I can't really do anything about a proxy if there is one. Running the commands git manually does work which made me think that a proxy wasn't the issue.

I just tried running it again and got the following output. It looks like it starts running properly but breaks after a little bit

> bower angular-mocks#1.4.8   not-cached https://github.com/angular/bower-angular-mocks.git#1.4.8
> bower angular-mocks#1.4.8      resolve https://github.com/angular/bower-angular-mocks.git#1.4.8
> bower font-awesome#^4.5.0       cached https://github.com/FortAwesome/Font-Awesome.git#4.6.1
> bower font-awesome#^4.5.0     validate 4.6.1 against https://github.com/FortAwesome/Font-Awesome.git#^4.5.0
> bower material-icons#^0.1.0     cached https://github.com/materialicons/material-icons.git#0.1.0
> bower material-icons#^0.1.0   validate 0.1.0 against https://github.com/materialicons/material-icons.git#^0.1.0
> bower angular#1.4.8             cached https://github.com/angular/bower-angular.git#1.4.8
> bower angular#1.4.8           validate 1.4.8 against https://github.com/angular/bower-angular.git#1.4.8
> bower angular#1.5.3             cached https://github.com/angular/bower-angular.git#1.5.3
> bower angular#1.5.3           validate 1.5.3 against https://github.com/angular/bower-angular.git#1.5.3
> bower angular#^1.4.8            cached https://github.com/angular/bower-angular.git#1.5.5
> bower angular#^1.4.8          validate 1.5.5 against https://github.com/angular/bower-angular.git#^1.4.8
> bower angular#*                 cached https://github.com/angular/bower-angular.git#1.5.5
> bower angular#*               validate 1.5.5 against https://github.com/angular/bower-angular.git#*
> bower angular#^1.0.8            cached https://github.com/angular/bower-angular.git#1.5.5
> bower angular#^1.0.8          validate 1.5.5 against https://github.com/angular/bower-angular.git#^1.0.8
> bower angular-animate#^1.4.8       not-cached https://github.com/angular/bower-angular-animate.git#^1.4.8
> bower angular-animate#^1.4.8          resolve https://github.com/angular/bower-angular-animate.git#^1.4.8
> bower angular-route#1.4.8          not-cached https://github.com/angular/bower-angular-route.git#1.4.8
> bower angular-route#1.4.8             resolve https://github.com/angular/bower-angular-route.git#1.4.8
> bower angular-touch#1.4.8          not-cached https://github.com/angular/bower-angular-touch.git#1.4.8
> bower angular-touch#1.4.8             resolve https://github.com/angular/bower-angular-touch.git#1.4.8
> bower angular-message-format#1.4.8 not-cached https://github.com/angular/bower-angular-message-format.git#1.4.8
> bower angular-message-format#1.4.8    resolve https://github.com/angular/bower-angular-message-format.git#1.4.8
> bower angular-animate#1.4.8        not-cached https://github.com/angular/bower-angular-animate.git#1.4.8
> bower angular-animate#1.4.8           resolve https://github.com/angular/bower-angular-animate.git#1.4.8
> bower angular-resource#1.4.8       not-cached https://github.com/angular/bower-angular-resource.git#1.4.8
> bower angular-resource#1.4.8          resolve https://github.com/angular/bower-angular-resource.git#1.4.8
> bower angular-messages#^1.4.8      not-cached https://github.com/angular/bower-angular-messages.git#^1.4.8
> bower angular-messages#^1.4.8         resolve https://github.com/angular/bower-angular-messages.git#^1.4.8
> bower angular-sanitize#1.4.8       not-cached https://github.com/angular/bower-angular-sanitize.git#1.4.8
> bower angular-sanitize#1.4.8          resolve https://github.com/angular/bower-angular-sanitize.git#1.4.8
> bower angular-aria#^1.4.8          not-cached https://github.com/angular/bower-angular-aria.git#^1.4.8
> bower angular-aria#^1.4.8             resolve https://github.com/angular/bower-angular-aria.git#^1.4.8
> bower angular-messages#1.4.8       not-cached https://github.com/angular/bower-angular-messages.git#1.4.8
> bower angular-messages#1.4.8          resolve https://github.com/angular/bower-angular-messages.git#1.4.8
> bower angular-cookies#1.4.8        not-cached https://github.com/angular/bower-angular-cookies.git#1.4.8
> bower angular-cookies#1.4.8           resolve https://github.com/angular/bower-angular-cookies.git#1.4.8
> bower angular-aria#1.4.8           not-cached https://github.com/angular/bower-angular-aria.git#1.4.8
> bower angular-aria#1.4.8              resolve https://github.com/angular/bower-angular-aria.git#1.4.8
> bower angular-mocks#1.4.8            checkout v1.4.8
> bower angular-animate#^1.4.8         checkout v1.5.5
> bower angular-animate#1.4.8          checkout v1.4.8
> bower angular-route#1.4.8            checkout v1.4.8
> bower angular-message-format#1.4.8   checkout v1.4.8
> bower angular-touch#1.4.8            checkout v1.4.8
> bower angular-sanitize#1.4.8         checkout v1.4.8
> bower angular-resource#1.4.8         checkout v1.4.8
> bower angular-messages#^1.4.8        checkout v1.5.5
> bower angular-messages#1.4.8         checkout v1.4.8
> bower angular-aria#^1.4.8            checkout v1.5.5
> bower angular-aria#1.4.8             checkout v1.4.8
> bower angular-mocks#1.4.8            progress remote: Compressing objects:  11% (1/9)   [K
> bower angular-mocks#1.4.8            progress remote: Compressing objects:  22% (2/9)   [K
> bower angular-mocks#1.4.8            progress remote: Compressing objects:  33% (3/9)   [K
> bower angular-mocks#1.4.8            progress remote: Compressing objects:  44% (4/9)   [K
> bower angular-mocks#1.4.8            progress remote: Compressing objects:  55% (5/9)   [K
> bower angular-mocks#1.4.8            progress remote: Compressing objects:  66% (6/9)   [K
> bower angular-mocks#1.4.8            progress remote: Compressing objects:  77% (7/9)   [K
> bower angular-mocks#1.4.8            progress remote: Compressing objects:  88% (8/9)   [K
> bower angular-mocks#1.4.8            progress remote: Compressing objects: 100% (9/9)   [K
> bower angular-mocks#1.4.8            progress remote: Compressing objects: 100% (9/9), done.[K
> bower angular-animate#^1.4.8         progress remote: Compressing objects:  11% (1/9)   [K
> bower angular-animate#^1.4.8         progress remote: Compressing objects:  22% (2/9)   [K
> bower angular-animate#^1.4.8         progress remote: Compressing objects:  33% (3/9)   [K
> bower angular-animate#^1.4.8         progress remote: Compressing objects:  44% (4/9)   [K
> bower angular-animate#^1.4.8         progress remote: Compressing objects:  55% (5/9)   [K
> bower angular-animate#^1.4.8         progress remote: Compressing objects:  66% (6/9)   [K
> bower angular-animate#^1.4.8         progress remote: Compressing objects:  77% (7/9)   [K
> bower angular-animate#^1.4.8         progress remote: Compressing objects:  88% (8/9)   [K
> bower angular-animate#^1.4.8         progress remote: Compressing objects: 100% (9/9)   [K
> bower angular-animate#^1.4.8         progress remote: Compressing objects: 100% (9/9), done.[K
> bower angular-cookies#1.4.8          checkout v1.4.8
> bower angular-animate#1.4.8          progress remote: Compressing objects:  11% (1/9)   [K
> bower angular-animate#1.4.8          progress remote: Compressing objects:  22% (2/9)   [K
> bower angular-animate#1.4.8          progress remote: Compressing objects:  33% (3/9)   [K
> bower angular-animate#1.4.8          progress remote: Compressing objects:  44% (4/9)   [K
> bower angular-animate#1.4.8          progress remote: Compressing objects:  55% (5/9)   [K
> bower angular-animate#1.4.8          progress remote: Compressing objects:  66% (6/9)   [K
> bower angular-animate#1.4.8          progress remote: Compressing objects:  77% (7/9)   [K
> bower angular-animate#1.4.8          progress remote: Compressing objects:  88% (8/9)   [K
> bower angular-animate#1.4.8          progress remote: Compressing objects: 100% (9/9)   [K
> bower angular-animate#1.4.8          progress remote: Compressing objects: 100% (9/9), done.[K
> bower angular-route#1.4.8            progress remote: Compressing objects:  11% (1/9)   [K
> bower angular-route#1.4.8            progress remote: Compressing objects:  22% (2/9)   [K
> bower angular-route#1.4.8            progress remote: Compressing objects:  33% (3/9)   [K
> bower angular-route#1.4.8            progress remote: Compressing objects:  44% (4/9)   [K
> bower angular-route#1.4.8            progress remote: Compressing objects:  55% (5/9)   [K
> bower angular-route#1.4.8            progress remote: Compressing objects:  66% (6/9)   [K
> bower angular-route#1.4.8            progress remote: Compressing objects:  77% (7/9)   [K
> bower angular-route#1.4.8            progress remote: Compressing objects:  88% (8/9)   [K
> bower angular-route#1.4.8            progress remote: Compressing objects: 100% (9/9)   [K
> bower angular-route#1.4.8            progress remote: Compressing objects: 100% (9/9), done.[K
> bower angular-mocks#1.4.8            resolved https://github.com/angular/bower-angular-mocks.git#1.4.8
> bower angular-animate#^1.4.8         resolved https://github.com/angular/bower-angular-animate.git#1.5.5
> bower angular-message-format#1.4.8   progress remote: Compressing objects:  11% (1/9)   [K
> bower angular-message-format#1.4.8   progress remote: Compressing objects:  22% (2/9)   [K
> bower angular-message-format#1.4.8   progress remote: Compressing objects:  33% (3/9)   [K
> bower angular-message-format#1.4.8   progress remote: Compressing objects:  44% (4/9)   [K
> bower angular-message-format#1.4.8   progress remote: Compressing objects:  55% (5/9)   [K
> bower angular-message-format#1.4.8   progress remote: Compressing objects:  66% (6/9)   [K
> bower angular-message-format#1.4.8   progress remote: Compressing objects:  77% (7/9)   [K
> bower angular-message-format#1.4.8   progress remote: Compressing objects:  88% (8/9)   [K
> bower angular-message-format#1.4.8   progress remote: Compressing objects: 100% (9/9)   [K
> bower angular-message-format#1.4.8   progress remote: Compressing objects: 100% (9/9), done.[K
> bower angular-animate#1.4.8          resolved https://github.com/angular/bower-angular-animate.git#1.4.8
> bower angular-message-format#1.4.8   resolved https://github.com/angular/bower-angular-message-format.git#1.4.8
> bower angular-route#1.4.8            resolved https://github.com/angular/bower-angular-route.git#1.4.8
> bower angular-touch#1.4.8            progress remote: Compressing objects:  11% (1/9)   [K
> bower angular-touch#1.4.8            progress remote: Compressing objects:  22% (2/9)   [K
> bower angular-touch#1.4.8            progress remote: Compressing objects:  33% (3/9)   [K
> bower angular-touch#1.4.8            progress remote: Compressing objects:  44% (4/9)   [K
> bower angular-touch#1.4.8            progress remote: Compressing objects:  55% (5/9)   [K
> bower angular-touch#1.4.8            progress remote: Compressing objects:  66% (6/9)   [K
> bower angular-touch#1.4.8            progress remote: Compressing objects:  77% (7/9)   [K
> bower angular-touch#1.4.8            progress remote: Compressing objects:  88% (8/9)   [K
> bower angular-touch#1.4.8            progress remote: Compressing objects: 100% (9/9)   [K
> bower angular-touch#1.4.8            progress remote: Compressing objects: 100% (9/9), done.[K
> bower angular-sanitize#1.4.8         progress remote: Compressing objects:  11% (1/9)   [K
> bower angular-sanitize#1.4.8         progress remote: Compressing objects:  22% (2/9)   [K
> bower angular-sanitize#1.4.8         progress remote: Compressing objects:  33% (3/9)   [K
> bower angular-sanitize#1.4.8         progress remote: Compressing objects:  44% (4/9)   [K
> bower angular-sanitize#1.4.8         progress remote: Compressing objects:  55% (5/9)   [K
> bower angular-sanitize#1.4.8         progress remote: Compressing objects:  66% (6/9)   [K
> bower angular-sanitize#1.4.8         progress remote: Compressing objects:  77% (7/9)   [K
> bower angular-sanitize#1.4.8         progress remote: Compressing objects:  88% (8/9)   [K
> bower angular-sanitize#1.4.8         progress remote: Compressing objects: 100% (9/9)   [K
> bower angular-sanitize#1.4.8         progress remote: Compressing objects: 100% (9/9), done.[K
> bower angular-resource#1.4.8         progress remote: Compressing objects:  11% (1/9)   [K
> bower angular-resource#1.4.8         progress remote: Compressing objects:  22% (2/9)   [K
> bower angular-resource#1.4.8         progress remote: Compressing objects:  33% (3/9)   [K
> bower angular-resource#1.4.8         progress remote: Compressing objects:  44% (4/9)   [K
> bower angular-resource#1.4.8         progress remote: Compressing objects:  55% (5/9)   [K
> bower angular-resource#1.4.8         progress remote: Compressing objects:  66% (6/9)   [K
> bower angular-resource#1.4.8         progress remote: Compressing objects:  77% (7/9)   [K
> bower angular-resource#1.4.8         progress remote: Compressing objects:  88% (8/9)   [K
> bower angular-resource#1.4.8         progress remote: Compressing objects: 100% (9/9)   [K
> bower angular-resource#1.4.8         progress remote: Compressing objects: 100% (9/9), done.[K
> bower angular-sanitize#1.4.8         resolved https://github.com/angular/bower-angular-sanitize.git#1.4.8
> bower angular-touch#1.4.8            resolved https://github.com/angular/bower-angular-touch.git#1.4.8
> bower angular-messages#1.4.8         progress remote: Compressing objects:  11% (1/9)   [K
> bower angular-messages#1.4.8         progress remote: Compressing objects:  22% (2/9)   [K
> bower angular-messages#1.4.8         progress remote: Compressing objects:  33% (3/9)   [K
> bower angular-messages#1.4.8         progress remote: Compressing objects:  44% (4/9)   [K
> bower angular-messages#1.4.8         progress remote: Compressing objects:  55% (5/9)   [K
> bower angular-messages#1.4.8         progress remote: Compressing objects:  66% (6/9)   [K
> bower angular-messages#1.4.8         progress remote: Compressing objects:  77% (7/9)   [K
> bower angular-messages#1.4.8         progress remote: Compressing objects:  88% (8/9)   [K
> bower angular-messages#1.4.8         progress remote: Compressing objects: 100% (9/9)   [K
> bower angular-messages#1.4.8         progress remote: Compressing objects: 100% (9/9), done.[K
> bower angular-messages#^1.4.8        progress remote: Compressing objects:  11% (1/9)   [K
> bower angular-messages#^1.4.8        progress remote: Compressing objects:  22% (2/9)   [K
> bower angular-messages#^1.4.8        progress remote: Compressing objects:  33% (3/9)   [K
> bower angular-messages#^1.4.8        progress remote: Compressing objects:  44% (4/9)   [K
> bower angular-messages#^1.4.8        progress remote: Compressing objects:  55% (5/9)   [K
> bower angular-messages#^1.4.8        progress remote: Compressing objects:  66% (6/9)   [K
> bower angular-messages#^1.4.8        progress remote: Compressing objects:  77% (7/9)   [K
> bower angular-messages#^1.4.8        progress remote: Compressing objects:  88% (8/9)   [K
> bower angular-messages#^1.4.8        progress remote: Compressing objects: 100% (9/9)   [K
> bower angular-messages#^1.4.8        progress remote: Compressing objects: 100% (9/9), done.[K
> bower angular-resource#1.4.8         resolved https://github.com/angular/bower-angular-resource.git#1.4.8
> bower angular-aria#^1.4.8            progress remote: Compressing objects:  11% (1/9)   [K
> bower angular-aria#^1.4.8            progress remote: Compressing objects:  22% (2/9)   [K
> bower angular-aria#^1.4.8            progress remote: Compressing objects:  33% (3/9)   [K
> bower angular-aria#^1.4.8            progress remote: Compressing objects:  44% (4/9)   [K
> bower angular-aria#^1.4.8            progress remote: Compressing objects:  55% (5/9)   [K
> bower angular-aria#^1.4.8            progress remote: Compressing objects:  66% (6/9)   [K
> bower angular-aria#^1.4.8            progress remote: Compressing objects:  77% (7/9)   [K
> bower angular-aria#^1.4.8            progress remote: Compressing objects:  88% (8/9)   [K
> bower angular-aria#^1.4.8            progress remote: Compressing objects: 100% (9/9)   [K
> bower angular-aria#^1.4.8            progress remote: Compressing objects: 100% (9/9), done.[K
> bower angular-messages#^1.4.8        resolved https://github.com/angular/bower-angular-messages.git#1.5.5
> bower angular-messages#1.4.8         resolved https://github.com/angular/bower-angular-messages.git#1.4.8
> bower angular-aria#1.4.8             progress remote: Compressing objects:  11% (1/9)   [K
> bower angular-aria#1.4.8             progress remote: Compressing objects:  22% (2/9)   [K
> bower angular-aria#1.4.8             progress remote: Compressing objects:  33% (3/9)   [K
> bower angular-aria#1.4.8             progress remote: Compressing objects:  44% (4/9)   [K
> bower angular-aria#1.4.8             progress remote: Compressing objects:  55% (5/9)   [K
> bower angular-aria#1.4.8             progress remote: Compressing objects:  66% (6/9)   [K
> bower angular-aria#1.4.8             progress remote: Compressing objects:  77% (7/9)   [K
> bower angular-aria#1.4.8             progress remote: Compressing objects:  88% (8/9)   [K
> bower angular-aria#1.4.8             progress remote: Compressing objects: 100% (9/9)   [K
> bower angular-aria#1.4.8             progress remote: Compressing objects: 100% (9/9), done.[K
> bower angular-aria#^1.4.8            resolved https://github.com/angular/bower-angular-aria.git#1.5.5
> bower angular-aria#1.4.8             resolved https://github.com/angular/bower-angular-aria.git#1.4.8
> 
> D:\home\site\repository\CoachingWebApp>bower angular-cookies#1.4.8           ECMDERR Failed to execute "git clone https://github.com/angular/bower-angular-cookies.git -b v1.4.8 --progress . --depth 1", exit code of #128
> 
> Additional error details:
> fatal: unable to access 'https://github.com/angular/bower-angular-cookies.git/': Could not resolve host: github.com

**Comment by jrmaingo** [comment]
Issue appears to be resolved now, must have been something on azure's end
