### ISSUE TITLE
Bower started to throw ECMDERR error in Visual Studio.

### ISSUE THREAD

**Issue by ziombo** [bower/bower#2250]
I'm using bower in visual studio 2015 in my mvc 6 project, by having bower.json file and each time i want to download new package I used to add a new line to the dependencies and write down which package I want and got suggested the newest version by intellisense. After downloading some of the packages with no problem, recently I got an ECMDERR error whenever I try to download any package. It first started when I wanted to download "angular-routing", I managed to work around it by inputting the git:// address of the package instead of version I want to download, but it doesn't always work with other packages. The error I get is 
`ECMDERR Failed to execute "git clone https://github.com/angular/bower-angular.git -b v1.5.3 --progress . --depth 1", exit code of #-532462766`

What I realised so far is that by running this command in git bash, the `.` between --progress and --depth 1 causes some sort of error (but I don't think it's the reason my intellisense stopped working when choosing packages latest version).

**Comment by bhanodai** [comment]
+1

**Comment by mrcha0s** [comment]
+1

**Comment by jonniv6** [comment]
+1

**Comment by hhtopcu** [comment]
Any solution for that?

**Comment by mrcha0s** [comment]
there is a work around in Turkish http://www.sayfalar.com/View/Article/5

**Comment by sheerun** [comment]
Maybe someone wants to clone bower and fix it?
