### ISSUE TITLE
Separate bower.json files for different environments under Git version control

### ISSUE THREAD

**Issue by robbymarston** [bower/bower#2253]
I have a multi-environment setup, for this example let's say it's just Dev and Prod (both hosted on remote servers, accessible by all developers). All of the files, including bower.json, are under version control so front-end developers can update dependencies at will and those updates will be shared amongst all developers. That said, we need the ability to test unstable versions of a specific package in Dev (using #<branch>) while Prod continues using the latest stable version. Currently our Jenkins build job for both environments runs the 'bower update' command so that any new changes are taken into account and the bower_components files are adjusted accordingly ... therein lies the problem. Any of the following solutions (or others I haven't thought of) may mitigate the issue allowing for a setup that fulfills my requirements:

1) Adding the -d/--development flag to ONLY install devDependencies
2) Allowing the user to specify the name of the bower.json file that's used in .bowerrc so that ${ENV} may be used, e.g. {json:'bower-${ENV}.json'}

**Comment by BenMann** [comment]
That's a pretty special scenario to be honest.
Just from a workflow perspective I'd say test the unstable versions locally. You probably don't want to deploy them to production anyway, but that's not always true I guess.

One quick solution might be to add `ignoredDependencies` to your `.bowerrc` and ignore everything but your `devDependencies` as you described in 1). Alternatively you might be able to utilize [Hooks](http://bower.io/docs/config/#hooks) to build your own workflow. There is also an override plugin for Gulp [here](https://www.npmjs.com/package/gulp-bower-overrides) if that's an option for you.

I personally think 2) might be a cool enhancement that you can set if needed (disabled by default).

**Comment by sheerun** [comment]
Bower is deprecated and we won't implement new features like this one. We recommend switching to yarn and migrating projects to it with https://github.com/sheerun/bower-away
