### ISSUE TITLE
packages are installed at computer root instead of project subdirectory 

### ISSUE THREAD

**Issue by tdmoneybanks** [bower/bower#2254]
I have a project that is using bower to manage some dependencies. The bower.json file and .bowerrc file live at a path like ../../v2. I have been going to the v2 directory and running bower update or bower install (with sudo and --allow-root) and getting some weird behavior. The packages are installed at root level of the computer (on osx where the applications and Users folders are). for reference my .bowerrc has a directory path of "/". I am not sure how to fix this has this issue been seen before?

**Comment by dprice809** [comment]
I believe this is similar to #2194

**Comment by tdmoneybanks** [comment]
hi just read this. It does seem to be a similar issue. But the only fix he found was to change the .bowerrc? Other devs on my team use the same .bowerrc and it works fine with their directory path set to "/". Is there any other alternative? I have tried to uninstall and reinstall bower a couple times with no change. I also dont have cwd defined in any bowerrc

**Comment by dprice809** [comment]
There is a chain of .bowerrc files. These files can be found in multiple locations, outlined [here](http://bower.io/docs/config/#placement--order) . But it looks like the one in the working directory has the most influence. 

It is interesting that this continues to happen across multiple machines. May I ask, what OS are you running? It sounds like there may be some kind of conflict with the way Bower accesses the file system.

**Comment by tdmoneybanks** [comment]
I am running OSX yosemite 10.10.4. Yea I am not sure why it would be trying to install in the root.

**Comment by tdmoneybanks** [comment]
I figured out the problem btw and it was a strange one. It seems like for some people "/" is configured as a relative path according to bower. However, for my comp and a couple others on my team, it was read as a absolute path. The fix was to make sure its relative with "./"

**Comment by sheerun** [comment]
It's because newer bower accepts absolute paths as well and older don't
