### ISSUE TITLE
Update only compatible dependencies

### ISSUE THREAD

**Issue by karmeli87** [bower/bower#2255]
For ex. i have the following bower.json:
```json
"dependencies": {
    "angular": "1.4.10",
    "angular-bootstrap": "1.x",
    "angular-resource": "1.x",
    "angular-cookies": "1.x",
    "angular-sanitize": "1.x",
    "angular-route": "1.x",
    "angular-animate": "1.x",
    ...
}
```
As far as I understood bower resolves every dependency to it latest regardless of the angular compatibility. 
I would like that bower resolves the latest compatible versions of angular modules with angular. 
So in this example I would like that the angular-bootstrap,angular-resource, .... will resolve to their 1.4.10 version or any other compatible version (if available).

**Comment by BenMann** [comment]
Generally if you have multiple packages depending on different versions of angular, you can run into version conflicts, which Bower will warn you about (interactive mode). In some cases you might even have to solve them manually by deciding on a suitable version. The best way to prevent this (and solve your problem) would be to specify a resolution manually:
```
 "resolutions": {
    "angular": "~1.11.3"
  }
```
In interactive mode you can also persist your choice during install, by prefixing your choice with `!`.
[This](http://stackoverflow.com/questions/16991128/how-to-resolve-bower-dependency-version-conflicts) might also be helpful.
