### ISSUE TITLE
Register a private library from a private Subversion endpoint

### ISSUE THREAD

**Issue by nicolasrosado** [bower/bower#2256]
Hi,

I try to register a private library from a private Subversion endpoint.

I already saw this two documentations about register options :
http://bower.io/docs/api/#install
http://bower.io/docs/creating-packages/#register

I saw that we can use Subversion endpoint like this :
Private Subversion endpoint svn+ssh://package.googlecode.com/svn/

But when I did the command line, I met this error : 

nrosado@pc-dev-10:~$ **bower register amcharts svn+ssh://my_host/librairies-javascript-privees/amcharts#3.18.5**
bower amcharts#\*               resolve svn+ssh://my_host/librairies-javascript-privees/amcharts#3.18.5#*
nrosado@my_host's password: 
bower amcharts#\*               ECMDERR Failed to execute "svn list svn+ssh://my_host/librairies-javascript-privees/amcharts#3.18.5/tags --verbose --non-interactive", exit code of #1 svn: E210005: Unable to connect to a repository at URL 'svn+ssh://my_host/librairies-javascript-privees/amcharts%233.18.5/tags' svn: E210005: No repository found in 'svn+ssh://my_host/librairies-javascript-privees/amcharts%233.18.5/tags'

Additional error details:
svn: E210005: Unable to connect to a repository at URL 'svn+ssh://my_host/librairies-javascript-privees/amcharts%233.18.5/tags'
svn: E210005: No repository found in 'svn+ssh://my_host/librairies-javascript-privees/amcharts%233.18.5/tags'

I don't understand why the command line try to find this url :
svn+ssh:/my_host/librairies-javascript-privees/amcharts/**%233.18.5/**tags 

For me the correct url should be : 
svn+ssh://my_host/librairies-javascript-privees/amcharts/tags/3.18.5

Morever, It seems to be not consider the version of the library when It did the resolve : 
bower **amcharts#**\*               resolve svn+ssh://my_host/librairies-javascript-privees/amcharts#3.18.5#*

See below my svn structure : 
root
|--- librairies-javascript-privees
|----------- branches
|----------- tags
|--------------------- 3.18.5
|---------------------------- amcharts.js
|---------------------------- bower.json
|---------------------------- others folders and js files ...
|----------- trunk
|--------------------- amcharts.js
|--------------------- bower.json
|--------------------- others folders and js files ...

In addition see below the error when I don't specify the version of the library : 

nrosado@pc-dev-10:~$ **bower register amcharts svn+ssh://my_host/librairies-javascript-privees/amcharts**
bower amcharts#\*               resolve svn+ssh://my_host/librairies-javascript-privees/amcharts#*
nrosado@my_hosts password: 
bower amcharts#\*               ECMDERR Failed to execute "svn list svn+ssh://my_host/librairies-javascript-privees/amcharts/tags --verbose --non-interactive", exit code of #1 svn: E210005: Unable to connect to a repository at URL 'svn+ssh://my_host/librairies-javascript-privees/amcharts/tags' svn: E210005: No repository found in 'svn+ssh://my_host/librairies-javascript-privees/amcharts/tags'

Additional error details:
svn: E210005: Unable to connect to a repository at URL 'svn+ssh://my_host/librairies-javascript-privees/amcharts/tags'
svn: E210005: No repository found in 'svn+ssh://my_host/librairies-javascript-privees/amcharts/tags'

If you see the url, the command line try to find the tags folder : 
 'svn+ssh://my_host/librairies-javascript-privees/amcharts/tags'

On top of that, when I try to execute the svn list command used by bower this failed : 
nrosado@pc-dev-10:~$ svn list svn+ssh://my_host/librairies-javascript-privees/amcharts/tags
nrosado@my_host's password: 
svn: E210005: Unable to connect to a repository at URL 'svn+ssh://my_host/librairies-javascript-privees/amcharts/tags'
svn: E210005: No repository found in 'svn+ssh://my_host/librairies-javascript-privees/amcharts/tags'

But the command below works : 
nrosado@pc-dev-10:~$ svn list svn://my_host/librairies-javascript-privees/amcharts/tags
3.18.5/

Could you tell me the correct way to register my library from my private subversion endpoint ? 
May be I forgot something.

Thanks in advance for your time and your response

**Comment by nicolasrosado** [comment]
May be my bug already exist see below :
https://github.com/bower/bower/issues/1313
https://github.com/bower/bower/pull/1602

and 
https://github.com/bower/bower/issues?utf8=%E2%9C%93&q=ECMDERR+svn

**Comment by sheerun** [comment]
Bower is not deprecated, if someone still has issues with this and would like this fixed, please open another issue

**Comment by sheerun** [comment]
not -> now
