### ISSUE TITLE
bower install on CI server with a private package hangs forever with no error.

### ISSUE THREAD

**Issue by Mattykins** [bower/bower#2257]
I am currently trying to stitch together a CI workflow using TeamCity, and a private bower registry for our website projects. The registry we are using is https://www.npmjs.com/package/private-bower

We are using bitbucket for our git provider.

I've registered one package with the private registry, who's `bower.json` file looks like this:

```
{
  "private": true,
  "name": "myPrivatePackage",
  "main": [
    "dist/scripts/app.js",
    "dist/styles/app.css"
  ],
  "dependencies": {
    "angular-ui-router": "~0.2.15",
    "angular-bootstrap": "~0.13.0",
    "angular": "~1.4.0",
    "bootstrap-sass": "bootstrap-sass-official#~3.3.6",
    "lodash": "~4.8.2"
  },
  "resolutions": {
    "jquery": "~2.1.4",
    "angular": "~1.4.0"
  }
}
```

I have a separate project trying to consume this bower package. It's bower.json and .bowerrc look like this:

bower.json

```
{
  "name": "myApp",
  "version": "0.0.0",
  "dependencies": {
    "angular-animate": "~1.4.0",
    "angular-cookies": "~1.4.0",
    "angular-ladda": "~0.2.2",
    "angular-local-storage": "~0.1.5",
    "angular-touch": "~1.4.0",
    "angular-sanitize": "~1.4.0",
    "jquery": "~2.1.4",
    "angular-ui-router": "~0.2.15",
    "bootstrap-sass-official": "~3.3.4",
    "angular-bootstrap": "~0.13.0",
    "animate.css": "~3.3.0",
    "angular": "~1.4.0",
    "myPrivatePackage": "myPrivatePackage#~0.0.1"
  },
  "devDependencies": {
    "angular-mocks": "~1.4.0"
  },
  "resolutions": {
    "jquery": "~2.1.4",
    "angular": "~1.4.0"
  }
}
```

.bowerrc

```
{
  "directory": "bower_components",
  "registry": "http://bower.mycompany.com"
}
```

Locally, all of this stuff works fine. I can run `bower install` no problem, it installs my private package and everything is good. However, in TeamCity during CI it hangs silently at this point:

`bower spin.js#~2.0.2                       resolved https://github.com/fgnass/spin.js.git#2.0.2`

The actual package it hangs on varies. I've seen it hang at `angular-animate` and `jquery` as well. So it's really weird that it hangs on these packages and _not_ my custom private package. If anything, I would think that it would hang on that package.

Now, if I remove my private package as a dependency, the build runs fine. 

I've put a couple of things in place to make the CI build even possible. I have a global `git config.url ssh://.insteadOf "https://"` so that my CI server can communicate with my private git repository over ssh and it doesn't get prompted for credentials.

The actual bower install command I'm using is as follows: `bower install --config.interactive=false --verbose --force`

I had read someone's similar problem who blamed node and bower versioning so I've tried a multitude of different bower/npm/node versions. My current versions are:

node: `v0.10.44`
npm: `3.8.7`
bower `1.7.2`

(I can easily change versions if this seems to be the root of the issue, but like I said I've tried a bunch)

Sorry about the wall of text, just trying to provide as much info as possible.

Thanks!

EDIT: I Should also mention that my CI server is running Windows Server 2012 R2

**Comment by sheerun** [comment]
what is git version on ci?

**Comment by sheerun** [comment]
what is the git version?

**Comment by dlo83** [comment]
FWIW, I'm experiencing the same thing.  My Ember app install hangs after this last message: ```bower FakeXMLHttpRequest#~1.2.1           resolved https://github.com/trek/FakeXMLHttpRequest.git#1.2.1```

node: v0.12.14
npm: 2.15.1
bower: 1.7.9
git: 2.7.4
