### ISSUE TITLE
bower-github.json

### ISSUE THREAD

**Issue by mojisilver** [bower/bower#2260]
Hey guys,
I was trying to install a package trough bower, this is my first time that I use bower.
after trying bower install command I received this weird message.please let me know if you know how can I handle it. the message was this:
Error: EACCES: permission denied, open '/Users/mySystem/.config/configstore/bower-github.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.create.all.get (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:35:26)
    at Object.Configstore (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:28:44)
    at readCachedConfig (/usr/local/lib/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/usr/local/lib/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/lib/index.js:16:32)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by prappo** [comment]
Did you try with sudo ?
`sudo bower install --allow-root
sudo bower install <package>`

**Comment by mojisilver** [comment]
Thanks for your help. Actually I tried all kind of command and finally just below command worked for me:

sudo bower update -a

Thanks again


Best regards,

Mojtaba ahmadi,






On Tue, Apr 19, 2016 at 12:57 PM -0700, "Prappo Prince" <notifications@github.com> wrote:





Did you try with sudo ?
`sudo bower install --allow-root
sudo bower install <package>`




---

**Comment by modymok** [comment]
Hi @prappo 
I have the same problem, and i tried the "`sudo bower install --allow-root`" . it gave me and error " `bower ENOENT        No bower.json present`" 
it's not my first time to install packages with bower !! 

Thanks

**Comment by prappo** [comment]
Try 
`bower init`
if it dose not work then try this 
`sudo chown -R <user>:<user> /home/<user>/.config/configstore`
example => `sudo chown -R prappo:prappo /home/prappo/.config/configstore`
then , 
`bower init`
`bower install <package>`
hopefully it would work

**Comment by sgaurav19928** [comment]
@prappo  :After 
`sudo chown -R <user>:<user> /home/<user>/.config/configstore`
`bower init`
...
there are multiple questions out there such as:

name 
description
...
? set currently installed components as dependencies? 
? add commonly ignored files to ignore list? 
? would you like to mark this package as private which prevents it from being accidentally published to the registry? 
...

how to work out with this questions.

**Comment by prakashkhadka** [comment]
sudo bower init --allow-root
That worked for me

**Comment by gareththomasnz** [comment]
It works for me using sudo bower install --allow-root  but its not using the bowerrc directory

**Comment by kelvin4incubit** [comment]
i keep having this error and i don't know why, is there a way i could solve this
There is an error in your gulpfile: Error: EACCES: permission denied, open '/Users/.config/configstore/bower-github.json'

**Comment by kelvin4incubit** [comment]
i have solved it by changing the permission to my root home so i dont have to use sudo anymore

**Comment by janaka120** [comment]
this work for me. 
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config
sudo chown -R $USER:$GROUP ~/.cache

**Comment by zulrich91** [comment]
I changed the ownership of the file from root to a normal user and It worked for me

**Comment by Hbharti** [comment]
Try this
sudo chown -R <user> *

**Comment by venkateshkarni** [comment]
This has sloved this issue for me. MacBook Air
sudo bower update -a
