### ISSUE TITLE
EACCES: permission denied .config/configstore/bower-github.json

### ISSUE THREAD

**Issue by alexlaw17** [bower/bower#2262]
I keep running into this problem. I uninstalled and reinstalled bower. Nothing is working. 

`alexlaw$ bower
/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:54
				throw err;
				^

Error: EACCES: permission denied, open '/Users/alexlaw/.config/configstore/bower-github.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.create.all.get (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:35:26)
    at Object.Configstore (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:28:44)
    at readCachedConfig (/usr/local/lib/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/usr/local/lib/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/lib/index.js:16:32)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)`

**Comment by BenMann** [comment]
Did you see this issue: https://github.com/bower/bower/issues/2260
Does it work for you too?

**Comment by alexlaw17** [comment]
I'm still getting the same error, even after
`sudo bower install --allow-root`
`sudo bower install <package>`

**Comment by alexlaw17** [comment]
fixed it with 
`sudo chown -R $USER:$GROUP ~/.npm`
`sudo chown -R $USER:$GROUP ~/.config`

**Comment by BenMann** [comment]
Strange but still a problem with permissions (as also indicated by the error).
Closing for now.

**Comment by steveandrewwong** [comment]
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

works for me

**Comment by jcanales** [comment]
Worked for me as well 

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by beormalte** [comment]
Worked for me :)

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by dpanfili** [comment]
This helped me - thanks!

**Comment by Samuel7l** [comment]
Worked for me :)

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by jkoksharova** [comment]
Worked for me too.

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by rswetabh** [comment]
Worked for me too.

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by AsherPeruscini** [comment]
and me

`sudo chown -R $USER:$GROUP ~/.npm`
`sudo chown -R $USER:$GROUP ~/.config`

**Comment by Shakogun** [comment]
Same goes for me

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by Pravin-Parkhi** [comment]
Worked for me as well

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by pankajdaffodil** [comment]
Thanks to all
worked for me .

**Comment by revanthreddya** [comment]
Perfect .. thanks @alexlaw17
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by BlackRussian** [comment]
Thanks to all
worked for me .

**Comment by emotilla** [comment]
### in Ubuntu 14 LTS / DigitalOcean:

sudo chown -R $USER:$GROUP /usr/share/nginx/html/

checkout a good tutorial: 
https://www.digitalocean.com/community/tutorials/how-to-manage-front-end-javascript-and-css-dependencies-with-bower-on-ubuntu-14-04

**Comment by sashacarvajal94** [comment]
Great!!! Been with this issue for days! Worked for me too!

**Comment by ragalindoh** [comment]
Worked for me, thank you @alexlaw17 

```
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config
```

**Comment by dannymac7** [comment]
Worked for me, thanks!!!

**Comment by jorgeants** [comment]
Worked for me too. Thanks @alexlaw17. :)

**Comment by ils-anshub** [comment]
Worked for me as well...Thanks @alexlaw17

**Comment by appssunset** [comment]
Worked for me as well

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

But I needed to execute the follow too:
sudo chown -R $USER:$GROUP ~/.cache

**Comment by cliftonc0613** [comment]
Worked for me as well

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by NikolaVujanic** [comment]
Worked for me :)

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by alansutherland** [comment]
Thanks @alexlaw17

**Comment by richardj** [comment]
worked for me as well! :) 

> 
> 
> fixed it with 
> ```
> sudo chown -R $USER:$GROUP ~/.npm
> sudo chown -R $USER:$GROUP ~/.config
> ```

**Comment by crrollyson** [comment]
Same here, thanks!

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by avastamin** [comment]
Worked! thanks

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by anngelfra** [comment]
Thank you, thank you. I had gone crazy trying to restart and uninstall and then I found these commands and IT WORKS <3

**Comment by ayibfanani** [comment]
`sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config`

work like charm, thanks

**Comment by AnnaUmi** [comment]
thanks you! It works
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by itumoraes** [comment]
Finally! It works! Thanks!

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by monis01** [comment]
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

worked for me too, Thanks!

**Comment by jimbojw** [comment]
The root cause of this issue (and many like it) is https://github.com/npm/write-file-atomic/issues/11.

There is an outstanding patch which will fix this for everyone. We're all waiting for someone from npm to accept it: https://github.com/npm/write-file-atomic/pull/13

**Comment by akohli96** [comment]
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

Worked for me too!

**Comment by eduard-ungureanu** [comment]
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

Worked for me too, on OSX EL Capitan

Thank you so much!

**Comment by Paras-avantsoft** [comment]
thanks.. Its working.. on OSX EL Capitan

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by w9ahmed** [comment]
Worked for me! 

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by Andraw-lin** [comment]
Works for me too !!!!! Thanks !!!

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by Bernardoow** [comment]
Works for me too !!!!! Thanks !!!

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by Sekhno** [comment]
Works for me too !!!!! Thanks !!!

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by vinayakkulkarni** [comment]
`sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config`

Worked like a charm! Thanks a ton!

**Comment by IgorTsapyak** [comment]
Works for me!

Thanks...

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by Philyorkshire** [comment]
Worked for me, I got into this issue running 

`sudo bower install`

by mistake, which messed it all up. But then running 

`sudo chown -R $USER:$GROUP ~/.npm`
`sudo chown -R $USER:$GROUP ~/.config`

fixed it all for me.

**Comment by SibuStephen** [comment]
Thank you @alexlaw17  :) 

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by Carlos-Augusto** [comment]
It worked like magic

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

**Comment by iCristian** [comment]
Thanks
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

Work for me in ionic Framework Great!!

**Comment by rahul-jat** [comment]
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

this worked for me as well. :)

**Comment by baaronp7** [comment]
@appssunset 
Good call...
This is the one I needed:
sudo chown -R $USER:$GROUP ~/.cache

**Comment by shellygraham** [comment]
@alexlaw17 - Thanks man!

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config

Worked liked magic.
