### ISSUE TITLE
[Suggestion] Add a command line switch to use git submodules for components obtained via git in a git repo

### ISSUE THREAD

**Issue by charlesmilette** [bower/bower#2265]
I am working my website, that will use bower components. It is published using GitHub Pages.

Since GitHub Pages uses git to get the webpage code, and a lot of components means a lot of unuseful code, already present in some other git repo, bower could simply update the `.gitmodules` file, and then do `git submodules update` to get the components.

**Comment by sheerun** [comment]
sorry, bower doesn't integrate with version control systems that deeply
