### ISSUE TITLE
[Bug] Race condition behavior in bower.commands.install

### ISSUE THREAD

**Issue by jasonmit** [bower/bower#2267]
If you run multiple `bower.commands.install`'s in parallel the output of the last one to settle will write over the first settled install in the append line operation to `bower.json`

https://github.com/bower/bower/blob/343e6ac8bcb3ad69a90b2e8c37bf71796417f7b8/lib/core/Project.js#L44 `analyse` here reads `bower.json` and sets `that._json`

`that._json` is later used to append the line entry to once the async operation is complete.

https://github.com/bower/bower/blob/343e6ac8bcb3ad69a90b2e8c37bf71796417f7b8/lib/core/Project.js#L111 writes using the original `that._json` which doesn't contain the content of the first `bower.commands.install` since it settled before the update was written to `bower.json`

Order of operations:

```
* read bower.json into memory
* read bower.json into memory
* async fetching operation
* async fetching operation
* write update to bower.json using originally cached content
* write update to bower.json using originally cached content
```

Where I think it should be:

```
* read bower.json into memory
* read bower.json into memory
* async fetching operation
* async fetching operation
* re-read bower.json and write update to bower.json
* re-read bower.json and write update to bower.json
```

This is consistently reproducible if you clear your bower cache between tests.

**Comment by ptitgraig** [comment]
Thanks for reporting @jasonmit. Just to get it right, the use case is when one is running several install at the same time on the same projet ?

**Comment by jasonmit** [comment]
Yes and programmatically.

**Comment by jasonmit** [comment]
Let me know if you're open to another read before the right, to implement a lock to prevent concurrent installs, or a third option I am not thinking of.

**Comment by sheerun** [comment]
bower doesn't support "merging" of bower.json. if you operate on single project, you need to run commands sequentially, or pass multiple arguments to install / uninstall multiple things
