### ISSUE TITLE
Malformed .bower.json - Unexpected token `}`

### ISSUE THREAD

**Issue by SephVelut** [bower/bower#2268]
```
EMALFORMED bower_components/flot/.bower.json

Additional error details:
Unexpected token }

```
bower.json: https://gist.github.com/SephVelut/d28bef8cf10e5f4dcf663cbd8c1c17ba
failure output: https://gist.github.com/SephVelut/406412439bef11775d3c0b07224c1ccd
success_output: https://gist.github.com/SephVelut/1aeb0ad9992a6bfc54a4cbd8f7a471ef

With the above bower.json, If I do a `rm -rf bower_components && bower install` I'll get a malformed bower_components/flot/.bower.json in the official Flot library. https://gist.github.com/SephVelut/e031f6c51117a6309a49fcba43907e3f

If I do this a bunch of times, eventually I'll get a non malformed bower_components/flot/.bower.json.

**Comment by BenMann** [comment]
Can you provide the faulty `.bower.json?`
Pretty sure this is the same issue as https://github.com/bower/bower/issues/2067. With your `.bower.json` we can be sure.

**Comment by SephVelut** [comment]
failure: https://gist.github.com/SephVelut/e031f6c51117a6309a49fcba43907e3f

success: https://gist.github.com/SephVelut/560fab6f2a28d85b6bcbcef0185a9482

**Comment by BenMann** [comment]
Thanks!
Without further looking at the separate packages, I'm pretty confident that this is the same issue.
In short: Some of your dependencies are requiring `jquery` and others `jQuery`, which unfortunately are different packages in the registry. When writing to `bower_components` those two conflict.

given the packages below, it is very likely some are requiring the one version and others the other version of jQuery. There is currently no real fix for this. You could try to set a `resolution` to a certain jQuery version, but I am not sure that helps.

```
    "jquery-advanced-news-ticker": "https://github.com/risq/jquery-advanced-news-ticker.git#1.0.0",
    "jquery-minicolors": "^2.2.4",
    "jquery-ui": "^1.11.4",
    "jquery.cookie": "jquery-cookie#^1.4.1",
    "jquery.easy-pie-chart": "^2.1.6",
```

I'll close the issue in favor of the more elaborate one (https://github.com/bower/bower/issues/2067).
We're already working on a newer version of the registry, which will hopefully also fix this behavior by cleaning out such cases!

**Comment by SephVelut** [comment]
Gotcha. Thank you for looking into it.
