### ISSUE TITLE
My bower is installed. But on gulp serve I get the below issue,Error: Error: modernizr is not installed. Try running `bower install`.

### ISSUE THREAD

**Issue by priyatrp** [bower/bower#2269]

**Comment by ptitgraig** [comment]
Hello.
Is modernizr declared in your `bower.json` ? 
If so, have you run `bower install` ?

**Comment by priyatrp** [comment]
yes It is and Bower installation was fine. I verified using bower list and modernizr is listed with its version.

**Comment by priyatrp** [comment]
This is fixed . My bower install installed all its components under my project but my gulp server was expecting for bower components to be under a folder named bower_components. I created a folder bower_components and moved all its components under it after which gulp serve was running fine. Thanks for the help :) Grégory Pelletey.
