### ISSUE TITLE
`bower link` does not follow already-created bower links in dependencies of a module we're linking to, and overrides the existing local ones

### ISSUE THREAD

**Issue by jakub-g** [bower/bower#2273]
This is a bit complex case and I may understand if you want to reject it. I will open it anyway for reference.

Say I have these three components I am developing locally. I specified dependency between them like this, specifying that B depends on 1.0.0 of A (not yet released) and C depends on 1.0.0 of B (not yet released):

```
A
B->A
C->B
```

Then I do

```
cd A; bower link
cd B; bower link A; bower link       # will link A and install other deps too, fine
cd C; bower link B                   # bang!
```

`bower link A` installs linked package's dependencies as agreed in #673 hence in the second line I get deps of A installed.

In the last case, `bower link B` will try to install dependencies of B too; B depends on A#1.0.0 which is not yet released and bower will fail with `ENORESTARGET No version found that was able to satisfy 1.0.0` even though A has already been bower-linked.

I thought I could fix it by doing instead

```
cd C; bower link A; bower link B
```

but the result is the same.

It seems I need to already have something published matching the version from `bower.json` so that bower can resolve it, and only then I can do this kind of complex bower linking.

In fact, even when I have 1.0.0 released, when I do

```
cd C; bower link A; bower link B
```

then linking B will override the link created to A, so it seems I have to do bower linking in reverse order:

```
cd C; bower link B; bower link A
```

**Comment by vag1830** [comment]
Same issue for me. I am not sure if this is the expected functionality.

**Comment by sheerun** [comment]
Bower is deprecated and no longer recommended for development, please use yarn and yarn link instead
