### ISSUE TITLE
Make bower respect HTTP_PROXY/HTTPS_PROXY

### ISSUE THREAD

**Issue by orf** [bower/bower#2274]
Hello,
Why does Bower not respect the `HTTP_PROXY/HTTPS_PROXY` environment variables? It seems senseless that I have to re-define them in a special place just for bower.

Surely if the proxy keys are not defined anywhere in the configuration chain (`~/.bowerrc`, or `.bowerrc`) then the environment variables should be used? This allows project overrides if you so need.

**Comment by sheerun** [comment]
it should respect them

**Comment by orf** [comment]
Nope, it's never respected them as long as I've used it. I can't find any reference to the environment variables in any of the code either. `npm` doesn't either, but at least that has `npm config set proxy` you can run.

**Comment by sheerun** [comment]
here it is: https://github.com/bower/config/blob/master/lib/util/defaults.js
