### ISSUE TITLE
bower install crash 

### ISSUE THREAD

**Issue by guangyya** [bower/bower#2278]
bower --version @1.7.9

while doing $bower install , I got crash and stop at 

```
{
  "type": "input",
  "message": "Answer",
  "name": "prompt",
  "level": "prompt"

```

then I change bower version to 1.4.1, everything fine.

**Comment by ptitgraig** [comment]
Hey. Could you give us a more detailed error log ? 
Thanks

**Comment by guangyya** [comment]
above
```
{
  "type": "input",
  "message": "Answer",
  "name": "prompt",
  "level": "prompt"
```
is a lot of bower install dependence information. 

This is my bower.json file 

```
{
  "name": "angular-bootstrap-rails",
  "description": "A starter project for AngularJS with rails",
  "version": "0.0.1",
  "private": true,
  "dependencies": {
    "angular": "~1.2.21",
    "bootstrap": "*",
    "angular-route": "~1.2.21",
    "angular-resource": "~1.2.21",
    "jquery": "*",
    "angular-animate": "~1.2.16",
    "angular-bootstrap": "~0.11.0",
    "angular-http-auth": "*",
    "angular-strap": "~2.0.4",
    "angular-motion": "~0.3.3",
    "angular-cookies": "~1.2.21",
    "angular-sanitize": "~1.2.21",
    "angular-xeditable": "~0.1.8",
    "angles": "*",
    "esl": "~1.8.4",
    "angular-toastr": "~0.4.0",
    "ng-ckeditor": "~0.2.1",
    "ng-tags-input": "~2.3.0",
    "angular-ui-grid": "~3.0.0-rc.21",
    "ng-ckeditor": "~0.2.1"
  }
}

```



since I have already fixed this problem by change bower version,  sorry I am not able to reproduce that on my Mac.

**Comment by dudeofawesome** [comment]
I'm having a similar error whenever I try to init or install, although it does not seem to crash for me.

![image](https://cloud.githubusercontent.com/assets/1683595/15002883/f8f01dbe-115a-11e6-9b1d-d2c784cbdfe1.png)

It looks like it might be an issue related to inquirer.

I'm using ZSH and iTerm2 on OS X 10.11.3

**Comment by crayygy** [comment]
Hi there:
  I've already find the reason why bower install crash.

It's all caused by a wrong .bowerrc file.

The way to fix it is:
> 1. delete the 	`  "json": "bower.json"  ` line 
> 2. remember to delete the comma of the upper line.

at last, a .bowerrc file like this is fine.
```
{
  "directory": "public/bower_components"
}
```
That's all. 😆
