### ISSUE TITLE
bower home not working?

### ISSUE THREAD

**Issue by mrdulin** [bower/bower#2279]
![image](https://cloud.githubusercontent.com/assets/17866683/15063558/d2b660fc-137d-11e6-86b8-102d3b2f43e1.png)

Nothing happened..

Anyone tell me why? Am I doing wrong someting?

**Comment by evanjbowling** [comment]
That didn't open: https://github.com/jquery/jquery-dist and https://github.com/angular-ui/angular-ui-router-bower in your browser?

Are you using Cygwin?

**Comment by mrdulin** [comment]
@evanjbowling nope, I use win10 cmd. My default browser is chrome. I ran the command, but nothing happened.

**Comment by sheerun** [comment]
@mrdulin Does https://github.com/pwnall/node-open work for you?

**Comment by mrdulin** [comment]
@sheerun 
![image](https://cloud.githubusercontent.com/assets/17866683/15070368/64043a7e-13b6-11e6-8f6c-95445517a9f8.png)

![image](https://cloud.githubusercontent.com/assets/17866683/15070378/719d27cc-13b6-11e6-8715-9808d2160035.png)

`node-open` works.

**Comment by evanjbowling** [comment]
Ok, could you give us a bit more debugging information?

node version (run `node --version`)
npm version (run `npm --version`)
bower version (run `bower --version`)

Mine are:

node: v5.5.0
npm: 3.3.12
bower: 1.7.9

**Comment by mrdulin** [comment]
@evanjbowling 
![image](https://cloud.githubusercontent.com/assets/17866683/15139329/1b790e1e-16c8-11e6-982f-de0ee74630ef.png)

**Comment by BenMann** [comment]
@mrdulin can you try with another shell?
@bower/contributors can somebody on windows try and reproduce this?

**Comment by mrdulin** [comment]
@BenMann 
![image](https://cloud.githubusercontent.com/assets/17866683/15140900/dc455ae2-16cf-11e6-8847-aad941ccb4a5.png)

I try the windows `cmd` use `admin` , did not work neither.

![image](https://cloud.githubusercontent.com/assets/17866683/15140944/20fcbd7e-16d0-11e6-8e72-ab54471f64ee.png)

**Comment by sheerun** [comment]
Please try bower 1.7.9

**Comment by mrdulin** [comment]
@sheerun  

Finally! when I updated my bower version from `1.7.7`  to `1.7.9`, `bower home` command works.
Thanks!
