### ISSUE TITLE
While installing bower it gives error like <unexpected token> and error parsing json. Please refer below error log

### ISSUE THREAD

**Issue by AsmitaKudale** [bower/bower#2281]
C:\windows\system32>npm install -g bower
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3

npm ERR! Unexpected token <
npm ERR! <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w
.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm ERR! <html xmlns="http://www.w3.org/1999/xhtml">
npm ERR! <head>
npm ERR! <title>IIS 7.5 Detailed Error - 404.0 - Not Found</title>
npm ERR! <style type="text/css">
npm ERR! 
npm ERR! </style>
npm ERR!
npm ERR! </head>
npm ERR! <body>
npm ERR! <div id="header"><h1>Server Error in Application "DEFAULT WEB SITE"</h
></div>
npm ERR! <div id="server_version"><p>Internet Information Services 7.5</p></div

npm ERR! <div id="content">
npm ERR! <div class="content-container">
npm ERR!  <fieldset><legend>Error Summary</legend>
npm ERR!   <h2>HTTP Error 404.0 - Not Found</h2>
npm ERR!   <h3>The resource you are looking for has been removed, had its name
hanged, or is temporarily unavailable.</h3>
npm ERR!  </fieldset>
npm ERR! </div>
npm ERR! <div class="content-container">
npm ERR!  <fieldset><legend>Detailed Error Information</legend>
npm ERR!   <div id="details-left">
npm ERR!    <table border="0" cellpadding="0" cellspacing="0">
npm ERR!     <tr class="alt"><th>Module</th><td>IIS Web Core</td></tr>
npm ERR!     <tr><th>Notification</th><td>MapRequestHandler</td></tr>
npm ERR!     <tr class="alt"><th>Handler</th><td>StaticFile</td></tr>
npm ERR!     <tr><th>Error Code</th><td>0x80070002</td></tr>
npm ERR!
npm ERR!    </table>
npm ERR!   </div>
npm ERR!   <div id="details-right">
npm ERR!    <table border="0" cellpadding="0" cellspacing="0">
npm ERR!     <tr class="alt"><th>Requested URL</th><td>http://registry.npmjs.or
:80/bower</td></tr>
npm ERR!     <tr><th>Physical Path</th><td>C:\inetpub\wwwroot\bower</td></tr>
npm ERR!     <tr class="alt"><th>Logon Method</th><td>Anonymous</td></tr>
npm ERR!     <tr><th>Logon User</th><td>Anonymous</td></tr>
npm ERR!
npm ERR!    </table>
npm ERR!    <div class="clear"></div>
npm ERR!   </div>
npm ERR!  </fieldset>
npm ERR! </div>
npm ERR! <div class="content-container">
npm ERR!  <fieldset><legend>Most likely causes:</legend>
npm ERR!   <ul>         <li>The directory or file specified does not exist on t
e Web server.</li>      <li>The URL contains a typographical error.</li>
<li>A custom filter or module, such as URLScan, restricts access to the file.</
i> </ul>
npm ERR!  </fieldset>
npm ERR! </div>
npm ERR! <div class="content-container">
npm ERR!  <fieldset><legend>Things you can try:</legend>
npm ERR!   <ul>         <li>Create the content on the Web server.</li>  <li>Rev
ew the browser URL.</li>        <li>Create a tracing rule to track failed reque
ts for this HTTP status code and see which module is calling SetStatus. For mor
 information about creating a tracing rule for failed requests, click <a href="
ttp://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul>
npm ERR!  </fieldset>
npm ERR! </div>
npm ERR!
npm ERR!
npm ERR! <div class="content-container">
npm ERR!  <fieldset><legend>Links and More Information</legend>
npm ERR!   This error means that the file or directory does not exist on the se
ver. Create the file or directory and try the request again.
npm ERR!   <p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Er
or=404,0,0x80070002,7601">View more information &raquo;</a></p>
npm ERR!
npm ERR!  </fieldset>
npm ERR! </div>
npm ERR! </div>
npm ERR! </body>
npm ERR! </html>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\windows\system32\npm-debug.log

**Comment by BenMann** [comment]
If the issue persists please open an issue with the folks at npm as this error message says
```
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues
```
This is about installing Bower via npm not installing packages via Bower.
