### ISSUE TITLE
bower ignores bower.json in repository

### ISSUE THREAD

**Issue by andrewsalveson** [bower/bower#2284]
I'm trying to use a registered package (`obfilter`), but every time I install it `bower.json` is missing from `bower_components/obfilter` and nothing works. there is definitely a `bower.json` in the repo ([https://github.com/andrewsalveson/obfilter/blob/master/bower.json](https://github.com/andrewsalveson/obfilter/blob/master/bower.json))

if I create `bower.json` and copy in the contents from the repo everything seems to work, but when installing it's like it pretends the .json file doesn't exist. what am I doing wrong?

**Comment by sheerun** [comment]
Bower fetches latest tag, not latest commit:
https://github.com/andrewsalveson/obfilter/tree/088b4f87bd46e3219bb3cb9d8f6c3efb47387a95
