### ISSUE TITLE
Is there a `bower shrinkwrap` command?

### ISSUE THREAD

**Issue by mrdulin** [bower/bower#2285]
like `npm shrinkwrap`, lock down the version of the packages.

or, is there a way to do that? uh... except doing it manually.

**Comment by BenMann** [comment]
There are plans to integrate a shrinkwrap feature but there is currently no implementation.
Here`s the latest rebase of the original PR: https://github.com/bower/bower/pull/2100.
Feel free to contribute if you want to! I think there are also some lightweight implementations as modules on npm, maybe try searching there if you need it now.

**Comment by mrdulin** [comment]
@BenMann ok! Thanks!
