### ISSUE TITLE
Failure to install bower packages -Exit code # 128

### ISSUE THREAD

**Issue by kopgal73** [bower/bower#2286]
I'm getting below error every time I try to install any package with bower. I ran https instead of git command but still getting the same error. 

$ bower install jQuery
bower jQuery#*              not-cached https://github.com/jquery/jquery.git#*
bower jQuery#*                 resolve https://github.com/jquery/jquery.git#*
bower jQuery#*                 ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/jquery/jquery.git", exit code of #128 fatal: unable to access ### https://github.com/jquery/jquery.git/': Failed to connect to 198.208.159.17 port 80: Timed out

Additional error details:
fatal: unable to access 'https://github.com/jquery/jquery.git/': Failed to connect to 198.208.159.17 port 80: Timed out

**Comment by BenMann** [comment]
Make sure that `git ls-remote --tags --heads https://github.com/jquery/jquery.git` works for you. It's most likely a misconfiguration with git. Please also refer to this [issue here](https://github.com/bower/bower/issues/2172). There are also threads [elsewhere](http://stackoverflow.com/questions/21544803/git-bower-errors-exit-code-128-failed-connect) that might help. :cake:

**Comment by kopgal73** [comment]
Thanks a bunch @BenMann  

It was the global config file which has wrong proxy information. Once I fixed that, issue is resolved quickly.

**Comment by punnashivakrishna** [comment]
'CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g'
operable program or batch file.


i'm getting error ,when i tried 
npm install -g bower.


can anyone help me
