### ISSUE TITLE
fatal: unable to access 'https://github.com

### ISSUE THREAD

**Issue by vivex** [bower/bower#2288]
I am facing this issue in my ubuntu system, node version is 5.0.0 , bower version is 1.7.9
i am able to access github so  there is no network problem and i am not using any proxy, and using https:// only. But still it is saying 

```
 ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/angular/bower-angular-route.git", exit code of #128 fatal: unable to access 'https://github.com/angular/bower-angular-route.git/': Could not resolve host: github.com

Additional error details:
fatal: unable to access 'https://github.com/angular/bower-angular-route.git/': Could not resolve host: github.com
```

if i run "git ls-remote --tags --heads https://github.com/angular/bower-angular-route.git" from command line it give valid output.

**Comment by evanjbowling** [comment]
Can you paste your `bower.json` file? I was able to install that library via:

    bower install https://github.com/angular/bower-angular-route.git

**Comment by awoerner92** [comment]
I also came across this error which I was able to solve with this:
`
git config --global url.git://github.com/.insteadOf https://github.com/
`

Hope that helps!

**Comment by sheerun** [comment]
what is your git version?

**Comment by awoerner92** [comment]
2.7.4

**Comment by antongorodezkiy** [comment]
Have the same issue
CentOS 6.8
Bower version: 1.7.9
Node version: 5.2.0

**Comment by vivex** [comment]
@sheerun  Git version is 1.9.1 node version is 5.4.0 bower version is 1.7.9 , This error is occurring in every package, some time it says access to github failed some time it says access to herokuapp failed.  i am not able to install even a single package,

**Comment by sheerun** [comment]
Most likely it's your internet connection or old git version..

**Comment by Kingdez** [comment]
#1730 wow @awoerner92 is right i was struggling for two days to solve the issue i just typed what he said into my gitbash and it worked i am using a windows 8.1 pro on a wireless network try it out this is the command. git config --global url.git://github.com/.insteadOf https://github.com/

**Comment by lukedottec** [comment]
Quite an old thread, but if you've read down to here then you've likely not found a solution. Thought I'd try and help out. 

For me, the error was **incompatible/out-of-date versions of git**. Try updating your git version and see if that helps. Removing the security of HTTPS seems like a risky workaround.

**Comment by SaravananTms** [comment]
Try with this line
 git config --global https.proxy http://3.28.29.241:88
This will solve the above fatal error

**Comment by fperezci** [comment]
> Try with this line
> git config --global https.proxy http://3.28.29.241:88
> This will solve the above fatal error



> Try with this line
> git config --global https.proxy http://3.28.29.241:88
> This will solve the above fatal error

Thank for this observation...
I config wrong my proxy in git

**Comment by saurabh-dongre-au25** [comment]
fatal: unable to access 'https://github.com/attainu/saurabh-dongre-au25.git/': Could not resolve host: github.com

**Comment by LuckyNwekeKFC** [comment]
> git config --global url.git://github.com/.insteadOf https://github.com/

I also came across this error which I was able to solve with this:
git config --global url.git://github.com/.insteadOf https://github.com/

Hope that helps!

by @awoerner92

**Comment by fendiflexin** [comment]
> I also came across this error which I was able to solve with this: `git config --global url.git://github.com/.insteadOf https://github.com/`
> 
> Hope that helps!

Worked for me. Thanks!
