### ISSUE TITLE
Private Repository Install via HTTPS: exit code #128

### ISSUE THREAD

**Issue by p-hebert** [bower/bower#2291]
I am trying to install two private bitbucket repositories to which I have access, both under the same organization name. Trying to install the first repository exits successfully, but installing any other private repository under the same organization exits with `exit code of #128 fatal: I don't handle protocol '<first repository name>=https'`.

The two commands used are in this format:
`bower install https://bitbucket.org/<organization>/<repository>.git --save`

The first repository completes successfully while the second one ends up with the following trace:

```
bower not-cached    <Name of Repository 1>=https://bitbucket.org/<organization>/<repository2>.git#*
bower resolve      <Name of Repository 1>=https://bitbucket.org/<organization>/<repository2>.git#*
bower not-cached    https://bitbucket.org/<organization>/<repository2>.git #*
bower resolve       https://bitbucket.org/<organization>/<repository2>.git #*
Username for 'https://bitbucket.org': p-hebert
Password for 'https://p-hebert@bitbucket.org': 
bower checkout     <repository2>#master
Username for 'https://bitbucket.org': p-hebert
Password for 'https://p-hebert@bitbucket.org': 
bower progress      <repository2>#* remote: Compressing objects:   0% (1/199)   
bower progress      <repository2>#* remote: Compressing objects:   1% (2/199)   
bower progress      <repository2>#* remote: Compressing objects:   2% (4/199)   
bower progress      <repository2>#* remote: Compressing objects:   3% (6/199)   
bower progress      <repository2>#* remote: Compressing objects:   4% (8/199)   
bower progress      <repository2>#* remote: Compressing objects:   5% (10/199)   
bower progress      <repository2>#* remote: Compressing objects:   6% (12/199)   
bower progress      <repository2>#* remote: Compressing objects:   7% (14/199)   
bower progress      <repository2>#* remote: Compressing objects:   8% (16/199)   
bower progress      <repository2>#* remote: Compressing objects:   9% (18/199)   
bower resolved      https://bitbucket.org/<organization>/<repository2>.git#6180289d64
bower ECMDERR       Failed to execute "git ls-remote --tags --heads <Name of Repository 1>=https://bitbucket.org/<organization>/<repository2>.git", exit code of #128 fatal: I don't handle protocol '<Name of Repository 1>=https'
```

What is weird here is how the name of the previously installed repository pops up even though I specified the URL to the second repository.
I am under Ubuntu Trusty 14.04, with bower 1.7.9 and npm 3.6.0.

**Comment by sheerun** [comment]
Could you provide git version and example repository to reproduce?

**Comment by p-hebert** [comment]
Alright, so git version is 1.9.1 .
As for example repository to reproduce, I created repositories to reproduce the situation but I was unable to reproduce the bug. I can still give you access to the said repositories (and team) created for this bug.
Let me check if I can dig something up. Is there any test tools I can load to test bower functionalities?

**Comment by p-hebert** [comment]
Must have been some kind of hiccup or a typo somewhere. I couldn't reproduce at all, and I was even able to install the repositories on my own repository. You can close the issue if you want to.

**Comment by p-hebert** [comment]
Extra info: I was successful in installing both repositories on the condition that the url passed had the user specified in there, like so: ` https://p-hebert@bitbucket.org/<organization>/<repository>.git#`. Hence I successfully circumvented the problem where it was an issue by creating a read-only bitbucket user for the team to use while setting up dependencies.
