### ISSUE TITLE
Allow reregistering existing packages when only protocol is changed

### ISSUE THREAD

**Issue by ghost** [bower/bower#2292]
So as to make git => http => https easy even for non-github packages.

I want to migrate my packages, but https://github.com/bower/registry/issues/193 where I asked for manual migration is left unanswered for weeks.

**Comment by BenMann** [comment]
Which packages are we talking about exactly?
As I understand it, all packages have been automatically changed to use https (I might be wrong). If you provide the actual package names, I can check and unregister them in case, so you could re-register them.

**Comment by herby** [comment]
This issue is about allowing that in bower cli, not doing it for specific packages.
Are you telling that bower now uses https for every url evrn if it is registered with git:// (we're talking non-Github ones)?

Dňa 10. júna 2016 10:35:55 CEST používateľ Ben <notifications@github.com> napísal:

**Comment by sheerun** [comment]
Agree it's good idea. We don't have time to implement it, but you can do it if you want.
