### ISSUE TITLE
Multiple registries configuration fails on the the first attempted search

### ISSUE THREAD

**Issue by treilhes** [bower/bower#2293]
Hello,
When using the following configuration
`"registry" : {
        "search" : [ 
            "http://xxxxx:8081/repository/private-bower.herokuapp.com",
            "http://bower.herokuapp.com" 
        ]
    }`

When the private registry is not accessible i get the following error

`[ERROR] bower angular-filter#0.5.8     EINVRES Request to http://xxxxx:8081/repository/private-bower.herokuapp.com/packages/angular-filter failed with 503`

I was expecting bower to fall back to http://bower.herokuapp.com. Am i missing something?
Thanks for your time and efforts.

**Comment by lmesz** [comment]
Hello,

Did you find any workaround for your issue ? I faced the same issue.

**Comment by treilhes** [comment]
Hello,
A bit late answer but no, we did a workaround using maven profile and bower command line argument.

When the private registry is accessible the argument --config.registry=${bower.registry} is set to the private registry url.
When it is not, a maven profile "nonexus" is activated and the argument --config.registry=${bower.registry} is set http://bower.herokuapp.com
