### ISSUE TITLE
Can't init oder install bower 1.7.9

### ISSUE THREAD

**Issue by mirkoschubert** [bower/bower#2294]
Every time I want to use `bower init` or `bower install`, I get an error that the name must be lowercase. Here is the error in verbose mode:

> bower init -V
> bower EINVALID      Name must be lowercase, can contain digits, dots, dashes, "@" or spaces
> 
> Stack trace:
> Error: Name must be lowercase, can contain digits, dots, dashes, "@" or spaces
>     at createError (/usr/local/lib/node_modules/bower/lib/node_modules/bower-json/lib/util/createError.js:2:15)
>     at validate (/usr/local/lib/node_modules/bower/lib/node_modules/bower-json/lib/json.js:215:15)
>     at Function.parse (/usr/local/lib/node_modules/bower/lib/node_modules/bower-json/lib/json.js:115:9)
>     at /usr/local/lib/node_modules/bower/lib/util/readJson.js:35:31
> From previous event:
>     at init (/usr/local/lib/node_modules/bower/lib/commands/init.js:43:6)
>     at /usr/local/lib/node_modules/bower/lib/commands/index.js:33:28
> From previous event:
>     at withLogger (/usr/local/lib/node_modules/bower/lib/commands/index.js:40:14)
>     at Function.runFromArgv [as line](/usr/local/lib/node_modules/bower/lib/commands/index.js:30:16)
>     at Object.<anonymous> (/usr/local/lib/node_modules/bower/lib/bin/bower.js:83:26)
> 
> Console trace:
> Error
>     at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
>     at Logger.<anonymous> (/usr/local/lib/node_modules/bower/lib/bin/bower.js:110:26)
>     at emitOne (events.js:77:13)
>     at Logger.emit (events.js:169:7)
>     at Logger.emit (/usr/local/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
>     at /usr/local/lib/node_modules/bower/lib/commands/index.js:48:20
>     at _rejected (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
>     at /usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
>     at Promise.when (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
>     at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
> System info:
> Bower version: 1.7.9
> Node version: 4.4.4
> OS: Darwin 15.5.0 x64

**Comment by BenMann** [comment]
Can't reproduce..
The error indicates that the package name is invalid, but there shouldn't be one in case you run `bower init` in an empty directory. Is there anything your directory when you run those commands? Can you provide a `bower.json` if there is any?

**Comment by mirkoschubert** [comment]
You're right, I have to specify that. I tested it out on a new and empty directory. In this case `bower init` works perfectly and creates a `bower.json`. But if I use it on a existing directory with installed nodejs packages (but no `bower.json`), the same error message appears. I wanted to use it with `jescalan/roots`, so I first installed roots and then tried bower. Same result: error message and no `bower.json`.

**Comment by macik** [comment]
Getting same issues...

After some test found that get this error on not all folders.
Seems it caused by local names in path (or other special symbols like `#`).
running in `c:\test\` -  it's ok
running in `c:\тест` - getting mentioned error

Bower 1.7.9
Windows 7x64

**Comment by AndreLachance** [comment]
Im getting the same problem, Fresh install of npm and nodejs in the project folder,
 did npm install bower -g
ran fine, installed 1.7.9

then in the project folder ran bower init, returns bower EINVALID.  
Path contains uppercase and lowercase and digits, but no special characters.

Same specs as macik, windows 7x64 and bower 1.7.9

**Comment by comfymike** [comment]
if you're using NPM, and therefore have a package.json file, bower will try to use the name you provided in that file.

when that name contains any of the disallowed characters, bower will throw you this error, as if you supplied an invalid name.
