### ISSUE TITLE
Add revert functionality to bower

### ISSUE THREAD

**Issue by SteveTheTechie** [bower/bower#2296]
Bower would benefit from some type of "revert to previous" functionality for package updates.  I sometimes run into a case where breaking changes have been made to a package I am using...  Sometimes those breaking changes affect me, sometimes they do not, and I can only be sure by testing the updated package before actually deploying it.

I could certainly fiddle around with multiple bower repositories or a gulp task to address this, but those seem like they would be a bit more cumbersome.  A better solution might be to enable bower update to save the current package version somewhere before updating it so that a "revert to previous" is possible via a simple "bower revert packagename" command.

**Comment by thinkxl** [comment]
You can install a specific version of the package by doing `bower install <package>#<version>`.

Having a `bower revert <package>` would just do that in the background, with additional functionality for defining a previous version, so installing with specific one is more flexible.

Check http://bower.io/docs/api/#install for further explanation.

**Comment by sheerun** [comment]
Yeah, no random new feature for now.. sorry!

**Comment by SteveTheTechie** [comment]
Thanks for the reply.

However, I would respectfully point out that I would think that having Bower keep track of what versions have been installed (version history) for each package is a better proposition than having me keep (or lose) track of that.  ;-D

Having the "flexibility" of installing a specific package version is very nice, but typically I just want to install the latest version of packages and have the ability to revert to the last installed version if the latest package version breaks stuff when it is installed.

**Comment by thinkxl** [comment]
@SteveTheTechie You should use git for that. When you need to introduce breaking changes (installing new version of a dependency is one) create a test branch, if the change breaks your software you can go back to the working branch, or merge them together if you see that everything went fine.

I don't think that's a task for bower :smile:
