### ISSUE TITLE
Terminal Handling Broken in Interactive Modes

### ISSUE THREAD

**Issue by c-j-s** [bower/bower#2299]
In a standard xterm (version `XTerm(297)` on Ubuntu 14.04) with `TERM=xterm` in the environment, bower messes up the terminal handling when it tries to ask questions interactively. The initial question looks fine, but any keypress moves the `Answer` prompt a dozen or so lines up the screen and some way across, and subsequent keypresses continue this movement. (`vim` and other programs work just fine.)

Running with `TERM=` (i.e., "glass TTY mode") removes the color, but the cursor movement problems remain.

See the image below for an example of what the screen looks like after a few keypresses.

As well as fixing the problem in bower or whatever library it's using, it would also be nice to have a command-line option to ask it not to do special terminal handling but just work as a normal command-line program.

![bower-broken-terminal-interaction](https://cloud.githubusercontent.com/assets/2586652/15738527/b46899d4-28e6-11e6-9c6d-3aab21657127.png)

**Comment by sheerun** [comment]
This should be fixed in `inquirer` that bower uses. Please raise this issue there if it's still present in newest version of it.

**Comment by c-j-s** [comment]
This still occurs in Bower 1.8.0 running under node v6.9.1. I did `npm update -g` before doing this test:
![bower](https://cloud.githubusercontent.com/assets/2586652/20252464/c050dd00-aa65-11e6-8d06-2303b66fdf45.png)
