### ISSUE TITLE
Loading nested private repos prevents entering credentials

### ISSUE THREAD

**Issue by cttibbetts** [bower/bower#2300]
I am trying to load a private repo that depends upon another private repo. When I try to `bower install` the second repo, the way the github credential prompt is presented overlaps, preventing me from entering my credentials. If it matters, the top project depends on both project 1 and project 2

An example:
Project 2's bower.json would look like 

```
{
    ...
    "dependencies": {
        "project1": "https://github.com/private/repo1.git"
    }
}
```

When I try to `bower install --save https://github.com/private/repo2.git`, the output reads

```
bower not-cached https://github.com/private/repo2.git
bower resolve       https://github.com/private/repo2.git
bower not-cached https://github.com/private/repo2.git
bower resolve       https://github.com/private/repo2.git
bower cached       https://github.com/private/repo1.git
bower validate      <version> against https://github.com/private/repo1.git#^<version>
Username for 'https://github.com': Username for 'https://github.com': 
```

Where the last line prompts me for credentials twice at the same time. 
I have not yet been able to find a combination of username/password entries that will get beyond that nested prompt.
It would be nice if when a prompt was needed, it would wait for entry before the next git repo was accessed.

**Comment by cttibbetts** [comment]
Correction - if I enter my credentials twice, then my passsword twice, it works. However, the second password entry is typed into the console, not hidden at all.

**Comment by JanGe** [comment]
I had the same problem today and could work around it by replacing `https://github.com/` with `git@github.com:`.

**Comment by sheerun** [comment]
entering credentials this way never was officially supported
