### ISSUE TITLE
"No versions available" from bower info [package]

### ISSUE THREAD

**Issue by suewonjp** [bower/bower#2301]
Hello.

I'm new to Bower but trying to publish my github project [dndx.js](https://github.com/suewonjp/DNDX.JS) via Bower.

I've registered my project with _bower register_, but _bower info_ keeps saying that **"No versions available"**

I've specified the version as **0.5.0-beta.0**. (for both [bower.json](https://github.com/suewonjp/DNDX.JS/blob/master/bower.json) and the [tag](https://github.com/suewonjp/DNDX.JS/releases/tag/0.5.0-beta.0))

I know you would get this message when your _semver_ is incorrect (e.g., 1.0, which is not [major, minor, patch] tuple), but my version notation is an incorrect _semver_ too?  If not, why do I get this message?

**Comment by sheerun** [comment]
`--verbose` shows also pre-release versions
