### ISSUE TITLE
Scripts are executed when all of packages have already been installed

### ISSUE THREAD

**Issue by lovanwubing** [bower/bower#2302]
I spent several hours on figuring out why postinstall scripts are not executing. Here is my configuration in .browerrc.

"scripts": {
    "postinstall": "bower link wf-shared"
 }

When I tried to execute "bower install", nothing happened. Then I tried to debug the code by myself, and found out the following code in https://github.com/bower/bower/blob/master/lib/core/Manager.js#L131 :
    if (mout.lang.isEmpty(that._dissected)) {
        return Q.resolve({});
    }

The interesting thing is: If I have already installed all of the packages, the variable "_dissected" will always be empty object.

I think it should be a bug, because I always want to execute the scripts when I execute "bower install". The npm install have the correct behavior.

**Comment by marfous** [comment]
The same for me, please could you take a look on that? As reporter mentions, the NPM postinstall script works differently and runs the script always, the Bower's not.

**Comment by sheerun** [comment]
We can't change this behavior now and bower is deprecated
