### ISSUE TITLE
Support @ as an alternative name version separator

### ISSUE THREAD

**Issue by sheerun** [bower/bower#2307]
Migrated from bower/endpoint-parser

---

The current `#` doesn't work unquoted in ZSH which makes it annoying to use. It's also inconsistent with npm which uses `@` (for that exact reason?).

Add support for using both `@` and `#` when doing eg. `bower install`

```
bower install jquery#2
bower install jquery@2
```

---

Are you sure? Dependencies that will use this format won't be backward-compatible.

---

Just for installing in the CLI, not bower.json.

**Comment by ubermuda** [comment]
It would be more clear and less wtf-prone if only one version separator was supported. I can already see people used to "bower install jquery@2 --save" trying to add "somethingsomething@3" in their bower.json.

It would be a BC-breaking change indeed, but it could be introduced in 2.x. After all, what are major version changes for if not for BC?

If you're worried about the migration path, double support could be in 1.8 (or 1.9), with a deprecation warning encouraging people to migrate their config file to `@`

**Comment by sheerun** [comment]
For now let's just allow it in CLI, undocumented, without any deprecations

**Comment by wookoouk** [comment]
I am looking at this issue but I cannot access the bower-registry-client source, is it private?

**Comment by sheerun** [comment]
It's in the main repository now (bower/bower/packages)

**Comment by wookoouk** [comment]
Thanks, I am looking at multiple solutions to this ticket,
for example, it would be possible to just modify bower-endpoint-parser to replace @ with # when parsing the endpoint, this would mean that all logs would still show #, the alternative would require a major overhaul on the code.

**Comment by sheerun** [comment]
It's ok to just modify "bower install" command to replace @ with #, no need to modify parsing logic.

**Comment by wookoouk** [comment]
Im happy to that but there are other commands (such as `bower info`) that could be given a @. Wouldn't it make sense to allow all the tools to accept @ is `install` does?

**Comment by sheerun** [comment]
Ach, you're right. Maybe it's better to modify bower-endpoint-parser  like you suggested :)

**Comment by wookoouk** [comment]
If we change it there it will trickle down to everything else, it would also mean that if this gets made a 'thing' we could store the separator value (@ or #) in the endpoint object so it could be used in logs, bower.json, etc.
Not sure how to best write a test for this (based on the current test setup) but ill figure something out.

**Comment by sheerun** [comment]
Probably an integration test in test/commands/install.js would be the best. Maybe plus one unit test in parser itself

**Comment by wookoouk** [comment]
Due to the decompose function also being used for git urls and other strings that are designed to have @ symbols in, I will do as originally planned and replace inside the commands. this can be replaced if/when documented support if brought in.

**Comment by sheerun** [comment]
agreed

**Comment by wookoouk** [comment]
I have put a pull request in the using @ within the info command https://github.com/bower/bower/pull/2320

Just working on testing the install command, the current test (helper) setup does not seem to allow using # to specify a version of a 'fake' dependency.

**Comment by wookoouk** [comment]
Merge replaced with https://github.com/bower/bower/pull/2322

**Comment by wookoouk** [comment]
Completed with https://github.com/bower/bower/pull/2322
