### ISSUE TITLE
Package shows in cmdline search but not on website search

### ISSUE THREAD

**Issue by nickweedon** [bower/bower#2309]
It seems that my package 'xhr-adaptor-js' and others do not show up in the bower search website however they do show up on command line when doing a "bower search xhr-adaptor-js".

Note that I am aware that this has already been reported in #1627 however this issue seems to have been incorrectly closed as the duplicates that are referred to do not exist and yield a 404 error when you attempt to follow them.

I have only re-registered this package in the last hour or so, is it that I just need to wait for a while for the website to update?

If somebody could explain what the requirements are to have a bower package shown on the website search and explain how regularly the database is indexed (i.e. how often the search results get updated) , that would be great.

Thanks

**Comment by BenMann** [comment]
The issue hasn't been closed incorrectly, the repositories under which the referred-to-issues were stored (and closed) just disappeared, as we moved them into bower/bower.
Indeed indexing takes nothing but time. We recently moved the search to use [libraries.io](http://libraries.io), which has your package on the radar already, not super sure how long it will take though.

**Comment by sheerun** [comment]
I've notified libraries.io author

**Comment by BenMann** [comment]
Seems to work by now! 🍰

**Comment by sheerun** [comment]
Not exactly. If you type only the prefix it doesn't show. We're working on it.

**Comment by nickweedon** [comment]
Here is some more info on the current erroneous search behavior (note that this is just a sample of some of the incorrect behavior):

**Scenario 1 - Fail**
Enter search string: 
>  adaptor

Expected results:
>  xhr-adaptor-js
  _(any other result with 'adaptor' in the name)_

Actual Results:
>  Nactive-adaptors-backbone
  ractive-adaptors-stapes
  Ractive-adaptors-Promise
  ractive-adaptors-rxjs
  ractive-adaptors-bacon
  ember-data-sails-adapter
  ractive-backbone
  signal
  demock-angular
  demock-jquery

**Scenario 2 - Fail**
Enter search string: xhr-adap
Expected results:
>  xhr-adaptor-js
  _(any other result with 'xhr-adap' in the name)_

Actual Results:
> _(none)_

**Scenario 3 - Pass**
Enter search string: xhr-adaptor
Expected results:
>  xhr-adaptor-js
  _(any other result with 'xhr-adaptor' in the name)_

Actual Results:
> xhr-adaptor-js

**Comment by sheerun** [comment]
Thank you for additional info, @andrew will be working on it this week

**Comment by andrew** [comment]
Maybe it's worth switching the command line search to use the same api so as to avoid confusing people with different results?

**Comment by sheerun** [comment]
We could do it, but first they need to match :) Bower CLI search integration would be little different as we can't magically change already released bower versions, forwarding to new search server needs to happen server-side.

**Comment by sheerun** [comment]
This should be fine now, but unfortunately still:

1. Search is not case-insensitive
2. Results are not ordered by stars-count

@andrew Could you handle it maybe?

**Comment by andrew** [comment]
@sheerun you can sort search results by stars by adding `&sort=stars` to the api query but I wouldn't recommend it as you'll lose all relevance ordering and things like https://libraries.io/bower/testPackage will show up for a search of jquery: https://libraries.io/search?q=jquery&platforms=Bower&sort=rank&sort=stars

**Comment by sheerun** [comment]
Even for bower-search endpoint?

**Comment by andrew** [comment]
Should bower packages be considered case insensitive? If so I can remove all the duplicates from the libraries database which will help remove those extras results

**Comment by andrew** [comment]
I can change the sorting for /api/bower-search at the weekend

**Comment by julmot** [comment]
> Should bower packages be considered case insensitive? If so I can remove all the duplicates from the libraries database which will help remove those extras results

I'm going to create another issue regarding this in a few minutes.

**Comment by sheerun** [comment]
@julmot Please do it on bower/registry

**Comment by sheerun** [comment]
@andrew Bower packages are case-sensitive, but probably search results should be case-insensitive

**Comment by julmot** [comment]
@sheerun Done.

**Comment by nickweedon** [comment]
I think this needs to be re-opened since the fix has regressed previous search behaviour. Specifically, as seen in "Scenaio 1" as documented above, the search used to function as a free text search. It appears that this is now no longer the case and instead the search is anchored to the start of the string, like a prefix search. This unfortunately makes the search engine significantly less useful since you must know precisely what you are searching for before you search for which somewhat defeats the purpose.
