### ISSUE TITLE
Bower api for list()

### ISSUE THREAD

**Issue by prateekjadhwani** [bower/bower#2310]
## QUESTION

Hi Team, I am trying to use bower api to list the packages installed in a particular directory using node.  

When I run it this way

```javascript
        bower.commands
        .list()
        .on('end', (results) => {
            console.log(results);
        });
```

it works fine and returns the package name on the root level but 

```javascript
         bower.commands
        .list({paths: './sub-dir/components'})
        .on('end', (results) => {
            console.log(results);
        });
```
doesnt work and returns an empty object `{}` even though there are bower packages installed in that folder.

any suggestions?

**Comment by sheerun** [comment]
`paths` is boolean param. you can pass custom directory as third argument, something like:

```
bower.commands
.list(undefined, undefined, { cwd: path.resolve(process.cwd(), 'foo/bar') })
```

**Comment by sheerun** [comment]
Also, issue tracker is not a place for support questions, please do it on discord or stackoverflow

**Comment by prateekjadhwani** [comment]
Hi @sheerun  Thanks for the answer. But, the solution doesnt work.

**Comment by aemonge** [comment]
How should one set the --offline option for this ?

**Comment by prateekjadhwani** [comment]
Does it work @aemonge  ?
Does it give you the list of installed packages?

**Comment by aemonge** [comment]
Yeah, it does works. But it slow enough that I think it's committing the `offline: true` option.
