### ISSUE TITLE
Enterprise support for registries that require authentication.

### ISSUE THREAD

**Issue by blindenvy** [bower/bower#2311]
Problem:
It is common for organizations to maintain a private bower repository hosting their own artifacts as well as proxying the public central repositories using software like nexus, artifactory, etc. These environments are usually secure and require authentication when accessing any resources; as such the user credentials must be provided in bower configuration. Currently the only way to do that is to supply them in clear text in the url of the various registries (search, register). This is a problem in enterprise settings where company policy forbids credentials being store in clear text in configuration files, typically a minimum requirement is for those credentials to be encoded (eg. base64, etc.). 

Solution:
Making modifications to bower-registry-client and adding new optional configuration parameters to bower that allow encoded credentials to be provided for each registry can resolve this use case. An example configuration would look like:

```
"registry" : {
  "search" : [ "https://example.com:8450/repository/bower-all/" ]
},
"registryAuth" : {
  "search" : [ "dXNlcjpwYXNz" ]
}
```

I would like to ensure support for this enhancement before I attempt to implement it.

**Comment by sheerun** [comment]
Hey. `.bowerrc` supports interpolation of ENV variables. Does it solve your issue?

https://bower.io/docs/config/#environment-variables-in-bowerrc

**Comment by blindenvy** [comment]
Hi. Thanks for the suggestion (I was already aware of env variable support.) Unfortunately we have the same restrictions on storing passwords in cleartext in environment variables, so that does NOT solve my issue.

**Comment by sheerun** [comment]
Hmm. Maybe we could create something like https://bower.io/docs/pluggable-resolvers/ but for registry

**Comment by sheerun** [comment]
Bower is not deprecated and won't implement new features like this one
