### ISSUE TITLE
what about a bower components loader for browsers ?

### ISSUE THREAD

**Issue by tnga** [bower/bower#2312]
The approach using for [bowerder](https://github.com/tnga/bowerder) can be a good start since components are provided with files ready for production. However it's far away from es-module/commonJS/AMD module philosophy. That said feedback are welcome, specially if they concern behavior, necessity and enhancements.

![bowerder-logo](https://raw.githubusercontent.com/tnga/bowerder/master/bowerder.png)

Maybe once can think that it isn't a place for that but since this specially concern bower, why not ?

**Comment by sheerun** [comment]
Hey. That's a nice project, it's really similar to jspm. It could be good for development, but production applications probably require also bundler like webpack, jspm, browserify, or rollup.

**Comment by tnga** [comment]
Web technologies are growing so fast with divers solutions. However, it firstly affect particular developers who are directly involved. From universities to startup, it generally with time that they get involved. Specially in my country, when i look around, CommonJS, AMD, es-module features are just improvements that once ear about (if he do) and that will maybe transform the future of project's development. (*soon old or maybe*) actual approach steel persevere (*and maybe will continue to*) because it is difficult to tell today to someone who want to learn thing that he have to do like this and tomorrow that he have to throw it because this (*for him complicate (this because he is inexperienced)*) (*for you better (cause your are experienced and futurist)*) new way is more efficient.

without counting that these new solutions (*preferable for professional developers*) are like Linux was (or is) to Windows users.

**Comment by sheerun** [comment]
Feel free to send PR to list this project on our official "Tools" page :)
https://bower.io/docs/tools/
