### ISSUE TITLE
Token login does not work

### ISSUE THREAD

**Issue by bluesmoon** [bower/bower#2317]
**Output of `bower -v && npm -v && node -v`:**

```
$ bower -v
1.7.9
$ npm -v
3.8.3
$ node -v
v5.10.1
```

**Steps to reproduce the issue:**
1. Generate token on github
2. `bower login -t <token>`

**Describe the results you received:**

```
bower EAUTH         Logged in as undefined
```

**Describe the results you expected:**

I expected to be logged in as user `bluesmoon`, not as `undefined`

**Additional information:**

**Comment by LoganArnett** [comment]
+1 for this one, having this issue when running `bower install` on Travis-CI

**Comment by DavidTPate** [comment]
I'm receiving the same result. Additionally when attempting to use the solution here: http://stackoverflow.com/a/26069427/1076683 I'm not able to access private dependencies locally or on my CI server.

Seems to be an issue with the latest version of bower as even builds that were passing yesterday for me are no longer even able to install my `bower` components.

**Comment by LoganArnett** [comment]
@DavidTPate pointed out updates to the Github API and the Node Github package as a possible issue:
https://github.com/mikedeboer/node-github

**Comment by DavidTPate** [comment]
Yeah, this issue isn't really a priority for me anymore. It was the catalyst that I needed to just finally move off `bower` onto `npm`.

**Comment by sheerun** [comment]
It seems like UI error. If you provide correct token, `bower unregister` should work.

**Comment by sheerun** [comment]
@DavidTPate Bower bundles all of its dependencies so literally nothing changes since last release.

**Comment by DavidTPate** [comment]
Gotcha @sheerun Maybe it's GitHub deprecating part of their API or something then? I'm unable to retrieve any of my private dependencies whether I use SSH or include the credentials in the URL.

**Comment by sheerun** [comment]
None that I'm aware of. "bower login" isn't connected with private packages authentication in any way. Its only purpose is to authenticate for "bower unregister" command. You might be experiencing another issue, but we need steps to reproduce to fix it.
