### ISSUE TITLE
jquery-ui-sass

### ISSUE THREAD

**Issue by mscarchilli** [bower/bower#2318]
Just tried adding the jquery-ui-sass package. It actually points to jquery-ui-sass-rails, and it does not actually include any sass files. Not sure how that is fixed on your side, but just thought I'd let you know since the package name in Bower is misleading, and the bigger issue that it doesn't have any sass files.

More people are actually probably looking for the jquery-ui-scss package instead.

**Comment by sheerun** [comment]
It's not an issue with bower itself, sorry
