### ISSUE TITLE
`bower install` installs a large amount of dependencies

### ISSUE THREAD

**Issue by anesumuz** [bower/bower#2323]
Running bower install downloads a huge amount of data.

 bower install angular --save downloads more than 22MB (I quit the install at 22MB) and bower install jquery more than 11MB.

What could be the issue here? I'm running version 1.7.9 on Ubuntu Linux 12.04 LTS

**Comment by wookoouk** [comment]
Could you paste your bower file here please

**Comment by wookoouk** [comment]
No response in 2 months. Closing
