### ISSUE TITLE
Can't use github commit reference, "reference is not a tree"

### ISSUE THREAD

**Issue by 1mike12** [bower/bower#2325]
**Output of `bower -v && npm -v && node -v`:**

```
1.7.9
2.15.5
v4.4.5

```

**Additional environment details (proxy, private registry, etc.):**

**Steps to reproduce the issue:**
try to install a specific commit of angular material repo
1. `bower install https://github.com/angular/material.git#1663341d5d67c225b6953ee7d3ebc5d56823fa4b --save`

**Describe the results you received:**
The package is not installed. 

```
ECMDERR Failed to execute "git checkout 1663341d5d67c225b6953ee7d3ebc5d5682
3fa4b", exit code of #128 fatal: reference is not a tree: 1663341d5d67c225b6953ee7d3ebc5d56823fa4b
```

**Describe the results you expected:**
bower to install angular material, commit 166334...

**Additional information:**
I can successfully install by tracking a branch, say `master`, but don't want to track a moving target. It looks like lots of people can install specific commits fine. http://stackoverflow.com/questions/18639488/bower-git-package-with-a-commit-id

found some other people with [same issue ](http://stackoverflow.com/questions/16949173/how-to-install-latest-untagged-state-of-a-repo-using-bower)back in 2014 on SO, but no solutions

**Comment by 1mike12** [comment]
Was actually caused by somehow having a messed up bower.json. May have been manually entered in as 

``` json
angular-material: "1663341d5d67c225b6953ee7d3ebc5d56823fa4b"
```

Then installing via command line wouldn't overwrite what was written in bower.json. Is that normal behavior?

**Comment by BenMann** [comment]
@1mike12 Persisting to the `bower.json` is only done when you run `install` with [--save](https://bower.io/docs/api/). You okay with closing this issue? 🎊

**Comment by 1mike12** [comment]
I actually still have a problem installing the example given by trying to do `angular-material#1663341d5d67c225b6953ee7d3ebc5d56823fa4b` . Could anyone else repro this?

**Comment by sophieH29** [comment]
+1 get the same issue

**Comment by BenMann** [comment]
@1mike12 This might be because `angular-material` uses a [special repo](https://github.com/angular/bower-material) for distributing via package managers. 
If you try to use the registered package then 
(`bower install angular-material#1663341d5d67c225b6953ee7d3ebc5d56823fa4b`) it fails but it will work with the original git repo: 
`bower install https://github.com/angular/material.git#1663341d5d67c225b6953ee7d3ebc5d56823fa4b`. 

Can you confirm that?

**Comment by sheerun** [comment]
This commit is not present in their distribution repository:
https://github.com/angular/bower-material/commit/1663341d5d67c225b6953ee7d3ebc5d56823fa4b
