### ISSUE TITLE
bower not working without sudo and --allow-root

### ISSUE THREAD

**Issue by monala** [bower/bower#2338]
every time i want to download with bower 
i must use **sudo bower install --allow-root** in mac 
how i can get rid of sudo and --allow-root?

**Comment by BenMann** [comment]
This seems like a pure permissions issue, nothing we can *fix*.
I would recommend asking this on [SO](https://stackoverflow.com) if this is still an issue for you. Also have you seen this(?): http://stackoverflow.com/questions/21616785/bower-installation-errors
🍬
