### ISSUE TITLE
Fail on unsuitable resolutions

### ISSUE THREAD

**Issue by ChristopherBrix** [bower/bower#2339]
I'm currently setting up a CI server. Part of the build consists of installing all bower packages with `bower install --config.interactive=false`.

Unfortunately, this causes bower to ignore unsuitable resolutions - it only prints `bower resolution            Unsuitable resolution declared for [...]` to the console, where this message will never be found.

Instead, I'd like to set a flag that bower should abort (causing the build to fail) when the resolution can not be applied.

**Comment by sheerun** [comment]
Duplicate of #1362
