### ISSUE TITLE
"os" key (blacklist/whitelist) as part of bower.json

### ISSUE THREAD

**Issue by Happy-Ferret** [bower/bower#2340]
As far as I'm aware, there is currently no way to blacklist or whitelist a specific operating system/platform the same way this can be done with npm's "os".

Being the author of a couple of modules that only work on GNU/Linux, I'd like to make this issue a feature request asking for the addition of such an option.

Ideally, bower should refuse to install any OS specific packages on a system that doesn't match the `process.platform` string defined in bower.json.

**Comment by evanjbowling** [comment]
Hi @Happy-Ferret, it's an interesting idea. Here's my thoughts:

Npm does support an ["os"](https://docs.npmjs.com/files/package.json#os) property and even a ["cpu"](https://docs.npmjs.com/files/package.json#cpu) property. While bower doesn't place a hard requirement on the types of components published/registered, most components are designed for the browser. That being said, a "browser" property might be more appropriate. However, I have to say I'm opposed to either. I'd rather the components be published in a cross-browser format.

Can you point me to any of your example projects if they are public?

**Comment by sheerun** [comment]
bower is mainly for front-end packages and they should be os-independent. Browser-independence is done with shims, so it's the same deal.
