### ISSUE TITLE
Unable to install from git URL, getting ENOTFOUND error

### ISSUE THREAD

**Issue by rohan-deshpande** [bower/bower#2341]
So yeah I was trying to install this repo I made just so I could get this code in via bower as it's currently only hosted on npm, the react-router folks don't have a bower.json file and I am working on an app that is currently still in ES5 land. 

Anyway, I created this repo and couldn't install it by just having `"react-router-umd": "https://github.com/rohan-deshpande/react-router-umd.git#master"` in my app's `bower.json` file.

It would resolve, but then tell me the package was not found. I had to register the package with bower to get it to work. Is this expected behaviour? I was under the impression that you could install from a git repo url without the package being registered, indeed this is how I have done it at companies where gitlab was in use for private repositories.

**Output of `bower -v && npm -v && node -v`:**

```
1.7.9
1.4.23
v0.10.31
```

**Describe the results you received:**

```
bower install react-router-umd
bower not-cached    https://github.com/rohan-deshpande/react-router-umd.git#master
bower resolve       https://github.com/rohan-deshpande/react-router-umd.git#master
bower checkout      react-router-umd#master
bower resolved      https://github.com/rohan-deshpande/react-router-umd.git#e3fd880626
bower ENOTFOUND     Package react-router-umd not found
```

**Describe the results you expected:**

That the package would be found and installed.

**Comment by echavezNS** [comment]
When I run ` bower install react-router-umd ` it installed that package.

**Comment by rohan-deshpande** [comment]
Yes, I had to register it to get it to work. I was under the impression that this should work even if the package has not been registered with bower.

**Comment by BenMann** [comment]
@rohan-deshpande without registering the package you would need to install it this way:
`bower install https://github.com/rohan-deshpande/react-router-umd.git#master`.
Otherwise registering is the way to go 👯 

Good to close? :)

**Comment by rohan-deshpande** [comment]
Well umm that doesn't really fix the issue because that's exactly what I had above, except that it was in my bower.json instead of directly calling install. I don't see how that should make a difference though?

**Comment by BenMann** [comment]
Sorry, read the issue half-assed. What you want to do in your `bower.json` is give it a name just like you did.. That's expected to work indeed and does work for me.
```
  "dependencies": {
    "test": "https://github.com/rohan-deshpande/react-router-umd.git#master"
  }
```

**Comment by rohan-deshpande** [comment]
Yeah, it will work now because I registered it, but it wasn't working before and that was why I made the issue. Anyway if you want to close go ahead. Was pretty weird though.

**Comment by evanjbowling** [comment]
Hey @rohan-deshpande, thanks for the report.

I just tried reproducing this with my own github bower project "bower-test". This is a trivial project that has not been published. I was able to successfully install it from the command line.

### Test 1 - Passed

    bower install -S https://github.com/evanjbowling/bower-test.git#master

__Output:__

    bower install -S https://github.com/evanjbowling/bower-test.git#master
    bower not-cached    https://github.com/evanjbowling/bower-test.git#master
    bower resolve       https://github.com/evanjbowling/bower-test.git#master
    bower checkout      bower-test#master
    bower resolved      https://github.com/evanjbowling/bower-test.git#30707fdfe0
    bower install       bower-test#30707fdfe0

So that didn't seem to be the problem. The `bower.json` created was:

    {
      "name": "test-1",
      "homepage": "",
      "authors": [
        "Evan Bowling <evan.j.bowling@gmail.com>"
      ],
      "description": "",
      "main": "",
      "license": "MIT",
      "ignore": [
        "**/.*",
        "node_modules",
        "bower_components",
        "test",
        "tests"
      ],
      "dependencies": {
        "bower-test": "https://github.com/evanjbowling/bower-test.git#master"
      }
    }


### Test 2 - Failed

I then deleted my "bower_components" directory and ran:

    bower install bower-test

__Output:__

    bower install bower-test
    bower not-cached    https://github.com/evanjbowling/bower-test.git#master
    bower resolve       https://github.com/evanjbowling/bower-test.git#master
    bower checkout      bower-test#master
    bower not-cached    https://github.com/EvandroLG/bower-test.git#*
    bower resolve       https://github.com/EvandroLG/bower-test.git#*
    bower resolved      https://github.com/evanjbowling/bower-test.git#30707fdfe0
    bower ECMDERR       Failed to execute "git ls-remote --tags --heads https://github.com/EvandroLG/bower-test.git", exit code of #128 remote: Repository not found. fatal: repository 'https://github.com/EvandroLG/bower-test.git/' not found

    Additional error details:
    remote: Repository not found.
    fatal: repository 'https://github.com/EvandroLG/bower-test.git/' not found

This was unexpected. Notice how it changed my username in the URL to "EvandroLG". I don't have a good answer for that yet.

### Test 3 - Passed

After this, I tried one more install:

    bower install

__Output:__

    bower install
    bower not-cached    https://github.com/evanjbowling/bower-test.git#master
    bower resolve       https://github.com/evanjbowling/bower-test.git#master
    bower checkout      bower-test#master
    bower resolved      https://github.com/evanjbowling/bower-test.git#30707fdfe0
    bower install       bower-test#30707fdfe0

    bower-test#30707fdfe0 bower_components/bower-test

This suggests to me that if you had just run `bower install` before, then it would have worked. But I'm still confused about "Test Case 2"...

**Comment by sheerun** [comment]
this seems to work with bower.json @eventualbuddha 

the `bower install bower-test` doesn't work because bower registry points to `/github.com/EvandroLG/bower-test` and that doesn't exist indeed
