### ISSUE TITLE
Give cache bypass its own config setting

### ISSUE THREAD

**Issue by ghost** [bower/bower#2343]
**Output of `bower -v && npm -v && node -v`:**

```
1.7.9
3.6.0
v5.6.0
```

**Additional environment details (proxy, private registry, etc.):**
Using a private registry.

**Steps to reproduce the issue:**
1. Add dependencies to bower.json that will have version conflicts
2. Run `bower install --force` to install packages and bypass the cache 

**Describe the results you received:**
Bower automatically chooses a resolution to the conflict, and one of the conflicting choices is downloaded.  The `install --force` documentation does not mention this.

**Describe the results you expected:**
I expect the install to fail with a version conflict.

**Additional information:**
The documentation for `install --force` appears to be the only option for bypassing the cache, and does not mention automatic resolution.  What I would like is an option in the config to always bypass the cache without needing to use the `--force` option.  I would also like to see the conflict resolution results mentioned in the `install --force` documentation.

Running `bower cache clean` before installation might be an option, but since I am running simultaneous builds in a continuous integration environment, I'm afraid of creating a race condition when one build cleans the cache another build is using.

**Comment by sheerun** [comment]
This behavior won't be changed as bower is in maintenance mode
