### ISSUE TITLE
when will `bower update --save` work?

### ISSUE THREAD

**Issue by jaichandra** [bower/bower#2348]
I see that this is reverted in v1.7.1. When are we getting this back?

**Comment by mtpultz** [comment]
There's a lot of movement to move back to npm - https://gofore.com/stop-using-bower/.  Without small things like this to help improve workflow and prevent wasted time this is a momentum that won't subside.  On some of our projects we've already started this process, and frameworks like Ionic 2 have already implemented the change back to npm and documented it as best practice.

**Comment by sheerun** [comment]
update never worked well and bower is now deprecated
