### ISSUE TITLE
Uninstall package via URL

### ISSUE THREAD

**Issue by bluemoehre** [bower/bower#2352]
My first time with Bower installing a package from my own repo, I was confused the `uninstall` does not work using the repo URL. Since I am sure it is easy to implement crawling the installed packages to look for the repo URL and run the existing uninstall logic when the package was found, I would like this as a little feature request. This should improve the UX a little bit.

**What happened:**

```
bower install --save git://my.git/user/repo.git
> package#version vendor/bower/package

bower uninstall git://my.git/user/repo.git
> bower not-installed 'git://my.git/user/repo.git'
```

What I expected:

```
bower install --save git://my.git/user/repo.git
> package#version vendor/bower/package

bower uninstall git://my.git/user/repo.git
> bower uninstall 'package'
```

**Comment by MoezGholami** [comment]
Can anyone close this issue?
It has been resolved in [https://github.com/bower/bower/pull/2368](https://github.com/bower/bower/pull/2368) and it has been merged with master.
