### ISSUE TITLE
Sorry, there was an error while fetching repositories

### ISSUE THREAD

**Issue by chrismbeckett** [bower/bower#2353]
I recently (over a week ago) published a new bower package [oxygen-language](https://gitlab.com/arsnebula/oxygen-language). The package is published, and it can be installed:

```
bower install --save oxygen-language
```
Before publishing I checked whether the name was available and there were other packages that were returned with the *oxygen* prefix. After publishing my package, when attempting to search for *oxygen* on the Bower website it returns:

``Sorry, there was an error while fetching repositories``

I think something about the package I published is breaking the search functionality.

**Comment by BenMann** [comment]
Thanks for the issue. I'm also seeing this.. however the request is returning valid JSON (see below). Maybe something with rendering the data onto the page. This also happens for queries like `"xyz"`
or just `"ox"`...
```
[  
   {  
      "name":"oxygen-googlefont",
      "platform":"Bower",
      "description":null,
      "homepage":null,
      "repository_url":"https://github.com/google-fonts-bower/oxygen-bower",
      "normalized_licenses":[  

      ],
      "rank":0,
      "latest_release_published_at":"2016-04-17T08:52:14.983Z",
      "latest_release_number":null,
      "language":"HTML",
      "status":null,
      "package_manager_url":null,
      "stars":0,
      "forks":0,
      "keywords":[  

      ],
      "versions":[  

      ]
   },
   {  
      "name":"oxygenmono-googlefont",
      "platform":"Bower",
      "description":null,
      "homepage":null,
      "repository_url":"https://github.com/google-fonts-bower/oxygenmono-bower",
      "normalized_licenses":[  

      ],
      "rank":0,
      "latest_release_published_at":"2016-04-17T08:52:15.036Z",
      "latest_release_number":null,
      "language":"HTML",
      "status":null,
      "package_manager_url":null,
      "stars":0,
      "forks":0,
      "keywords":[  

      ],
      "versions":[  

      ]
   },
   {  
      "name":"oxygen-language",
      "platform":"Bower",
      "description":null,
      "homepage":null,
      "repository_url":null,
      "normalized_licenses":[  

      ],
      "rank":0,
      "latest_release_published_at":"2016-08-29T06:03:23.526Z",
      "latest_release_number":null,
      "language":null,
      "status":null,
      "package_manager_url":null,
      "stars":0,
      "forks":0,
      "keywords":[  

      ],
      "versions":[  

      ]
   }
]
```

**Comment by chrismbeckett** [comment]
Why is the repository for oxygen-language set to *null*? Isn't the repository_url required? This might explain why the error is related to "fetching repositories"?

**Comment by BenMann** [comment]
Yeah that seems wrong indeed. Didn't have the time to take a closer look earlier and I'm at work now, however I'll dig deeper as soon as I have some time.

cc: @andrew : Just mentioning you cause the returned `null` **might** also come from the query/db, I guess?

**Comment by andrew** [comment]
Thanks for the ping @BenMann, I didn't notice that Bower now allows non-github repositories, have fixed the null `repository_url` on ~300 bower projects including `oxygen-language` and handle it better for any new ones in future too.

**Comment by BenMann** [comment]
@andrew Thanks for the awesomely quick fix ❤️ 
Issue solved :-)

**Comment by chrismbeckett** [comment]
Thank you - great job :)
