### ISSUE TITLE
bower should allow root under CI

### ISSUE THREAD

**Issue by cedk** [bower/bower#2354]
The option "--allow-root" should be activated by default if it is run under CI environment.
Many CI runs the tests under a sandbox (docker image) environment as root.

**Comment by wookoouk** [comment]
I disagree, if bower fails to build the first time (it will say 'use --allow root'), add '--allow-root' and push... fixed.

**Comment by cedk** [comment]
But this means that we must have a different script to build in CI than the one used by users. And this is bad because user build script will not be tested.
Or that we must force users to also run with the '--allow-root' option. And this goes against the idea of this option.

**Comment by wookoouk** [comment]
good point, I personally put `bower install` in my readme but `bower install --allow-root` in my 'pre build' script.

**Comment by wookoouk** [comment]
Side note, Dont tell users to run the commands you use for CI, my CI build script also generates documentation coverage, test coverage, etc and posts them to external services... this would fail if users tried it. test building, ci building and deploy building are all different.

**Comment by vanilla-thunder** [comment]
in my opinion, its none of bower's business if i run commands as root or any other user.
It is just a package manager and it should do what package managers are supposed to do instead of bothering users with lifestyle advices

**Comment by wookoouk** [comment]
Hi @vanilla-thunder, you may not care about server security but giving the publicly accessible files in your web-root root access is a security issue and its important that users be notified of that.

**Comment by wookoouk** [comment]
@cedk I believe you can put `"allow_root": true` in your .bowerrc file to allow as default. (http://stackoverflow.com/questions/25672924/run-bower-from-root-user-its-possible-how)
