### ISSUE TITLE
Possible to recover abandoned package?

### ISSUE THREAD

**Issue by andrewplummer** [bower/bower#2359]
Hello. I'm the maintainer of [Sugar](https://sugarjs.com/), which was recently updated. Part of the upgrade was modularization of the library, and as part of publishing the modularized packages, I've contacted the owners of 2 packages whose names were already taken, `sugar-string` and [sugar-date](https://github.com/bower-packages/bower-sugarjs-date). The owner of `sugar-string` got back to me promptly and gave me publish permissions, however the owner of `sugar-date` appears to be AWOL, and never got back to me.

I was wondering, is there any way to take over an abandoned package?

**Comment by sheerun** [comment]
@andrewplummer Please e-mail me when you're online at sheerun@sher.pl, so I'll unregister this package and you can re-register it immediately.
