### ISSUE TITLE
Enforcing 2-factor authentication

### ISSUE THREAD

**Issue by riyadhalnur** [bower/bower#2362]
GitHub announced new security measures along with a plethora of other [features](https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features) yesterday. What will be helpful will be start enforcing 2-factor authentication for all members organisation-wide.

**Comment by wookoouk** [comment]
https://github.com/nodeschool/organizers/issues/377

**Comment by riyadhalnur** [comment]
@wookoouk That author would be me over there as well

**Comment by wookoouk** [comment]
If this is made mandatory we will enforce it but for now this is not required.
