### ISSUE TITLE
Tests should not fail on Windows by default

### ISSUE THREAD

**Issue by cezarykluczynski** [bower/bower#2364]
README says:

> Note that on Windows for tests to pass you need to configure Git before cloning:
> 
> git config --global core.autocrlf input

It seems unnecessary. Tests should be rewritten to work on Windows out of the box. Would you accept a pull request that fixes this?

**Comment by sheerun** [comment]
It's harder to implement than you might think. also, when you install bower on windows, you don't get crlf line ends, as npm packages and extracts source without changes.

It's better option is just to configure git on windows to clone original line endings
