### ISSUE TITLE
No versions available (but my GitLab repo does have proper semver tags)

### ISSUE THREAD

**Issue by chrismbeckett** [bower/bower#2365]
I just published a new package to Bower named **oxygen-state**. The repo has been tagged with proper semver tags, but when I do a **bower info oxygen-state** I get a "No versions available.". If I try to install with **bower install oxygen-state** it uses "*" for the version and none of my files are downloaded into the components folder.

If I install using the repo URL, it works and detects the latest tagged version correctly.

Here is the repo tags: https://gitlab.com/arsnebula/oxygen-state/tags

**Comment by sheerun** [comment]
It's registered under wrong url, the correct one being: "https://gitlab.com/arsnebula/oxygen-state.git". I've unregistered it for you so you can re-registe.r
