### ISSUE TITLE
`bower list` does't suggest the latest revision for jQuery-UI

### ISSUE THREAD

**Issue by TonyaSolaris** [bower/bower#2366]
A new revision of `jQuery-UI` came out recently:
https://jqueryui.com/changelog/1.12.1/
Our application is currently on the previous revision `1.12.0.1`.
When I run `bower list` the output doesn't offer a new revision:

```
$ bower list
bower check-new     Checking for new versions of the project dependencies...
├─┬ bootstrap#3.3.7 (latest is 4.0.0-alpha.4)
│ └── jquery#3.1.0
├─┬ flot#0.8.3
│ └── jquery#3.1.0
├─┬ fullcalendar#3.0.0
│ ├── jquery#3.1.0
│ └── moment#2.15.1
├── jquery#3.1.0
├─┬ jquery-ui#1.12.0.1
│ └── jquery#3.1.0
├─┬ jquery.scrollTo#2.1.2
│ └── jquery#3.1.0
├─┬ jquery.tablesorter#2.27.6
│ └── jquery#3.1.0
├── jqueryui-timepicker-addon#1.6.3
├── kbwood_countdown#2.0.1 (latest is 2.0.2)
├── moment#2.15.1
└── tinymce#4.4.3
```

Our `bower.json`:

```
{
    "name": "ourapp",
    "dependencies": {
        "bootstrap": "3.3.7",
        "flot": "0.8.3",
        "fullcalendar": "3.0.0",
        "jquery": "3.1.0",
        "jquery-ui": "1.12.0.1",
        "jquery.scrollTo": "2.1.2",
        "jquery.tablesorter": "2.27.6",
        "jqueryui-timepicker-addon": "1.6.3",
        "kbwood_countdown": "2.0.1",
        "moment": "2.15.1",
        "tinymce": "4.4.3"
    }
}
```

**Output of `bower -v && npm -v && node -v`:**

```
1.7.9
1.4.28
v0.10.37
```

**Steps to reproduce the issue:**
1. Install JQuery-UI 1.12.0.1 revision
2. Run `bower list` command
3. The result doesn't suggest to update jQuery-UI with the latest 1.12.1 revision -> unexpected

Thank you!

**Comment by sheerun** [comment]
I can confirm. Maybe you'd like to try to fix it?

**Comment by PatrickWalker** [comment]
So 1.12.0.1 is not an official version of jquery-ui it seems.

If you set that to 1.12.0 you will be prompted to upgrade to 1.12.1.

The list.js mentions that it doesn't check for bad semver version on targets. Would this be the desired approach going forward for both lists/installs? Would you want an error shown the user? If so any preference on the content?

**Comment by TonyaSolaris** [comment]
Thank you for looking into it and explaining the cause! So, it doesn't look like a bug.
I think a warning would be nice, but since you explained the cause and the version we used was not in the list of the released versions, I think it would be OK too if you don't add it.
Thank you!

**Comment by TonyaSolaris** [comment]
I am going to close this issue.
