### ISSUE TITLE
How register single component, being a part of complete product?

### ISSUE THREAD

**Issue by jwaliszko** [bower/bower#2367]
I have a project which finally consists of 3 components (2 DLLs and a script).
Each product release contains these 3 components, separately versioned, e.g.

```
product - v2.9.1
    * DLL 1 - v2.7.0
    * DLL 2 - v2.5.1
    * script.js - v2.6.8
```

I've been [requested to create a bower package](https://github.com/jwaliszko/ExpressiveAnnotations/issues/124) with the javascript component.

After reading [registration section](https://bower.io/docs/creating-packages/#register) on bower site, I see that I need a release tag, to which package version corresponds. The current tag informs about the whole product version, i.e. 2.9.1. How can I register bower package in a proper way, when script component version is different, mainly 2.6.8? Any recommended way, other than separate repository for bower-dedicated releases?

Thank you for any support.

**Comment by sheerun** [comment]
Separate repository is currently the only solution, as Bower depends on proper tags for versioning

So no support for monorepos, sorry. Maybe adding npm resolver to bower could help.
