### ISSUE TITLE
Shallow clone is not used for git ssh url's

### ISSUE THREAD

**Issue by betalb** [bower/bower#2372]
**Output of `bower -v && npm -v && node -v`:**

```
1.7.9
3.10.3
v6.7.0
```

**Additional environment details (proxy, private registry, etc.):**
no additional details

**Steps to reproduce the issue:**

Note that I've added additional log statement in [GitRemoteResolver](https://github.com/bower/bower/blob/d405917b4a6efdeeb24a2087680fd4163896ab8e/lib/core/resolvers/GitRemoteResolver.js#L126) to print arguments that were passed to git executable

```
that._logger.info("git", "Running git with argumens: ["+ args +"] and cwd '"+ that._tempDir +"'");
```
1. Configure `bitbucket.org` as host that supports shallow clone `{ "shallowCloneHosts": [ "bitbucket.org" ] }`
2. Add bower dependency using raw git over ssh url, like this `git@bitbucket.org:atlassian/atlassian-connect-js.git#master`
3. Inspect log statement

**Describe the results you received:**

Log statement shows that `--depth=1` argument was not added

**Describe the results you expected:**

Shallow clone should be used, as I've explicitly added this into configuration and `ssh` protocol was used

**Additional information:**
Changing url to `ssh://git@bitbucket.org/atlassian/atlassian-connect-js.git#master` solves the issue, as now `url.parse` can identify ssh as protocol

**Comment by sheerun** [comment]
Can you write failing test for it?

**Comment by betalb** [comment]
@sheerun Sorry for delay, here is failing test, should I create PR?

https://github.com/betalb/bower/commit/4d5d391bf9466a17c09242773d2d7a69b5c6afbd

**Comment by sheerun** [comment]
@betalb Isn't the correct ssh url `ssh://git@bitbucket.org:atlassian/atlassian-connect-js.git#master` (you need double colon after the domain). Otherwise bower recognizes whole path as domain. Could you update test and verify it's still failing?
