### ISSUE TITLE
Feature Request: Get a report with all dependencies versions and licenses (for a legal purpose)

### ISSUE THREAD

**Issue by F2X** [bower/bower#2375]
Hi,
I have to check with the legal department to check if there is not contaminating licenses in dependencies, e.g. a dependency with a GPL license which make automatically my project under the same GPL obligations.
So I'm looking for a tool/plugin to do it automatically, but I think it will be usefull if it can be done natively from the bower cli.

**Comment by sheerun** [comment]
This is something 3rd party module could do. Like https://www.npmjs.com/package/bower-license
