### ISSUE TITLE
How do I update the git-endpoint?

### ISSUE THREAD

**Issue by moses-seeq** [bower/bower#2378]
I registered a bower package to my fork prior to the original package owner accepting my pull request and now want to update the git-endpoint to the original package. I was forbidden to unregister so that I could register it anew. Does anyone know how I can update the git-endpoint for a given bower package?

Thanks in advance.

**Comment by benmann** [comment]
If you tell me the package name I can unregister it, so you can re-register it with the correct URL.

**Comment by moses-seeq** [comment]
angular-highlight-partial-words

Thanks!

**Comment by benmann** [comment]
@moses-seeq Done. All yours! Thanks for using Bower 🍬

**Comment by moses-seeq** [comment]
Thanks!  When will I be able to register the new end point?  It's telling me duplicate package now and I still see it pointing to my fork.

**Comment by benmann** [comment]
Hmm sorry I think something went wrong during unregistering.. I'm getting a
`FORBIDDEN Must have push access to view repository collaborators.` error atm.

Maybe cause I switched my GH name to all lowercase recently? @sheerun 
Actually tried `bower login` with the old spelling as well, with which didn't work either.

**Comment by moses-seeq** [comment]
Can you reopen this until it's resolved?  Is there anything I can do to help move toward a solution?

**Comment by benmann** [comment]
Nah, just needs some time now :)

**Comment by moses-seeq** [comment]
Ok, thanks!

**Comment by sheerun** [comment]
@moses-seeq I've unregistered it, you can register it again under different url

**Comment by moses-seeq** [comment]
Thank you!
