### ISSUE TITLE
bower install eperm when using --save

### ISSUE THREAD

**Issue by SajidQ** [bower/bower#2382]
I keep getting the following error when I use **bower install <package>** with "**--save**" option. This is the exact command: **bower install amitava82-angular-multiselect --save**. My bower.json file is shown below. I looked at similar questions and have tried solutions like re-installing bower, re-installing npm, and clearing bower and npm cache. I am using Window Command Prompt as an admin. 

This seems to download and install the files from the git repository but not save to the bower.json file. Also, if I add the git repository as a dependency to bower.json and run bower install it does not do anything. 

I know I've used --save before on this file and it had worked. 

**ERROR**
bower invalid-meta  The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower cached        https://github.com/amitava82/angular-multiselect.git#1.2.0
bower validate      1.2.0 against https://github.com/amitava82/angular-multiselect.git#*
_bower EPERM         EPERM: operation not permitted, open 'C:\Users<user>\Documents\BVA\BVDashboard\bower.json'_

Stack trace:
Error: EPERM: operation not permitted, open 'C:\Users<user>\Documents\BVA\BVDashboard\bower.json'
    at Error (native)

Console trace:
Error
    at StandardRenderer.error (c:\Users<user>\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:81:37)
    at Logger.<anonymous> (c:\Users<user>\AppData\Roaming\npm\node_modules\bower\lib\bin\bower.js:110:26)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (c:\Users<user>\AppData\Roaming\npm\node_modules\bower\lib\node_modules\bower-logger\lib\Logger.js:29:39)
    at c:\Users<user>\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (c:\Users<user>\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:844:24)
    at c:\Users<user>\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:870:30
    at Promise.when (c:\Users<user>\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (c:\Users<user>\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:788:41)
System info:
Bower version: 1.7.9
Node version: 4.6.1
OS: Windows_NT 6.1.7601 x64

**bower.json file:**
{
  "name": "projectName",
  "authors": [
    "Bob Smith bob.smith@bob.com"
  ],
  "description": "Build Validation Web Dashboard",
  "main": "",
  "moduleType": [],
  "license": "company",
  "homepage": "",
  "private": true,
  "ignore": [
    "*_/._",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "bootstrap": "~3.3.7",
    "angular": "~1.5.8",
    "angular-route": "~1.5.8",
    "Flot": "flot#~0.8.3",
    "font-awesome": "~4.6.3",
    "jquery": "~3.1.0",
    "morris.js": "morrisjs#~0.5.1",
    "metisMenu": "~2.5.2",
    "amstock3": "^3.20.13",
    "amcharts3": "^3.20.13",
    "underscore": "~1.8.3",
    "abdmob/x2js": "git://github.com/abdmob/x2js.git#^1.2.0"
  },
  "resolutions": {
    "jquery": "~3.1.0"
  }
}

**Comment by sheerun** [comment]
It's impossible for us to reproduce this issue, and there can be multiple reasons.

Please make sure that terminal from where you run bower is able to write to bower.json as well. We cannot help here otherwise
