### ISSUE TITLE
Registering a repo with HTTPS without adding .git extension points to HTML page

### ISSUE THREAD

**Issue by koreyconway** [bower/bower#2383]
When registering a package I used https and no .git extension which caused the bower package to install the HTML page instead of the repo. This is should at the very least be documented and provide a warning. Personally I'd like to see the default be a nice error message telling the user to put ".git" or to use the "force" flag if they really wanted to set the HTML page. This is especially a problem for people who don't use GitHub for the repo and cannot fix it without creating an issue for it (as is my case).

Note: I did not test using "git" as the protocol but I'm assuming it does not have the same problem

**Comment by tenaciousRas** [comment]
Are you sure this is a bug?  The resolver tests at https://github.com/bower/bower/tree/d405917b4a6efdeeb24a2087680fd4163896ab8e/test/core/resolvers may be of interest to you.  It sounds like urlresolver may be getting used in your case and working as expected.  Maybe you can adjust your usage to match that test, or that might be a good place to consider adding features you requested.

**Comment by sheerun** [comment]
@koreyconway What's the package name and url you used?

**Comment by koreyconway** [comment]
@sheerun Yes I am sure. As I explained, at the very least a warning should be given since it might be the correct behaviour but not the expected one. To achieve this behaviour a --force flag should be added, otherwise are warning message should be displayed and not action performed by the bower registry.

This is obviously a significant issue since the registry repo is full of people who are waiting for fixes to their bower pointers (including me who has been waiting for 18 days and counting to get my registry working with still no response).

**Comment by kevin-lot** [comment]
Same problem here.

A package using https has to finish with .git.
Without it, bower download index file with content of main page.

**Comment by sheerun** [comment]
Registering is not supported anymore
