### ISSUE TITLE
bower tilde and/or caret are not working as expected

### ISSUE THREAD

**Issue by uella** [bower/bower#2385]
Hi All, 

My bower.json looks like this: 

`

> {
>   "name": "asp.net",
>   "private": true,
>   "dependencies": {
>     "angular": "~1.5.8",
>     "es5-shim": "",
>     "angular-resource": "*",
>     "angular-cookies": "~1.5.8",
>     "angular-sanitize": "~1.5.8",
>     "angular-animate": "~1.5.8",
>     "angular-touch": "~1.5.8",
>     "angular-route": "~1.5.8",
>     "font-awesome": "4.6.3",
>     "angular-bootstrap": "2.1.3",
>     "oclazyload": "1.0.9",
>     "angular-loading-bar": "0.9.0",
>     "angular-ui-router": "0.3.1",
>     "angular-toggle-switch": "1.3.0",
>     "jquery": "3.1.0",
>     "bootstrap": "3.3.7",
>     "angular-ui-grid": "3.2.1",
>     "lodash": "~4.16.4",
>     "angular-timeline": "1.7.0",
>     "textAngular": "1.5.7",
>     "angular-bootstrap-show-errors": "2.3.0",
>     "angular-strap": "2.3.9",
>     "angular-bootstrap-nav-tree": "",
>     "angular-flash-alert": "2.3.0",
>     "angular-selectize2": "3.0.1",
>     "selectize": "0.12.3",  
>     "angular-filter": "0.5.11",
>     "checklist-model": "0.10.0",
>     "angular-chart.js": "1.0.3",
>     "chart.js": "2.3.0"
>   },
>   "devDependencies": {
>     "angular-mocks": "",
>     "angular-scenario": ""
>   },
>   "resolutions": {
>     "angular": "~1.5.8"
>   }
> }

`

and I got AngularJS v1.6.0-rc.0 in my bower_components. What am I doing wrong? 

Thank you.

**Comment by sheerun** [comment]
resolutions are ignored if versions of dependencies don't produce conflicts
