### ISSUE TITLE
Bower update is not working 

### ISSUE THREAD

**Issue by Kanimozhi12** [bower/bower#2386]
Hi,
Bower version :1.7.9

The issue is reported in below thread is reproduced with my machine.

https://github.com/bower/bower/issues/1054 .

Any how i will repeat the issue details

Steps to reproduce:

Create a new folder on the desktop.
Open terminal and cd to your new folder.
Run this command: bower install jquery#2.2.0
Run bower list and verify that jQuery 2.2.0 is installed.
Run bower update jquery
Run bower list and find that jQuery 2.2.0 is still installed and that Bower reports 3.1.1 as the latest available version.
Expected Results:

After running bower update, jQuery 2.2.0 should be replaced with jQuery 3.1.1.

Actual Results:

jQuery is not updated to the latest version available.

Note: This is not only with jQuery it is with all other packages that is installed

**Comment by sheerun** [comment]
bower update doesn't update package.json by design, and `bower update --save` is currently broken: #256
