### ISSUE TITLE
bower username/password post attributes in request when i register

### ISSUE THREAD

**Issue by publicocean0** [bower/bower#2390]
Hi i saw there is a missing part in bower. 
I use a bower registry that permits to pass username/password for registering a new module.

The problem is that bower can't permit to pass username/password as post rest request but just in query string. It is not good because users need to save the query string with clear password in their .bowerrc. 

It would be a good emprovement if you add the possibility to post username/password.

**Comment by dvidsilva** [comment]
There's no authentication in bower register, what guide are you using? 

Look at the official document https://bower.io/docs/creating-packages/  or look at this one which is longer http://bob.yexley.net/creating-and-maintaining-your-own-bower-package/

**Comment by publicocean0** [comment]
i suggest you to be a bit more respectful about people writing you. Bower is a simple software ... there are people writing software 1000 times more complex and anyway listen what other want tell.

**Comment by dvidsilva** [comment]
Oh, how is that disrespectful? If I misunderstood your question you can expand on it.

From re reading, you're saying that you're using a private registry? and this private registry supports authentication? and you want to pass the username and password on the body of the request and not the query string?

> Bower is a simple software ... 

Not super encouraging to help you. But if other people believe this is an issue I can submit a PR.

**Comment by publicocean0** [comment]
i think you already proved your bad analitical skills with your previous actions. Every action has a meaning for a person having good analitical qualities. bye bye
