### ISSUE TITLE
Cannot read property 'getWindowSize' of null

### ISSUE THREAD

**Issue by mymbrooks** [bower/bower#2394]
**Output of `bower -v && npm -v && node -v`:**

```
1.8.0
3.10.9
v7.1.0
```

**Additional environment details (proxy, private registry, etc.):**

Win10 14393 x64 with node windows installer

**Steps to reproduce the issue:**

1.bower init
2.
3.

**Describe the results you received:**
                                                         tty.js:76
  var err = this._handle.getWindowSize(winSize);
                        ^

TypeError: Cannot read property 'getWindowSize' of null
    at WriteStream._refreshSize (tty.js:76:25)
    at process.on (internal/process/stdio.js:16:43)
    at emitNone (events.js:91:20)
    at process.emit (events.js:185:7)
    at Signal.wrap.onsignal (internal/process.js:200:44)

**Describe the results you expected:**
in node 6.x bower init works well.

**Additional information:**

**Comment by shakuu** [comment]
Same setup,  same issue occurs when resizing powershell. 
Also Bower init does not complete successfully or unsuccessfully.

Steps to reproduce the issue:
1.bower init in powershell
2.command does not complete
3.resize window

updating to node 7.2.0 seems to have fixed the issue.

**Comment by mischah** [comment]
That was a regression in node 7.1.0 on windows.
See https://github.com/nodejs/node/issues/9542

**Comment by wookoouk** [comment]
Any windows users that can test this please.
