### ISSUE TITLE
should svn endpoint with explicit revision really add /trunk to svn path?

### ISSUE THREAD

**Issue by mkropf** [bower/bower#2396]
**Output of `bower -v && npm -v && node -v`:**

```
1.8.0
3.7.5
v4.3.0
```

**Steps to reproduce the issue:**

1. bower info svn+https://[svnrepo]/[somepath]#r[revnum]

**Describe the results you received:**
ECMDERR Failed to execute "svn export [...] https://[svnrepo][somepath]/trunk -r[revnum]

**Describe the results you expected:**

Because svn support appends /trunk it is not possible to get a module out of a svn repo with modules bundled by project:

    [project1]
      trunk/
        module1/
        module2/

**Additional information:**

**Comment by Polarisation** [comment]
Bower worked like this for some time, so I doubt that could be changed now as it would break builds.

However this seems like a fairly common scenario, so I just added a workaround to the alternative SVN resolver I wrote a few months ago: https://github.com/Polarisation/svn-resolver

After installing that you should be able to do:
`bower info svn+https://[svnrepo]/[somepath]#r[revnum]-no-trunk` and it will not append /trunk as usual. I haven't tested it thoroughly, feel free to log issues if you find any.

**Comment by sheerun** [comment]
This behavior won't be changed but you can use pluggable resolver to implement it differently https://bower.io/docs/pluggable-resolvers/
