### ISSUE TITLE
What happened to the bower-config repo?

### ISSUE THREAD

**Issue by justinfagnani** [bower/bower#2397]
I'm trying to write code that read bower.json files, and looking at the Bower CLI code I see that it uses bower-config, apparently from here: https://www.npmjs.com/package/bower-config

But there's no repository by that name. Google search results say there should be as well. Was the repository deleted? Has the code moved somewhere else?

**Comment by justinfagnani** [comment]
It looks like `bower-json` is the package that the CLI uses to read `bower.json` files, but it's repo is deleted too. What's it mean that Bower depends on npm packages that have been removed from Github?

**Comment by sheerun** [comment]
They are in the main repo

**Comment by thinkxl** [comment]
Closing this since the original question got answered.
