### ISSUE TITLE
Changed repo name, how do I update Bower?

### ISSUE THREAD

**Issue by will-stone** [bower/bower#2398]
`https://github.com/eggboxio/quick-select.git`
is now
`https://github.com/will-stone/quick-select.git`

I've updated the bower.json file but I still see the old url when running `cache clean` then `info quick-select`.

**Comment by thinkxl** [comment]
You need to `bower unregister <package>` old name and then `bower register <name> <url>` it with the new name.

Closing as this is a support question. Next time please ask any support related question in:

https://github.com/bower/bower#support
