### ISSUE TITLE
scrollMonitor hijacked with malicious code!

### ISSUE THREAD

**Issue by stutrek** [bower/bower#2399]
Months ago I switched from sakabako to stutrek, github's redirect worked for a long time but has now been hijacked and contains malicious code. Please update the repository to stutrek/scrollMonitor from sakabako/scrollMonitor.

stutrek/scrollMonitor/issues/54

**Comment by sheerun** [comment]
it seems already done ?

**Comment by sheerun** [comment]
ok, done. please notice it means clients need to run "bower cache clean" to get new url

**Comment by stutrek** [comment]
Thank you!
