### ISSUE TITLE
Support multiple components per one repo

### ISSUE THREAD

**Issue by IgorMinar** [bower/bower#24]
For AngularJS we keep all of our build artifacts for all versions in a single repo: https://github.com/angular/code.angularjs.org

Each of our releases contains several modules / build artifacts, so there is quite a few files in there. It would be great if I could reuse this repo for bower. I really don't want to create 8+ repos and have a continuous maintenance overhead to keep everything up to date with every release.

**Comment by rprieto** [comment]
Hi, is that a final rejection, or are you still open to discussing it as Bower evolves over time (as you mentioned above)?

I fully agree with @petebacondarwin (Mar 3, 2013) that in many systems (`npm`, `ruby gems`...) repositories and components are different things. One is a development concern (how many repos do I want to check-out, how do I want to solve re-use, how easily do I want to grep across packages) and the other is a build/deployment capability (how do things get published, versioned and retrieved).

If you have a large number of components, a private repo for each sometimes feels like overkill. A single repo doesn't exclude the idea of multiple components the evolve separately, only that their version/publish step becomes separate from the single-line-history of the repo itself - either a different system altogether (registry) or an auxiliary mapping of some sort (like another file in the repo).

**Comment by sheerun** [comment]
@rprieto Bower versioning is based on git tags. It's impossible to version two components in the same repository. Also, nothing stops you to publish multiple components under common bower manifest :)

**Comment by rprieto** [comment]
Fair enough thanks - I thought this question was what the issue was about, but :+1: it can't be done because of core design decisions in Bower. I'll look into bower manifests some more.

**Comment by shellscape** [comment]
quoting @sheerun 
`Bower versioning is based on git tags. It's impossible to version two components in the same repository.`

I'd disagree with that sentiment. We're exploring bower as an alternative to npm for our front-end asset management. We have several modules per repo, which are categorized based on need. Regardless of the merits (or lack thereof) of the setup, we have roughly ~150 modules that are categorized within a half dozen repos. We tag in the respective git repo as such for each module publish: `common.thing-0.0.1`. It would appear trivial then, to look for `[module-name].[version]` rather than simply `[version]` for repos with multiple modules.

**Comment by JohannesHoppe** [comment]
For internal use a custom bower resolver could be used. That bower resolver might work on directory level and might use special combined tags (e.g. “directoryx_0.1.2”).

**Comment by shellscape** [comment]
@JohannesHoppe any urls/references you might be able to point us to?

**Comment by JohannesHoppe** [comment]
Writing a pluggable bower resolver is pretty easy and well documented. I will try this out for TFS soon.


----- Ursprüngliche Nachricht -----
Von: "Andrew Powell" <notifications@github.com>
Gesendet: ‎04.‎11.‎2015 15:58
An: "bower/bower" <bower@noreply.github.com>
Cc: "Johannes Hoppe" <johannes.hoppe@haushoppe-its.de>
Betreff: Re: [bower] Support multiple components per one repo (#24)

@JohannesHoppe any urls/references you might be able to point us to?

**Comment by publicocean0** [comment]
They are ight , bower is too much simple. 
If you write a complex javascript module , you want separate it in different submodules to reuse in other projects or you want embedd in the browser just the necessary submodules.  It is necessary to introduce a way for handling sub components

**Comment by jakub-g** [comment]
I'm late to the party, but we've had exactly this requirement (multiple packages in one git repo), and we solved it by publishing our bower packages to our private npm registry and forking [bower-npm-resolver](https://github.com/mjeanroy/bower-npm-resolver) to match it to our needs.

With this setup npm takes care of all the package management stuff, and bower is able to do wildcard resolving (i.e. locator like `1.2.x` in `bower.json`) based on existing npm releases.
Initially we were just putting a zip on our server and using URL resolver of bower, but this one supports only `*` target which is obviously not good for a setup where you have multiple branches (3.x, 4.x...) in parallel in your project and want to have sane dependency management.

Pluggable resolvers are documented here
http://bower.io/docs/pluggable-resolvers/

@JohannesHoppe thanks for your input which pointed me in a good direction

**Comment by publicocean0** [comment]
It seams a trick not a architectural solution.  
i have a project named A and inside A i have submodules A.a, A.b, A.c , and A.d depending by A.b.
In a webproject i want use A with A.a and A.d because A.c is a additional feature not required. 
For my option this can be solved just introducing a more complex bower.json.
