### ISSUE TITLE
bower uninstall --remove should remove dependencies from component.json?

### ISSUE THREAD

**Issue by codylindley** [bower/bower#240]
I might be missing why this is not possible, but shouldn't there be a flag --remove since we can have a flag that --save's? When I uninstall, I want it to update component.json as well.

**Comment by fricks** [comment]
@sheerun thank you :)

**Comment by mpathy** [comment]
$ bower install jplayer
..works, but..
$ bower uninstall jplayer -S 
bower not-installed 'jplayer' cannot be uninstalled as it is not currently installed
..doesnt, while..
$ bower uninstall jPlayer -S
bower uninstall jPlayer
..works, its like its written, so it makes sense..
..but the installation should also only work **case-sensitive**, dont you think?

**Comment by sanchezcarlos1986** [comment]
**Delete** de dependencies from your **bower.json** file, then run `bower prune,` and the dependencies will be deleted from **bower_components**.

**Comment by HorchataHTML** [comment]
### Easy solution
Delete the dependency including only and exclusively the **name of the dependency**.
 
**That's OK**  `> bower uninstall bootstrap --save` 👍 

**This is wrong** `> bower uninstall bootstrap#v4.0.0-beta --save` 👎 

This will delete the folder and the dependency.
