### ISSUE TITLE
Improve bower error reporting on 401 - Unauthorized

### ISSUE THREAD

**Issue by TheHalcyonSavant** [bower/bower#2401]
We're using nexus private bower registry, and we've noticed that the bower client isn't producing the error we're hoping for. The debug info must be understood clearly. Otherwise, it's difficult to know where the problem resides - the client configurations, or the server.

Steps to reproduce the issue:
1. [ Install private bower for nexus](https://books.sonatype.com/nexus-book/3.0/reference/bower.html)
3. Include all registry specs in .bowerrc, but avoid including "nexus" object.
3. Run `bower register example-package svn+https://svn.example.com/example-package --loglevel=debug`

After step 3, you should see the following output:
```
bower example-package#*   resolve svn+https://svn.example.com/example-package#*
bower example-package#*   export v0.1.0
bower example-package#*   resolved https://svn.example.com/example-package#0.1.0
bower example-package     register svn+https://svn.example.com/example-package
bower                     EUNKNOWN Unknown error: 401 - undefined
...
```

Tracing the network with Wireshark will produce the following results:
```
POST /repository/bower-internal/packages HTTP/1.1
User-Agent: node/v6.9.1 linux x64
...
content-type: application/x-www-form-urlencoded
accept: application/json
content-length: 103
Connection: close

name=example-package&url=svn%2Bhttps%3A%2F%2Fsvn.example.com%2Fexample-packageHTTP/1.1 401 Unauthorized
Date: Wed, 07 Dec 2016 06:39:18 GMT
Server: Nexus/3.1.0-04 (OSS)
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
WWW-Authenticate: BASIC realm="Sonatype Nexus Repository Manager"
Connection: close
```

Instead, we believe the bower log should end with:
```
EUNKNOWN Unknown error: 401 - Unauthorized
```

Additional notes: _I understand that this issue should be reported in the bower-registry-client repository, just its github link is unavailable at the moment._

**Comment by dpalic** [comment]
I had very similar issues in the past with bower.
The major problem in our case was, that bower is not showing the failure URL. E.g. it should be something like:

`EUNKNOWN Unknown error: 401 - Unauthorized at https://<yourServerURL>/repository/bower-internal/packages`

additionally to this the result of the http body/payload of the server response shall also be traced in level debug. So all informations would be available to track down the problem with the access. This would have reduced hours of analysis to track down, that the issue in **NOT** related to SVN like the last URL in the bower report on the console is reporting

**Comment by sheerun** [comment]
Feature like this one won't be implemented as Bower is deprecated now
