### ISSUE TITLE
Document ignore changes in 1.8.0

### ISSUE THREAD

**Issue by typeoneerror** [bower/bower#2402]
**Output of `bower -v && npm -v && node -v`:**

```
1.8.0
3.10.9
v6.9.2
```

**Additional environment details (proxy, private registry, etc.):**

None

**Steps to reproduce the issue:**

1. Install https://github.com/iamceege/tooltipster with bower 1.7.9
2. Install https://github.com/iamceege/tooltipster with bower 1.8.0
3. Note that with 1.8.0 that "doc" "index.html" and "src" and "demo" are missing.

**Describe the results you received:**

Installed using bower's default ignores.

**Describe the results you expected:**

Don't do any ignores since "ignore" is not specified in their bower.json. That or document this change in the changelog (I couldn't find anything about this change so perhaps I was looking in the wrong place). Seems like not using the [default ignores has been the default for some time](http://stackoverflow.com/a/22598185/53653), unless I was mistaken. 

**Additional information:**

Happy to submit documentation PR update if I am correct about this!

**Comment by sheerun** [comment]
I've added default ignores in https://github.com/bower/spec
