### ISSUE TITLE
ECONFLICT Unable to find suitable version for angular  |  It worked fine on mac but on ubuntu server recently started giving me error. 

### ISSUE THREAD

**Issue by jpca999** [bower/bower#2403]
{
  "name": "meanjs",
  "description": "Fullstack JavaScript with MongoDB, Express, AngularJS, and Node.js.",
  "homepage": "http://meanjs.org/",
  "license": "MIT",
  "dependencies": {
    "angular": "~1.5.0",
    "angular-animate": "~1.5.0",
    "angular-bootstrap": "~1.2.1",
    "angular-messages": "~1.5.0",
    "angular-mocks": "~1.5.0",
    "angular-resource": "~1.5.0",
    "angular-ui-notification": "~0.2.0",
    "angular-ui-router": "~0.2.18",
    "bootstrap": "~3.3.6",
    "ng-file-upload": "^12.1.0",
    "ng-img-crop": "ngImgCrop#^0.3.2",
    "owasp-password-strength-test": "~1.3.0",
    "underscore": "^1.8.3",
    "angular-material": "^1.1.1",
    "angular-material-data-table": "^0.10.9",
    "material-design-icons": "^3.0.1",
    "angular-moment": "^1.0.0",
    "angular-aria": "^1.5.8"
  },
  "overrides": {
    "bootstrap": {
      "main": [
        "dist/css/bootstrap.css",
        "dist/css/bootstrap-theme.css",
        "less/bootstrap.less"
      ]
    },
    "jquery": {
      "main": []
    }
  }
}

**Comment by john2x** [comment]
Experiencing the same. Our builds are running fine on our local machines (macOS), but on CircleCI (Ubuntu 14.04) it's failing with the same error message.

**Comment by jpca999** [comment]
It's breaking on ubuntu 16.06

**Comment by idan666** [comment]
Same here....

**Comment by daB0bby** [comment]
Do you have a `.bowerrc` with `"json": "bower.json"` defined?

Removing that solved the issue for me.

**Comment by jpca999** [comment]
no its just .bowerrc.    What do you mean   " .bowerrc with "json": "bower.json" defined? "

**Comment by daB0bby** [comment]
@jpca999 if you have `"json": "bower.json"` in your `.bowerrc` than remove it.

**Comment by jpca999** [comment]
i dont think so . here it is    https://github.com/meanjs/mean/blob/master/.bowerrc

**Comment by thinkxl** [comment]
Could you give more info, npm version, bower version, node version, also take a look at https://github.com/bower/bower/wiki/Report-a-Bug and modify the issue accordingly, please.

**Comment by jpca999** [comment]
i no longer use bower/ npm.   pls use Yarn


thank you,

**Comment by thinkxl** [comment]
Thanks for the heads up!

**Comment by idan666** [comment]
angular-material bower package installation fails with ECONFLICT.
If you remove angular-material, the installation works fine.

The solution is to explicitly specify "angular-aria": "~1.5.0", 
same as the angular version (1.5.0) in the bower.json file.
moreover, adding 
"resolutions": {
   "angular": "~1.5.0"
 }
allows for the version to be met in case of fail.
node: 6.9.1
npm: 3.10.8
bower: 1.7.9
