### ISSUE TITLE
The root command warning should be disabled on bash for ubuntu on Windows

### ISSUE THREAD

**Issue by jarrodek** [bower/bower#2406]
When using Bash on Ubuntu on Windows introduced in latest Service Pack for Windows 10 the default user is the root. I'm not even sure if changing the user in this shell is possible.

Each time I want to use the bower in this shell I have to add `--allow-root` option or I'll see error message. I think this error message should be skipped the using Bash on Windows.

**Comment by kupuguy** [comment]
Not true. When you first run Bash for Windows it prompts for a username and if necessary creates an account. That account may be changed at any time by running (from windows command prompt, not from bash):

    lxrun /setdefaultuser someusername

I would suggest that at some point somebody must have run:

   lxrun /setdefaultuser root

as that will make root the default user, or whoever first ran bash on this system entered 'root' as the username.

**Comment by vanilla-thunder** [comment]
in my opinion, its none of bower's business if i run commands as root or any other user.
It is just a package manager and it should do what package managers are supposed to do instead of bothering users with lifestyle advices

**Comment by yellowiscool** [comment]
Yes, I had to modify build scripts because bower refuses to work as root when building a docker container.

I think it should be a warning, not a breaking error.
