### ISSUE TITLE
Transfering bower name from fork to original repo

### ISSUE THREAD

**Issue by Draccoz** [bower/bower#2407]
Hi there. Is it possible to transfer bower repo (name) to different GitHub (from fork to original) without breaking peoples builds? More details here: https://github.com/Microsoft/tslib/issues/15.
Cheers,
Dracco

**Comment by dvidsilva** [comment]
Have you tried unregister and then register again?, it was temporatily disabled but it should  be back there. Otherwise @sheerun will have to change the db.

**Comment by Draccoz** [comment]
Great to hear `unregister` is back! As for doing so, would it be safe for projects that already use the package? It appears it breaks the bower if use has previous package in cache already, no idea though it that would also be an issue with transferring (if possible). Any suggestions?

**Comment by dvidsilva** [comment]
cached code will remain  cached, but when downloading new versions it should just work, that will be no different to the current way it would work. Just be careful with version numbers too. If it's a fork it should work out of the box.

To unregister you should be loged in with collaborator credentials.

**Comment by Draccoz** [comment]
Awesome! We should proceed with the transfer then. Thank you and wish us luck ^^.

**Comment by dvidsilva** [comment]
Let us know how it goes!

https://bower.io/docs/api/#login

**Comment by Draccoz** [comment]
Transfer is done and everything works :). Thanks for all the info ;).
