### ISSUE TITLE
Remove Packages

### ISSUE THREAD

**Issue by chrismbeckett** [bower/bower#2410]
I have a number of broken registrations on Bower Search. I don't believe anyone is using these packages, and the registrations when you click on them don't take you to the repo correctly anyway. I would like to ask that these registrations be removed.

oxygen-language: https://gitlab.com/arsnebula/oxygen-language.git
oxygen-log-behavior: https://gitlab.com/arsnebula/oxygen-log-behavior.git
oxygen-state: https://gitlab.com/arsnebula/oxygen-state.git

I think the registration problems were related to trying to register them on GitLab instead of GitHub. In future I am just going to mirror them to GitHub so they can be installed easily without Bower registration. I intend to republish these again once I have cleaned them up.

**Comment by sheerun** [comment]
Maybe it's better to just leave them? Someone can hijack these names and provide malicious package instead..

**Comment by chrismbeckett** [comment]
Is it possible to hide them so they don't appear in the search? Otherwise, I guess that's fine.

**Comment by sheerun** [comment]
Our search is hosted by https://libraries.io/ I think currently it's not possible but you might open an issue there to support such feature.
