### ISSUE TITLE
.cache .config and .local/bower location configuratble

### ISSUE THREAD

**Issue by akostadinov** [bower/bower#2412]
Presently bower creates a number of directories (see $subject) without an option to configure their PATH. As a user I would like to be able to change all of these paths using a command line options. This would allow me easier overview of bower used space and let me manage it better.

Also bower should not crash when root of user home dir is non-writable.

**Comment by sheerun** [comment]
it is: https://github.com/bower/spec/blob/master/config.md

**Comment by akostadinov** [comment]
In source `.cache` and `.config` (the directory) appear to be hard-coded. Am I missing something?

**Comment by sheerun** [comment]
Bower config can be in multiple locations:

1. CLI arguments via `--config`
2. Environment variables
3. Environment variables with [`config`](https://docs.npmjs.com/files/package.json#config) key of package.json
4. Local .bowerrc located in the current working directory
5. All .bowerrc files upwards the directory tree
6. `.bowerrc` file located in user’s home folder (~)
7. `.bowerrc` file located in the global folder (/)
