### ISSUE TITLE
bower update <package> dont work

### ISSUE THREAD

**Issue by publicocean0** [bower/bower#2419]
there are case in which it dont work correctly

package is A
my case: 
A version 1.0.0 in git and bower pointing at git repo directly
in git i remove 1.0.0 tag  change code and then i add again
i go to a project using A as dependency

i executed bower update A

the code remains the old code. 

I tried also removing cache. same problem.

For solving the problem i removed it
with bower uninstall A
and bower install A

now code is correct

**Comment by Trost123** [comment]
I think you have a wrong idea about "[bower update](https://bower.io/docs/api/#update)".
When you run this command, it only updates your modules if there's a newer version available.

In your example you install 1.0.0, modify it check for updates, but the newest version is still 1.0.0, so no files are changed on your machine, unless you reinstall the package.

**Comment by thinkxl** [comment]
yes, that's the expected behavior AFAIK, even though there are some issues with `bower update`. @publicocean0 it works as you expect with `bower --force update`
