### ISSUE TITLE
On "update", bower re-downloads git repository even if there are no changes

### ISSUE THREAD

**Issue by stevevanhooser** [bower/bower#2420]
Hello -

I'm not sure if this is user error or a bug, but whenever I install a package that refers to a git repo, and then run bower update, the package is downloaded again even if there is no new version. I have been unable to uncover anything on the web by searching.

Example:

bower install vhlab_mltbx_toolbox

bower update vhlab_mltbx_toolbox

(bower appears to re-download and re-install, even though there have been no changes to the repo.)

# BUG REPORT

**Output of `bower -v && npm -v && node -v`:**

```
1.8.0
3.10.10
v6.9.4

```

**Additional environment details (proxy, private registry, etc.):**

**Steps to reproduce the issue:**

1.bower install vhlab_mltbx_toolbox
2.bower update vhlab_mltbx_toolbox

**Describe the results you received:**

Upon running update, Bower reinstalls the git repo

**Describe the results you expected:**

I expected that Bower would examine the repo and report "up-to-date" or "no action needed" or something similar:

bash-3.2$ bower install vhlab_mltbx_toolbox
bower not-cached    https://github.com/VH-Lab/vhlab_mltbx_toolbox.git#*
bower resolve       https://github.com/VH-Lab/vhlab_mltbx_toolbox.git#*
bower download      https://github.com/VH-Lab/vhlab_mltbx_toolbox/archive/master.tar.gz
bower extract       vhlab_mltbx_toolbox#* archive.tar.gz
bower resolved      https://github.com/VH-Lab/vhlab_mltbx_toolbox.git#a208203249
bower install       vhlab_mltbx_toolbox#a208203249

vhlab_mltbx_toolbox#a208203249 bower_components/vhlab_mltbx_toolbox
bash-3.2$ bower update vhlab_mltbx_toolbox
bower not-cached    https://github.com/VH-Lab/vhlab_mltbx_toolbox.git#*
bower resolve       https://github.com/VH-Lab/vhlab_mltbx_toolbox.git#*
bower download      https://github.com/VH-Lab/vhlab_mltbx_toolbox/archive/master.tar.gz
bower extract       vhlab_mltbx_toolbox#* archive.tar.gz
bower resolved      https://github.com/VH-Lab/vhlab_mltbx_toolbox.git#a208203249

**Additional information:**

**Comment by thinkxl** [comment]
related to https://github.com/bower/bower/issues/256

**Comment by sheerun** [comment]
Closing for the same reason as #256
