### ISSUE TITLE
Bower version does not work when 'bower.json' is not in the same folder as '.git'

### ISSUE THREAD

**Issue by lwblackledge** [bower/bower#2423]
**Output of `bower -v && npm -v && node -v`:**

```
1.8.0
3.3.4
v5.6.0
```

**Additional environment details (proxy, private registry, etc.):**

Windows 7 / Powershell

**Steps to reproduce the issue:**

1. Create a new git repo
2. Add subfolders e.g. server, client
3. Run `> bower init` in the new `client` folder
4. Add some files and `git commit`
5. `cd client && npm version patch`

**Describe the results you received:**
I received the following error message:
```
[{
  "code": "ENOTGITREPOSITORY",
  "id": "ENOTGITREPOSITORY",
  "level": "error",
  "data": {},
  "message": "Version bump currently supports only git repositories",
  "stacktrace": "Error: Version bump currently supports only git repositories
```

**Additional:**

I would also suggest adding an option to skip the `git` check as I have a projects with several version tags (NPM, C#, Bower, LESS) and I want to run a script to update them all at once, so I do not want bower arbitrarily creating commits/tags in the middle of this process. Maybe `--no-git` or similar.

Thanks!

**Comment by sheerun** [comment]
This issue seems to confuse npm with bower
