### ISSUE TITLE
Bower info (verbose) is missing some pre-release beta versions.

### ISSUE THREAD

**Issue by Trost123** [bower/bower#2425]
> npm info bourbon

Returns all versions, up to the latest 5.0.0-beta.7 (correct behavior)
> bower info bourbon --verbose

Returns versions up to 4.2.7, including all old betas, but ignores all 5.0.0 beta.

Is this a bug or an expected behavior?
I want to use ^5.0.0-beta of that package, but Bower doesn't see any 5.0 versions. NPM does.
_(although Bower does allow to install 5.0.0-beta by tag with "bower install bourbon#v5.0.0.beta.7", but this makes "bower update" ineffective for the package)_
[Bower screenshot](http://prntscr.com/e0png0)

**Comment by Trost123** [comment]
I've further investigated on the issue and it looks like Bower is unable to recognize tags like this: "v5.0.0**.**beta.7", because it expects "v5.0.0**-**beta.7", while [NPM has no trouble parsing such tags](http://prnt.sc/e0s7rk).

**Comment by thinkxl** [comment]
I think bower should be able to recognize tags like that, unless @sheerun says otherwise. Will wait on mark it as bug until we get more feedback.

**Comment by sheerun** [comment]
Bower only recognizes proper semver tags
