### ISSUE TITLE
Invisible warnings from bower-json package 

### ISSUE THREAD

**Issue by Mottie** [bower/bower#2426]
The [bower-json package](https://github.com/bower/bower/tree/master/packages/bower-json) will only alert you if there are errors in your `bower.json` file.

Using the code from [the readme](https://github.com/bower/bower/tree/master/packages/bower-json#readme), to either `read` or `parse` the json file, neither method will display any warning messages.

For example, if my `bower.json` file was completely valid except that I linked the `"main"` entry to a minimized file...

```js
{
  "name": "my-library",
  "main": "lib/index.min.js",
  "ignore": [
    "/node_modules",
    "/bower_components"
  ]
}
```

No error, or warning would be shown.

[Within the `validate` function](https://github.com/bower/bower/blob/master/packages/bower-json/lib/json.js#L214), an error is thrown only if there are `issue.errors`. Nothing is done with the `issue.warnings` values.

It might be easiest to have the `validate` function display any warnings in the console.

----

Additionally, I didn't think I needed to open another issue for these...

* The `validate` portion of the readme is malformed and the `validate` entry itself is included in the code block of the deprecated [`.getIssues(json)` entry](https://github.com/bower/bower/tree/master/packages/bower-json#getissuesjson---deprecated).
* The npm module page - https://www.npmjs.com/package/bower-json - links to https://github.com/bower/json - which doesn't exist.

**Comment by sheerun** [comment]
This issue got invalid because Bower is deprecated and we don't encourage creating new Bower packages anymore
