### ISSUE TITLE
Fix with cache, because must be no case sensitive

### ISSUE THREAD

**Issue by froucher** [bower/bower#2429]
**Output of `bower -v && npm -v && node -v`:**

1.8.0
3.8.6
v5.12.0

**Additional environment details (proxy, private registry, etc.):**

none.

**Steps to reproduce the issue:**

1. mkdir test && cd test
2. bower cache clean
3. bower install PolymerElements/iron-flex-layout#^1.0.0 --production
4. bower install polymerelements/iron-flex-layout#^1.0.0 --offline --production

```
bower iron-flex-layout#^1.0.0   cached https://github.com/polymerelements/iron-flex-layout.git#1.3.1
https://github.com/Polymer/polymer.git f7f075fb0e2eb0ce17a7ed61f88773a8
bower polymer#^1.1.0          ENOCACHE No cached version for https://github.com/Polymer/polymer.git#^1.1.0
```

**Describe the results you received:**

Two dependencies like “https://github.com/PolymerElements/iron-flex-layout.git” must be equal to “https://github.com/polymerelements/iron-flex-layout.git”

But in the cache is treated as differents folders:

~/.cache/bower/packages/444ea84ad1b11545629269bdc8d5330e/
~/.cache/bower/packages/9170ac518f979438268666845fc8f0fb/

$ md5 -s https://github.com/PolymerElements/iron-flex-layout.git
MD5 ("https://github.com/PolymerElements/iron-flex-layout.git") = 444ea84ad1b11545629269bdc8d5330e

$ md5 -s https://github.com/polymerelements/iron-flex-layout.git
MD5 ("https://github.com/polymerelements/iron-flex-layout.git") = 9170ac518f979438268666845fc8f0fb

It must be no case sensitive

**Describe the results you expected:**

Just one folder in the cache

~/.cache/bower/packages/9170ac518f979438268666845fc8f0fb/

With the lowercase:

$ md5 -s https://github.com/polymerelements/iron-flex-layout.git
MD5 ("https://github.com/polymerelements/iron-flex-layout.git") = 9170ac518f979438268666845fc8f0fb

**Additional information:**

Pull Request #2428 with changes...

**Comment by thinkxl** [comment]
I was able to reproduce this. Thanks for the PR, I added some comments to it.

**Comment by thinkxl** [comment]
Closing this. As mentioned in the PR, current behavior is expected. Thanks for the effort.
