### ISSUE TITLE
Bower Downloads All Deps

### ISSUE THREAD

**Issue by kmccullough** [bower/bower#2430]
**Output of `bower -v && npm -v && node -v`:**

```
1.7.9
2.11.3
v0.12.7
```

**Steps to reproduce the issue:**

1. Include `angular-ui-router#1.0.0-alpha.0` and `angular#1.5.8`
2. Add resolutions entry for `angular#1.5.8`
3. Run `bower install`

**Describe the results you received:**

Based on the dependency in `angular-ui-router` of `angular>=1.3`, bower still downloads both 1.5.8 and 1.3.  Though 1.5.8 is eventually resolved as the correct version for use after download, it seems I shouldn't have to download multiple additional version of angular, just for them to be thrown out.

**Describe the results you expected:**

Older versions specified in a way which also matches new version (e.g. >=1.3), should not result in multiple versions downloading.

**Additional information:**

Adding overrides for each package that requires angular as a dependency to clear those dependencies works, but I shouldn't have to do this. Does bower really need to download the entire repo to determine it won't resolve to using it? I would expect the resolutions entry to prevent the download.

**Comment by sheerun** [comment]
This issue got stale, Bower is not deprecated and we suggest migrating to yarn with bower-away
