### ISSUE TITLE
Register Doesn't Use Stored Git Credentials

### ISSUE THREAD

**Issue by andrew-boutin** [bower/bower#2432]
`bower register` doesn't use [`git-credentials`](https://git-scm.com/docs/git-credential-store) for GIT HTTPS credentials. I can successfully use the GIT credential store to store my GIT credentials so that I don't have to keep entering my credentials when using GIT. However, `bower register` doesn't use those stored credentials forcing me to enter them once again through the interactive prompt.

**Output of `bower -v && npm -v && node -v`:**

```
bower -v
1.8.0
npm -v
3.10.10
node -v
v7.2.1
```

**Additional environment details (proxy, private registry, etc.):**
Running in Docker container based from `node:7.2.1-alpine`.

**Steps to reproduce the issue:**
1. Run `bower register <package_name> <GIT_HTTPS_URL>`.
2. Observe being prompted for username + password as expected.
3. Run `git config credential.helper store`.
4. Add a GIT remote with an HTTPS GIT URL.
5. Run `git fetch remote`.
6. Enter credentials when prompted as expected.
7. Run `git fetch remote`.
8. Observe that credentials weren't required since they were put in the GIT credential store.
9. Run `bower register <package_name> <GIT_HTTPS_URL>`.
10. Observe that bower still prompts for the GIT credentials.

**Describe the results you received:**
`bower register` prompted me for GIT HTTPS credentials (username & password) even though I used `git-credential-store` to store my GIT credentials.

**Describe the results you expected:**
I expected `bower register` to use my GIT HTTPS credentials stored with `git-credential-store`.

**Additional information:**
None

**Comment by thinkxl** [comment]
Hey @andrew-boutin, I think `bower login` might help with this, have you tried that?

**Comment by andrew-boutin** [comment]
I have investigated `bower login` (see my other issue: https://github.com/bower/bower/issues/2431). Since `bower login` doesn't handle input pipes yet that doesn't help me out. Could you see if you can reproduce in a clean environment? This may be another instance of some additional functionality that could be useful.

**Comment by sheerun** [comment]
Bower doesn't allow registering new packages anymore
