### ISSUE TITLE
Consider adding nodegit support.

### ISSUE THREAD

**Issue by nicolasnoble** [bower/bower#2434]
My main issue with bower at the moment is its dependency on the system's git. In all fairness, this has the advantage of being able to use private repositories and credentials. But the drawback is that bower can't be used for installing packages dynamically on an end user system.

More specifically, what I have in mind is using bower in an extension system, vscode-style. The only thing preventing me from going down that route is the system git requirement.

Fortunately, there is a npm package that supports libgit2: https://www.npmjs.com/package/nodegit

Using this as a fallback to the git command line would help drastically.

**Comment by thinkxl** [comment]
> But the drawback is that bower can't be used for installing packages dynamically on an end user system.
Bower is a development tool, you should ship only the packages installed with it. 

This use case is very specific for your needs and I don't think it would be high priority on the project right now.

I will let it open to discussion, though.

**Comment by nicolasnoble** [comment]
I agree, it's kind of specific, but at the same time, I see a variety of Electron projects popping up right now, or even Atom or VSCode right now, and they have to reinvent the wheel every time to create their extension system. Why not using something very simple, that allows for self hosting of the specific packages, with the ability to grab the sub-dependencies anywhere they are ? Or in other words, why should self-hosted extension packages have to contain the full list of dependencies, duplicated over and over ?

My point being, right now, the git dependency is the only thing really separating bower from being used by developers to being used under the hood by applications in end-user's computers.

**Comment by nicolasnoble** [comment]
Also I shall specify that I am ready to put my money where my mouth is and submit a pull request to add this, if desired :)

**Comment by thinkxl** [comment]
i would like to hear more opinions about it cc @sheerun @wookoouk

**Comment by sheerun** [comment]
Because of Bower's popularity every change in bower seems to be a breaking change. Because of it we don't want to modify resolvers for 1.x version and nobody is committed for releasing 2.x

Don't worry though, you can implement it as Pluggable Resolver:
https://bower.io/docs/pluggable-resolvers/

**Comment by thinkxl** [comment]
I think @sheerun's comment resolves this issue. cc @nicolasnoble
