### ISSUE TITLE
Need Timestamp for bower components installation log

### ISSUE THREAD

**Issue by suriyanath** [bower/bower#2435]
If we do bower install something it prints the details as below,
bower angular-route#^1.5.0 not-cached art://angular/bower-angular-route#^1.5.0
bower angular-route#^1.5.0 resolve art://angular/bower-angular-route#^1.5.0
bower angular-sanitize#^1.5.0 not-cached art://angular/bower-angular-sanitize#^1.5.0
bower angular-sanitize#^1.5.0 resolve art://angular/bower-angular-sanitize#^1.5.0
bower angular-touch#^1.5.0 not-cached art://angular/bower-angular-touch#^1.5.0
bower angular-touch#^1.5.0 resolve art://angular/bower-angular-touch#^1.5.0
bower angular-cookies#~1.5.0 not-cached art://angular/bower-angular-cookies#~1.5.0
bower angular-cookies#~1.5.0 resolve art://angular/bower-angular-cookies#~1.5.0
bower angularjs-imageupload-directive#* not-cached art://Mischi/angularjs-imageupload-directive#*
bower angularjs-imageupload-directive#* resolve art://Mischi/angularjs-imageupload-directive#*

What I expect is the time taken to install each bower component, typically like below,
Mar  1 07:24:56  bower angular-route#^1.5.0 not-cached art://angular/bower-angular-route#^1.5.0
Mar  1 07:24:58  bower angular-route#^1.5.0 resolve art://angular/bower-angular-route#^1.5.0

This will be really helpful in finding the timeout needed for each component in case of problem with network.

**Comment by wookoouk** [comment]
Time stamps are also not given with --verbose, how does everyone else feel about this being added?

**Comment by chriswoodle** [comment]
I can take a look into implementing it.

**Comment by wookoouk** [comment]
Need to get approval that this can be added.

##Note
npm does not give a time stamp (with or without `--verbose`

**Comment by thinkxl** [comment]
I think it could be useful.

**Comment by thinkxl** [comment]
I don't think we will be adding new features, so I think we can close this? cc @wookoouk @sheerun

**Comment by sheerun** [comment]
Yes we don't implement new features
