### ISSUE TITLE
bower version resolution strategy leads to version conflict

### ISSUE THREAD

**Issue by skyboyer** [bower/bower#2436]
**Output of `bower -v && npm -v && node -v`:**
```
1.8.0
3.10.10
6.9.5
```

**Steps to reproduce the issue:**
I use quite short component config:
```javascript
{
  "name": "test",
  "dependencies": {
	"angular": "1.5.3",
	"angular-translate-storage-cookie": "^2.11.0"
  }
}
```
angular-translate-storage-cookie has next dependencies config:
```javascript
  "dependencies": {
    "angular-translate": "~2.15.1",
    "angular-cookies": ">=1.2.26 <1.7"
  }
```
angular-cookies explicitly depends on angular of the same version
So my app depends on single version of dependency A(angular#1.5.3) and other dependency is flexible with version used but depends on the same version of dependency A.

**Describe the results you received:**
For angular-cookies latest version(1.6.4) is chosen. It depends on angular#1.6.4 so this creates conflict(explicit dependency angular#1.5.3 and implicit dependency angular#1.6.4). Both resolutions are inacceptable(either application is broken or angular-cookies is broken)

**Describe the results you expected:**
I expect that version for angular-cookies is chosen such way there is no version conflict(angular-cookies#1.5.3 -> angular#1.5.3)

**Additional information:**
There is workaround with listing explicitly all dependencies of 2nd level and deeper(with acceptable versions set) if they create such kind of conflicts. In case above we should add `"angular-cookies": "1.5.3"` to make everything work.

Currently it cannot be done in `resolutions` section(see https://github.com/bower/bower/issues/1362) so all that should be placed into `dependencies` section. This decreases maintainability of application(say it prevents us from removing redundant dependencies).

**Comment by skyboyer** [comment]
I understand why such strategy is used so I don't expect it will be fixed in nearest future :(
Rather I'd like to highlight a gap for version resolution that occurs "in the wild"

**Comment by sheerun** [comment]
Bower is not developed anymore and resolution strategy is not something we can change without breaking 100 things
