### ISSUE TITLE
bower.commands.init does not generate bower.json file

### ISSUE THREAD

**Issue by vpusher** [bower/bower#2437]
**Output of `bower -v && npm -v && node -v`:**

```
1.8.0
3.8.9
v6.2.0
```

**Additional environment details (proxy, private registry, etc.):**

macOS 10.11.5

**Steps to reproduce the issue:**

Here is my NPM package definition:

```
{
  "name": "bower-init",
  "version": "0.0.1",
  "description": "bower-init",
  "scripts": {
    "bower-init": "bin/bower-init.js"
  },
  "dependencies": {
    "bower": "^1.8.0",
    "inquirer": "^3.0.6",
    "shelljs": "^0.7.7"
  },
  "bin": {
    "bower-init": "bin/bower-init.js",
  }
}
```

I have the following node script `bin/bower-init.js`:

```
 #! /usr/bin/env node
 var inquirer =  require('inquirer');
 var bower =  require('bower');
 bower.commands
        .init({interactive: true})
        .on('prompt', function (prompts, callback) {
            inquirer.prompt(prompts, callback);
        })
        .on('end', function(){
            console.log('ended');
        })
```

The script is ran with NPM: `npm run bower-init`.

> Then, answer to the several prompts.

**Describe the results you received:**

No `bower.json` file is generated and the `console.log('ended');`is never reached.

**Describe the results you expected:**

It should have generated the `bower.json` file and log "ended".

**Comment by wookoouk** [comment]
Can confirm I get the same result.

I also included an 'error'** event on my test make sure it was not hitting an error and not getting to 'end' but it did not fire.


**
```
.on('error', function(){
        console.log('error');
})
```

**Comment by vpusher** [comment]
Ok, **Inquirer** changed from callback style prototypes to Promises. Using Promise instead make it work:

```
 .on('prompt', function (prompts, callback) {
    inquirer.prompt(prompts).then(callback);
})
```

The documentation needs a tiny update in the sample: [programmatic-api](/bower/bower.github.io/blob/master/docs/api.md#programmatic-api)

**Comment by sheerun** [comment]
I see it's fixed now, thanks!
