### ISSUE TITLE
Is there a compelling reason to keep package name length to 50 characters or less? 

### ISSUE THREAD

**Issue by jcollum** [bower/bower#2440]
https://github.com/bower/bower/blob/d405917b4a6efdeeb24a2087680fd4163896ab8e/packages/bower-json/lib/json.js#L144

A colleague ran into this today. I don't see any reason to make the package name so limited. NPM limits package names to 214 characters (which is such a weird number that I have to assume there's a strong reason for it): https://docs.npmjs.com/files/package.json

**Comment by sheerun** [comment]
it's a magic number, one rarely needs more. one reason to limit length is because some systems (windows) have limit on path size (250 characters or so).

**Comment by jcollum** [comment]
So why not make it the same as node? If it's arbitrary at least pick a
number that someone else in the same ecosystem picked.

**Comment by sheerun** [comment]
I didn't pick it and there's not enough reason to change it

**Comment by envygeeks** [comment]
@sheerun that's wrong, Windows 10 removed that limit last year.
