### ISSUE TITLE
save weui

### ISSUE THREAD

**Issue by XDHHBanks** [bower/bower#2443]
git clone https://github.com/weui/weui.git
cd weui
npm install -g gulp
npm install
gulp -ws

If you are reporting a new issue, make sure that we do not have any duplicates.
You can ensure this by searching the issue list for this repository.

You are welcome to open issues to discuss important general topics concerning Bower.
However for support questions, please consider using http://stackoverflow.com or
asking for help in our Discord channel: https://discordapp.com/invite/0fFM7QF0KpZaDeN9

# BUG REPORT

Use the commands below to provide key information to reproduce:
You do NOT have to include this information if this is a FEATURE REQUEST OR DISCUSSION

For more information about reporting bugs, see:
https://github.com/bower/bower/wiki/Report-a-Bug

-->

**Output of `bower -v && npm -v && node -v`:**

```
(paste your output here)
```

**Additional environment details (proxy, private registry, etc.):**

**Steps to reproduce the issue:**

1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information:**

**Comment by sheerun** [comment]
this is not bower's bug

**Comment by XDHHBanks** [comment]
自家银行，更贴心意！
