### ISSUE TITLE
npm install -g bower 

### ISSUE THREAD

**Issue by punnashivakrishna** [bower/bower#2444]
bower angular#~1.6.0           ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/angular/bower-angular.git", exit code of #128 fatal: unable to access 'https://github.com/angular/bower-angular.git/': error se
tting certificate verify locations:   CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt   CApath: none

Additional error details:
fatal: unable to access 'https://github.com/angular/bower-angular.git/': error setting certificate verify locations:
  CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none

can anyone help me
thanks

**Comment by jameelmoses** [comment]
https://github.com/npm/npm/issues/1484#issuecomment-264656461

That should help you out. It doesn't appear that your certificate is existing where git thinks it is.

**Comment by thinkxl** [comment]
Closing as this is not bower related. @jameelmoses thanks for the link!
