### ISSUE TITLE
Win when Node and Git Bash is installed on other disk then c: bower is getting wrong path to module

### ISSUE THREAD

**Issue by kb-git** [bower/bower#2449]
**Output of `bower -v && npm -v && node -v`:**

```
C:\Users\BlueA>bower -v && npm -v && node -v
1.8.0
3.10.10
v6.10.1
```

**Additional environment details (proxy, private registry, etc.):**

Win 10 pro x64 
Git-2.12.2-64-bit

![image](https://cloud.githubusercontent.com/assets/17294332/24582748/d16ba550-1736-11e7-8686-5e89b4955860.png)

**Steps to reproduce the issue:**
1. Install Git on for example D:
2. Install Node on for example D:
3. Run Git Bash type any command for bower for example 'bower -v'

**Describe the results you received:**
Hello, like u can see on image bellow from Git Bash when I'm trying execute bower command for example 'bower -v',  bower is throwing error with path('D:\Program Files\Git\node_modules\bower\bin\bower') to module which is in another directory('C:\Users\BlueA\AppData\Roaming\npm\node_modules\bower\bin\bower'). The issue are not occurs on cmd. The reason is probably that because I have installed Node or Git on d: not c:.

![image](https://cloud.githubusercontent.com/assets/17294332/24581954/b4080a6e-1725-11e7-86e8-9653b2e1d14b.png)

![image](https://cloud.githubusercontent.com/assets/17294332/24581952/a86bd0be-1725-11e7-947a-62e00d75260b.png)

`$ bower -v
module.js:471
    throw err;
    ^

Error: Cannot find module 'D:\Program Files\Git\node_modules\bower\bin\bower'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
`

**Describe the results you expected:**

**Additional information:**
![image](https://cloud.githubusercontent.com/assets/17294332/24582500/62203de6-1731-11e7-87c1-4588a58bfd71.png)

![image](https://cloud.githubusercontent.com/assets/17294332/24582805/ea1bf07c-1737-11e7-8165-141c279b262f.png)

I have tried to run Git Bash as Administrator but that didn't resolve issue.

**Comment by thinkxl** [comment]
hey @bower/windows, need some help here, could you try to replicate this?

**Comment by PatrickWalker** [comment]
The file in the stacktrace is a node.js file rather than Bower. 

How was Bower installed?

The file referenced does try and use current working directory at some points

**Comment by kb-git** [comment]
I checked other packages and the same problem occurs so @PatrickWalker as you pointed It is something with my node. I have installed a few diffrent versions of node before v6.10.1 so maybe something is missing or is corrupted. 

![2](https://cloud.githubusercontent.com/assets/17294332/25786448/84f9e6c0-3395-11e7-9d94-6d917c8da007.png)

```

BlueA@DESKTOP-86T917B MINGW64 ~
$ bower -v
module.js:471
    throw err;
    ^

Error: Cannot find module 'D:\Program Files\Git\node_modules\bower\bin\bower'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

BlueA@DESKTOP-86T917B MINGW64 ~
$ npm uninstall bower
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\BlueA\package.json'
npm WARN BlueA No description
npm WARN BlueA No repository field.
npm WARN BlueA No README data
npm WARN BlueA No license field.

BlueA@DESKTOP-86T917B MINGW64 ~
$ npm uninstall -g bower
- bower@1.8.0 node_modules\bower

BlueA@DESKTOP-86T917B MINGW64 ~
$ npm install -g bower
C:\Users\BlueA\AppData\Roaming\npm\bower -> C:\Users\BlueA\AppData\Roaming\npm\node_modules\bower\bin\bower
C:\Users\BlueA\AppData\Roaming\npm
`-- bower@1.8.0


BlueA@DESKTOP-86T917B MINGW64 ~
$ bower -v
module.js:471
    throw err;
    ^

Error: Cannot find module 'D:\Program Files\Git\node_modules\bower\bin\bower'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

BlueA@DESKTOP-86T917B MINGW64 ~
$ npm list -g --depth=0
C:\Users\BlueA\AppData\Roaming\npm
+-- bower@1.8.0
+-- generator-webapp@2.4.1
+-- gulp@3.9.1
+-- gulp-cli@1.2.2
`-- yo@1.8.5


BlueA@DESKTOP-86T917B MINGW64 ~
$ gulp -v
module.js:471
    throw err;
    ^

Error: Cannot find module 'D:\Program Files\Git\node_modules\gulp-cli\bin\gulp.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

BlueA@DESKTOP-86T917
```

**Comment by hiciu** [comment]
Hi @Karklik, have you managed to fix your node / mingw environment?

I have very similar issue, after few hours of debugging I think this could be some rare bug in mingw and windows 10. I would be grateful if you could execute these commands in your mingw environment to confirm:

This one should return `hello world`:
```
$ sh -c 'echo $(echo hello world)'
```

This one too should return `hello world`:
```
sh -c 'sleep 1; echo $(sleep 1; echo $(sleep 1; echo hello world))'
```

But this one is failing on my windows 10 system:
```
sh -c 'echo $(echo $(echo hello world))'
```

How is this related to node? Packages installed via npm have wrapper script that is executed with bash, and at the beginning it executes something like this:

```
basedir=$(dirname "$(echo $0)")
```

If you execute for example gulp with "bash -x", like this: `bash -x node_modules/.bin/gulp` you will notice that basdir is empty even though it shouldn't be. So far I'm unable to reproduce this with windows 8.1.

**Comment by Karklik** [comment]
Hi, I didn't resolve my issue and I don't have access anymore to pc with
this issue, it was a quiet long time ago.

19.01.2018 6:25 PM "hiciu" <notifications@github.com> napisał(a):

**Comment by kospl** [comment]
Not sure it's bower problem, but I have exactly problem described by OP with Windows 10 with mingw, Git and Bower:

```
$ bower install
module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\Git\node_modules\bower\bin\bower'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
```

For some reason it's trying to load C:\Program Files\ **Git** \node_modules\bower\bin\bower, but probably should look under C:\Program Files\ **nodejs** \node_modules\bower\bin\bower
