### ISSUE TITLE
[Question] Why does bower recommend yarn? But yarn does not support bower.

### ISSUE THREAD

**Issue by ajcastro** [bower/bower#2452]
In the website of bower, it says: 
> ...psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects!

But I found out that yarn dropped the support for bower. http://stackoverflow.com/a/40035166

**Comment by thinkxl** [comment]
Some context: https://github.com/bower/bower.github.io/commit/12566e5b777ef4c93c525cf3d2fa35ebc9f4d2e5

**Comment by thinkxl** [comment]
I will close this for now. Feel free to join our [discord channel](https://discordapp.com/channels/119103197720739842/123728452816732160) if you have any further questions.

**Comment by sheerun** [comment]
Also, yarn doesn't need to support bower, as it is an alternative, not an integration. The purpose of both bower and yarn is simple: download dependencies of your project into some directory. Please read Bower's blog to know why yarn might be a better choice.

**Comment by ajcastro** [comment]
As long as the js packages can be included via traditional <script src="">, I think there's no problem. The issue here is when others dont want to use bundlers like webpack and browserify. They cannot use packages which are in common js format only.

**Comment by sheerun** [comment]
Honestly I think not using a bundler nowadays is to be discouraged. It's easy/familiar to start this way, but it ends with either tenths of `<script src="">` in production, or by implementing bundler by hand with something like gulp or grunt (these tools aren't bundlers but for automating tasks).

**Comment by ajcastro** [comment]
Yeah.. It makes sense.

**Comment by cjsimon** [comment]
Are there any alternatives to using a bundler in this scenario? Let's say for a real world scenario where your current code base does not and won't be using use one.
