### ISSUE TITLE
Package dependancies are not installed when "*" is ignored in bower.json.

### ISSUE THREAD

**Issue by arctelix** [bower/bower#2456]
Consider the following bower.json file residing in project_root/packageA:

```
}
    "ignore": ["*"],
    "dependencies": {
        "some-dependancy": "0.0.0",
    }
}
```

And this bower.json in project_root:

```
}
    "dependencies": {
        "packageA": "./packageA",
    }
}
```

Running `bower install` in project_root should install packageA with only a `.bower.json` file and all of packageA's dependancies.   So we would expect project_root/bower_components to look like this:

```
packageA
  - .bower.json
some-dependancy
  ...
```
However, packageA's dependancies are not installed, only a directory for packageA with a .bower.json file.   Has someting changed?  Is there any reason for this behavior?  Can we get this to behave as expected?

**Comment by thinkxl** [comment]
AFAIK this is expected behavior unless @sheerun says otherwise. This might help you: https://stackoverflow.com/questions/21225803/recursive-bower-install
