### ISSUE TITLE
Install Global Package in Bower

### ISSUE THREAD

**Issue by Progyan1997** [bower/bower#2459]
How to install global packages with bower?

Like in npm we have: `npm install <package-name> -g`
Is there similar functionality in bower also?
I need to install a package as CLI, but while installing it always installs in current directory instead of npm registry. How to fix this?

**Comment by mischah** [comment]
It’s not possible. 

> I need to install a package as CLI

Just use npm or Yarn.

**Comment by sheerun** [comment]
Bower doesn't have such functionality
