### ISSUE TITLE
Bower deprecation warning points to non-existent blog post

### ISSUE THREAD

**Issue by IGx89** [bower/bower#2460]
I'm seeing the following message when using Bower: "psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects! Please read our blog for more."

However, I can't find the blog post referred to. I Google'd and https://bower.io/blog/ appears to be the official blog, but nothing on there talks about Bower being deprecated. I see posts about "Bower is growing!" and "What's new in bower", as well as a post recommending trying Yarn (but then saying Yarn has temporarily dropped support for bower). 

Am I missing something? Was the blog post deleted? I was expecting to see a post about why Bower is deprecated now (graphs of declining usage, areas its lacking in, developers moving on, etc.) and helpful instructions on how to upgrade Bower apps to Yarn/Webpack.

**Comment by sheerun** [comment]
It's the one about Yarn and its advantages compared to Bower.

**Comment by dequis** [comment]
>It's the one about Yarn and its advantages compared to Bower.

But that post says

>UPDATE: Yarn decided to drop Bower support for now. We recommend to try it anyway as an alternative to npm!

Which sounds like yarn isn't really a replacement

**Comment by panuhorsmalahti** [comment]
And now that npm v5 is released, there's little benefit from yarn over npm. I'd probably change yarn to npm now, even if npm v5 doesn't have special bower support.

**Comment by sheerun** [comment]
Yarn supports full flatttning and right now is reported to be more stable
and little faster. I'd consiter it in few months, not right after the
release.

**Comment by neilsh** [comment]
Would it be possible to include some info on how one would actually transition to yarn/webpack? As it currently stands the message is pretty confusing.

**Comment by sheerun** [comment]
Currently there's no transition path, that's why it says "for new projects".

We could publish an article how to migrate from bower to yarn, but currently it's blocked by non-ability of yarn installing git repositories without package.json: https://github.com/yarnpkg/yarn/pull/2651

As soon as yarn is released with this feature we could write the article or tool to migrate.

**Comment by sheerun** [comment]
I've changed deprecation message on `npm install -g bower` to hopefully something better:

> ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path but we hope you'll help us figure out one.
