### ISSUE TITLE
git ls-remote alway error,when install any package

### ISSUE THREAD

**Issue by Talbot3** [bower/bower#2463]
# BUG REPORT

bower v1.8.0
node v7.8.0
git v2.7.4

**Additional environment details (proxy, private registry, etc.):**
registry=https://registry.npm.taobao.org

**Steps to reproduce the issue:**

1. npm install --save underscore

**Describe the results you received:**
```
bower underscore#*          not-cached https://github.com/jashkenas/underscore.git#*
bower underscore#*             resolve https://github.com/jashkenas/underscore.git#*
bower underscore#*             ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/jashkenas/underscore.git", exit code of #128 fatal: transport 'https' not allowed

Additional error details:
fatal: transport 'https' not allowed

```

**Describe the results you expected:**
I hope can install package successfu

**Additional information:**
When Boser install any package ,have same issues

**Comment by thinkxl** [comment]
Can you take a look at these:
* https://github.com/Hacklone/private-bower/issues/102#issuecomment-76548661
* https://github.com/bower/bower/issues/713
And see if they solve your issue?

**Comment by sheerun** [comment]
This issue is stale. If this is still an issue for someone, please open new one
