### ISSUE TITLE
License details not updated as expected in Bower Package Manager - VS 2017

### ISSUE THREAD

**Issue by Abbas1546** [bower/bower#2465]
Hi,

We have updated the Licensing details for our Bower Package as mentioned in the documentation for our UG. But it seems license field is empty when we load our bower package from Visual Studio Bower Package Manager. Find the Bower details and screenshot below,

**Package name** : syncfusion-ej-global

**Bower.json** - https://github.com/syncfusion/ej-global/blob/master/bower.json

**Bower Package Manager from VS** - 

![image](https://user-images.githubusercontent.com/24931580/27020895-3f505ec2-4f62-11e7-9f72-e356124c3aff.png)

Can you please update the details to fix this issue? 

Thanks,
Abbas K

**Comment by sheerun** [comment]
bower doesn't maintain any information in registry except name -> url mapping

maybe you need to clear the cache

**Comment by Abbas1546** [comment]
@sheerun  - Cache clear doesn't work. Any other work around regarding this ?

**Comment by sheerun** [comment]
nothing we can do from our side, you need to contact support for VS 2017

**Comment by Abbas1546** [comment]
@sheerun - Thanks for your time and update.
