### ISSUE TITLE
deprecation message on npm is grammatically incorrect

### ISSUE THREAD

**Issue by graingert** [bower/bower#2466]
", and Webpack's is support for both CommonJS and AMD projects."

', and' is invalid
"Webpack's is " is invalid.

**Comment by sheerun** [comment]
From my understanding both are correct:

https://www.grammarly.com/blog/comma-before-and/
http://www.grammarbook.com/punctuation/apostro.asp

What should be the correct form according to you?

**Comment by sheerun** [comment]
btw. in `Webpack's is`, the `'s` refers to something of Webpack (advantage), and `is` refers to advantage, so it's not a duplication

**Comment by thinkxl** [comment]
Closing this as no more feedback has been given, and the issue was clarified by @sheerun
