### ISSUE TITLE
Debugging Bower "INVALID_PURPOSE" certificate error?

### ISSUE THREAD

**Issue by ornamentist** [bower/bower#2469]
On any use of Bower install <package> I'm getting this certificate error:

```
bower INVALID_PURPOSE      Request to https://bower.herokuapp.com/packages/lodash failed: unsupported certificate purpose
```

Firefox also complains about that URL.  I've tried this on two macOS systems and a new Debian VM with the same error. I've also tried NPM and Yarn. I'm guessing this might be something in my firewall setup or other local network issue.

It's probably not an error in Bower but I'd appreciate any advice on how I might debug the issue and the correct collection of settings to possibly turn off HTTPS/SSL access during installations.

**Output of `bower -v && npm -v && node -v`:**

```
$ bower -v
1.3.0
$ yarn -v
yarn install v0.27.5
$ node -v
v8.1.3
```

**Comment by thinkxl** [comment]
I'm sorry, but as this is not Bower related we can't really troubleshoot it or give support. Closing this.

**Comment by ornamentist** [comment]
My apologies for raising it.  There is a (tangential) relation to Bower that might be useful for future reference.

As I understand it Bower uses https://bower.herokuapp.com as a registry of package metadata (?) My firewall ad/trackers/malware blocking package subscribes to a recommended domains-to-block service that lists herokuapp.com as a known source of these problems. Once I whitelisted that domain the bower issues went way.
