### ISSUE TITLE
Bower not found while running or executing jenkins pipeline job

### ISSUE THREAD

**Issue by sarjerav** [bower/bower#2471]
Hello All,

I have installed jenkins on my local windows 7. I have installed java 8. I have downloaded jenkins from official website & completed setup by signing up.

I have spring boot project with jenkinsFile so I started creating job with pipeline. I have setup pipeline from SCM git/bitbucket. I have also added specific Branch in Branches to build & script path as jenkinsFile path. 
I have installed plugins like NodeJSPlugin. & configured in global tool configuration for NodeJS installation.
I tried multiple ways to install bower package but it won't give me success. Also after bower I want to install gulp.
This is how my job is created. 

please find below error log.

> [Pipeline] tool
> $ cmd /c "C:\Program Files (x86)\Jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\node-4.6.0\npm.cmd" install -g npm install -g npm
> C:\Program Files (x86)\Jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\node-4.6.0\npm -> C:\Program Files (x86)\Jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\node-4.6.0\node_modules\npm\bin\npm-cli.js
> C:\Program Files (x86)\Jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\node-4.6.0\npx -> C:\Program Files (x86)\Jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\node-4.6.0\node_modules\npm\bin\npx-cli.js
> + install@0.10.1
> + npm@5.3.0
> + npm@5.3.0
> updated 2 packages in 89.036s
> [Pipeline] stage
> [Pipeline] { (check tools)
> [Pipeline] sh
> [C:\Program Files (x86)\Jenkins\workspace\test-project-v0.1] Running shell script
> + node -v
> v6.10.0
> [Pipeline] sh
> [C:\Program Files (x86)\Jenkins\workspace\test-project-v0.1] Running shell script
> + npm -v
> 3.10.10
> [Pipeline] sh
> [C:\Program Files (x86)\Jenkins\workspace\test-project-v0.1] Running shell script
> + bower -v
> C:/Program Files (x86)/Jenkins/workspace/test-project-v0.1@tmp/durable-4ecb94cf/script.sh: line 2: bower: command not found
> [Pipeline] }
> [Pipeline] // stage
> [Pipeline] }
> [Pipeline] // node
> [Pipeline] End of Pipeline
> ERROR: script returned exit code 127
> Finished: FAILURE

I tried multiple ways to install by trying Global npm packages to install as - npm install -g grunt-bower-cli, npm install -g bower, bower@1.8.0 grunt-cli .

![image](https://user-images.githubusercontent.com/3907661/28567305-8554a8ba-714f-11e7-936b-3ddcba6e6bf8.png)

**Comment by sheerun** [comment]
@graingert Said before:

It looks like you've not added
C:\Program Files (x86)\Jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\node-4.6.0\

To your PATH.

---

In general this kind of issue is out of scope for Bower's issue tracker, as it seems it's not an issue with Bower itself but with your environment. We're no experts in Jenkins.

**Comment by graingert** [comment]
@sarjerav don't install bower globally!

In your package.json add:
```json
{
  "name": "your-project-name-here",
  "version": "0.0.1",
  "devDependencies": [
    "bower": "^1.7.7",
  ],
  "scripts": {
    "postinstall": "bower install",
  }
]
```

then run "yarn install" or "npm install", and it will install bower and run the bower install for you.
