### ISSUE TITLE
https://bower.io/search/ search no result ?

### ISSUE THREAD

**Issue by taadis** [bower/bower#2473]
**Output of `bower -v && npm -v && node -v`:**

```
1.7.9
3.10.8
v7.0.0
```

**Additional environment details (proxy, private registry, etc.):**

**Steps to reproduce the issue:**

1. `bower search taadis-tagcanvas` 
2. https://bower.io/search/ -> search`taadis-tagcanvas`
3.

**Describe the results you received:**
> 1. use commond `bower search taadis-tagcanvas` that ok. 
Search results:
    taadis-tagcanvas https://github.com/taadis/tagcanvas.git

> 2. search`taadis-tagcanvas` for [https://bower.io/search/](https://bower.io/search/) that no result ?

**Describe the results you expected:**
> 2. search`taadis-tagcanvas` for [https://bower.io/search/](https://bower.io/search/) that also ok.

**Additional information:**

**Comment by sheerun** [comment]
The search engine is handled by https://libraries.io/ Please contact them :)
