### ISSUE TITLE
can't run bower install  with yarn ?

### ISSUE THREAD

**Issue by jpca999** [bower/bower#2477]
after installing yran i can't run bower commands.. it keep giving me this error. 
I tried chmod and other options but still theres error. whats the solution ?

![image](https://user-images.githubusercontent.com/1026325/29535956-e64fcb3c-8689-11e7-956a-e630591e3be0.png)

**Output of `bower -v && npm -v && node -v`:**

```
(paste your output here)
```

**Additional environment details (proxy, private registry, etc.):**

**Steps to reproduce the issue:**

1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information:**

**Comment by sheerun** [comment]
you probably run some command with sudo, the fix is:

sudo chown -R $USER $HOME/.config
