### ISSUE TITLE
Bower versioning issue

### ISSUE THREAD

**Issue by vineethvnair0** [bower/bower#2478]
**Output of `bower -v && npm -v && node -v`:**

```
(1.6.5 && 3.3.10 && v0.10.36)
```

**Additional environment details (proxy, private registry, etc.):**

**Steps to reproduce the issue:**

1.Created a component which has all angular dependencies and resolution towards angular 1.5.11
2.Use this component in another component as a dependency
3.When i do bower installl

**Unable to find a suitable version for angular, please choose one:
    1) angular#1.4.0 which resolved to 1.4.0 and is required by angular-cookies#1.4.0
    2) angular#1.4.5 which resolved to 1.4.5 and is required by angular-mocks#1.4.5
    3) angular#>=1.0.8 which resolved to 1.4.14 and is required by angular-breadcrumb#0.4.1
    4) angular#>= 1.0.8 which resolved to 1.4.14 and is required by angular-ui-router#0.2.15
    5) angular#>1.3.x which resolved to 1.4.14 and is required by angular-material-icons#0.7.1
    6) angular#>=1.2.0 <1.7.0 which resolved to 1.4.14 and is required by angular-moment#1.0.1
    7) angular#^1 which resolved to 1.4.14 and is required by angular-ui-layout#1.4.1
    8) angular#>=1.2.26 <=1.5 which resolved to 1.4.14 and is required by angular-translate#2.7.2
    9) angular#>=1.3.* which resolved to 1.4.14 and is required by angular-file-model#0.3.1
    10) angular#^1.1.5 which resolved to 1.4.14 and is required by angular-file-upload#2.3.4
    11) angular#>= 1.2.0 which resolved to 1.4.14 and is required by ng-idle#1.1.1
    12) angular#^1.4.8 which resolved to 1.4.14 and is required by angular-material#1.1.4
    13) angular#* which resolved to 1.4.14 and is required by angular-websocket#1.1.0
    14) angular#^1.4.0 which resolved to 1.4.14 and is required by angular-material-data-table#0.10.10
    15) angular#1.5.11 which resolved to 1.5.11 and is required by angular-animate#1.5.11, angular-aria#1.5.11, angular-messages#1.5.11, angular-resource#1.5.11, angular-route#1.5.11, angular-sanitize#1.5.11, angular-touch#1.5.11, common-lib#1.0.2

**

**Expecting bower to resolve it automatically as its mentioned in common-lib**

**Contents of bower.json of common-lib 
{
  "name": "common-lib",
  "version": "1.0.2",
  "authors": [ ],
  "main": [
  ],
  "dependencies": {
    "angular": "1.5.11",
    "angular-animate": "1.5.11",
    "angular-aria": "1.5.11",
    "angular-route": "1.5.11",
    "angular-sanitize": "1.5.11",
    "angular-touch": "1.5.11",
    "angular-material": "1.1.4",
    "angular-resource": "1.5.11",
    "angular-touch": "1.5.11",
    "angular-translate": "2.7.2",
    "angular-cookies": "1.4.0",
    "angular-translate-storage-local": "2.7.2",
    "angular-translate-loader-static-files": "2.7.2",
    "angular-ui-router": "0.2.15",
    "angular-breadcrumb": "0.4.1",
    "angular-dynamic-locale": "0.1.32",
    "angular-i18n": "1.6.5",
    "angularjs-imageupload-directive": "*",
    "angular-material-data-table": "0.10.10",
    "angular-material-icons": "0.7.1",
    "angular-messages": "1.5.11",
    "angular-moment": "1.0.1",
    "angular-translate-loader-partial": "2.7.2",
    "angular-translate-loader-url": "2.7.2",
    "angular-translate-storage-cookie": "2.7.2",
    "angular-ui-layout": "1.4.1",
    "angular-underscore-module": "1.0.3",
    "angular-websocket": "1.1.0",
    "jquery": "3.1.1",
    "angular-file-model": "0.3.1",
    "angular-file-upload": "2.3.4",
    "ng-idle": "1.1.1",
    "angular-mocks":"1.4.5"
  },
  "license": "PRIVATE",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "devDependencies": {
    "angular-mocks": "~1.5.0"
  },
  "resolutions": {
    "angular": "1.5.11"
  }
}

**

**Comment by sheerun** [comment]
this is standard behavior when there are multiple matching versions, you need to manually select one as bower cannot possibly decide by itself which package should have correct version of dependency and which not
