### ISSUE TITLE
register works without login

### ISSUE THREAD

**Issue by patrickhrastnik** [bower/bower#2479]
When using "bower register" no login credentials are needed.
But "bower unregister" needs login first.

Scenario:
I thought "bower register" will add some package to my local registry. So I executed the following command:
`bower register jquery.mailto https://github.com/chris-fuchman/jquery.mailtoIt`
Then I recognized I made some typo in the package name (original name is `jquery.mailtoIt` but I registered it as `bower.mailto`) and wanted to unregister the package.
`bower unregister jquery.mailto`
Then the following error occured:
`bower EFORBIDDEN    Use "bower login" with collaborator credentials`
So I logged in with my credentials using `bower login`, but I wasn't able to unregister the package name:
`bower EFORBIDDEN    Must have push access to view repository collaborators.`

Is this a security issue?

**Comment by robv8r** [comment]
> When using "bower register" no login credentials are needed.
> But "bower unregister" needs login first.

This is by design.  https://bower.io/docs/creating-packages/#register

Per the above documentation:

> You’ll likely want to `bower cache clean` after your change. Please remember it is generally considered bad behavior to remove versions of a library that others are depending on. Think twice :) If the above doesn’t work for you, you can [request a package be unregistered manually](https://github.com/bower/registry/issues).

**Comment by thinkxl** [comment]
Like @robv8r said, this is by design. Closing the issue.

**Comment by patrickhrastnik** [comment]
@robv8r thanks for explanation. But how do I fix my typo? As mentioned above, `jquery.mailto` is the wrong package name - its correct name is `jquery.mailtoIt`.
