### ISSUE TITLE
Bower 1.8.2 reports incorrect version

### ISSUE THREAD

**Issue by liger1978** [bower/bower#2483]
**Output of `bower -v && npm -v && node -v`:**

```
1.8.0
3.10.10
v6.11.3
```

**Additional environment details (proxy, private registry, etc.):**

NA

**Steps to reproduce the issue:**

1. Run `bower -v`

**Describe the results you received:**

`1.8.0`

**Describe the results you expected:**

`1.8.2`

**Additional information:**

NA

**Comment by sheerun** [comment]
that's true.. does it affect you in any way?

**Comment by liger1978** [comment]
No, I don't care.  Just thought the project might like to know...

**Comment by sheerun** [comment]
yes, thank you

**Comment by sheerun** [comment]
Seems to work for me now

**Comment by liger1978** [comment]
Happening again for version 1.8.4.  Bower reports its version as "1.8.3".
