### ISSUE TITLE
https://bower.herokuapp.com/packages/xxxx 410

### ISSUE THREAD

**Issue by blowsie** [bower/bower#2484]
**Output of `bower -v && npm -v && node -v`:**

```
λ bower -v && npm -v && node -v
1.8.0
5.3.0
v6.10.0
```

**Additional environment details (proxy, private registry, etc.):**

**Steps to reproduce the issue:**

1. `bower list`

**Describe the results you received:**
> Request to https://bower.herokuapp.com/packages/angular failed with 410

**Describe the results you expected:**
> HTTP 200

**Additional information:**
I have tested on my mobile outside of this network and encounter the same issue.

**Comment by TheDutchCoder** [comment]
Can confirm, we're getting the same issue.

**Comment by blowsie** [comment]
https://twitter.com/bower/status/918073147789889536
https://gist.github.com/sheerun/c04d856a7a368bad2896ff0c4958cb00

**Comment by blowsie** [comment]
https://bower.io/blog/2017/how-to-migrate-away-from-bower/

**Comment by blowsie** [comment]
As discovered, this is not a bug, but an undocumented change. 
I'd imagine this ticket will be discovered by many in the coming hours / days.

**Comment by TheDutchCoder** [comment]
Holy moly, didn't see that coming...

But thanks for pointing me in the right direction, we'll try to switch it asap as our (production) docker images depend on it.

**Comment by sheerun** [comment]
The solution is to upgrade bower (preferred solution) or put following in your `.bowerrc`:

```
{
  "registry": "https://registry.bower.io"
}
```

Why deprecate old registry url? The current domain of registry hardcored into Bower (https://bower.herokuapp.com) belongs to Heroku. It means we have no control over it and that presents at least two serious disadvantages:

1) We're dependent on Heroku for hosting of the registry (currently they kindly provide us with credits but we can't expect it forever)
2) We are unable to change DNS of this domain to, for example, put it behind CDN for reduced costs and latency.

To fix this, we released patches for each Bower version that change registry url to https://registry.bower.io It's enough to upgrade.

In case someone is unable to upgrade Bower (not recommended), the .bowerrc file presented above needs to be added to a project.
