### ISSUE TITLE
Default Naming Convention for a Project Directory needs to be converted to lowercase while running the command "bower init".

### ISSUE THREAD

**Issue by tvek** [bower/bower#2486]
**Output of `bower -v && npm -v && node -v`:**

```
1.8.2
2.15.8
v4.4.7
```

**Additional environment details (proxy, private registry, etc.):**
NA (Not Applicatable)

**Steps to reproduce the issue:**

1. Creating the Project Directory with camel Cased Folder Name
`mkdir "tvekProject"`
2. Installing Required Packages using bower
`bower install angularjs jquery boostrap backbone`
3. Initializing the project using bower
`bower init`
_Output :_
> ? name tvekProject
> ? description
> ? main file
> ? keywords
> ? authors
> ? license MIT
> ? homepage
> ? set currently installed components as dependencies? Yes
> ? add commonly ignored files to ignore list? Yes
> ? would you like to mark this package as private which prevents it from being accidentally published to the registry? No
> 
> {
>   name: 'tvekProject',
>   description: '',
>   main: '',
>   license: 'MIT',
>   homepage: 'index.html',
>   ignore: [
>     '**/.*',
>     'node_modules',
>     'bower_components',
>     'test',
>     'tests'
>   ],
>   dependencies: {
>     angular: 'angularjs#^1.6.6',
>     backbone: '^1.3.3',
>     bootstrap: '^3.3.7'
>   }
> }
4. Show the Bower Home
`bower home`
_Output:_
> bower invalid-meta  for:/home/scrapbook/tutorial/tvekProject/bower.json
> bower invalid-meta  The "name" is recommended to be lowercase, can contain digits, dots, dashes

**_HERE WE CAN SEE THAT THE PROJECT DEFAULT NAMING CONVENTION IN INIT COMMAND TO SUPPORT CAMELCASED HAS CONFLICTED WITH THE HOME COMMAND._**

**Describe the results you received:**

here in the output, it has shown that the bower.json contains an invalid-meta tag for "name" as "tvekProject".
> $>bower home
> bower invalid-meta  for:/home/scrapbook/tutorial/tvekProject/bower.json
> bower invalid-meta  The "name" is recommended to be lowercase, can contain digits, dots, dashes
> $>

**Describe the results you expected:**
> $>` bower home`
>
> $>

**Additional information:**
The Expected Solution for this is change the default project name to lowercase(name of the current foldername.).

ie.,
Currently
 > ? name tvekProject

After Fixing

> ? name tvek-project

**Comment by sheerun** [comment]
Bower is deprecated and we don't recommend creating new packages
