### ISSUE TITLE
Unexpected token @ in JSON at position 0

### ISSUE THREAD

**Issue by akvaliya** [bower/bower#2488]
I am running bower install command & it stops with error "Unexpected token @ in JSON at position 0"

![](https://content.screencast.com/users/Akvaliya/folders/Jing/media/6481e8e7-26b0-4e53-b744-45a5abb58a49/2017-10-23_1831.png)

Below is my bower.json file

{
  "name": "demo1",
  "dependencies": {
    "jquery": "~3.2.0",
    "angular": "~1.6.1",
    "angular-animate": "~1.6.1",
    "angular-aria": "~1.6.1",
    "angular-messages": "^1.6.1",
    "angular-ui-router": "^0.4.2",
    "angular-translate": "~2.15.1",
    "angular-translate-loader-static-files": "~2.15.1",
    "angular-scroll": "~1.0.0",
    "jquery.slimscroll": "~1.3.8",
    "oclazyload": "^1.0.9",
    "webfontloader": "^1.6.24",
    "angular-material": "1.1.3",
    "angular-validation-match": "^1.9.0",
    "textAngular": "~1.5.12",
    "angular-wizard": "^0.10.0",
    "angular-material-data-table": "^0.10.9",
    "ngmap": "^1.17.3",
    "ngECharts": "ngecharts#^0.2.0",
    "echarts": "~3.4.0",
    "angular-ui-calendar": "1.0.1",
    "fullcalendar": "~2.3.1",
    "font-awesome": "^4.7.0",
    "weather-icons": "^2.0.10"
  },
  "devDependencies": {
    "bootstrap": "~4.0.0-alpha.6",
    "material-design-lite": "~1.3.0"
  },
  "resolutions": {
    "angular": "~1.6.1",
    "jquery": "~3.2.0"
  }
}

Can anyone help me to resolve this issue. I am using latest version of bower.

**Comment by sheerun** [comment]
What is the contents of this json file?

**Comment by akvaliya** [comment]
@sheerun What do you mean by contents? That is complete bower.json file.

**Comment by rquadling** [comment]
https://github.com/twbs/bootstrap/blob/v4-dev/bower.json

Bootstrap 4 no longer supports bower.

**Comment by akvaliya** [comment]
@rquadling Thanks for the reply. All i had to do is remove "~" from `"bootstrap": "~4.0.0-alpha.6"`. After i modified it to "bootstrap": "4.0.0-alpha.6" it works.
