### ISSUE TITLE
ECONNRESET tunnelling socket could not be established, cause=write EPROTO

### ISSUE THREAD

**Issue by cyb-prajaktac** [bower/bower#2489]
**Output of `bower -v && npm -v && node -v`:**

```
bower -v
1.8.0

 npm -v 
3.10.10

node -v
6.11.0
```

**Additional environment details (proxy, private registry, etc.):**
```
{
  "directory": "bower_components",
  "registry": "http://bower.herokuapp.com",
  "strict-ssl" : false
}
```

**Steps to reproduce the issue:**

1. bower install

**Describe the results you received:**

Getting retry error for almost every plugin mentioned in the `bower.json` with failed with ECONNRESET error like this:

```
retry Download of https://github.com/lodash/lodash/archive/2.4.2.tar.gz failed with ECONNRESET, trying with git..

```

Tried solutions:

https://github.com/bower/bower/issues/467#issuecomment-58002733

Not sure what exactly is the problem. Please let me know if you need more info.

Thanks

**Comment by sheerun** [comment]
bower.herokuapp.com is deprecated, please update bower to newest version
