### ISSUE TITLE
bower install | GutHub keeps asking for github username & password

### ISSUE THREAD

**Issue by GRawatCoder** [bower/bower#2490]
I am struggling with this issue while installing bower install it keeps asking for github username and password everytime, does anyone has any idea or faces this issue ?

Error while installing -

![image](https://user-images.githubusercontent.com/22786031/32095318-60d0efc4-bb20-11e7-883f-28f109efcf5b.png)

**Comment by sheerun** [comment]
It's because this repo/file doesn't exist anymore, probably.

**Comment by GRawatCoder** [comment]
Thanks sheerun. I found owl carousel doesn't exist anymore ob bower.

**Comment by GRawatCoder** [comment]
how do i install owl-carousel now ? do you have any suggestion ?

**Comment by sheerun** [comment]
maybe something like bower install OwlCarousel2/OwlCarousel2

**Comment by GRawatCoder** [comment]
updated the owl.carousel version mentioned in bower.json as ow.carousel 1.3.2 is not available on github repo which is why it keeps asking for github username and password.

**Comment by krishna1682** [comment]
I am getting the similar issue when I include blockUI in bower.json file. Git login popup is getting triggered and getting the following error message.

**Error in plugin 'gulp-bower'**
Message:
    Failed to execute "git ls-remote --tags --heads https://github.com/ueqt/blockui.git", exit code of #128
Logon failed, use ctrl+c to cancel basic credential prompt.
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com/': Invalid argument

Details:
    code: ECMDERR
    details: Logon failed, use ctrl+c to cancel basic credential prompt.
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com/': Invalid argument

    exitCode: 128
    data: [object Object]
