### ISSUE TITLE
Repository URL not updated when changed in a new version

### ISSUE THREAD

**Issue by lpil** [bower/bower#2494]
Hi all.

I mistakenly uploaded a package with the incorrect repository URL. I've since corrected it and pushed again, but when pull again I still get the result from the originally specified repository, even when explicitly pulling the new version.

I've reinstalled bower and removed ~/.cache/bower but no luck. How might I fix this?

The project is purescript-aws-serverless-express

```
louis ~ $ bower -v; npm -v; node -v
1.8.2
5.0.3
v8.1.3
```

**Comment by sheerun** [comment]
Package is pointing at github.com/purescript/purescript-prelude

`bower cache clean` should help
