### ISSUE TITLE
npm WARN deprecated bower@1.8.2 - npm install --global foundation-cli

### ISSUE THREAD

**Issue by funcion** [bower/bower#2504]
I'm installing, and then executing the following code.

`npm install --global foundation-cli`

It shows me the following message:

```
npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/

[    ..............] / fetchMetadata: WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/
```

**Comment by rquadling** [comment]
Yes. Bower is deprecated and you should move to something else to manage your dependencies.

Sad, but true.

**Comment by funcion** [comment]
What are the steps to follow to change from bower to https://yarnpkg.com, I have seen that just adding a regitro of this is enough, how true is it

npm registry https://yarnpkg.com

**Comment by sheerun** [comment]
You can read guide for both app developers and module developers on: https://bower.io/blog/

**Comment by sheerun** [comment]
(the message you posted in issue mentions this)

**Comment by funcion** [comment]
I've decided to use **Yarn** instead of **bower** and **npm**

It is developed by Facebook and is much faster, easy to install and use, I recommend them.

**More details:** [https://yarnpkg.com/](https://yarnpkg.com/)
