### ISSUE TITLE
bower doesn't downloads resolutions added in bower josn

### ISSUE THREAD

**Issue by karthickg24** [bower/bower#2511]
**Output of `bower -v && npm -v && node -v`:**

```
1.8.4
5.6.0
v9.7.1

```

**Additional environment details (proxy, private registry, etc.):**

**Steps to reproduce the issue:**

1. Bower.json should have some packages under resolutions
2. bower install
3. Getting following log in console

**Describe the results you received:**
bower angular         extra-resolution Unnecessary resolution: angular#1.6.1
bower angular-agility extra-resolution Unnecessary resolution: angular-agility#0.8.40
bower d3              extra-resolution Unnecessary resolution: d3#4.9.1
bower topojson        extra-resolution Unnecessary resolution: topojson#2.2.0

**Describe the results you expected:**
should download all packages added in resolutions object.

**Additional information:**

**Comment by sheerun** [comment]
please add required information or close this issue

**Comment by sheerun** [comment]
resulotions are used only when there are conflicts, this is known behavior.

in general you'd be better switching to Yarn that supports arbitrary re-writes of dependencies
