### ISSUE TITLE
Permission denied, mkdir '/opt/hygieia/UI/bower_components'

### ISSUE THREAD

**Issue by trinathtiru** [bower/bower#2514]
EACCES EACCES: permission denied, mkdir '/opt/hygieia/UI/bower_components'

**Output of `bower -v && npm -v && node -v`:**
 bower -v => 1.8.4
 npm -v => 5.6.0
node -v => v10.1.0
```
(paste your output here)
bower angular                  extra-resolution Unnecessary resolution: angular#~1.5.9
bower chartist                 extra-resolution Unnecessary resolution: chartist#~0.9.5
bower                                    EACCES EACCES: permission denied, mkdir '/opt/hygieia/UI/bower_components'

Stack trace:
Error: EACCES: permission denied, mkdir '/opt/hygieia/UI/bower_components'

Console trace:
Error
    at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:88:37)
    at Logger.<anonymous> (/usr/lib/node_modules/bower/lib/bin/bower.js:113:30)
    at Logger.emit (events.js:182:13)
    at Logger.emit (/usr/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/bower/lib/commands/index.js:49:24
    at _rejected (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:864:24)
    at /usr/lib/node_modules/bower/lib/node_modules/q/q.js:890:30
    at Promise.when (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:808:41)
    at /usr/lib/node_modules/bower/lib/node_modules/q/q.js:624:44
```

**Additional environment details (proxy, private registry, etc.):**

System info:
Bower version: 1.8.4
Node version: 10.1.0
OS: Linux 4.4.0-1052-aws x64

**Steps to reproduce the issue:**

1.
2.
3.

**Describe the results you received:**

![image](https://user-images.githubusercontent.com/33506201/39919432-3bc9f8f0-5531-11e8-9a00-0911dc0903ac.png)

**Describe the results you expected:**
Bower need to be installed successfully 

**Additional information:**

**Comment by rquadling** [comment]
Can you manually create `mkdir /opt/hygieia/UI/bower_components`?

**Comment by trinathtiru** [comment]
Thanks @rquadling 
but that doesnt help to solve my issue.
I have given this echo '{ "allow_root": true }' > /root/.bowerrc to solve the issue.

**Comment by rquadling** [comment]
Ah. OK. Well done on the fix.
