### ISSUE TITLE
Bower blockUI trying to load from older repository

### ISSUE THREAD

**Issue by gschambial** [bower/bower#2517]
I am trying to install blockUI via bower and whenever I am running `bower install`, It is trying to load old 'https://github.com/ueqt/blockui.git' instead of latest 'https://github.com/malsup/blockui.git'.

I have tried clearing cache but no benefit yielded. Any help would be appreciated.

**Comment by sheerun** [comment]
You can put something like this into bower.json:

  "dependencies": {
    "blockui": "malsup/blockui"
  }

**Comment by rquadling** [comment]
There is no github page for https://github.com/ueqt/blockui and bower.io shows malsup as the owner. As this package SEEMS to have been passed to malsup, unless there's been some significant history rewrite, things should be OK.

**Comment by gschambial** [comment]
@sheerun 
This is actually how things worked out for me. But, I want to keep it as "*" so that I would not have to worry about it whenever next time repo is passed on to some other person or version is upgraded. I guess bower should be able to manage it.

**Comment by gschambial** [comment]
@rquadling 
There was a repo with this name previously which was being referred to by bower and later it changed. But, It is still trying to load from the old one when trying to do a `bower install`

**Comment by sheerun** [comment]
I think you can use:

"dependencies": {
    "blockui": "malsup/blockui#*"
  }

**Comment by sheerun** [comment]
Plus we don't handle re-registrations, owner of this project needs to do it
