### ISSUE TITLE
Timeout + unexpected failures

### ISSUE THREAD

**Issue by MaxCCC** [bower/bower#2518]
Are there issues on https://registry.bower.io?
Our packages are breaking during a lot of builds.

**Comment by sheerun** [comment]
We don't see any issues on server side. You should not experience any issues if you use newest bower version (including one in Docker if you use it) .

**Comment by avizcaino** [comment]
Same problem here. It's been weeks struggling with this issue... lot of builds crashed due to timeouts with `bower install`.

**Comment by sheerun** [comment]
just update bower
