### ISSUE TITLE
EINVRES Request to https://bower.herokuapp.com/packages/syncfusion-javascript failed with 502

### ISSUE THREAD

**Issue by mishra14** [bower/bower#2519]
_From @GanesanRengasamy on June 27, 2018 13:14_

Hi, 

I have faced the below issue while trying to install the bower packages in my project. 

![image](https://user-images.githubusercontent.com/16695209/41976189-17cb1f96-7a3a-11e8-8573-0f29f9c43d99.png)

Could you please help me to resolve this issue?

Thanks,
Ganesan R.

_Copied from original issue: NuGet/Home#7068_

**Comment by GanesanRengasamy** [comment]
Could you please suggest the solution regarding this?

**Comment by espenh** [comment]
Try upgrading to version 1.8.2 or newer.

If you check out the release notes for 1.8.2 (https://github.com/bower/bower/releases/tag/v1.8.2), you'll see that it says:

> Migrate registry url from http://bower.herokuapp.com to https://registry.bower.io
>It is so we leverage CDN and offload Heroku instance reducing costs.

**Comment by mhintzke13** [comment]
I find it bizarre that a _patch_ level change included breaking changes :(

**Comment by joo92** [comment]
Hi @espenh ,

I have updated bower version. but still am facing same issue in Visual Studio which reported above.
>>>
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\cmd;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\bin
<<<

Could you please help me to resolve this issue?

Regards,
Dheepa Kumar

**Comment by MAB3** [comment]
Hi @joo92, 

were you able to figure this problem out? I'm currently stuck on the same dilemma.

**Comment by girishgodage** [comment]
I have created following file .bowerrc Which help me resolve the dependancy

{
  "registry": "https://registry.bower.io",
  "directory": "wwwroot/lib"
}

**Comment by cutefrank** [comment]
Hi @girishgodage ,
Thanks, it works for me.

**Comment by mandarexceptionaire** [comment]
Thanks @girishgodage

**Comment by sheerun** [comment]
bower.herokuapp.com registry is deprecated and not available, please update bower or update .bowerrc to have { "registry": "https://registry.bower.io" }
