### ISSUE TITLE
Discussion: Migration path for AngularJS app

### ISSUE THREAD

**Issue by aarjithn** [bower/bower#2520]
With bower getting deprecated, we are coming to end of the bower + grunt/gulp + angularjs ecosystem. There would be many angular apps, for eg those scaffolded by popular generator-angular or generator-m-ionic that has a similar workflow

- bower for frontend Dependencies
- grunt / gulp as task runner
- Wiredep to wire dependencies from main field to index.html
- Angular Dependency Injection to modularise code

Migrating from first two is fairly well documented and popular choice is now to go with npm and web pack. 
The next are bit challenging, when there is a large existing codebase as this requires extensive changes to the app code itself.

- Angular 1 is designed not with es6 modules in mind
- Inorder to work with es6 modules, we need to add the overhead of babel
- There is not much documentation to use many components, say ui-router with es6 modules
- Most of the angularjs - webpack tutorials are written using es6 classes

So, how do we go about converting an existing codebase of angular 1 with bower? Is there a way to avoid heavy rework to the app source code. These are few options, which is recommended?

1 - Migrate bower / grunt to npm and web pack. Update angular 1 codebase to work with es6 modules.
2 - Option 1 is not worth the effort, scratch current setup and migrate to angular 5
3 - Take control of bower_components, manually download libs and point to the files (good ol’ days)

Any other suggestions?

**Comment by sheerun** [comment]
You can migrate to yarn and still use es5 dependencies, yarn is able to install non-npm github repositories. You can use bower-away tool to migrate.

**Comment by sheerun** [comment]
Also it might be you can use Parcel for bundling your project instead of gulp, grunt or webpack but I didn't try it yet with bower-style dependencies. Maybe give it a try

**Comment by aarjithn** [comment]
Good suggestion on Parcel. Seems the least disruptive way to migrate.

Found a nice starter project here - https://github.com/edm00se/modernize-ng1
