### ISSUE TITLE
Prerelease versions are incorrectly included into caret ranges.

### ISSUE THREAD

**Issue by SomeoneToIgnore** [bower/bower#2522]
**Output of `bower -v && npm -v && node -v`:**

```
1.8.4
6.1.0
v8.11.1
```

**Steps to reproduce the issue:**

1. Have a package with prerelease versions for some minor version and no stable releases of that minor version.
For instance, `vaadin-button` (https://github.com/vaadin/vaadin-button/releases) has currently `2.1.0-alpha2` and `2.1.0-alpha1` prerelease versions and no other version that starts with `2.1.`.

2. Add it into `bower.json` with range on the minor version mentioned above:
```
{
  "name": "test-range",
  "dependencies": {
    "vaadin-button": "^2.1.0"
  }
}
```

3. Run `bower i`

**Describe the results you received:**

`vaadin-button#2.1.0-alpha2` version is installed.

**Describe the results you expected:**

No version should be installed, `2.1.0-alpha2` does not belong to the range `^2.1.0`

**Additional information:**

I did not find any `^` description in bower.json specs, but had found the one in node specs:
https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004
> ^1.2.3 := >=1.2.3 <2.0.0

Semver explicitly states in https://semver.org/#spec-item-11 that 
> 1.0.0-rc.1 < 1.0.0

In our case that means that
* `^2.1.0 := >=2.1.0 <3.0.0`
* `2.1.0-alpha2 < 2.1.0`

Hence `2.1.0-alpha2` version does not belong to `^2.1.0` range and should not be resolved.

Most probably the bug is caused by `semver` library that is used in `bower`: it is of version `2.3.2` in the project and the following snippet returns `true`:
```
const semver = require('semver');
semver.satisfies('2.1.0-alpha2', '^2.1.0'); // true
```

Latest `semver` version, `5.5.0` returns `false` for the same snippet.

I've tried updating `semver` in the project but got 6 tests failing.
If you approve that the issue is worth investigating and releasing a new `bower` version, I can investigate the test failures more deeply.

**Comment by sheerun** [comment]
This is unfortunate, but we can't change this as it's very much a breaking change :/
