### ISSUE TITLE
bower install error with new registry "https://registry.bower.io"

### ISSUE THREAD

**Issue by brucewar** [bower/bower#2523]
**Output of `bower -v && npm -v && node -v`:**

```
bower: 1.8.4
npm: 5.6.0
node: v8.11.3
```

**Additional environment details (proxy, private registry, etc.):**
registry: https://registry.bower.io

**Steps to reproduce the issue:**

1.bower install

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/4013475/42549162-736a8c4c-84fd-11e8-8256-d322d7236cf7.png)

**Describe the results you expected:**
install success

**Comment by sheerun** [comment]
Works for me. You can try to change to https://components.bower.io in .bowerrc if you're behind corporate proxy that doesn't like Cloudflare

**Comment by territorial** [comment]
> Works for me. You can try to change to https://components.bower.io in .bowerrc if you're behind corporate proxy that doesn't like Cloudflare

`echo '{"registry": "https://components.bower.io","directory": "wwwroot/lib"}' > .bowerrc `
