### ISSUE TITLE
How to publish multiple bower packages by single repository

### ISSUE THREAD

**Issue by GanesanRengasamy** [bower/bower#2525]
Hi All,

I have github repository which is forked from some another collaborator. In this repository I have publish the 2 NPM packages with the same repository with just add the component folder with packages.json file. But, I didn't achieve this same with add the bower.json in the same location where packages.json available. 

![image](https://user-images.githubusercontent.com/16695209/44654566-c324cb80-aa0f-11e8-901e-e5cc3d6c1a28.png)

I  have faced the below installation problem after add the bower.json file. 

![image](https://user-images.githubusercontent.com/16695209/44654516-9bcdfe80-aa0f-11e8-86eb-db74d7659b94.png)

Please help me to how can I achieve this with bower.json file? and what are the steps to publish multiple bower packages by using the single repository like NPM?.

Thanks,
Ganesan R.

**Comment by GanesanRengasamy** [comment]
Could you please suggest the solution regarding this?

**Comment by vadivel1234** [comment]
Could anyone please suggest a solution for this? Due to this, we didn't start the bower publish for our latest Service Pack release?

**Comment by sheerun** [comment]
It's not possible, and never was. Bower can only install one package per repository, sorry
