### ISSUE TITLE
How to caught the bower install error in shell

### ISSUE THREAD

**Issue by theodore3131** [bower/bower#2526]
**Output of `bower -v && npm -v && node -v`:**

```
(paste your output here)
```

**Additional environment details (proxy, private registry, etc.):**

**Steps to reproduce the issue:**

1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information:**
I want to catch the bower install error, but seems that I cannot test it with 
`if [ bower install -q ]` as it always returns false

**Comment by sheerun** [comment]
sorry, not enough details to reproduce it, bower works fine for me
