### ISSUE TITLE
.bowerrc hooks (preinstall and postinstall) not working when installing repos as dependency

### ISSUE THREAD

**Issue by asingh12541** [bower/bower#2529]
.bowerrc hooks (preinstall and postinstall) not working when installing repos as dependency

.bowerrc File

```
{
    "cwd": "./",
    "scripts": {
        "preinstall": "npm run replace" ,
        "postinstall": "bower install"
    }
}
```

P.S. I'm on OS 10.9.2 with:

```
node -v
v8.11.1
npm -v
5.6.0
bower -v
1.8.4
```

**Comment by sheerun** [comment]
This correct, .bowerrc is supported only for applications, not their dependenies. This is security feature
