### ISSUE TITLE
canvg#1.5.3 ENORESTARGET No tag found that was able to satisfy 1.5.3

### ISSUE THREAD

**Issue by vuvinay23** [bower/bower#2530]
bower angular#1.7.5                               cached https://github.com/angular/bower-angular.git#1.7.5
bower angular#1.7.5                             validate 1.7.5 against https://github.com/angular/bower-angular.git#1.7.5
bower angular-data-grid#*                        extract archive.tar.gz
bower angular-data-grid#*                   invalid-meta for:C:\Users\SYSGAI~1\AppData\Local\Temp\DESKTOP-JG1K8A9-vinay kumar\bower\0eb9084a5e186f467edc81cb6881812d-10900-1zCX5d\bower.json
bower angular-data-grid#*                   invalid-meta The "description" is too long, the limit is 140 characters
bower angular-data-grid#*                       resolved https://github.com/angular-data-grid/angular-data-grid.github.io.git#2aab407637
bower canvg#1.5.3                           ENORESTARGET No tag found that was able to satisfy 1.5.3

Additional error details:
Available versions in https://github.com/shprink/canvg.git: 1.3.0

getting above error with bower install

**Comment by lennartpedersen** [comment]
I had a similar issue, which appeared to be because of jspdf being updated and having canvg as a dependency. 
I solved it by setting the jspdf version in the bower.json to a older one - maybe you have a similar issue?

**Comment by SirajKakeh** [comment]
> I had a similar issue, which appeared to be because of jspdf being updated and having canvg 1.5.3 as a dependency.
> I solved it by setting the jspdf version in the bower.json to a older one - maybe you have a similar issue?

@lennartpedersen much love man

**Comment by niksharma1997** [comment]
can anyone send the bower.json file with the version setup?
Thanks in advance

**Comment by silviotroia** [comment]
The solution is to downgrade jspdf to 1.4.1
