### ISSUE TITLE
cannot install packages tried everything

### ISSUE THREAD

**Issue by benag** [bower/bower#2535]
Is it duplicate? hell yes
did i find a solution ? No
did someone is the discord channel managed to help? no

# BUG REPORT

1.8.7
3.5.2
8.10.0

```
cannot bower install see attached 
https://drive.google.com/file/d/1dzrjIxfag3p-zFWVrasmO1OcDaHbYSj2/view?usp=sharing
```

**Additional environment details (proxy, private registry, etc.):**

**Steps to reproduce the issue:**

1.
2.
3.

**Describe the results you received:**

stuck

**Describe the results you expected:**
finish

**Additional information:**
never happened to me before the last 5 years

**Comment by sheerun** [comment]
This issue is now stale, closing
