### ISSUE TITLE
Bower package 'dagre' incomlete

### ISSUE THREAD

**Issue by ErikSteNL** [bower/bower#2536]
Hey,

Not sure if this is the repo to create an issue in but here it goes.
The package 'dagre' when downloaded with bower does not contain some files.
https://github.com/dagrejs/dagre
This repo contains: dist/dagre.js and /dist/dagre.min.js but when imported with bower these are missing.

Can I modify this somehow myself or could someone look at this?
Thanks!

**Comment by sheerun** [comment]
bower info dagre says this packages comes from https://github.com/cpettitt/dagre

**Comment by sheerun** [comment]
If you look at bower.json of this package it ignores these files:

  "ignore": [
    ".*",
    "README.md",
    "CHANGELOG.md",
    "Makefile",
    "browser.js",
    "dist/dagre.js",
    "dist/dagre.min.js",
    "index.js",
    "karma*",
    "lib/**",
    "package.json",
    "src/**",
    "test/**"
  ],

**Comment by ErikSteNL** [comment]
Yes, that's it, thank you for the response. I will see what I can do on the dagre repo.
Thank for your help @sheerun
