### ISSUE TITLE
Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by burakhanalkan** [bower/bower#2537]
bower install is failing with JavaScript heap out of memory error.

**Output of `bower -v && npm -v && node -v`:**

1.8.8
6.4.1
v10.15.3

**Additional environment details (proxy, private registry, etc.):**

**Steps to reproduce the issue:**

1. bower install

**Describe the results you received:**

<--- Last few GCs --->

172105 ms: Scavenge 1392.5 (1423.7) -> 1391.6 (1424.2) MB, 3.3 / 0.0 ms  (average mu = 0.104, current mu = 0.035) allocation failure 
172113 ms: Scavenge 1392.5 (1424.2) -> 1391.7 (1424.7) MB, 3.2 / 0.0 ms  (average mu = 0.104, current mu = 0.035) allocation failure 
172120 ms: Scavenge 1392.6 (1424.7) -> 1391.8 (1425.2) MB, 3.2 / 0.0 ms  (average mu = 0.104, current mu = 0.035) allocation failure 

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame Security context:  <JSObject>
    1: filterValues [/usr/local/lib/node_modules/bower/lib/node_modules/mout/object/filter.js:~8] 
    2: arguments adaptor frame...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 5: v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/local/bin/node]
 6: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 7: v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 9: v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
10: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/usr/local/bin/node]
11: v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
12: 
13: 
Abort trap: 6

In another attempt, **mout** package is again seen at the stack trace.

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame Security context: <JSObject>
    1: forIn [/usr/local/lib/node_modules/bower/lib/node_modules/mout/object/forIn.js:~29] 
    2: arguments adaptor frame: 2->3
    3: toData [/us...

**Comment by burakhanalkan** [comment]
I'll close this issue for further investigation on my local environment.

**Comment by AnastasiaD** [comment]
> I'll close this issue for further investigation on my local environment.

Hi, what was the solution?

**Comment by burakhanalkan** [comment]
For us, the issue has gone after fixing the code piece causing huge memory consumption. However, if there is need to increase memory allocation it's possible to do it with the following command:

``node --max_old_space_size=2000  `which npm` start``

Please also check this: https://github.com/npm/npm/issues/12238
