### ISSUE TITLE
Permission denied .config/configstore/bower-github.json - magic formula does not work!

### ISSUE THREAD

**Issue by taokann** [bower/bower#2547]
Hi, I have exactly the same issue as #2262 , but the magic command that solved the problem for everyone does not work for me...
I even tried chmod 777 the file, and run as root: access denied.
Can you help me please?

**Comment by sheerun** [comment]
It's not easy to to fix such issue by discussing it. You'd need to find someone to help you on debug this and fix it on your computer. chmod and running as root should fix it, I cannot tell why it's not working
