### ISSUE TITLE
Bower Install returning ENOTFOUND

### ISSUE THREAD

**Issue by SketchBookkeeper** [bower/bower#2556]
**Output of `bower -v && npm -v && node -v`:**

```
1.8.8
6.13.4
v12.14.0
```

**Steps to reproduce the issue:**
1: `bower install polymer-decorators#2.1.0`

**Describe the results you received:**
```
bower polymer-decorators#2.1.0  cached https://github.com/Polymer/polymer-decorators.git#2.1.0
bower polymer-decorators#2.1.0         validate 2.1.0 against https://github.com/Polymer/polymer-decorators.git#2.1.0
bower                                 ENOTFOUND Package Polymer/polymer=Polymer/polymer not found
```

**Describe the results you expected:**
I ran this command on Dec 18th, 2019 and bower was able to install polymer-decorators. 

**Additional information:**
I noticed that polymer-decorators is using a different syntax for it's dependencies list.
[bower.json](https://github.com/Polymer/polymer-decorators/blob/v2.1.0/bower.json)
```
  "dependencies": {
    "Polymer/polymer": "^2.4"
  }
```
As opposed to this :
```
  "dependencies": {
    "polymer": "polymer/polymer#^2.4.0"
  }
```
 Thank you!

**Comment by sheerun** [comment]
Please raise issue to polymer-decorators then

**Comment by SketchBookkeeper** [comment]
Thanks for getting back to me. Just for clarification, which way is bower expecting. Docs use the syntax that polymer-decorators is using. https://github.com/bower/spec/blob/master/json.md
