### ISSUE TITLE
Bower getting wrong tag version

### ISSUE THREAD

**Issue by CoderSquirrel** [bower/bower#2557]
I'm using bower in a private lib. This lib has 2 branchs, the master, with x.0.0 version's tag (it's a company pattern to have on master only the major version)  and the dev's branch for new frature and experiments with (current).y.z. tags.

The versions where we use in productions systems are only the X.0.0, the x.y.z versions are only use in testing new features and when read it goes to a pr to master.

In both of then we used tags.

Current we have ours 2.0.0 on master, the one everyone should be using. And we have the 2.x.x where some dev are implementing new features. Eeach new feature has a tag, 2.1.0, 2.2.0 and go on.

On the web project we haven't define the branch , only the repo url (`git@bitbucket.xxxxxx/weCoolDiretivas.git`), and the master is the main branch for the repository.

When we try to update some systens from the 1.0.0 to the 2.0.0 version (the tag in the master branch), bower is instaling the 2.2.0 tag version, from the dev branch.

Can we set the global bower to use the master branch? 
Or, is this a bug in bower to get a a than from outside of the main branch?

**Comment by sheerun** [comment]
Bower doesn't look at branches at all, it only uses tags to resolve versions.

I recomment you to use beta semver releases like 2.1.0-beta this way bower will install 2.0.0 until you decide to release and tag 2.1.0 version

**Comment by CoderSquirrel** [comment]
Thank you @sheerun , that solved my problem
