### ISSUE TITLE
Registering bower package names is not supported anymore

### ISSUE THREAD

**Issue by jalbam** [bower/bower#2558]
Hello,

I am trying to register a new Bower package. Once it asks this:

> Registering a package will make it installable via the registry (https://registry.bower.io), continue? 

I agree answering "Y", but I get the following error just after a few seconds:

> EUNKNOWN Unknown error: 500 - Registering bower package names is not supported anymore. You can install any bower package on github with command like "bower install jquery/jquery-dist --save"

Was the register support really dropped or it is an issue?

Thank you very much in advance!

Cheers,
 Joan

**Comment by sheerun** [comment]
Yes it was dropped

**Comment by jalbam** [comment]
Thank you for your fast reply! As I could not find the error anywhere and the official web site still talks about registering packages, I was wondering whether it was due to the big size of the package or not...

**Comment by sheerun** [comment]
Good point, we'll update website docs. Thank you!

**Comment by jalbam** [comment]
Thanks to you! Best regards

**Comment by sheerun** [comment]
Docs are now updated
