### ISSUE TITLE
bower sinonjs#~1.7.3: ENORESTARGET No tag found that was able to satisfy ~1.7.3

### ISSUE THREAD

**Issue by sameerkhan662** [bower/bower#2559]
I am not able to solve this issue since the dependency is missing as owner removed all old dependency and kept only two recently [https://github.com/blittle/sinon.js](sinonjs dependency).
I have removed it completely then also picking the same thing. Also, I have posted this on stackoverflow yet no help.

[https://stackoverflow.com/questions/60428781/bower-dependency-picking-wrong-link](stackoverflow question link)

Please tell me why bower is picking something which is not in bower.json and already deleted I have also cleared cache

**Comment by sheerun** [comment]
You can point to repositories directly like described on https://bower.io/docs/creating-packages/
