### ISSUE TITLE
Bower update of a single package updates all

### ISSUE THREAD

**Issue by euge** [bower/bower#256]
Heya,

I have a component.json file that looks like:

``` javascript
{
  "name": "b",
  "version": "1.0.0",
  "dependencies": {
    "jquery": "1.8.3",
    "demo": "git@github.com:euge/demo.git"
  }
}
```

When I run `bower update demo`, I see the following

```
bower cloning git@github.com:euge/demo.git
bower cloning git://github.com/components/jquery.git
bower cached git@github.com:euge/demo.git
bower fetching demo
bower cached git://github.com/components/jquery.git
bower fetching jquery
bower checking out jquery#1.9.1
bower copying /Users/euge/.bower/cache/jquery/cf68c4c4e7507c8d20fee7b5f26709d9
bower checking out demo#60eef655c0100bc7dfb63acaab6e8d5e4ee0887e
bower copying /Users/euge/.bower/cache/demo/b9a57fca7e6f588769b0b061b1ed5071
bower installing demo#60eef655c0100bc7dfb63acaab6e8d5e4ee0887e
bower installing jquery#1.9.1
```

But my jQuery dependency is set to 1.8.3, so why would update of demo cause jQuery to bump to 1.9.1?

I'm using bower 0.7.0.

Thanks!

Euge

**Comment by vikbez** [comment]
+1 :+1: 
this is really annoying;
I was in the train, tethered, needed only one package to continue coding but bower failed continuously resolving on some other package for unknown reason.

I wish only one package installation method worked.

bower 1.3.12 on OSX

**Comment by sheerun** [comment]
Without version locking this feature doesn't make much sense. Please contribute to #1592

**Comment by dickeylth** [comment]
+1
Why this bug lasts so long?...

**Comment by trisys3** [comment]
I s. I now have bower versiproblemseem to only be having this problem when I install a dependent package, which would make sense in a nested dependency structure like npm but not a flat one like bower. I am not sure if this is the same way it was when I commented before. I have bower version 1.3.12.

**Comment by sheerun** [comment]
The correct behavior is as @nschloe pointed out:

1. If no arguments are passed to `bower update`, it updates packages in `bower_components` that don't match the specs in bower.json (basically `bower install`, maybe without extra downloads). Also update packages in `bower_components` that are not listed in `bower.json`
2. If arguments are passed, limit updated packages.

Failing tests can be added to:
https://github.com/bower/bower/blob/master/test/commands/update.js

**Comment by sheerun** [comment]
@prappo Why did you close it?

**Comment by contolini** [comment]
@albertinadx Are you working on this issue? If you're not, let me know, and I'll hack on it later today.

**Comment by contolini** [comment]
Satisfied by #2070.

**Comment by erquhart** [comment]
@contolini I'm on bower 1.7.9 and am still experiencing this issue. I run `bower update <package>`, and an additional package gets updated as well. The additional package is not a direct dependency of the package I'm trying to update.

Is there any known reason why this would be happening?

**Comment by erquhart** [comment]
Found it:
https://github.com/bower/bower/commit/d3eef5772af9d2c06036abe84f932b6a7d9e9ca7

@sheerun it looks like you reverted this fix, but there's no reason given anywhere, and the changelog doesn't acknowledge it. Can we re-open this issue to continue the discussion?

**Comment by sheerun** [comment]
This is true, I had to revert because of #2097

**Comment by lmmfranco** [comment]
Still happens in 1.8.
I'm having a problem when installing all dependencies at once, so I was trying to install one at a time, but I cannot achieve that because of this issue.

**Comment by sheerun** [comment]
Now that Bower is not developed anymore, I'll close this issue. The update command never worked very well, and in fact even npm's and yarn's update also suffers from many issues. The solution is to use proper version ranges in `bower.json` and use `bower install` instead of `bower update`.
