### ISSUE TITLE
[bower-config] v1.4.2 breaks wct if used with `bower-alternative-source-resolver` 

### ISSUE THREAD

**Issue by armujahid** [bower/bower#2573]
**Output of `bower -v && npm -v && node -v`:**

```
1.8.8
6.4.1
v8.16.2
```

**Additional environment details (proxy, private registry, etc.):**
bower-alternative-source-resolver is being used e.g. 
```json
{
    "resolvers": ["bower-alternative-source-resolver"],
    "alternateSources": [
        {
            "owner": "AbdulRauf",
            "url": "https://github.com/twbs/${package}.git${version}"
        }
    ]
}

```

**Steps to reproduce the issue:**

run `wct` with `.bowerrc` containing `bower-alternative-source-resolver`
Issue example: https://github.com/armujahid/bower-config-wct-alternateSources-issue/tree/bower-config-1.4.2issue

**Describe the results you received:**
Following error was shown
`Error: Environment variable used in .bowerrc is not defined: ${package}`

**Describe the results you expected:**
wct tests should run.

**Additional information:**
If I lock `bower-config` version to 1.4.1 then everything works as expected.
Fix example: https://github.com/armujahid/bower-config-wct-alternateSources-issue/tree/bower-config-1.4.1-fix

**Comment by sheerun** [comment]
This issue got stale. If this is still relevant, please create another one

**Comment by armujahid** [comment]
Yes this issue is still relevant. [bower-config v1.4.2](https://www.npmjs.com/package/bower-config) released just a day ago and has broken our builds.

**Comment by sheerun** [comment]
sorry I marked this as stale by mistake

**Comment by sheerun** [comment]
I can reproduce this issue

**Comment by sheerun** [comment]
It seems this actually fixes behavior of expanding env variables in .bowerrc https://bower.io/docs/config/ (you use env expansion in `https://github.com/twbs/${package}.git${version}`), but as I understand this is breaking behavior..

I guess we can meet in the middle and skip expansion instead of throwing an error if env variable doesn't exist

**Comment by sheerun** [comment]
1.4.3 should be ok

**Comment by armujahid** [comment]
Thanks that was really quick :)
