### ISSUE TITLE
Bower1.8.8 has a version of handlebars that caused Prototype Pollution.

### ISSUE THREAD

**Issue by nli8n** [bower/bower#2580]
Bower1.8.8 has a version of handlebars that caused Prototype Pollution.
Please upgrade handlebars to 4.5.3

**Comment by sheerun** [comment]
Upgrade of handlebars will be released in 1.8.9 soon

**Comment by nli8n** [comment]
@sheerun   : is bower going to release new version 1.8.9??

**Comment by sheerun** [comment]
Yes, today
