### ISSUE TITLE
Discord invite expired

### ISSUE THREAD

**Issue by zrhoffman** [bower/bower#2581]
The [Discord invite in `CONTRIBUTING.md`](https://github.com/bower/bower/commit/aa6b51edc0#diff-6a3371457528722a734f3c51d9238c13R21) has expired.

**Output of `bower -v && npm -v && node -v`:**
```shell
1.8.8
6.14.5
v14.2.0
```

**Additional environment details (proxy, private registry, etc.):**
Discord desktop client

**Steps to reproduce the issue:**

1. Open Discord
2. Add a server
3. Paste invite

**Describe the results you received:**
Recieved message:
> (The invite is invalid or has expired)

**Describe the results you expected:**
Joining the Bower Discord

**Comment by sheerun** [comment]
we discontinued discord server because no one was using it, I'll remove reference
