### ISSUE TITLE
Is the project still maintained?

### ISSUE THREAD

**Issue by THETCR** [bower/bower#2587]
Even though the README mentions that the project is still being maintained, is it actually still maintained?

It has been almost two years since the last release and half a year since the last commit. (most commits are dependency updates and documentation).

**Comment by sheerun** [comment]
Are there some issues you have?

**Comment by THETCR** [comment]
We are currently slowly migrating and the argument was presented that the migration process doesn't have to be done in a hurry, since bower is still maintained as stated by the documentation.

But all things considered it was best to ask if this is actually still the case?

**Comment by sheerun** [comment]
We are keeping servers online and fixing critical bugs, nothing more. It's best for you to migrate, even if bower is maintained, because it doesn't have lockfile like npm or yarn, which means your application at some point won't install

**Comment by THETCR** [comment]
Fair enough. Only the pace of the migration is a discussion point right now.  Does this mean there won't be a release with updated dependencies like minimist and handlebars?

**Comment by sheerun** [comment]
I've reviewed them and they don't affect security or functionality of Bower. Updates usually mean breaking something, and I don't want to make unnecessary ones. For example new handlebars or minimist could break compatiblity with Node 0.10 which Bower is still compatible with
