### ISSUE TITLE
Failed to Install Bower Packages - git exit code 128

### ISSUE THREAD

**Issue by marcoonzo** [bower/bower#2588]
Hi everyone,
I'm trying to install some packages through bower but i'm having some problem.
When i execute bower install, this happens:
Failed to execute "git ls-remote --tags --heads https://github.com/blueimp/JavaScript-Load-Image.git", exit code of #128 error: RPC failed; curl 18 transfer closed with outstanding read data remaining fatal: expected flush after ref listing.

I tried many solution, like changing my .gitconfig like this:
- git config --global http.postBuffer 524288000
- git config --global url."https://".insteadOf git://

I'm on Mac. OS: Catalina 10.15.7

**Comment by sheerun** [comment]
Most likely some network error on your side. If this still happens, please show bower.json you're using and bower version
