### ISSUE TITLE
error since bower update to 1.8.11

### ISSUE THREAD

**Issue by rpo-fr** [bower/bower#2591]
Hi,
Since bower is updated to 1.8.11,
I have this error:

     [exec] module.js:550
     [exec]     throw err;
     [exec]     ^
     [exec]
     [exec] Error: Cannot find module 'qs'
     [exec]     at Function.Module._resolveFilename (module.js:548:15)
     [exec]     at Function.Module._load (module.js:475:25)
     [exec]     at Module.require (module.js:597:17)
     [exec]     at require (internal/module.js:11:18)
     [exec]     at Object.<anonymous> (/usr/lib/node_modules/bower/lib/node_modules/request/lib/querystring.js:3:10)
     [exec]     at Module._compile (module.js:653:30)
     [exec]     at Object.Module._extensions..js (module.js:664:10)
     [exec]     at Module.load (module.js:566:32)
     [exec]     at tryModuleLoad (module.js:506:12)
     [exec]     at Function.Module._load (module.js:498:3)

**Comment by eroSilva** [comment]
I have the same problem. 

Sorry by question but, a fix to this problem will be merged still today?

**Comment by krazyjakee** [comment]
Another related issue: https://github.com/bower/bower/issues/2590

**Comment by eroSilva** [comment]
> Another related issue: #2590

Thanks :)

**Comment by eburton** [comment]
My team have been facing this issue since the latest update, looks to be a missing dependency. If anyone needs to solve this urgently before a fix is pushed, simply install the "qs" package globally via `npm i qs -g`.

**Comment by sheerun** [comment]
I'm workingon resolving this. In the meantime 1.8.8 is marked as latest version so it should install by default

**Comment by sheerun** [comment]
It should be fixed in 1.8.12 which is now marked as latest. Sorry for the trouble, we need to fight against new npm versions each time we upgrade becase we bundle all dependencies
