### ISSUE TITLE
Cloning into 'discover'... fatal: unable to access 'https://github.com/leebaird/discover.git/': Could not resolve host: github.com

### ISSUE THREAD

**Issue by tommy123123123** [bower/bower#2604]
Cloning into 'discover'...
fatal: unable to access 'https://github.com/leebaird/discover.git/': Could not resolve host: github.com

Please help I need to clone my things and that says

**Comment by sheerun** [comment]
Github has temporary problems, it's not Bower's issue

**Comment by tommy123123123** [comment]
oh okay thank you
