### ISSUE TITLE
Git clone not working on kali linux 1.unable to access 2ssh: Could not resolve hostname github.com: Temporary failure in name resolution

### ISSUE THREAD

**Issue by tommy123123123** [bower/bower#2606]
please help me I have 2 days working and I cant Do a git clone can somebody help me 

Cloning into 'Storm-Breaker'...
ssh: Could not resolve hostname github.com: Temporary failure in name resolution
fatal: Could not read from remote repository

and 2 problem

 https://github.com/ultrasecurity/Storm-Breaker.git                                                                                                                                                                         1 ⨯
Cloning into 'Storm-Breaker'...
fatal: unable to look up github.com (port 9418) (Temporary failure in name resolution)

**Comment by sheerun** [comment]
It's temporary failure on github side or  DNS resolver in your infrastructure, not a Bower's issue

**Comment by tommy123123123** [comment]
but how many days i  need to wait

**Comment by sheerun** [comment]
github is working for me so it's probably DNS resolver in your infrastructure or issues with firewall. this problem won't resolve itself, you need to debug this somehow. either way it's not Bower's issue so it's not a place to get help. most likely `git clone https://github.com/ultrasecurity/Storm-Breaker.git` won't work for you as well and it's just pure git

**Comment by Phalguni87** [comment]
So what do we do?
