### ISSUE TITLE
git:// no longer supported by github

### ISSUE THREAD

**Issue by oliverfoster** [bower/bower#2610]
I'm not quite sure how to log this, so apologies.

Error: Failed to execute "git ls-remote --tags --heads git://github.com/owner/repo.git", exit code of #128
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

**Comment by fabioebt** [comment]
https://github.com/bower/bower/pull/2612

**Comment by sheerun** [comment]
Released as bower 1.8.14, thank you!
