### ISSUE TITLE
CERT_HAS_EXPIRED Request to https://registry.bower.io/packages/jquery failed: certificate has expired

### ISSUE THREAD

**Issue by hajdukda** [bower/bower#2623]
bower jquery#1.10.2 

Seems the certificate is expired - are there any actions taken to renew ?

Edit.
notBefore=Apr 24 01:43:54 2023 GMT Seems certificate was rotated today, so this app should already work with new certificate. Why it does not work with the new certificate ?

My assumption is that if you move your pc datetime by one day into the future suddenly it will start working. Too lazy to test.
But if someone has a moment to verify how stupidly this app is written - feel free to do so.

**Comment by nataliasver** [comment]
I have the same issue!
Just looking at this old one https://github.com/bower/bower/issues/2608
Other people are having trouble with the same certificate problem.
Waiting for a solution =(

**Comment by nataliasver** [comment]
I tried changing the date on at least my pc locally, but doesn work either. I think maybe its checked with other timezone?
Also tried with "strict-ssl: false" that´s mention on the other issue, and that works, but it isn´t a viable solution to deploy.

**Comment by SureshGedela** [comment]
I am getting the same error

**bower json3#3.3.2**  CERT_HAS_EXPIRED Request to https://registry.bower.io/packages/json3 failed: certificate has expired

**Comment by sheerun** [comment]
Certificate seems fine for me, maybe you are MITM by spyware or something. I don't know. Try following commands on urls to debug:

```
curl -v https://registry.bower.io/packages/json3
```

```
echo | openssl s_client -connect registry.bower.io:443 -servername registry.bower.io | openssl x509 -noout -text
```

```
echo | openssl s_client -connect registry.bower.io:443 -servername registry.bower.io -showcerts
```

**Comment by bryant-finney** [comment]
I was able to reproduce this on some older versions of `node`:

```sh
❯ for i in `seq 6 14`; do
    printf 'node:%s\t%s\n' "$i" $(
      docker run --rm "node:$i" /bin/sh -c "npm i -g bower &&
        bower install --allow-root jquery" 2>&1 | grep -o CERT_HAS_EXPIRED
    )
  done
node:6  CERT_HAS_EXPIRED
node:7  CERT_HAS_EXPIRED
node:8  CERT_HAS_EXPIRED
node:9  CERT_HAS_EXPIRED
node:10
node:11
node:12
node:13
node:14
```

**Comment by NguyenKhacTung** [comment]
I also got it with node v8
Shall we waiting for a solution from Github?

**Comment by scan0qr** [comment]
> I also got it with node v8 Shall we waiting for a solution from Github?

Please let me know if you find valid solution instead of just disabling ssl

**Comment by scan0qr** [comment]
> > I was able to reproduce this on some older versions of `node`:
> > ```shell
> > ❯ for i in `seq 6 14`; do
> >     printf 'node:%s\t%s\n' "$i" $(
> >       docker run --rm "node:$i" /bin/sh -c "npm i -g bower &&
> >         bower install --allow-root jquery" 2>&1 | grep -o CERT_HAS_EXPIRED
> >     )
> >   done
> > node:6  CERT_HAS_EXPIRED
> > node:7  CERT_HAS_EXPIRED
> > node:8  CERT_HAS_EXPIRED
> > node:9  CERT_HAS_EXPIRED
> > node:10
> > node:11
> > node:12
> > node:13
> > node:14
> > ```
> 
> Switching to newer nodeJS fixes the issue, thank you for validating which versions are broken. Time to update legacy stuff boyz, cheers.

Can you please check if 16 is fine? We are getting same error for node 16.

**Comment by hajdukda** [comment]
Another option I've seen was to run "bower cache clean"

**Comment by sheerun** [comment]
Solution is to use `NODE_OPTIONS=--use-openssl-ca`, and true solution is to finally let go of Bower https://github.com/bower/registry/issues/304#issuecomment-1521604693
