### ISSUE TITLE
Bower 0.8.5 seems to be stuck

### ISSUE THREAD

**Issue by xseignard** [bower/bower#314]
I updated from 0.8.0 (I guess) or later to 0.8.5 and bower seems stuck when i do a simple bower install. It happens on my machine and with my cloudbees hosted jenkins.
I tried to do a `bower clean-cache`, a `bower install --force` and a `rm -rf ~/.bower` with no luck.

It always gets stuck on copying instructions such as :

```
bower copying /home/bigx/.bower/cache/require/34f0965def4ee39276726c265c9162b6
```

or any other lib, there is no pattern.

I've got the following when I try to reinstall bower (only on my machine not on cloudbees):

```
npm WARN unmet dependency /usr/lib/node_modules/modulus/node_modules/prompt/node_modules/winston requires pkginfo@'0.2.x' but will load
npm WARN unmet dependency /usr/lib/node_modules/modulus/node_modules/prompt/node_modules/pkginfo,
npm WARN unmet dependency which is version 0.3.0
```

And here is my component.json

```
{
    "dependencies": {
        "angular": "~1.0.5",
        "requirejs": "~2.1.4",
        "jquery": "~1.9.1",
        "angular-sanitize": "~1.0.5",
        "foundation": "http://foundation.zurb.com/files/foundation-3.2.5.zip",
        "less.js": "~1.3.3",
        "font-awesome": "~3.0.2"
    },
    "devDependencies": {
        "angular-mocks": "~1.0.5"
    }
}
```

Any idea? Any debug options?

Regards,

Xavier

**Comment by s3w47m88** [comment]
I'm still experiencing this issue. v0.10.26 on Ubuntu 12.04 and am unable to locate a solution. Initially I ran is as a user sudo su as root, and added the --allow-root option, then tried again as non-root without that option and it still hangs. The repo it's accessing is git://github.com/twbs/boostrap.git

**Comment by buccfer** [comment]
Have you generated your ssh public/private key and registered the public key in the github server already??? Maybe git is using ssh and the authentication is failing... 

Regards

**Comment by tmleeek** [comment]
just tried from visual studio code and still stucks , its also stuck in the terminal , i think this project is dead

**Comment by sheerun** [comment]
0.8.5 is not supported for a long time
