### ISSUE TITLE
Allow for custom component sources in .bowerc

### ISSUE THREAD

**Issue by dancras** [bower/bower#342]
I have a fork of the bower-angular and bower-angular mock repositories, with extra tags for the pre-release versions so that I can install them using bower. I attempted something like the following:

    {
      "dependencies": {
        "angular": "git://github.com/dancras/bower-angular.git#~1.1.3",
        "angular-mocks": "git://github.com/dancras/bower-angular-mocks.git#~1.1.3"
      }
    }

Angular mocks has its own dependency on angular, and currently it ignores the already installed angular version in favour of the one in the heroku registry. It will attempt to install a second version of angular which doesn't have my extra tag.

The ability to replace a third party library with your own fork is quite useful, for example for an urgent fix or feature while waiting for it to be added to a release. The new multiple endpoint functionality could be used to achieve this, but that seems more suitable for maintaining a large number of permanent dependencies.

My current solution is to add a registry to my .bowerrc:

    {
      "registry": {
        "angular": "git://github.com/dancras/bower-angular.git",
        "angular-mocks": "git://github.com/dancras/bower-angular-mocks.git"
      }
    }

Then modify the Source API so that endpoints defined in this local registry take highest priority:

    exports.lookup = function (name, callback) {

      if (config.registry && config.registry[name]) {
        callback(null, config.registry[name]);
        return;
      }

      // ... search endpoints

In my components.json I can go back to simply using:

    {
      "dependencies": {
        "angular": "~1.1.3",
        "angular-mocks": "~1.1.3"
      }
    }

Thoughts appreciated. Thanks

**Comment by sheerun** [comment]
It can be now achieved with `locate` method of [Pluggable Resolvers](http://bower.io/docs/pluggable-resolvers/) feature :) You can implement custom resolver that looks at the `sources` field in .bowerrc, returns `true` from `match` function when resolved dependency matches one of the sources, and write `locate` method that returns custom source. Hope you'll have time to implement it.
