### ISSUE TITLE
Quiet/Silent option for install/update

### ISSUE THREAD

**Issue by schickling** [bower/bower#343]
I think it would be nice to have options like

```
bower install --quiet
bower install --silent
```

like npm has.

**Comment by AbhiMatcha** [comment]
Hey, I want to run the command "bower install" in Jenkins build. As we know we need to select options while installing can anyone tell me what command I need to give in Jenkins so that it automatically selects the option and continue installation. 
Thanks in advance.

**Comment by sheerun** [comment]
afaik `--force`
