### ISSUE TITLE
Ability to specify tag regex

### ISSUE THREAD

**Issue by ProLoser** [bower/bower#405]
In continuation of thoughts from #8 and #24 I would like to propose a new solution to allowing people to NOT have to maintain multiple repos just to please bower.

Ideally, it would be nice if my project could simply have a bower branch or the ability to specify a branch. This way if a repo produces separate components, I could simply create multiple bower-branches for each produced component.

_However_, as we both know bower primarily uses tags (unless you use latest?) and tags are branch independent. This means that if you tag your source branches then these tags will show up in bower.
## Solution: Double Tagging

Perhaps instead people can create src-tags and build-tags? The build tags would be done off of a separate branch, while the src tags could be off their master(?) branch. If people could then specify regex pattern to filter tags they would then be able to only let the build-tags be accessible.
## New Thought: Encourage Practice Globally

WHILE writing this proposal I had a trivial revelation. WHY would I want to prevent people from switching to snapshots of my src rather than just snapshots of builds? Perhaps we should instead encourage across the community as a whole an entirely new paradigm! Create 2 sets of tags instead of maintaining 2 separate projects! Doing so would not only benefit bower's own consumption but also could potentially benefit many other git consumers!
## Example:

Develop in master and tag your src snapshots. Then switch to bower (build) branch, merge master, commit a new build, and tag your distribution version. Very easy to lump into a git task.

```
+ git repo
  + master (src) branch // build directory is ignored
    - tag: src1.0.x
    - tag: src1.1.x
  + bower (build) branch // build directory is committed
    - tag: v1.0.x
    - tag: v1.1.x
  + bower-subcomponent (angular-resource) branch
    - tag: resource-1.0.x
    - tag: resource-1.1.x
```

**Comment by maxlk** [comment]
@wibblymat @necolas 
I'm looking for best practices to publish a bower module.
I see that this issue was closed, but according to [docs](https://bower.io/docs/creating-packages/#register) bower still relies on github.
Does it mean that best practice is to maintain two different github repositories for development and publishing, or am I missing something?

**Comment by ProLoser** [comment]
Personally, I've completely abandoned bower these days and generally advocate against it. I've completely moved to browserify (or rollup) and have been much happier although I no longer publish pure frontend code anymore. Npm let's you publish uncommitted code.
