### ISSUE TITLE
bower install doesn't generate the components directory

### ISSUE THREAD

**Issue by nuweb** [bower/bower#414]
I was having a problem with 0.8.6, as it was not unzipping http://twitter.github.com/bootstrap/assets/bootstrap.zip. So I had uninstalled bower and re-installed it, with the intention that the unzipping problem would be resolved. But now, I see another problem, bower install doesn't generate the components directory at all and it doesn't throw an error.

Here's the component.json,
{
  "name": "AngularSeed",
  "version": "0.0.0",
  "dependencies": {
    "angular": "~1.0.6",
    "angular-resource": "~1.0.6",
    "angular-cookies": "~1.0.6",
    "angular-sanitize": "~1.0.6",
    "jquery" : "latest",
    "bootstrap" : "http://twitter.github.com/bootstrap/assets/bootstrap.zip",
    "modernizr": "~2.6.1",
    "requirejs": "latest"
  },
  "devDependencies": {
    "angular-mocks": "~1.0.6",
    "angular-scenario": "~1.0.6"
  }
}

Here's the log, after executing bower install,
bower install  
bower downloading http://twitter.github.com/bootstrap/assets/bootstrap.zip
bower cloning git://github.com/angular/bower-angular.git
bower cached git://github.com/angular/bower-angular.git
bower fetching angular
bower cloning git://github.com/components/jquery.git
bower cloning git://github.com/angular/bower-angular-resource.git
bower cloning git://github.com/angular/bower-angular-cookies.git
bower cloning git://github.com/angular/bower-angular-sanitize.git
bower cached git://github.com/components/jquery.git
bower fetching jquery
bower cached git://github.com/angular/bower-angular-resource.git
bower fetching angular-resource
bower cached git://github.com/angular/bower-angular-cookies.git
bower fetching angular-cookies
bower cached git://github.com/angular/bower-angular-sanitize.git
bower fetching angular-sanitize
bower cloning git://github.com/Modernizr/Modernizr.git
bower cached git://github.com/Modernizr/Modernizr.git
bower fetching modernizr
bower cloning git://github.com/jrburke/requirejs
bower cached git://github.com/jrburke/requirejs
bower fetching requirejs
bower cloning git://github.com/angular/bower-angular-scenario.git
bower cloning git://github.com/angular/bower-angular-mocks.git
bower cached git://github.com/angular/bower-angular-scenario.git
bower fetching angular-scenario
bower cached git://github.com/angular/bower-angular-mocks.git
bower fetching angular-mocks
bower redirect detected http://twitter.github.com/bootstrap/assets/bootstrap.zip
bower downloading http://twitter.github.io/bootstrap/assets/bootstrap.zip
bower checking out angular-cookies#v1.0.6
bower checking out angular-scenario#v1.0.6
bower checking out angular-resource#v1.0.6
bower checking out angular-sanitize#v1.0.6
bower checking out jquery#2.0.0
bower checking out angular-mocks#v1.0.6
bower checking out angular#v1.0.6
bower checking out requirejs#2.1.5
bower copying /Users/veeracs/.bower/cache/angular-cookies/661bd34ffe85aab6deffd7292f51d140
bower copying /Users/veeracs/.bower/cache/angular-scenario/58fadc8fe221a0569c61cd85ea4bec69
bower copying /Users/veeracs/.bower/cache/angular-resource/8af0e3f889969e27f60f8957c51eb157
bower copying /Users/veeracs/.bower/cache/angular/683afc7e2aea6bbad5baa3ce1e59216d
bower copying /Users/veeracs/.bower/cache/angular-sanitize/18d349fe4790f6955714758e794cef93
bower extracting /var/folders/82/7lp6vbz53fq_mjq484ys62w00000gn/T/bower-bootstrap-159832mmtf8w/index.zip
bower copying /Users/veeracs/.bower/cache/angular-mocks/bd33066d85506b0788f38febe91d06b6
bower copying /Users/veeracs/.bower/cache/jquery/cf68c4c4e7507c8d20fee7b5f26709d9
bower checking out modernizr#v2.6.2
bower copying /Users/veeracs/.bower/cache/requirejs/5ca1099b5f0eab07b04b080835510df1
bower copying /Users/veeracs/.bower/cache/modernizr/9e3143e153f397b3c7d7da78376adc78
bower cloning git://github.com/angular/bower-angular.git
bower cached git://github.com/angular/bower-angular.git
bower fetching angular
bower checking out angular#v1.0.6
bower copying /Users/veeracs/.bower/cache/angular/683afc7e2aea6bbad5baa3ce1e59216d

Thanks
Chandra

**Comment by jibiabraham** [comment]
My two cents.
Running OSX 10.10.1 on a 2014 Macbook Pro.
Nodejs 0.10.33
Bower 1.3.12

I had the issue where bower would run and show me the cached, validating, downloading, etc messages on the console, but the bower_components folder would never be created.

For me the issue was because for some reason usr ▸ local ▸ lib ▸ node_modules ▸ bower 's permissions were changed to 'nobody'. I reset the permissions to my user and things just started working again.

For anyone who wants to try this and is unfamiliar with setting permissions on a mac, http://superuser.com/questions/52598/how-to-recursively-change-sharing-permission-of-a-folder-in-mac-os-x

**Comment by hokkoo** [comment]
@funkybob,Hi,I have same question,but I can't get install without any log information.The 'bower list' command show a strange information:
![azz0j w uns7w lsg2pey0](https://cloud.githubusercontent.com/assets/4771449/8514495/545e9558-23c3-11e5-8870-09c15da50cf1.png)
Can you help me,thanks a lot.

**Comment by funkybob** [comment]
@hokkoo not sure how I can help... I had an old, broken version... I got rid of it, and everything "just worked".

**Comment by kinzhao** [comment]
If you can do `bower` and see the list of commands, options and still don't see anything after doing a bower install, it's possible, that you already have bower installed. You can test this by renaming the bower_components to another name and doing a `bower install`. It should work. If not, it could be a corporate proxy issue.

**Comment by mlent** [comment]
For those searching:

My issue was that I had deleted the `bower_components` directory. As soon as I made a new directory for `bower_components` and re-ran the install command, everything went in successful. Maybe just a permissions issue.

**Comment by akjoshi** [comment]
I had the same issue. I passed one of the libraries in the command and it worked fine.

$ bower install jquery --save 
This installed all libraries listed in bower.json.  
Note: jquery was also listed in bower.json

**Comment by hafsteinn** [comment]
my problem was that "dependencies" in bower.json was written with a capital D (e.g. Dependencies) ... changed to lower-case and now everything works!

**Comment by superveetz** [comment]
`sudo bower install --allow-root` did it for me
