### ISSUE TITLE
Is it possible to bypass CERT_UNTRUSTED issue?

### ISSUE THREAD

**Issue by fpetitit** [bower/bower#419]
Hello,
the proxy of my company transforms certificates, which brings "CERT_UNTRUSTED" errors.
Is it possible to add an option to Bower to continue in spite of this?

Thank you.

**Comment by artofthem** [comment]
+1 @hypery2k. Thanks

**Comment by ktal90** [comment]
This is still an issue for me. I need to use custom CA certs to be able to verify SSL for bower. I have gotten it to work with npm and other repository managers that allow CA definition. It appears that bower is not taking the config file nor command line options for defining the CA to be used and ends up rejecting on CERT_UNTRUSTED.

**Comment by joshstrange** [comment]
I am not aware of my company MitM-ing our connections but we have to use the .bowerrc file listed above to get it to work on some of our machines. Most of the dev boxes don't seem to have this issue but our servers do. I'm still a little confused to why github seems to be having this issue. I've read through the above comments but I can't imagine why github, of all places, would have HTTPS issues with bower....

**Comment by Splaktar** [comment]
My company just put a MitM proxy on us as well and we're hitting this now. The `.bowerrc` file mentioned above does seem to fix it though. Thank you.

**Comment by ktal90** [comment]
By "fix", you mean "workaround" right? The workarounds above suppress SSL checking. The true fix would be for the bower config file's `ca` and command line's `--config.ca` to actually recognize the CA that I would like to point to. bower's doucmentation claims that it does this, but it does not.

**Comment by Splaktar** [comment]
Yes, I've updated my comment. We've 'fixed' the problem now by getting IT to take this network off of their proxy list. So we are no longer going through the MitM proxy and have removed the disabling of SSL checking.

**Comment by francois-montmasson-efg** [comment]
Even add ca in .bowerrc do not solve the issue. 
Configuration seems simply ignored... or not enough in order to have bower believing in this certificate.

Please reopen. strict-ssl false is wrong way to fix. It's unsecure.

**Comment by sheerun** [comment]
PR with fix is welcome

**Comment by tloebermannvw** [comment]
I need a fix too. Its not possible to add a certificate to bower!

**Comment by adriaanthomas** [comment]
Given that Bower uses `request`, looking at the [documentation](https://github.com/request/request#tlsssl-protocol), it seems that the `ca` option should contain the contents of the certificate file, not a path to it. If I modify my `.bowerrc` to contain the full certificate contents (with newlines, `BEGIN` and `END CERTIFICATE` and all), registry lookups now work.

As for pulling in tar balls, there are still issues, in our case because `GitHubResolver` [does not pass the ca option](https://github.com/bower/bower/blob/master/lib/core/resolvers/GitHubResolver.js#L74). Adding the `ca` option there makes Bower work for us behind the proxy with its custom root CA and `strict-ssl` enabled.

I would be happy to issue a pull request, but how should this work? I assume the `ca` option in `.bowerrc` should be a path to a file? How do people use this currently?

**Comment by john-jay** [comment]
I got bower to work by using this command:

git config http.sslVerify "false"

**Comment by adriaanthomas** [comment]
As [mentioned](#issuecomment-85091976) [above](#issuecomment-93410970) that's only a workaround.

For anyone else working from behind a proxy with its own root CA, these are our settings (setting `strict-ssl` to `true` just to make clear what works, this should be the default everywhere):

#### Certificate file

Export your company's root CA certificate to some location on your local file system, `CA_FILE`. You can also append it to some existing CA bundle file, `CA_BUNDLE`.

We use the `HTTPS_PROXY` environment variable for the proxy config, including user credentials.

#### npm

Strictly not linked to bower, but as you will probably use this too:

```sh
npm config set --global cafile $CA_FILE
npm config set --global strict-ssl true
```

Not everything works 100% but there are no blocking issues here.

#### bower

In `~/.bowerrc` we have:

```json
{
  "strict-ssl": false
}
```

After something like #1869 we can make this (truncated certificate contents):

```json
{
  "strict-ssl": true,
  "ca": "-----BEGIN CERTIFICATE-----\nkjhDKUFKJS...jfdhH==\n-----END CERTIFICATE-----\n"
}
```

And then after bower/config#28 we can make it (using the actual value of `$CA_FILE` or `$CA_BUNDLE`):

```json
{
  "strict-ssl": true,
  "ca": "$CA_FILE"
}
```

#### git

```sh
git config --global http.sslverify true
git config --global url.https://.insteadOf git://
git config --global http.sslCAInfo $CA_BUNDLE
```

**Comment by sywesk** [comment]
Please add the "strict-ssl" configuration entry to the .bowerrc documentation ( http://bower.io/docs/config/ ). It solved my problem.

Thanks !

**Comment by jenny8993** [comment]
Thanks !
