### ISSUE TITLE
No output from bower command?

### ISSUE THREAD

**Issue by dmackerman** [bower/bower#432]
Hey there.

Just installed bower using `sudo npm install -g bower`. Everything seemed to complete fine, but when I run a `bower --help` or any bower command, nothing gets returned. Just makes a new line in the shell

npm version `1.2.17`
node version `v0.11.1-pre`

Here's an example if that helps at all:

![yes](http://dl.dropbox.com/u/68704/Screenshots/azmr.png)

**Comment by adityamenon** [comment]
Thanks @mlms13, that's the mistake I made too <facepalm> :D
