### ISSUE TITLE
Does having a component.json file not prevent an entire repo from being downloaded?

### ISSUE THREAD

**Issue by jcreamer898** [bower/bower#45]
Is there proper way to setup a bower install to use it with it's OWN repo? 

I was thinking that by merely including a component.json file in a repo that when running `bower install`, it would only actually install the things listed under `main` into my project.

But, it downloaded my entire github repository?

Is this the expected behavior, or did I do something wrong?

The package I uploaded is `postal`.

Thanks!

**Comment by troygrosfield** [comment]
Been sitting tight for ~1.5 years, now my butt hurts. :) Jk, but I am curious if any progress has been made?

**Comment by rquadling** [comment]
Does https://github.com/blittle/bower-installer help you. I use this to pull in about 20 different projects. I end up with a directory containing only the files I want (.js, .less) and from there, I use grunt to package them all up into a single js and css file. YMMV.

**Comment by troygrosfield** [comment]
It took a bit to get the config correct, but eventually got bower-installer to work for my case (for the most part).  

However, there are parts of bower-installer that feels like a "one size fits all" type of solution which doesn't work for every repo. 

For example, you can define certain files go to certain paths ``"png": "path/to/img"``which works for the projects that have statics referencing the same folder structure, but unfortunately not all css files reference an image folder called "img" at the exact same relative path.

I know you can use glob wildcards on folders to maintain folder structure, but mixing and matching glob wildcards with path default directories didn't seem to jive well (hence the one size fits all comment). For that reason I had to still end up taking a few repos in their entirety.

 It would still love to see enhancements to native bower to address some of this.

FWIW, I'm using Django and static files management with django-pipeline.

**Comment by rquadling** [comment]
@troygrosfield, I do have an issue with bower-installer, but for the main, it works well. The one-size-fits-all is close, but/and you can/do need to tweak things a bit. Similar to composer.json in some ways.

But neither bower nor composer handles the things that bower-installer does, and I've raised that issue with composer too.

**Comment by AlastairTaft** [comment]
+1 Installing the entire repository instead of what's specified in main seems counter intuitive to me. Will use just npm with an install script instead.
