### ISSUE TITLE
Always get connection reset (ECONNRESET) error

### ISSUE THREAD

**Issue by caarlos0** [bower/bower#467]
Don't matter what command I try, I always got this same error with bower:

```
$ bower search angular 
bower error tunneling socket could not be established, cause=read ECONNRESET
```

I didn't found bower logs (perhaps I looked in the wrong place), so, I don't have any idea about why am I getting this error.

I'm behind a proxy (cntlm), which is exported in my ENV. `npm` works as expected. Just `bower` don't.

Info:

```
$ env | grep -i proxy
socks_proxy=socks://127.0.0.1:8010/
http_proxy=http://127.0.0.1:3128/
https_proxy=https://127.0.0.1:3128/
ftp_proxy=ftp://127.0.0.1:3128/

$ bower -v
0.9.2

$ npm -v
1.2.18

$ node -v
v0.10.5
```

OS is an Ubuntu Linux.

If I could give any more info, please ask. I'll be glad to help.

Cheers.

**Comment by sanjeevsuresh** [comment]
@nanowizard Adding HTTP_PROXY and HTTPS_PROXY env variables worked for me on Windows 7. Thanks!

**Comment by ppaul** [comment]
I don't know what I am missing here, but when I try to scaffold  'yo gulp-angular', .bowerrc always gets overwritten. It asks me in the beginning about the conflict, but then overwrites it no matter what I choose. Please help

**Comment by antoniomtz** [comment]
I solved it by using Git bash cmd on windows and adding:
export http_proxy="yourproxy:port"

**Comment by bownie** [comment]
Adding the registry entry in addition to the proxies led to less failures and eventually working so many thanks @gaving

**Comment by Wasmoo** [comment]
At my company, we the retry every now and then, and I have no idea why. It seems to go away after an hour. I'm not sure if it's our side or theirs.

**Comment by rana22** [comment]
@gaving Thanks

**Comment by emrecamasuvi** [comment]
thnx @thebignet adding strictssl(false) to related .bowerrc file solved my problem.
proxy and https-proxy definitions also exist in .npmrc .gitconfig and .bowerrc files too.

**Comment by RupenAnjaria** [comment]
Where is the .bowerrc file? and what is the exact name of it? (is it just ".bowerrc" or something like "bower.bowerrc"?

**Comment by kthejoker** [comment]
File name is just ".bowerrc"

Here's documentation on the file's contents and how bower loads it:

http://bower.io/docs/config/

The no-muss no-fuss method is to just put it in the |path to bower|/config
folder

Here's the priority bower uses to find your config file:

   - CLI arguments via --config
   - Environment variables
   - Local .bowerrc located in the current working directory
   - All .bowerrc files upwards the directory tree
   - .bowerrc file located in user’s home folder (~)
   - .bowerrc file located in the global folder (/)

**Comment by ARUNMOHANRAJ471** [comment]
Thanks @thebignet .. it worked
