### ISSUE TITLE
Bower doesn't react

### ISSUE THREAD

**Issue by aminalhazwani** [bower/bower#475]
$ bower gives as output nothing, just a new command line ready for a new input.
$ bower -help, $ bower install, nothing. there are no outputs. 

I've installed bower through $ sudo npm install -g bower. 
I can see it in the folder trough $ ls -la, but nothing happen when I try to run it.

It appears just a new empty command line.

**Comment by liadlivnat** [comment]
I removed bower manually, after uninstalling and reinstalling several times
bower command are not reacting, still get nothing when i try to run bower --version
bower install.

Any idea what to do? 
I'm running on ubuntu

**Comment by pheaver** [comment]
I'm on ubuntu and observing the same behavior. Have removed and reinstalled bower using npm, with no luck.

**Comment by diokey** [comment]
One Ubuntu there is a program called node which is NOT node.js. Make sure you have node.js and not node. Also make sure to remove node, if it exists it may confuse bower where to look for node.js binary.

Start by removing node 

``sudo apt-get autoremove node``

and install node.js. I recommend install node.js using nvm https://github.com/creationix/nvm

**Comment by pheaver** [comment]
Yup, that was the problem, thanks!

**Comment by liadlivnat** [comment]
worked for me to!!

Liad Livnat.

W: http://liadlivnat.com
IN: http://linkedin.com/in/liadl
F:https://www.facebook.com/liad.livnat
T: 054-4302040

**Comment by jimbasilio** [comment]
Also, if the autoremove doesn't fully fix it .. ubuntu packages don't always link 'node' to 'nodejs'. You can manually create this link if you are getting a '/usr/bin/env: node: No such file or directory' error. Run 'sudo ln -s /usr/bin/nodejs /usr/bin/node' and it'll create a link to the nodejs app which will then allow bower to run. I don't understand the packaging issues .. but I'm moving on from it.

I had to add the symlink as well as the autoremove.

**Comment by DiegoYungh** [comment]
Ubuntu 15 vivid
I had to remove node package and add the symlink to nodejs manually

**Comment by undersky0** [comment]
Has anyone found a way around this on Mac ? I still have the same problem, none of the suggestions worked ;/

**Comment by ondrejd** [comment]
I just have this problem on freshly installed Ubuntu 15.04. I installed Node and Npm with:

```
sudo apt-get install node npm
```

Then:

```
sudo npm install -g bower
```

And bower does nothing. Than I tried the re-installation with clearing cashe as is suggested above but with no positive result.

Node.js version is 0.10.25
Npm version is 1.4.21

**Comment by jordanmack** [comment]
I had the same problem on Ubuntu 14.04.3 Desktop. I was receiving the error `/usr/bin/env: node: No such file or directory` @jimbasilio's suggestion worked for me: `ln -s /usr/bin/nodejs /usr/bin/node`

**Comment by artem328** [comment]
Reinstall nodejs-legacy was helpfull for me. Ubuntu 14.04

**Comment by chrispauley** [comment]
Issue seems unresoloved:

macOS 10.12
npm -v && node -v && bower -v
3.7.3
v5.8.0
1.7.9

bower install 
<no response>

bower reinstall, same issue.

Manually deleting bower, then reinstalling... same issue

One would hope that re-installing would work!
