### ISSUE TITLE
Git status: 128

### ISSUE THREAD

**Issue by D3CK3R** [bower/bower#50]
Hey guys,
just registered a new package a few minutes ago.
When i want to install it, i'm getting an error "Git status: 128"

The package is 'underscore.string':
git://github.com/epeli/underscore.string.git

The solution in issue #32 doesn't work for me.

Could you help with this?
Thanks in advance!

**Comment by TormodHystad** [comment]
Make sure "telnet github.com 9418" from a command prompt works, if it doesn't, you have firewall issues. (I got the code 128 error on Windows, because of a corporate firewall)

**Comment by AntonMaltsev** [comment]
Thanks! Tip below helped! BTW not only on Mac, I'm on Windows

#mac only
rm -rf ~/.bower

**Comment by thiagocavaloti** [comment]
like @renjithvincent said, git config --global url."https://".insteadOf git://
works for me too :+1:

**Comment by hiteshmodha** [comment]
thanks @renjithvincent, `git config --global url."https://".insteadOf git://`  worked for me

**Comment by chotkos** [comment]
Thanks, this helped me :)

**Comment by maboiteaspam** [comment]
faced the problem a moment ago, 

```bower -v 1.4.1```

I was trying to install the module from a public github repo with 
`bower i maboiteaspam/grunt-vid2pict --save` 

Even i m the owner, i got 
`ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/maboiteaspam/grunt-vid2pic.git", exit code of #128 fatal: remote error:    Repository not found.`
(this cmd never worked for me, btw)

I had to change for explicit http 
`bower i https://github.com/maboiteaspam/grunt-vid2pict.git --save`

The module would install.

I also tried `bower cache clean` before, but that did not help.

Maybe i did something wrong, only sharing.

**Comment by esoyke** [comment]
Maybe this will help someone someday, but also be sure you aren't simply using an old version of bower. I tried every solution here plus adding "strict-ssl": false, "https-proxy": "" to the .bowerrc, with no dice. Then I noticed the Windows box I had recently switched over to was running bower 1.4.1. Upgrading to 1.7.9 resolved it.

**Comment by vkjangra1209** [comment]
git config --global url."https://".insteadOf git:// worked for me. thnx

**Comment by pik** [comment]
Same issue here, I'd like to note that e.g. `git ls-remote git@github.com:User/a_private_repo.git` resolves correctly even though the bower `git ls-remote git://github.com/User/private_repo` does not? Is this a git issue or the way bower is expanding the urls ?

**Comment by venkatav** [comment]
after git config --global url."https://".insteadOf git:// this git push is not working for me.
