### ISSUE TITLE
Show last version available in "bower search"

### ISSUE THREAD

**Issue by chikamichi** [bower/bower#518]
Hi, feature request ahead:

> As a Bower user using the search command,
> In order to move faster and code more,
> I would like Bower to display the last available version.

Use case: I want to quickly add the uri.js dependency in my project. I don't mind the version, I just want the latest available. I type in:

    $ bower search uri
    
    Search results:
    
        uri.js git://github.com/medialize/URI.js.git (v1.10.2)
        curist/grunt-bower git://github.com/curist/grunt-bower (0.2.3)
        tourist git://github.com/easelinc/tourist.git (0.0.11)

Since I already got the last version number, I can skip `bower info uri.js` and edit my `bower.json`, then install it in a flash.

**Comment by sheerun** [comment]
We probably won't upgrade registry to do it, and this feature has doubtful usability. It can be replaced by either `bower install components --save` or `bower info component`
