### ISSUE TITLE
Integration bower install with Jenkins

### ISSUE THREAD

**Issue by thomaspons** [bower/bower#525]
The integration with Jenkins doesn't work : error code 128 !!

And the https hack doesn't work too ...

Any idea ?

Thx to you,

Tom

**Comment by allwinac** [comment]
It is been a very long time. but when I check this issue there is no solution given  for Jenkins on windows.  In my case I have Jenkins and Jenkins Slave installed on Windows Servers. I get the same issue with bower install
bower install jquery 
bower jquery#*              not-cached git://github.com/jquery/jquery-dist.git#*
bower jquery#*                 resolve git://github.com/jquery/jquery-dist.git#*
bower jquery#*                 ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/jquery/jquery-dist.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: *.*.*.*]: errno=No such file or directory

What I did to resolve, is the same solution that is given as resolution  for #128.
git config --global url."https://".insteadOf git://

Only thing is I add this line before calling bower restore!. In my case I use, NPM, Gulp, bower integrated with visual studio MSBuild. So I added the above config command before calling MBbuild Rebuild.

This may not be the right solution. I am just a beginner. advice if there is anything other good solution. 
Thanks
