### ISSUE TITLE
Bower always throws an exception when run in an environment without HOME env variable

### ISSUE THREAD

**Issue by jvandesande** [bower/bower#558]
Bower always throws the following error when the environment variable HOME is not set (we're running CentOS). 

``` bash
path.js:360
        throw new TypeError('Arguments to path.join must be strings');
              ^
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at Object.<anonymous> (/usr/lib/node_modules/bower/node_modules/update-notifier/node_modules/configstore/configstore.js:9:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

We run bower from php (in apache) where no HOME variable is not set.

You can reproduce this using the following shell commands:

``` bash
env -i /bin/bash
/usr/bin/bower
```

It looks like this bug is introduced with the addition of the update notifier (#202), is it possible to run bower without using the update notifier?

**Comment by jweyrich** [comment]
I just ran into this issue using Bower 1.3.12. According to my tests ([see here](https://gist.github.com/jweyrich/b045afd29b6530c14518)), the problem happens only when both $HOME and $USERNAME are not set. Can anyone reproduce? Maybe I should open a new issue.

**Comment by vjpr** [comment]
> I suggest you just define HOME to the empty string.

Bower gets user home dir from [user-home](https://github.com/sindresorhus/user-home/blob/master/index.js) module.If `HOME` is set to empty string it will return null. See the module source in the link.

On ElasticBeanstalk Bower will fail to run and produce this error unless you pass `HOME=/root` before your `bower install` command.

**Comment by ddagone** [comment]
Hi, where can I find the `.bowerrc` file ?
