### ISSUE TITLE
Detect when there is no internet connection and auto-enable offline mode

### ISSUE THREAD

**Issue by sindresorhus** [bower/bower#572]
In the rewrite you can pass in `--offline` to have it work without using net. Would be sweet if it were smart enough to detect if internet was unavailable and auto-enable the offline. This should come with a info message that it's being activated and how to override. User can override with either `--no-offline` or `offline`.

**Comment by maxfurman** [comment]
Is this issue still valid? If so, I can take it; if not, it should probably be closed.

**Comment by sheerun** [comment]
The solution seems to be `bower install || bower install --offline`
