### ISSUE TITLE
Different renderer for install and update commands

### ISSUE THREAD

**Issue by satazor** [bower/bower#637]
I had this crazy idea when I was thinking about how bower output would look like in the rewrite. The initial idea was to use https://github.com/chjj/blessed to render a progress bar and state for each dependency. But I ended up implementing a multiple render mechanism, with a simple default renderer.

Though, this architecture allows us to easily implement new renderers. So what if we implemented the original idea as a new renderer that would be used for the `install` and `update` commands?

**Comment by sheerun** [comment]
Not enough time to implement
