### ISSUE TITLE
Config flag to always use a certain protocol (e.g. https)

### ISSUE THREAD

**Issue by jaramir** [bower/bower#656]
Hello

It would be useful for me to be able to use bower with git via http but I can't use the workaround since I'd have to modify the config  for the entire CI environment and we have a mixture of git and http access (we build from a mirror not straight from github)

My idea would be to recognize this by the fact that an http:// url ends with ".git"

It should not impact the other http use cases as far as I understand them but let me know if you think it would

I'm willing to dedicate some time to get this done and merged but I have no experience with the code base: suggestions welcome

Kind Regards

**Comment by sheerun** [comment]
This can be implemented using [Pluggable Resolver](http://bower.io/docs/pluggable-resolvers/)'s `locate` method.
