### ISSUE TITLE
"ignore" array in bower.json does not remove or ignore anything

### ISSUE THREAD

**Issue by happypoulp** [bower/bower#663]
Hi,

I tried the "ignore" option in bower.json with default parameters provided by a "bower init" command and it doesn't remove/ignore files and directory as it should.

Here is my bower.json config:

``` json
{
  "name": "bower_test",
  "version": "1.0.0",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "pickadate": "git://github.com/amsul/pickadate.js.git#3.1.3"
  }
}

```

and after running a "bower install" command, here is the content of my bower_components/pickadate folder:

```
CHANGELOG.md           Gruntfile.js           README.md              api.htm                demo/                  lib/                   pickadate.jquery.json  time.htm
CONTRIBUTING.md        LICENSE.md             _raw/                  date.htm               index.htm              package.json           tests/                 v2/
```

and as you can see the pickadate folder still contain "tests" folder that should be ignored thanks to "ignore" array in my bower.json.

Am I missing / misunderstanding / misusing something?

I also tried to add "pickadate/tests", "pickadate/tests/*" and many more combination and none seems to have any impact on the content of my bower's pickadate folder.

Tested with:

node v0.10.15 + bower v1.0.0
and
node v0.8.12 + bower v0.8.5

**Comment by jacobtomlinson** [comment]
Agreed this wasn't obvious to me either!

**Comment by HammadTheBoss** [comment]
It should work in the supposed way, i.e. ignore the folders or files from the downloaded packages as well....

**Comment by R4YM3** [comment]
wasn't clear to me either, thought exactly the same..

**Comment by anant-svc** [comment]
I know this is very old issue. But if the installing package bower.json does not have ignore then bower should check my bower.json file for ignore list.
