### ISSUE TITLE
No AX.25 port data configured

### ISSUE THREAD

**Issue by CoStiC** [bower/bower#677]
Hi,

I'm not sure that bower is the problem, but each time I try to launch it, i get this message in the syslog.

for information :
npm -v
1.3.5
nodejs -v
v0.10.15

regards,

**Comment by yaleman** [comment]
You're probably installing and running the [node](https://packages.debian.org/wheezy/node) package which is an amateur radio related tool - I had this issue installing node-red.

Try this to fix it:

> sudo ln -s /usr/bin/nodejs /usr/bin/node
