### ISSUE TITLE
Packages will not install in version 1.0.3 on Windows

### ISSUE THREAD

**Issue by jcreamer898** [bower/bower#701]
I just upgraded to 1.0.3 and am unable to install any components. They all throw an error that says...

```
EINVRES Response of request to ... is not a valid json
```

![](https://www.evernote.com/shard/s43/sh/fac16bbb-71c0-46f4-81cc-a39b658f713a/5de818c236c96db76d4bd57e8ba1a645/res/8c1500a7-749c-4dda-bb01-5de8ee89103f/ScreenClip.png?resizeSmall&width=832])

**Comment by mgmoonlight** [comment]
"bower install" was enough for me (didn't need to uninstall it)
