### ISSUE TITLE
Make name optional in bower.json

### ISSUE THREAD

**Issue by cowboy** [bower/bower#706]
I'm not sure if any other published-package-centric fields are required in bower.json, but at the very minimum, the `name` field should be optional. The `name` field should, however, be required for publishing a package.

There was a (now resolved) issue isaacs/npm#914 to make name and version in `package.json` optional, because many projects that utilize npm are never published. They use npm modules solely as dev dependencies, and `package.json` solely as a place to store the list of dev dependencies.

**Comment by vsn4ik** [comment]
:+1: for add `private` option.

**Comment by sheerun** [comment]
I think it was implemented at some point
