### ISSUE TITLE
Getting random ECMDERR errors

### ISSUE THREAD

**Issue by robdodson** [bower/bower#713]
Working on the tests for grunt-bower-requirejs I'm seeing intermittent ECMDERR errors. If I rerun bower they go away. It's always on different files and I've run `bower cache clean` so I don't think that's the issue.

My `bower.json` looks like this:

```
{
  "name": "grunt-bower-requirejs",
  "version": "0.7.0",
  "private": true,
  "dependencies": {
    "jquery": "~1.10.0",
    "underscore": "~1.5.1",
    "requirejs": "~2.1.8",
    "respond": "~1.2.0",
    "anima": "~0.3.2",
    "typeahead.js": "~0.9.3",
    "json2": "*",
    "jquery-ui-touch-punch-amd": "0.1.0",
    "highstock": "~3.0.1"
  },
  "resolutions": {
    "jquery": "~1.10.0"
  }
}
```

Here's the output from a regular `bower install` executed from the command line.

```
bower cached        git://github.com/documentcloud/underscore.git#1.5.1
bower validate      1.5.1 against git://github.com/documentcloud/underscore.git#~1.5.1
bower cached        git://github.com/components/jquery.git#1.10.2
bower validate      1.10.2 against git://github.com/components/jquery.git#~1.10.0
bower cached        git://github.com/jrburke/requirejs.git#2.1.8
bower validate      2.1.8 against git://github.com/jrburke/requirejs.git#~2.1.8
bower cached        git://github.com/scottjehl/Respond.git#1.2.0
bower validate      1.2.0 against git://github.com/scottjehl/Respond.git#~1.2.0
bower cached        git://github.com/lvivski/anima.git#0.3.2
bower validate      0.3.2 against git://github.com/lvivski/anima.git#~0.3.2
bower cached        git://github.com/twitter/typeahead.js.git#0.9.3
bower validate      0.9.3 against git://github.com/twitter/typeahead.js.git#~0.9.3
bower cached        git://github.com/douglascrockford/JSON-js.git#e39db4b7e6
bower validate      e39db4b7e6 against git://github.com/douglascrockford/JSON-js.git#*
bower cached        git://github.com/GeneralElectric/jquery-ui-touch-punch.git#0.1.0
bower validate      0.1.0 against git://github.com/GeneralElectric/jquery-ui-touch-punch.git#0.1.0
bower cached        git://github.com/robdodson/highcharts.com.git#3.0.1
bower validate      3.0.1 against git://github.com/robdodson/highcharts.com.git#~3.0.1
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/documentcloud/underscore.git", exit code of #128
```

**Comment by amantur** [comment]
`git config --global url."https://".insteadOf git://` worked for me as well while installing **angular-seed**

**Comment by luhtonen** [comment]
I have no problems running `bower install` on my Macs at home, but I've found problems with `bower install` at the office. Apparently there is firewall, which blocks some ports. I have Windows 7 as native OS on my office laptop and I have Ubuntu 14.04 running on VirtualBox. I was able to solve problem with `bower install` on Ubuntu by configuring Git to use HTTPS instead of GIT protocol with the command given above: `git config --global url."https://".insteadOf git://` But this was not helping on Windows neither in normal Command Prompt nor in PowerShell

**Comment by artismarti** [comment]
@StakshiGarg Thanks! This helped after hours of frustration.

**Comment by ssabareesh** [comment]
@StakshiGarg Thanks a ton!! You saved my day!! :)

**Comment by gyver98** [comment]
I've encountered below error during scaffolding out angularjs app with yeoman.
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/angular/bower-angular.git", exit code of #128 fatal: unable to connect to g
ithub.com: github.com[0: 192.30.252.128]: errno=No error

Resolved the error with the command given above: git config --global url."https://".insteadOf git:// 
@StakshiGarg thanks

**Comment by faceleg** [comment]
Locking as the solution is identified above and we don't want excessive `+1` comments putting strain on contributors.
