### ISSUE TITLE
Bower install ETIMEDOUT bower download dependencies and bower retry the same dependencies

### ISSUE THREAD

**Issue by meganelp** [bower/bower#764]
Hello,

I want to use the ui-calendar module and I've a problem to install bower dependencies. 

In my Git console I execute "bower install" and I've this response: 
$ bower install
bower not-cached    https://github.com/angular/bower-angular/archive/1.0.7.zip#*

bower resolve       https://github.com/angular/bower-angular/archive/1.0.7.zip#*

bower not-cached    https://github.com/components/jquery/archive/v1.10.2.zip#*
bower resolve       https://github.com/components/jquery/archive/v1.10.2.zip#*
bower not-cached    https://github.com/components/jqueryui/archive/v1.10.2.zip#*

bower resolve       https://github.com/components/jqueryui/archive/v1.10.2.zip#*

bower not-cached    https://github.com/arshaw/fullcalendar-component/archive/v1.6.3.zip#*
bower resolve       https://github.com/arshaw/fullcalendar-component/archive/v1.6.3.zip#*
bower not-cached    https://github.com/angular/bower-angular-mocks/archive/v1.0.7.zip#*
bower resolve       https://github.com/angular/bower-angular-mocks/archive/v1.0.7.zip#*
bower not-cached    https://github.com/jozefizso/bower-bootstrap-css/archive/v2.3.1.zip#*
bower resolve       https://github.com/jozefizso/bower-bootstrap-css/archive/v2.3.1.zip#*
bower download      https://github.com/angular/bower-angular/archive/1.0.7.zip
bower download      https://github.com/components/jquery/archive/v1.10.2.zip
bower download      https://github.com/arshaw/fullcalendar-component/archive/v1.6.3.zip
bower download      https://github.com/jozefizso/bower-bootstrap-css/archive/v2.3.1.zip
bower download      https://github.com/angular/bower-angular-mocks/archive/v1.0.7.zip
bower download      https://github.com/components/jqueryui/archive/v1.10.2.zip

bower retry         Download of https://github.com/angular/bower-angular-mocks/archive/v1.0.7.zip failed with ETIMEDOUT, retrying in 1.4s
bower retry         Download of https://github.com/arshaw/fullcalendar-component/archive/v1.6.3.zip failed with ETIMEDOUT, retrying in 1.5s
bower retry         Download of https://github.com/angular/bower-angular/archive/1.0.7.zip failed with ETIMEDOUT, retrying in 1.9s
bower retry         Download of https://github.com/components/jquery/archive/v1.10.2.zip failed with ETIMEDOUT, retrying in 1.5s
bower retry         Download of https://github.com/jozefizso/bower-bootstrap-css/archive/v2.3.1.zip failed with ETIMEDOUT, retrying in 1.9s
bower retry         Download of https://github.com/components/jqueryui/archive/v1.10.2.zip failed with ETIMEDOUT, retrying in 1.0s
[....]
bower ETIMEDOUT     connect ETIMEDOUT

Stack trace:
Error: connect ETIMEDOUT
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete](net.js:892:19)

Console trace:
Trace
    at StandardRenderer.error (c:\Users\mlp\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:70:17)
    at Logger.updateNotifier.packageName (c:\Users\mlp\AppData\Roaming\npm\node_modules\bower\bin\bower:113:18)
    at Logger.EventEmitter.emit (events.js:95:17)
    at Logger.emit (c:\Users\mlp\AppData\Roaming\npm\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:39)
    at c:\Users\mlp\AppData\Roaming\npm\node_modules\bower\lib\commands\install.js:25:16
    at _rejected (c:\Users\mlp\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:713:24)
    at c:\Users\mlp\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:739:30
    at Promise.when (c:\Users\mlp\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:979:31)
    at Promise.promise.promiseDispatch (c:\Users\mlp\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:661:41)
    at c:\Users\mlp\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:543:44

System info:
Bower version: 1.1.1
Node version: 0.10.15
OS: Windows_NT 6.1.7601 x64

I executed before : git config --global url."https://".insteadOF git:// => doesn't work after this. 
{
  "name": "angular-ui-calendar",
  "version": "0.1.3",
  "description": "A complete AngularJS directive for the Arshaw FullCalendar.",
  "author": "https://github.com/angular-ui/ui-calendar/graphs/contributors",
  "license": "MIT",
  "homepage": "http://angular-ui.github.com",
  "main": "./ui-calendar.js",
  "ignore": [
    "*_/._",
    "node_modules",
    "bower_components",
    "test_",
    "demo_",
    "gruntFile.js",
    "package.json"
  ],
  "dependencies": {
    "angular": "git://github.com/angular/bower-angular.git#1.x",
    "jquery": "git://github.com/components/jquery.git#1.x",
    "jquery-ui": "git://github.com/components/jqueryui#1.10.2",
    "fullcalendar": "git://github.com/arshaw/fullcalendar-component.git#1.x"
  },
  "devDependencies": {
    "angular-mocks": "git://github.com/angular/bower-angular-mocks.git",
    "bootstrap-css": "git://github.com/jozefizso/bower-bootstrap-css.git#2.3.1"
  }
}

So I changed my bower.json for: 
  "dependencies": {
    "angular": "https://github.com/angular/bower-angular/archive/1.0.7.zip",
    "jquery": "https://github.com/components/jquery/archive/v1.10.2.zip",
    "jquery-ui": "https://github.com/components/jqueryui/archive/v1.10.2.zip",
    "fullcalendar": "https://github.com/arshaw/fullcalendar-component/archive/v1.6.3.zip"
  },
  "devDependencies": {
    "angular-mocks": "https://github.com/angular/bower-angular-mocks/archive/v1.0.7.zip",
    "bootstrap-css": "https://github.com/jozefizso/bower-bootstrap-css/archive/v2.3.1.zip"
  }

**Comment by amarraja123** [comment]
"https-proxy":"http://myproxy.com:8080",
"strict-ssl": false
This resolves the issue.
