### ISSUE TITLE
bower leaves /tmp/bower behind after 'bower install' causing permission problems

### ISSUE THREAD

**Issue by ghost** [bower/bower#766]
Bower leaves /tmp/bower after a 'bower install', owned by the current user. If a subsequent user attempts a 'bower install', they get a permission error as they cannot write to /tmp/bower. 

Ideally, bower should rmdir /tmp/bower on completion of a build. 
It would also be nice if it checked the ownership of /tmp/bower on an bower install, and either failed early or attempted to chown it (since the permissions of /tmp may allow this)

**Comment by luckylooke** [comment]
Bower version: 1.4.1, deleting ```~/.cache/bower``` worked. Thanks @GuyWithAfro!

**Comment by lokeshjain2008** [comment]
@luckylooke  Thanks

**Comment by thomcom** [comment]
I had a crusty ~/.cache/bower as well, with root ownership!  Removing that directory fixed me.
