### ISSUE TITLE
Verbose mode (-V) to be really verbose

### ISSUE THREAD

**Issue by hansgru** [bower/bower#780]
The verbose mode doesn't seem to help for many of the commands.

It would be really helpful if the `-V` parameter would have some effect even on commands like `search` and `info`.

**Comment by kand** [comment]
:+1: my bower is freezing on a step the output is exactly the same as without ```--verbose```, not very helpful.

**Comment by eppineda** [comment]
How many features are potentially affected by this enhancement request? Can this work be divided?

**Comment by sheerun** [comment]
I think it can but it's probably better if someone takes this task, sugars `logger.debug` all over the place, and submits a PR :)

**Comment by thinkxl** [comment]
is this a WIP? cc @pertrai1

**Comment by pertrai1** [comment]
@thinkxl Not at this time on my end

**Comment by thinkxl** [comment]
@pertrai1 cool, thanks for the quick reply

**Comment by suriyanath** [comment]
Any updates here? It would also be great if there are time stamp for the logs.

Right now what I see with bower install -V is as below,
bower angular-route#^1.5.0                               not-cached art://angular/bower-angular-route#^1.5.0
bower angular-route#^1.5.0                                  resolve art://angular/bower-angular-route#^1.5.0
bower angular-sanitize#^1.5.0                            not-cached art://angular/bower-angular-sanitize#^1.5.0
bower angular-sanitize#^1.5.0                               resolve art://angular/bower-angular-sanitize#^1.5.0
bower angular-touch#^1.5.0                               not-cached art://angular/bower-angular-touch#^1.5.0
bower angular-touch#^1.5.0                                  resolve art://angular/bower-angular-touch#^1.5.0
bower angular-cookies#~1.5.0                             not-cached art://angular/bower-angular-cookies#~1.5.0
bower angular-cookies#~1.5.0                                resolve art://angular/bower-angular-cookies#~1.5.0
bower angularjs-imageupload-directive#*                  not-cached art://Mischi/angularjs-imageupload-directive#*
bower angularjs-imageupload-directive#*                     resolve art://Mischi/angularjs-imageupload-directive#*


What I expect is the time taken to install each bower component, typically like below,
01:15 bower angular-route#^1.5.0                               not-cached art://angular/bower-angular-route#^1.5.0
01:16 bower angular-route#^1.5.0                                  resolve art://angular/bower-angular-route#^1.5.0

This would help us in finding the accurate timeout value to be set to .bowerrc

**Comment by sheerun** [comment]
Bower is deprecated and features like this one unfortunately won't be implemented
