### ISSUE TITLE
Error thrown at bower install

### ISSUE THREAD

**Issue by pavanik** [bower/bower#798]
Hi,
I'm getting the following error when installing bower.

bower extract json3# 3.2.4 archive.tar.gz
bower EPERM  EPERM , rename 'c:\users\pavani\AppData\Local\Temp\bower\json3-6492-3zOTLm'
     at StandardRenderer.error <c:\users\pavani\AppData\Raoming\npm\node-modules\bower\lib\renderers\StandardRenderer.js :70:17>
     at Logger.updateNotifier.packageName <c:\users\pavani\AppData\Raoming\npm\node-modules\bower\bin\bower: 113 :18>

can anyone please tell me why it was coming like that.

**Comment by sheerun** [comment]
If someone encounters this problem again, please create failing test. We have now Windows CI.

**Comment by RohanSakhale** [comment]
I still encounter this issue over Windows 8 and Antivirus installed is AVG, should I run the cmd using Administrator???

**Comment by TFA-WaqasBaig** [comment]
Hi,
I have tried every single command, but I'm getting same error. I'm using windows 7(x64).
Kindly there's anyone who can help me out to fix the error.

Regards,
Waqas

**Comment by sheerun** [comment]
We can help you if you can reproduce it on our AppVeyor CI tests for Windows.

**Comment by TFA-WaqasBaig** [comment]
When I execute graldew :<project>:bootRun --offline I got as under exception:

$ gradlew :vans-ui:bootRun
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\mbusa\vans\build.gradle' line: 3

* What went wrong:
A problem occurred evaluating root project 'vans'.
> Cannot resolve placeholder 'use.home' in value '${use.home}/.m2/repository'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.042 secs

Is there any help for this?
Should I need to paste build.gradle file here?

Regards,
Waqas

**Comment by feniixx** [comment]
I had same problem but I desactivated the antivirus **Bitdefender** and I could install the dependency.
