### ISSUE TITLE
Second round of init command improvements

### ISSUE THREAD

**Issue by satazor** [bower/bower#803]
- Should allow homepage in authors, e.g.: "John Doe <johndoe@email.com" (http://johndoe.com)
- Should allow reading authors as an array of objects (keeping the format!)
- Allow multiple licenses (one license should be a string, two or more should be an array)
- Ask for `repository` assuming a default from `git remotes`

The last item cannot be done until everyone agrees in adding that property in the google docs spec. Note that it might overlap with the goal of `location`, which was a property proposed by @necolas. Comment on that please.

**Comment by sheerun** [comment]
Bower is deprecated and we don't recommend creating new Bower packages anymore
