### ISSUE TITLE
Bower install does not pickup changes in private git repos

### ISSUE THREAD

**Issue by vladgurovich** [bower/bower#822]
When dealing with private repos specified in a bower.json file as follows:

``` javascript
"dependencies": {
  ...,
  "my_private_lib": "git@github.com:my_org/my_private_lib.git"
  }
```

Bower install would not pickup the changes to the repo and simply return.
As soon as i would modify 'my_private_lib' by specifying a particular branch, it would fetch them, but it would not fetch the latest changes in that branch after the initial fetch.
Please advise. This reduces viability of bower for management of internal/private libraries.

This issue was mentioned by @robdodson 7months ago:  
https://github.com/bower/bower/issues/107#issuecomment-12683200

**Comment by aramk** [comment]
It seems it also doesn't re-fetch if a hash is provided in the URL and later updated?
