### ISSUE TITLE
Feature discussion: Add a command to see an entire dependency tree for endpoints

### ISSUE THREAD

**Issue by NickHeiner** [bower/bower#823]
It would be nice if there was a command (maybe called `bower tree`) that let you see the entire dependency tree for a list of endpoints. ("If I were to `bower install` all these endpoints, what would get pulled down?") Ideally, it would contain information about incompatible dependencies as well.

This is basically `bower install` followed by `bower list`, but without actually installing anything. 

I hacked together my own implementation of this using `bower info`, fetching the dependencies for each endpoint, and traversing the tree that way. However, it feels redundant with essentially the same logic that lives in Bower. It would also be nice to know that I'm getting the canonical dependency information from Bower and there won't be subtle differences in how we're calculating it.

Some different use cases could be a tool that:
- Shows a d3 dependency graph for an endpoint or
- Determines if two projects can be on a page together or
- Installs all the dependencies for a set of projects, even if there are incompatibilities, without having to install the projects one at a time and thus redownload most dependencies multiple times

**Example**
For `bower tree foo#~1 quux#>=3`, the json response would look like:

``` json
[
  {
    "name": "foo",
    "version": "1.2.1",
    "dependencies": [{
        "name": "bar",
        "version": "0.4.0",
        "dependencies": []
    }]
  },
  {
    "name": "quux",
    "version": "3.1.0",
    "dependencies": [{
      "name": "bar",
      "version": "0.5.6",
      "dependencies": [{
        "name": "omg",
        "version": "9.8.2",
        "dependencies": []
      }]
    }]
  }
]
```

What do you think? I would be happy to submit a PR for this.

**Comment by ygayl** [comment]
@NickHeiner That was an interesting idea. Any news? Maybe I can help.

**Comment by sheerun** [comment]
Bower is depreacted and we don't implement new features like this one. We recommend switching to Yarn
