### ISSUE TITLE
"bower install jquery" downloads the official jQuery project rather than the shim project

### ISSUE THREAD

**Issue by pkorzeniewski** [bower/bower#859]
The official jQuery project doesn't contain build files (jquery.js and jquery.min.js), so I believe "jquery" component should point to the shim project rather than the official jQuery project. 

This is probably caused by the case-insensitivity, as "jquery" (shim project) and "jQuery" (official project) are both treated as the same project.

**Comment by artivilla99** [comment]
Is anyone else having this issue with outer.js and inner.js files not minifying?

**Comment by fjcero** [comment]
There is a way to solve this?
