### ISSUE TITLE
Ability to configure/perform sparse checkout

### ISSUE THREAD

**Issue by mgcrea** [bower/bower#863]
It's a pain to have to setup & maintain additional specific repositories for bower releases while they only often are just the contents of the `build`/`dist` folder.

Would be great if somehow we could configure our component in `bower.json` to specify which folder should be checked-out, for instance:

```
"sparse": ["dist"]
```

On install, bower would perform a [git sparse checkout](http://briancoyner.github.io/blog/2013/06/05/git-sparse-checkout/) of the selected paths.

**Comment by eduardoinnorway** [comment]
2 years later and this is still relevant. You as consumer wan't to decide what you want, and you as Author want to give them that freedom. I have for example an asset library that has a dist, and my consumers either want to use the LESS/SASS format or they just want CSS format that is in dist, they usally never want both. And now for me give this freedom of choice to users I have to have one repo with originals and one with dist ... So, this is still a very relevant issue as a propsal for better user experience.
