### ISSUE TITLE
ECONFLICT Unable to find suitable version for angular

### ISSUE THREAD

**Issue by zajca** [bower/bower#866]
Hi, 
I have strange problem with bower. 
On my PC I run bower install and on my server with same version of bower 1.2.6 I'm getting

```
bower angular#*                         validate 1.0.8 against git://github.com/angular/bower-angular.git#*
bower                                  ECONFLICT Unable to find suitable version for angular
```

I don't know what could cause this 
This is how my bower.json looks like.

```
{
  "name": "project",
  "version": "0.0.1",
  "devDependencies": {
    "angular": "~1.2.0-rc.2",
    "angular-mocks": "~1.2.0-rc.2",
    "bootstrap": "~2.3.2",
    "angular-bootstrap": "~0.5.0",
    "angular-ui-router": "~0.0.1",
    "angular-ui-utils": "~0.0.4",
    "angular-sanitize": "~1.2.0-rc.2",
    "angular-resource": "~1.2.0-rc.2",
    "angularytics":"0.2.2",
      "json2":"*",
    "underscore":"1.5.1",
    "restangular":"1.1.3",
    "tinymce": "git://github.com/jozzhart/tinymce.git#4.0.0"
  },
  "dependencies": {}
}
```

**Comment by crisu83** [comment]
@satazor thanks for the tip about prefix choices with ```!```. That solved my issue.

**Comment by 59naga** [comment]
+1

**Comment by megha-n-bodke** [comment]
Adding angular entry to "resolutions" in angular worked for me.
@robfletcher Thanks for  sharing solution!

**Comment by abhi80y** [comment]
It worked for me by making following changes in "bower.json":

"angular": "latest",
"angular-mocks": "latest",
"jquery": "latest",
"bootstrap": "latest"

there was a mismatch in the version updated and the version that I got from Git for "angular-phonecat"

**Comment by ykanzi** [comment]
add --force like this

>  bower install angular-route --force

**Comment by watonyweng** [comment]
Thank you for your answer at @ykanzi

**Comment by ferakpeter** [comment]
I had the same issue with a different setup: 
We have an Artifactory proxy that is accessing the public bower repository. So the chain goes like this: bower install -> bower-art-resolver -> artifactory -> bower public repo

The problem was the bower-art-resolver, after updating to the latest version the conflict was resolved.

**Comment by calcyu** [comment]
@ykanzi 3Q

**Comment by thinkMX** [comment]
I solved this error message by using the same version for angular and angular-route

"dependencies": {
    "bootstrap": "~3.3.5",
    "font-awesome": "~4.4.0",
    "angular": "~1.4.7",
    "angular-route": "~1.4.7"
  }

**Comment by abdouszn** [comment]
i have  some problem and i resolve it by adding : 
"resolutions": {
  "angular": "~1.2.0"
} 

in bower.json file
with ~1.2.0 is my version of angular , so you need to replace this by your angular version

**Comment by AAdewunmi** [comment]
Hi,
I'm having problems with bower. Can't seem to find a solution.

**1. Here is the error message:**

**$ bower install angular-route -S**
bower                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower angular-route#*           cached https://github.com/angular/bower-angular-route.git#1.6.4
bower angular-route#*         validate 1.6.4 against https://github.com/angular/bower-angular-route.git#*
bower angular#1.6.4             cached https://github.com/angular/bower-angular.git#1.6.4
bower angular#1.6.4           validate 1.6.4 against https://github.com/angular/bower-angular.git#1.6.4
**bower                        ECONFLICT Unable to find suitable version for angular**

**2. Injected "resolutions" into my project bower.json file** 
"dependencies": {
    "bootstrap": "~3.3.5",
    "font-awesome": "~4.4.0",
    "angular": "~1.4.7"
  },
    
  "resolutions": {
  "angular": "~1.4.7"
  }

**3. Still getting the same error:**
**bower                       ECONFLICT Unable to find suitable version for angular**

How can I resolve this problem?

Thanks

**Comment by gityoti** [comment]
don't use  command tool of git,  use cmd tool of PC.

 git error = bower    ECONFLICT Unable to find suitable version for xxx

**Comment by sonnysavage** [comment]
I had an issue like this due to running MinTTY on Windows 10 (Git Bash). This article explains why, and gives two different solutions: https://willi.am/blog/2016/08/08/docker-for-windows-interactive-sessions-in-mintty-git-bash/
