### ISSUE TITLE
bower couldnt install anything

### ISSUE THREAD

**Issue by lujiajing1126** [bower/bower#919]
when i ran 

```
bower install jquery --save
```

it command lines show errors:

```
bower ENORESTARGET Tag/branch master does not exist

Additional error details:
No tags found in git://......
No branches found in git://....
```

i installed msysgit and nodejs on win7
and use npm install -g bower to install bower

and i use

``` git
git clone git://github.com/components/jquery.git
```

to clone the repo, the result is sucess

SO i wonder if there exists bugs in this version of bower

**Comment by leonadler** [comment]
For those looking at this issue in the future (aka 2016+), the wiki entry is now under [Troubleshooting](https://github.com/bower/bower/wiki/Troubleshooting#how-can-i-use-bower-with-only-https-urls-and-not-git).
