### ISSUE TITLE
Mark Dependency as "Ignore", or "Already Satisfied"

### ISSUE THREAD

**Issue by CyborgMaster** [bower/bower#927]
It would be great if we could mark some dependencies as already resolved, already satisfied, don't install, ignore, etc.  

I'm currently working on a Rails project and am trying to use Bower to manage my front-end dependencies.  However some dependencies are better to pull in using gems instead of bower.  For example, `jquery-rails` is heavily integrated into Rails and some other gems expect jquery to be included in that fashion.  

I would be fine installing some packages with Bower and others in gems, except that some bower packages also list jquery as a dependency, so I am stuck with including jquery twice.  

I would like to be able to continue to include the jquery-rails gem and somehow tell bower to ignore the requirement of some of my dependencies to install the bower jquery package.

**Comment by armyofda12mnkeys** [comment]
is this in yet? Im using bower 1.4.1 on the Windows platform and when bower-installing international-phone-number, i tried putting below in the JSON and didnt work.
I have a newer and also customized version of that jquery plugin I would like to manually add to my index.html instead its still downloading into bower_components and getting autoinjected into bower:js/bower:css wired dependencies.
```
$bower install  international-phone-number -S

{
  ...

  "suppliedDependencies": {
    "intl-tel-input": true
  },
  ...
}
```

**Comment by sheerun** [comment]
Bower 1.6.2 supports `ignoredDependencies` in `.bowerrc`.
