### ISSUE TITLE
`main` property - showdown

### ISSUE THREAD

**Issue by wibblymat** [bower/bower#935]
We need to get this done. It's been more than half a year. Let's leave this for discussion and voting until the Bower meeting on the 3rd November (14 days). Then we should count up votes and pick a winner.

Resources:
- [Spec document](https://docs.google.com/a/wibbly.org.uk/document/d/1APq7oA9tNao1UYWyOm8dKqlRP2blVkROYLZ2fLIjtWc/edit)
- Previous related issues: #46, #59, #63, #110, #393, #263, #750

Contenders:

1. **single entry point** - A relative path to the single file that you include to load the component. Could be any file type.
2. **one-per-type array** - An array of file paths, only one per type (e.g. CSS, JS, image, etc.)
3. **array of everything** - An array of all of the paths you could possibly want to include to get everything. All types mixed together.
4. **type map** - An object with file types as keys. Values are either single paths (**4a**) or arrays of paths (**4b**)
5. **feature map** - An object with feature names as keys. Values could be any the above (**5a** - single paths, **5b** - array of paths, **5c** - type map)

Anywhere that there is an array we can obviously *optionally* allow a single string instead which means the same as a one-item array without introducing any ambiguity.

If you have a favorite option not listed here, let me know ASAP and I will include it.

//cc: @satazor @addyosmani @sindresorhus @paulirish @benschwarz @wycats @svnlto @desandro @necolas. Please ping anyone else who might have a strong opinion or interesting use-case.

**Comment by desandro** [comment]
I've opened bower/bower.json-spec#43 to implement sheerun's proposal and resolve this once and for all.
