### ISSUE TITLE
bower install does not install the correct version

### ISSUE THREAD

**Issue by johanneswuerbach** [bower/bower#939]
I changed the required version of ember from "~1.0.0" to "~1.1.0" to trigger an update of ember, but `bower install` doesn't upgrade the already installed ember. I would expect bower to install the latest ember 1.1.x like npm or bundler as ember 1.0.x doesn't match "~1.1.0".

Bower: 1.2.7
Node: v0.10.21

bower.json

``` json
{
  "name": "xy",
  "dependencies": {
    "ember": "~1.1.0"
  }
}
```

Reproduce by creating a bower.json, lock ember to ~1.0.0, run `bower install` and change the required version to ~1.1.0.

**Comment by blaise-io** [comment]
I'm also having this issue with Angular and UI Bootstrap. 
I switched to bower update because of it.
