### ISSUE TITLE
Forked Repository still tries to install from upstream

### ISSUE THREAD

**Issue by cam-stitt** [bower/bower#952]
I forked csshat/Lesshat to try and get around the installation issue mentioned in #948.

When I attempted to install from the fork, it actually just reverts back to trying to install from upstream:

```
bower install git@github.com:exitio/LESSHat.git
bower LESSHat#*             not-cached git@github.com:exitio/LESSHat.git#*
bower LESSHat#*                resolve git@github.com:exitio/LESSHat.git#*
bower lesshat#1.1.1         not-cached git://github.com/CSSHat/LESSHat.git#1.1.1
bower lesshat#1.1.1            resolve git://github.com/CSSHat/LESSHat.git#1.1.1
bower LESSHat#*               checkout v1.1.2
bower LESSHat#*               resolved git@github.com:exitio/LESSHat.git#1.1.2
bower lesshat#1.1.1            ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/CSSHat/LESSHat.git", exit code of #128

Additional error details:
fatal: remote error: 
  Repository not found.
```

Is there any reason why it is trying to resolve back to upstream?

**Comment by maxime1992** [comment]
I'm in the same situation. I have a fork of Bootstrap not made by me (so i can't modify it).
I need to install it via bower but it's installing the original Bootstrap.
How can i do ? 
@cam-stitt when you say "This issue was some time ago and was resolved anyway." you say how it has been resolved. Could you develop ? Thanks !

**Comment by saeidscorp** [comment]
@maxime1992 The only way I think of is to fork that repository yourself and change its `bower.json` file.
May be then you want to request a PR.
