### ISSUE TITLE
Wanted: `outdated` command

### ISSUE THREAD

**Issue by binarykitchen** [bower/bower#955]
Like npm does. For listing installed bower packages that are outdated. This to see if newer versions exist without really updating.

For development pretty useful to check for new stuff.

**Comment by niedzielski** [comment]
This works well but dependency listings are long. Is the canonical way to only list outdated packages to run `bower list|grep latest`?

**Comment by jaworskm** [comment]
bower list used to work for us, until we started using `shorthand_resolver` in our .bowerrc file. Now it just fails without applying the `shorthand_resolver`

**Comment by micky2be** [comment]
Would be nice to have a list of outdated dependencies like npm is doing

**Comment by AlbertoFdzM** [comment]
I'm using this package for this [`bower-outdated`](https://github.com/HugoCapocci/bower-outdated)
