### ISSUE TITLE
Permit comments in .bowerrc files

### ISSUE THREAD

**Issue by endorama** [bower/bower#966]
Hello, I'm starting to use bower and found a little issue: is not possible to add comments ( using // or /\* */ ) inside `.bowerrc` files.

Has a "newbie" with bower, I'd like to add some comments to explain some configuration, or to simply link to the documentation for configuration from the bower.io site.

Would be possible to enable comments inside this files? I tried to put a comment in a bower.json file and it worked, so I hope this could be an "easy fix" :)

Thanks for your work!

**Comment by skarllot** [comment]
You can duplicate keys, and parser take precedence to the last one:

```JSON
{
    "jQuery": "// My comment here",
    "jQuery": "latest"
}
```

**Comment by tnais** [comment]
Wonderful! I have to work within or without a proxy between me and the world. Comments should have been what's was going to solve the problem, as in several other configuration files. Maybe the choice of JSON has been the "choice of the man with the hammer".
