### ISSUE TITLE
bower ENOGIT        git is not installed or not in the PATH

### ISSUE THREAD

**Issue by sundyxfan** [bower/bower#972]
bower ENOGIT        git is not installed or not in the PATH

**Comment by aviv1ron1** [comment]
I also bumped into this on Windows. Had Git installed and on path and still Bower was unable to find it. Re installing git for windows from https://msysgit.github.io/ solved the problem

**Comment by RQuadling** [comment]
PICNIC.

**Comment by skfd** [comment]
It's wierd to depend on global Git. Is there a way to tell Bower which local Git  to use?

**Comment by pmualaba** [comment]
Just copy only the git.exe file from your msysgit (...\msysgit\bin\git.exe) or Cmder installataion directory ( ...\vendor\msysgit\bin\git.exe ) to C:\Windows\System32\git.exe. Solved the problem for me.

**Comment by romainlaisne** [comment]
Specifying the GIT path as proposed by saurabhkohli, directly from NodeJS command prompt, worked for me, I only had to add (x86) for the Program Files path. This is on a WINDOWS 7 Installation.

So, like this, in NODEJS command prompt:

set PATH=%PATH%;C:\Program Files (x86)\Git\bin;

**Comment by zishanj** [comment]
I was facing this same issue on my Ubuntu and I have installed `git`:

`sudo apt-get install git`

For windows users, they should visit this link to install `git`: https://msysgit.github.io/

**Comment by mufaddalmw** [comment]
I was facing same issue on windows 8.1. I was trying on "cmd command prompt" but when I tried same command in "git shell" above issue got resolve automatically.

**Comment by johnx7271** [comment]
I found that this is due to the way node deal with path. I used system internal to log the file access during "bower install xxx", and found the pattern: D:\path\to\currentdir\"C:\Program Files (x86)\Git\cmd"\git.exe, clearly incorrect,i.e. node should not prepend current dir to a path dir item.

**Comment by badisa** [comment]
I had to go into `/bower/lib/core/resolvers/GitResolver.js` and comment out the line that checks if Git is there to get this to work. It seems that the `which` module isn't working correctly for me.

Commented out line:
```
if (!hasGit) {
     throw createError('git is not installed or not in the PATH', 'ENOGIT');
}
```

**Comment by dev-mraj** [comment]
same problem...

in same script i used git commands and when it comes bower's turn
it got failed..saying that git not installed.

if i comment out above lines, works well for me as well..
what to do ?

Please reopen this.

**Comment by rquadling** [comment]
Each shell has it's own path. If you non Windows shell doesn't honour the Windows PATH, then the commands that are available from CMD will NOT be available from BASH.

If you are using Cygwin or some other unix toolset on Windows and the tools aren't configured in a Windows PATH, then the same issue.

Mixing shells (especially different OS shells), does need a bit of thought about where and how you install things.

**Comment by dev-mraj** [comment]
its simple linux, has no connection with windows..

**Comment by rquadling** [comment]
Can you create a docker setup that can reproduce this? (Docker is perfect for this sort of thing).

**Comment by rquadling** [comment]
> Its ubunto 16.04, running under non-root user in PHP-FPM process via php script exec commands.

Are you saying you are using a web server (apache, nginx, etc.) to run a PHP script that runs bower?

If so, can you replace the exec with something that can report the PATH? It may be that the user that is being used to execute PHP is using a different shell/path/config.

**Comment by airtonix** [comment]
Who even uses bower anymore... Really. I mean you already have npm
installed, any package you can't install with npm or doesn't provide a dist
build you'd just be loading via cdn anyway.

**Comment by mfaridzia** [comment]
You can install it using git bash

**Comment by rquadling** [comment]
With regard to

    Who even uses bower anymore... Really. I mean you already have npm
    installed, any package you can't install with npm or doesn't provide a dist
    build you'd just be loading via cdn anyway.

I'm a relative novice in the JS world (including node). I use bower, in conjunction with bower-installer to get a set of JS,CSS,HTML files from various sources and then use a grunt script to combine them into a single page app. 1 JS, 1 CSS and a minimal number of images. This app is then cached in our devices and allow for offline access.

Prior to the automation provided by bower and bower-installer, we had to manually copy files from manually expanded archives or manually download them from their associated repos, etc.

I'm not saying this is perfect, but I'd really like to know what alternatives exist that would allow me to manage packages in the same way. If I'm using a dead-horse and don't know it, then that would be good to know and to be able to move to a more "modern" approach. Of course, not broken, don't fix it comes to mind.

**Comment by galiazzi** [comment]
I solved using the following code in my php script

`putenv("PATH=/bin:/usr/sbin:/usr/local/bin:/usr/bin");`
