### ISSUE TITLE
Is there a way to check which files will end up in the package?

### ISSUE THREAD

**Issue by szimek** [bower/bower#986]
I had `package.json` file in my project and bower somehow used configuration from this file to set up package info. Now I'd like to add `bower.json` to be able to ignore some files/folders from Bower package. Is there a way to test the ignore option - e.g. get a list of all files that will end up in the package installed by the end user or create a package locally and just check what's inside?

**Comment by sheerun** [comment]
Bower is deprecated and we won't implement new features like this one. We recommend switching to yarn and migrating projects to it with https://github.com/sheerun/bower-away
