### ISSUE TITLE
Updating the revision behind a tag does not update the package on install / update

### ISSUE THREAD

**Issue by qraynaud** [bower/bower#994]
I'm having a repository that contains compiled versions of a library for numerous backends. To allow this, I'm using tags that are not semver (I don't think I have a choice here) like : <implemName>-v<semver> and one specific <implemName>-latest that resolves to the last uploaded version of the library.

I add in my bower.json : git@internal.github.fr:orgname/repository.git#implemName-latest. The problem I'm having is that bower install & bower update are not updating the package when I point the tag to a new commit in the repository.

I believe this is a problem that can either be fixed by updating the package when the commit hash changes.

It might also be a good idea to propose a scheme to prefix tags to allow for more complex tag naming.

**Comment by adjohnson916** [comment]
@sheerun, if you want examples, see: desandro/jquery-bridget#7 and jquery/jquery-mousewheel#143.
